(function(a){var g=window.kendo;
var j=g.ui;
var d=a.extend;
var b={wrapper:"RadSpreadsheet"};
d(true,j.Spreadsheet,{classNames:b});
var c={wrapper:"k-spreadsheet-filter-menu"};
d(true,g.spreadsheet.FilterMenu,{classNames:c});
var f={wrapper:"rssFormulaBar"};
a.extend(true,g.spreadsheet.FormulaBar,{classNames:f});
var e={wrapper:"rssFormulaInput",listWrapper:"rssFormulaList"};
a.extend(true,g.spreadsheet.FormulaInput,{classNames:e});
var i={sheetsBarWrapper:"k-widget k-header",sheetsBarSheetsWrapper:"t-tabstrip t-tabstrip-bottom",sheetsBarActive:"t-spreadsheet-sheets-bar-active",sheetsBarInactive:"t-spreadsheet-sheets-bar-inactive",sheetsBarAdd:"t-spreadsheet-sheets-bar-add",sheetsBarRemove:"t-spreadsheet-sheets-remove",sheetsBarItems:"t-spreadsheet-sheets-items",sheetsBarEditor:"t-spreadsheet-sheets-editor",sheetsBarScrollable:"k-spreadsheet-sheets-scrollable",sheetsBarNext:"t-spreadsheet-sheets-next",sheetsBarPrev:"t-spreadsheet-sheets-prev",sheetsBarKItem:"t-item t-state-default",sheetsBarKActive:"t-state-active k-state-tab-on-top",sheetsBarKTextbox:"t-textbox",sheetsBarKLink:"t-link",sheetsBarKIcon:"t-icon",sheetsBarKFontIcon:"t-font-icon",sheetsBarKButton:"t-button t-button-icon",sheetsBarKButtonBare:"t-button-bare",sheetsBarKArrowW:"t-i-arrow-w",sheetsBarKArrowE:"t-i-arrow-e",sheetsBarKReset:"t-reset t-tabstrip-items",sheetsBarKIconX:"t-i-x",sheetsBarKSprite:"t-sprite",sheetsBarKIconPlus:"t-i-plus",sheetsBarHintWrapper:"k-widget t-tabstrip t-tabstrip-bottom t-spreadsheet-sheets-items-hint",sheetsBarKResetItems:"t-reset t-tabstrip-items",sheetsBarHovered:"t-state-hover",sheetsBarKItemBase:"t-item"};
a.extend(true,g.spreadsheet.SheetsBar,{classNames:i});
var k={view:"rssView",fixedContainer:"rssFixedContainer",scroller:"rssScroller",viewSize:"rssViewSize",clipboard:"k-spreadsheet-clipboard",cellEditor:"rssCellEditor",barEditor:"k-spreadsheet-editor",topCorner:"rssTopCorner",filterHeadersWrapper:"k-filter-headers",filterButton:"k-spreadsheet-filter",icon:"k-icon k-font-icon",iconFilterDefault:"k-i-arrow-s",sheetsBar:"rssSheetsbar",sheetsBarActive:"k-spreadsheet-sheets-bar-active",sheetsBarInactive:"k-spreadsheet-sheets-bar-inactive",cellContextMenu:"k-spreadsheet-cell-context-menu",rowHeaderContextMenu:"k-spreadsheet-row-header-context-menu",colHeaderContextMenu:"k-spreadsheet-col-header-context-menu"};
a.extend(true,g.spreadsheet.View,{classNames:k});
var h={rowHeader:"rssRowHeader",columnHeader:"rssColumnHeader",pane:"rssPane",data:"rssData",mergedCell:"rssMergedCell",mergedCellsWrapper:"rssMergedCellsWrapper",activeCell:"rssActiveCell",selection:"rssSelection",selectionWrapper:"rssSelectionWrapper",single:"k-single",top:"k-top",right:"k-right",bottom:"k-bottom",left:"k-left",resizeHandle:"k-resize-handle",resizeHint:"k-resize-hint",resizeHintHandle:"k-resize-hint-handle",resizeHintMarker:"k-resize-hint-marker",resizeHintVertical:"k-resize-hint-vertical",selectionHighlight:"k-spreadsheet-selection-highlight",series:["k-series-a","k-series-b","k-series-c","k-series-d","k-series-e","k-series-f"]};
a.extend(true,g.spreadsheet.Pane,{classNames:h});
})($telerik.$);
(function(a,f){var d=12;
var c="Arial";
var b=Telerik.Web.UI;
kendo.spreadsheet.TabStrip=kendo.Observable.extend({init:function(g,h){this.element=g;
kendo.Observable.fn.init.call(this);
var i=g.parents(".RadSpreadsheet").find("[id$='SpreadsheetToolbarWrapper']");
a(g).append(i);
this._tabStrip=$find(i.children()[0].id);
this._initToolBars();
},select:function(){},quickAccessAdjust:function(){},refreshTools:function(j){var k=this.toolBars;
for(var h=0,g=k.length;
h<g;
h++){k[h].refreshTools(j);
}},destroy:function(){var j=this.toolBars;
for(var h=0,g=j.length;
h<g;
h++){j[h].destroy();
}this.element=null;
this._tabStrip=null;
this._toolBars=null;
},_initToolBars:function(){var k=this._tabStrip.get_tabs();
var n=this.toolBars=[];
var j;
var l;
var m;
for(var h=0,g=k.get_count();
h<g;
h++){j=k.getTab(h).get_pageView();
m=a(j.get_element()).find(".RadToolBar");
l=new e(m);
l.bind("action",a.proxy(this._triggerAction,this));
l.bind("dialog",a.proxy(this._triggerDialog,this));
l.bind("toolBarCommand",a.proxy(this._triggerCommand,this));
n.push(l);
}},_triggerAction:function(g){this.trigger("action",g);
},_triggerDialog:function(g){this.trigger("dialog",g);
},_triggerCommand:function(g){this.trigger("toolBarCommand",g);
}});
var e=kendo.Observable.extend({init:function(h){this.element=h;
kendo.Observable.fn.init.call(this);
this._borderType="allBorders";
this._borderColor="#000";
this._borderSize=1;
var n=this._toolbar=$find(h.attr("id"));
n._shouldUpdateClientState=false;
n.add_buttonClicked(a.proxy(this._onButtonClicked,this));
var l=n.get_items();
for(var j=0,m=l.get_count();
j<m;
j++){var k=l.getItem(j);
if(a(k.get_element()).hasClass("rtbTemplate")){var g=k.findControl(k.get_commandArgument());
if(b.RadComboBox&&g instanceof b.RadComboBox){g.add_selectedIndexChanged(a.proxy(this._onComboBoxSelectedIndexChanged,this));
}else{if(b.RadDropDownList&&g instanceof b.RadDropDownList){g.add_selectedIndexChanged(a.proxy(this._onDropDownListSelectedIndexChanged,this));
}else{if(b.RadColorPicker&&g instanceof b.RadColorPicker){g.add_colorChange(a.proxy(this._onColorPickerColorChanged,this));
}}}}else{if(k.get_attributes().getAttribute("gallery")==="true"){a(k.get_dropDownElement()).addClass("rssGallery");
}}}},refreshTools:function(m){var j=this._toolbar.get_items();
for(var g=0,k=j.get_count();
g<k;
g++){var h=j.getItem(g);
if(h instanceof b.RadToolBarDropDown){if(h.get_attributes().getAttribute("toggle")==="true"){this._setDropDownButtonValue(h,m);
}continue;
}if(h.get_isSeparator&&h.get_isSeparator()){continue;
}var l=h.get_commandArgument();
if(!l){continue;
}var n=kendo.isFunction(m[l])?m[l]():m;
this._suppressEvents=true;
this._setItemValue(h,n);
this._suppressEvents=false;
}},destroy:function(){this.element=null;
this._toolbar=null;
},_setItemValue:function(h,k){function j(l,m){if(m===null||m===true||m===false){l.set_checked(m);
return;
}l.set_checked(l.get_value()===m);
}if(a(h.get_element()).hasClass("rtbTemplate")){var g=h.findControl(h.get_commandArgument());
if(b.RadComboBox&&g instanceof b.RadComboBox){g.set_text(""+(kendo.parseInt(k)||d));
}else{if(b.RadDropDownList&&g instanceof b.RadDropDownList){var i=g.findItemByText(k);
if(i){i.select();
}else{g.findItemByText(c).select();
}}else{if(b.RadColorPicker&&g instanceof b.RadColorPicker){g.set_selectedColor(k);
}}}}else{j(h,k);
}},_setDropDownButtonValue:function(k,n){var h=k.get_buttons();
var g;
for(var j=0,l=h.get_count();
j<l;
j++){g=h.getButton(j);
var m=g.get_commandArgument();
if(!m){continue;
}var o=kendo.isFunction(n[m])?n[m]():n;
a(g.get_element()).toggleClass("rtbSelected",g.get_value()===o);
}},_onButtonClicked:function(i,g){var h=g.get_item();
var j=h.get_value();
if(j==="true"||j==="false"){j=h.get_checked()?true:null;
}this._triggerAction(h,j);
},_onComboBoxSelectedIndexChanged:function(i,g){var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=kendo.parseInt(i.get_selectedItem().get_text());
this._triggerAction(h,j);
},_onDropDownListSelectedIndexChanged:function(i,g){if(this._suppressEvents){return;
}var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=i.get_selectedItem().get_text();
this._triggerAction(h,j);
},_onColorPickerColorChanged:function(i,g){if(this._suppressEvents){return;
}var h=this._toolbar._extractItemFromDomElement(i.get_element());
var j=i.get_selectedColor();
this._triggerAction(h,j);
},_triggerAction:function(j,k){var i=j.get_commandName();
var h=j.get_commandArgument();
if(!i){return;
}if(i==="AdjustDecimalsCommand"){k=parseInt(k,10);
}if(i==="DialogCommand"){this.trigger("dialog",{name:h,options:{wrapper:this.element.parents(".RadSpreadsheet")}});
return;
}if(i==="ToolBarCommand"){this.trigger("toolBarCommand",{value:k});
return;
}if(i==="Action"){this.trigger("action",{action:k});
return;
}var g={command:i,options:{property:h||null,value:k||null}};
if(i==="SortCommand"){g.options.sheet=false;
}if(i==="BorderChangeCommand"){if(h=="borderColor"){this._borderColor=k;
}else{this._borderType=k;
}g.options={border:this._borderType,style:{color:this._borderColor,size:this._borderSize}};
}this.trigger("action",g);
}});
})($telerik.$);
(function(a,c){var b={CommandCut:"cut",CommandCopy:"copy",CommandPaste:"paste",CommandHideRow:"hide-row",CommandHideColumn:"hide-column",CommandDeleteRow:"delete-row",CommandDeleteColumn:"delete-column"};
kendo.spreadsheet.ContextMenu=kendo.Observable.extend({init:function(d,e){this.element=d;
d.hide();
kendo.Observable.fn.init.call(this);
},destroy:function(){this.element.remove();
this.element=null;
if(this._menu){this._menu.dispose();
this._menu=null;
}},open:function(d,e){if(this._menu){this._menu.showAt(d,e);
}},close:function(){if(this._menu){this._menu.hide();
}},_initContextMenu:function(d){if(!d){return;
}var e=this._menu=$find(a("[id$='"+d+"']").attr("id"));
if(e){e.add_itemClicked(a.proxy(this._onItemClick,this));
}},_onItemClick:function(i,g){var h=g.get_item();
var f=h.get_element();
var d=b[h.get_value()];
a(f).data("action",d);
var e={item:f};
this.trigger("select",e);
}});
})($telerik.$);
(function(a,m){Type.registerNamespace("Telerik.Web.UI.Spreadsheet");
var d=Telerik.Web.UI;
var g=".spreadsheetFilterMenu";
var n=".spreadsheetFilterMenuView";
var k="mouseenter";
var l="mouseleave";
var j="mousedown";
var e="click";
var i="input";
var h=kendo.spreadsheet.FilterMenuController;
var b=a.extend;
var c=a.proxy;
function f(o,p){return o===p||a.contains(o,p);
}kendo.spreadsheet.FilterMenu=kendo.Observable.extend({init:function(o,p){kendo.Observable.fn.init.call(this);
this.options=b(true,{},p);
this.container=o.parent();
this.element=this.container.find(".rssFilterMenu");
this.animationContainer=this.element.parents(".rssSlide")[0];
this._initDropDown(this.animationContainer);
this._initView();
this._initFilter();
},destroy:function(){this.close();
this.container.append(this.animationContainer);
this.animationContainer=this.element=this.container=null;
a(this._dropDown._animationContainer).attr("style","display: none;");
this._dropDown._animationContainer=null;
this._dropDown.dispose();
this._dropDown=null;
this._view.destroy();
this._view=null;
this.options={};
},openFor:function(o){this._dropDown.set_anchor(o);
this._dropDown.show();
a(document.documentElement).on(j+g,c(this._mousedown,this));
},close:function(){if(this._dropDown){this._dropDown.hide();
}a(document.documentElement).off(g);
},clear:function(){this.close();
},_initDropDown:function(o){var p=this._dropDown=new d.DropDown(o,{direction:2,enableScreenBoundaryDetection:false,enableDirectionDetection:false});
p.initialize();
p.updateSize();
},_initView:function(){var o=h.valuesTree(this.options.range,this.options.column);
this._view=new d.Spreadsheet.FilterMenuView(this.element);
this._view.init();
this._view.on({action:this._viewAction},this);
this._view.populateValueListBox(o[0].items);
},_initFilter:function(){var p=this.options;
var o=h.filter(p.column,p.range.sheet());
if(o){this._view.setFilter(o);
}else{this._view.reset();
}},_viewAction:function(o){var p=this.options.range;
if(o.command==="SortCommand"){p=p.resize({top:1});
}else{if(o.command==="ApplyFilterCommand"&&!o.options.valueFilter&&!o.options.customFilter){return;
}}b(o.options,{sheet:false,operatingRange:p,column:this.options.column});
this.trigger("action",b({},o));
},_mousedown:function(q){var r=q.target;
var p=this._dropDown._element;
var o=this._dropDown.get_anchor();
if(!f(p,r)&&!f(o,r)&&!a(r).parents(".RadCalendar").length){this.close();
}}});
d.Spreadsheet.FilterMenuView=function(o,p){a.observable(this);
this.options=b({},p);
this.element=o;
this._animationType=d.AnimationType.toEasing(1);
this._animationDuration=200;
};
d.Spreadsheet.FilterMenuView.prototype={init:function(){this.initControls();
this.initEvents();
this.initPanelBar();
this.initSort();
this.initFilterByCondition();
this.initFilterByValue();
this.initButtons();
},destroy:function(){this.element.find(".rssHovered").removeClass("rssHovered");
this.element.off(n);
this.element=null;
this.controls.conditionDropDownList.get_events()._list={};
this.controls.valueListBox.get_events()._list={};
this.controls={};
},action:function(o){this.trigger("action",b({},o));
},initControls:function(){var o=this.controls={};
var p=function(q){return $find(a("[id$='"+q+"']").attr("id"));
};
o.conditionDropDownList=p("_ConditionDropDownList");
o.conditionTextBox=p("_ConditionTextBox");
o.conditionNumericTextBox=p("_ConditionNumericTextBox");
o.conditionDatePicker=p("_ConditionDatePicker");
o.valueListBox=p("_ValueListBox");
},initEvents:function(){var o=function(p,q){a(p).toggleClass("rssHovered",q);
};
a(this.element).on(k+n,".rssLI",function(p){o(this,true);
}).on(l+n,".rssLI",function(p){o(this,false);
});
},initPanelBar:function(){var o=this;
a(this.element).on(e+n,".rssCollapsibleList .rssLI.rssCollapsed",function(p){o._selectPanel(a(this).attr("data-value"),true);
});
},initSort:function(){var o=this;
a(this.element).on(e+n,".rssMenu .rssLink",function(p){var q={value:a(this).attr("data-command")};
o.action({command:"SortCommand",options:q});
});
},initFilterByCondition:function(){this.controls.conditionDropDownList.add_selectedIndexChanged(c(this._onConditionCategoryChange,this));
},initFilterByValue:function(){this.controls.valueListBox.add_selectedIndexChanging(c(this._onValueSelectionChange,this));
this.initSearchBoxFilter();
},initButtons:function(){var o=this;
a(this.element).on(e+n,".rssButtons .rssButton",function(r){r.preventDefault();
var p=a(this).attr("data-command");
var q="";
var s={};
if(p==="apply"){q="ApplyFilterCommand";
s=o.getFilter();
}else{q="ClearFilterCommand";
}o.action({command:q,options:s});
});
},initSearchBoxFilter:function(){var o=this;
a(this.element).find("#ValueSearchBox .rssFakeInput").val("");
a(this.element).on(i+n,"#ValueSearchBox .rssFakeInput",function(p){o.filterValueListBox(this.value);
});
},populateValueListBox:function(p){var q=this.controls.valueListBox;
var s=q.get_items();
s.clear();
for(var o=0;
o<p.length;
o++){var r=new d.RadListBoxItem();
r.set_text(p[o].text.toString());
r.set_value(p[o].value);
r.set_checked(p[o].checked);
s.add(r);
}},filterValueListBox:function(v){var u=this.controls.valueListBox;
var t=u.get_items();
var o=t.get_count();
var s;
var r;
var p=false;
for(var q=0;
q<o;
q++){s=t.getItem(q);
r=s.get_text().indexOf(v)>-1;
s.set_visible(r);
p=p||r;
}a(u.get_element()).find(".rlbCheckAllItems").toggle(p);
},getFilter:function(){var o=a(this.element).find(".rssCollapsibleList .rssLI.rssExpanded").attr("data-value");
var p={};
if(o==="customFilter"){p.customFilter=this.getCustomFilter();
}else{p.valueFilter=this.getValueFilter();
}return p;
},getCustomFilter:function(){var o=this.controls;
var p=o.conditionDropDownList;
var q=p.get_selectedItem();
var r=q.get_value();
var t=q.get_attributes().getAttribute("category");
var u;
var s={criteria:[],logic:"and"};
switch(t){case"string":u=o.conditionTextBox.get_value();
break;
case"number":u=o.conditionNumericTextBox.get_value();
break;
case"date":u=o.conditionDatePicker.get_selectedDate();
break;
default:return;
}s.criteria.push({operator:r,type:t,value:u});
return s;
},getValueFilter:function(){var q=this.controls.valueListBox;
var p=q.get_checkedItems();
var t=p.filter(function(u){return u.get_visible();
});
var s=a.map(t,function(u){return u.get_value();
});
var o=s.filter(function(u){return u==="(Blanks)";
});
s=s.filter(function(u){return u!=="(Blanks)";
});
o=o.length>0;
var r={blanks:o,values:s};
return r;
},setFilter:function(o){var p=o.type+"Filter";
this._selectPanel(p,false);
if(o.type=="custom"){this.setCustomFilter(o.options);
}},setCustomFilter:function(q){var o=this.controls;
var p=q.criteria[0];
this._setConditionCategory(p.type,p.operator);
this._resetConditionControls();
switch(p.type){case"string":o.conditionTextBox.set_value(p.value);
break;
case"number":o.conditionNumericTextBox.set_value(p.value);
break;
case"date":o.conditionDatePicker.set_selectedDate(p.value);
break;
}},reset:function(){this._selectPanel("valueFilter",false);
this._setConditionCategory("","");
this._resetConditionControls();
},_resetConditionControls:function(){var o=this.controls;
o.conditionTextBox.set_value("");
o.conditionNumericTextBox.set_value("");
o.conditionDatePicker.set_selectedDate("");
},_setConditionCategory:function(o,v){var q=this.controls.conditionDropDownList;
var u=q.get_items();
var p=u.get_count();
var s=0;
var t;
for(var r=0;
r<p;
r++){t=u.getItem(r);
if(t.get_value()===v&&t.get_attributes().getAttribute("category")===o){s=t.get_index();
break;
}}q.getItem(s).select();
this._onConditionCategoryChange();
},_onConditionCategoryChange:function(){var p=this.controls;
var r=p.conditionDropDownList.get_selectedItem();
var o=r.get_attributes().getAttribute("category");
var q;
a(this.element).find(".rssFormListOption").hide();
switch(o){case"string":q=p.conditionTextBox;
break;
case"number":q=p.conditionNumericTextBox;
break;
case"date":q=p.conditionDatePicker;
break;
}if(q){a(q.get_element()).parents(".rssFormListOption").show();
}},_onValueSelectionChange:function(p,o){o.set_cancel(true);
o.get_item().set_checked(!o.get_item().get_checked());
},_selectPanel:function(r,o){var s=this;
var q=a(this.element).find(".rssCollapsibleList .rssLI");
var u=q.filter("[data-value='valueFilter']");
var p=q.filter("[data-value='customFilter']");
var t=function(w,x,v){a(w).toggleClass("rssExpanded",x).toggleClass("rssCollapsed",!x).find(".rssSummary > .rssIcon").toggleClass("rssIconCollapse",x).toggleClass("rssIconExpand",!x);
s._toggleElement(a(w).find(".rssDetails"),x,v);
};
t(u,(r==="valueFilter"),o);
t(p,(r==="customFilter"),o);
},_toggleElement:function(q,t,o){var s=t?"":0;
var p=s;
if(o){if(t){p=q.height("").height();
q.height(0);
}else{q.height(q.height());
}var r={height:p};
$telerik.stopTransition(q,false);
$telerik.transition(q,r,this._animationDuration,this._animationType,function(){this.height(s);
});
}else{q.height(s);
}}};
})($telerik.$);
(function(a,e){var b=Telerik.Web.UI;
var c={zIndex:4000,draggable:true,modal:true,minTop:10,minBottom:10,minLeft:10,minRight:10,maxHeight:550,width:350};
var d='<div class="rssWindow rssSkin"><div class="rssWindowTitlebar"><span class="rssWindowTitle">{0}</span><span class="rssWindowActions"><span class="rssWindowAction" data-command="close" title="Close"><span class="rssIcon rssIconClose"></span></span></span></div><div class="rssWindowContent"></div></div>")';
b.Spreadsheet.PopupDialog=function(h,g){a.observable(this);
this._element=h;
this._eventsNamespace="."+(h.id||"SpreadsheetPopupDialog");
this.options=a.extend({},c,g);
var f=a(String.format(d,g.title));
a(h).parent().append(f);
f.find(".rssWindowContent").append(h);
this._wrapper=f[0];
if(b.Calendar){this._originalCalendarZIndex=b.Calendar.Popup.zIndex;
}};
b.Spreadsheet.PopupDialog.prototype={open:function(){var h=this;
var f=this._wrapper;
var g="fixed";
this._modalExtender=new Telerik.Web.UI.ModalExtender(f);
f.style.position=g;
if(this.options.modal){a(this._modalExtender._getModalOverlay()).css({position:g,zIndex:this.options.zIndex});
this._modalExtender.show();
}a(f).css({display:"block",zIndex:this.options.zIndex+1});
if(b.Calendar){b.Calendar.Popup.zIndex=this.options.zIndex+2;
}a(f).on("click"+this._eventsNamespace,".rssWindowAction",function(i){if(a(this).attr("data-command")==="close"){h.close();
}});
a(window).on("resize"+this._eventsNamespace,function(){h._resizeForm();
h._positionForm();
});
a(window).trigger("resize"+this._eventsNamespace);
},close:function(){if(this._modalExtender){this._modalExtender.dispose();
}a(this._wrapper).hide().off(this._eventsNamespace);
a(window).off(this._eventsNamespace);
if(b.Calendar){b.Calendar.Popup.zIndex=this._originalCalendarZIndex;
}this.trigger("close");
},_positionForm:function(){var k=a(window);
var j=0;
var i=0;
var h=0;
var g=0;
var f=a(this._wrapper);
i+=(k.width()-f.outerWidth())/2;
j+=(k.height()-parseInt(f.outerHeight(),10))/2;
i=Math.max(i,g);
j=Math.max(j,h);
f.css({top:j,left:i});
},_resizeForm:function(){var f=a(this._wrapper);
var g=f.find(".rssWindowContent");
var h=a(window).height()-(f.outerHeight(true)-g.outerHeight(true));
var i=Math.min(h,this.options.maxHeight);
f.css({width:this.options.width});
g.css({"max-height":i});
}};
})($telerik.$);
(function(a,o){Type.registerNamespace("Telerik.Web.UI.Spreadsheet");
var d=Telerik.Web.UI;
var g=".spreadsheet";
var i=".spreadsheetFormatCellsView";
var q=".spreadsheetValidationView";
var e="click";
var l="mouseenter";
var m="mouseleave";
var b=a.extend;
var c=a.proxy;
var n=kendo.Observable.extend({init:function(s){kendo.Observable.fn.init.call(this);
this.options=b(true,{},this.options,{messages:d.Spreadsheet.Localization},s);
this._initPopup();
},destroy:function(){this.element=null;
},open:function(){this._dialog.open();
},close:function(){this._dialog.close();
},apply:function(){this.close();
},_initPopup:function(){this.element.show();
this._dialog=new d.Spreadsheet.PopupDialog(this.element[0],{zIndex:5001,title:this.options.title,width:this.options.width});
this._dialog.on({close:this._dialogClose},this);
},_dialogClose:function(){var s=this.options.wrapper;
this.element.hide();
if(s){s.append(this.element);
}a(this._dialog._wrapper).remove();
this._dialog=null;
this.trigger("deactivate");
this.destroy();
}});
var f=n.extend({init:function(s){this.initTemplate();
n.fn.init.call(this,s);
this.initButtons();
},destroy:function(){this.element.off(g);
n.fn.destroy.call(this);
},options:{width:350,template:"<div class='rssMessage'><div class='rssMessageText'></div><div class='rssButtons'><span class='rssButton rssPrimary' data-command='ok'></span></div></div>"},initTemplate:function(){var s=this.options;
this.element=a(s.template).hide().appendTo(document.documentElement);
},initButtons:function(){var s=this;
this.element.on(e+g,".rssButtons .rssButton",function(t){t.preventDefault();
s.close();
}).on(l+g,".rssButtons .rssButton",function(t){a(this).addClass("rssHovered");
}).on(m+g,".rssButtons .rssButton",function(t){a(this).removeClass("rssHovered");
});
}});
var k=f.extend({init:function(s){f.fn.init.call(this,s);
},open:function(){var t=this.options;
var s=t.messages.messageDialog;
this.element.find(".rssMessageText").text(t.text).end().find(".rssButton[data-command='ok']").text(s.useKeyboardOK);
n.fn.open.call(this);
}});
kendo.spreadsheet.dialogs.register("message",k);
var p=f.extend({init:function(){f.fn.init.call(this,{});
},open:function(){var s=this.options.messages.messageDialog;
this.element.find(".rssMessageText").text(s.useKeyboardText).end().find(".rssButton[data-command='ok']").text(s.useKeyboardOK);
n.fn.open.call(this);
},options:{title:"Copying and pasting"}});
kendo.spreadsheet.dialogs.register("useKeyboard",p);
var j=n.extend({init:function(s){this.element=s.wrapper.find(".rssCustomFormatTemplate");
n.fn.init.call(this,s);
this._initView();
},destroy:function(){n.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},options:{title:"Format",width:400},apply:function(s){this.trigger("action",{command:"PropertyChangeCommand",options:{property:"format",value:s.format}});
n.fn.apply.call(this);
},open:function(s){n.fn.open.call(this);
this._view._value=s.value();
this._view.init();
},_initView:function(){this._view=new d.Spreadsheet.FormatCellsView(this.element);
this._view.on({action:this._viewAction},this);
},_viewAction:function(s){switch(s.command){case"save":this.apply(s.options);
break;
case"cancel":this.close();
break;
}}});
kendo.spreadsheet.dialogs.register("formatCells",j);
var r=n.extend({init:function(s){this.element=s.wrapper.find(".rssValidationTemplate");
n.fn.init.call(this,s);
this._initView();
},destroy:function(){n.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},options:{title:"Data Validation",width:450},apply:function(s){this.trigger("action",{command:"EditValidationCommand",options:{value:s.value}});
n.fn.apply.call(this);
},open:function(s){n.fn.open.call(this);
this._view._validation=s.validation();
this._view.init();
},_initView:function(){this._view=new d.Spreadsheet.ValidationView(this.element);
this._view.on({action:this._viewAction},this);
},_viewAction:function(s){switch(s.command){case"save":this.apply(s.options);
break;
case"remove":this.apply({value:null});
break;
case"cancel":this.close();
break;
}}});
kendo.spreadsheet.dialogs.register("validation",r);
function h(s){return $find(a(s).attr("id"));
}d.Spreadsheet.FormatText=function(t,s){return kendo.spreadsheet.formatting.text(t,s);
};
d.Spreadsheet.FormatCellsView=function(s,t){a.observable(this);
this.options=b({},t);
this.element=s;
};
d.Spreadsheet.FormatCellsView.prototype={init:function(){this.initControls();
this.initTabStrip();
this.initButtons();
},destroy:function(){this._activeListBox=null;
this.tabStrip.remove_tabSelected(this._tabSelectedHandler);
this.tabStrip=null;
this._tabSelectedHandler=null;
for(var s=0,t=this.listBoxes.length;
s<t;
s++){this.listBoxes[s].remove_selectedIndexChanged(this._listBoxItemSelectedHandler);
}this.listBoxes=[];
this.element.find(".rssHovered").removeClass("rssHovered");
this.element.off(i);
this.element=null;
},action:function(s){this.trigger("action",b({},s));
},initControls:function(){this.tabStrip=h(this.element.find("[id$='_FormatsTabStrip']"));
this.initListBoxes();
},initListBoxes:function(){var w=this.listBoxes=[];
var z=this.tabStrip.get_tabs();
var s=z.get_count();
var y;
var x;
var v;
var u;
this._listBoxItemSelectedHandler=c(this._onListBoxItemSelected,this);
for(var t=0;
t<s;
t++){y=z.getTab(t);
x=y.get_pageView();
v=a(x.get_element()).find(".RadListBox");
u=h(v);
w.push(u);
u.add_selectedIndexChanged(this._listBoxItemSelectedHandler);
}},initTabStrip:function(){var s=this.tabStrip;
this._tabSelectedHandler=c(this._onTabSelected,this);
s.add_tabSelected(this._tabSelectedHandler);
s.set_selectedIndex(-1);
s.set_selectedIndex(0);
},initButtons:function(){var s=this;
a(this.element).on(e+i,".rssButtons .rssButton",function(u){u.preventDefault();
var t=a(this).attr("data-command");
var v={};
if(t==="save"){v.format=s._getFormat();
}s.action({command:t,options:v});
}).on(l+i,".rssButtons .rssButton",function(t){a(this).addClass("rssHovered");
}).on(m+i,".rssButtons .rssButton",function(t){a(this).removeClass("rssHovered");
});
},_getFormat:function(){var t=this._activeListBox.get_selectedItem();
var s=t.get_value();
return s;
},_onTabSelected:function(v,s){var u=s.get_tab();
var t=this._activeListBox=this.listBoxes[u.get_index()];
t.get_items().getItem(0).select();
},_onListBoxItemSelected:function(u,s){var t=u.get_selectedItem().get_value();
var w=this._value||100;
var v=d.Spreadsheet.FormatText(w,t);
a(u.get_element()).siblings(".rssFormatPreview").text(v);
}};
d.Spreadsheet.ValidationView=function(s,t){a.observable(this);
this.options=b({},t);
this.element=s;
};
d.Spreadsheet.ValidationView.prototype={init:function(){this.initControls();
this.initControlsValues();
this.initControlEvents();
this.initButtons();
},destroy:function(){this.element.find(".rssHovered").removeClass("rssHovered");
this.disposeControlEvents();
this.controls={};
this.element.off(q);
this.element=null;
},disposeControlEvents:function(){var s=this.controls;
s.criteria.remove_selectedIndexChanged(this._criteriaChangedHandler);
s.numberCriteria.remove_selectedIndexChanged(this._comparerTypeChangedHandler);
s.dateCriteria.remove_selectedIndexChanged(this._comparerTypeChangedHandler);
},action:function(s){this.trigger("action",b({},s));
},initControls:function(){var u=this;
var s=this.controls={};
var t=function(v){return h(u.element.find("[id$='"+v+"']"));
};
s.criteria=t("_CriteriaDropDownList");
s.numberCriteria=t("_NumberCriteriaDropDownList");
s.textCriteria=t("_TextCriteriaDropDownList");
s.dateCriteria=t("_DateCriteriaDropDownList");
s.numberCriteriaFrom=t("_NumberCriteriaNumericMin");
s.numberCriteriaTo=t("_NumberCriteriaNumericMax");
s.textCriteriaFrom=t("_TextCriteriaTextBox");
s.dateCriteriaFrom=t("_DateCriteriaDatePickerMin");
s.dateCriteriaTo=t("_DateCriteriaDatePickerMax");
s.customCriteriaFrom=t("_CustomCriteriaTextBox");
s.ignoreBlanks=this.element.find("[id$='_CriteriaIgnoreCheckBox']")[0];
s.invalidButtonList=this.element.find("[id$='_InvalidDataRadioButtonList']")[0];
s.hint=this.element.find("[id$='_HintCheckBox']")[0];
s.hintMessage=t("_HintTextBox");
},initControlsValues:function(){var s=this.controls;
s.criteria.getItem(0).select();
s.numberCriteria.getItem(0).select();
s.textCriteria.getItem(0).select();
s.dateCriteria.getItem(0).select();
s.numberCriteriaFrom.set_value("");
s.numberCriteriaTo.set_value("");
s.textCriteriaFrom.set_value("");
s.dateCriteriaFrom.set_selectedDate("");
s.dateCriteriaTo.set_selectedDate("");
s.customCriteriaFrom.set_value("");
this._setValidation(this._validation);
},initControlEvents:function(){var s=this.controls;
this._criteriaChangedHandler=c(this._onCriteriaChanged,this);
s.criteria.add_selectedIndexChanged(this._criteriaChangedHandler);
this._comparerTypeChangedHandler=c(this._onComparerTypeChanged,this);
s.numberCriteria.add_selectedIndexChanged(this._comparerTypeChangedHandler);
s.dateCriteria.add_selectedIndexChanged(this._comparerTypeChangedHandler);
this._onCriteriaChanged(s.criteria);
this._onComparerTypeChanged(s.numberCriteria);
this._onComparerTypeChanged(s.dateCriteria);
},initButtons:function(){var s=this;
a(this.element).on(e+q,".rssButtons .rssButton",function(u){u.preventDefault();
var t=a(this).attr("data-command");
var v={};
var w=s._getValidation();
if(w!==null){w=b({},w);
}if(t==="save"){if(!s.isValid()){return;
}v.value=w;
}s.action({command:t,options:v});
}).on(l+q,".rssButtons .rssButton",function(t){a(this).addClass("rssHovered");
}).on(m+q,".rssButtons .rssButton",function(t){a(this).removeClass("rssHovered");
});
},isValid:function(){var t=this._getCriteria();
var s=this._getComparerType();
var u=true;
switch(t){case"number":u=Page_ClientValidate("NumberCriteriaMin");
if(s==="between"||s==="notBetween"){u=u&&Page_ClientValidate("NumberCriteriaMax");
}break;
case"text":u=Page_ClientValidate("TextCriteria");
break;
case"date":u=Page_ClientValidate("DateCriteriaMin");
if(s==="between"||s==="notBetween"){u=u&&Page_ClientValidate("DateCriteriaMax");
}break;
case"custom":u=Page_ClientValidate("CustomCriteria");
break;
}return u;
},_onCriteriaChanged:function(u){var s=u.get_selectedItem().get_value();
var t=this.element.find(".rssFormListOption");
t.hide();
t.filter("[data-value='"+s+"']").show();
},_onComparerTypeChanged:function(t){var v=t.get_selectedItem().get_value();
var s=a(t.get_element()).parents(".rssFormList").first();
var u=(v==="between"||v==="notBetween");
s.find("li").last().toggle(u);
},_getValidation:function(){var s=this.controls;
var t=this._getCriteria();
if(t==="any"){return null;
}var u={allowNulls:this._getIgnoreBlanks(),comparerType:this._getComparerType(),dataType:t,from:this._getFrom(),to:this._getTo(),type:this._getInvalidType()};
if(s.hint.checked){u.messageTemplate=this._getHint();
}return u;
},_getCriteria:function(){return this.controls.criteria.get_selectedItem().get_value();
},_getComparerType:function(){var u=null;
var s=this.controls;
var t=this._getCriteria();
switch(t){case"number":u=s.numberCriteria.get_selectedItem().get_value();
break;
case"text":u=s.textCriteria.get_selectedItem().get_value();
break;
case"date":u=s.dateCriteria.get_selectedItem().get_value();
break;
}return u;
},_getFrom:function(){var u=null;
var s=this.controls;
var t=this._getCriteria();
switch(t){case"number":u=s.numberCriteriaFrom.get_value();
break;
case"text":u=s.textCriteriaFrom.get_value();
break;
case"date":u=s.dateCriteriaFrom.get_selectedDate();
break;
case"custom":u=s.customCriteriaFrom.get_value();
break;
}return u;
},_getTo:function(){var u=null;
var s=this.controls;
var t=this._getCriteria();
switch(t){case"number":u=s.numberCriteriaTo.get_value();
break;
case"date":u=s.dateCriteriaTo.get_selectedDate();
break;
}return u;
},_getInvalidType:function(){var s=a(this.controls.invalidButtonList).find("input:checked").attr("value");
return s;
},_getHint:function(){return this.controls.hintMessage.get_value();
},_getIgnoreBlanks:function(){return this.controls.ignoreBlanks.checked;
},_setValidation:function(s){if(s===null){s={dataType:"any"};
}this._setCriteria(s.dataType);
this._setComparerType(s.comparerType);
this._setFrom(s.from);
this._setTo(s.to);
this._setInvalidType(s.type);
this._setHint(s.messageTemplate);
this._setIgnoreBlanks(s.allowNulls);
},_setCriteria:function(s){var t=this.controls.criteria;
var u=t.findItemByValue(s);
if(!u){u=t.getItem(0);
}u.select();
},_setComparerType:function(s){var t=this.controls;
var u=this._getCriteria();
var v=null;
switch(u){case"number":v=t.numberCriteria.findItemByValue(s);
break;
case"text":v=t.textCriteria.findItemByValue(s);
break;
case"date":v=t.dateCriteria.findItemByValue(s);
break;
}if(v){v.select();
}},_setFrom:function(u){var s=this.controls;
var t=this._getCriteria();
if(!u){return;
}switch(t){case"number":s.numberCriteriaFrom.set_value(u);
break;
case"text":u=s.textCriteriaFrom.set_value(u);
break;
case"date":s.dateCriteriaFrom.set_selectedDate(this._parseDate(u));
break;
case"custom":s.customCriteriaFrom.set_value(u);
break;
}},_setTo:function(u){var s=this.controls;
var t=this._getCriteria();
if(!u){return;
}switch(t){case"number":s.numberCriteriaTo.set_value(u);
break;
case"date":s.dateCriteriaTo.set_selectedDate(this._parseDate(u));
break;
}},_setInvalidType:function(t){var s=this.controls.invalidButtonList;
if(t!=="warning"){t="reject";
}a(s).find("input[value='"+t+"']")[0].checked=true;
},_setHint:function(t){var s=this.controls;
s.hint.checked=!!t;
s.hintMessage.set_value(t||"");
},_setIgnoreBlanks:function(s){this.controls.ignoreBlanks.checked=(s!==o)?s:true;
},_parseDate:function(s){return new Date(s.substring("DATEVALUE(".length+1,s.length-2));
}};
})($telerik.$);
(function(a,e){var b=Telerik.Web.UI;
b.SpreadsheetSheet=function(){this._sheet=null;
};
b.SpreadsheetSheet.prototype={get_range:function(h){var f=this._sheet.range(h);
var g=this._getRange(f);
return g;
},get_selection:function(){var f=this._sheet.selection();
var g=this._getRange(f);
return g;
},get_columnWidth:function(f){return this._sheet.columnWidth(f);
},set_columnWidth:function(f,g){this._sheet.columnWidth(f,g);
},get_rowHeight:function(f){return this._sheet.rowHeight(f);
},set_rowHeight:function(g,f){this._sheet.rowHeight(g,f);
},_getRange:function(f){var g=new b.SpreadsheetRange();
g._range=f;
return g;
}};
function c(f,g){a.each(g,function(h,i){f.prototype[i]=function(){this._sheet[i].apply(this._sheet,arguments);
};
});
}c(b.SpreadsheetSheet,["clearFilter","deleteColumn","deleteRow","hideColumn","hideRow","unhideColumn","unhideRow","insertColumn","insertRow"]);
function d(i,h,j){var f=function(k){return function(){var l=this._sheet[k]();
return l;
};
};
var g=function(k){return function(l){this._sheet[k](l);
};
};
a.each(i,function(k,l){h=h||f;
j=j||g;
b.SpreadsheetSheet.prototype["get_"+l]=h(l);
b.SpreadsheetSheet.prototype["set_"+l]=j(l);
});
}d(["frozenColumns","frozenRows"]);
})($telerik.$);
(function(a,g){var b=Telerik.Web.UI;
b.SpreadsheetRange=function(){this._range=null;
};
b.SpreadsheetRange.prototype={get_enabled:function(){return this._range.enable();
},set_enabled:function(h){this._range.enable(h);
},set_filter:function(h){this._range.filter(h);
},hasFilter:function(){return this._range.hasFilter();
},get_isSortable:function(){return this._range.isSortable();
},get_isFilterable:function(){return this._range.isFilterable();
}};
function e(h){a.each(h,function(i,j){b.SpreadsheetRange.prototype[j]=function(){this._range[j].apply(this._range,arguments);
};
});
}e(["merge","unmerge","select","fillFrom","clear","clearFilter"]);
function f(k,j,l){var h=function(m){return function(){var n=this._range[m]();
return n;
};
};
var i=function(m){return function(n){this._range[m](n);
};
};
a.each(k,function(m,n){j=j||h;
l=l||i;
b.SpreadsheetRange.prototype["get_"+n]=j(n);
b.SpreadsheetRange.prototype["set_"+n]=l(n);
});
}f(["background","bold","color","fontFamily","fontSize","format","formula","input","italic","textAlign","value","values","validation","verticalAlign","wrap"]);
function d(j,k){var h={};
var i=[];
a.each(j,function(m,n){var l=n+k;
h[l]=n;
i.push(l);
});
f(i,function(l){return function(){var m=this._range[h[l]]();
return m?(m[k.toLowerCase()]||null):null;
};
},function(l){return function(n){var m={};
m[k.toLowerCase()]=n;
this._range[h[l]](m);
};
});
}var c=["borderBottom","borderLeft","borderRight","borderTop"];
d(c,"Color");
d(c,"Size");
})($telerik.$);
(function(a,i){Type.registerNamespace("Telerik.Web.UI");
var e=Telerik.Web.UI;
var c=Sys.Serialization.JavaScriptSerializer;
var d=a.proxy;
var b=a.extend;
var f=".";
var g="mouseenter";
var h="mouseleave";
e.Spreadsheet.Localization={messageDialog:{useKeyboardTitle:"Copying and pasting",useKeyboardText:"These actions cannot be invoked through the menu. Please use the keyboard shortcuts instead",useKeyboardOK:"OK"}};
e.RadSpreadsheet=function(j){e.RadSpreadsheet.initializeBase(this,[j]);
this._widget=null;
this._uniqueId=null;
this._cellContextMenuID=null;
this._rowHeaderContextMenuID=null;
this._columnHeaderContextMenuID=null;
};
e.RadSpreadsheet.prototype={initialize:function(){this.initializeLocalization();
this.initializeWidget();
},initializeLocalization:function(){b(true,e.Spreadsheet.Localization,this.get_localization());
},initializeWidget:function(){var j={columns:this.get_columnsCount(),columnWidth:this.get_columnWidth(),headerHeight:this.get_columnHeaderHeight(),headerWidth:this.get_rowHeaderWidth(),rows:this.get_rowsCount(),rowHeight:this.get_rowHeight(),sheets:this.get_sheetsData()};
this._widget=a(this.get_element()).kendoSpreadsheet(j).data("kendoSpreadsheet");
this._widget._workbook.unbind("excelImport");
this.initializeToolbar();
this.initializeContextMenus();
this._initializeHoveredStates();
},initializeToolbar:function(){this._widget._view.tabstrip.bind("toolBarCommand",d(this._onToolbarCommand,this));
},initializeContextMenus:function(){var j=this._widget._view;
j.cellContextMenu._initContextMenu(this._cellContextMenuID);
j.rowHeaderContextMenu._initContextMenu(this._rowHeaderContextMenuID);
j.colHeaderContextMenu._initContextMenu(this._columnHeaderContextMenuID);
},get_kendoWidget:function(){return this._widget;
},save:function(){var j=c.serialize(this._widget.toJSON());
this._doCallback(j);
},saveAsExcel:function(){this._widget.saveAsExcel();
},fromFile:function(j){this._widget.fromFile(j);
},get_activeSheet:function(){var j=this._widget.activeSheet();
var k=this._getSheet(j);
return k;
},get_sheets:function(){var l=this;
var j=this._widget.sheets();
var k=a.map(j,function(m){return l._getSheet(m);
});
return k;
},findSheetByName:function(k){var j=this._widget.sheetByName(k);
var l=this._getSheet(j);
return l;
},findSheetByIndex:function(j){var k=this._widget.sheetByIndex(j);
var l=this._getSheet(k);
return l;
},insertSheet:function(){this._widget.insertSheet();
},removeSheet:function(j){this._widget.removeSheet(j._sheet);
},renameSheet:function(k,j){this._widget.renameSheet(k._sheet,j);
},_getSheet:function(j){if(!j){return null;
}var k=new e.SpreadsheetSheet();
k._sheet=j;
return k;
},_onToolbarCommand:function(j){switch(j.value){case"save":this.save();
break;
}},_doCallback:function(j){var k=d(this._onCallbackResponse,this);
var l=d(this._onCallbackError,this);
WebForm_DoCallback(this._uniqueId,j,k,this,l,true);
},_onCallbackResponse:function(){},_onCallbackError:function(j){var k=this._extractErrorMessage(j);
alert(k);
},_extractErrorMessage:function(j){if(j.get_message){return j.get_message();
}else{return j.replace(/(\d*\|.*)/,"");
}},_initializeHoveredStates:function(){var j=kendo.spreadsheet.SheetsBar.classNames;
var k=f+kendo.spreadsheet.View.classNames.sheetsBar;
var m=f+j.sheetsBarItems+" "+f+j.sheetsBarKItemBase;
var l=f+j.sheetsBarRemove;
this._applyHoveredState(k,m);
this._applyHoveredState(k,l);
},_applyHoveredState:function(j,l){var k=kendo.spreadsheet.SheetsBar.classNames.sheetsBarHovered;
a(j).on(g,l,function(m){a(m.currentTarget).addClass(k);
}).on(h,l,function(m){a(m.currentTarget).removeClass(k);
});
}};
a.registerControlProperties(e.RadSpreadsheet,{sheetsData:[],localization:{},columnsCount:50,columnWidth:64,columnHeaderHeight:20,rowsCount:200,rowHeight:20,rowHeaderWidth:32});
e.RadSpreadsheet.registerClass("Telerik.Web.UI.RadSpreadsheet",e.RadWebControl);
})($telerik.$);
