using System;
using System.Globalization;

namespace HouseOfSynergy.AffinityDms.ResourceProvider
{
	public static partial class ResourceManagement
	{
		public static string DesktopClient_AuthenticationErrorCredentials { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_AuthenticationErrorCredentials")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_AuthenticationErrorCredentials"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_AuthenticationErrorDomain { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_AuthenticationErrorDomain")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_AuthenticationErrorDomain"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_AuthenticationErrorUnknown { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_AuthenticationErrorUnknown")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_AuthenticationErrorUnknown"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_ButtonCancel { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_ButtonCancel")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_ButtonCancel"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_ButtonOk { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_ButtonOk")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_ButtonOk"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_ExceptionNotImplemented { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_ExceptionNotImplemented")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_ExceptionNotImplemented"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelCulture { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelCulture")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelCulture"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelCultureName { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelCultureName")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelCultureName"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelCultureNameEnglish { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelCultureNameEnglish")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelCultureNameEnglish"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelCultureNameNative { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelCultureNameNative")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelCultureNameNative"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelDomain { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelDomain")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelDomain"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelLogin { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelLogin")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelLogin"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelPassword { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelPassword")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelPassword"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_LabelUsername { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_LabelUsername")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_LabelUsername"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_MessageErrorDomainEnter { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_MessageErrorDomainEnter")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_MessageErrorDomainEnter"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_MessageErrorLanguageSelect { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_MessageErrorLanguageSelect")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_MessageErrorLanguageSelect"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_MessageErrorList { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_MessageErrorList")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_MessageErrorList"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_MessageErrorPasswordEnter { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_MessageErrorPasswordEnter")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_MessageErrorPasswordEnter"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_MessageErrorUsernameEnter { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_MessageErrorUsernameEnter")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_MessageErrorUsernameEnter"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_ProductDescription { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_ProductDescription")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_ProductDescription"]); } else { return (""); } } else { return (""); } } }
		public static string DesktopClient_ProductName { get { if (ResourceManagement.Dictionary.ContainsKey(CultureInfo.CurrentCulture.Name)) { if (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name].ContainsKey("DesktopClient_ProductName")) { return (ResourceManagement.Dictionary [CultureInfo.CurrentCulture.Name] ["DesktopClient_ProductName"]); } else { return (""); } } else { return (""); } } }
	}
}