(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.binder",["kendo.core","kendo.data"],l);
}(function(){var k={id:"binder",name:"MVVM",category:"framework",description:"Model View ViewModel (MVVM) is a design pattern which helps developers separate the Model (the data) from the View (the UI).",depends:["core","data"]};
(function(l,V){var E=window.kendo,H=E.Observable,J=E.data.ObservableObject,I=E.data.ObservableArray,P={}.toString,q={},w=E.Class,L=l.proxy,W="value",N="source",C="events",v="checked",y="css",A=true,D="function",u="change";
(function(){var Z=document.createElement("a");
try{delete Z.test;
}catch(aa){A=false;
}}());
var r=H.extend({init:function(Z,aa){var ab=this;
H.fn.init.call(ab);
ab.source=Z[0];
ab.parents=Z;
ab.path=aa;
ab.dependencies={};
ab.dependencies[aa]=true;
ab.observable=ab.source instanceof H;
ab._access=function(ac){ab.dependencies[ac.field]=true;
};
if(ab.observable){ab._change=function(ac){ab.change(ac);
};
ab.source.bind(u,ab._change);
}},_parents:function(){var aa=this.parents;
var ab=this.get();
if(ab&&typeof ab.parent=="function"){var Z=ab.parent();
if(l.inArray(Z,aa)<0){aa=[Z].concat(aa);
}}return aa;
},change:function(ab){var aa,Z,ac=ab.field,ad=this;
if(ad.path==="this"){ad.trigger(u,ab);
}else{for(aa in ad.dependencies){if(aa.indexOf(ac)===0){Z=aa.charAt(ac.length);
if(!Z||Z==="."||Z==="["){ad.trigger(u,ab);
break;
}}}}},start:function(Z){Z.bind("get",this._access);
},stop:function(Z){Z.unbind("get",this._access);
},get:function(){var ad=this,ac=ad.source,Z=0,aa=ad.path,ab=ac;
if(!ad.observable){return ab;
}ad.start(ad.source);
ab=ac.get(aa);
while(ab===V&&ac){ac=ad.parents[++Z];
if(ac instanceof J){ab=ac.get(aa);
}}if(ab===V){ac=ad.source;
while(ab===V&&ac){ac=ac.parent();
if(ac instanceof J){ab=ac.get(aa);
}}}if(typeof ab==="function"){Z=aa.lastIndexOf(".");
if(Z>0){ac=ac.get(aa.substring(0,Z));
}ad.start(ac);
if(ac!==ad.source){ab=ab.call(ac,ad.source);
}else{ab=ab.call(ac);
}ad.stop(ac);
}if(ac&&ac!==ad.source){ad.currentSource=ac;
ac.unbind(u,ad._change).bind(u,ad._change);
}ad.stop(ad.source);
return ab;
},set:function(ab){var aa=this.currentSource||this.source;
var Z=E.getter(this.path)(aa);
if(typeof Z==="function"){if(aa!==this.source){Z.call(aa,this.source,ab);
}else{Z.call(aa,ab);
}}else{aa.set(this.path,ab);
}},destroy:function(){if(this.observable){this.source.unbind(u,this._change);
if(this.currentSource){this.currentSource.unbind(u,this._change);
}}this.unbind();
}});
var B=r.extend({get:function(){var ac=this.source,ab=this.path,aa=0,Z;
Z=ac.get(ab);
while(!Z&&ac){ac=this.parents[++aa];
if(ac instanceof J){Z=ac.get(ab);
}}return L(Z,ac);
}});
var O=r.extend({init:function(aa,Z,ab){var ac=this;
r.fn.init.call(ac,aa,Z);
ac.template=ab;
},render:function(aa){var Z;
this.start(this.source);
Z=E.render(this.template,aa);
this.stop(this.source);
return Z;
}});
var p=w.extend({init:function(aa,Z,ab){this.element=aa;
this.bindings=Z;
this.options=ab;
},bind:function(aa,Z){var ab=this;
aa=Z?aa[Z]:aa;
aa.bind(u,function(ac){ab.refresh(Z||ac);
});
ab.refresh(Z);
},destroy:function(){}});
var Q=p.extend({dataType:function(){var Z=this.element.getAttribute("data-type")||this.element.type||"text";
return Z.toLowerCase();
},parsedValue:function(){return this._parseValue(this.element.value,this.dataType());
},_parseValue:function(aa,Z){if(Z=="date"){aa=E.parseDate(aa,"yyyy-MM-dd");
}else{if(Z=="datetime-local"){aa=E.parseDate(aa,["yyyy-MM-ddTHH:mm:ss","yyyy-MM-ddTHH:mm"]);
}else{if(Z=="number"){aa=E.parseFloat(aa);
}else{if(Z=="boolean"){aa=aa.toLowerCase();
if(E.parseFloat(aa)!==null){aa=Boolean(E.parseFloat(aa));
}else{aa=aa.toLowerCase()==="true";
}}}}}return aa;
}});
q.attr=p.extend({refresh:function(Z){this.element.setAttribute(Z,this.bindings.attr[Z].get());
}});
q.css=p.extend({init:function(aa,Z,ab){p.fn.init.call(this,aa,Z,ab);
this.classes={};
},refresh:function(aa){var ab=l(this.element),Z=this.bindings.css[aa],ac=this.classes[aa]=Z.get();
if(ac){ab.addClass(aa);
}else{ab.removeClass(aa);
}}});
q.style=p.extend({refresh:function(Z){this.element.style[Z]=this.bindings.style[Z].get()||"";
}});
q.enabled=p.extend({refresh:function(){if(this.bindings.enabled.get()){this.element.removeAttribute("disabled");
}else{this.element.setAttribute("disabled","disabled");
}}});
q.readonly=p.extend({refresh:function(){if(this.bindings.readonly.get()){this.element.setAttribute("readonly","readonly");
}else{this.element.removeAttribute("readonly");
}}});
q.disabled=p.extend({refresh:function(){if(this.bindings.disabled.get()){this.element.setAttribute("disabled","disabled");
}else{this.element.removeAttribute("disabled");
}}});
q.events=p.extend({init:function(aa,Z,ab){p.fn.init.call(this,aa,Z,ab);
this.handlers={};
},refresh:function(ac){var aa=l(this.element),Z=this.bindings.events[ac],ab=this.handlers[ac];
if(ab){aa.off(ac,ab);
}ab=this.handlers[ac]=Z.get();
aa.on(ac,Z.source,ab);
},destroy:function(){var Z=l(this.element),aa;
for(aa in this.handlers){Z.off(aa,this.handlers[aa]);
}}});
q.text=p.extend({refresh:function(){var aa=this.bindings.text.get();
var Z=this.element.getAttribute("data-format")||"";
if(aa==null){aa="";
}l(this.element).text(E.toString(aa,Z));
}});
q.visible=p.extend({refresh:function(){if(this.bindings.visible.get()){this.element.style.display="";
}else{this.element.style.display="none";
}}});
q.invisible=p.extend({refresh:function(){if(!this.bindings.invisible.get()){this.element.style.display="";
}else{this.element.style.display="none";
}}});
q.html=p.extend({refresh:function(){this.element.innerHTML=this.bindings.html.get();
}});
q.value=Q.extend({init:function(aa,Z,ab){Q.fn.init.call(this,aa,Z,ab);
this._change=L(this.change,this);
this.eventName=ab.valueUpdate||u;
l(this.element).on(this.eventName,this._change);
this._initChange=false;
},change:function(){this._initChange=this.eventName!=u;
this.bindings[W].set(this.parsedValue());
this._initChange=false;
},refresh:function(){if(!this._initChange){var aa=this.bindings[W].get();
if(aa==null){aa="";
}var Z=this.dataType();
if(Z=="date"){aa=E.toString(aa,"yyyy-MM-dd");
}else{if(Z=="datetime-local"){aa=E.toString(aa,"yyyy-MM-ddTHH:mm:ss");
}}this.element.value=aa;
}this._initChange=false;
},destroy:function(){l(this.element).off(this.eventName,this._change);
}});
q.source=p.extend({init:function(aa,Z,ab){p.fn.init.call(this,aa,Z,ab);
var ac=this.bindings.source.get();
if(ac instanceof E.data.DataSource&&ab.autoBind!==false){ac.fetch();
}},refresh:function(Z){var ab=this,aa=ab.bindings.source.get();
if(aa instanceof I||aa instanceof E.data.DataSource){Z=Z||{};
if(Z.action=="add"){ab.add(Z.index,Z.items);
}else{if(Z.action=="remove"){ab.remove(Z.index,Z.items);
}else{if(Z.action!="itemchange"){ab.render();
}}}}else{ab.render();
}},container:function(){var Z=this.element;
if(Z.nodeName.toLowerCase()=="table"){if(!Z.tBodies[0]){Z.appendChild(document.createElement("tbody"));
}Z=Z.tBodies[0];
}return Z;
},template:function(){var aa=this.options,ab=aa.template,Z=this.container().nodeName.toLowerCase();
if(!ab){if(Z=="select"){if(aa.valueField||aa.textField){ab=E.format('<option value="#:{0}#">#:{1}#</option>',aa.valueField||aa.textField,aa.textField||aa.valueField);
}else{ab="<option>#:data#</option>";
}}else{if(Z=="tbody"){ab="<tr><td>#:data#</td></tr>";
}else{if(Z=="ul"||Z=="ol"){ab="<li>#:data#</li>";
}else{ab="#:data#";
}}}ab=E.template(ab);
}return ab;
},add:function(ad,ae){var ab=this.container(),ag,ac,af,Z,aa=ab.cloneNode(false),ah=ab.children[ad];
l(aa).html(E.render(this.template(),ae));
if(aa.children.length){ag=this.bindings.source._parents();
for(ac=0,af=ae.length;
ac<af;
ac++){Z=aa.children[0];
ab.insertBefore(Z,ah||null);
o(Z,ae[ac],this.options.roles,[ae[ac]].concat(ag));
}}},remove:function(ac,ad){var ab,aa=this.container();
for(ab=0;
ab<ad.length;
ab++){var Z=aa.children[ac];
U(Z,true);
aa.removeChild(Z);
}},render:function(){var ad=this.bindings.source.get(),ac,aa,ab,Z=this.container(),ae=this.template();
if(ad==null){return;
}if(ad instanceof E.data.DataSource){ad=ad.view();
}if(!(ad instanceof I)&&P.call(ad)!=="[object Array]"){ad=[ad];
}if(this.bindings.template){T(Z,true);
l(Z).html(this.bindings.template.render(ad));
if(Z.children.length){ac=this.bindings.source._parents();
for(aa=0,ab=ad.length;
aa<ab;
aa++){o(Z.children[aa],ad[aa],this.options.roles,[ad[aa]].concat(ac));
}}}else{l(Z).html(E.render(ae,ad));
}}});
q.input={checked:Q.extend({init:function(aa,Z,ab){Q.fn.init.call(this,aa,Z,ab);
this._change=L(this.change,this);
l(this.element).change(this._change);
},change:function(){var Z=this.element;
var ad=this.value();
if(Z.type=="radio"){ad=this.parsedValue();
this.bindings[v].set(ad);
}else{if(Z.type=="checkbox"){var ac=this.bindings[v].get();
var ab;
if(ac instanceof I){ad=this.parsedValue();
if(ad instanceof Date){for(var aa=0;
aa<ac.length;
aa++){if(ac[aa] instanceof Date&&+ac[aa]===+ad){ab=aa;
break;
}}}else{ab=ac.indexOf(ad);
}if(ab>-1){ac.splice(ab,1);
}else{ac.push(ad);
}}else{this.bindings[v].set(ad);
}}}},refresh:function(){var ae=this.bindings[v].get(),ac=ae,ad=this.dataType(),Z=this.element;
if(Z.type=="checkbox"){if(ac instanceof I){var ab=-1;
ae=this.parsedValue();
if(ae instanceof Date){for(var aa=0;
aa<ac.length;
aa++){if(ac[aa] instanceof Date&&+ac[aa]===+ae){ab=aa;
break;
}}}else{ab=ac.indexOf(ae);
}Z.checked=ab>=0;
}else{Z.checked=ac;
}}else{if(Z.type=="radio"&&ae!=null){if(ad=="date"){ae=E.toString(ae,"yyyy-MM-dd");
}else{if(ad=="datetime-local"){ae=E.toString(ae,"yyyy-MM-ddTHH:mm:ss");
}}if(Z.value===ae.toString()){Z.checked=true;
}else{Z.checked=false;
}}}},value:function(){var Z=this.element,aa=Z.value;
if(Z.type=="checkbox"){aa=Z.checked;
}return aa;
},destroy:function(){l(this.element).off(u,this._change);
}})};
q.select={source:q.source.extend({refresh:function(Z){var ab=this,aa=ab.bindings.source.get();
if(aa instanceof I||aa instanceof E.data.DataSource){Z=Z||{};
if(Z.action=="add"){ab.add(Z.index,Z.items);
}else{if(Z.action=="remove"){ab.remove(Z.index,Z.items);
}else{if(Z.action=="itemchange"||Z.action===V){ab.render();
if(ab.bindings.value){if(ab.bindings.value){var ac=M(ab.bindings.value.get(),l(ab.element).data("valueField"));
if(ac===null){ab.element.selectedIndex=-1;
}else{ab.element.value=ac;
}}}}}}}else{ab.render();
}}}),value:Q.extend({init:function(ab,Z,aa){Q.fn.init.call(this,ab,Z,aa);
this._change=L(this.change,this);
l(this.element).change(this._change);
},parsedValue:function(){var Z=this.dataType();
var ae=[];
var ad,ac,aa,ab;
for(aa=0,ab=this.element.options.length;
aa<ab;
aa++){ac=this.element.options[aa];
if(ac.selected){ad=ac.attributes.value;
if(ad&&ad.specified){ad=ac.value;
}else{ad=ac.text;
}ae.push(this._parseValue(ad,Z));
}}return ae;
},change:function(){var ak=[],Z=this.element,af,aa=this.options.valueField||this.options.textField,aj=this.options.valuePrimitive,ae,ai,ah,ab,ac;
for(ab=0,ac=Z.options.length;
ab<ac;
ab++){ae=Z.options[ab];
if(ae.selected){ah=ae.attributes.value;
if(ah&&ah.specified){ah=ae.value;
}else{ah=ae.text;
}ak.push(this._parseValue(ah,this.dataType()));
}}if(aa){af=this.bindings.source.get();
if(af instanceof E.data.DataSource){af=af.view();
}for(ai=0;
ai<ak.length;
ai++){for(ab=0,ac=af.length;
ab<ac;
ab++){var ag=this._parseValue(af[ab].get(aa),this.dataType());
var ad=String(ag)===ak[ai];
if(ad){ak[ai]=af[ab];
break;
}}}}ah=this.bindings[W].get();
if(ah instanceof I){ah.splice.apply(ah,[0,ah.length].concat(ak));
}else{if(!aj&&(ah instanceof J||ah===null||ah===V||!aa)){this.bindings[W].set(ak[0]);
}else{this.bindings[W].set(ak[0].get(aa));
}}},refresh:function(){var ac,Z=this.element,ad=Z.options,ag=this.bindings[W].get(),ai=ag,aa=this.options.valueField||this.options.textField,ab=false,af=this.dataType(),ae;
if(!(ai instanceof I)){ai=new I([ag]);
}Z.selectedIndex=-1;
for(var ah=0;
ah<ai.length;
ah++){ag=ai[ah];
if(aa&&ag instanceof J){ag=ag.get(aa);
}if(af=="date"){ag=E.toString(ai[ah],"yyyy-MM-dd");
}else{if(af=="datetime-local"){ag=E.toString(ai[ah],"yyyy-MM-ddTHH:mm:ss");
}}for(ac=0;
ac<ad.length;
ac++){ae=ad[ac].value;
if(ae===""&&ag!==""){ae=ad[ac].text;
}if(ag!=null&&ae==ag.toString()){ad[ac].selected=true;
ab=true;
}}}},destroy:function(){l(this.element).off(u,this._change);
}})};
function z(Z,aa,ab){return p.extend({init:function(af,ac,ad){var ae=this;
p.fn.init.call(ae,af.element[0],ac,ad);
ae.widget=af;
ae._dataBinding=L(ae.dataBinding,ae);
ae._dataBound=L(ae.dataBound,ae);
ae._itemChange=L(ae.itemChange,ae);
},itemChange:function(ac){o(ac.item[0],ac.data,this._ns(ac.ns),[ac.data].concat(this.bindings[Z]._parents()));
},dataBinding:function(ac){var ad,af,ag=this.widget,ae=ac.removedItems||ag.items();
for(ad=0,af=ae.length;
ad<af;
ad++){U(ae[ad],false);
}},_ns:function(ad){ad=ad||E.ui;
var ac=[E.ui,E.dataviz.ui,E.mobile.ui];
ac.splice(l.inArray(ad,ac),1);
ac.unshift(ad);
return E.rolesFromNamespaces(ac);
},dataBound:function(ad){var af,ah,ak=this.widget,ag=ad.addedItems||ak.items(),ac=ak[aa],aj,ai,ae=E.data.HierarchicalDataSource;
if(ae&&ac instanceof ae){return;
}if(ag.length){aj=ad.addedDataItems||ac.flatView();
ai=this.bindings[Z]._parents();
for(af=0,ah=aj.length;
af<ah;
af++){o(ag[af],aj[af],this._ns(ad.ns),[aj[af]].concat(ai));
}}},refresh:function(ac){var ag=this,af,ah=ag.widget,ae,ad;
ac=ac||{};
if(!ac.action){ag.destroy();
ah.bind("dataBinding",ag._dataBinding);
ah.bind("dataBound",ag._dataBound);
ah.bind("itemChange",ag._itemChange);
af=ag.bindings[Z].get();
if(ah[aa] instanceof E.data.DataSource&&ah[aa]!=af){if(af instanceof E.data.DataSource){ah[ab](af);
}else{if(af&&af._dataSource){ah[ab](af._dataSource);
}else{ah[aa].data(af);
ae=E.ui.Select&&ah instanceof E.ui.Select;
ad=E.ui.MultiSelect&&ah instanceof E.ui.MultiSelect;
if(ag.bindings.value&&(ae||ad)){ah.value(M(ag.bindings.value.get(),ah.options.dataValueField));
}}}}}},destroy:function(){var ac=this.widget;
ac.unbind("dataBinding",this._dataBinding);
ac.unbind("dataBound",this._dataBound);
ac.unbind("itemChange",this._itemChange);
}});
}q.widget={events:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
this.handlers={};
},refresh:function(ab){var Z=this.bindings.events[ab],aa=this.handlers[ab];
if(aa){this.widget.unbind(ab,aa);
}aa=Z.get();
this.handlers[ab]=function(ac){ac.data=Z.source;
aa(ac);
if(ac.data===Z.source){delete ac.data;
}};
this.widget.bind(ab,this.handlers[ab]);
},destroy:function(){var Z;
for(Z in this.handlers){this.widget.unbind(Z,this.handlers[Z]);
}}}),checked:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
this._change=L(this.change,this);
this.widget.bind(u,this._change);
},change:function(){this.bindings[v].set(this.value());
},refresh:function(){this.widget.check(this.bindings[v].get()===true);
},value:function(){var Z=this.element,aa=Z.value;
if(aa=="on"||aa=="off"){aa=Z.checked;
}return aa;
},destroy:function(){this.widget.unbind(u,this._change);
}}),visible:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
},refresh:function(){var Z=this.bindings.visible.get();
this.widget.wrapper[0].style.display=Z?"":"none";
}}),invisible:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
},refresh:function(){var Z=this.bindings.invisible.get();
this.widget.wrapper[0].style.display=Z?"none":"";
}}),enabled:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
},refresh:function(){if(this.widget.enable){this.widget.enable(this.bindings.enabled.get());
}}}),disabled:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
},refresh:function(){if(this.widget.enable){this.widget.enable(!this.bindings.disabled.get());
}}}),source:z("source","dataSource","setDataSource"),value:p.extend({init:function(ac,Z,aa){p.fn.init.call(this,ac.element[0],Z,aa);
this.widget=ac;
this._change=l.proxy(this.change,this);
this.widget.first(u,this._change);
var ab=this.bindings.value.get();
this._valueIsObservableObject=!aa.valuePrimitive&&(ab==null||ab instanceof J);
this._valueIsObservableArray=ab instanceof I;
this._initChange=false;
},_source:function(){var Z;
if(this.widget.dataItem){Z=this.widget.dataItem();
if(Z&&Z instanceof J){return[Z];
}}if(this.bindings.source){Z=this.bindings.source.get();
}if(!Z||Z instanceof E.data.DataSource){Z=this.widget.dataSource.flatView();
}return Z;
},change:function(){var ah=this.widget.value(),Z=this.options.dataValueField||this.options.dataTextField,ab=P.call(ah)==="[object Array]",ac=this._valueIsObservableObject,ai,aj,ak=[],af,ag,aa,ad,ae;
this._initChange=true;
if(Z){if(ah===""&&(ac||this.options.valuePrimitive)){ah=null;
}else{ae=this._source();
if(ab){aj=ah.length;
ak=ah.slice(0);
}for(aa=0,ad=ae.length;
aa<ad;
aa++){af=ae[aa];
ag=af.get(Z);
if(ab){for(ai=0;
ai<aj;
ai++){if(ag==ak[ai]){ak[ai]=af;
break;
}}}else{if(ag==ah){ah=ac?af:ag;
break;
}}}if(ak[0]){if(this._valueIsObservableArray){ah=ak;
}else{if(ac||!Z){ah=ak[0];
}else{ah=ak[0].get(Z);
}}}}}this.bindings.value.set(ah);
this._initChange=false;
},refresh:function(){if(!this._initChange){var ah=this.widget;
var ab=ah.options;
var ad=ab.dataTextField;
var af=ab.dataValueField||ad;
var ae=this.bindings.value.get();
var ac=ab.text||"";
var Z=0,aa;
var ag=[];
if(ae===V){ae=null;
}if(af){if(ae instanceof I){for(aa=ae.length;
Z<aa;
Z++){ag[Z]=ae[Z].get(af);
}ae=ag;
}else{if(ae instanceof J){ac=ae.get(ad);
ae=ae.get(af);
}}}if(ab.autoBind===false&&!ab.cascadeFrom&&ah.listView&&!ah.listView.bound()){if(ad===af&&!ac){ac=ae;
}if(!ac&&(ae||ae===0)&&ab.valuePrimitive){ah.value(ae);
}else{ah._preselect(ae,ac);
}}else{ah.value(ae);
}}this._initChange=false;
},destroy:function(){this.widget.unbind(u,this._change);
}}),gantt:{dependencies:z("dependencies","dependencies","setDependenciesDataSource")},multiselect:{value:p.extend({init:function(ab,Z,aa){p.fn.init.call(this,ab.element[0],Z,aa);
this.widget=ab;
this._change=l.proxy(this.change,this);
this.widget.first(u,this._change);
this._initChange=false;
},change:function(){var al=this,ah=al.bindings[W].get(),am=al.options.valuePrimitive,af=am?al.widget.value():al.widget.dataItems();
var Z=this.options.dataValueField||this.options.dataTextField;
af=af.slice(0);
al._initChange=true;
if(ah instanceof I){var ai=[];
var ad=af.length;
var ab=0,ac=0;
var ag=ah[ab];
var ak=false;
var aj;
var ae;
var aa;
while(ag!==V){aa=false;
for(ac=0;
ac<ad;
ac++){if(am){ak=af[ac]==ag;
}else{ae=af[ac];
ae=ae.get?ae.get(Z):ae;
ak=ae==(ag.get?ag.get(Z):ag);
}if(ak){af.splice(ac,1);
ad-=1;
aa=true;
break;
}}if(!aa){ai.push(ag);
m(ah,ab,1);
aj=ab;
}else{ab+=1;
}ag=ah[ab];
}m(ah,ah.length,0,af);
if(ai.length){ah.trigger("change",{action:"remove",items:ai,index:aj});
}if(af.length){ah.trigger("change",{action:"add",items:af,index:ah.length-1});
}}else{al.bindings[W].set(af);
}al._initChange=false;
},refresh:function(){if(!this._initChange){var ad=this.options,ah=this.widget,aa=ad.dataValueField||ad.dataTextField,af=this.bindings.value.get(),Z=af,ab=0,ac,ag=[],ae;
if(af===V){af=null;
}if(aa){if(af instanceof I){for(ac=af.length;
ab<ac;
ab++){ae=af[ab];
ag[ab]=ae.get?ae.get(aa):ae;
}af=ag;
}else{if(af instanceof J){af=af.get(aa);
}}}if(ad.autoBind===false&&ad.valuePrimitive!==true&&!ah._isBound()){ah._preselect(Z,af);
}else{ah.value(af);
}}},destroy:function(){this.widget.unbind(u,this._change);
}})},scheduler:{source:z("source","dataSource","setDataSource").extend({dataBound:function(aa){var ac;
var ad;
var af=this.widget;
var ab=aa.addedItems||af.items();
var Z,ae;
if(ab.length){Z=aa.addedDataItems||af.dataItems();
ae=this.bindings.source._parents();
for(ac=0,ad=Z.length;
ac<ad;
ac++){o(ab[ac],Z[ac],this._ns(aa.ns),[Z[ac]].concat(ae));
}}}})}};
var m=function(ab,ac,af,Z){Z=Z||[];
af=af||0;
var aa=Z.length;
var ae=ab.length;
var ag=[].slice.call(ab,ac+af);
var ah=ag.length;
var ad;
if(aa){aa=ac+aa;
ad=0;
for(;
ac<aa;
ac++){ab[ac]=Z[ad];
ad++;
}ab.length=aa;
}else{if(af){ab.length=ac;
af+=ac;
while(ac<af){delete ab[--af];
}}}if(ah){ah=ac+ah;
ad=0;
for(;
ac<ah;
ac++){ab[ac]=ag[ad];
ad++;
}ab.length=ah;
}ac=ab.length;
while(ac<ae){delete ab[ac];
ac++;
}};
var s=w.extend({init:function(aa,Z){this.target=aa;
this.options=Z;
this.toDestroy=[];
},bind:function(Z){var af,ae,ad,ac,aa,ab,ah=this instanceof Y,ag=this.binders();
for(af in Z){if(af==W){ae=true;
}else{if(af==N){ad=true;
}else{if(af==C&&!ah){ac=true;
}else{if(af==v){aa=true;
}else{if(af==y){ab=true;
}else{this.applyBinding(af,Z,ag);
}}}}}}if(ad){this.applyBinding(N,Z,ag);
}if(ae){this.applyBinding(W,Z,ag);
}if(aa){this.applyBinding(v,Z,ag);
}if(ac&&!ah){this.applyBinding(C,Z,ag);
}if(ab&&!ah){this.applyBinding(y,Z,ag);
}},binders:function(){return q[this.target.nodeName.toLowerCase()]||{};
},applyBinding:function(ad,ac,ae){var aa=ae[ad]||q[ad],af=this.toDestroy,Z,ab=ac[ad];
if(aa){aa=new aa(this.target,ac,this.options);
af.push(aa);
if(ab instanceof r){aa.bind(ab);
af.push(ab);
}else{for(Z in ab){aa.bind(ab,Z);
af.push(ab[Z]);
}}}else{if(ad!=="template"){throw new Error("The "+ad+" binding is not supported by the "+this.target.nodeName.toLowerCase()+" element");
}}},destroy:function(){var Z,aa,ab=this.toDestroy;
for(Z=0,aa=ab.length;
Z<aa;
Z++){ab[Z].destroy();
}}});
var Y=s.extend({binders:function(){return q.widget[this.target.options.name.toLowerCase()]||{};
},applyBinding:function(ad,ac,ae){var aa=ae[ad]||q.widget[ad],af=this.toDestroy,Z,ab=ac[ad];
if(aa){aa=new aa(this.target,ac,this.target.options);
af.push(aa);
if(ab instanceof r){aa.bind(ab);
af.push(ab);
}else{for(Z in ab){aa.bind(ab,Z);
af.push(ab[Z]);
}}}else{throw new Error("The "+ad+" binding is not supported by the "+this.target.options.name+" widget");
}}});
function t(Z,aa){var ab=E.initWidget(Z,{},aa);
if(ab){return new Y(ab);
}}var F=/[A-Za-z0-9_\-]+:(\{([^}]*)\}|[^,}]+)/g,X=/\s/g;
function K(Z){var ae={},ab,ad,af,aa,ac,ah,ag;
ag=Z.match(F);
for(ab=0,ad=ag.length;
ab<ad;
ab++){af=ag[ab];
aa=af.indexOf(":");
ac=af.substring(0,aa);
ah=af.substring(aa+1);
if(ah.charAt(0)=="{"){ah=K(ah);
}ae[ac]=ah;
}return ae;
}function x(aa,ac,ad){var Z,ab={};
for(Z in aa){ab[Z]=new ad(ac,aa[Z]);
}return ab;
}function o(ae,ak,aj,ah){var ai=ae.getAttribute("data-"+E.ns+"role"),af,Z=ae.getAttribute("data-"+E.ns+"bind"),ab=ae.children,ac=[],ad=true,aa,ag={},al;
ah=ah||[ak];
if(ai||Z){S(ae,false);
}if(ai){al=t(ae,aj);
}if(Z){Z=K(Z.replace(X,""));
if(!al){ag=E.parseOptions(ae,{textField:"",valueField:"",template:"",valueUpdate:u,valuePrimitive:false,autoBind:true});
ag.roles=aj;
al=new s(ae,ag);
}al.source=ak;
aa=x(Z,ah,r);
if(ag.template){aa.template=new O(ah,"",ag.template);
}if(aa.click){Z.events=Z.events||{};
Z.events.click=Z.click;
aa.click.destroy();
delete aa.click;
}if(aa.source){ad=false;
}if(Z.attr){aa.attr=x(Z.attr,ah,r);
}if(Z.style){aa.style=x(Z.style,ah,r);
}if(Z.events){aa.events=x(Z.events,ah,B);
}if(Z.css){aa.css=x(Z.css,ah,r);
}al.bind(aa);
}if(al){ae.kendoBindingTarget=al;
}if(ad&&ab){for(af=0;
af<ab.length;
af++){ac[af]=ab[af];
}for(af=0;
af<ac.length;
af++){o(ac[af],ak,aj,ah);
}}}function n(Z,ad){var aa,ab,ac,ae=E.rolesFromNamespaces([].slice.call(arguments,2));
ad=E.observable(ad);
Z=l(Z);
for(aa=0,ab=Z.length;
aa<ab;
aa++){ac=Z[aa];
if(ac.nodeType===1){o(ac,ad,ae);
}}}function S(ab,aa){var Z=ab.kendoBindingTarget;
if(Z){Z.destroy();
if(A){delete ab.kendoBindingTarget;
}else{if(ab.removeAttribute){ab.removeAttribute("kendoBindingTarget");
}else{ab.kendoBindingTarget=null;
}}}if(aa){var ac=E.widgetInstance(l(ab));
if(ac&&typeof ac.destroy===D){ac.destroy();
}}}function U(aa,Z){S(aa,Z);
T(aa,Z);
}function T(ab,aa){var Z=ab.children;
if(Z){for(var ac=0,ad=Z.length;
ac<ad;
ac++){U(Z[ac],aa);
}}}function R(Z){var aa,ab;
Z=l(Z);
for(aa=0,ab=Z.length;
aa<ab;
aa++){U(Z[aa],false);
}}function G(ac,ab){var aa=ac.element,Z=aa[0].kendoBindingTarget;
if(Z){n(aa,Z.source,ab);
}}function M(ac,ad){var ae=[];
var Z=0;
var ab;
var aa;
if(!ad){return ac;
}if(ac instanceof I){for(ab=ac.length;
Z<ab;
Z++){aa=ac[Z];
ae[Z]=aa.get?aa.get(ad):aa[ad];
}ac=ae;
}else{if(ac instanceof J){ac=ac.get(ad);
}}return ac;
}E.unbind=R;
E.bind=n;
E.data.binders=q;
E.data.Binder=p;
E.notify=G;
E.observable=function(Z){if(!(Z instanceof J)){Z=new J(Z);
}return Z;
};
E.observableHierarchy=function(Z){var aa=E.data.HierarchicalDataSource.create(Z);
function ab(ad){var ae,ac;
for(ae=0;
ae<ad.length;
ae++){ad[ae]._initChildren();
ac=ad[ae].children;
ac.fetch();
ad[ae].items=ac.data();
ab(ad[ae].items);
}}aa.fetch();
ab(aa.data());
aa._data._dataSource=aa;
return aa._data;
};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
