(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.calendar",["kendo.core"],l);
}(function(){var k={id:"calendar",name:"Calendar",category:"web",description:"The Calendar widget renders a graphical calendar that supports navigation and selection.",depends:["core"]};
(function(l,aE){var V=window.kendo,ax=V.support,aD=V.ui,aI=aD.Widget,X=V.keys,ao=V.parseDate,m=V.date.adjustDST,F=V._extractFormat,ay=V.template,K=V.getCulture,aC=V.support.transitions,aB=aC?aC.css+"transform-origin":"",u=ay('<td#=data.cssClass# role="gridcell"><a tabindex="-1" class="k-link" href="\\#" data-#=data.ns#value="#=data.dateString#">#=data.value#</a></td>',{useWithBlock:false}),D=ay('<td role="gridcell">&nbsp;</td>',{useWithBlock:false}),q=V.support.browser,T=q.msie&&q.version<9,al=".kendoCalendar",x="click"+al,W="keydown"+al,O="id",aa="min",Y="left",aw="slideIn",ab="month",v="century",w="change",ai="navigate",aF="value",N="k-state-hover",C="k-state-disabled",I="k-state-focused",am="k-other-month",an=' class="'+am+'"',aA="k-nav-today",t="td:has(.k-link)",p="blur"+al,G="focus",H=G+al,ac=ax.touch?"touchstart":"mouseenter",ad=ax.touch?"touchstart"+al:"mouseenter"+al,ae=ax.touch?"touchend"+al+" touchmove"+al:"mouseleave"+al,ah=60000,ag=86400000,ap="_prevArrow",aj="_nextArrow",n="aria-disabled",o="aria-selected",ar=l.proxy,E=l.extend,B=Date,aH={month:0,year:1,decade:2,century:3};
var s=aI.extend({init:function(aJ,aL){var aM=this,aN,aK;
aI.fn.init.call(aM,aJ,aL);
aJ=aM.wrapper=aM.element;
aL=aM.options;
aL.url=window.unescape(aL.url);
aM.options.disableDates=L(aM.options.disableDates);
aM._templates();
aM._header();
aM._footer(aM.footer);
aK=aJ.addClass("k-widget k-calendar").on(ad+" "+ae,t,af).on(W,"table.k-content",ar(aM._move,aM)).on(x,t,function(aO){var aP=aO.currentTarget.firstChild,aQ=aM._toDateObject(aP);
if(aP.href.indexOf("#")!=-1){aO.preventDefault();
}if(aM.options.disableDates(aQ)&&aM._view.name=="month"){return;
}aM._click(l(aP));
}).on("mouseup"+al,"table.k-content, .k-footer",function(){aM._focusView(aM.options.focusOnNav!==false);
}).attr(O);
if(aK){aM._cellID=aK+"_cell_selected";
}ak(aL);
aN=ao(aL.value,aL.format,aL.culture);
aM._index=aH[aL.start];
aM._current=new B(+at(aN,aL.min,aL.max));
aM._addClassProxy=function(){aM._active=true;
if(aM._cell.hasClass(C)){var aO=aM._view.toDateString(M());
aM._cell=aM._cellByDate(aO);
}aM._cell.addClass(I);
};
aM._removeClassProxy=function(){aM._active=false;
aM._cell.removeClass(I);
};
aM.value(aN);
V.notify(aM);
},options:{name:"Calendar",value:null,min:new B(1900,0,1),max:new B(2099,11,31),dates:[],url:"",culture:"",footer:"",format:"",month:{},start:ab,depth:ab,animation:{horizontal:{effects:aw,reverse:true,duration:500,divisor:2},vertical:{effects:"zoomIn",duration:400}}},events:[w,ai],setOptions:function(aJ){var aK=this;
ak(aJ);
if(!aJ.dates[0]){aJ.dates=aK.options.dates;
}aJ.disableDates=L(aJ.disableDates);
aI.fn.setOptions.call(aK,aJ);
aK._templates();
aK._footer(aK.footer);
aK._index=aH[aK.options.start];
aK.navigate();
},destroy:function(){var aJ=this,aK=aJ._today;
aJ.element.off(al);
aJ._title.off(al);
aJ[ap].off(al);
aJ[aj].off(al);
V.destroy(aJ._table);
if(aK){V.destroy(aK.off(al));
}aI.fn.destroy.call(aJ);
},current:function(){return this._current;
},view:function(){return this._view;
},focus:function(aJ){aJ=aJ||this._table;
this._bindTable(aJ);
aJ.focus();
},min:function(aJ){return this._option(aa,aJ);
},max:function(aJ){return this._option("max",aJ);
},navigateToPast:function(){this._navigate(ap,-1);
},navigateToFuture:function(){this._navigate(aj,1);
},navigateUp:function(){var aK=this,aJ=aK._index;
if(aK._title.hasClass(C)){return;
}aK.navigate(aK._current,++aJ);
},navigateDown:function(aM){var aL=this,aK=aL._index,aJ=aL.options.depth;
if(!aM){return;
}if(aK===aH[aJ]){if(!Q(aL._value,aL._current)||!Q(aL._value,aM)){aL.value(aM);
aL.trigger(w);
}return;
}aL.navigate(aM,--aK);
},navigate:function(aZ,a1){a1=isNaN(a1)?aH[a1]:a1;
var aW=this,aT=aW.options,aK=aT.culture,aR=aT.min,aQ=aT.max,aX=aW._title,aO=aW._table,aS=aW._oldTable,aV=aW._value,aL=aW._current,aP=aZ&&+aZ>+aL,a0=a1!==aE&&a1!==aW._index,aY,aM,aJ,aN;
if(!aZ){aZ=aL;
}aW._current=aZ=new B(+at(aZ,aR,aQ));
if(a1===aE){a1=aW._index;
}else{aW._index=a1;
}aW._view=aM=r.views[a1];
aJ=aM.compare;
aN=a1===aH[v];
aX.toggleClass(C,aN).attr(n,aN);
aN=aJ(aZ,aR)<1;
aW[ap].toggleClass(C,aN).attr(n,aN);
aN=aJ(aZ,aQ)>-1;
aW[aj].toggleClass(C,aN).attr(n,aN);
if(aO&&aS&&aS.data("animating")){aS.kendoStop(true,true);
aO.kendoStop(true,true);
}aW._oldTable=aO;
if(!aO||aW._changeView){aX.html(aM.title(aZ,aR,aQ,aK));
aW._table=aY=l(aM.content(E({min:aR,max:aQ,date:aZ,url:aT.url,dates:aT.dates,format:aT.format,culture:aK,disableDates:aT.disableDates},aW[aM.name])));
Z(aY);
var aU=aO&&aO.data("start")===aY.data("start");
aW._animate({from:aO,to:aY,vertical:a0,future:aP,replace:aU});
aW.trigger(ai);
aW._focus(aZ);
}if(a1===aH[aT.depth]&&aV&&!aW.options.disableDates(aV)){aW._class("k-state-selected",aV);
}aW._class(I,aZ);
if(!aO&&aW._cell){aW._cell.removeClass(I);
}aW._changeView=true;
},value:function(aO){var aN=this,aP=aN._view,aM=aN.options,aL=aN._view,aK=aM.min,aJ=aM.max;
if(aO===aE){return aN._value;
}if(aO===null){aN._current=new Date(aN._current.getFullYear(),aN._current.getMonth(),aN._current.getDate());
}aO=ao(aO,aM.format,aM.culture);
if(aO!==null){aO=new B(+aO);
if(!U(aO,aK,aJ)){aO=null;
}}if(!aN.options.disableDates(aO)){aN._value=aO;
}else{if(aN._value===aE){aN._value=null;
}}if(aL&&aO===null&&aN._cell){aN._cell.removeClass("k-state-selected");
}else{aN._changeView=!aO||aP&&aP.compare(aO,aN._current)!==0;
aN.navigate(aO);
}},_move:function(aK){var aV=this,aS=aV.options,aO=aK.keyCode,aX=aV._view,aL=aV._index,aR=aV.options.min,aP=aV.options.max,aJ=new B(+aV._current),aN=V.support.isRtl(aV.wrapper),aM=aV.options.disableDates,aW,aT,aQ,aU;
if(aK.target===aV._table[0]){aV._active=true;
}if(aK.ctrlKey){if(aO==X.RIGHT&&!aN||aO==X.LEFT&&aN){aV.navigateToFuture();
aT=true;
}else{if(aO==X.LEFT&&!aN||aO==X.RIGHT&&aN){aV.navigateToPast();
aT=true;
}else{if(aO==X.UP){aV.navigateUp();
aT=true;
}else{if(aO==X.DOWN){aV._click(l(aV._cell[0].firstChild));
aT=true;
}}}}}else{if(aO==X.RIGHT&&!aN||aO==X.LEFT&&aN){aW=1;
aT=true;
}else{if(aO==X.LEFT&&!aN||aO==X.RIGHT&&aN){aW=-1;
aT=true;
}else{if(aO==X.UP){aW=aL===0?-7:-4;
aT=true;
}else{if(aO==X.DOWN){aW=aL===0?7:4;
aT=true;
}else{if(aO==X.ENTER){aV._click(l(aV._cell[0].firstChild));
aT=true;
}else{if(aO==X.HOME||aO==X.END){aQ=aO==X.HOME?"first":"last";
aU=aX[aQ](aJ);
aJ=new B(aU.getFullYear(),aU.getMonth(),aU.getDate(),aJ.getHours(),aJ.getMinutes(),aJ.getSeconds(),aJ.getMilliseconds());
aT=true;
}else{if(aO==X.PAGEUP){aT=true;
aV.navigateToPast();
}else{if(aO==X.PAGEDOWN){aT=true;
aV.navigateToFuture();
}}}}}}}}if(aW||aQ){if(!aQ){aX.setDate(aJ,aW);
}if(aM(aJ)){aJ=aV._nextNavigatable(aJ,aW);
}if(U(aJ,aR,aP)){aV._focus(at(aJ,aS.min,aS.max));
}}}if(aT){aK.preventDefault();
}return aV._current;
},_nextNavigatable:function(aJ,aQ){var aP=this,aK=true,aR=aP._view,aN=aP.options.min,aM=aP.options.max,aL=aP.options.disableDates,aO=new Date(aJ.getTime());
aR.setDate(aO,-aQ);
while(aK){aR.setDate(aJ,aQ);
if(!U(aJ,aN,aM)){aJ=aO;
break;
}aK=aL(aJ);
}return aJ;
},_animate:function(aL){var aM=this,aK=aL.from,aN=aL.to,aJ=aM._active;
if(!aK){aN.insertAfter(aM.element[0].firstChild);
aM._bindTable(aN);
}else{if(aK.parent().data("animating")){aK.off(al);
aK.parent().kendoStop(true,true).remove();
aK.remove();
aN.insertAfter(aM.element[0].firstChild);
aM._focusView(aJ);
}else{if(!aK.is(":visible")||aM.options.animation===false||aL.replace){aN.insertAfter(aK);
aK.off(al).remove();
aM._focusView(aJ);
}else{aM[aL.vertical?"_vertical":"_horizontal"](aK,aN,aL.future);
}}}},_horizontal:function(aL,aP,aM){var aO=this,aJ=aO._active,aN=aO.options.animation.horizontal,aK=aN.effects,aQ=aL.outerWidth();
if(aK&&aK.indexOf(aw)!=-1){aL.add(aP).css({width:aQ});
aL.wrap("<div/>");
aO._focusView(aJ,aL);
aL.parent().css({position:"relative",width:aQ*2,"float":Y,"margin-left":aM?0:-aQ});
aP[aM?"insertAfter":"insertBefore"](aL);
E(aN,{effects:aw+":"+(aM?"right":Y),complete:function(){aL.off(al).remove();
aO._oldTable=null;
aP.unwrap();
aO._focusView(aJ);
}});
aL.parent().kendoStop(true,true).kendoAnimate(aN);
}},_vertical:function(aM,aP){var aO=this,aQ=aO.options.animation.vertical,aL=aQ.effects,aJ=aO._active,aK,aN;
if(aL&&aL.indexOf("zoom")!=-1){aP.css({position:"absolute",top:aM.prev().outerHeight(),left:0}).insertBefore(aM);
if(aB){aK=aO._cellByDate(aO._view.toDateString(aO._current));
aN=aK.position();
aN=aN.left+parseInt(aK.width()/2,10)+"px "+(aN.top+parseInt(aK.height()/2,10)+"px");
aP.css(aB,aN);
}aM.kendoStop(true,true).kendoAnimate({effects:"fadeOut",duration:600,complete:function(){aM.off(al).remove();
aO._oldTable=null;
aP.css({position:"static",top:0,left:0});
aO._focusView(aJ);
}});
aP.kendoStop(true,true).kendoAnimate(aQ);
}},_cellByDate:function(aJ){return this._table.find("td:not(."+am+")").filter(function(){return l(this.firstChild).attr(V.attr(aF))===aJ;
});
},_class:function(aK,aL){var aO=this,aN=aO._cellID,aJ=aO._cell,aP=aO._view.toDateString(aL),aM;
if(aJ){aJ.removeAttr(o).removeAttr("aria-label").removeAttr(O);
}if(aL){aM=aO.options.disableDates(aL);
}aJ=aO._table.find("td:not(."+am+")").removeClass(aK).filter(function(){return l(this.firstChild).attr(V.attr(aF))===aP;
}).attr(o,true);
if(aK===I&&!aO._active&&aO.options.focusOnNav!==false||aM){aK="";
}aJ.addClass(aK);
if(aJ[0]){aO._cell=aJ;
}if(aN){aJ.attr(O,aN);
aO._table.removeAttr("aria-activedescendant").attr("aria-activedescendant",aN);
}},_bindTable:function(aJ){aJ.on(H,this._addClassProxy).on(p,this._removeClassProxy);
},_click:function(aK){var aM=this,aL=aM.options,aJ=new Date(+aM._current),aN=aM._toDateObject(aK);
m(aN,0);
if(aM.options.disableDates(aN)&&aM._view.name=="month"){aN=aM._value;
}aM._view.setDate(aJ,aN);
aM.navigateDown(at(aJ,aL.min,aL.max));
},_focus:function(aK){var aJ=this,aL=aJ._view;
if(aL.compare(aK,aJ._current)!==0){aJ.navigate(aK);
}else{aJ._current=aK;
aJ._class(I,aK);
}},_focusView:function(aJ,aK){if(aJ){this.focus(aK);
}},_footer:function(aL){var aM=this,aN=M(),aJ=aM.element,aK=aJ.find(".k-footer");
if(!aL){aM._toggle(false);
aK.hide();
return;
}if(!aK[0]){aK=l('<div class="k-footer"><a href="#" class="k-link k-nav-today"></a></div>').appendTo(aJ);
}aM._today=aK.show().find(".k-link").html(aL(aN)).attr("title",V.toString(aN,"D",aM.options.culture));
aM._toggle();
},_header:function(){var aL=this,aJ=aL.element,aK;
if(!aJ.find(".k-header")[0]){aJ.html('<div class="k-header"><a href="#" role="button" class="k-link k-nav-prev"><span class="k-icon k-i-arrow-w"></span></a><a href="#" role="button" aria-live="assertive" aria-atomic="true" class="k-link k-nav-fast"></a><a href="#" role="button" class="k-link k-nav-next"><span class="k-icon k-i-arrow-e"></span></a></div>');
}aK=aJ.find(".k-link").on(ad+" "+ae+" "+H+" "+p,af).click(false);
aL._title=aK.eq(1).on(x,function(){aL._active=aL.options.focusOnNav!==false;
aL.navigateUp();
});
aL[ap]=aK.eq(0).on(x,function(){aL._active=aL.options.focusOnNav!==false;
aL.navigateToPast();
});
aL[aj]=aK.eq(2).on(x,function(){aL._active=aL.options.focusOnNav!==false;
aL.navigateToFuture();
});
},_navigate:function(aJ,aM){var aN=this,aL=aN._index+1,aK=new B(+aN._current);
aJ=aN[aJ];
if(!aJ.hasClass(C)){if(aL>3){aK.setFullYear(aK.getFullYear()+100*aM);
}else{r.views[aL].setDate(aK,aM);
}aN.navigate(aK);
}},_option:function(aL,aO){var aN=this,aM=aN.options,aJ=aN._value||aN._current,aK;
if(aO===aE){return aM[aL];
}aO=ao(aO,aM.format,aM.culture);
if(!aO){return;
}aM[aL]=new B(+aO);
if(aL===aa){aK=aO>aJ;
}else{aK=aJ>aO;
}if(aK||S(aJ,aO)){if(aK){aN._value=null;
}aN._changeView=true;
}if(!aN._changeView){aN._changeView=!!(aM.month.content||aM.month.empty);
}aN.navigate(aN._value);
aN._toggle();
},_toggle:function(aN){var aM=this,aL=aM.options,aJ=aM.options.disableDates(M()),aK=aM._today;
if(aN===aE){aN=U(M(),aL.min,aL.max);
}if(aK){aK.off(x);
if(aN&&!aJ){aK.addClass(aA).removeClass(C).on(x,ar(aM._todayClick,aM));
}else{aK.removeClass(aA).addClass(C).on(x,aq);
}}},_todayClick:function(aL){var aM=this,aJ=aH[aM.options.depth],aK=aM.options.disableDates,aN=M();
aL.preventDefault();
if(aK(aN)){return;
}if(aM._view.compare(aM._current,aN)===0&&aM._index==aJ){aM._changeView=false;
}aM._value=aN;
aM.navigate(aN,aJ);
aM.trigger(w);
},_toDateObject:function(aJ){var aK=l(aJ).attr(V.attr(aF)).split("/");
aK=new B(aK[0],aK[1],aK[2]);
return aK;
},_templates:function(){var aO=this,aN=aO.options,aL=aN.footer,aM=aN.month,aJ=aM.content,aK=aM.empty;
aO.month={content:ay('<td#=data.cssClass# role="gridcell"><a tabindex="-1" class="k-link#=data.linkClass#" href="#=data.url#" '+V.attr("value")+'="#=data.dateString#" title="#=data.title#">'+(aJ||"#=data.value#")+"</a></td>",{useWithBlock:!!aJ}),empty:ay('<td role="gridcell">'+(aK||"&nbsp;")+"</td>",{useWithBlock:!!aK})};
aO.footer=aL!==false?ay(aL||'#= kendo.toString(data,"D","'+aN.culture+'") #',{useWithBlock:false}):null;
}});
aD.plugin(s);
var r={firstDayOfMonth:function(aJ){return new B(aJ.getFullYear(),aJ.getMonth(),1);
},firstVisibleDay:function(aK,aJ){aJ=aJ||V.culture().calendar;
var aL=aJ.firstDay,aM=new B(aK.getFullYear(),aK.getMonth(),0,aK.getHours(),aK.getMinutes(),aK.getSeconds(),aK.getMilliseconds());
while(aM.getDay()!=aL){r.setTime(aM,-1*ag);
}return aM;
},setTime:function(aJ,aL){var aM=aJ.getTimezoneOffset(),aK=new B(aJ.getTime()+aL),aN=aK.getTimezoneOffset()-aM;
aJ.setTime(aK.getTime()+aN*ah);
},views:[{name:ab,title:function(aK,aM,aL,aJ){return J(aJ).months.names[aK.getMonth()]+" "+aK.getFullYear();
},content:function(aZ){var a2=this,aT=0,aW=aZ.min,aV=aZ.max,aL=aZ.date,aM=aZ.dates,aQ=aZ.format,aJ=aZ.culture,aY=aZ.url,aR=aY&&aM[0],aK=J(aJ),aO=aK.firstDay,aN=aK.days,aX=av(aN.names,aO),a0=av(aN.namesShort,aO),a1=r.firstVisibleDay(aL,aK),aP=a2.first(aL),aU=a2.last(aL),a3=a2.toDateString,a4=new B(),aS='<table tabindex="0" role="grid" class="k-content" cellspacing="0" data-start="'+a3(a1)+'"><thead><tr role="row">';
for(;
aT<7;
aT++){aS+='<th scope="col" title="'+aX[aT]+'">'+a0[aT]+"</th>";
}a4=new B(a4.getFullYear(),a4.getMonth(),a4.getDate());
m(a4,0);
a4=+a4;
return aG({cells:42,perRow:7,html:aS+='</tr></thead><tbody><tr role="row">',start:a1,min:new B(aW.getFullYear(),aW.getMonth(),aW.getDate()),max:new B(aV.getFullYear(),aV.getMonth(),aV.getDate()),content:aZ.content,empty:aZ.empty,setter:a2.setDate,disableDates:aZ.disableDates,build:function(a6,a9,a8){var a5=[],a7=a6.getDay(),ba="",bb="#";
if(a6<aP||a6>aU){a5.push(am);
}if(a8(a6)){a5.push(C);
}if(+a6===a4){a5.push("k-today");
}if(a7===0||a7===6){a5.push("k-weekend");
}if(aR&&P(+a6,aM)){bb=aY.replace("{0}",V.toString(a6,aQ,aJ));
ba=" k-action-link";
}return{date:a6,dates:aM,ns:V.ns,title:V.toString(a6,"D",aJ),value:a6.getDate(),dateString:a3(a6),cssClass:a5[0]?' class="'+a5.join(" ")+'"':"",linkClass:ba,url:bb};
}});
},first:function(aJ){return r.firstDayOfMonth(aJ);
},last:function(aJ){var aL=new B(aJ.getFullYear(),aJ.getMonth()+1,0),aK=r.firstDayOfMonth(aJ),aM=Math.abs(aL.getTimezoneOffset()-aK.getTimezoneOffset());
if(aM){aL.setHours(aK.getHours()+aM/60);
}return aL;
},compare:function(aJ,aK){var aN,aL=aJ.getMonth(),aO=aJ.getFullYear(),aM=aK.getMonth(),aP=aK.getFullYear();
if(aO>aP){aN=1;
}else{if(aO<aP){aN=-1;
}else{aN=aL==aM?0:aL>aM?1:-1;
}}return aN;
},setDate:function(aJ,aL){var aK=aJ.getHours();
if(aL instanceof B){aJ.setFullYear(aL.getFullYear(),aL.getMonth(),aL.getDate());
}else{r.setTime(aJ,aL*ag);
}m(aJ,aK);
},toDateString:function(aJ){return aJ.getFullYear()+"/"+aJ.getMonth()+"/"+aJ.getDate();
}},{name:"year",title:function(aJ){return aJ.getFullYear();
},content:function(aM){var aL=J(aM.culture).months.namesAbbr,aN=this.toDateString,aK=aM.min,aJ=aM.max;
return aG({min:new B(aK.getFullYear(),aK.getMonth(),1),max:new B(aJ.getFullYear(),aJ.getMonth(),1),start:new B(aM.date.getFullYear(),0,1),setter:this.setDate,build:function(aO){return{value:aL[aO.getMonth()],ns:V.ns,dateString:aN(aO),cssClass:""};
}});
},first:function(aJ){return new B(aJ.getFullYear(),0,aJ.getDate());
},last:function(aJ){return new B(aJ.getFullYear(),11,aJ.getDate());
},compare:function(aJ,aK){return y(aJ,aK);
},setDate:function(aJ,aM){var aL,aK=aJ.getHours();
if(aM instanceof B){aL=aM.getMonth();
aJ.setFullYear(aM.getFullYear(),aL,aJ.getDate());
if(aL!==aJ.getMonth()){aJ.setDate(0);
}}else{aL=aJ.getMonth()+aM;
aJ.setMonth(aL);
if(aL>11){aL-=12;
}if(aL>0&&aJ.getMonth()!=aL){aJ.setDate(0);
}}m(aJ,aK);
},toDateString:function(aJ){return aJ.getFullYear()+"/"+aJ.getMonth()+"/1";
}},{name:"decade",title:function(aJ,aL,aK){return az(aJ,aL,aK,10);
},content:function(aJ){var aL=aJ.date.getFullYear(),aK=this.toDateString;
return aG({start:new B(aL-aL%10-1,0,1),min:new B(aJ.min.getFullYear(),0,1),max:new B(aJ.max.getFullYear(),0,1),setter:this.setDate,build:function(aM,aN){return{value:aM.getFullYear(),ns:V.ns,dateString:aK(aM),cssClass:aN===0||aN==11?an:""};
}});
},first:function(aJ){var aK=aJ.getFullYear();
return new B(aK-aK%10,aJ.getMonth(),aJ.getDate());
},last:function(aJ){var aK=aJ.getFullYear();
return new B(aK-aK%10+9,aJ.getMonth(),aJ.getDate());
},compare:function(aJ,aK){return y(aJ,aK,10);
},setDate:function(aJ,aK){au(aJ,aK,1);
},toDateString:function(aJ){return aJ.getFullYear()+"/0/1";
}},{name:v,title:function(aJ,aL,aK){return az(aJ,aL,aK,100);
},content:function(aN){var aP=aN.date.getFullYear(),aL=aN.min.getFullYear(),aJ=aN.max.getFullYear(),aO=this.toDateString,aM=aL,aK=aJ;
aM=aM-aM%10;
aK=aK-aK%10;
if(aK-aM<10){aK=aM+9;
}return aG({start:new B(aP-aP%100-10,0,1),min:new B(aM,0,1),max:new B(aK,0,1),setter:this.setDate,build:function(aQ,aS){var aT=aQ.getFullYear(),aR=aT+9;
if(aT<aL){aT=aL;
}if(aR>aJ){aR=aJ;
}return{ns:V.ns,value:aT+" - "+aR,dateString:aO(aQ),cssClass:aS===0||aS==11?an:""};
}});
},first:function(aJ){var aK=aJ.getFullYear();
return new B(aK-aK%100,aJ.getMonth(),aJ.getDate());
},last:function(aJ){var aK=aJ.getFullYear();
return new B(aK-aK%100+99,aJ.getMonth(),aJ.getDate());
},compare:function(aJ,aK){return y(aJ,aK,100);
},setDate:function(aJ,aK){au(aJ,aK,10);
},toDateString:function(aJ){var aK=aJ.getFullYear();
return aK-aK%10+"/0/1";
}}]};
function az(aJ,aN,aL,aP){var aQ=aJ.getFullYear(),aO=aN.getFullYear(),aM=aL.getFullYear(),aK;
aQ=aQ-aQ%aP;
aK=aQ+(aP-1);
if(aQ<aO){aQ=aO;
}if(aK>aM){aK=aM;
}return aQ+"-"+aK;
}function aG(aT){var aP=0,aM,aS=aT.min,aR=aT.max,aV=aT.start,aU=aT.setter,aJ=aT.build,aQ=aT.cells||12,aK=aT.perRow||4,aL=aT.content||u,aN=aT.empty||D,aO=aT.html||'<table tabindex="0" role="grid" class="k-content k-meta-view" cellspacing="0"><tbody><tr role="row">';
for(;
aP<aQ;
aP++){if(aP>0&&aP%aK===0){aO+='</tr><tr role="row">';
}aV=new B(aV.getFullYear(),aV.getMonth(),aV.getDate(),0,0,0);
m(aV,0);
aM=aJ(aV,aP,aT.disableDates);
aO+=U(aV,aS,aR)?aL(aM):aN(aM);
aU(aV,1);
}return aO+"</tr></tbody></table>";
}function y(aJ,aK,aM){var aP=aJ.getFullYear(),aO=aK.getFullYear(),aL=aO,aN=0;
if(aM){aO=aO-aO%aM;
aL=aO-aO%aM+aM-1;
}if(aP>aL){aN=1;
}else{if(aP<aO){aN=-1;
}}return aN;
}function M(){var aJ=new B();
return new B(aJ.getFullYear(),aJ.getMonth(),aJ.getDate());
}function at(aM,aK,aJ){var aL=M();
if(aM){aL=new B(+aM);
}if(aK>aL){aL=new B(+aK);
}else{if(aJ<aL){aL=new B(+aJ);
}}return aL;
}function U(aJ,aL,aK){return +aJ>=+aL&&+aJ<=+aK;
}function av(aJ,aK){return aJ.slice(aK).concat(aJ.slice(0,aK));
}function au(aJ,aL,aK){aL=aL instanceof B?aL.getFullYear():aJ.getFullYear()+aK*aL;
aJ.setFullYear(aL);
}function af(aK){var aJ=l(this).hasClass("k-state-disabled");
if(!aJ){l(this).toggleClass(N,ac.indexOf(aK.type)>-1||aK.type==G);
}}function aq(aJ){aJ.preventDefault();
}function J(aJ){return K(aJ).calendars.standard;
}function ak(aL){var aM=aH[aL.start],aK=aH[aL.depth],aJ=K(aL.culture);
aL.format=F(aL.format||aJ.calendars.standard.patterns.d);
if(isNaN(aM)){aM=0;
aL.start=ab;
}if(aK===aE||aK>aM){aL.depth=ab;
}if(!aL.dates){aL.dates=[];
}}function Z(aJ){if(T){aJ.find("*").attr("unselectable","on");
}}function P(aJ,aK){for(var aL=0,aM=aK.length;
aL<aM;
aL++){if(aJ===+aK[aL]){return true;
}}return false;
}function R(aJ,aK){if(aJ){return aJ.getFullYear()===aK.getFullYear()&&aJ.getMonth()===aK.getMonth()&&aJ.getDate()===aK.getDate();
}return false;
}function S(aJ,aK){if(aJ){return aJ.getFullYear()===aK.getFullYear()&&aJ.getMonth()===aK.getMonth();
}return false;
}function L(aJ){if(V.isFunction(aJ)){return aJ;
}if(l.isArray(aJ)){return A(aJ);
}return l.noop;
}function z(aJ){var aL=[];
for(var aK=0;
aK<aJ.length;
aK++){aL.push(aJ[aK].setHours(0,0,0,0));
}return aL;
}function A(aL){var aJ,aK,aO=[],aN=["su","mo","tu","we","th","fr","sa"],aR="if (found) { return true } else {return false}";
if(aL[0] instanceof B){aO=z(aL);
aJ="var found = date && $.inArray(date.setHours(0, 0, 0, 0),["+aO+"]) > -1;"+aR;
}else{for(var aP=0;
aP<aL.length;
aP++){var aM=aL[aP].slice(0,2).toLowerCase();
var aQ=l.inArray(aM,aN);
if(aQ>-1){aO.push(aQ);
}}aJ="var found = date && $.inArray(date.getDay(),["+aO+"]) > -1;"+aR;
}aK=new Function("date",aJ);
return aK;
}function Q(aK,aJ){if(aK instanceof Date&&aJ instanceof Date){aK=aK.getTime();
aJ=aJ.getTime();
}return aK===aJ;
}r.isEqualDatePart=R;
r.makeUnselectable=Z;
r.restrictValue=at;
r.isInRange=U;
r.normalize=ak;
r.viewsEnum=aH;
r.disabled=L;
V.calendar=r;
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
