(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.datetimepicker",["kendo.datepicker","kendo.timepicker"],l);
}(function(){var k={id:"datetimepicker",name:"DateTimePicker",category:"web",description:"The DateTimePicker allows the end user to select a value from a calendar or a time drop-down list.",depends:["datepicker","timepicker"]};
(function(l,ac){var K=window.kendo,Z=K.TimeView,T=K.parseDate,m=K._activeElement,D=K._extractFormat,t=K.calendar,J=t.isInRange,W=t.restrictValue,I=t.isEqualDatePart,F=Z.getMilliseconds,ab=K.ui,ad=ab.Widget,S="open",w="close",u="change",R=".kendoDateTimePicker",v="click"+R,B="disabled",V="readonly",A="k-state-default",E="k-state-focused",G="k-state-hover",Y="k-state-disabled",H="mouseenter"+R+" mouseleave"+R,P="mousedown"+R,O="month",X="<span/>",n="aria-activedescendant",p="aria-expanded",q="aria-hidden",r="aria-owns",o="aria-disabled",s="aria-readonly",x=Date,N=new x(1800,0,1),M=new x(2099,11,31),z={view:"date"},aa={view:"time"},C=l.extend;
var y=ad.extend({init:function(ag,ah){var ai=this,ae;
ad.fn.init.call(ai,ag,ah);
ag=ai.element;
ah=ai.options;
ah.disableDates=K.calendar.disabled(ah.disableDates);
ah.min=T(ag.attr("min"))||T(ah.min);
ah.max=T(ag.attr("max"))||T(ah.max);
Q(ah);
ai._initialOptions=C({},ah);
ai._wrapper();
ai._views();
ai._icons();
ai._reset();
ai._template();
try{ag[0].setAttribute("type","text");
}catch(af){ag[0].type="text";
}ag.addClass("k-input").attr({role:"combobox","aria-expanded":false});
ai._midnight=ai._calculateMidnight(ah.min,ah.max);
ae=ag.is("[disabled]")||l(ai.element).parents("fieldset").is(":disabled");
if(ae){ai.enable(false);
}else{ai.readonly(ag.is("[readonly]"));
}ai._old=ai._update(ah.value||ai.element.val());
ai._oldText=ag.val();
K.notify(ai);
},options:{name:"DateTimePicker",value:null,format:"",timeFormat:"",culture:"",parseFormats:[],dates:[],min:new x(N),max:new x(M),interval:30,height:200,footer:"",start:O,depth:O,animation:{},month:{},ARIATemplate:'Current focused date is #=kendo.toString(data.current, "d")#'},events:[S,w,u],setOptions:function(ah){var ai=this,aj=ai._value,ag,af,ae;
ad.fn.setOptions.call(ai,ah);
ah=ai.options;
ah.min=ag=T(ah.min);
ah.max=af=T(ah.max);
Q(ah);
ai._midnight=ai._calculateMidnight(ah.min,ah.max);
ae=ah.value||ai._value||ai.dateView._current;
if(ag&&!I(ag,ae)){ag=new x(N);
}if(af&&!I(af,ae)){af=new x(M);
}ai.dateView.setOptions(ah);
ai.timeView.setOptions(C({},ah,{format:ah.timeFormat,min:ag,max:af}));
if(aj){ai.element.val(K.toString(aj,ah.format,ah.culture));
ai._updateARIA(aj);
}},_editable:function(ah){var aj=this,ag=aj.element.off(R),ae=aj._dateIcon.off(R),ak=aj._timeIcon.off(R),al=aj._inputWrapper.off(R),ai=ah.readonly,af=ah.disable;
if(!ai&&!af){al.addClass(A).removeClass(Y).on(H,aj._toggleHover);
ag.removeAttr(B).removeAttr(V).attr(o,false).attr(s,false).on("keydown"+R,l.proxy(aj._keydown,aj)).on("focus"+R,function(){aj._inputWrapper.addClass(E);
}).on("focusout"+R,function(){aj._inputWrapper.removeClass(E);
if(ag.val()!==aj._oldText){aj._change(ag.val());
}aj.close("date");
aj.close("time");
});
ae.on(P,U).on(v,function(){aj.toggle("date");
if(!K.support.touch&&ag[0]!==m()){ag.focus();
}});
ak.on(P,U).on(v,function(){aj.toggle("time");
if(!K.support.touch&&ag[0]!==m()){ag.focus();
}});
}else{al.addClass(af?Y:A).removeClass(af?A:Y);
ag.attr(B,af).attr(V,ai).attr(o,af).attr(s,ai);
}},readonly:function(ae){this._editable({readonly:ae===ac?true:ae,disable:false});
},enable:function(ae){this._editable({readonly:false,disable:!(ae=ae===ac?true:ae)});
},destroy:function(){var ae=this;
ad.fn.destroy.call(ae);
ae.dateView.destroy();
ae.timeView.destroy();
ae.element.off(R);
ae._dateIcon.off(R);
ae._timeIcon.off(R);
ae._inputWrapper.off(R);
if(ae._form){ae._form.off("reset",ae._resetHandler);
}},close:function(ae){if(ae!=="time"){ae="date";
}this[ae+"View"].close();
},open:function(ae){if(ae!=="time"){ae="date";
}this[ae+"View"].open();
},min:function(ae){return this._option("min",ae);
},max:function(ae){return this._option("max",ae);
},toggle:function(af){var ae="timeView";
if(af!=="time"){af="date";
}else{ae="dateView";
}this[af+"View"].toggle();
this[ae].close();
},value:function(af){var ae=this;
if(af===ac){return ae._value;
}ae._old=ae._update(af);
if(ae._old===null){ae.element.val("");
}ae._oldText=ae.element.val();
},_change:function(ai){var ah=this,af=ah.element.val(),ae;
ai=ah._update(ai);
ae=+ah._old!=+ai;
var aj=ae&&!ah._typing;
var ag=af!==ah.element.val();
if(aj||ag){ah.element.trigger(u);
}if(ae){ah._old=ai;
ah._oldText=ah.element.val();
ah.trigger(u);
}ah._typing=false;
},_option:function(ah,am){var aj=this;
var ai=aj.options;
var ak=aj.timeView;
var al=ak.options;
var ae=aj._value||aj._old;
var ag;
var af;
if(am===ac){return ai[ah];
}am=T(am,ai.parseFormats,ai.culture);
if(!am){return;
}if(ai.min.getTime()===ai.max.getTime()){al.dates=[];
}ai[ah]=new x(am.getTime());
aj.dateView[ah](am);
aj._midnight=aj._calculateMidnight(ai.min,ai.max);
if(ae){ag=I(ai.min,ae);
af=I(ai.max,ae);
}if(ag||af){al[ah]=am;
if(ag&&!af){al.max=L(ai.interval);
}if(af){if(aj._midnight){ak.dataBind([M]);
return;
}else{if(!ag){al.min=N;
}}}}else{al.max=M;
al.min=N;
}ak.bind();
},_toggleHover:function(ae){l(ae.currentTarget).toggleClass(G,ae.type==="mouseenter");
},_update:function(at){var ap=this,am=ap.options,ak=am.min,aj=am.max,ag=am.dates,aq=ap.timeView,ae=ap._value,af=T(at,am.parseFormats,am.culture),ai=af===null&&ae===null||af instanceof Date&&ae instanceof Date,an,ar,al,ao,ah;
if(am.disableDates&&am.disableDates(af)){af=null;
if(!ap._old){at=null;
}}if(+af===+ae&&ai){ah=K.toString(af,am.format,am.culture);
if(ah!==at){ap.element.val(af===null?at:ah);
ap.element.trigger(u);
}return af;
}if(af!==null&&I(af,ak)){af=W(af,ak,aj);
}else{if(!J(af,ak,aj)){af=null;
}}ap._value=af;
aq.value(af);
ap.dateView.value(af);
if(af){al=ap._old;
ar=aq.options;
if(ag[0]){ag=l.grep(ag,function(au){return I(af,au);
});
if(ag[0]){aq.dataBind(ag);
ao=true;
}}if(!ao){if(I(af,ak)){ar.min=ak;
ar.max=L(am.interval);
an=true;
}if(I(af,aj)){if(ap._midnight){aq.dataBind([M]);
ao=true;
}else{ar.max=aj;
if(!an){ar.min=N;
}an=true;
}}}if(!ao&&(!al&&an||al&&!I(al,af))){if(!an){ar.max=M;
ar.min=N;
}aq.bind();
}}ap.element.val(af?K.toString(af,am.format,am.culture):at);
ap._updateARIA(af);
return af;
},_keydown:function(af){var ah=this,ae=ah.dateView,ai=ah.timeView,aj=ah.element.val(),ag=ae.popup.visible();
if(af.altKey&&af.keyCode===K.keys.DOWN){ah.toggle(ag?"time":"date");
}else{if(ag){ae.move(af);
ah._updateARIA(ae._current);
}else{if(ai.popup.visible()){ai.move(af);
}else{if(af.keyCode===K.keys.ENTER&&aj!==ah._oldText){ah._change(aj);
}else{ah._typing=true;
}}}}},_views:function(){var al=this,ah=al.element,ak=al.options,ai=ah.attr("id"),af,am,ag,an,aj,ae;
al.dateView=af=new K.DateView(C({},ak,{id:ai,anchor:al.wrapper,change:function(){var au=af.calendar.value(),at=+au,ar=+ak.min,aq=+ak.max,ap,ao;
if(at===ar||at===aq){ap=new x(+al._value);
ap.setFullYear(au.getFullYear(),au.getMonth(),au.getDate());
if(J(ap,ar,aq)){au=ap;
}}if(al._value){ao=K.date.setHours(new Date(au),al._value);
if(J(ao,ar,aq)){au=ao;
}}al._change(au);
al.close("date");
},close:function(ao){if(al.trigger(w,z)){ao.preventDefault();
}else{ah.attr(p,false);
ag.attr(q,true);
if(!am.popup.visible()){ah.removeAttr(r);
}}},open:function(ao){if(al.trigger(S,z)){ao.preventDefault();
}else{if(ah.val()!==al._oldText){ae=T(ah.val(),ak.parseFormats,ak.culture);
al.dateView[ae?"current":"value"](ae);
}ag.attr(q,false);
ah.attr(p,true).attr(r,af._dateViewID);
al._updateARIA(ae);
}}}));
ag=af.div;
aj=ak.min.getTime();
al.timeView=am=new Z({id:ai,value:ak.value,anchor:al.wrapper,animation:ak.animation,format:ak.timeFormat,culture:ak.culture,height:ak.height,interval:ak.interval,min:new x(N),max:new x(M),dates:aj===ak.max.getTime()?[new Date(aj)]:[],parseFormats:ak.parseFormats,change:function(ap,ao){ap=am._parse(ap);
if(ap<ak.min){ap=new x(+ak.min);
am.options.min=ap;
}else{if(ap>ak.max){ap=new x(+ak.max);
am.options.max=ap;
}}if(ao){al._timeSelected=true;
al._change(ap);
}else{ah.val(K.toString(ap,ak.format,ak.culture));
af.value(ap);
al._updateARIA(ap);
}},close:function(ao){if(al.trigger(w,aa)){ao.preventDefault();
}else{an.attr(q,true);
ah.attr(p,false);
if(!af.popup.visible()){ah.removeAttr(r);
}}},open:function(ao){am._adjustListWidth();
if(al.trigger(S,aa)){ao.preventDefault();
}else{if(ah.val()!==al._oldText){ae=T(ah.val(),ak.parseFormats,ak.culture);
al.timeView.value(ae);
}an.attr(q,false);
ah.attr(p,true).attr(r,am._timeViewID);
am.options.active(am.current());
}},active:function(ao){ah.removeAttr(n);
if(ao){ah.attr(n,am._optionID);
}}});
an=am.ul;
},_icons:function(){var ag=this,ae=ag.element,af;
af=ae.next("span.k-select");
if(!af[0]){af=l('<span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-calendar">select</span><span unselectable="on" class="k-icon k-i-clock">select</span></span>').insertAfter(ae);
}af=af.children();
ag._dateIcon=af.eq(0).attr({role:"button","aria-controls":ag.dateView._dateViewID});
ag._timeIcon=af.eq(1).attr({role:"button","aria-controls":ag.timeView._timeViewID});
},_wrapper:function(){var af=this,ae=af.element,ag;
ag=ae.parents(".k-datetimepicker");
if(!ag[0]){ag=ae.wrap(X).parent().addClass("k-picker-wrap k-state-default");
ag=ag.wrap(X).parent();
}ag[0].style.cssText=ae[0].style.cssText;
ae.css({width:"100%",height:ae[0].style.height});
af.wrapper=ag.addClass("k-widget k-datetimepicker k-header").addClass(ae[0].className);
af._inputWrapper=l(ag[0].firstChild);
},_reset:function(){var ah=this,ae=ah.element,ag=ae.attr("form"),af=ag?l("#"+ag):ae.closest("form");
if(af[0]){ah._resetHandler=function(){ah.value(ae[0].defaultValue);
ah.max(ah._initialOptions.max);
ah.min(ah._initialOptions.min);
};
ah._form=af.on("reset",ah._resetHandler);
}},_template:function(){this._ariaTemplate=K.template(this.options.ARIATemplate);
},_calculateMidnight:function(af,ae){return F(af)+F(ae)===0;
},_updateARIA:function(ag){var af;
var ah=this;
var ae=ah.dateView.calendar;
ah.element.removeAttr(n);
if(ae){af=ae._cell;
af.attr("aria-label",ah._ariaTemplate({current:ag||ae.current()}));
ah.element.attr(n,af.attr("id"));
}}});
function L(af){var ae=new Date(2100,0,1);
ae.setMinutes(-af);
return ae;
}function U(ae){ae.preventDefault();
}function Q(ae){var ag=K.getCulture(ae.culture).calendars.standard.patterns,af=!ae.parseFormats.length,ah;
ae.format=D(ae.format||ag.g);
ae.timeFormat=ah=D(ae.timeFormat||ag.t);
K.DateView.normalize(ae);
if(af){ae.parseFormats.unshift("yyyy-MM-ddTHH:mm:ss");
}if(l.inArray(ah,ae.parseFormats)===-1){ae.parseFormats.splice(1,0,ah);
}}ab.plugin(y);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
