(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.datepicker",["kendo.calendar","kendo.popup"],l);
}(function(){var k={id:"datepicker",name:"DatePicker",category:"web",description:"The DatePicker widget allows the user to select a date from a calendar or by direct input.",depends:["calendar","popup"]};
(function(l,ab){var I=window.kendo,aa=I.ui,ac=aa.Widget,R=I.parseDate,J=I.keys,Z=I.template,m=I._activeElement,A="<div />",X="<span />",P=".kendoDatePicker",t="click"+P,Q="open",u="close",s="change",z="disabled",U="readonly",y="k-state-default",C="k-state-focused",W="k-state-selected",Y="k-state-disabled",D="k-state-hover",E="mouseenter"+P+" mouseleave"+P,N="mousedown"+P,F="id",L="min",K="max",M="month",n="aria-disabled",o="aria-expanded",p="aria-hidden",q="aria-readonly",r=I.calendar,H=r.isInRange,V=r.restrictValue,G=r.isEqualDatePart,B=l.extend,T=l.proxy,v=Date;
function O(ae){var af=ae.parseFormats,ad=ae.format;
r.normalize(ae);
af=l.isArray(af)?af:[af];
if(!af.length){af.push("yyyy-MM-dd");
}if(l.inArray(ad,af)===-1){af.splice(0,0,ae.format);
}ae.parseFormats=af;
}function S(ad){ad.preventDefault();
}var x=function(ag){var ah=this,af,ad=document.body,ae=l(A).attr(p,"true").addClass("k-calendar-container").appendTo(ad);
ah.options=ag=ag||{};
af=ag.id;
if(af){af+="_dateview";
ae.attr(F,af);
ah._dateViewID=af;
}ah.popup=new aa.Popup(ae,B(ag.popup,ag,{name:"Popup",isRtl:I.support.isRtl(ag.anchor)}));
ah.div=ae;
ah.value(ag.value);
};
x.prototype={_calendar:function(){var ag=this;
var ad=ag.calendar;
var af=ag.options;
var ae;
if(!ad){ae=l(A).attr(F,I.guid()).appendTo(ag.popup.element).on(N,S).on(t,"td:has(.k-link)",T(ag._click,ag));
ag.calendar=ad=new aa.Calendar(ae);
ag._setOptions(af);
I.calendar.makeUnselectable(ad.element);
ad.navigate(ag._value||ag._current,af.start);
ag.value(ag._value);
}},_setOptions:function(ad){this.calendar.setOptions({focusOnNav:false,change:ad.change,culture:ad.culture,dates:ad.dates,depth:ad.depth,footer:ad.footer,format:ad.format,max:ad.max,min:ad.min,month:ad.month,start:ad.start,disableDates:ad.disableDates});
},setOptions:function(ae){var ad=this.options;
this.options=B(ad,ae,{change:ad.change,close:ad.close,open:ad.open});
if(this.calendar){this._setOptions(this.options);
}},destroy:function(){this.popup.destroy();
},open:function(){var ad=this;
ad._calendar();
ad.popup.open();
},close:function(){this.popup.close();
},min:function(ad){this._option(L,ad);
},max:function(ad){this._option(K,ad);
},toggle:function(){var ad=this;
ad[ad.popup.visible()?u:Q]();
},move:function(ae){var ai=this,ag=ae.keyCode,ad=ai.calendar,ah=ae.ctrlKey&&ag==J.DOWN||ag==J.ENTER,af=false;
if(ae.altKey){if(ag==J.DOWN){ai.open();
ae.preventDefault();
af=true;
}else{if(ag==J.UP){ai.close();
ae.preventDefault();
af=true;
}}}else{if(ai.popup.visible()){if(ag==J.ESC||ah&&ad._cell.hasClass(W)){ai.close();
ae.preventDefault();
return true;
}ai._current=ad._move(ae);
af=true;
}}return af;
},current:function(ad){this._current=ad;
this.calendar._focus(ad);
},value:function(ah){var ag=this,ad=ag.calendar,af=ag.options,ae=af.disableDates;
if(ae&&ae(ah)){ah=null;
}ag._value=ah;
ag._current=new v(+V(ah,af.min,af.max));
if(ad){ad.value(ah);
}},_click:function(ad){if(ad.currentTarget.className.indexOf(W)!==-1){this.close();
}},_option:function(ae,ag){var af=this;
var ad=af.calendar;
af.options[ae]=ag;
if(ad){ad[ae](ag);
}}};
x.normalize=O;
I.DateView=x;
var w=ac.extend({init:function(ag,ah){var ai=this,ad,ae;
ac.fn.init.call(ai,ag,ah);
ag=ai.element;
ah=ai.options;
ah.disableDates=I.calendar.disabled(ah.disableDates);
ah.min=R(ag.attr("min"))||R(ah.min);
ah.max=R(ag.attr("max"))||R(ah.max);
O(ah);
ai._initialOptions=B({},ah);
ai._wrapper();
ai.dateView=new x(B({},ah,{id:ag.attr(F),anchor:ai.wrapper,change:function(){ai._change(this.value());
ai.close();
},close:function(aj){if(ai.trigger(u)){aj.preventDefault();
}else{ag.attr(o,false);
ae.attr(p,true);
}},open:function(ak){var al=ai.options,aj;
if(ai.trigger(Q)){ak.preventDefault();
}else{if(ai.element.val()!==ai._oldText){aj=R(ag.val(),al.parseFormats,al.culture);
ai.dateView[aj?"current":"value"](aj);
}ag.attr(o,true);
ae.attr(p,false);
ai._updateARIA(aj);
}}}));
ae=ai.dateView.div;
ai._icon();
try{ag[0].setAttribute("type","text");
}catch(af){ag[0].type="text";
}ag.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":ai.dateView._dateViewID});
ai._reset();
ai._template();
ad=ag.is("[disabled]")||l(ai.element).parents("fieldset").is(":disabled");
if(ad){ai.enable(false);
}else{ai.readonly(ag.is("[readonly]"));
}ai._old=ai._update(ah.value||ai.element.val());
ai._oldText=ag.val();
I.notify(ai);
},events:[Q,u,s],options:{name:"DatePicker",value:null,footer:"",format:"",culture:"",parseFormats:[],min:new Date(1900,0,1),max:new Date(2099,11,31),start:M,depth:M,animation:{},month:{},dates:[],ARIATemplate:'Current focused date is #=kendo.toString(data.current, "D")#'},setOptions:function(ad){var ae=this;
var af=ae._value;
ac.fn.setOptions.call(ae,ad);
ad=ae.options;
ad.min=R(ad.min);
ad.max=R(ad.max);
O(ad);
ae.dateView.setOptions(ad);
if(af){ae.element.val(I.toString(af,ad.format,ad.culture));
ae._updateARIA(af);
}},_editable:function(ag){var ai=this,af=ai._dateIcon.off(P),ae=ai.element.off(P),aj=ai._inputWrapper.off(P),ah=ag.readonly,ad=ag.disable;
if(!ah&&!ad){aj.addClass(y).removeClass(Y).on(E,ai._toggleHover);
ae.removeAttr(z).removeAttr(U).attr(n,false).attr(q,false).on("keydown"+P,T(ai._keydown,ai)).on("focusout"+P,T(ai._blur,ai)).on("focus"+P,function(){ai._inputWrapper.addClass(C);
});
af.on(t,T(ai._click,ai)).on(N,S);
}else{aj.addClass(ad?Y:y).removeClass(ad?y:Y);
ae.attr(z,ad).attr(U,ah).attr(n,ad).attr(q,ah);
}},readonly:function(ad){this._editable({readonly:ad===ab?true:ad,disable:false});
},enable:function(ad){this._editable({readonly:false,disable:!(ad=ad===ab?true:ad)});
},destroy:function(){var ad=this;
ac.fn.destroy.call(ad);
ad.dateView.destroy();
ad.element.off(P);
ad._dateIcon.off(P);
ad._inputWrapper.off(P);
if(ad._form){ad._form.off("reset",ad._resetHandler);
}},open:function(){this.dateView.open();
},close:function(){this.dateView.close();
},min:function(ad){return this._option(L,ad);
},max:function(ad){return this._option(K,ad);
},value:function(ae){var ad=this;
if(ae===ab){return ad._value;
}ad._old=ad._update(ae);
if(ad._old===null){ad.element.val("");
}ad._oldText=ad.element.val();
},_toggleHover:function(ad){l(ad.currentTarget).toggleClass(D,ad.type==="mouseenter");
},_blur:function(){var ad=this,ae=ad.element.val();
ad.close();
if(ae!==ad._oldText){ad._change(ae);
}ad._inputWrapper.removeClass(C);
},_click:function(){var ae=this,ad=ae.element;
ae.dateView.toggle();
if(!I.support.touch&&ad[0]!==m()){ad.focus();
}},_change:function(ah){var ag=this,ae=ag.element.val(),ad;
ah=ag._update(ah);
ad=+ag._old!=+ah;
var ai=ad&&!ag._typing;
var af=ae!==ag.element.val();
if(ai||af){ag.element.trigger(s);
}if(ad){ag._old=ah;
ag._oldText=ag.element.val();
ag.trigger(s);
}ag._typing=false;
},_keydown:function(ae){var ag=this,ad=ag.dateView,ah=ag.element.val(),af=false;
if(!ad.popup.visible()&&ae.keyCode==J.ENTER&&ah!==ag._oldText){ag._change(ah);
}else{af=ad.move(ae);
ag._updateARIA(ad._current);
if(!af){ag._typing=true;
}}},_icon:function(){var af=this,ad=af.element,ae;
ae=ad.next("span.k-select");
if(!ae[0]){ae=l('<span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-calendar">select</span></span>').insertAfter(ad);
}af._dateIcon=ae.attr({role:"button","aria-controls":af.dateView._dateViewID});
},_option:function(ad,ag){var af=this,ae=af.options;
if(ag===ab){return ae[ad];
}ag=R(ag,ae.parseFormats,ae.culture);
if(!ag){return;
}ae[ad]=new v(+ag);
af.dateView[ad](ag);
},_update:function(al){var ak=this,aj=ak.options,ai=aj.min,ah=aj.max,ad=ak._value,ae=R(al,aj.parseFormats,aj.culture),ag=ae===null&&ad===null||ae instanceof Date&&ad instanceof Date,af;
if(aj.disableDates(ae)){ae=null;
if(!ak._old){al=null;
}}if(+ae===+ad&&ag){af=I.toString(ae,aj.format,aj.culture);
if(af!==al){ak.element.val(ae===null?al:af);
}return ae;
}if(ae!==null&&G(ae,ai)){ae=V(ae,ai,ah);
}else{if(!H(ae,ai,ah)){ae=null;
}}ak._value=ae;
ak.dateView.value(ae);
ak.element.val(ae?I.toString(ae,aj.format,aj.culture):al);
ak._updateARIA(ae);
return ae;
},_wrapper:function(){var ae=this,ad=ae.element,af;
af=ad.parents(".k-datepicker");
if(!af[0]){af=ad.wrap(X).parent().addClass("k-picker-wrap k-state-default");
af=af.wrap(X).parent();
}af[0].style.cssText=ad[0].style.cssText;
ad.css({width:"100%",height:ad[0].style.height});
ae.wrapper=af.addClass("k-widget k-datepicker k-header").addClass(ad[0].className);
ae._inputWrapper=l(af[0].firstChild);
},_reset:function(){var ag=this,ad=ag.element,af=ad.attr("form"),ae=af?l("#"+af):ad.closest("form");
if(ae[0]){ag._resetHandler=function(){ag.value(ad[0].defaultValue);
ag.max(ag._initialOptions.max);
ag.min(ag._initialOptions.min);
};
ag._form=ae.on("reset",ag._resetHandler);
}},_template:function(){this._ariaTemplate=Z(this.options.ARIATemplate);
},_updateARIA:function(af){var ae;
var ag=this;
var ad=ag.dateView.calendar;
ag.element.removeAttr("aria-activedescendant");
if(ad){ae=ad._cell;
ae.attr("aria-label",ag._ariaTemplate({current:af||ad.current()}));
ag.element.attr("aria-activedescendant",ae.attr("id"));
}}});
aa.plugin(w);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
