(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.draganddrop",["kendo.core","kendo.userevents"],l);
}(function(){var k={id:"draganddrop",name:"Drag & drop",category:"framework",description:"Drag & drop functionality for any DOM element.",depends:["core","userevents"]};
(function(l,af){var O=window.kendo,ab=O.support,u=window.document,m=l(window),q=O.Class,ah=O.ui.Widget,T=O.Observable,ag=O.UserEvents,Y=l.proxy,J=l.extend,L=O.getOffset,A={},H={},E={},Q,I=O.elementUnderCursor,P="keyup",o="change",C="dragstart",N="hold",v="drag",x="dragend",w="dragcancel",M="hintDestroyed",y="dragenter",B="dragleave",D="drop";
function s(al,aj){try{return l.contains(al,aj)||al==aj;
}catch(ak){return false;
}}function S(aj,ak){return parseInt(aj.css(ak),10)||0;
}function ai(ak,aj){return Math.min(Math.max(ak,aj.min),aj.max);
}function r(aj,ak){var ap=L(aj),an=ap.left+S(aj,"borderLeftWidth")+S(aj,"paddingLeft"),ao=ap.top+S(aj,"borderTopWidth")+S(aj,"paddingTop"),al=an+aj.width()-ak.outerWidth(true),am=ao+aj.height()-ak.outerHeight(true);
return{x:{min:an,max:al},y:{min:ao,max:am}};
}function p(am,ao,ak){var aq,ap,al=0,an=ao&&ao.length,aj=ak&&ak.length;
while(am&&am.parentNode){for(al=0;
al<an;
al++){aq=ao[al];
if(aq.element[0]===am){return{target:aq,targetElement:am};
}}for(al=0;
al<aj;
al++){ap=ak[al];
if(l.contains(ap.element[0],am)&&ab.matchesSelector.call(am,ap.options.filter)){return{target:ap,targetElement:am};
}}am=am.parentNode;
}return af;
}var ac=T.extend({init:function(ak,al){var am=this,aj=ak[0];
am.capture=false;
if(aj.addEventListener){l.each(O.eventMap.down.split(" "),function(){aj.addEventListener(this,Y(am._press,am),true);
});
l.each(O.eventMap.up.split(" "),function(){aj.addEventListener(this,Y(am._release,am),true);
});
}else{l.each(O.eventMap.down.split(" "),function(){aj.attachEvent(this,Y(am._press,am));
});
l.each(O.eventMap.up.split(" "),function(){aj.attachEvent(this,Y(am._release,am));
});
}T.fn.init.call(am);
am.bind(["press","release"],al||{});
},captureNext:function(){this.capture=true;
},cancelCapture:function(){this.capture=false;
},_press:function(aj){var ak=this;
ak.trigger("press");
if(ak.capture){aj.preventDefault();
}},_release:function(aj){var ak=this;
ak.trigger("release");
if(ak.capture){aj.preventDefault();
ak.cancelCapture();
}}});
var W=T.extend({init:function(aj){var ak=this;
T.fn.init.call(ak);
ak.forcedEnabled=false;
l.extend(ak,aj);
ak.scale=1;
if(ak.horizontal){ak.measure="offsetWidth";
ak.scrollSize="scrollWidth";
ak.axis="x";
}else{ak.measure="offsetHeight";
ak.scrollSize="scrollHeight";
ak.axis="y";
}},makeVirtual:function(){l.extend(this,{virtual:true,forcedEnabled:true,_virtualMin:0,_virtualMax:0});
},virtualSize:function(ak,aj){if(this._virtualMin!==ak||this._virtualMax!==aj){this._virtualMin=ak;
this._virtualMax=aj;
this.update();
}},outOfBounds:function(aj){return aj>this.max||aj<this.min;
},forceEnabled:function(){this.forcedEnabled=true;
},getSize:function(){return this.container[0][this.measure];
},getTotal:function(){return this.element[0][this.scrollSize];
},rescale:function(aj){this.scale=aj;
},update:function(ak){var am=this,an=am.virtual?am._virtualMax:am.getTotal(),aj=an*am.scale,al=am.getSize();
if(an===0&&!am.forcedEnabled){return;
}am.max=am.virtual?-am._virtualMin:0;
am.size=al;
am.total=aj;
am.min=Math.min(am.max,al-aj);
am.minScale=al/an;
am.centerOffset=(aj-al)/2;
am.enabled=am.forcedEnabled||aj>al;
if(!ak){am.trigger(o,am);
}}});
var X=T.extend({init:function(aj){var ak=this;
T.fn.init.call(ak);
ak.x=new W(J({horizontal:true},aj));
ak.y=new W(J({horizontal:false},aj));
ak.container=aj.container;
ak.forcedMinScale=aj.minScale;
ak.maxScale=aj.maxScale||100;
ak.bind(o,aj);
},rescale:function(aj){this.x.rescale(aj);
this.y.rescale(aj);
this.refresh();
},centerCoordinates:function(){return{x:Math.min(0,-this.x.centerOffset),y:Math.min(0,-this.y.centerOffset)};
},refresh:function(){var aj=this;
aj.x.update();
aj.y.update();
aj.enabled=aj.x.enabled||aj.y.enabled;
aj.minScale=aj.forcedMinScale||Math.min(aj.x.minScale,aj.y.minScale);
aj.fitScale=Math.max(aj.x.minScale,aj.y.minScale);
aj.trigger(o);
}});
var V=T.extend({init:function(aj){var ak=this;
J(ak,aj);
T.fn.init.call(ak);
},outOfBounds:function(){return this.dimension.outOfBounds(this.movable[this.axis]);
},dragMove:function(ak){var ao=this,al=ao.dimension,aj=ao.axis,am=ao.movable,an=am[aj]+ak;
if(!al.enabled){return;
}if(an<al.min&&ak<0||an>al.max&&ak>0){ak*=ao.resistance;
}am.translateAxis(aj,ak);
ao.trigger(o,ao);
}});
var U=q.extend({init:function(ak){var am=this,an,ao,al,aj;
J(am,{elastic:true},ak);
al=am.elastic?0.5:0;
aj=am.movable;
am.x=an=new V({axis:"x",dimension:am.dimensions.x,resistance:al,movable:aj});
am.y=ao=new V({axis:"y",dimension:am.dimensions.y,resistance:al,movable:aj});
am.userEvents.bind(["press","move","end","gesturestart","gesturechange"],{gesturestart:function(ap){am.gesture=ap;
am.offset=am.dimensions.container.offset();
},press:function(ap){if(l(ap.event.target).closest("a").is("[data-navigate-on-press=true]")){ap.sender.cancel();
}},gesturechange:function(ar){var ay=am.gesture,ax=ay.center,ap=ar.center,az=ar.distance/ay.distance,au=am.dimensions.minScale,at=am.dimensions.maxScale,aq;
if(aj.scale<=au&&az<1){az+=(1-az)*0.8;
}if(aj.scale*az>=at){az=at/aj.scale;
}var av=aj.x+am.offset.left,aw=aj.y+am.offset.top;
aq={x:(av-ax.x)*az+ap.x-av,y:(aw-ax.y)*az+ap.y-aw};
aj.scaleWith(az);
an.dragMove(aq.x);
ao.dragMove(aq.y);
am.dimensions.rescale(aj.scale);
am.gesture=ar;
ar.preventDefault();
},move:function(ap){if(ap.event.target.tagName.match(/textarea|input/i)){return;
}if(an.dimension.enabled||ao.dimension.enabled){an.dragMove(ap.x.delta);
ao.dragMove(ap.y.delta);
ap.preventDefault();
}else{ap.touch.skip();
}},end:function(ap){ap.preventDefault();
}});
}});
var ad=ab.transitions.prefix+"Transform",ae;
if(ab.hasHW3D){ae=function(ak,al,aj){return"translate3d("+ak+"px,"+al+"px,0) scale("+aj+")";
};
}else{ae=function(ak,al,aj){return"translate("+ak+"px,"+al+"px) scale("+aj+")";
};
}var R=T.extend({init:function(aj){var ak=this;
T.fn.init.call(ak);
ak.element=l(aj);
ak.element[0].style.webkitTransformOrigin="left top";
ak.x=0;
ak.y=0;
ak.scale=1;
ak._saveCoordinates(ae(ak.x,ak.y,ak.scale));
},translateAxis:function(aj,ak){this[aj]+=ak;
this.refresh();
},scaleTo:function(aj){this.scale=aj;
this.refresh();
},scaleWith:function(aj){this.scale*=aj;
this.refresh();
},translate:function(aj){this.x+=aj.x;
this.y+=aj.y;
this.refresh();
},moveAxis:function(aj,ak){this[aj]=ak;
this.refresh();
},moveTo:function(aj){J(this,aj);
this.refresh();
},refresh:function(){var ak=this,al=ak.x,am=ak.y,aj;
if(ak.round){al=Math.round(al);
am=Math.round(am);
}aj=ae(al,am,ak.scale);
if(aj!=ak.coordinates){if(O.support.browser.msie&&O.support.browser.version<10){ak.element[0].style.position="absolute";
ak.element[0].style.left=ak.x+"px";
ak.element[0].style.top=ak.y+"px";
}else{ak.element[0].style[ad]=aj;
}ak._saveCoordinates(aj);
ak.trigger(o);
}},_saveCoordinates:function(aj){this.coordinates=aj;
}});
function t(aj,an){var al=an.options.group,ak=aj[al],am;
ah.fn.destroy.call(an);
if(ak.length>1){for(am=0;
am<ak.length;
am++){if(ak[am]==an){ak.splice(am,1);
break;
}}}else{ak.length=0;
delete aj[al];
}}var F=ah.extend({init:function(aj,al){var am=this;
ah.fn.init.call(am,aj,al);
var ak=am.options.group;
if(!(ak in H)){H[ak]=[am];
}else{H[ak].push(am);
}},events:[y,B,D],options:{name:"DropTarget",group:"default"},destroy:function(){t(H,this);
},_trigger:function(al,ak){var am=this,aj=A[am.options.group];
if(aj){return am.trigger(al,J({},ak.event,{draggable:aj,dropTarget:ak.dropTarget}));
}},_over:function(aj){this._trigger(y,aj);
},_out:function(aj){this._trigger(B,aj);
},_drop:function(ak){var al=this,aj=A[al.options.group];
if(aj){aj.dropped=!al._trigger(D,ak);
}}});
F.destroyGroup=function(ak){var aj=H[ak]||E[ak],al;
if(aj){for(al=0;
al<aj.length;
al++){ah.fn.destroy.call(aj[al]);
}aj.length=0;
delete H[ak];
delete E[ak];
}};
F._cache=H;
var G=F.extend({init:function(aj,al){var am=this;
ah.fn.init.call(am,aj,al);
var ak=am.options.group;
if(!(ak in E)){E[ak]=[am];
}else{E[ak].push(am);
}},destroy:function(){t(E,this);
},options:{name:"DropTargetArea",group:"default",filter:null}});
var z=ah.extend({init:function(aj,ak){var al=this;
ah.fn.init.call(al,aj,ak);
al._activated=false;
al.userEvents=new ag(al.element,{global:true,allowSelection:true,filter:al.options.filter,threshold:al.options.distance,start:Y(al._start,al),hold:Y(al._hold,al),move:Y(al._drag,al),end:Y(al._end,al),cancel:Y(al._cancel,al),select:Y(al._select,al)});
al._afterEndHandler=Y(al._afterEnd,al);
al._captureEscape=Y(al._captureEscape,al);
},events:[N,C,v,x,w,M],options:{name:"Draggable",distance:O.support.touch?0:5,group:"default",cursorOffset:null,axis:null,container:null,filter:null,ignore:null,holdToDrag:false,autoScroll:false,dropped:false},cancelHold:function(){this._activated=false;
},_captureEscape:function(aj){var ak=this;
if(aj.keyCode===O.keys.ESC){ak._trigger(w,{event:aj});
ak.userEvents.cancel();
}},_updateHint:function(an){var ap=this,al,ao=ap.options,ak=ap.boundaries,aj=ao.axis,am=ap.options.cursorOffset;
if(am){al={left:an.x.location+am.left,top:an.y.location+am.top};
}else{ap.hintOffset.left+=an.x.delta;
ap.hintOffset.top+=an.y.delta;
al=l.extend({},ap.hintOffset);
}if(ak){al.top=ai(al.top,ak.y);
al.left=ai(al.left,ak.x);
}if(aj==="x"){delete al.top;
}else{if(aj==="y"){delete al.left;
}}ap.hint.css(al);
},_shouldIgnoreTarget:function(ak){var aj=this.options.ignore;
return aj&&l(ak).is(aj);
},_select:function(aj){if(!this._shouldIgnoreTarget(aj.event.target)){aj.preventDefault();
}},_start:function(ak){var ao=this,an=ao.options,aj=an.container,al=an.hint;
if(this._shouldIgnoreTarget(ak.touch.initialTouch)||an.holdToDrag&&!ao._activated){ao.userEvents.cancel();
return;
}ao.currentTarget=ak.target;
ao.currentTargetOffset=L(ao.currentTarget);
if(al){if(ao.hint){ao.hint.stop(true,true).remove();
}ao.hint=O.isFunction(al)?l(al.call(ao,ao.currentTarget)):al;
var am=L(ao.currentTarget);
ao.hintOffset=am;
ao.hint.css({position:"absolute",zIndex:20000,left:am.left,top:am.top}).appendTo(u.body);
ao.angular("compile",function(){ao.hint.removeAttr("ng-repeat");
var ap=l(ak.target);
while(!ap.data("$$kendoScope")&&ap.length){ap=ap.parent();
}return{elements:ao.hint.get(),scopeFrom:ap.data("$$kendoScope")};
});
}A[an.group]=ao;
ao.dropped=false;
if(aj){ao.boundaries=r(aj,ao.hint);
}l(u).on(P,ao._captureEscape);
if(ao._trigger(C,ak)){ao.userEvents.cancel();
ao._afterEnd();
}ao.userEvents.capture();
},_hold:function(aj){this.currentTarget=aj.target;
if(this._trigger(N,aj)){this.userEvents.cancel();
}else{this._activated=true;
}},_drag:function(ak){ak.preventDefault();
var aj=this._elementUnderCursor(ak);
this._lastEvent=ak;
this._processMovement(ak,aj);
if(this.options.autoScroll){if(this._cursorElement!==aj){this._scrollableParent=K(aj);
this._cursorElement=aj;
}if(this._scrollableParent[0]){var al=n(ak.x.location,ak.y.location,aa(this._scrollableParent));
this._scrollCompenstation=l.extend({},this.hintOffset);
this._scrollVelocity=al;
if(al.y===0&&al.x===0){clearInterval(this._scrollInterval);
this._scrollInterval=null;
}else{if(!this._scrollInterval){this._scrollInterval=setInterval(l.proxy(this,"_autoScroll"),50);
}}}}if(this.hint){this._updateHint(ak);
}},_processMovement:function(ak,aj){this._withDropTarget(aj,function(al,am){if(!al){if(Q){Q._trigger(B,J(ak,{dropTarget:l(Q.targetElement)}));
Q=null;
}return;
}if(Q){if(am===Q.targetElement){return;
}Q._trigger(B,J(ak,{dropTarget:l(Q.targetElement)}));
}al._trigger(y,J(ak,{dropTarget:l(am)}));
Q=J(al,{targetElement:am});
});
this._trigger(v,J(ak,{dropTarget:Q,elementUnderCursor:aj}));
},_autoScroll:function(){var am=this._scrollableParent[0],an=this._scrollVelocity,aj=this._scrollCompenstation;
if(!am){return;
}var ak=this._elementUnderCursor(this._lastEvent);
this._processMovement(this._lastEvent,ak);
var au,aq;
var al=am===Z()[0];
if(al){au=u.body.scrollHeight>m.height();
aq=u.body.scrollWidth>m.width();
}else{au=am.offsetHeight<=am.scrollHeight;
aq=am.offsetWidth<=am.scrollWidth;
}var ar=am.scrollTop+an.y;
var at=au&&ar>0&&ar<am.scrollHeight;
var ao=am.scrollLeft+an.x;
var ap=aq&&ao>0&&ao<am.scrollWidth;
if(at){am.scrollTop+=an.y;
}if(ap){am.scrollLeft+=an.x;
}if(al&&(ap||at)){if(at){aj.top+=an.y;
}if(ap){aj.left+=an.x;
}this.hint.css(aj);
}},_end:function(aj){this._withDropTarget(this._elementUnderCursor(aj),function(ak,al){if(ak){ak._drop(J({},aj,{dropTarget:l(al)}));
Q=null;
}});
this._cancel(this._trigger(x,aj));
},_cancel:function(aj){var ak=this;
ak._scrollableParent=null;
this._cursorElement=null;
clearInterval(this._scrollInterval);
ak._activated=false;
if(ak.hint&&!ak.dropped){setTimeout(function(){ak.hint.stop(true,true);
if(aj){ak._afterEndHandler();
}else{ak.hint.animate(ak.currentTargetOffset,"fast",ak._afterEndHandler);
}},0);
}else{ak._afterEnd();
}},_trigger:function(ak,aj){var al=this;
return al.trigger(ak,J({},aj.event,{x:aj.x,y:aj.y,currentTarget:al.currentTarget,initialTarget:aj.touch?aj.touch.initialTouch:null,dropTarget:aj.dropTarget,elementUnderCursor:aj.elementUnderCursor}));
},_elementUnderCursor:function(aj){var al=I(aj),ak=this.hint;
if(ak&&s(ak[0],al)){ak.hide();
al=I(aj);
if(!al){al=I(aj);
}ak.show();
}return al;
},_withDropTarget:function(al,ak){var an,am=this.options.group,ao=H[am],aj=E[am];
if(ao&&ao.length||aj&&aj.length){an=p(al,ao,aj);
if(an){ak(an.target,an.targetElement);
}else{ak();
}}},destroy:function(){var aj=this;
ah.fn.destroy.call(aj);
aj._afterEnd();
aj.userEvents.destroy();
this._scrollableParent=null;
this._cursorElement=null;
clearInterval(this._scrollInterval);
aj.currentTarget=null;
},_afterEnd:function(){var aj=this;
if(aj.hint){aj.hint.remove();
}delete A[aj.options.group];
aj.trigger("destroy");
aj.trigger(M);
l(u).off(P,aj._captureEscape);
}});
O.ui.plugin(F);
O.ui.plugin(G);
O.ui.plugin(z);
O.TapCapture=ac;
O.containerBoundaries=r;
J(O.ui,{Pane:U,PaneDimensions:X,Movable:R});
function aa(aj){var am=Z()[0],al,an,ak;
if(aj[0]===am){an=am.scrollTop;
ak=am.scrollLeft;
return{top:an,left:ak,bottom:an+m.height(),right:ak+m.width()};
}else{al=aj.offset();
al.bottom=al.top+aj.height();
al.right=al.left+aj.width();
return al;
}}function Z(){return l(O.support.browser.chrome?u.body:u.documentElement);
}function K(aj){var al=Z();
if(!aj||aj===u.body||aj===u.documentElement){return al;
}var ak=l(aj)[0];
while(ak&&!O.isScrollable(ak)&&ak!==u.body){ak=ak.parentNode;
}if(ak===u.body){return al;
}return l(ak);
}function n(ak,al,am){var an={x:0,y:0};
var aj=50;
if(ak-am.left<aj){an.x=-(aj-(ak-am.left));
}else{if(am.right-ak<aj){an.x=aj-(am.right-ak);
}}if(al-am.top<aj){an.y=-(aj-(al-am.top));
}else{if(am.bottom-al<aj){an.y=aj-(am.bottom-al);
}}return an;
}O.ui.Draggable.utils={autoScrollVelocity:n,scrollableViewPort:aa,findScrollableParent:K};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
