(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.dropdownlist",["kendo.list","kendo.mobile.scroller"],l);
}(function(){var k={id:"dropdownlist",name:"DropDownList",category:"web",description:"The DropDownList widget displays a list of values and allows the selection of a single value from the list.",depends:["list"],features:[{id:"mobile-scroller",name:"Mobile scroller",description:"Support for kinetic scrolling in mobile device",depends:["mobile.scroller"]},{id:"virtualization",name:"VirtualList",description:"Support for virtualization",depends:["virtuallist"]}]};
(function(l,N){var w=window.kendo,M=w.ui,y=M.List,G=M.Select,K=w.support,m=w._activeElement,C=w.data.ObservableObject,x=w.keys,B=".kendoDropDownList",s="disabled",E="readonly",q="change",u="k-state-focused",r="k-state-default",J="k-state-disabled",n="aria-disabled",o="aria-readonly",v="mouseenter"+B+" mouseleave"+B,L="tabindex",I="filter",H="accept",z="The `optionLabel` option is not valid due to missing fields. Define a custom optionLabel as shown here http://docs.telerik.com/kendo-ui/api/javascript/ui/dropdownlist#configuration-optionLabel",D=l.proxy;
var t=G.extend({init:function(P,S){var U=this;
var Q=S&&S.index;
var R,T,O;
U.ns=B;
S=l.isArray(S)?{dataSource:S}:S;
G.fn.init.call(U,P,S);
S=U.options;
P=U.element.on("focus"+B,D(U._focusHandler,U));
U._focusInputHandler=l.proxy(U._focusInput,U);
U.optionLabel=l();
U._optionLabel();
U._inputTemplate();
U._reset();
U._prev="";
U._word="";
U._wrapper();
U._tabindex();
U.wrapper.data(L,U.wrapper.attr(L));
U._span();
U._popup();
U._mobile();
U._dataSource();
U._ignoreCase();
U._filterHeader();
U._aria();
U._enable();
U._oldIndex=U.selectedIndex=-1;
if(Q!==N){S.index=Q;
}U._initialIndex=S.index;
U._initList();
U._cascade();
if(S.autoBind){U.dataSource.fetch();
}else{if(U.selectedIndex===-1){T=S.text||"";
if(!T){R=S.optionLabel;
if(R&&S.index===0){T=R;
}else{if(U._isSelect){T=P.children(":selected").text();
}}}U._textAccessor(T);
}}O=l(U.element).parents("fieldset").is(":disabled");
if(O){U.enable(false);
}U.listView.bind("click",function(V){V.preventDefault();
});
w.notify(U);
},options:{name:"DropDownList",enabled:true,autoBind:true,index:0,text:null,value:null,delay:500,height:200,dataTextField:"",dataValueField:"",optionLabel:"",cascadeFrom:"",cascadeFromField:"",ignoreCase:true,animation:{},filter:"none",minLength:1,virtual:false,template:null,valueTemplate:null,optionLabelTemplate:null,groupTemplate:"#:data#",fixedGroupTemplate:"#:data#"},events:["open","close",q,"select","filtering","dataBinding","dataBound","cascade","set"],setOptions:function(O){G.fn.setOptions.call(this,O);
this.listView.setOptions(this._listOptions(O));
this._optionLabel();
this._inputTemplate();
this._accessors();
this._filterHeader();
this._enable();
this._aria();
if(!this.value()&&this.hasOptionLabel()){this.select(0);
}},destroy:function(){var O=this;
G.fn.destroy.call(O);
O.wrapper.off(B);
O.element.off(B);
O._inputWrapper.off(B);
O._arrow.off();
O._arrow=null;
O.optionLabel.off();
},open:function(){var O=this;
if(O.popup.visible()){return;
}if(!O.listView.bound()||O._state===H){O._open=true;
O._state="rebind";
if(O.filterInput){O.filterInput.val("");
O._prev="";
}O._filterSource();
}else{if(O._allowOpening()){O.popup.one("activate",O._focusInputHandler);
O.popup.open();
O._focusItem();
}}},_focusInput:function(){this._focusElement(this.filterInput);
},_allowOpening:function(){return this.hasOptionLabel()||this.filterInput||this.dataSource.view().length;
},toggle:function(O){this._toggle(O,true);
},current:function(O){var P;
if(O===N){P=this.listView.focus();
if(!P&&this.selectedIndex===0&&this.hasOptionLabel()){return this.optionLabel;
}return P;
}this._focus(O);
},dataItem:function(P){var Q=this;
var O=null;
if(P===null){return P;
}if(P===N){O=Q.listView.selectedDataItems()[0];
}else{if(typeof P!=="number"){if(Q.options.virtual){return Q.dataSource.getByUid(l(P).data("uid"));
}if(P.hasClass("k-list-optionlabel")){P=-1;
}else{P=l(Q.items()).index(P);
}}else{if(Q.hasOptionLabel()){P-=1;
}}O=Q.dataSource.flatView()[P];
}if(!O){O=Q._optionLabelDataItem();
}return O;
},refresh:function(){this.listView.refresh();
},text:function(R){var S=this;
var O,Q;
var P=S.options.ignoreCase;
R=R===null?"":R;
if(R!==N){if(typeof R==="string"){Q=P?R.toLowerCase():R;
S._select(function(T){T=S._text(T);
if(P){T=(T+"").toLowerCase();
}return T===Q;
});
O=S.dataItem();
if(O){R=O;
}}S._textAccessor(R);
}else{return S._textAccessor();
}},value:function(R){var Q=this;
var P=Q.listView;
var O=Q.dataSource;
if(R===N){R=Q._accessor()||Q.listView.value()[0];
return R===N||R===null?"":R;
}if(R||!Q.hasOptionLabel()){Q._initialIndex=null;
}this.trigger("set",{value:R});
if(Q._request&&Q.options.cascadeFrom&&Q.listView.bound()){if(Q._valueSetter){O.unbind(q,Q._valueSetter);
}Q._valueSetter=D(function(){Q.value(R);
},Q);
O.one(q,Q._valueSetter);
return;
}if(Q._isFilterEnabled()&&P.bound()&&P.isFiltered()){P.bound(false);
Q._filterSource();
}else{Q._fetchData();
}P.value(R).done(function(){if(Q.selectedIndex===-1&&Q.text()){Q.text("");
Q._accessor("",-1);
}Q._old=Q._accessor();
Q._oldIndex=Q.selectedIndex;
});
},hasOptionLabel:function(){return this.optionLabel&&!!this.optionLabel[0];
},_optionLabel:function(){var R=this;
var P=R.options;
var O=P.optionLabel;
var Q=P.optionLabelTemplate;
if(!O){R.optionLabel.off().remove();
R.optionLabel=l();
return;
}if(!Q){Q="#:";
if(typeof O==="string"){Q+="data";
}else{Q+=w.expr(P.dataTextField,"data");
}Q+="#";
}if(typeof Q!=="function"){Q=w.template(Q);
}R.optionLabelTemplate=Q;
if(!R.hasOptionLabel()){R.optionLabel=l('<div class="k-list-optionlabel"></div>').prependTo(R.list);
}R.optionLabel.html(Q(O)).off().click(D(R._click,R)).on(v,R._toggleHover);
R.angular("compile",function(){return{elements:R.optionLabel};
});
},_optionLabelText:function(){var O=this.options.optionLabel;
return typeof O==="string"?O:this._text(O);
},_optionLabelDataItem:function(){var P=this;
var O=P.options.optionLabel;
if(P.hasOptionLabel()){return l.isPlainObject(O)?new C(O):P._assignInstance(P._optionLabelText(),"");
}return null;
},_buildOptions:function(O){var Q=this;
if(!Q._isSelect){return;
}var R=Q.listView.value()[0];
var P=Q._optionLabelDataItem();
if(R===N||R===null){R="";
}if(P){P='<option value="'+Q._value(P)+'">'+Q._text(P)+"</option>";
}Q._options(O,P,R);
if(R!==y.unifyType(Q._accessor(),typeof R)){Q._customOption=null;
Q._custom(R);
}},_listBound:function(){var S=this;
var R=S._initialIndex;
var Q=S._state===I;
var O=S.dataSource.flatView();
var P;
S._angularItems("compile");
S._presetValue=false;
S._resizePopup(true);
S.popup.position();
S._buildOptions(O);
S._makeUnselectable();
if(!Q){if(S._open){S.toggle(S._allowOpening());
}S._open=false;
if(!S._fetch){if(O.length){if(!S.listView.value().length&&R>-1&&R!==null){S.select(R);
}S._initialIndex=null;
P=S.listView.selectedDataItems()[0];
if(P&&S.text()!==S._text(P)){S._selectValue(P);
}}else{if(S._textAccessor()!==S._optionLabelText()){S.listView.value("");
S._selectValue(null);
S._oldIndex=S.selectedIndex;
}}}}S._hideBusy();
S.trigger("dataBound");
},_listChange:function(){this._selectValue(this.listView.selectedDataItems()[0]);
if(this._presetValue||this._old&&this._oldIndex===-1){this._oldIndex=this.selectedIndex;
}},_focusHandler:function(){this.wrapper.focus();
},_focusinHandler:function(){this._inputWrapper.addClass(u);
this._prevent=false;
},_focusoutHandler:function(){var R=this;
var O=R._state===I;
var Q=window.self!==window.top;
var P=R._focus();
if(!R._prevent){clearTimeout(R._typingTimeout);
if(O&&P&&!R.trigger("select",{item:P})){R._select(P,!R.dataSource.view().length);
}if(K.mobileOS.ios&&Q){R._change();
}else{R._blur();
}R._inputWrapper.removeClass(u);
R._prevent=true;
R._open=false;
R.element.blur();
}},_wrapperMousedown:function(){this._prevent=!!this.filterInput;
},_wrapperClick:function(O){O.preventDefault();
this.popup.unbind("activate",this._focusInputHandler);
this._focused=this.wrapper;
this._toggle();
},_editable:function(R){var T=this;
var Q=T.element;
var O=R.disable;
var S=R.readonly;
var U=T.wrapper.add(T.filterInput).off(B);
var P=T._inputWrapper.off(v);
if(!S&&!O){Q.removeAttr(s).removeAttr(E);
P.addClass(r).removeClass(J).on(v,T._toggleHover);
U.attr(L,U.data(L)).attr(n,false).attr(o,false).on("keydown"+B,D(T._keydown,T)).on("focusin"+B,D(T._focusinHandler,T)).on("focusout"+B,D(T._focusoutHandler,T)).on("mousedown"+B,D(T._wrapperMousedown,T));
T.wrapper.on("click"+B,D(T._wrapperClick,T));
if(!T.filterInput){U.on("keypress"+B,D(T._keypress,T));
}}else{if(O){U.removeAttr(L);
P.addClass(J).removeClass(r);
}else{P.addClass(r).removeClass(J);
U.on("focusin"+B,D(T._focusinHandler,T)).on("focusout"+B,D(T._focusoutHandler,T));
}}Q.attr(s,O).attr(E,S);
U.attr(n,O).attr(o,S);
},_keydown:function(P){var U=this;
var T=P.keyCode;
var O=P.altKey;
var R;
var Q;
var S=U.popup.visible();
if(U.filterInput){R=U.filterInput[0]===m();
}if(T===x.LEFT){T=x.UP;
Q=true;
}else{if(T===x.RIGHT){T=x.DOWN;
Q=true;
}}if(Q&&R){return;
}P.keyCode=T;
if(O&&T===x.UP||T===x.ESC){U._focusElement(U.wrapper);
}if(T===x.ENTER&&U._typingTimeout&&U.filterInput&&S){P.preventDefault();
return;
}Q=U._move(P);
if(Q){return;
}if(!S||!U.filterInput){if(T===x.HOME){Q=true;
U._firstItem();
}else{if(T===x.END){Q=true;
U._lastItem();
}}if(Q){U._select(U._focus());
P.preventDefault();
}}if(!O&&!Q&&U.filterInput){U._search();
}},_matchText:function(P,Q){var O=this.options.ignoreCase;
if(P===N||P===null){return false;
}P=P+"";
if(O){P=P.toLowerCase();
}return P.indexOf(Q)===0;
},_shuffleData:function(O,Q){var P=this._optionLabelDataItem();
if(P){O=[P].concat(O);
}return O.slice(Q).concat(O.slice(0,Q));
},_selectNext:function(){var V=this;
var O=V.dataSource.flatView();
var P=O.length+(V.hasOptionLabel()?1:0);
var R=F(V._word,V._last);
var T=V.selectedIndex;
var S;
var U;
if(T===-1){T=0;
}else{T+=R?1:0;
T=A(T,P);
}O=O.toJSON?O.toJSON():O.slice();
O=V._shuffleData(O,T);
for(var Q=0;
Q<P;
Q++){U=V._text(O[Q]);
if(R&&V._matchText(U,V._last)){break;
}else{if(V._matchText(U,V._word)){break;
}}}if(Q!==P){S=V._focus();
V._select(A(T+Q,P));
if(V.trigger("select",{item:V._focus()})){V._select(S);
}if(!V.popup.visible()){V._change();
}}},_keypress:function(P){var Q=this;
if(P.which===0||P.keyCode===w.keys.ENTER){return;
}var O=String.fromCharCode(P.charCode||P.keyCode);
if(Q.options.ignoreCase){O=O.toLowerCase();
}if(O===" "){P.preventDefault();
}Q._word+=O;
Q._last=O;
Q._search();
},_popupOpen:function(){var O=this.popup;
O.wrapper=w.wrap(O.element);
if(O.element.closest(".km-root")[0]){O.wrapper.addClass("km-popup km-widget");
this.wrapper.addClass("km-widget");
}},_popup:function(){G.fn._popup.call(this);
this.popup.one("open",D(this._popupOpen,this));
},_click:function(O){var P=O.item||l(O.currentTarget);
O.preventDefault();
if(this.trigger("select",{item:P})){this.close();
return;
}this._userTriggered=true;
this._select(P);
this._focusElement(this.wrapper);
this._blur();
},_focusElement:function(Q){var O=m();
var T=this.wrapper;
var R=this.filterInput;
var P=Q===R?T:R;
var S=K.mobileOS&&(K.touch||K.MSPointers||K.pointers);
if(R&&R[0]===Q[0]&&S){return;
}if(R&&P[0]===O){this._prevent=true;
this._focused=Q.focus();
}},_filter:function(Q){if(Q){var P=this;
var O=P.options.ignoreCase;
if(O){Q=Q.toLowerCase();
}P._select(function(R){return P._matchText(P._text(R),Q);
});
}},_search:function(){var P=this;
var O=P.dataSource;
clearTimeout(P._typingTimeout);
if(P._isFilterEnabled()){P._typingTimeout=setTimeout(function(){var Q=P.filterInput.val();
if(P._prev!==Q){P._prev=Q;
P.search(Q);
}P._typingTimeout=null;
},P.options.delay);
}else{P._typingTimeout=setTimeout(function(){P._word="";
},P.options.delay);
if(!P.listView.bound()){O.fetch().done(function(){P._selectNext();
});
return;
}P._selectNext();
}},_get:function(O){var P,Q,R;
var S=typeof O==="function";
var T=!S?l(O):l();
if(this.hasOptionLabel()){if(typeof O==="number"){if(O>-1){O-=1;
}}else{if(T.hasClass("k-list-optionlabel")){O=-1;
}}}if(S){P=this.dataSource.flatView();
for(R=0;
R<P.length;
R++){if(O(P[R])){O=R;
Q=true;
break;
}}if(!Q){O=-1;
}}return O;
},_firstItem:function(){if(this.hasOptionLabel()){this._focus(this.optionLabel);
}else{this.listView.focusFirst();
}},_lastItem:function(){this._resetOptionLabel();
this.listView.focusLast();
},_nextItem:function(){if(this.optionLabel.hasClass("k-state-focused")){this._resetOptionLabel();
this.listView.focusFirst();
}else{this.listView.focusNext();
}},_prevItem:function(){if(this.optionLabel.hasClass("k-state-focused")){return;
}this.listView.focusPrev();
if(!this.listView.focus()){this._focus(this.optionLabel);
}},_focusItem:function(){var Q=this.listView;
var O=Q.focus();
var P=Q.select();
P=P[P.length-1];
if(P===N&&this.options.highlightFirst&&!O){P=0;
}if(P!==N){Q.focus(P);
}else{if(this.options.optionLabel){this._focus(this.optionLabel);
this._select(this.optionLabel);
}else{Q.scrollToIndex(0);
}}},_resetOptionLabel:function(O){this.optionLabel.removeClass("k-state-focused"+(O||"")).removeAttr("id");
},_focus:function(O){var P=this.listView;
var Q=this.optionLabel;
if(O===N){O=P.focus();
if(!O&&Q.hasClass("k-state-focused")){O=Q;
}return O;
}this._resetOptionLabel();
O=this._get(O);
P.focus(O);
if(O===-1){Q.addClass("k-state-focused").attr("id",P._optionID);
this._focused.add(this.filterInput).removeAttr("aria-activedescendant").attr("aria-activedescendant",P._optionID);
}},_select:function(O,P){var Q=this;
O=Q._get(O);
Q.listView.select(O);
if(!P&&Q._state===I){Q._state=H;
}if(O===-1){Q._selectValue(null);
}},_selectValue:function(O){var S=this;
var Q=S.options.optionLabel;
var P=S.listView.select();
var T="";
var R="";
P=P[P.length-1];
if(P===N){P=-1;
}this._resetOptionLabel(" k-state-selected");
if(O){R=O;
T=S._dataValue(O);
if(Q){P+=1;
}}else{if(Q){S._focus(S.optionLabel.addClass("k-state-selected"));
R=S._optionLabelText();
if(typeof Q==="string"){T="";
}else{T=S._value(Q);
}P=0;
}}S.selectedIndex=P;
if(T===null){T="";
}S._textAccessor(R);
S._accessor(T,P);
S._triggerCascade();
},_mobile:function(){var R=this,P=R.popup,O=K.mobileOS,Q=P.element.parents(".km-root").eq(0);
if(Q.length&&O){P.options.animation.open.effects=O.android||O.meego?"fadeIn":O.ios||O.wp?"slideIn:up":P.options.animation.open.effects;
}},_filterHeader:function(){var O;
if(this.filterInput){this.filterInput.off(B).parent().remove();
this.filterInput=null;
}if(this._isFilterEnabled()){O='<span unselectable="on" class="k-icon k-i-search">select</span>';
this.filterInput=l('<input class="k-textbox"/>').attr({placeholder:this.element.attr("placeholder"),role:"listbox","aria-haspopup":true,"aria-expanded":false});
this.list.prepend(l('<span class="k-list-filter" />').append(this.filterInput.add(O)));
}},_span:function(){var Q=this,R=Q.wrapper,O="span.k-input",P;
P=R.find(O);
if(!P[0]){R.append('<span unselectable="on" class="k-dropdown-wrap k-state-default"><span unselectable="on" class="k-input">&nbsp;</span><span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-arrow-s">select</span></span></span>').append(Q.element);
P=R.find(O);
}Q.span=P;
Q._inputWrapper=l(R[0].firstChild);
Q._arrow=R.find(".k-icon");
},_wrapper:function(){var Q=this,P=Q.element,O=P[0],R;
R=P.parent();
if(!R.is("span.k-widget")){R=P.wrap("<span />").parent();
R[0].style.cssText=O.style.cssText;
R[0].title=O.title;
}P.hide();
Q._focused=Q.wrapper=R.addClass("k-widget k-dropdown k-header").addClass(O.className).css("display","").attr({accesskey:P.attr("accesskey"),unselectable:"on",role:"listbox","aria-haspopup":true,"aria-expanded":false});
},_clearSelection:function(O){this.select(O.value()?0:-1);
},_inputTemplate:function(){var Q=this,P=Q.options.valueTemplate;
if(!P){P=l.proxy(w.template("#:this._text(data)#",{useWithBlock:false}),Q);
}else{P=w.template(P);
}Q.valueTemplate=P;
if(Q.hasOptionLabel()){try{Q.valueTemplate(Q._optionLabelDataItem());
}catch(O){throw new Error(z);
}}},_textAccessor:function(V){var O=null;
var U=this.valueTemplate;
var S=this.options;
var R=S.optionLabel;
var T=this.span;
if(V!==N){if(l.isPlainObject(V)||V instanceof C){O=V;
}else{if(R&&this._optionLabelText()===V){O=R;
U=this.optionLabelTemplate;
}}if(!O){O=this._assignInstance(V,this._accessor());
}var Q=function(){return{elements:T.get(),data:[{dataItem:O}]};
};
this.angular("cleanup",Q);
try{T.html(U(O));
}catch(P){T.html("");
}this.angular("compile",Q);
}else{return T.text();
}},_preselect:function(P,O){if(!P&&!O){O=this._optionLabelText();
}this._accessor(P);
this._textAccessor(O);
this._old=this._accessor();
this._oldIndex=this.selectedIndex;
this.listView.setValue(P);
this._initialIndex=null;
this._presetValue=true;
},_assignInstance:function(Q,R){var P=this.options.dataTextField;
var O={};
if(P){p(O,P.split("."),Q);
p(O,this.options.dataValueField.split("."),R);
O=new C(O);
}else{O=Q;
}return O;
}});
function p(R,P,T){var Q=0,S=P.length-1,O;
for(;
Q<S;
++Q){O=P[Q];
if(!(O in R)){R[O]={};
}R=R[O];
}R[P[S]]=T;
}function A(O,P){if(O>=P){O-=P;
}return O;
}function F(Q,O){for(var P=0;
P<Q.length;
P++){if(Q.charAt(P)!==O){return false;
}}return true;
}M.plugin(t);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
