(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.editable",["kendo.datepicker","kendo.numerictextbox","kendo.validator","kendo.binder"],l);
}(function(){var k={id:"editable",name:"Editable",category:"framework",depends:["datepicker","numerictextbox","validator","binder"],hidden:true};
(function(l,E){var z=window.kendo,D=z.ui,F=D.Widget,u=l.extend,B=z.support.browser.msie&&z.support.browser.version<9,x=z.isFunction,y=l.isPlainObject,w=l.inArray,A=/("|\%|'|\[|\]|\$|\.|\,|\:|\;|\+|\*|\&|\!|\#|\(|\)|<|>|\=|\?|\@|\^|\{|\}|\~|\/|\||`)/g,t='<div class="k-widget k-tooltip k-tooltip-validation" style="margin:0.5em"><span class="k-icon k-warning"> </span>#=message#<div class="k-callout k-callout-n"></div></div>',n="change";
var C=["url","email","number","date","boolean"];
function v(G){G=G!=null?G:"";
return G.type||l.type(G)||"string";
}function p(G){G.find(":input:not(:button, ["+z.attr("role")+"=upload], ["+z.attr("skip")+"], [type=file]), select").each(function(){var H=z.attr("bind"),I=this.getAttribute(H)||"",J=this.type==="checkbox"||this.type==="radio"?"checked:":"value:",K=this.name;
if(I.indexOf(J)===-1&&K){I+=(I.length?",":"")+J+K;
l(this).attr(H,I);
}});
}function q(K){var J=(K.model.fields||K.model)[K.field],N=v(J),O=J?J.validation:{},M,I=z.attr("type"),H=z.attr("bind"),L,G={name:K.field};
for(M in O){L=O[M];
if(w(M,C)>=0){G[I]=M;
}else{if(!x(L)){G[M]=y(L)?L.value||M:L;
}}G[z.attr(M+"-msg")]=L.message;
}if(w(N,C)>=0){G[I]=N;
}G[H]=(N==="boolean"?"checked:":"value:")+K.field;
return G;
}function o(I){var G,J,H,M,L,K;
if(I&&I.length){K=[];
for(G=0,J=I.length;
G<J;
G++){H=I[G];
L=H.text||H.value||H;
M=H.value==null?H.text||H:H.value;
K[G]={text:L,value:M};
}}return K;
}var s={number:function(H,I){var G=q(I);
l('<input type="text"/>').attr(G).appendTo(H).kendoNumericTextBox({format:I.format});
l("<span "+z.attr("for")+'="'+I.field+'" class="k-invalid-msg"/>').hide().appendTo(H);
},date:function(H,J){var G=q(J),I=J.format;
if(I){I=z._extractFormat(I);
}G[z.attr("format")]=I;
l('<input type="text"/>').attr(G).appendTo(H).kendoDatePicker({format:J.format});
l("<span "+z.attr("for")+'="'+J.field+'" class="k-invalid-msg"/>').hide().appendTo(H);
},string:function(H,I){var G=q(I);
l('<input type="text" class="k-input k-textbox"/>').attr(G).appendTo(H);
},"boolean":function(H,I){var G=q(I);
l('<input type="checkbox" />').attr(G).appendTo(H);
},values:function(H,J){var G=q(J);
var I=z.stringify(o(J.values));
l("<select "+z.attr("text-field")+'="text"'+z.attr("value-field")+'="value"'+z.attr("source")+"='"+(I?I.replace(/\'/g,"&apos;"):I)+"'"+z.attr("role")+'="dropdownlist"/>').attr(G).appendTo(H);
l("<span "+z.attr("for")+'="'+J.field+'" class="k-invalid-msg"/>').hide().appendTo(H);
}};
function m(H,J){var K=H?H.validation||{}:{},I,G;
for(I in K){G=K[I];
if(y(G)&&G.value){G=G.value;
}if(x(G)){J[I]=G;
}}}var r=F.extend({init:function(G,H){var I=this;
if(H.target){H.$angular=H.target.options.$angular;
}F.fn.init.call(I,G,H);
I._validateProxy=l.proxy(I._validate,I);
I.refresh();
},events:[n],options:{name:"Editable",editors:s,clearContainer:true,errorTemplate:t},editor:function(J,P){var Q=this,I=Q.options.editors,M=y(J),K=M?J.field:J,O=Q.options.model||{},N=M&&J.values,R=N?"values":v(P),L=M&&J.editor,H=L?J.editor:I[R],G=Q.element.find("["+z.attr("container-for")+"="+K.replace(A,"\\$1")+"]");
H=H?H:I.string;
if(L&&typeof J.editor==="string"){H=function(S){S.append(J.editor);
};
}G=G.length?G:Q.element;
H(G,u(true,{},M?J:{field:K},{model:O}));
},_validate:function(I){var M=this,K,N=I.value,L=M._validationEventInProgress,O={},G=z.attr("bind"),J=I.field.replace(A,"\\$1"),H=new RegExp("(value|checked)\\s*:\\s*"+J+"\\s*(,|$)");
O[I.field]=I.value;
K=l(":input["+G+'*="'+J+'"]',M.element).filter("["+z.attr("validate")+"!='false']").filter(function(){return H.test(l(this).attr(G));
});
if(K.length>1){K=K.filter(function(){var P=l(this);
return !P.is(":radio")||P.val()==N;
});
}try{M._validationEventInProgress=true;
if(!M.validatable.validateInput(K)||!L&&M.trigger(n,{values:O})){I.preventDefault();
}}finally{M._validationEventInProgress=false;
}},end:function(){return this.validatable.validate();
},destroy:function(){var G=this;
G.angular("cleanup",function(){return{elements:G.element};
});
F.fn.destroy.call(G);
G.options.model.unbind("set",G._validateProxy);
z.unbind(G.element);
if(G.validatable){G.validatable.destroy();
}z.destroy(G.element);
G.element.removeData("kendoValidator");
if(G.element.is("["+z.attr("role")+"=editable]")){G.element.removeAttr(z.attr("role"));
}},refresh:function(){var S=this,L,N,J=S.options.fields||[],G=S.options.clearContainer?S.element.empty():S.element,O=S.options.model||{},R={},H,M,I,P,Q;
if(!l.isArray(J)){J=[J];
}for(L=0,N=J.length;
L<N;
L++){H=J[L];
M=y(H);
I=M?H.field:H;
P=(O.fields||O)[I];
m(P,R);
S.editor(H,P);
}if(S.options.target){S.angular("compile",function(){return{elements:G,data:G.map(function(){return{dataItem:O};
})};
});
}if(!N){Q=O.fields||O;
for(I in Q){m(Q[I],R);
}}p(G);
if(S.validatable){S.validatable.destroy();
}z.bind(G,S.options.model);
S.options.model.unbind("set",S._validateProxy);
S.options.model.bind("set",S._validateProxy);
S.validatable=new z.ui.Validator(G,{validateOnBlur:false,errorTemplate:S.options.errorTemplate||E,rules:R});
var K=G.find(":kendoFocusable").eq(0).focus();
if(B){K.focus();
}}});
D.plugin(r);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
