(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.popup",["kendo.core"],l);
}(function(){var k={id:"popup",name:"Pop-up",category:"framework",depends:["core"],advanced:true};
(function(l,T){var E=window.kendo,S=E.ui,V=S.Widget,P=E.support,C=E.getOffset,J="open",v="close",y="deactivate",n="activate",u="center",F="left",M="right",Q="top",t="bottom",m="absolute",D="hidden",s="body",G="location",L="position",U="visible",A="effects",o="k-state-active",p="k-state-border",q=/k-state-border-(\w+)/,r=".k-picker-wrap, .k-dropdown-wrap, .k-link",H="down",z=l(document.documentElement),W=l(window),N="scroll",x=P.transitions.css,R=x+"transform",B=l.extend,I=".kendoPopup",O=["font-size","font-family","font-stretch","font-style","font-weight","line-height"];
function w(X,Y){return X===Y||l.contains(X,Y);
}var K=V.extend({init:function(X,Y){var aa=this,Z;
Y=Y||{};
if(Y.isRtl){Y.origin=Y.origin||t+" "+M;
Y.position=Y.position||Q+" "+M;
}V.fn.init.call(aa,X,Y);
X=aa.element;
Y=aa.options;
aa.collisions=Y.collision?Y.collision.split(" "):[];
aa.downEvent=E.applyEventMap(H,E.guid());
if(aa.collisions.length===1){aa.collisions.push(aa.collisions[0]);
}Z=l(aa.options.anchor).closest(".k-popup,.k-group").filter(":not([class^=km-])");
Y.appendTo=l(l(Y.appendTo)[0]||Z[0]||s);
aa.element.hide().addClass("k-popup k-group k-reset").toggleClass("k-rtl",!!Y.isRtl).css({position:m}).appendTo(Y.appendTo).on("mouseenter"+I,function(){aa._hovered=true;
}).on("mouseleave"+I,function(){aa._hovered=false;
});
aa.wrapper=l();
if(Y.animation===false){Y.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}B(Y.animation.open,{complete:function(){aa.wrapper.css({overflow:U});
aa._activated=true;
aa._trigger(n);
}});
B(Y.animation.close,{complete:function(){aa._animationClose();
}});
aa._mousedownProxy=function(ab){aa._mousedown(ab);
};
if(P.mobileOS.android){aa._resizeProxy=function(ab){setTimeout(function(){aa._resize(ab);
},600);
};
}else{aa._resizeProxy=function(ab){aa._resize(ab);
};
}if(Y.toggleTarget){l(Y.toggleTarget).on(Y.toggleEvent+I,l.proxy(aa.toggle,aa));
}},events:[J,n,v,y],options:{name:"Popup",toggleEvent:"click",origin:t+" "+F,position:Q+" "+F,anchor:s,appendTo:null,collision:"flip fit",viewport:window,copyAnchorStyles:true,autosize:false,modal:false,adjustSize:{width:0,height:0},animation:{open:{effects:"slideIn:down",transition:true,duration:200},close:{duration:100,hide:true}}},_animationClose:function(){var Y=this;
var X=Y.wrapper.data(G);
Y.wrapper.hide();
if(X){Y.wrapper.css(X);
}if(Y.options.anchor!=s){Y._hideDirClass();
}Y._closing=false;
Y._trigger(y);
},destroy:function(){var aa=this,Y=aa.options,X=aa.element.off(I),Z;
V.fn.destroy.call(aa);
if(Y.toggleTarget){l(Y.toggleTarget).off(I);
}if(!Y.modal){z.unbind(aa.downEvent,aa._mousedownProxy);
aa._toggleResize(false);
}E.destroy(aa.element.children());
X.removeData();
if(Y.appendTo[0]===document.body){Z=X.parent(".k-animation-container");
if(Z[0]){Z.remove();
}else{X.remove();
}}},open:function(af,ag){var ad=this,aa={isFixed:!isNaN(parseInt(ag,10)),x:af,y:ag},Z=ad.element,ac=ad.options,Y,ae,X=l(ac.anchor),ab=Z[0]&&Z.hasClass("km-widget");
if(!ad.visible()){if(ac.copyAnchorStyles){if(ab&&O[0]=="font-size"){O.shift();
}Z.css(E.getComputedStyles(X[0],O));
}if(Z.data("animating")||ad._trigger(J)){return;
}ad._activated=false;
if(!ac.modal){z.unbind(ad.downEvent,ad._mousedownProxy).bind(ad.downEvent,ad._mousedownProxy);
ad._toggleResize(false);
ad._toggleResize(true);
}ad.wrapper=ae=E.wrap(Z,ac.autosize).css({overflow:D,display:"block",position:m});
if(P.mobileOS.android){ae.css(R,"translatez(0)");
}ae.css(L);
if(l(ac.appendTo)[0]==document.body){ae.css(Q,"-10000px");
}ad.flipped=ad._position(aa);
Y=ad._openAnimation();
if(ac.anchor!=s){ad._showDirClass(Y);
}Z.data(A,Y.effects).kendoStop(true).kendoAnimate(Y);
}},_openAnimation:function(){var X=B(true,{},this.options.animation.open);
X.effects=E.parseEffects(X.effects,this.flipped);
return X;
},_hideDirClass:function(){var X=l(this.options.anchor);
var Z=((X.attr("class")||"").match(q)||["","down"])[1];
var Y=p+"-"+Z;
X.removeClass(Y).children(r).removeClass(o).removeClass(Y);
this.element.removeClass(p+"-"+E.directions[Z].reverse);
},_showDirClass:function(X){var Z=X.effects.slideIn?X.effects.slideIn.direction:"down";
var Y=p+"-"+Z;
l(this.options.anchor).addClass(Y).children(r).addClass(o).addClass(Y);
this.element.addClass(p+"-"+E.directions[Z].reverse);
},position:function(){if(this.visible()){this.flipped=this._position();
}},toggle:function(){var X=this;
X[X.visible()?v:J]();
},visible:function(){return this.element.is(":"+U);
},close:function(ab){var ac=this,aa=ac.options,ad,X,Z,Y;
if(ac.visible()){ad=ac.wrapper[0]?ac.wrapper:E.wrap(ac.element).hide();
ac._toggleResize(false);
if(ac._closing||ac._trigger(v)){ac._toggleResize(true);
return;
}ac.element.find(".k-popup").each(function(){var af=l(this),ae=af.data("kendoPopup");
if(ae){ae.close(ab);
}});
z.unbind(ac.downEvent,ac._mousedownProxy);
if(ab){X={hide:true,effects:{}};
}else{X=B(true,{},aa.animation.close);
Z=ac.element.data(A);
Y=X.effects;
if(!Y&&!E.size(Y)&&Z&&E.size(Z)){X.effects=Z;
X.reverse=true;
}ac._closing=true;
}ac.element.kendoStop(true);
ad.css({overflow:D});
ac.element.kendoAnimate(X);
}},_trigger:function(X){return this.trigger(X,{type:X});
},_resize:function(X){var Y=this;
if(P.resize.indexOf(X.type)!==-1){clearTimeout(Y._resizeTimeout);
Y._resizeTimeout=setTimeout(function(){Y._position();
Y._resizeTimeout=null;
},50);
}else{if(!Y._hovered||Y._activated&&Y.element.hasClass("k-list-container")){Y.close();
}}},_toggleResize:function(Z){var Y=Z?"on":"off";
var X=P.resize;
if(!(P.mobileOS.ios||P.mobileOS.android)){X+=" "+N;
}this._scrollableParents()[Y](N,this._resizeProxy);
W[Y](X,this._resizeProxy);
},_mousedown:function(Z){var ae=this,Y=ae.element[0],ab=ae.options,X=l(ab.anchor)[0],af=ab.toggleTarget,ad=E.eventTarget(Z),ac=l(ad).closest(".k-popup"),aa=ac.parent().parent(".km-shim").length;
ac=ac[0];
if(!aa&&ac&&ac!==ae.element[0]){return;
}if(l(Z.target).closest("a").data("rel")==="popover"){return;
}if(!w(Y,ad)&&!w(X,ad)&&!(af&&w(l(af)[0],ad))){ae.close();
}},_fit:function(Y,Z,aa){var X=0;
if(Y+Z>aa){X=aa-(Y+Z);
}if(Y<0){X=-Y;
}return X;
},_flip:function(Z,ad,X,ae,aa,ac,Y){var ab=0;
Y=Y||ad;
if(ac!==aa&&ac!==u&&aa!==u){if(Z+Y>ae){ab+=-(X+ad);
}if(Z+ab<0){ab+=X+ad;
}}return ab;
},_scrollableParents:function(){return l(this.options.anchor).parentsUntil("body").filter(function(Y,X){return E.isScrollable(X);
});
},_position:function(ae){var au=this,ac=au.element,az=au.wrapper,am=au.options,av=l(am.viewport),ax=av.offset(),Y=l(am.anchor),an=am.origin.toLowerCase().split(" "),ar=am.position.toLowerCase().split(" "),aa=au.collisions,aC=P.zoomLevel(),at,ao,ap,aB=10002,ah=!!(av[0]==window&&window.innerWidth&&aC<=1.02),ag=0,ab=document.documentElement,ai,ay,aw;
ay=ah?window.innerWidth:av.width();
aw=ah?window.innerHeight:av.height();
if(ah&&ab.scrollHeight-ab.clientHeight>0){ay-=E.support.scrollbar();
}at=Y.parents().filter(az.siblings());
if(at[0]){ap=Math.max(Number(at.css("zIndex")),0);
if(ap){aB=ap+10;
}else{ao=Y.parentsUntil(at);
for(ai=ao.length;
ag<ai;
ag++){ap=Number(l(ao[ag]).css("zIndex"));
if(ap&&aB<ap){aB=ap+10;
}}}}az.css("zIndex",aB);
if(ae&&ae.isFixed){az.css({left:ae.x,top:ae.y});
}else{az.css(au._align(an,ar));
}var aq=C(az,L,Y[0]===az.offsetParent()[0]),ak=C(az),Z=Y.offsetParent().parent(".k-animation-container,.k-popup,.k-group");
if(Z.length){aq=C(az,L,true);
ak=C(az);
}if(av[0]===window){ak.top-=window.pageYOffset||document.documentElement.scrollTop||0;
ak.left-=window.pageXOffset||document.documentElement.scrollLeft||0;
}else{ak.top-=ax.top;
ak.left-=ax.left;
}if(!au.wrapper.data(G)){az.data(G,B({},aq));
}var al=B({},ak),aj=B({},aq),X=am.adjustSize;
if(aa[0]==="fit"){aj.top+=au._fit(al.top,az.outerHeight()+X.height,aw/aC);
}if(aa[1]==="fit"){aj.left+=au._fit(al.left,az.outerWidth()+X.width,ay/aC);
}var af=B({},aj);
var ad=ac.outerHeight();
var aA=az.outerHeight();
if(!az.height()&&ad){aA=aA+ad;
}if(aa[0]==="flip"){aj.top+=au._flip(al.top,ad,Y.outerHeight(),aw/aC,an[0],ar[0],aA);
}if(aa[1]==="flip"){aj.left+=au._flip(al.left,ac.outerWidth(),Y.outerWidth(),ay/aC,an[1],ar[1],az.outerWidth());
}ac.css(L,m);
az.css(aj);
return aj.left!=af.left||aj.top!=af.top;
},_align:function(ai,aj){var al=this,ad=al.wrapper,X=l(al.options.anchor),an=ai[0],af=ai[1],ao=aj[0],ag=aj[1],Z=C(X),ab=l(al.options.appendTo),ac,ap=ad.outerWidth(),ae=ad.outerHeight(),aa=X.outerWidth(),Y=X.outerHeight(),am=Z.top,ah=Z.left,ak=Math.round;
if(ab[0]!=document.body){ac=C(ab);
am-=ac.top;
ah-=ac.left;
}if(an===t){am+=Y;
}if(an===u){am+=ak(Y/2);
}if(ao===t){am-=ae;
}if(ao===u){am-=ak(ae/2);
}if(af===M){ah+=aa;
}if(af===u){ah+=ak(aa/2);
}if(ag===M){ah-=ap;
}if(ag===u){ah-=ak(ap/2);
}return{top:am,left:ah};
}});
S.plugin(K);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
