(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.validator",["kendo.core"],l);
}(function(){var k={id:"validator",name:"Validator",category:"web",description:"The Validator offers an easy way to do a client-side form validation.",depends:["core"]};
(function(l,I){var w=window.kendo,M=w.ui.Widget,A=".kendoValidator",u="k-invalid-msg",v=new RegExp(u,"i"),t="k-invalid",L="k-valid",p=/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i,J=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i,s=":input:not(:button,[type=submit],[type=reset],[disabled],[readonly])",n=":checkbox:not([disabled],[readonly])",B="[type=number],[type=range]",m="blur",y="name",q="form",z="novalidate",F=l.proxy,E=function(O,N){if(typeof N==="string"){N=new RegExp("^(?:"+N+")$");
}return N.test(O);
},x=function(N,P,O){var Q=N.val();
if(N.filter(P).length&&Q!==""){return E(Q,O);
}return true;
},r=function(N,O){if(N.length){return N[0].attributes[O]!=null;
}return false;
};
if(!w.ui.validator){w.ui.validator={rules:{},messages:{}};
}function G(N){var P=w.ui.validator.ruleResolvers||{},Q={},O;
for(O in P){l.extend(true,Q,P[O].resolve(N));
}return Q;
}function o(N){return N.replace(/&amp/g,"&amp;").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">");
}function C(N){N=(N+"").split(".");
if(N.length>1){return N[1].length;
}return 0;
}function D(N){if(l.parseHTML){return l(l.parseHTML(N));
}return l(N);
}function H(Q,R){var O=l(),P,N;
for(var S=0,T=Q.length;
S<T;
S++){P=Q[S];
if(v.test(P.className)){N=P.getAttribute(w.attr("for"));
if(N===R){O=O.add(P);
}}}return O;
}var K=M.extend({init:function(N,O){var Q=this,P=G(N),R="["+w.attr("validate")+"!=false]";
O=O||{};
O.rules=l.extend({},w.ui.validator.rules,P.rules,O.rules);
O.messages=l.extend({},w.ui.validator.messages,P.messages,O.messages);
M.fn.init.call(Q,N,O);
Q._errorTemplate=w.template(Q.options.errorTemplate);
if(Q.element.is(q)){Q.element.attr(z,z);
}Q._inputSelector=s+R;
Q._checkboxSelector=n+R;
Q._errors={};
Q._attachEvents();
Q._isValidated=false;
},events:["validate","change"],options:{name:"Validator",errorTemplate:'<span class="k-widget k-tooltip k-tooltip-validation"><span class="k-icon k-warning"> </span> #=message#</span>',messages:{required:"{0} is required",pattern:"{0} is not valid",min:"{0} should be greater than or equal to {1}",max:"{0} should be smaller than or equal to {1}",step:"{0} is not valid",email:"{0} is not valid email",url:"{0} is not valid URL",date:"{0} is not valid date",dateCompare:"End date should be greater than or equal to the start date"},rules:{required:function(O){var N=O.filter("[type=checkbox]").length&&!O.is(":checked"),P=O.val();
return !(r(O,"required")&&(P===""||!P||N));
},pattern:function(N){if(N.filter("[type=text],[type=email],[type=url],[type=tel],[type=search],[type=password]").filter("[pattern]").length&&N.val()!==""){return E(N.val(),N.attr("pattern"));
}return true;
},min:function(N){if(N.filter(B+",["+w.attr("type")+"=number]").filter("[min]").length&&N.val()!==""){var O=parseFloat(N.attr("min"))||0,P=w.parseFloat(N.val());
return O<=P;
}return true;
},max:function(N){if(N.filter(B+",["+w.attr("type")+"=number]").filter("[max]").length&&N.val()!==""){var O=parseFloat(N.attr("max"))||0,P=w.parseFloat(N.val());
return O>=P;
}return true;
},step:function(O){if(O.filter(B+",["+w.attr("type")+"=number]").filter("[step]").length&&O.val()!==""){var P=parseFloat(O.attr("min"))||0,R=parseFloat(O.attr("step"))||1,S=parseFloat(O.val()),N=C(R),Q;
if(N){Q=Math.pow(10,N);
return Math.floor((S-P)*Q)%(R*Q)/Math.pow(100,N)===0;
}return(S-P)%R===0;
}return true;
},email:function(N){return x(N,"[type=email],["+w.attr("type")+"=email]",p);
},url:function(N){return x(N,"[type=url],["+w.attr("type")+"=url]",J);
},date:function(N){if(N.filter("[type^=date],["+w.attr("type")+"=date]").length&&N.val()!==""){return w.parseDate(N.val(),N.attr(w.attr("format")))!==null;
}return true;
}},validateOnBlur:true},destroy:function(){M.fn.destroy.call(this);
this.element.off(A);
},value:function(){if(!this._isValidated){return false;
}return this.errors().length===0;
},_submit:function(N){if(!this.validate()){N.stopPropagation();
N.stopImmediatePropagation();
N.preventDefault();
return false;
}return true;
},_checkElement:function(N){var O=this.value();
this.validateInput(N);
if(this.value()!==O){this.trigger("change");
}},_attachEvents:function(){var N=this;
if(N.element.is(q)){N.element.on("submit"+A,F(N._submit,N));
}if(N.options.validateOnBlur){if(!N.element.is(s)){N.element.on(m+A,N._inputSelector,function(){N._checkElement(l(this));
});
N.element.on("click"+A,N._checkboxSelector,function(){N._checkElement(l(this));
});
}else{N.element.on(m+A,function(){N._checkElement(N.element);
});
if(N.element.is(n)){N.element.on("click"+A,function(){N._checkElement(N.element);
});
}}}},validate:function(){var O;
var N;
var S=false;
var R;
var Q=this.value();
this._errors={};
if(!this.element.is(s)){var P=false;
O=this.element.find(this._inputSelector);
for(N=0,R=O.length;
N<R;
N++){if(!this.validateInput(O.eq(N))){P=true;
}}S=!P;
}else{S=this.validateInput(this.element);
}this.trigger("validate",{valid:S});
if(Q!==S){this.trigger("change");
}return S;
},validateInput:function(P){P=l(P);
this._isValidated=true;
var W=this,V=W._errorTemplate,U=W._checkValidity(P),X=U.valid,N="."+u,O=P.attr(y)||"",Q=W._findMessageContainer(O).add(P.next(N).filter(function(){var Y=l(this);
if(Y.filter("["+w.attr("for")+"]").length){return Y.attr(w.attr("for"))===O;
}return true;
})).hide(),T;
P.removeAttr("aria-invalid");
if(!X){T=W._extractMessage(P,U.key);
W._errors[O]=T;
var S=D(V({message:o(T)}));
var R=Q.attr("id");
W._decorateMessageContainer(S,O);
if(R){S.attr("id",R);
}if(!Q.replaceWith(S).length){S.insertAfter(P);
}S.show();
P.attr("aria-invalid",true);
}else{delete W._errors[O];
}P.toggleClass(t,!X);
P.toggleClass(L,X);
return X;
},hideMessages:function(){var P=this,N="."+u,O=P.element;
if(!O.is(s)){O.find(N).hide();
}else{O.next(N).hide();
}},_findMessageContainer:function(O){var R=w.ui.validator.messageLocators,S,N=l();
for(var P=0,Q=this.element.length;
P<Q;
P++){N=N.add(H(this.element[P].getElementsByTagName("*"),O));
}for(S in R){N=N.add(R[S].locate(this.element,O));
}return N;
},_decorateMessageContainer:function(N,O){var P=w.ui.validator.messageLocators,Q;
N.addClass(u).attr(w.attr("for"),O||"");
for(Q in P){P[Q].decorate(N,O);
}N.attr("role","alert");
},_extractMessage:function(P,Q){var R=this,N=R.options.messages[Q],O=P.attr(y);
N=w.isFunction(N)?N(P):N;
return w.format(P.attr(w.attr(Q+"-msg"))||P.attr("validationMessage")||P.attr("title")||N||"",O,P.attr(Q)||P.attr(w.attr(Q)));
},_checkValidity:function(N){var P=this.options.rules,O;
for(O in P){if(!P[O].call(this,N)){return{valid:false,key:O};
}}return{valid:true};
},errors:function(){var P=[],O=this._errors,N;
for(N in O){P.push(O[N]);
}return P;
}});
w.ui.plugin(K);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
