(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.window",["kendo.draganddrop"],l);
}(function(){var k={id:"window",name:"Window",category:"web",description:"The Window widget displays content in a modal or non-modal HTML window.",depends:["draganddrop"]};
(function(l,ag){var F=window.kendo,ai=F.ui.Widget,v=F.ui.Draggable,D=l.isPlainObject,n=F._activeElement,X=l.proxy,A=l.extend,x=l.each,ad=F.template,o="body",ae,T=".kendoWindow",L=".k-window",O=".k-window-title",P=O+"bar",M=".k-window-content",N=".k-resize-handle",I=".k-overlay",E="k-content-frame",Q="k-loading",H="k-state-hover",G="k-state-focused",R="k-window-maximized",ah=":visible",B="hidden",r="cursor",U="open",m="activate",s="deactivate",p="close",Y="refresh",aa="resize",ab="resizeEnd",w="dragstart",u="dragend",y="error",V="overflow",am="zIndex",S=".k-window-actions .k-i-minimize,.k-window-actions .k-i-maximize",J=".k-i-pin",K=".k-i-unpin",W=J+","+K,af=".k-window-titlebar .k-window-action",Z=".k-window-titlebar .k-i-refresh",C=F.isLocalUrl;
function t(an){return typeof an!="undefined";
}function q(ap,ao,an){return Math.max(Math.min(parseInt(ap,10),an===Infinity?an:parseInt(an,10)),parseInt(ao,10));
}function ac(an,ao){return function(){var ar=this,at=ar.wrapper,aq=at[0].style,ap=ar.options;
if(ap.isMaximized||ap.isMinimized){return ar;
}ar.restoreOptions={width:aq.width,height:aq.height};
at.children(N).hide().end().children(P).find(S).parent().hide().eq(0).before(ae.action({name:"Restore"}));
ao.call(ar);
if(an=="maximize"){ar.wrapper.children(P).find(W).parent().hide();
}else{ar.wrapper.children(P).find(W).parent().show();
}return ar;
};
}function z(){return !this.type||this.type.toLowerCase().indexOf("script")>=0;
}var aj=ai.extend({init:function(ap,au){var ax=this,aA,at={},ay,ao,av,ar=false,an,az,aw=au&&au.actions&&!au.actions.length,aq;
ai.fn.init.call(ax,ap,au);
au=ax.options;
av=au.position;
ap=ax.element;
an=au.content;
if(aw){au.actions=[];
}ax.appendTo=l(au.appendTo);
if(an&&!D(an)){an=au.content={url:an};
}ap.find("script").filter(z).remove();
if(!ap.parent().is(ax.appendTo)&&(av.top===ag||av.left===ag)){if(ap.is(ah)){at=ap.offset();
ar=true;
}else{ay=ap.css("visibility");
ao=ap.css("display");
ap.css({visibility:B,display:""});
at=ap.offset();
ap.css({visibility:ay,display:ao});
}if(av.top===ag){av.top=at.top;
}if(av.left===ag){av.left=at.left;
}}if(!t(au.visible)||au.visible===null){au.visible=ap.is(ah);
}aA=ax.wrapper=ap.closest(L);
if(!ap.is(".k-content")||!aA[0]){ap.addClass("k-window-content k-content");
ax._createWindow(ap,au);
aA=ax.wrapper=ap.closest(L);
ax._dimensions();
}ax._position();
if(au.pinned){ax.pin(true);
}if(an){ax.refresh(an);
}if(au.visible){ax.toFront();
}az=aA.children(M);
ax._tabindex(az);
if(au.visible&&au.modal){ax._overlay(aA.is(ah)).css({opacity:0.5});
}aA.on("mouseenter"+T,af,X(ax._buttonEnter,ax)).on("mouseleave"+T,af,X(ax._buttonLeave,ax)).on("click"+T,"> "+af,X(ax._windowActionHandler,ax));
az.on("keydown"+T,X(ax._keydown,ax)).on("focus"+T,X(ax._focus,ax)).on("blur"+T,X(ax._blur,ax));
this._resizable();
this._draggable();
aq=ap.attr("id");
if(aq){aq=aq+"_wnd_title";
aA.children(P).children(O).attr("id",aq);
az.attr({role:"dialog","aria-labelledby":aq});
}aA.add(aA.children(".k-resize-handle,"+P)).on("mousedown"+T,X(ax.toFront,ax));
ax.touchScroller=F.touchScroller(ap);
ax._resizeHandler=X(ax._onDocumentResize,ax);
ax._marker=F.guid().substring(0,8);
l(window).on("resize"+T+ax._marker,ax._resizeHandler);
if(au.visible){ax.trigger(U);
ax.trigger(m);
}F.notify(ax);
},_buttonEnter:function(an){l(an.currentTarget).addClass(H);
},_buttonLeave:function(an){l(an.currentTarget).removeClass(H);
},_focus:function(){this.wrapper.addClass(G);
},_blur:function(){this.wrapper.removeClass(G);
},_dimensions:function(){var av=this.wrapper;
var ar=this.options;
var au=ar.width;
var ao=ar.height;
var aq=ar.maxHeight;
var an=["minWidth","minHeight","maxWidth","maxHeight"];
this.title(ar.title);
for(var ap=0;
ap<an.length;
ap++){var at=ar[an[ap]];
if(at&&at!=Infinity){av.css(an[ap],at);
}}if(aq&&aq!=Infinity){this.element.css("maxHeight",aq);
}if(au){if(au.toString().indexOf("%")>0){av.width(au);
}else{av.width(q(au,ar.minWidth,ar.maxWidth));
}}if(ao){if(ao.toString().indexOf("%")>0){av.height(ao);
}else{av.height(q(ao,ar.minHeight,ar.maxHeight));
}}if(!ar.visible){av.hide();
}},_position:function(){var ao=this.wrapper,an=this.options.position;
if(an.top===0){an.top=an.top.toString();
}if(an.left===0){an.left=an.left.toString();
}ao.css({top:an.top||"",left:an.left||""});
},_animationOptions:function(ap){var an=this.options.animation;
var ao={open:{effects:{}},close:{hide:true,effects:{}}};
return an&&an[ap]||ao[ap];
},_resize:function(){F.resize(this.element.children());
},_resizable:function(){var an=this.options.resizable;
var ao=this.wrapper;
if(this.resizing){ao.off("dblclick"+T).children(N).remove();
this.resizing.destroy();
this.resizing=null;
}if(an){ao.on("dblclick"+T,P,X(function(ap){if(!l(ap.target).closest(".k-window-action").length){this.toggleMaximization();
}},this));
x("n e s w se sw ne nw".split(" "),function(aq,ap){ao.append(ae.resizeHandle(ap));
});
this.resizing=new al(this);
}ao=null;
},_draggable:function(){var an=this.options.draggable;
if(this.dragging){this.dragging.destroy();
this.dragging=null;
}if(an){this.dragging=new ak(this,an.dragHandle||P);
}},_actions:function(){var an=this.options.actions;
var ap=this.wrapper.children(P);
var ao=ap.find(".k-window-actions");
an=l.map(an,function(aq){return{name:aq};
});
ao.html(F.render(ae.action,an));
},setOptions:function(an){ai.fn.setOptions.call(this,an);
var ao=this.options.scrollable!==false;
this.restore();
this._dimensions();
this._position();
this._resizable();
this._draggable();
this._actions();
if(typeof an.modal!=="undefined"){var ap=this.options.visible!==false;
this._overlay(an.modal&&ap);
}this.element.css(V,ao?"":"hidden");
},events:[U,m,s,p,Y,aa,ab,w,u,y],options:{name:"Window",animation:{open:{effects:{zoom:{direction:"in"},fade:{direction:"in"}},duration:350},close:{effects:{zoom:{direction:"out",properties:{scale:0.7}},fade:{direction:"out"}},duration:350,hide:true}},title:"",actions:["Close"],autoFocus:true,modal:false,resizable:true,draggable:true,minWidth:90,minHeight:50,maxWidth:Infinity,maxHeight:Infinity,pinned:false,scrollable:true,position:{},content:null,visible:null,height:null,width:null,appendTo:"body"},_closable:function(){return l.inArray("close",l.map(this.options.actions,function(an){return an.toLowerCase();
}))>-1;
},_keydown:function(ao){var az=this,ay=az.options,au=F.keys,at=ao.keyCode,aB=az.wrapper,ax,aq,an=10,ar=az.options.isMaximized,aw,av,aA,ap;
if(ao.target!=ao.currentTarget||az._closing){return;
}if(at==au.ESC&&az._closable()){az._close(false);
}if(ay.draggable&&!ao.ctrlKey&&!ar){ax=F.getOffset(aB);
if(at==au.UP){aq=aB.css("top",ax.top-an);
}else{if(at==au.DOWN){aq=aB.css("top",ax.top+an);
}else{if(at==au.LEFT){aq=aB.css("left",ax.left-an);
}else{if(at==au.RIGHT){aq=aB.css("left",ax.left+an);
}}}}}if(ay.resizable&&ao.ctrlKey&&!ar){if(at==au.UP){aq=true;
av=aB.height()-an;
}else{if(at==au.DOWN){aq=true;
av=aB.height()+an;
}}if(at==au.LEFT){aq=true;
aw=aB.width()-an;
}else{if(at==au.RIGHT){aq=true;
aw=aB.width()+an;
}}if(aq){aA=q(aw,ay.minWidth,ay.maxWidth);
ap=q(av,ay.minHeight,ay.maxHeight);
if(!isNaN(aA)){aB.width(aA);
az.options.width=aA+"px";
}if(!isNaN(ap)){aB.height(ap);
az.options.height=ap+"px";
}az.resize();
}}if(aq){ao.preventDefault();
}},_overlay:function(ao){var an=this.appendTo.children(I),ap=this.wrapper;
if(!an.length){an=l("<div class='k-overlay' />");
}an.insertBefore(ap[0]).toggle(ao).css(am,parseInt(ap.css(am),10)-1);
return an;
},_actionForIcon:function(an){var ao=/\bk-i-\w+\b/.exec(an[0].className)[0];
return{"k-i-close":"_close","k-i-maximize":"maximize","k-i-minimize":"minimize","k-i-restore":"restore","k-i-refresh":"refresh","k-i-pin":"pin","k-i-unpin":"unpin"}[ao];
},_windowActionHandler:function(ao){if(this._closing){return;
}var ap=l(ao.target).closest(".k-window-action").find(".k-icon");
var an=this._actionForIcon(ap);
if(an){ao.preventDefault();
this[an]();
return false;
}},_modals:function(){var an=this;
var ao=l(L).filter(function(){var ap=l(this);
var aq=an._object(ap);
var ar=aq&&aq.options;
return ar&&ar.modal&&ar.visible&&ar.appendTo===an.options.appendTo&&ap.is(ah);
}).sort(function(ap,aq){return +l(ap).css("zIndex")-+l(aq).css("zIndex");
});
an=null;
return ao;
},_object:function(ao){var an=ao.children(M);
var ap=F.widgetInstance(an);
if(ap instanceof aj){return ap;
}return ag;
},center:function(){var au=this,aq=au.options.position,av=au.wrapper,an=l(window),at=0,ar=0,ap,ao;
if(au.options.isMaximized){return au;
}if(!au.options.pinned){at=an.scrollTop();
ar=an.scrollLeft();
}ao=ar+Math.max(0,(an.width()-av.width())/2);
ap=at+Math.max(0,(an.height()-av.height()-parseInt(av.css("paddingTop"),10))/2);
av.css({left:ao,top:ap});
aq.top=ap;
aq.left=ao;
return au;
},title:function(ao){var ap=this,au=ap.wrapper,an=ap.options,ar=au.children(P),aq=ar.children(O),at;
if(!arguments.length){return aq.html();
}if(ao===false){au.addClass("k-window-titleless");
ar.remove();
}else{if(!ar.length){au.prepend(ae.titlebar(an));
ap._actions();
ar=au.children(P);
}else{aq.html(ao);
}at=ar.outerHeight();
au.css("padding-top",at);
ar.css("margin-top",-at);
}ap.options.title=ao;
return ap;
},content:function(ap,ao){var an=this.wrapper.children(M),aq=an.children(".km-scroll-container");
an=aq[0]?aq:an;
if(!t(ap)){return an.html();
}this.angular("cleanup",function(){return{elements:an.children()};
});
F.destroy(this.element.children());
an.empty().html(ap);
this.angular("compile",function(){var ar=[];
for(var at=an.length;
--at>=0;
){ar.push({dataItem:ao});
}return{elements:an.children(),data:ar};
});
return this;
},open:function(){var au=this,av=au.wrapper,ap=au.options,at=this._animationOptions("open"),an=av.children(M),aq,ao=l(document);
if(!au.trigger(U)){if(au._closing){av.kendoStop(true,true);
}au._closing=false;
au.toFront();
if(ap.autoFocus){au.element.focus();
}ap.visible=true;
if(ap.modal){aq=au._overlay(false);
aq.kendoStop(true,true);
if(at.duration&&F.effects.Fade){var ar=F.fx(aq).fadeIn();
ar.duration(at.duration||0);
ar.endValue(0.5);
ar.play();
}else{aq.css("opacity",0.5);
}aq.show();
}if(!av.is(ah)){an.css(V,B);
av.show().kendoStop().kendoAnimate({effects:at.effects,duration:at.duration,complete:X(this._activate,this)});
}}if(ap.isMaximized){au._documentScrollTop=ao.scrollTop();
au._documentScrollLeft=ao.scrollLeft();
l("html, body").css(V,B);
}return au;
},_activate:function(){var an=this.options.scrollable!==false;
if(this.options.autoFocus){this.element.focus();
}this.element.css(V,an?"":"hidden");
this.trigger(m);
},_removeOverlay:function(au){var ap=this._modals();
var aq=this.options;
var ao=aq.modal&&!ap.length;
var ar=aq.modal?this._overlay(true):l(ag);
var an=this._animationOptions("close");
if(ao){if(!au&&an.duration&&F.effects.Fade){var at=F.fx(ar).fadeOut();
at.duration(an.duration||0);
at.startValue(0.5);
at.play();
}else{this._overlay(false).remove();
}}else{if(ap.length){this._object(ap.last())._overlay(true);
}}},_close:function(ar){var at=this,au=at.wrapper,ap=at.options,aq=this._animationOptions("open"),ao=this._animationOptions("close"),an=l(document);
if(au.is(ah)&&!at.trigger(p,{userTriggered:!ar})){if(at._closing){return;
}at._closing=true;
ap.visible=false;
l(L).each(function(ax,aw){var av=l(aw).children(M);
if(aw!=au&&av.find("> ."+E).length>0){av.children(I).remove();
}});
this._removeOverlay();
au.kendoStop().kendoAnimate({effects:ao.effects||aq.effects,reverse:ao.reverse===true,duration:ao.duration,complete:X(this._deactivate,this)});
}if(at.options.isMaximized){l("html, body").css(V,"");
if(at._documentScrollTop&&at._documentScrollTop>0){an.scrollTop(at._documentScrollTop);
}if(at._documentScrollLeft&&at._documentScrollLeft>0){an.scrollLeft(at._documentScrollLeft);
}}},_deactivate:function(){var ao=this;
ao.wrapper.hide().css("opacity","");
ao.trigger(s);
if(ao.options.modal){var an=ao._object(ao._modals().last());
if(an){an.toFront();
}}},close:function(){this._close(true);
return this;
},_actionable:function(an){return l(an).is(af+","+af+" .k-icon,:input,a");
},_shouldFocus:function(ap){var an=n(),ao=this.element;
return this.options.autoFocus&&!l(an).is(ao)&&!this._actionable(ap)&&(!ao.find(an).length||!ao.find(ap).length);
},toFront:function(ao){var at=this,av=at.wrapper,an=av[0],aw=+av.css(am),ap=aw,ar=ao&&ao.target||null;
l(L).each(function(az,ay){var aA=l(ay),aB=aA.css(am),ax=aA.children(M);
if(!isNaN(aB)){aw=Math.max(+aB,aw);
}if(ay!=an&&ax.find("> ."+E).length>0){ax.append(ae.overlay);
}});
if(!av[0].style.zIndex||ap<aw){av.css(am,aw+2);
}at.element.find("> .k-overlay").remove();
if(at._shouldFocus(ar)){at.element.focus();
var aq=l(window).scrollTop(),au=parseInt(av.position().top,10);
if(au>0&&au<aq){if(aq>0){l(window).scrollTop(au);
}else{av.css("top",aq);
}}}av=null;
return at;
},toggleMaximization:function(){if(this._closing){return this;
}return this[this.options.isMaximized?"restore":"maximize"]();
},restore:function(){var ar=this;
var ap=ar.options;
var ao=ap.minHeight;
var aq=ar.restoreOptions;
var an=l(document);
if(!ap.isMaximized&&!ap.isMinimized){return ar;
}if(ao&&ao!=Infinity){ar.wrapper.css("min-height",ao);
}ar.wrapper.css({position:ap.pinned?"fixed":"absolute",left:aq.left,top:aq.top,width:aq.width,height:aq.height}).removeClass(R).find(".k-window-content,.k-resize-handle").show().end().find(".k-window-titlebar .k-i-restore").parent().remove().end().end().find(S).parent().show().end().end().find(W).parent().show();
ar.options.width=aq.width;
ar.options.height=aq.height;
l("html, body").css(V,"");
if(this._documentScrollTop&&this._documentScrollTop>0){an.scrollTop(this._documentScrollTop);
}if(this._documentScrollLeft&&this._documentScrollLeft>0){an.scrollLeft(this._documentScrollLeft);
}ap.isMaximized=ap.isMinimized=false;
ar.resize();
return ar;
},maximize:ac("maximize",function(){var ap=this,aq=ap.wrapper,ao=aq.position(),an=l(document);
A(ap.restoreOptions,{left:ao.left,top:ao.top});
aq.css({left:0,top:0,position:"fixed"}).addClass(R);
this._documentScrollTop=an.scrollTop();
this._documentScrollLeft=an.scrollLeft();
l("html, body").css(V,B);
ap.options.isMaximized=true;
ap._onDocumentResize();
}),minimize:ac("minimize",function(){var an=this;
an.wrapper.css({height:"",minHeight:""});
an.element.hide();
an.options.isMinimized=true;
}),pin:function(an){var ap=this,ar=l(window),at=ap.wrapper,aq=parseInt(at.css("top"),10),ao=parseInt(at.css("left"),10);
if(an||!ap.options.pinned&&!ap.options.isMaximized){at.css({position:"fixed",top:aq-ar.scrollTop(),left:ao-ar.scrollLeft()});
at.children(P).find(J).addClass("k-i-unpin").removeClass("k-i-pin");
ap.options.pinned=true;
}},unpin:function(){var ao=this,aq=l(window),ar=ao.wrapper,ap=parseInt(ar.css("top"),10),an=parseInt(ar.css("left"),10);
if(ao.options.pinned&&!ao.options.isMaximized){ar.css({position:"",top:ap+aq.scrollTop(),left:an+aq.scrollLeft()});
ar.children(P).find(K).addClass("k-i-pin").removeClass("k-i-unpin");
ao.options.pinned=false;
}},_onDocumentResize:function(){var ao=this,ar=ao.wrapper,aq=l(window),at=F.support.zoomLevel(),ap,an;
if(!ao.options.isMaximized){return;
}ap=aq.width()/at;
an=aq.height()/at-parseInt(ar.css("padding-top"),10);
ar.css({width:ap,height:an});
ao.options.width=ap;
ao.options.height=an;
ao.resize();
},refresh:function(aq){var at=this,ap=at.options,an=l(at.element),ao,ar,au;
if(!D(aq)){aq={url:aq};
}aq=A({},ap.content,aq);
ar=t(ap.iframe)?ap.iframe:aq.iframe;
au=aq.url;
if(au){if(!t(ar)){ar=!C(au);
}if(!ar){at._ajaxRequest(aq);
}else{ao=an.find("."+E)[0];
if(ao){ao.src=au||ao.src;
}else{an.html(ae.contentFrame(A({},ap,{content:aq})));
}an.find("."+E).unbind("load"+T).on("load"+T,X(this._triggerRefresh,this));
}}else{if(aq.template){at.content(ad(aq.template)({}));
}at.trigger(Y);
}an.toggleClass("k-window-iframecontent",!!ar);
return at;
},_triggerRefresh:function(){this.trigger(Y);
},_ajaxComplete:function(){clearTimeout(this._loadingIconTimeout);
this.wrapper.find(Z).removeClass(Q);
},_ajaxError:function(ao,an){this.trigger(y,{status:an,xhr:ao});
},_ajaxSuccess:function(an){return function(ao){var ap=ao;
if(an){ap=ad(an)(ao||{});
}this.content(ap,ao);
this.element.prop("scrollTop",0);
this.trigger(Y);
};
},_showLoading:function(){this.wrapper.find(Z).addClass(Q);
},_ajaxRequest:function(an){this._loadingIconTimeout=setTimeout(X(this._showLoading,this),100);
l.ajax(A({type:"GET",dataType:"html",cache:false,error:X(this._ajaxError,this),complete:X(this._ajaxComplete,this),success:X(this._ajaxSuccess(an.template),this)},an));
},_destroy:function(){if(this.resizing){this.resizing.destroy();
}if(this.dragging){this.dragging.destroy();
}this.wrapper.off(T).children(M).off(T).end().find(".k-resize-handle,.k-window-titlebar").off(T);
l(window).off("resize"+T+this._marker);
clearTimeout(this._loadingIconTimeout);
ai.fn.destroy.call(this);
this.unbind(ag);
F.destroy(this.wrapper);
this._removeOverlay(true);
},destroy:function(){this._destroy();
this.wrapper.empty().remove();
this.wrapper=this.appendTo=this.element=l();
},_createWindow:function(){var an=this.element,aq=this.options,ao,ar,ap=F.support.isRtl(an);
if(aq.scrollable===false){an.attr("style","overflow:hidden;");
}ar=l(ae.wrapper(aq));
ao=an.find("iframe:not(.k-content)").map(function(){var at=this.getAttribute("src");
this.src="";
return at;
});
ar.toggleClass("k-rtl",ap).appendTo(this.appendTo).append(an).find("iframe:not(.k-content)").each(function(at){this.src=ao[at];
});
ar.find(".k-window-title").css(ap?"left":"right",ar.find(".k-window-actions").outerWidth()+10);
an.css("visibility","").show();
an.find("[data-role=editor]").each(function(){var at=l(this).data("kendoEditor");
if(at){at.refresh();
}});
ar=an=null;
}});
ae={wrapper:ad("<div class='k-widget k-window' />"),action:ad("<a role='button' href='\\#' class='k-window-action k-link'><span role='presentation' class='k-icon k-i-#= name.toLowerCase() #'>#= name #</span></a>"),titlebar:ad("<div class='k-window-titlebar k-header'>&nbsp;<span class='k-window-title'>#= title #</span><div class='k-window-actions' /></div>"),overlay:"<div class='k-overlay' />",contentFrame:ad("<iframe frameborder='0' title='#= title #' class='"+E+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),resizeHandle:ad("<div class='k-resize-handle k-resize-#= data #'></div>")};
function al(ao){var an=this;
an.owner=ao;
an._draggable=new v(ao.wrapper,{filter:">"+N,group:ao.wrapper.id+"-resizing",dragstart:X(an.dragstart,an),drag:X(an.drag,an),dragend:X(an.dragend,an)});
an._draggable.userEvents.bind("press",X(an.addOverlay,an));
an._draggable.userEvents.bind("release",X(an.removeOverlay,an));
}al.prototype={addOverlay:function(){this.owner.wrapper.append(ae.overlay);
},removeOverlay:function(){this.owner.wrapper.find(I).remove();
},dragstart:function(an){var ao=this;
var ap=ao.owner;
var aq=ap.wrapper;
ao.elementPadding=parseInt(aq.css("padding-top"),10);
ao.initialPosition=F.getOffset(aq,"position");
ao.resizeDirection=an.currentTarget.prop("className").replace("k-resize-handle k-resize-","");
ao.initialSize={width:aq.width(),height:aq.height()};
ao.containerOffset=F.getOffset(ap.appendTo,"position");
aq.children(N).not(an.currentTarget).hide();
l(o).css(r,an.currentTarget.css(r));
},drag:function(ap){var aw=this,az=aw.owner,aA=az.wrapper,av=az.options,ao=aw.resizeDirection,an=aw.containerOffset,aq=aw.initialPosition,ar=aw.initialSize,au,at,ax,ay,aB=Math.max(ap.x.location,an.left),aC=Math.max(ap.y.location,an.top);
if(ao.indexOf("e")>=0){au=aB-aq.left;
aA.width(q(au,av.minWidth,av.maxWidth));
}else{if(ao.indexOf("w")>=0){ay=aq.left+ar.width;
au=q(ay-aB,av.minWidth,av.maxWidth);
aA.css({left:ay-au-an.left,width:au});
}}if(ao.indexOf("s")>=0){at=aC-aq.top-aw.elementPadding;
aA.height(q(at,av.minHeight,av.maxHeight));
}else{if(ao.indexOf("n")>=0){ax=aq.top+ar.height;
at=q(ax-aC,av.minHeight,av.maxHeight);
aA.css({top:ax-at-an.top,height:at});
}}if(au){az.options.width=au+"px";
}if(at){az.options.height=at+"px";
}az.resize();
},dragend:function(an){var ao=this,ap=ao.owner,aq=ap.wrapper;
aq.children(N).not(an.currentTarget).show();
l(o).css(r,"");
if(ap.touchScroller){ap.touchScroller.reset();
}if(an.keyCode==27){aq.css(ao.initialPosition).css(ao.initialSize);
}ap.trigger(ab);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
function ak(ap,an){var ao=this;
ao.owner=ap;
ao._draggable=new v(ap.wrapper,{filter:an,group:ap.wrapper.id+"-moving",dragstart:X(ao.dragstart,ao),drag:X(ao.drag,ao),dragend:X(ao.dragend,ao),dragcancel:X(ao.dragcancel,ao)});
ao._draggable.userEvents.stopPropagation=false;
}ak.prototype={dragstart:function(ap){var ar=this.owner,aq=ar.element,an=aq.find(".k-window-actions"),ao=F.getOffset(ar.appendTo);
ar.trigger(w);
ar.initialWindowPosition=F.getOffset(ar.wrapper,"position");
ar.startPosition={left:ap.x.client-ar.initialWindowPosition.left,top:ap.y.client-ar.initialWindowPosition.top};
if(an.length>0){ar.minLeftPosition=an.outerWidth()+parseInt(an.css("right"),10)-aq.outerWidth();
}else{ar.minLeftPosition=20-aq.outerWidth();
}ar.minLeftPosition-=ao.left;
ar.minTopPosition=-ao.top;
ar.wrapper.append(ae.overlay).children(N).hide();
l(o).css(r,ap.currentTarget.css(r));
},drag:function(ao){var at=this.owner,ar=at.options.position,aq=Math.max(ao.y.client-at.startPosition.top,at.minTopPosition),ap=Math.max(ao.x.client-at.startPosition.left,at.minLeftPosition),an={left:ap,top:aq};
l(at.wrapper).css(an);
ar.top=aq;
ar.left=ap;
},_finishDrag:function(){var an=this.owner;
an.wrapper.children(N).toggle(!an.options.isMinimized).end().find(I).remove();
l(o).css(r,"");
},dragcancel:function(an){this._finishDrag();
an.currentTarget.closest(L).css(this.owner.initialWindowPosition);
},dragend:function(){this._finishDrag();
this.owner.trigger(u);
return false;
},destroy:function(){if(this._draggable){this._draggable.destroy();
}this._draggable=this.owner=null;
}};
F.ui.plugin(aj);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
