(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.chart.funnel",["kendo.dataviz.chart","kendo.drawing"],l);
}(function(){var k={id:"dataviz.chart.funnel",name:"Funnel Chart",category:"dataviz",depends:["dataviz.chart"],hidden:true};
(function(l,P){var F=window.kendo,v=F.deepExtend,y=l.extend,E=F.isFunction,N=F.template,Q=F.util,m=Q.append,w=F.drawing,D=F.geometry,u=F.dataviz,s=F.drawing.Color,r=u.ChartElement,H=u.PieChartMixin,I=u.PlotAreaBase,J=u.PlotAreaFactory,K=u.Point2D,p=u.Box2D,L=u.SeriesBinder,O=u.TextBox,n=u.autoFormat,x=u.evalOptions,G=Q.limitValue,M=u.seriesTotal;
var q="category",t="color",z="funnel",R="value",o="black",S="white";
var B=I.extend({render:function(){var T=this,U=T.series;
T.createFunnelChart(U);
},createFunnelChart:function(W){var V=this,T=W[0],U=new A(V,{series:W,legend:V.options.legend,neckRatio:T.neckRatio,dynamicHeight:T.dynamicHeight,dynamicSlope:T.dynamicSlope,segmentSpacing:T.segmentSpacing,highlight:T.highlight});
V.appendChart(U);
},appendChart:function(T,U){I.fn.appendChart.call(this,T,U);
m(this.options.legend.items,T.legendItems);
}});
var A=r.extend({init:function(V,U){var T=this;
r.fn.init.call(T,U);
T.plotArea=V;
T.points=[];
T.labels=[];
T.legendItems=[];
T.render();
},options:{neckRatio:0.3,width:300,dynamicSlope:false,dynamicHeight:true,segmentSpacing:0,labels:{visible:false,align:"center",position:"center"}},formatPointValue:function(U,T){return n(T,U.value);
},render:function(){var T=this,aa=T.options,U=T.plotArea.options.seriesColors||[],V=U.length,ad=aa.series[0],ab,X,W=ad.data;
if(!W){return;
}var ae=M(ad),af,Y;
for(Y=0;
Y<W.length;
Y++){ab=L.current.bindPoint(ad,Y);
af=ab.valueFields.value;
if(af===null||af===P){continue;
}X=ab.fields;
if(!E(ad.color)){ad.color=X.color||U[Y%V];
}X=v({index:Y,owner:T,series:ad,category:X.category,dataItem:W[Y],percentage:Math.abs(af)/ae,visibleInLegend:X.visibleInLegend,visible:X.visible},X);
var ac=T.createSegment(af,X);
var Z=T.createLabel(af,X);
if(ac&&Z){ac.append(Z);
}}},evalSegmentOptions:function(U,W,T){var V=T.series;
x(U,{value:W,series:V,dataItem:T.dataItem,index:T.index},{defaults:V._defaults,excluded:["data","toggle","visual"]});
},createSegment:function(X,U){var T=this,V;
var W=v({},U.series);
T.evalSegmentOptions(W,X,U);
T.createLegendItem(X,W,U);
if(U.visible!==false){V=new C(X,W,U);
y(V,U);
T.append(V);
T.points.push(V);
return V;
}},createLabel:function(ac,W){var U=this,Z=W.series,V=W.dataItem,X=v({},U.options.labels,Z.labels),aa=ac,ab;
if(X.visible){if(X.template){var Y=N(X.template);
aa=Y({dataItem:V,value:ac,percentage:W.percentage,category:W.category,series:Z});
}else{if(X.format){aa=n(X.format,aa);
}}if(!X.color&&X.align==="center"){var T=new s(Z.color).percBrightness();
if(T>180){X.color=o;
}else{X.color=S;
}}U.evalSegmentOptions(X,ac,W);
ab=new O(aa,v({vAlign:X.position},X));
U.labels.push(ab);
return ab;
}},labelPadding:function(){var W=this.labels,V,T,Y,X={left:0,right:0},U;
for(U=0;
U<W.length;
U++){V=W[U];
T=V.options.align;
if(T!=="center"){Y=W[U].box.width();
if(T==="left"){X.left=Math.max(X.left,Y);
}else{X.right=Math.max(X.right,Y);
}}}return X;
},reflow:function(V){var U=this,aj=U.options,ao=U.points,W=ao.length,X=aj.neckRatio<=1,ac,ab,ad,al,ak,ai,T=V.clone().unpad(U.labelPadding()),at=T.width(),am=0,an=X?0:(at-at/aj.neckRatio)/2,ap=aj.segmentSpacing,Y=aj.dynamicSlope,ar=T.height()-ap*(W-1),af=X?aj.neckRatio*at:at;
if(!W){return;
}if(Y){var aa=ao[0],ae=aa,ah,ag;
l.each(ao,function(au,av){if(av.percentage>ae.percentage){ae=av;
}});
ad=aa.percentage/ae.percentage*at;
an=(at-ad)/2;
for(ac=0;
ac<W;
ac++){ak=ao[ac].percentage;
ah=ao[ac+1];
ag=ah?ah.percentage:ak;
al=ao[ac].points=[];
ab=aj.dynamicHeight?ar*ak:ar/W;
if(!ak){ai=ag?0:at/2;
}else{ai=(at-ad*(ag/ak))/2;
}ai=G(ai,0,at);
al.push(new D.Point(T.x1+an,T.y1+am));
al.push(new D.Point(T.x1+at-an,T.y1+am));
al.push(new D.Point(T.x1+at-ai,T.y1+ab+am));
al.push(new D.Point(T.x1+ai,T.y1+ab+am));
an=ai;
am+=ab+ap;
ad=G(at-2*ai,0,at);
}}else{var aq=X?at:at-an*2,Z=(aq-af)/2;
for(ac=0;
ac<W;
ac++){al=ao[ac].points=[];
ak=ao[ac].percentage;
ai=aj.dynamicHeight?Z*ak:Z/W;
ab=aj.dynamicHeight?ar*ak:ar/W;
al.push(new D.Point(T.x1+an,T.y1+am));
al.push(new D.Point(T.x1+at-an,T.y1+am));
al.push(new D.Point(T.x1+at-an-ai,T.y1+ab+am));
al.push(new D.Point(T.x1+an+ai,T.y1+ab+am));
an+=ai;
am+=ab+ap;
}}for(ac=0;
ac<W;
ac++){ao[ac].reflow(V);
}}});
v(A.fn,H);
var C=r.extend({init:function(W,T,V){var U=this;
r.fn.init.call(U,T);
U.value=W;
U.options.index=V.index;
},options:{color:S,border:{width:1}},reflow:function(T){var W=this,V=W.points,U=W.children[0];
W.box=new p(V[0].x,V[0].y,V[1].x,V[2].y);
if(U){U.reflow(new p(T.x1,V[0].y,T.x2,V[2].y));
}},createVisual:function(){var U=this;
var T=U.options;
var V;
r.fn.createVisual.call(this);
if(T.visual){V=T.visual({category:U.category,dataItem:U.dataItem,value:U.value,series:U.series,percentage:U.percentage,points:U.points,options:T,createVisual:function(){return U.createPath();
}});
}else{V=U.createPath();
}if(V){this.visual.append(V);
}},createPath:function(){var U=this.options;
var T=U.border;
var V=w.Path.fromPoints(this.points,{fill:{color:U.color,opacity:U.opacity},stroke:{color:T.color,opacity:T.opacity,width:T.width}}).close();
return V;
},createHighlight:function(T){return w.Path.fromPoints(this.points,T);
},highlightVisual:function(){return this.visual.children[0];
},highlightVisualArgs:function(){var T=w.Path.fromPoints(this.points).close();
return{options:this.options,path:T};
},highlightOverlay:function(Z,X){var Y=this.options,W=Y.highlight||{};
if(W.visible===false){return;
}var T=W.border||{};
var U=y({},X,{fill:W.color,stroke:T.color,strokeOpacity:T.opacity,strokeWidth:T.width,fillOpacity:W.opacity});
var V=Z.createPolyline(this.points,true,U);
return V;
},tooltipAnchor:function(U){var T=this.box;
return new K(T.center().x-U/2,T.y1);
},formatValue:function(T){var U=this;
return U.owner.formatPointValue(U,T);
}});
v(C.fn,u.PointEventsMixin);
J.current.register(B,[z]);
L.current.register([z],[R],[q,t,"visibleInLegend","visible"]);
v(u,{FunnelChart:A,FunnelSegment:C});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
