(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.core",["kendo.core","kendo.drawing"],l);
}(function(){var k={id:"dataviz.core",name:"Core",description:"The DataViz core functions",category:"dataviz",depends:["core","drawing"],hidden:true};
(function(l,a0){var an=window.kendo,a1=an.util,n=a1.append,U=a1.defined,ao=a1.last,a2=a1.valueOrDefault,L=an.dataviz,ad=L.geometry,W=L.drawing,aw=W.util.measureText,C=an.Class,aT=an.template,aA=l.noop,ah=l.inArray,am=l.isPlainObject,aZ=l.trim,au=Math,O=an.deepExtend;
var r="axisLabelClick",t="#000",u="bottom",z="center",F=3,D="clip",B="circle",J="cross",P="12px sans-serif",Q=400,R=7,S=10,T=600,V=au.PI/180,ac=/\{\d+:?/,af="height",G=100000,ai=600,ak="inside",ap="left",aq="linear",av=Number.MAX_VALUE,ax=-Number.MAX_VALUE,az="none",aC="noteClick",aD="noteHover",aG="outside",aI="radial",aL="right",aX="top",aY="triangle",a4="width",a3="#fff",a5="x",a6="y",a7=0.2;
function ae(a8,X){var Y={top:0,right:0,bottom:0,left:0};
X=X||0;
if(typeof a8==="number"){Y[aX]=Y[aL]=Y[u]=Y[ap]=a8;
}else{Y[aX]=a8[aX]||X;
Y[aL]=a8[aL]||X;
Y[u]=a8[u]||X;
Y[ap]=a8[ap]||X;
}return Y;
}var aH=function(Y,a8){var X=this;
if(!(X instanceof aH)){return new aH(Y,a8);
}X.x=Y||0;
X.y=a8||0;
};
aH.fn=aH.prototype={clone:function(){var X=this;
return new aH(X.x,X.y);
},equals:function(X){return X&&X.x===this.x&&X.y===this.y;
},rotate:function(X,ba){var bb=this,bd=ba*V,Y=au.cos(bd),bc=au.sin(bd),a8=X.x,a9=X.y,be=bb.x,bf=bb.y;
bb.x=aP(a8+(be-a8)*Y+(bf-a9)*bc,F);
bb.y=aP(a9+(bf-a9)*Y-(be-a8)*bc,F);
return bb;
},multiply:function(X){var Y=this;
Y.x*=X;
Y.y*=X;
return Y;
},distanceTo:function(a8){var X=this.x-a8.x,Y=this.y-a8.y;
return au.sqrt(X*X+Y*Y);
}};
aH.onCircle=function(Y,X,a8){X*=V;
return new aH(Y.x-a8*au.cos(X),Y.y-a8*au.sin(X));
};
var v=function(Y,a9,a8,ba){var X=this;
if(!(X instanceof v)){return new v(Y,a9,a8,ba);
}X.x1=Y||0;
X.x2=a8||0;
X.y1=a9||0;
X.y2=ba||0;
};
v.fn=v.prototype={width:function(){return this.x2-this.x1;
},height:function(){return this.y2-this.y1;
},translate:function(Y,a8){var X=this;
X.x1+=Y;
X.x2+=Y;
X.y1+=a8;
X.y2+=a8;
return X;
},move:function(a9,ba){var X=this,Y=X.height(),a8=X.width();
if(U(a9)){X.x1=a9;
X.x2=X.x1+a8;
}if(U(ba)){X.y1=ba;
X.y2=X.y1+Y;
}return X;
},wrap:function(Y){var X=this;
X.x1=au.min(X.x1,Y.x1);
X.y1=au.min(X.y1,Y.y1);
X.x2=au.max(X.x2,Y.x2);
X.y2=au.max(X.y2,Y.y2);
return X;
},wrapPoint:function(X){this.wrap(new v(X.x,X.y,X.x,X.y));
return this;
},snapTo:function(a8,X){var Y=this;
if(X==a5||!X){Y.x1=a8.x1;
Y.x2=a8.x2;
}if(X==a6||!X){Y.y1=a8.y1;
Y.y2=a8.y2;
}return Y;
},alignTo:function(bc,X){var a8=this,ba=a8.height(),be=a8.width(),Y=X==aX||X==u?a6:a5,bb=Y==a6?ba:be;
if(X===z){var bd=bc.center();
var a9=a8.center();
a8.x1+=bd.x-a9.x;
a8.y1+=bd.y-a9.y;
}else{if(X===aX||X===ap){a8[Y+1]=bc[Y+1]-bb;
}else{a8[Y+1]=bc[Y+2];
}}a8.x2=a8.x1+be;
a8.y2=a8.y1+ba;
return a8;
},shrink:function(a8,Y){var X=this;
X.x2-=a8;
X.y2-=Y;
return X;
},expand:function(Y,X){this.shrink(-Y,-X);
return this;
},pad:function(Y){var X=this,a8=ae(Y);
X.x1-=a8.left;
X.x2+=a8.right;
X.y1-=a8.top;
X.y2+=a8.bottom;
return X;
},unpad:function(Y){var X=this,a8=ae(Y);
a8.left=-a8.left;
a8.top=-a8.top;
a8.right=-a8.right;
a8.bottom=-a8.bottom;
return X.pad(a8);
},clone:function(){var X=this;
return new v(X.x1,X.y1,X.x2,X.y2);
},center:function(){var X=this;
return new aH(X.x1+X.width()/2,X.y1+X.height()/2);
},containsPoint:function(Y){var X=this;
return Y.x>=X.x1&&Y.x<=X.x2&&Y.y>=X.y1&&Y.y<=X.y2;
},points:function(){var X=this;
return[new aH(X.x1,X.y1),new aH(X.x2,X.y1),new aH(X.x2,X.y2),new aH(X.x1,X.y2)];
},getHash:function(){var X=this;
return[X.x1,X.y1,X.x2,X.y2].join(",");
},overlaps:function(X){return !(X.y2<this.y1||this.y2<X.y1||X.x2<this.x1||this.x2<X.x1);
},rotate:function(bf){var X=this;
var bg=X.width();
var ba=X.height();
var Y=X.center();
var a8=Y.x;
var a9=Y.y;
var bb=aO(0,0,a8,a9,bf);
var bc=aO(bg,0,a8,a9,bf);
var bd=aO(bg,ba,a8,a9,bf);
var be=aO(0,ba,a8,a9,bf);
bg=au.max(bb.x,bc.x,bd.x,be.x)-au.min(bb.x,bc.x,bd.x,be.x);
ba=au.max(bb.y,bc.y,bd.y,be.y)-au.min(bb.y,bc.y,bd.y,be.y);
X.x2=X.x1+bg;
X.y2=X.y1+ba;
return X;
},toRect:function(){return new ad.Rect([this.x1,this.y1],[this.width(),this.height()]);
},hasSize:function(){return this.width()!==0&&this.height()!==0;
},align:function(bd,Y,X){var a8=this,a9=Y+1,ba=Y+2,bc=Y===a5?a4:af,bb=a8[bc]();
if(ag(X,[ap,aX])){a8[a9]=bd[a9];
a8[ba]=a8[a9]+bb;
}else{if(ag(X,[aL,u])){a8[ba]=bd[ba];
a8[a9]=a8[ba]-bb;
}else{if(X==z){a8[a9]=bd[a9]+(bd[bc]()-bb)/2;
a8[ba]=a8[a9]+bb;
}}}}};
var aM=C.extend({init:function(Y,a8,a9,bb,X){var ba=this;
ba.c=Y;
ba.ir=a8;
ba.r=a9;
ba.startAngle=bb;
ba.angle=X;
},clone:function(){var X=this;
return new aM(X.c,X.ir,X.r,X.startAngle,X.angle);
},middle:function(){return this.startAngle+this.angle/2;
},radius:function(Y,X){var a8=this;
if(X){a8.ir=Y;
}else{a8.r=Y;
}return a8;
},point:function(X,a9){var bc=this,ba=X*V,Y=au.cos(ba),a8=au.sin(ba),bb=a9?bc.ir:bc.r,bd=aP(bc.c.x-Y*bb,F),be=aP(bc.c.y-a8*bb,F);
return new aH(bd,be);
},adjacentBox:function(Y,bf,a8){var be=this.clone().expand(Y),bb=be.middle(),bc=be.point(bb),ba=bf/2,a9=a8/2,bg=bc.x-ba,bh=bc.y-a9,bd=au.sin(bb*V),X=au.cos(bb*V);
if(au.abs(bd)<0.9){bg+=ba*-X/au.abs(X);
}if(au.abs(X)<0.9){bh+=a9*-bd/au.abs(bd);
}return new v(bg,bh,bg+bf,bh+a8);
},containsPoint:function(be){var bg=this,X=bg.c,bd=bg.ir,bf=bg.r,bh=bg.startAngle,ba=bg.startAngle+bg.angle,a8=be.x-X.x,a9=be.y-X.y,bk=new aH(a8,a9),bi=bg.point(bh),bj=new aH(bi.x-X.x,bi.y-X.y),bb=bg.point(ba),bc=new aH(bb.x-X.x,bb.y-X.y),Y=aP(a8*a8+a9*a9,F);
return(bj.equals(bk)||E(bj,bk))&&!E(bc,bk)&&Y>=bd*bd&&Y<=bf*bf;
},getBBox:function(){var be=this,a8=new v(av,av,ax,ax),bf=aP(be.startAngle%360),a9=aP((bf+be.angle)%360),bc=be.ir,X=[0,90,180,270,bf,a9].sort(aF),bg=ah(bf,X),ba=ah(a9,X),Y,bb,bd;
if(bf==a9){Y=X;
}else{if(bg<ba){Y=X.slice(bg,ba+1);
}else{Y=[].concat(X.slice(0,ba+1),X.slice(bg,X.length));
}}for(bb=0;
bb<Y.length;
bb++){bd=be.point(Y[bb]);
a8.wrapPoint(bd);
a8.wrapPoint(bd,bc);
}if(!bc){a8.wrapPoint(be.c);
}return a8;
},expand:function(X){this.r+=X;
return this;
}});
var aQ=aM.extend({init:function(Y,a8,a9,X){aM.fn.init.call(this,Y,0,a8,a9,X);
},expand:function(X){return aM.fn.expand.call(this,X);
},clone:function(){var X=this;
return new aQ(X.c,X.r,X.startAngle,X.angle);
},radius:function(X){return aM.fn.radius.call(this,X);
},point:function(X){return aM.fn.point.call(this,X);
}});
var aR=function(){};
aR.fn=aR.prototype={createRing:function(be,bb){var bf=be.startAngle+180;
var a8=be.angle+bf;
var Y=new ad.Point(be.c.x,be.c.y);
var bd=au.max(be.r,0);
var ba=au.max(be.ir,0);
var X=new ad.Arc(Y,{startAngle:bf,endAngle:a8,radiusX:bd,radiusY:bd});
var bc=W.Path.fromArc(X,bb).close();
if(ba){X.radiusX=X.radiusY=ba;
var a9=X.pointAt(a8);
bc.lineTo(a9.x,a9.y);
bc.arc(a8,bf,ba,ba,true);
}else{bc.lineTo(Y.x,Y.y);
}return bc;
}};
aR.current=new aR();
var A=C.extend({init:function(Y){var X=this;
X.children=[];
X.options=O({},X.options,Y);
},reflow:function(bb){var a9=this,Y=a9.children,X,ba,a8;
for(ba=0;
ba<Y.length;
ba++){a8=Y[ba];
a8.reflow(bb);
X=X?X.wrap(a8.box):a8.box.clone();
}a9.box=X||bb;
},destroy:function(){var Y=this,X=Y.children,a8;
if(this.animation){this.animation.destroy();
}for(a8=0;
a8<X.length;
a8++){X[a8].destroy();
}},getRoot:function(){var X=this.parent;
return X?X.getRoot():null;
},getChart:function(){var X=this.getRoot();
if(X){return X.chart;
}},translateChildren:function(a8,a9){var ba=this,X=ba.children,Y=X.length,bb;
for(bb=0;
bb<Y;
bb++){X[bb].box.translate(a8,a9);
}},append:function(){n(this.children,arguments);
for(var X=0;
X<arguments.length;
X++){arguments[X].parent=this;
}},renderVisual:function(){if(this.options.visible===false){return;
}this.createVisual();
this.addVisual();
this.renderChildren();
this.createAnimation();
this.renderComplete();
},addVisual:function(){if(this.visual){this.visual.chartElement=this;
if(this.parent){this.parent.appendVisual(this.visual);
}}},renderChildren:function(){var X=this.children;
for(var Y=0;
Y<X.length;
Y++){X[Y].renderVisual();
}},createVisual:function(){this.visual=new L.drawing.Group({zIndex:this.options.zIndex,visible:a2(this.options.visible,true)});
},createAnimation:function(){if(this.visual){this.animation=W.Animation.create(this.visual,this.options.animation);
}},appendVisual:function(X){if(!X.chartElement){X.chartElement=this;
}if(X.options.noclip){this.clipRoot().visual.append(X);
}else{if(U(X.options.zIndex)){this.stackRoot().stackVisual(X);
}else{if(this.visual){this.visual.append(X);
}else{this.parent.appendVisual(X);
}}}},clipRoot:function(){if(this.parent){return this.parent.clipRoot();
}return this;
},stackRoot:function(){if(this.parent){return this.parent.stackRoot();
}return this;
},stackVisual:function(X){var bb=X.options.zIndex||0;
var ba=this.visual.children;
for(var a8=0;
a8<ba.length;
a8++){var a9=ba[a8];
var Y=a2(a9.options.zIndex,0);
if(Y>bb){break;
}}this.visual.insertAt(X,a8);
},traverse:function(X){var a8=this.children;
for(var a9=0;
a9<a8.length;
a9++){var Y=a8[a9];
X(Y);
if(Y.traverse){Y.traverse(X);
}}},closest:function(Y){var X=this;
var a8=false;
while(X&&!a8){a8=Y(X);
if(!a8){X=X.parent;
}}if(a8){return X;
}},renderComplete:l.noop,hasHighlight:function(){var X=(this.options||{}).highlight;
return !(!this.createHighlight||X&&X.visible===false);
},toggleHighlight:function(ba){var bb=this;
var Y=bb._highlight;
var a9=(bb.options||{}).highlight;
var X=(a9||{}).visual;
if(!Y){var a8={fill:{color:a3,opacity:0.2},stroke:{color:a3,width:1,opacity:0.2}};
if(X){Y=bb._highlight=X(l.extend(bb.highlightVisualArgs(),{createVisual:function(){return bb.createHighlight(a8);
},sender:bb.getChart(),series:bb.series,dataItem:bb.dataItem,category:bb.category,value:bb.value,percentage:bb.percentage,runningTotal:bb.runningTotal,total:bb.total}));
if(!Y){return;
}}else{Y=bb._highlight=bb.createHighlight(a8);
}Y.options.zIndex=bb.options.zIndex;
bb.appendVisual(Y);
}Y.visible(ba);
},createGradientOverlay:function(X,a8,Y){var a9=new W.Path(O({stroke:{color:az},fill:this.createGradient(Y),closed:X.options.closed},a8));
a9.segments.elements(X.segments.elements());
return a9;
},createGradient:function(X){if(this.parent){return this.parent.createGradient(X);
}}});
var aN=A.extend({init:function(X){var Y=this;
Y.gradients={};
A.fn.init.call(Y,X);
},options:{width:T,height:Q,background:a3,border:{color:t,width:0},margin:ae(5),zIndex:-2},reflow:function(){var ba=this,a9=ba.options,X=ba.children,Y=new v(0,0,a9.width,a9.height);
ba.box=Y.unpad(a9.margin);
for(var a8=0;
a8<X.length;
a8++){X[a8].reflow(Y);
Y=w(Y,X[a8].box)||v();
}},createVisual:function(){this.visual=new W.Group();
this.createBackground();
},createBackground:function(){var a9=this.options;
var Y=a9.border||{};
var a8=this.box.clone().pad(a9.margin).unpad(Y.width);
var X=W.Path.fromRect(a8.toRect(),{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType},fill:{color:a9.background,opacity:a9.opacity},zIndex:-10});
this.visual.append(X);
},getRoot:function(){return this;
},createGradient:function(bb){var a9=this.gradients;
var ba=a1.objectKey(bb);
var Y=L.Gradients[bb.gradient];
var X;
if(a9[ba]){X=a9[ba];
}else{var a8=O({},Y,bb);
if(Y.type=="linear"){X=new W.LinearGradient(a8);
}else{if(bb.innerRadius){a8.stops=aj(a8);
}X=new W.RadialGradient(a8);
X.supportVML=Y.supportVML!==false;
}a9[ba]=X;
}return X;
}});
var x=A.extend({options:{align:ap,vAlign:aX,margin:{},padding:{},border:{color:t,width:0},background:"",shrinkToFit:false,width:0,height:0,visible:true},reflow:function(bk){var ba=this,Y,a9,bg=ba.options,bl=bg.width,bc=bg.height,bb=bl&&bc,bj=bg.shrinkToFit,bf=ae(bg.margin),bh=ae(bg.padding),X=bg.border.width,a8=ba.children,bd,be;
function bi(){ba.align(bk,a5,bg.align);
ba.align(bk,a6,bg.vAlign);
ba.paddingBox=Y.clone().unpad(bf).unpad(X);
}a9=bk.clone();
if(bb){a9.x2=a9.x1+bl;
a9.y2=a9.y1+bc;
}if(bj){a9.unpad(bf).unpad(X).unpad(bh);
}A.fn.reflow.call(ba,a9);
if(bb){Y=ba.box=v(0,0,bl,bc);
}else{Y=ba.box;
}if(bj&&bb){bi();
a9=ba.contentBox=ba.paddingBox.clone().unpad(bh);
}else{a9=ba.contentBox=Y.clone();
Y.pad(bh).pad(X).pad(bf);
bi();
}ba.translateChildren(Y.x1-a9.x1+bf.left+X+bh.left,Y.y1-a9.y1+bf.top+X+bh.top);
for(bd=0;
bd<a8.length;
bd++){be=a8[bd];
be.reflow(be.box);
}},align:function(a8,Y,X){this.box.align(a8,Y,X);
},hasBox:function(){var X=this.options;
return X.border.width||X.background;
},createVisual:function(){A.fn.createVisual.call(this);
var X=this.options;
if(X.visible&&this.hasBox()){this.visual.append(W.Path.fromRect(this.paddingBox.toRect(),this.visualStyle()));
}},visualStyle:function(){var Y=this,a8=Y.options,X=a8.border||{};
return{stroke:{width:X.width,color:X.color,opacity:a2(X.opacity,a8.opacity),dashType:X.dashType},fill:{color:a8.background,opacity:a8.opacity},cursor:a8.cursor};
}});
var aU=A.extend({init:function(X,Y){var a8=this;
A.fn.init.call(a8,Y);
a8.content=X;
a8.reflow(v());
},options:{font:P,color:t,align:ap,vAlign:""},reflow:function(a8){var a9=this,X=a9.options,Y;
Y=X.size=aw(a9.content,{font:X.font});
a9.baseline=Y.baseline;
a9.box=v(a8.x1,a8.y1,a8.x1+Y.width,a8.y1+Y.height);
},createVisual:function(){var X=this.options;
this.visual=new W.Text(this.content,this.box.toRect().topLeft(),{font:X.font,fill:{color:X.color,opacity:X.opacity},cursor:X.cursor});
}});
var aa=A.extend({init:function(X){A.fn.init.call(this,X);
this._initDirection();
},_initDirection:function(){var X=this.options;
if(X.vertical){this.groupAxis=a5;
this.elementAxis=a6;
this.groupSizeField=a4;
this.elementSizeField=af;
this.groupSpacing=X.spacing;
this.elementSpacing=X.vSpacing;
}else{this.groupAxis=a6;
this.elementAxis=a5;
this.groupSizeField=af;
this.elementSizeField=a4;
this.groupSpacing=X.vSpacing;
this.elementSpacing=X.spacing;
}},options:{vertical:true,wrap:true,vSpacing:0,spacing:0},reflow:function(X){this.box=X.clone();
this.reflowChildren();
},reflowChildren:function(){var bd=this;
var X=bd.box;
var a8=bd.elementAxis;
var bf=bd.groupAxis;
var bb=bd.elementSizeField;
var bn=bd.groupSizeField;
var bk=bd.groupOptions();
var bl=bk.groups;
var bm=bl.length;
var bo=X[bf+1]+bd.alignStart(bk.groupsSize,X[bn]());
var bp=bo;
var bc;
var bi;
var be;
var bg;
var bh;
var bq;
var bj;
var Y;
var a9;
var ba;
if(bm){for(bj=0;
bj<bm;
bj++){be=bl[bj];
bg=be.groupElements;
bh=bg.length;
bc=X[a8+1];
for(bq=0;
bq<bh;
bq++){Y=bg[bq];
ba=bd.elementSize(Y);
bi=bp+bd.alignStart(ba[bn],be.groupSize);
a9=v();
a9[bf+1]=bi;
a9[bf+2]=bi+ba[bn];
a9[a8+1]=bc;
a9[a8+2]=bc+ba[bb];
Y.reflow(a9);
bc+=ba[bb]+bd.elementSpacing;
}bp+=be.groupSize+bd.groupSpacing;
}X[bf+1]=bo;
X[bf+2]=bo+bk.groupsSize;
X[a8+2]=X[a8+1]+bk.maxGroupElementsSize;
}},alignStart:function(a8,Y){var a9=0;
var X=this.options.align;
if(X==aL||X==u){a9=Y-a8;
}else{if(X==z){a9=(Y-a8)/2;
}}return a9;
},groupOptions:function(){var bd=this;
var X=bd.box;
var Y=bd.children;
var a8=Y.length;
var bb=this.elementSizeField;
var bi=this.groupSizeField;
var bc=this.elementSpacing;
var bj=this.groupSpacing;
var bn=aP(X[bb]());
var bl=0;
var bh=0;
var ba;
var a9;
var bf=0;
var bk=0;
var bg=[];
var be=[];
var bm=0;
for(bl=0;
bl<a8;
bl++){a9=Y[bl];
if(!a9.box){a9.reflow(X);
}ba=this.elementSize(a9);
if(bd.options.wrap&&aP(bf+bc+ba[bb])>bn){bg.push({groupElements:be,groupSize:bh,groupElementsSize:bf});
bm=au.max(bm,bf);
bk+=bj+bh;
bh=0;
bf=0;
be=[];
}bh=au.max(bh,ba[bi]);
if(bf>0){bf+=bc;
}bf+=ba[bb];
be.push(a9);
}bg.push({groupElements:be,groupSize:bh,groupElementsSize:bf});
bm=au.max(bm,bf);
bk+=bh;
return{groups:bg,groupsSize:bk,maxGroupElementsSize:bm};
},elementSize:function(X){return{width:X.box.width(),height:X.box.height()};
},createVisual:aA});
var aV=x.extend({ROWS_SPLIT_REGEX:/\n|\\n/m,init:function(X,Y){var a8=this;
a8.content=X;
x.fn.init.call(a8,Y);
a8._initContainer();
a8.reflow(v());
},_initContainer:function(){var bb=this;
var Y=bb.options;
var a9=(bb.content+"").split(bb.ROWS_SPLIT_REGEX);
var X=new aa({vertical:true,align:Y.align,wrap:false});
var bc=O({},Y,{opacity:1,animation:null});
var ba;
var a8;
bb.container=X;
bb.append(X);
for(a8=0;
a8<a9.length;
a8++){ba=new aU(aZ(a9[a8]),bc);
X.append(ba);
}},reflow:function(a9){var a8=this.options;
var bb=a8.visual;
this.container.options.align=a8.align;
if(bb&&!this._boxReflow){if(!a9.hasSize()){this._boxReflow=true;
this.reflow(a9);
this._boxReflow=false;
a9=this.box;
}this.visual=bb(this.visualContext(a9));
var ba=a9;
if(this.visual){ba=aJ(this.visual.clippedBBox()||new ad.Rect());
this.visual.options.zIndex=a8.zIndex;
this.visual.options.noclip=a8.noclip;
}this.box=this.contentBox=this.paddingBox=ba;
}else{x.fn.reflow.call(this,a9);
if(a8.rotation){var Y=ae(a8.margin);
var X=this.box.unpad(Y);
this.targetBox=a9;
this.normalBox=X.clone();
X=this.rotate();
X.translate(Y.left-Y.right,Y.top-Y.bottom);
this.rotatedBox=X.clone();
X.pad(Y);
}}},createVisual:function(){var Y=this.options;
if(!Y.visible){return;
}this.visual=new L.drawing.Group({transform:this.rotationTransform(),zIndex:Y.zIndex,noclip:Y.noclip});
if(this.hasBox()){var X=W.Path.fromRect(this.paddingBox.toRect(),this.visualStyle());
this.visual.append(X);
}},renderVisual:function(){if(this.options.visual){this.addVisual();
this.createAnimation();
}else{x.fn.renderVisual.call(this);
}},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,color:X.color,font:X.font,margin:X.margin,padding:X.padding,visible:X.visible};
},visualContext:function(X){var Y=this;
return{text:Y.content,rect:X.toRect(),sender:this.getChart(),options:Y.visualOptions(),createVisual:function(){Y._boxReflow=true;
Y.reflow(X);
Y._boxReflow=false;
return Y.getDefaultVisual();
}};
},getDefaultVisual:function(){this.createVisual();
this.renderChildren();
var X=this.visual;
delete this.visual;
return X;
},rotate:function(){var X=this.options;
this.box.rotate(X.rotation);
this.align(this.targetBox,a5,X.align);
this.align(this.targetBox,a6,X.vAlign);
return this.box;
},rotationTransform:function(){var ba=this.options.rotation;
if(!ba){return null;
}var Y=this.normalBox.center();
var a8=Y.x;
var a9=Y.y;
var X=this.rotatedBox.center();
return ad.transform().translate(X.x-a8,X.y-a9).rotate(ba,[a8,a9]);
}});
var aW=A.extend({init:function(X){var Y=this;
A.fn.init.call(Y,X);
X=Y.options;
Y.append(new aV(X.text,O({},X,{vAlign:X.position})));
},options:{color:t,position:aX,align:z,margin:ae(5),padding:ae(5)},reflow:function(X){var Y=this;
A.fn.reflow.call(Y,X);
Y.box.snapTo(X,a5);
}});
aW.buildTitle=function(Y,a8,X){var a9;
if(typeof Y==="string"){Y={text:Y};
}Y=O({visible:true},X,Y);
if(Y&&Y.visible&&Y.text){a9=new aW(Y);
a8.append(a9);
}return a9;
};
var s=aV.extend({init:function(bb,ba,Y,X,a9){var a8=this;
a8.text=ba;
a8.value=bb;
a8.index=Y;
a8.dataItem=X;
aV.fn.init.call(a8,ba,a9);
},visualContext:function(Y){var X=aV.fn.visualContext.call(this,Y);
X.value=this.value;
X.dataItem=this.dataItem;
X.format=this.options.format;
X.culture=this.options.culture;
return X;
},click:function(a8,X){var Y=this;
a8.trigger(r,{element:l(X.target),value:Y.value,text:Y.text,index:Y.index,dataItem:Y.dataItem,axis:Y.parent.options});
},rotate:function(){if(this.options.alignRotation!=z){var X=this.normalBox.toRect();
var Y=this.rotationTransform();
this.box=aJ(X.bbox(Y.matrix()));
}else{aV.fn.rotate.call(this);
}return this.box;
},rotationTransform:function(){var bh=this.options;
var bk=bh.rotation;
if(!bk){return null;
}if(bh.alignRotation==z){return aV.fn.rotationTransform.call(this);
}var bl=ad.transform().rotate(bk).matrix();
var bd=this.normalBox.toRect();
var bi=this.targetBox.toRect();
var bm=bh.rotationOrigin||aX;
var X=bm==aX||bm==u?a5:a6;
var be=bm==aX||bm==u?a6:a5;
var ba=bm==aX||bm==ap?bi.origin:bi.bottomRight();
var bn=bd.topLeft().transformCopy(bl);
var bo=bd.topRight().transformCopy(bl);
var bc=bd.bottomRight().transformCopy(bl);
var bb=bd.bottomLeft().transformCopy(bl);
var bj=ad.Rect.fromPoints(bn,bo,bc,bb);
var bp={};
bp[be]=bi.origin[be]-bj.origin[be];
var bf=au.abs(bn[be]+bp[be]-ba[be]);
var bg=au.abs(bo[be]+bp[be]-ba[be]);
var a9;
var a8;
if(aP(bf,S)===aP(bg,S)){a9=bn;
a8=bo;
}else{if(bg<bf){a9=bo;
a8=bc;
}else{a9=bn;
a8=bb;
}}var Y=a9[X]+(a8[X]-a9[X])/2;
bp[X]=bi.center()[X]-Y;
return ad.transform().translate(bp.x,bp.y).rotate(bk);
}});
function I(X,a9){var ba=X.tickX,bb=X.tickY,Y=X.position;
var a8=new W.Path({stroke:{width:a9.width,color:a9.color}});
if(X.vertical){a8.moveTo(ba,Y).lineTo(ba+a9.size,Y);
}else{a8.moveTo(Y,bb).lineTo(Y,bb+a9.size);
}m(a8);
return a8;
}function H(ba,X){var a9=ba.lineStart,a8=ba.lineEnd,bb=ba.position;
var Y=new W.Path({stroke:{width:X.width,color:X.color,dashType:X.dashType}});
if(ba.vertical){Y.moveTo(a9,bb).lineTo(a8,bb);
}else{Y.moveTo(bb,a9).lineTo(bb,a8);
}m(Y);
return Y;
}var q=A.extend({init:function(Y){var X=this;
A.fn.init.call(X,Y);
if(!X.options.visible){X.options=O({},X.options,{labels:{visible:false},line:{visible:false},margin:0,majorTickSize:0,minorTickSize:0});
}X.options.minorTicks=O({},{color:X.options.line.color,width:X.options.line.width,visible:X.options.minorTickType!=az},X.options.minorTicks,{size:X.options.minorTickSize,align:X.options.minorTickType});
X.options.majorTicks=O({},{color:X.options.line.color,width:X.options.line.width,visible:X.options.majorTickType!=az},X.options.majorTicks,{size:X.options.majorTickSize,align:X.options.majorTickType});
if(!this.options._deferLabels){X.createLabels();
}X.createTitle();
X.createNotes();
},options:{labels:{visible:true,rotation:0,mirror:false,step:1,skip:0},line:{width:1,color:t,visible:true},title:{visible:true,position:z},majorTicks:{align:aG,size:4,skip:0,step:1},minorTicks:{align:aG,size:3,skip:0,step:1},axisCrossingValue:0,majorTickType:aG,minorTickType:az,majorGridLines:{skip:0,step:1},minorGridLines:{visible:false,width:1,color:t,skip:0,step:1},margin:5,visible:true,reverse:false,justified:true,notes:{label:{text:""}},_alignLines:true,_deferLabels:false},labelsRange:function(){return{min:this.options.labels.skip,max:this.labelsCount()};
},createLabels:function(){var Y=this,bb=Y.options,X=bb.vertical?aL:z,ba=O({},bb.labels,{align:X,zIndex:bb.zIndex}),be=au.max(1,ba.step);
Y.children=l.grep(Y.children,function(bf){return !(bf instanceof s);
});
Y.labels=[];
if(ba.visible){var bc=Y.labelsRange(),bd=ba.rotation,a9,a8;
if(am(bd)){ba.alignRotation=bd.align;
ba.rotation=bd.angle;
}if(ba.rotation=="auto"){ba.rotation=0;
bb.autoRotateLabels=true;
}for(a8=bc.min;
a8<bc.max;
a8+=be){a9=Y.createAxisLabel(a8,ba);
if(a9){Y.append(a9);
Y.labels.push(a9);
}}}},lineBox:function(){var X=this,bc=X.options,a9=X.box,bd=bc.vertical,bb=bc.labels.mirror,Y=bb?a9.x1:a9.x2,a8=bb?a9.y2:a9.y1,ba=bc.line.width||0;
return bd?v(Y,a9.y1,Y,a9.y2-ba):v(a9.x1,a8,a9.x2-ba,a8);
},createTitle:function(){var X=this,Y=X.options,a9=O({rotation:Y.vertical?-90:0,text:"",zIndex:1,visualSize:true},Y.title),a8;
if(a9.visible&&a9.text){a8=new aV(a9.text,a9);
X.append(a8);
X.title=a8;
}},createNotes:function(){var X=this,bc=X.options,bb=bc.notes,a9=bb.data||[],Y,a8,ba;
X.notes=[];
for(Y=0;
Y<a9.length;
Y++){a8=O({},bb,a9[Y]);
a8.value=X.parseNoteValue(a8.value);
ba=new aB(a8.value,a8.label.text,null,null,null,a8);
if(ba.options.visible){if(U(ba.options.position)){if(bc.vertical&&!ag(ba.options.position,[ap,aL])){ba.options.position=bc.reverse?ap:aL;
}else{if(!bc.vertical&&!ag(ba.options.position,[aX,u])){ba.options.position=bc.reverse?u:aX;
}}}else{if(bc.vertical){ba.options.position=bc.reverse?ap:aL;
}else{ba.options.position=bc.reverse?u:aX;
}}X.append(ba);
X.notes.push(ba);
}}},parseNoteValue:function(X){return X;
},renderVisual:function(){A.fn.renderVisual.call(this);
this.createPlotBands();
},createVisual:function(){A.fn.createVisual.call(this);
this.createBackground();
this.createLine();
},gridLinesVisual:function(){var X=this._gridLines;
if(!X){X=this._gridLines=new W.Group({zIndex:-2});
this.appendVisual(this._gridLines);
}return X;
},createTicks:function(a8){var X=this,bb=X.options,Y=X.lineBox(),ba=bb.labels.mirror,a9=bb.majorTicks.visible?bb.majorUnit:0,bd={vertical:bb.vertical};
function bc(bi,bh,bg){var bf,be=bi.length;
if(bh.visible){for(bf=bh.skip;
bf<be;
bf+=bh.step){if(U(bg)&&bf%bg===0){continue;
}bd.tickX=ba?Y.x2:Y.x2-bh.size;
bd.tickY=ba?Y.y1-bh.size:Y.y1;
bd.position=bi[bf];
a8.append(I(bd,bh));
}}}bc(X.getMajorTickPositions(),bb.majorTicks);
bc(X.getMinorTickPositions(),bb.minorTicks,a9/bb.minorUnit);
},createLine:function(){var X=this,ba=X.options,a8=ba.line,a9=X.lineBox();
if(a8.width>0&&a8.visible){var bb=new W.Path({stroke:{width:a8.width,color:a8.color,dashType:a8.dashType}});
bb.moveTo(a9.x1,a9.y1).lineTo(a9.x2,a9.y2);
if(ba._alignLines){m(bb);
}var Y=this._lineGroup=new W.Group();
Y.append(bb);
this.visual.append(Y);
this.createTicks(Y);
}},getActualTickSize:function(){var X=this,Y=X.options,a8=0;
if(Y.majorTicks.visible&&Y.minorTicks.visible){a8=au.max(Y.majorTicks.size,Y.minorTicks.size);
}else{if(Y.majorTicks.visible){a8=Y.majorTicks.size;
}else{if(Y.minorTicks.visible){a8=Y.minorTicks.size;
}}}return a8;
},createBackground:function(){var X=this,a9=X.options,Y=a9.background,a8=X.box;
if(Y){X._backgroundPath=W.Path.fromRect(a8.toRect(),{fill:{color:Y},stroke:null});
this.visual.append(X._backgroundPath);
}},createPlotBands:function(){var Y=this,ba=Y.options,bc=ba.plotBands||[],bg=ba.vertical,bb=Y.plotArea,bd,be,a8,bf;
if(bc.length===0){return;
}var a9=this._plotbandGroup=new W.Group({zIndex:-1});
var X=l.grep(Y.pane.axes,function(bh){return bh.options.vertical!==Y.options.vertical;
})[0];
l.each(bc,function(bi,bj){a8=a2(bj.from,ax);
bf=a2(bj.to,av);
if(bg){bd=(X||bb.axisX).lineBox();
be=Y.getSlot(bj.from,bj.to,true);
}else{bd=Y.getSlot(bj.from,bj.to,true);
be=(X||bb.axisY).lineBox();
}if(bd.width()!==0&&be.height()!==0){var bh=new ad.Rect([bd.x1,be.y1],[bd.width(),be.height()]);
var bk=W.Path.fromRect(bh,{fill:{color:bj.color,opacity:bj.opacity},stroke:null});
a9.append(bk);
}});
Y.appendVisual(a9);
},createGridLines:function(X){var Y=this,bg=Y.options,a8=X.options.line.visible,bd=bg.majorGridLines,bf=bd.visible?bg.majorUnit:0,bj=bg.vertical,ba=X.lineBox(),bc=ba[bj?"y1":"x1"],bb={lineStart:ba[bj?"x1":"y1"],lineEnd:ba[bj?"x2":"y2"],vertical:bj},bh,be=[];
var a9=this.gridLinesVisual();
function bi(bo,bl,bn){var bk=bo.length,bm;
if(bl.visible){for(bm=bl.skip;
bm<bk;
bm+=bl.step){bh=aP(bo[bm]);
if(!ag(bh,be)){if(bm%bn!==0&&(!a8||bc!==bh)){bb.position=bh;
a9.append(H(bb,bl));
be.push(bh);
}}}}}bi(Y.getMajorTickPositions(),bg.majorGridLines);
bi(Y.getMinorTickPositions(),bg.minorGridLines,bf/bg.minorUnit);
return a9.children;
},reflow:function(Y){var X=this,be=X.options,bk=be.vertical,bb=X.labels,a9=bb.length,bi=X.title,bg=bk?a4:af,bj=bi?bi.box[bg]():0,bh=X.getActualTickSize()+be.margin+bj,bd=0,bf=(this.getRoot()||{}).box||Y,a8=bf[bg](),bc,ba;
for(ba=0;
ba<a9;
ba++){bc=bb[ba].box[bg]();
if(bc+bh<=a8){bd=au.max(bd,bc);
}}if(bk){X.box=v(Y.x1,Y.y1,Y.x1+bd+bh,Y.y2);
}else{X.box=v(Y.x1,Y.y1,Y.x2,Y.y1+bd+bh);
}X.arrangeTitle();
X.arrangeLabels();
X.arrangeNotes();
},getLabelsTickPositions:function(){return this.getMajorTickPositions();
},labelTickIndex:function(X){return X.index;
},arrangeLabels:function(){var X=this,bm=X.options,bd=X.labels,be=!bm.justified,bp=bm.vertical,bi=X.lineBox(),bk=bm.labels.mirror,bo=X.getLabelsTickPositions(),bb=X.getActualTickSize()+bm.margin,ba,bh,a8;
for(a8=0;
a8<bd.length;
a8++){var a9=bd[a8],bn=X.labelTickIndex(a9),bf=bp?a9.box.height():a9.box.width(),bc=bo[bn]-bf/2,Y,bl,bj,bg;
if(bp){if(be){Y=bo[bn];
bl=bo[bn+1];
bj=Y+(bl-Y)/2;
bc=bj-bf/2;
}bg=bi.x2;
if(bk){bg+=bb;
a9.options.rotationOrigin=ap;
}else{bg-=bb+a9.box.width();
a9.options.rotationOrigin=aL;
}ba=a9.box.move(bg,bc);
}else{if(be){Y=bo[bn];
bl=bo[bn+1];
}else{Y=bc;
bl=bc+bf;
}bh=bi.y1;
if(bk){bh-=bb+a9.box.height();
a9.options.rotationOrigin=u;
}else{bh+=bb;
a9.options.rotationOrigin=aX;
}ba=v(Y,bh,bl,bh+a9.box.height());
}a9.reflow(ba);
}},autoRotateLabels:function(){if(this.options.autoRotateLabels&&!this.options.vertical){var ba=this.getMajorTickPositions();
var a9=this.labels;
var a8,X,bb,Y;
for(Y=0;
Y<a9.length;
Y++){bb=ba[Y+1]-ba[Y];
a8=a9[Y].box;
if(a8.width()>bb){if(a8.height()>bb){X=-90;
break;
}X=-45;
}}if(X){for(Y=0;
Y<a9.length;
Y++){a9[Y].options.rotation=X;
a9[Y].reflow(v());
}return true;
}}},arrangeTitle:function(){var X=this,a8=X.options,Y=a8.labels.mirror,ba=a8.vertical,a9=X.title;
if(a9){if(ba){a9.options.align=Y?aL:ap;
a9.options.vAlign=a9.options.position;
}else{a9.options.align=a9.options.position;
a9.options.vAlign=Y?aX:u;
}a9.reflow(X.box);
}},arrangeNotes:function(){var X=this,Y,a8,a9,ba;
for(Y=0;
Y<X.notes.length;
Y++){a8=X.notes[Y];
ba=a8.options.value;
if(U(ba)){if(X.shouldRenderNote(ba)){a8.show();
}else{a8.hide();
}a9=X.getSlot(ba);
}else{a8.hide();
}a8.reflow(a9||X.lineBox());
}},alignTo:function(a9){var X=this,Y=a9.lineBox(),ba=X.options.vertical,a8=ba?a6:a5;
X.box.snapTo(Y,a8);
if(ba){X.box.shrink(0,X.lineBox().height()-Y.height());
}else{X.box.shrink(X.lineBox().width()-Y.width(),0);
}X.box[a8+1]-=X.lineBox()[a8+1]-Y[a8+1];
X.box[a8+2]-=X.lineBox()[a8+2]-Y[a8+2];
},axisLabelText:function(ba,X,Y){var a8=ba;
if(Y.template){var a9=aT(Y.template);
a8=a9({value:ba,dataItem:X,format:Y.format,culture:Y.culture});
}else{if(Y.format){if(Y.format.match(ac)){a8=an.format(Y.format,ba);
}else{a8=an.toString(ba,Y.format,Y.culture);
}}}return a8;
},slot:function(X,a8){var Y=this.getSlot(X,a8);
if(Y){return Y.toRect();
}},contentBox:function(){var X=this.box.clone();
var Y=this.labels;
if(Y.length){if(Y[0].options.visible){X.wrap(Y[0].box);
}if(ao(Y).options.visible){X.wrap(ao(Y).box);
}}return X;
},limitRange:function(X,bc,a8,Y,a9){var ba=this.options;
if(X<a8&&a9<0&&(!U(ba.min)||ba.min<=a8)||Y<bc&&a9>0&&(!U(ba.max)||Y<=ba.max)){return;
}if(bc<a8&&a9>0||Y<X&&a9<0){return{min:X,max:bc};
}var bb=bc-X;
if(X<a8){X=a1.limitValue(X,a8,Y);
bc=a1.limitValue(X+bb,a8+bb,Y);
}else{if(bc>Y){bc=a1.limitValue(bc,a8,Y);
X=a1.limitValue(bc-bb,a8,Y-bb);
}}return{min:X,max:bc};
}});
var aB=x.extend({init:function(bc,bb,Y,X,ba,a9){var a8=this;
x.fn.init.call(a8,a9);
a8.value=bc;
a8.text=bb;
a8.dataItem=Y;
a8.category=X;
a8.series=ba;
a8.render();
},options:{icon:{visible:true,type:B},label:{position:ak,visible:true,align:z,vAlign:z},line:{visible:true},visible:true,position:aX,zIndex:2},hide:function(){this.options.visible=false;
},show:function(){this.options.visible=true;
},render:function(){var bb=this,bd=bb.options,a9=bd.label,bf=bb.text,a8=bd.icon,be=a8.size,X=v(),ba,bg,Y,bc;
if(bd.visible){if(U(a9)&&a9.visible){if(a9.template){bc=aT(a9.template);
bf=bc({dataItem:bb.dataItem,category:bb.category,value:bb.value,text:bf,series:bb.series});
}else{if(a9.format){bf=o(a9.format,bf);
}}bb.label=new aV(bf,O({},a9));
if(a9.position===ak&&!U(be)){if(a8.type===B){be=au.max(bb.label.box.width(),bb.label.box.height());
}else{bg=bb.label.box.width();
Y=bb.label.box.height();
}X.wrap(bb.label.box);
}}a8.width=bg||be||R;
a8.height=Y||be||R;
ba=new aS(O({},a8));
bb.marker=ba;
bb.append(ba);
if(bb.label){bb.append(bb.label);
}ba.reflow(v());
bb.wrapperBox=X.wrap(ba.box);
}},reflow:function(bg){var bd=this,be=bd.options,Y=bg.center(),bh=bd.wrapperBox,ba=be.line.length,bf=be.position,a9=bd.label,bc=bd.marker,bb,X,a8;
if(be.visible){if(ag(bf,[ap,aL])){if(bf===ap){a8=bh.alignTo(bg,bf).translate(-ba,bg.center().y-bh.center().y);
if(be.line.visible){bb=[bg.x1,Y.y];
bd.linePoints=[bb,[a8.x2,Y.y]];
X=a8.clone().wrapPoint(bb);
}}else{a8=bh.alignTo(bg,bf).translate(ba,bg.center().y-bh.center().y);
if(be.line.visible){bb=[bg.x2,Y.y];
bd.linePoints=[bb,[a8.x1,Y.y]];
X=a8.clone().wrapPoint(bb);
}}}else{if(bf===u){a8=bh.alignTo(bg,bf).translate(bg.center().x-bh.center().x,ba);
if(be.line.visible){bb=[Y.x,bg.y2];
bd.linePoints=[bb,[Y.x,a8.y1]];
X=a8.clone().wrapPoint(bb);
}}else{a8=bh.alignTo(bg,bf).translate(bg.center().x-bh.center().x,-ba);
if(be.line.visible){bb=[Y.x,bg.y1];
bd.linePoints=[bb,[Y.x,a8.y2]];
X=a8.clone().wrapPoint(bb);
}}}if(bc){bc.reflow(a8);
}if(a9){a9.reflow(a8);
if(bc){if(be.label.position===aG){a9.box.alignTo(bc.box,bf);
}a9.reflow(a9.box);
}}bd.contentBox=a8;
bd.targetBox=bg;
bd.box=X||a8;
}},createVisual:function(){x.fn.createVisual.call(this);
if(this.options.visible){this.createLine();
}},renderVisual:function(){var a8=this;
var Y=a8.options;
var X=Y.visual;
if(Y.visible&&X){a8.visual=X({dataItem:a8.dataItem,category:a8.category,value:a8.value,text:a8.text,sender:a8.getChart(),series:a8.series,rect:a8.targetBox.toRect(),options:{background:Y.background,border:Y.background,icon:Y.icon,label:Y.label,line:Y.line,position:Y.position,visible:Y.visible},createVisual:function(){a8.createVisual();
a8.renderChildren();
var a9=a8.visual;
delete a8.visual;
return a9;
}});
a8.addVisual();
}else{x.fn.renderVisual.call(a8);
}},createLine:function(){var X=this.options.line;
if(this.linePoints){var Y=W.Path.fromPoints(this.linePoints,{stroke:{color:X.color,width:X.width,dashType:X.dashType}});
m(Y);
this.visual.append(Y);
}},click:function(a8,Y){var X=this.eventArgs(Y);
if(!a8.trigger(aC,X)){Y.preventDefault();
}},hover:function(a8,Y){var X=this.eventArgs(Y);
if(!a8.trigger(aD,X)){Y.preventDefault();
}},leave:function(X){X._unsetActivePoint();
},eventArgs:function(X){var Y=this,a8=Y.options;
return{element:l(X.target),text:U(a8.label)?a8.label.text:"",dataItem:Y.dataItem,series:Y.series,value:Y.value,category:Y.category,visual:Y.visual};
}});
var aS=x.extend({init:function(X,Y){this.pointData=Y;
x.fn.init.call(this,X);
},options:{type:B,align:z,vAlign:z},getElement:function(){var ba=this,bb=ba.options,be=bb.type,bc=bb.rotation,X=ba.paddingBox,a8,Y=X.center(),a9=X.width()/2;
if(!bb.visible||!ba.hasBox()){return;
}var bd=ba.visualStyle();
if(be===B){a8=new W.Circle(new ad.Circle([aP(X.x1+a9,F),aP(X.y1+X.height()/2,F)],a9),bd);
}else{if(be===aY){a8=W.Path.fromPoints([[X.x1+a9,X.y1],[X.x1,X.y2],[X.x2,X.y2]],bd).close();
}else{if(be===J){a8=new W.MultiPath(bd);
a8.moveTo(X.x1,X.y1).lineTo(X.x2,X.y2);
a8.moveTo(X.x1,X.y2).lineTo(X.x2,X.y1);
}else{a8=W.Path.fromRect(X.toRect(),bd);
}}}if(bc){a8.transform(ad.transform().rotate(-bc,[Y.x,Y.y]));
}a8.options.zIndex=this.options.zIndex;
return a8;
},createElement:function(){var a8=this;
var X=a8.options.visual;
var Y=a8.pointData||{};
var a9;
if(X){a9=X({value:Y.value,dataItem:Y.dataItem,sender:a8.getChart(),series:Y.series,category:Y.category,rect:a8.paddingBox.toRect(),options:a8.visualOptions(),createVisual:function(){return a8.getElement();
}});
}else{a9=a8.getElement();
}return a9;
},visualOptions:function(){var X=this.options;
return{background:X.background,border:X.border,margin:X.margin,padding:X.padding,type:X.type,size:X.width,visible:X.visible};
},createVisual:function(){this.visual=this.createElement();
}});
var aE=q.extend({init:function(ba,a9,a8){var X=this,Y=X.initDefaults(ba,a9,a8);
q.fn.init.call(X,Y);
},startValue:function(){return 0;
},options:{type:"numeric",min:0,max:1,vertical:true,majorGridLines:{visible:true,width:1,color:t},labels:{format:"#.####################"},zIndex:1},initDefaults:function(be,bd,bc){var a9=this,bb=bc.narrowRange,Y=a9.autoAxisMin(be,bd,bb),X=a9.autoAxisMax(be,bd,bb),ba=p(Y,X),a8={majorUnit:ba},bf;
if(bc.roundToMajorUnit!==false){if(Y<0&&aK(Y,ba,1/3)){Y-=ba;
}if(X>0&&aK(X,ba,1/3)){X+=ba;
}}a8.min=ab(Y,ba);
a8.max=y(X,ba);
this.totalMin=U(bc.min)?au.min(a8.min,bc.min):a8.min;
this.totalMax=U(bc.max)?au.max(a8.max,bc.max):a8.max;
this.totalMajorUnit=ba;
if(bc){bf=U(bc.min)||U(bc.max);
if(bf){if(bc.min===bc.max){if(bc.min>0){bc.min=0;
}else{bc.max=1;
}}}if(bc.majorUnit){a8.min=ab(a8.min,bc.majorUnit);
a8.max=y(a8.max,bc.majorUnit);
}else{if(bf){bc=O(a8,bc);
a8.majorUnit=p(bc.min,bc.max);
}}}a8.minorUnit=(bc.majorUnit||a8.majorUnit)/5;
return O(a8,bc);
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},autoAxisMax:function(a9,a8,ba){var X,Y;
if(!a9&&!a8){return 1;
}if(a9<=0&&a8<=0){a8=a9==a8?0:a8;
Y=au.abs((a8-a9)/a8);
if(ba===false||!ba&&Y>a7){return 0;
}X=au.min(0,a8-(a9-a8)/2);
}else{a9=a9==a8?0:a9;
X=a8;
}return X;
},autoAxisMin:function(a9,a8,ba){var X,Y;
if(!a9&&!a8){return 0;
}if(a9>=0&&a8>=0){a9=a9==a8?0:a9;
Y=(a8-a9)/a8;
if(ba===false||!ba&&Y>a7){return 0;
}X=au.max(0,a9-(a8-a9)/2);
}else{a8=a9==a8?0:a8;
X=a9;
}return X;
},getDivisions:function(a8){if(a8===0){return 1;
}var X=this.options,Y=X.max-X.min;
return au.floor(aP(Y/a8,F))+1;
},getTickPositions:function(bm,bj){var X=this,bc=X.options,bn=bc.vertical,bg=bc.reverse,ba=X.lineBox(),bb=bn?ba.height():ba.width(),bf=bc.max-bc.min,bh=bb/bf,bl=bm*bh,bi=0,a8=X.getDivisions(bm),Y=(bn?-1:1)*(bg?-1:1),bk=Y===1?1:2,bd=ba[(bn?a6:a5)+bk],be=[],a9;
if(bj){bi=bj/bm;
}for(a9=0;
a9<a8;
a9++){if(a9%bi!==0){be.push(aP(bd,F));
}bd=bd+bl*Y;
}return be;
},getMajorTickPositions:function(){var X=this;
return X.getTickPositions(X.options.majorUnit);
},getMinorTickPositions:function(){var X=this;
return X.getTickPositions(X.options.minorUnit);
},getSlot:function(X,a8,ba){var Y=this,be=Y.options,bh=be.reverse,bl=be.vertical,bk=bl?a6:a5,bb=Y.lineBox(),bd=bb[bk+(bh?2:1)],bc=bl?bb.height():bb.width(),a9=bh?-1:1,bj=a9*(bc/(be.max-be.min)),bf,bg,bi=new v(bb.x1,bb.y1,bb.x1,bb.y1);
if(!U(X)){X=a8||0;
}if(!U(a8)){a8=X||0;
}if(ba){X=au.max(au.min(X,be.max),be.min);
a8=au.max(au.min(a8,be.max),be.min);
}if(bl){bf=be.max-au.max(X,a8);
bg=be.max-au.min(X,a8);
}else{bf=au.min(X,a8)-be.min;
bg=au.max(X,a8)-be.min;
}bi[bk+1]=au.max(au.min(bd+bj*(bh?bg:bf),G),-G);
bi[bk+2]=au.max(au.min(bd+bj*(bh?bf:bg),G),-G);
return bi;
},getValue:function(bf){var X=this,be=X.options,bg=be.reverse,bl=be.vertical,bb=be.max*1,bc=be.min*1,bj=bl?a6:a5,a8=X.lineBox(),ba=a8[bj+(bg?2:1)],a9=bl?a8.height():a8.width(),Y=bg?-1:1,bd=Y*(bf[bj]-ba),bh=(bb-bc)/a9,bk=bd*bh,bi;
if(bd<0||bd>a9){return null;
}bi=bl?bb-bk:bc+bk;
return aP(bi,S);
},translateRange:function(Y){var X=this,ba=X.options,a8=X.lineBox(),bf=ba.vertical,bc=ba.reverse,be=bf?a8.height():a8.width(),bb=ba.max-ba.min,bd=be/bb,a9=aP(Y/bd,S);
if((bf||bc)&&!(bf&&bc)){a9=-a9;
}return{min:ba.min+a9,max:ba.max+a9};
},scaleRange:function(Y){var X=this,a9=X.options,a8=-Y*a9.majorUnit;
return{min:a9.min-a8,max:a9.max+a8};
},labelsCount:function(){return this.getDivisions(this.options.majorUnit);
},createAxisLabel:function(Y,a8){var X=this,a9=X.options,bb=aP(a9.min+Y*a9.majorUnit,S),ba=X.axisLabelText(bb,null,a8);
return new s(bb,ba,Y,null,a8);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
},pan:function(X){var Y=this.translateRange(X);
return this.limitRange(Y.min,Y.max,this.totalMin,this.totalMax);
},pointsRange:function(ba,X){var bb=this.getValue(ba);
var Y=this.getValue(X);
var a9=au.min(bb,Y);
var a8=au.max(bb,Y);
return{min:a9,max:a8};
},zoomRange:function(X){var a9=this.scaleRange(X);
var bb=this.totalMax;
var bc=this.totalMin;
var a8=a1.limitValue(a9.min,bc,bb);
var Y=a1.limitValue(a9.max,bc,bb);
var ba=this.options.max-this.options.min;
if(ba<this.totalMajorUnit||Y-a8>=this.totalMajorUnit){return{min:a8,max:Y};
}}});
var at=q.extend({init:function(a8,Y,X){this.options=this._initOptions(a8,Y,X);
q.fn.init.call(this,X);
},startValue:function(){return this.options.min;
},options:{type:"log",majorUnit:10,minorUnit:1,axisCrossingValue:1,vertical:true,majorGridLines:{visible:true,width:1,color:t},zIndex:1},getSlot:function(X,a8,bb){var Y=this,bh=Y.options,bk=bh.reverse,bo=bh.vertical,bn=bo?a6:a5,bc=Y.lineBox(),be=bc[bn+(bk?2:1)],bd=bo?bc.height():bc.width(),ba=bk?-1:1,a9=bh.majorUnit,bg=Y.logMin,bf=Y.logMax,bm=ba*(bd/(bf-bg)),bi,bj,bl=new v(bc.x1,bc.y1,bc.x1,bc.y1);
if(!U(X)){X=a8||1;
}if(!U(a8)){a8=X||1;
}if(X<=0||a8<=0){return;
}if(bb){X=au.max(au.min(X,bh.max),bh.min);
a8=au.max(au.min(a8,bh.max),bh.min);
}X=ar(X,a9);
a8=ar(a8,a9);
if(bo){bi=bf-au.max(X,a8);
bj=bf-au.min(X,a8);
}else{bi=au.min(X,a8)-bg;
bj=au.max(X,a8)-bg;
}bl[bn+1]=be+bm*(bk?bj:bi);
bl[bn+2]=be+bm*(bk?bi:bj);
return bl;
},getValue:function(bg){var X=this,bf=X.options,bh=bf.reverse,bn=bf.vertical,a9=X.lineBox(),Y=bf.majorUnit,bd=X.logMin,bc=X.logMax,a8=bn===bh?1:-1,bi=a8===1?1:2,ba=bn?a9.height():a9.width(),bj=(bc-bd)/ba,bl=bn?a6:a5,bb=a9[bl+bi],be=a8*(bg[bl]-bb),bm=be*bj,bk;
if(be<0||be>ba){return null;
}bk=bd+bm;
return aP(au.pow(Y,bk),S);
},range:function(){var X=this.options;
return{min:X.min,max:X.max};
},scaleRange:function(a8){var X=this,ba=X.options,Y=ba.majorUnit,a9=-a8;
return{min:au.pow(Y,X.logMin-a9),max:au.pow(Y,X.logMax+a9)};
},translateRange:function(a8){var X=this,bb=X.options,Y=bb.majorUnit,a9=X.lineBox(),bf=bb.vertical,bc=bb.reverse,be=bf?a9.height():a9.width(),bd=be/(X.logMax-X.logMin),ba=aP(a8/bd,S);
if((bf||bc)&&!(bf&&bc)){ba=-ba;
}return{min:au.pow(Y,X.logMin+ba),max:au.pow(Y,X.logMax+ba)};
},labelsCount:function(){var X=this,a8=au.floor(X.logMax),Y=au.floor(a8-X.logMin)+1;
return Y;
},getMajorTickPositions:function(){var X=this,Y=[];
X.traverseMajorTicksPositions(function(a8){Y.push(a8);
},{step:1,skip:0});
return Y;
},createTicks:function(a8){var X=this,bf=[],bc=X.options,Y=X.lineBox(),bb=bc.labels.mirror,a9=bc.majorTicks,ba=bc.minorTicks,be={vertical:bc.vertical};
function bd(bh,bg){be.tickX=bb?Y.x2:Y.x2-bg.size;
be.tickY=bb?Y.y1-bg.size:Y.y1;
be.position=bh;
a8.append(I(be,bg));
}if(a9.visible){X.traverseMajorTicksPositions(bd,a9);
}if(ba.visible){X.traverseMinorTicksPositions(bd,ba);
}return bf;
},createGridLines:function(X){var Y=this,be=Y.options,bb=be.majorGridLines,bd=be.minorGridLines,bg=be.vertical,a9=X.lineBox(),ba={lineStart:a9[bg?"x1":"y1"],lineEnd:a9[bg?"x2":"y2"],vertical:bg},bc=[];
var a8=this.gridLinesVisual();
function bf(bi,bh){if(!ag(bi,bc)){ba.position=bi;
a8.append(H(ba,bh));
bc.push(bi);
}}if(bb.visible){Y.traverseMajorTicksPositions(bf,bb);
}if(bd.visible){Y.traverseMinorTicksPositions(bf,bd);
}return a8.children;
},traverseMajorTicksPositions:function(Y,bf){var X=this,a8=X._lineOptions(),a9=a8.lineStart,be=a8.step,bb=X.logMin,ba=X.logMax,bd,bc;
for(bd=au.ceil(bb)+bf.skip;
bd<=ba;
bd+=bf.step){bc=aP(a9+be*(bd-bb),S);
Y(bc,bf);
}},traverseMinorTicksPositions:function(a8,bn){var X=this,bj=X.options,ba=X._lineOptions(),bb=ba.lineStart,bc=ba.step,Y=bj.majorUnit,be=X.logMin,bd=X.logMax,bm=au.floor(be),bf=bj.max,bg=bj.min,bi=bj.minorUnit,bl,bo,bk,bh;
for(bl=bm;
bl<bd;
bl++){bh=X._minorIntervalOptions(bl);
for(var a9=bn.skip;
a9<bi;
a9+=bn.step){bo=bh.value+a9*bh.minorStep;
if(bo>bf){break;
}if(bo>=bg){bk=aP(bb+bc*(ar(bo,Y)-be),S);
a8(bk,bn);
}}}},createAxisLabel:function(Y,a8){var X=this,a9=X.options,ba=au.ceil(X.logMin+Y),bc=Math.pow(a9.majorUnit,ba),bb=X.axisLabelText(bc,null,a8);
return new s(bc,bb,Y,null,a8);
},shouldRenderNote:function(Y){var X=this.range();
return X.min<=Y&&Y<=X.max;
},_throwNegativeValuesError:function(){throw new Error("Non positive values cannot be used for a logarithmic axis");
},_initOptions:function(bf,be,bd){var a8=this,a9=O({},a8.options,{min:bf,max:be},bd),bc=a9.min,bb=a9.max,ba=a9.majorUnit,X=this._autoMax(be,ba),Y=this._autoMin(bf,be,a9);
if(a9.axisCrossingValue<=0){a8._throwNegativeValuesError();
}if(!U(bd.max)){bb=X;
}else{if(bd.max<=0){a8._throwNegativeValuesError();
}}if(!U(bd.min)){bc=Y;
}else{if(bd.min<=0){a8._throwNegativeValuesError();
}}this.totalMin=U(bd.min)?au.min(Y,bd.min):Y;
this.totalMax=U(bd.max)?au.max(X,bd.max):X;
a8.logMin=aP(ar(bc,ba),S);
a8.logMax=aP(ar(bb,ba),S);
a9.max=bb;
a9.min=bc;
a9.minorUnit=bd.minorUnit||aP(ba-1,S);
return a9;
},_autoMin:function(a9,a8,ba){var X=a9;
var Y=ba.majorUnit;
if(a9<=0){X=a8<=1?au.pow(Y,-2):1;
}else{if(!ba.narrowRange){X=au.pow(Y,au.floor(ar(a9,Y)));
}}return X;
},_autoMax:function(a9,Y){var a8=aP(ar(a9,Y),S)%1;
var X;
if(a9<=0){X=Y;
}else{if(a8!==0&&(a8<0.3||a8>0.9)){X=au.pow(Y,ar(a9,Y)+0.2);
}else{X=au.pow(Y,au.ceil(ar(a9,Y)));
}}return X;
},pan:function(X){var Y=this.translateRange(X);
return this.limitRange(Y.min,Y.max,this.totalMin,this.totalMax,-X);
},pointsRange:function(ba,X){var bb=this.getValue(ba);
var Y=this.getValue(X);
var a9=au.min(bb,Y);
var a8=au.max(bb,Y);
return{min:a9,max:a8};
},zoomRange:function(a9){var bd=this.options;
var bc=this.scaleRange(a9);
var be=this.totalMax;
var bf=this.totalMin;
var bb=a1.limitValue(bc.min,bf,be);
var ba=a1.limitValue(bc.max,bf,be);
var a8=bd.majorUnit;
var Y=ba>bb&&bd.min&&bd.max&&aP(ar(bd.max,a8)-ar(bd.min,a8),S)<1;
var X=!(bd.min===bf&&bd.max===be)&&aP(ar(ba,a8)-ar(bb,a8),S)>=1;
if(Y||X){return{min:bb,max:ba};
}},_minorIntervalOptions:function(ba){var X=this.options.majorUnit,bb=au.pow(X,ba),a9=au.pow(X,ba+1),Y=a9-bb,a8=Y/this.options.minorUnit;
return{value:bb,minorStep:a8};
},_lineOptions:function(){var X=this,bb=X.options,bc=bb.reverse,bg=bb.vertical,bf=bg?a6:a5,a8=X.lineBox(),Y=bg===bc?1:-1,bd=Y===1?1:2,a9=bg?a8.height():a8.width(),be=Y*(a9/(X.logMax-X.logMin)),ba=a8[bf+bd];
return{step:be,lineStart:ba,lineBox:a8};
}});
L.Gradients={glass:{type:aq,rotation:0,stops:[{offset:0,color:a3,opacity:0},{offset:0.25,color:a3,opacity:0.3},{offset:1,color:a3,opacity:0}]},sharpBevel:{type:aI,stops:[{offset:0,color:a3,opacity:0.55},{offset:0.65,color:a3,opacity:0},{offset:0.95,color:a3,opacity:0.25}]},roundedBevel:{type:aI,stops:[{offset:0.33,color:a3,opacity:0.06},{offset:0.83,color:a3,opacity:0.2},{offset:0.95,color:a3,opacity:0}]},roundedGlass:{type:aI,supportVML:false,stops:[{offset:0,color:a3,opacity:0},{offset:0.5,color:a3,opacity:0.3},{offset:0.99,color:a3,opacity:0}]},sharpGlass:{type:aI,supportVML:false,stops:[{offset:0,color:a3,opacity:0.2},{offset:0.15,color:a3,opacity:0.15},{offset:0.17,color:a3,opacity:0.35},{offset:0.85,color:a3,opacity:0.05},{offset:0.87,color:a3,opacity:0.15},{offset:0.99,color:a3,opacity:0}]}};
var Z={extend:function(X,Y){if(!X.exportVisual){throw new Error("Mixin target has no exportVisual method defined.");
}X.exportSVG=this.exportSVG;
X.exportImage=this.exportImage;
X.exportPDF=this.exportPDF;
if(!Y){X.svg=this.svg;
X.imageDataURL=this.imageDataURL;
}},exportSVG:function(X){return W.exportSVG(this.exportVisual(),X);
},exportImage:function(X){return W.exportImage(this.exportVisual(X),X);
},exportPDF:function(X){return W.exportPDF(this.exportVisual(),X);
},svg:function(){if(W.svg.Surface){return W.svg._exportGroup(this.exportVisual());
}else{throw new Error("SVG Export failed. Unable to export instantiate kendo.drawing.svg.Surface");
}},imageDataURL:function(){if(!an.support.canvas){return null;
}if(W.canvas.Surface){var X=l("<div />").css({display:"none",width:this.element.width(),height:this.element.height()}).appendTo(document.body);
var a8=new W.canvas.Surface(X);
a8.draw(this.exportVisual());
var Y=a8._rootElement.toDataURL();
a8.destroy();
X.remove();
return Y;
}else{throw new Error("Image Export failed. Unable to export instantiate kendo.drawing.canvas.Surface");
}}};
function p(a8,Y){var X=aP(Y-a8,S-1);
if(X===0){if(Y===0){return 0.1;
}X=au.abs(Y);
}var ba=au.pow(10,au.floor(au.log(X)/au.log(10))),a9=aP(X/ba,S),bb=1;
if(a9<1.904762){bb=0.2;
}else{if(a9<4.761904){bb=0.5;
}else{if(a9<9.523809){bb=1;
}else{bb=2;
}}}return aP(ba*bb,S);
}function aO(ba,bb,Y,a8,X){var a9=X*V;
return new aH(Y+(ba-Y)*au.cos(a9)+(bb-a8)*au.sin(a9),a8-(ba-Y)*au.sin(a9)+(bb-a8)*au.cos(a9));
}function w(be,bg){if(be.x1==bg.x1&&be.y1==bg.y1&&be.x2==bg.x2&&be.y2==bg.y2){return bg;
}var X=au.min(be.x1,bg.x1),Y=au.max(be.x1,bg.x1),a8=au.min(be.x2,bg.x2),a9=au.max(be.x2,bg.x2),ba=au.min(be.y1,bg.y1),bb=au.max(be.y1,bg.y1),bc=au.min(be.y2,bg.y2),bd=au.max(be.y2,bg.y2),bf=[];
bf[0]=v(Y,ba,a8,bb);
bf[1]=v(X,bb,Y,bc);
bf[2]=v(a8,bb,a9,bc);
bf[3]=v(Y,bc,a8,bd);
if(be.x1==X&&be.y1==ba||bg.x1==X&&bg.y1==ba){bf[4]=v(X,ba,Y,bb);
bf[5]=v(a8,bc,a9,bd);
}else{bf[4]=v(a8,ba,a9,bb);
bf[5]=v(X,bc,Y,bd);
}return l.grep(bf,function(bh){return bh.height()>0&&bh.width()>0;
})[0];
}function ag(Y,X){return ah(Y,X)!=-1;
}function y(Y,X){return aP(au.ceil(Y/X)*X,S);
}function ab(Y,X){return aP(au.floor(Y/X)*X,S);
}function aP(a8,Y){var X=au.pow(10,Y||0);
return au.round(a8*X)/X;
}function ar(Y,X){return au.log(Y)/au.log(X);
}function aK(ba,X,Y){var a8=aP(au.abs(ba%X),S),a9=X*(1-Y);
return a8===0||a8>a9;
}function al(a8,X,Y){return aP(a8+(X-a8)*Y,F);
}function aF(X,Y){return X-Y;
}function o(X,Y){if(X.match(ac)){return an.format.apply(this,arguments);
}return an.toString(Y,X);
}function E(X,Y){return -X.x*Y.y+X.y*Y.x<0;
}function M(X,Y){if(X&&Y){return X.getTime()-Y.getTime();
}return -1;
}var K=function(X){this.closed=X;
};
K.prototype=K.fn={WEIGHT:0.333,EXTREMUM_ALLOWED_DEVIATION:0.01,process:function(ba){var bl=this,X=bl.closed,bi=ba.slice(0),be=bi.length,bj=[],bf,bg,bh,Y,bc,bd,bk;
if(be>2){bl.removeDuplicates(0,bi);
be=bi.length;
}if(be<2||be==2&&bi[0].equals(bi[1])){return bj;
}bf=bi[0];
bg=bi[1];
bh=bi[2];
bj.push(new W.Segment(bf));
while(bf.equals(bi[be-1])){X=true;
bi.pop();
be--;
}if(be==2){bk=bl.tangent(bf,bg,a5,a6);
ao(bj).controlOut(bl.firstControlPoint(bk,bf,bg,a5,a6));
bj.push(new W.Segment(bg,bl.secondControlPoint(bk,bf,bg,a5,a6)));
return bj;
}if(X){bf=bi[be-1];
bg=bi[0];
bh=bi[1];
Y=bl.controlPoints(bf,bg,bh);
bc=Y[1];
bd=Y[0];
}else{bk=bl.tangent(bf,bg,a5,a6);
bc=bl.firstControlPoint(bk,bf,bg,a5,a6);
}var a8=bc;
for(var bb=0;
bb<=be-3;
bb++){bl.removeDuplicates(bb,bi);
be=bi.length;
if(bb+3<=be){bf=bi[bb];
bg=bi[bb+1];
bh=bi[bb+2];
Y=bl.controlPoints(bf,bg,bh);
ao(bj).controlOut(a8);
a8=Y[1];
var a9=Y[0];
bj.push(new W.Segment(bg,a9));
}}if(X){bf=bi[be-2];
bg=bi[be-1];
bh=bi[0];
Y=bl.controlPoints(bf,bg,bh);
ao(bj).controlOut(a8);
bj.push(new W.Segment(bg,Y[0]));
ao(bj).controlOut(Y[1]);
bj.push(new W.Segment(bh,bd));
}else{bk=bl.tangent(bg,bh,a5,a6);
ao(bj).controlOut(a8);
bj.push(new W.Segment(bh,bl.secondControlPoint(bk,bg,bh,a5,a6)));
}return bj;
},removeDuplicates:function(X,Y){while(Y[X].equals(Y[X+1])||Y[X+1].equals(Y[X+2])){Y.splice(X+1,1);
}},invertAxis:function(a8,a9,ba){var bb=this,X,bc,Y=false;
if(a8.x===a9.x){Y=true;
}else{if(a9.x===ba.x){if(a9.y<ba.y&&a8.y<=a9.y||ba.y<a9.y&&a9.y<=a8.y){Y=true;
}}else{X=bb.lineFunction(a8,a9);
bc=bb.calculateFunction(X,ba.x);
if(!(a8.y<=a9.y&&ba.y<=bc)&&!(a9.y<=a8.y&&ba.y>=bc)){Y=true;
}}}return Y;
},isLine:function(Y,a8,a9){var ba=this,X=ba.lineFunction(Y,a8),bb=ba.calculateFunction(X,a9.x);
return Y.x==a8.x&&a8.x==a9.x||aP(bb,1)===aP(a9.y,1);
},lineFunction:function(a8,a9){var X=(a9.y-a8.y)/(a9.x-a8.x),Y=a8.y-X*a8.x;
return[Y,X];
},controlPoints:function(ba,bb,bc){var bi=this,bj=a5,bk=a6,bd=false,bg=false,bh,a8,Y,be,X=bi.EXTREMUM_ALLOWED_DEVIATION;
if(bi.isLine(ba,bb,bc)){bh=bi.tangent(ba,bb,a5,a6);
}else{a8={x:bi.isMonotonicByField(ba,bb,bc,a5),y:bi.isMonotonicByField(ba,bb,bc,a6)};
if(a8.x&&a8.y){bh=bi.tangent(ba,bc,a5,a6);
bd=true;
}else{if(bi.invertAxis(ba,bb,bc)){bj=a6;
bk=a5;
}if(a8[bj]){bh=0;
}else{var bf;
if(bc[bk]<ba[bk]&&ba[bk]<=bb[bk]||ba[bk]<bc[bk]&&bb[bk]<=ba[bk]){bf=bi.sign((bc[bk]-ba[bk])*(bb[bj]-ba[bj]));
}else{bf=-bi.sign((bc[bj]-ba[bj])*(bb[bk]-ba[bk]));
}bh=X*bf;
bg=true;
}}}be=bi.secondControlPoint(bh,ba,bb,bj,bk);
if(bg){var a9=bj;
bj=bk;
bk=a9;
}Y=bi.firstControlPoint(bh,bb,bc,bj,bk);
if(bd){bi.restrictControlPoint(ba,bb,be,bh);
bi.restrictControlPoint(bb,bc,Y,bh);
}return[be,Y];
},sign:function(X){return X<=0?-1:1;
},restrictControlPoint:function(Y,a8,X,a9){if(Y.y<a8.y){if(a8.y<X.y){X.x=Y.x+(a8.y-Y.y)/a9;
X.y=a8.y;
}else{if(X.y<Y.y){X.x=a8.x-(a8.y-Y.y)/a9;
X.y=Y.y;
}}}else{if(X.y<a8.y){X.x=Y.x-(Y.y-a8.y)/a9;
X.y=a8.y;
}else{if(Y.y<X.y){X.x=a8.x+(Y.y-a8.y)/a9;
X.y=Y.y;
}}}},tangent:function(X,Y,ba,bc){var a8,a9=Y[ba]-X[ba],bb=Y[bc]-X[bc];
if(a9===0){a8=0;
}else{a8=bb/a9;
}return a8;
},isMonotonicByField:function(Y,a8,a9,X){return a9[X]>a8[X]&&a8[X]>Y[X]||a9[X]<a8[X]&&a8[X]<Y[X];
},firstControlPoint:function(bb,Y,a8,bd,be){var bc=this,a9=Y[bd],ba=a8[bd],X=(ba-a9)*bc.WEIGHT;
return bc.point(a9+X,Y[be]+X*bb,bd,be);
},secondControlPoint:function(bb,Y,a8,bd,be){var bc=this,a9=Y[bd],ba=a8[bd],X=(ba-a9)*bc.WEIGHT;
return bc.point(ba-X,a8[be]-X*bb,bd,be);
},point:function(a8,ba,Y,a9){var X=new ad.Point();
X[Y]=a8;
X[a9]=ba;
return X;
},calculateFunction:function(X,ba){var a9=0,a8=X.length;
for(var Y=0;
Y<a8;
Y++){a9+=Math.pow(ba,Y)*X[Y];
}return a9;
}};
function ay(Y){var a8=Y.originalEvent,X=0;
if(a8.wheelDelta){X=-a8.wheelDelta/120;
X=X>0?au.ceil(X):au.floor(X);
}if(a8.detail){X=aP(a8.detail/3);
}return X;
}function N(Y){if(!Y||!Y.indexOf||Y.indexOf("&")<0){return Y;
}else{var X=N._element;
X.innerHTML=Y;
return X.textContent||X.innerText;
}}function m(a8){if(!an.support.vml){var Y=0.5;
if(a8.options.stroke&&U(a8.options.stroke.width)){if(a8.options.stroke.width%2===0){Y=0;
}}for(var X=0;
X<a8.segments.length;
X++){a8.segments[X].anchor().round(0).translate(Y,Y);
}}return a8;
}function aj(ba){var bb=ba.stops,bc=ba.innerRadius/ba.radius*100,a8,a9=bb.length,X,Y=[];
for(a8=0;
a8<a9;
a8++){X=O({},bb[a8]);
X.offset=(X.offset*(100-bc)+bc)/100;
Y.push(X);
}return Y;
}function aJ(a8){var Y=a8.origin;
var X=a8.bottomRight();
return new v(Y.x,Y.y,X.x,X.y);
}N._element=document.createElement("span");
O(an.dataviz,{AXIS_LABEL_CLICK:r,COORD_PRECISION:F,DEFAULT_PRECISION:S,DEFAULT_WIDTH:T,DEFAULT_HEIGHT:Q,DEFAULT_FONT:P,INITIAL_ANIMATION_DURATION:ai,NOTE_CLICK:aC,NOTE_HOVER:aD,CLIP:D,Axis:q,AxisLabel:s,Box2D:v,BoxElement:x,ChartElement:A,CurveProcessor:K,ExportMixin:Z,FloatElement:aa,LogarithmicAxis:at,Note:aB,NumericAxis:aE,Point2D:aH,Ring:aM,RootElement:aN,Sector:aQ,ShapeBuilder:aR,ShapeElement:aS,Text:aU,TextBox:aV,Title:aW,alignPathToPixel:m,autoFormat:o,autoMajorUnit:p,boxDiff:w,dateComparer:M,decodeEntities:N,getSpacing:ae,inArray:ag,interpolateValue:al,mwDelta:ay,rectToBox:aJ,rotatePoint:aO,round:aP,ceil:y,floor:ab});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
