(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.gantt.timeline",["kendo.dom","kendo.touch","kendo.draganddrop"],l);
}(function(){var k={id:"gantt.timeline",name:"Gantt Timeline",category:"web",description:"The Gantt Timeline",depends:["dom","touch","draganddrop"],hidden:true};
(function(l){var W=kendo.ui.Widget;
var z=kendo.dom.element;
var B=kendo.dom.text;
var A=kendo.dom.html;
var x=l.isPlainObject;
var t=l.extend;
var K=l.proxy;
var n=kendo.support.browser;
var y=false;
var D=kendo.keys;
var L=kendo.data.Query;
var P="string";
var I=".kendoGanttTimeline";
var o="click";
var q="dblclick";
var H="mousemove";
var F="mouseenter";
var G="mouseleave";
var C="keydown";
var s=".";
var R=kendo.template("#=kendo.toString(start, 't')#");
var p=kendo.template("#=kendo.toString(start, 'ddd M/dd')#");
var V=kendo.template("#=kendo.toString(start, 'ddd M/dd')# - #=kendo.toString(kendo.date.addDays(end, -1), 'ddd M/dd')#");
var E=kendo.template("#=kendo.toString(start, 'MMM')#");
var X=kendo.template("#=kendo.toString(start, 'yyyy')#");
var M=kendo.template('<div class="#=styles.marquee#"><div class="#=styles.marqueeColor#"></div></div>');
var N=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#"><div class="#=styles.tooltipContent#"><div>#=messages.start#: #=kendo.toString(start, format)#</div><div>#=messages.end#: #=kendo.toString(end, format)#</div></div></div>');
var J=kendo.template('<div style="z-index: 100002;" class="#=styles.tooltipWrapper#" ><div class="#=styles.tooltipContent#">#=text#%</div><div class="#=styles.tooltipCallout#" style="left:13px;"></div></div>');
var Q=kendo.template('<div class="#=styles.taskDetails#"><strong>#=task.title#</strong><div class="#=styles.taskDetailsPercent#">#=kendo.toString(task.percentComplete, "p0")#</div><ul class="#=styles.reset#"><li>#=messages.start#: #=kendo.toString(task.start, "h:mm tt ddd, MMM d")#</li><li>#=messages.end#: #=kendo.toString(task.end, "h:mm tt ddd, MMM d")#</li></ul></div>');
var O="<table style='visibility: hidden;'><tbody><tr style='height:{0}'><td>&nbsp;</td></tr></tbody></table>";
var r={day:{type:"kendo.ui.GanttDayView"},week:{type:"kendo.ui.GanttWeekView"},month:{type:"kendo.ui.GanttMonthView"},year:{type:"kendo.ui.GanttYearView"}};
function T(Y){delete Y.name;
delete Y.prefix;
delete Y.views;
return Y;
}function w(Z){var aa=[];
var Y=Z.workWeekStart;
aa.push(Y);
while(Z.workWeekEnd!=Y){if(Y>6){Y-=7;
}else{Y++;
}aa.push(Y);
}return aa;
}function m(){var Y=kendo._activeElement();
if(Y&&Y.nodeName.toLowerCase()!=="body"){l(Y).blur();
}}var U={alt:"k-alt",reset:"k-reset",nonWorking:"k-nonwork-hour",header:"k-header",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",tasksWrapper:"k-gantt-tables",rowsTable:"k-gantt-rows",columnsTable:"k-gantt-columns",tasksTable:"k-gantt-tasks",dependenciesWrapper:"k-gantt-dependencies",resource:"k-resource",resourceAlt:"k-resource k-alt",task:"k-task",taskSingle:"k-task-single",taskMilestone:"k-task-milestone",taskSummary:"k-task-summary",taskWrap:"k-task-wrap",taskMilestoneWrap:"k-milestone-wrap",resourcesWrap:"k-resources-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",taskDragHandle:"k-task-draghandle",taskContent:"k-task-content",taskTemplate:"k-task-template",taskActions:"k-task-actions",taskDelete:"k-task-delete",taskComplete:"k-task-complete",taskDetails:"k-task-details",taskDetailsPercent:"k-task-pct",link:"k-link",icon:"k-icon",iconDelete:"k-si-close",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskResizeHandleEast:"k-resize-e",taskSummaryProgress:"k-task-summary-progress",taskSummaryComplete:"k-task-summary-complete",line:"k-line",lineHorizontal:"k-line-h",lineVertical:"k-line-v",arrowWest:"k-arrow-w",arrowEast:"k-arrow-e",dragHint:"k-drag-hint",dependencyHint:"k-dependency-hint",tooltipWrapper:"k-widget k-tooltip k-popup k-group k-reset",tooltipContent:"k-tooltip-content",tooltipCallout:"k-callout k-callout-s",callout:"k-callout",marquee:"k-marquee k-gantt-marquee",marqueeColor:"k-marquee-color"};
var v=kendo.ui.GanttView=W.extend({init:function(Y,Z){W.fn.init.call(this,Y,Z);
this.title=this.options.title||this.options.name;
this.header=this.element.find(s+v.styles.gridHeader);
this.content=this.element.find(s+v.styles.gridContent);
this.contentWidth=this.content.width();
this._workDays=w(this.options);
this._headerTree=Z.headerTree;
this._taskTree=Z.taskTree;
this._taskTemplate=Z.taskTemplate?kendo.template(Z.taskTemplate,t({},kendo.Template,Z.templateSettings)):null;
this._dependencyTree=Z.dependencyTree;
this._taskCoordinates={};
this._currentTime();
},destroy:function(){W.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
this.headerRow=null;
this.header=null;
this.content=null;
this._dragHint=null;
this._resizeHint=null;
this._resizeTooltip=null;
this._taskTooltip=null;
this._percentCompleteResizeTooltip=null;
this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
},options:{showWorkHours:false,showWorkDays:false,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,slotSize:100,currentTimeMarker:{updateInterval:10000}},renderLayout:function(){this._slots=this._createSlots();
this._tableWidth=this._calculateTableWidth();
this.createLayout(this._layout());
this._slotDimensions();
this._adjustHeight();
this.content.find(s+v.styles.dependenciesWrapper).width(this._tableWidth);
},_adjustHeight:function(){this.content.height(this.element.height()-this.header.outerHeight());
},createLayout:function(ab){var aa=this._headers(ab);
var Y=this._colgroup();
var ad=this._headerTree;
var Z=z("thead",null,aa);
var ac=z("table",{style:{width:this._tableWidth+"px"}},[Y,Z]);
ad.render([ac]);
this.headerRow=this.header.find("table:first tr").last();
},_slotDimensions:function(){var Z=this.headerRow[0].children;
var ad=this._timeSlots();
var ac;
var Y;
for(var aa=0,ab=Z.length;
aa<ab;
aa++){Y=Z[aa];
ac=ad[aa];
ac.offsetLeft=Y.offsetLeft;
ac.offsetWidth=Y.offsetWidth;
}},render:function(af){var ae=af.length;
var ad=v.styles;
var aa;
var ac=this._rowsTable(ae);
var Z=this._columnsTable(ae);
var ag=this._tasksTable(af);
var ab=this.options.currentTimeMarker;
var Y=this.options.calculatedSize;
var ah;
this._taskTree.render([ac,Z,ag]);
aa=this.content.find(s+ad.rowsTable);
if(Y){ah=Y.row*af.length;
this.content.find(s+ad.tasksTable).height(ah);
aa.height(ah);
}this._contentHeight=aa.height();
this._rowHeight=Y?Y.row:this._contentHeight/aa.find("tr").length;
this.content.find(s+ad.columnsTable).height(this._contentHeight);
if(ab!==false&&ab.updateInterval!==j){this._renderCurrentTime();
}},_rowsTable:function(ab){var ac=[];
var aa;
var ad=v.styles;
var Y=[null,{className:ad.alt}];
for(var Z=0;
Z<ab;
Z++){aa=z("tr",Y[Z%2],[z("td",null,[B("\xA0")])]);
ac.push(aa);
}return this._createTable(1,ac,{className:ad.rowsTable});
},_columnsTable:function(){var Z=[];
var ab;
var ag=v.styles;
var ad=this._timeSlots();
var ae=ad.length;
var ac;
var af;
var ah=0;
var Y;
for(var aa=0;
aa<ae;
aa++){ac=ad[aa];
Y={};
af=ac.span;
ah+=af;
if(af!==1){Y.colspan=af;
}if(ac.isNonWorking){Y.className=ag.nonWorking;
}Z.push(z("td",Y,[B("\xA0")]));
}ab=z("tr",null,Z);
return this._createTable(ah,[ab],{className:ag.columnsTable});
},_tasksTable:function(ar){var am=[];
var al;
var aa;
var ag;
var ap;
var ao=v.styles;
var ac=this._taskCoordinates={};
var an=this._calculateMilestoneWidth();
var af=Math.round(an.width);
var ah=this.options.resourcesField;
var ab=[ao.resource,ao.resourceAlt];
var Z=this.options.calculatedSize;
var aj;
var ai=this._calculateResourcesMargin();
var aq=this._calculateTaskBorderWidth();
var ak;
var Y=function(at){var au;
var av;
au=ag.left;
av=au+ag.width;
if(ap.isMilestone()){au-=af/2;
av=au+af;
}ac[ap.id]={start:au,end:av,rowIndex:at};
};
for(var ad=0,ae=ar.length;
ad<ae;
ad++){ap=ar[ad];
ag=this._taskPosition(ap);
ag.borderWidth=aq;
al=z("tr",null);
aa=z("td",null,[this._renderTask(ar[ad],ag)]);
if(ap[ah]&&ap[ah].length){if(y){aj=this._tableWidth-ag.left;
}else{aj=Math.max(ag.width||an.clientWidth,0)+ag.left;
}ak={width:this._tableWidth-(aj+ai)+"px"};
ak[y?"right":"left"]=aj+"px";
if(Z){ak.height=Z.cell+"px";
}aa.children.push(z("div",{className:ao.resourcesWrap,style:ak},this._renderResources(ap[ah],ab[ad%2])));
}al.children.push(aa);
am.push(al);
Y(ad);
}return this._createTable(1,am,{className:v.styles.tasksTable});
},_createTable:function(aa,ac,ad){var Z=[];
var Y;
var ae;
for(var ab=0;
ab<aa;
ab++){Z.push(z("col"));
}Y=z("colgroup",null,Z);
ae=z("tbody",null,ac);
if(!ad.style){ad.style={};
}ad.style.width=this._tableWidth+"px";
return z("table",ad,[Y,ae]);
},_calculateTableWidth:function(){var ac=this._timeSlots();
var ab=0;
var ae=0;
var Y;
var ad;
for(var Z=0,aa=ac.length;
Z<aa;
Z++){Y=ac[Z].span;
ae+=Y;
if(Y>ab){ab=Y;
}}ad=Math.round(ae*this.options.slotSize/ab);
return ad;
},_calculateMilestoneWidth:function(){var ab;
var Z=v.styles.task+" "+v.styles.taskMilestone;
var aa=l("<div class='"+Z+"' style='visibility: hidden; position: absolute'>");
var Y;
this.content.append(aa);
Y=aa[0].getBoundingClientRect();
ab={width:Y.right-Y.left,clientWidth:aa[0].clientWidth};
aa.remove();
return ab;
},_calculateResourcesMargin:function(){var Y;
var Z=l("<div class='"+v.styles.resourcesWrap+"' style='visibility: hidden; position: absolute'>");
this.content.append(Z);
Y=parseInt(Z.css(y?"margin-right":"margin-left"),10);
Z.remove();
return Y;
},_calculateTaskBorderWidth:function(){var ab;
var Y=v.styles.task+" "+v.styles.taskSingle;
var aa=l("<div class='"+Y+"' style='visibility: hidden; position: absolute'>");
var Z;
this.content.append(aa);
Z=kendo.getComputedStyles(aa[0],["border-left-width"]);
ab=parseFloat(Z["border-left-width"],10);
aa.remove();
return ab;
},_renderTask:function(ae,ab){var ai;
var af;
var aa=this.options.editable;
var ac;
var ag=ab.left;
var ad=v.styles;
var aj=ad.taskWrap;
var Y=this.options.calculatedSize;
var Z={};
var ah={className:aj,style:{left:ag+"px"}};
if(Y){ah.style.height=Y.cell+"px";
}if(ae.summary){af=this._renderSummary(ae,ab);
}else{if(ae.isMilestone()){af=this._renderMilestone(ae,ab);
ah.className+=" "+ad.taskMilestoneWrap;
}else{af=this._renderSingleTask(ae,ab);
}}ai=z("div",ah,[af]);
if(aa){ai.children.push(z("div",{className:ad.taskDot+" "+ad.taskDotStart}));
ai.children.push(z("div",{className:ad.taskDot+" "+ad.taskDotEnd}));
}if(!ae.summary&&!ae.isMilestone()&&aa&&this._taskTemplate===null){ac=Math.round(ab.width*ae.percentComplete);
Z[y?"right":"left"]=ac+"px";
ai.children.push(z("div",{className:ad.taskDragHandle,style:Z}));
}return ai;
},_renderSingleTask:function(ad,aa){var ac=v.styles;
var ab=Math.round(aa.width*ad.percentComplete);
var ae=[];
var af;
if(this._taskTemplate!==null){af=A(this._taskTemplate(ad));
}else{af=B(ad.title);
ae.push(z("div",{className:ac.taskComplete,style:{width:ab+"px"}}));
}var Y=z("div",{className:ac.taskContent},[z("div",{className:ac.taskTemplate},[af])]);
ae.push(Y);
if(this.options.editable){Y.children.push(z("span",{className:ac.taskActions},[z("a",{className:ac.link+" "+ac.taskDelete,href:"#"},[z("span",{className:ac.icon+" "+ac.iconDelete})])]));
Y.children.push(z("span",{className:ac.taskResizeHandle+" "+ac.taskResizeHandleWest}));
Y.children.push(z("span",{className:ac.taskResizeHandle+" "+ac.taskResizeHandleEast}));
}var Z=z("div",{className:ac.task+" "+ac.taskSingle,"data-uid":ad.uid,style:{width:Math.max(aa.width-aa.borderWidth*2,0)+"px"}},ae);
return Z;
},_renderMilestone:function(aa){var Z=v.styles;
var Y=z("div",{className:Z.task+" "+Z.taskMilestone,"data-uid":aa.uid});
return Y;
},_renderSummary:function(ac,Z){var ab=v.styles;
var aa=Math.round(Z.width*ac.percentComplete);
var Y=z("div",{className:ab.task+" "+ab.taskSummary,"data-uid":ac.uid,style:{width:Z.width+"px"}},[z("div",{className:ab.taskSummaryProgress,style:{width:aa+"px"}},[z("div",{className:ab.taskSummaryComplete,style:{width:Z.width+"px"}})])]);
return Y;
},_renderResources:function(ad,Z){var Y=[];
var ac;
for(var aa=0,ab=ad.length;
aa<ab;
aa++){ac=ad[aa];
Y.push(z("span",{className:Z,style:{color:ac.get("color")}},[B(ac.get("name"))]));
}if(y){Y.reverse();
}return Y;
},_taskPosition:function(ab){var Z=Math.round;
var aa=Z(this._offset(y?ab.end:ab.start));
var Y=Z(this._offset(y?ab.start:ab.end));
return{left:aa,width:Y-aa};
},_offset:function(Y){var ac=this._timeSlots();
var Z;
var ae;
var aa;
var ab=0;
var ad;
if(!ac.length){return 0;
}ad=this._slotIndex("start",Y);
Z=ac[ad];
if(Z.end<Y){ab=Z.offsetWidth;
}else{if(Z.start<=Y){ae=Y-Z.start;
aa=Z.end-Z.start;
ab=ae/aa*Z.offsetWidth;
}}if(y){ab=Z.offsetWidth+1-ab;
}return Z.offsetLeft+ab;
},_slotIndex:function(Z,ae,ab){var ac=this._timeSlots();
var ad=0;
var Y=ac.length-1;
var aa;
if(ab){ac=[].slice.call(ac).reverse();
}do{aa=Math.ceil((Y+ad)/2);
if(ac[aa][Z]<ae){ad=aa;
}else{if(aa===Y){aa--;
}Y=aa;
}}while(ad!==Y);
if(ab){ad=ac.length-1-ad;
}return ad;
},_timeByPosition:function(ae,ac,ad){var aa=this._slotByPosition(ae);
if(ac){return ad?aa.end:aa.start;
}var Z=ae-l(s+v.styles.tasksTable).offset().left;
var Y=aa.end-aa.start;
var ab=Z-aa.offsetLeft;
if(y){ab=aa.offsetWidth-ab;
}return new Date(aa.start.getTime()+Y*(ab/aa.offsetWidth));
},_slotByPosition:function(aa){var Y=aa-l(s+v.styles.tasksTable).offset().left;
var Z=this._slotIndex("offsetLeft",Y,y);
return this._timeSlots()[Z];
},_renderDependencies:function(Y){var Z=[];
var ac=this._dependencyTree;
for(var aa=0,ab=Y.length;
aa<ab;
aa++){Z.push.apply(Z,this._renderDependency(Y[aa]));
}ac.render(Z);
},_renderDependency:function(Y){var ad=this._taskCoordinates[Y.predecessorId];
var ae=this._taskCoordinates[Y.successorId];
var Z;
var ac;
if(!ad||!ae){return[];
}ac="_render"+["FF","FS","SF","SS"][y?3-Y.type:Y.type];
Z=this[ac](ad,ae);
for(var aa=0,ab=Z.length;
aa<ab;
aa++){Z[aa].attr["data-uid"]=Y.uid;
}return Z;
},_renderFF:function(Y,aa){var Z=this._dependencyFF(Y,aa,false);
Z[Z.length-1].children[0]=this._arrow(true);
return Z;
},_renderSS:function(Y,aa){var Z=this._dependencyFF(aa,Y,true);
Z[0].children[0]=this._arrow(false);
return Z.reverse();
},_renderFS:function(Y,aa){var Z=this._dependencyFS(Y,aa,false);
Z[Z.length-1].children[0]=this._arrow(false);
return Z;
},_renderSF:function(Y,aa){var Z=this._dependencyFS(aa,Y,true);
Z[0].children[0]=this._arrow(true);
return Z.reverse();
},_dependencyFF:function(ad,ao,ak){var an=this;
var ah=[];
var ag=0;
var ap=0;
var ar=0;
var af=0;
var ac=ak?"start":"end";
var ab;
var aj=2;
var aa=1;
var al=this._rowHeight;
var ai=10;
var ae=ad.rowIndex*al+Math.floor(al/2)-1;
var aq=ao.rowIndex*al+Math.floor(al/2)-1;
var am=v.styles;
var Y=function(){ah.push(an._line(am.line+" "+am.lineHorizontal,{left:ag+"px",top:ap+"px",width:ar+"px"}));
};
var Z=function(){ah.push(an._line(am.line+" "+am.lineVertical,{left:ag+"px",top:ap+"px",height:af+"px"}));
};
ag=ad[ac];
ap=ae;
ar=ai;
ab=ao[ac]-ad[ac];
if(ab>0!==ak){ar=Math.abs(ab)+ai;
}if(ak){ag-=ar;
ar-=aa;
Y();
}else{Y();
ag+=ar-aj;
}if(aq<ap){af=ap-aq;
af+=aj;
ap=aq;
Z();
}else{af=aq-ap;
af+=aj;
Z();
ap+=af-aj;
}ar=Math.abs(ag-ao[ac]);
if(!ak){ar-=aa;
ag-=ar;
}Y();
return ah;
},_dependencyFS:function(ac,ap,al){var ao=this;
var ag=[];
var af=0;
var aq=0;
var at=0;
var ae=0;
var am=this._rowHeight;
var ai=Math.floor(am/2);
var aj=10;
var ah=2*aj;
var ab=ap.start-ac.end;
var ak=2;
var aa=1;
var ad=ac.rowIndex*am+Math.floor(am/2)-1;
var ar=ap.rowIndex*am+Math.floor(am/2)-1;
var an=v.styles;
var Y=function(){ag.push(ao._line(an.line+" "+an.lineHorizontal,{left:af+"px",top:aq+"px",width:at+"px"}));
};
var Z=function(){ag.push(ao._line(an.line+" "+an.lineVertical,{left:af+"px",top:aq+"px",height:ae+"px"}));
};
af=ac.end;
aq=ad;
at=aj;
if(al){af+=aa;
if(ab>ah){at=ab-(aj-ak);
}at-=aa;
}Y();
af+=at-ak;
if(ab<=ah){ae=al?Math.abs(ar-ad)-ai:ai;
if(ar<ad){aq-=ae;
ae+=ak;
Z();
}else{Z();
aq+=ae;
}at=ac.end-ap.start+ah;
if(at<aj){at=aj;
}af-=at-ak;
Y();
}if(ar<ad){ae=aq-ar;
aq=ar;
ae+=ak;
Z();
}else{ae=ar-aq;
Z();
aq+=ae;
}at=ap.start-af;
if(!al){at-=aa;
}Y();
return ag;
},_line:function(Y,Z){return z("div",{className:Y,style:Z});
},_arrow:function(Y){return z("span",{className:Y?v.styles.arrowWest:v.styles.arrowEast});
},_colgroup:function(){var ad=this._timeSlots();
var Z=ad.length;
var Y=[];
for(var aa=0;
aa<Z;
aa++){for(var ab=0,ac=ad[aa].span;
ab<ac;
ab++){Y.push(z("col"));
}}return z("colgroup",null,Y);
},_createDragHint:function(Y){this._dragHint=Y.clone().addClass(v.styles.dragHint).css("cursor","move");
Y.parent().append(this._dragHint);
},_updateDragHint:function(Z){var Y=this._offset(Z);
this._dragHint.css({left:Y});
},_removeDragHint:function(){this._dragHint.remove();
this._dragHint=null;
},_createResizeHint:function(ab){var aa=v.styles;
var ac=this._taskCoordinates[ab.id].rowIndex*this._rowHeight;
var ad;
var ae;
var Z=this.options;
var Y=Z.messages;
this._resizeHint=l(M({styles:aa})).css({top:0,height:this._contentHeight});
this.content.append(this._resizeHint);
this._resizeTooltip=l(N({styles:aa,start:ab.start,end:ab.end,messages:Y.views,format:Z.resizeTooltipFormat})).css({top:0,left:0});
this.content.append(this._resizeTooltip);
this._resizeTooltipWidth=this._resizeTooltip.outerWidth();
ad=this._resizeTooltip.outerHeight();
ae=ac-ad;
if(ae<0){ae=ac+this._rowHeight;
}this._resizeTooltipTop=ae;
},_updateResizeHint:function(ae,Y,ac){var Z=this._offset(y?Y:ae);
var ad=this._offset(y?ae:Y);
var aj=ad-Z;
var ah=ac!==y?Z:ad;
var ag=this._tableWidth-kendo.support.scrollbar();
var ai=this._resizeTooltipWidth;
var ab=this.options;
var aa=ab.messages;
var af=l(s+v.styles.tasksTable).offset().left-l(s+v.styles.tasksWrapper).offset().left;
if(y){Z+=af;
}this._resizeHint.css({left:Z,width:aj});
if(this._resizeTooltip){this._resizeTooltip.remove();
}ah-=Math.round(ai/2);
if(ah<0){ah=0;
}else{if(ah+ai>ag){ah=ag-ai;
}}if(y){ah+=af;
}this._resizeTooltip=l(N({styles:v.styles,start:ae,end:Y,messages:aa.views,format:ab.resizeTooltipFormat})).css({top:this._resizeTooltipTop,left:ah,"min-width":ai}).appendTo(this.content);
},_removeResizeHint:function(){this._resizeHint.remove();
this._resizeHint=null;
this._resizeTooltip.remove();
this._resizeTooltip=null;
},_updatePercentCompleteTooltip:function(ae,aa,ab){this._removePercentCompleteTooltip();
var ac=this._percentCompleteResizeTooltip=l(J({styles:v.styles,text:ab})).appendTo(this.element);
var ad=Math.round(ac.outerWidth()/2);
var Y=ac.find(s+v.styles.callout);
var Z=Math.round(Y.outerWidth()/2);
ac.css({top:ae-(ac.outerHeight()+Z),left:aa-ad});
Y.css("left",ad-Z);
},_removePercentCompleteTooltip:function(){if(this._percentCompleteResizeTooltip){this._percentCompleteResizeTooltip.remove();
}this._percentCompleteResizeTooltip=null;
},_updateDependencyDragHint:function(Y,Z,aa){this._removeDependencyDragHint();
if(aa){this._creteVmlDependencyDragHint(Y,Z);
}else{this._creteDependencyDragHint(Y,Z);
}},_creteDependencyDragHint:function(ab,ad){var ac=v.styles;
var Z=ad.x-ab.x;
var aa=ad.y-ab.y;
var ae=Math.sqrt(Z*Z+aa*aa);
var Y=Math.atan(aa/Z);
if(Z<0){Y+=Math.PI;
}l("<div class='"+ac.line+" "+ac.lineHorizontal+" "+ac.dependencyHint+"'></div>").css({top:ab.y,left:ab.x,width:ae,"transform-origin":"0% 0","-ms-transform-origin":"0% 0","-webkit-transform-origin":"0% 0",transform:"rotate("+Y+"rad)","-ms-transform":"rotate("+Y+"rad)","-webkit-transform":"rotate("+Y+"rad)"}).appendTo(this.content);
},_creteVmlDependencyDragHint:function(Y,aa){var Z=l("<kvml:line class='"+v.styles.dependencyHint+"' style='position:absolute; top: 0px; left: 0px;' strokecolor='black' strokeweight='2px' from='"+Y.x+"px,"+Y.y+"px' to='"+aa.x+"px,"+aa.y+"px'></kvml:line>").appendTo(this.content);
Z[0].outerHTML=Z[0].outerHTML;
},_removeDependencyDragHint:function(){this.content.find(s+v.styles.dependencyHint).remove();
},_createTaskTooltip:function(aj,ac,ae){var ai=v.styles;
var af=this.options;
var Y=this.content;
var Z=Y.offset();
var ab=Y.width();
var aa=kendo.scrollLeft(Y);
var ag=l(ac).parents("tr").first();
var ah=ag.offset();
var ak=af.tooltip&&af.tooltip.template?kendo.template(af.tooltip.template):Q;
var ad=y?ae-(Z.left+aa+kendo.support.scrollbar()):ae-(Z.left-aa);
var an=ah.top+ag.outerHeight()-Z.top+Y.scrollTop();
var al=this._taskTooltip=l('<div style="z-index: 100002;" class="'+ai.tooltipWrapper+'" ><div class="'+ai.taskContent+'"></div></div>');
var am;
al.css({left:ad,top:an}).appendTo(Y).find(s+ai.taskContent).append(ak({styles:ai,task:aj,messages:af.messages.views}));
if(al.outerHeight()<ah.top-Z.top){al.css("top",ah.top-Z.top-al.outerHeight()+Y.scrollTop());
}am=al.outerWidth();
if(am+ad-aa>ab){ad-=am;
if(ad<aa){ad=aa+ab-(am+17);
}al.css("left",ad);
}},_removeTaskTooltip:function(){if(this._taskTooltip){this._taskTooltip.remove();
}this._taskTooltip=null;
},_scrollTo:function(ag){var ah=ag.offset().left;
var aj=ag.width();
var ai=ah+aj;
var ak=ag.closest("tr");
var an=ak.offset().top;
var am=ak.height();
var al=an+am;
var Y=this.content;
var ac=Y.offset();
var ae=ac.top;
var aa=Y.height();
var Z=ae+aa;
var ab=ac.left;
var af=Y.width();
var ad=ab+af;
var ao=kendo.support.scrollbar();
if(an<ae){Y.scrollTop(Y.scrollTop()+(an-ae));
}else{if(al>Z){Y.scrollTop(Y.scrollTop()+(al+ao-Z));
}}if(ah<ab&&aj>af&&ai<ad||ai>ad&&aj<af){Y.scrollLeft(Y.scrollLeft()+(ai+ao-ad));
}else{if(ai>ad&&aj>af&&ah>ab||ah<ab&&aj<af){Y.scrollLeft(Y.scrollLeft()+(ah-ab));
}}},_timeSlots:function(){if(!this._slots||!this._slots.length){return[];
}return this._slots[this._slots.length-1];
},_headers:function(ab){var ah=[];
var ae;
var ac;
var Y;
var ad;
var ai=v.styles;
for(var ag=0,af=ab.length;
ag<af;
ag++){ae=ab[ag];
ac=[];
for(var aa=0,Z=ae.length;
aa<Z;
aa++){Y=ae[aa];
ad=B(Y.text);
ac.push(z("th",{colspan:Y.span,className:ai.header+(Y.isNonWorking?" "+ai.nonWorking:"")},[ad]));
}ah.push(z("tr",null,ac));
}return ah;
},_hours:function(af,Y){var ad;
var ae=[];
var ac=this.options;
var ah=ac.workDayStart.getHours();
var ag=ac.workDayEnd.getHours();
var ab;
var Z;
var aa=ac.hourSpan;
af=new Date(af);
Y=new Date(Y);
while(af<Y){ad=new Date(af);
Z=ad.getHours();
ab=Z>=ah&&Z<ag;
ad.setHours(ad.getHours()+aa);
if(Z==ad.getHours()){ad.setHours(ad.getHours()+2*aa);
}if(!ac.showWorkHours||ab){ae.push({start:af,end:ad,isNonWorking:!ab,span:1});
}af=ad;
}return ae;
},_days:function(ac,Y){var aa;
var ab=[];
var Z;
ac=new Date(ac);
Y=new Date(Y);
while(ac<Y){aa=kendo.date.nextDay(ac);
Z=this._isWorkDay(ac);
if(!this.options.showWorkDays||Z){ab.push({start:ac,end:aa,isNonWorking:!Z,span:1});
}ac=aa;
}return ab;
},_weeks:function(ae,Z){var ab;
var ac=[];
var aa=this.calendarInfo().firstDay;
var Y;
var ad;
ae=new Date(ae);
Z=new Date(Z);
while(ae<Z){ab=kendo.date.dayOfWeek(kendo.date.addDays(ae,1),aa,1);
if(ab>Z){ab=Z;
}Y=this._days(ae,ab);
ad=Y.length;
if(ad>0){ac.push({start:Y[0].start,end:Y[ad-1].end,span:ad});
}ae=ab;
}return ac;
},_months:function(ad,Z){var aa;
var ab=[];
var Y;
var ac;
ad=new Date(ad);
Z=new Date(Z);
while(ad<Z){aa=new Date(ad);
aa.setMonth(aa.getMonth()+1);
Y=this._days(ad,aa);
ac=Y.length;
if(ac>0){ab.push({start:Y[0].start,end:Y[ac-1].end,span:ac});
}ad=aa;
}return ab;
},_years:function(ab,Y){var Z;
var aa=[];
ab=new Date(ab);
Y=new Date(Y);
while(ab<Y){Z=new Date(ab);
Z.setFullYear(Z.getFullYear()+1);
aa.push({start:ab,end:Z,span:12});
ab=Z;
}return aa;
},_slotHeaders:function(ac,ad){var Y=[];
var ab;
for(var Z=0,aa=ac.length;
Z<aa;
Z++){ab=ac[Z];
Y.push({text:ad(ab),isNonWorking:!!ab.isNonWorking,span:ab.span});
}return Y;
},_isWorkDay:function(Y){var Z=Y.getDay();
var ac=this._workDays;
for(var aa=0,ab=ac.length;
aa<ab;
aa++){if(ac[aa]===Z){return true;
}}return false;
},calendarInfo:function(){return kendo.getCulture().calendars.standard;
},_renderCurrentTime:function(){var Y=this._getCurrentTime();
var ad=this._offset(Y);
var Z=l("<div class='k-current-time'></div>");
var ae=v.styles;
var ab=l(s+ae.tasksWrapper);
var ac=l(s+ae.tasksTable);
var aa;
if(!this.content||!this._timeSlots().length){return;
}this.content.find(".k-current-time").remove();
aa=this._timeSlots()[this._slotIndex("start",Y)];
if(Y<aa.start||Y>aa.end){return;
}if(ab.length&&ac.length){ad+=ac.offset().left-ab.offset().left;
}Z.css({left:ad+"px",top:"0px",width:"1px",height:this._contentHeight+"px"}).appendTo(this.content);
},_getCurrentTime:function(){return new Date();
},_currentTime:function(){var Y=this.options.currentTimeMarker;
if(Y!==false&&Y.updateInterval!==j){this._renderCurrentTime();
this._currentTimeUpdateTimer=setInterval(K(this._renderCurrentTime,this),Y.updateInterval);
}}});
t(true,v,{styles:U});
kendo.ui.GanttDayView=v.extend({name:"day",options:{timeHeaderTemplate:R,dayHeaderTemplate:p,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(Y){this.start=kendo.date.getDate(Y.start);
this.end=kendo.date.getDate(Y.end);
if(kendo.date.getMilliseconds(Y.end)>0||this.end.getTime()===this.start.getTime()){this.end=kendo.date.addDays(this.end,1);
}},_createSlots:function(){var Z;
var Y;
var ab;
var aa;
var ae=[];
Z=this._days(this.start,this.end);
ab=[];
for(var ac=0,ad=Z.length;
ac<ad;
ac++){Y=Z[ac];
aa=this._hours(Y.start,Y.end);
Y.span=aa.length;
ab.push.apply(ab,aa);
}ae.push(Z);
ae.push(ab);
return ae;
},_layout:function(){var Z=[];
var Y=this.options;
Z.push(this._slotHeaders(this._slots[0],kendo.template(Y.dayHeaderTemplate)));
Z.push(this._slotHeaders(this._slots[1],kendo.template(Y.timeHeaderTemplate)));
return Z;
}});
kendo.ui.GanttWeekView=v.extend({name:"week",options:{dayHeaderTemplate:p,weekHeaderTemplate:V,resizeTooltipFormat:"h:mm tt ddd, MMM d"},range:function(aa){var Y=this.calendarInfo();
var Z=Y.firstDay;
var ab=aa.end;
if(Z===ab.getDay()){ab.setDate(ab.getDate()+7);
}this.start=kendo.date.getDate(kendo.date.dayOfWeek(aa.start,Z,-1));
this.end=kendo.date.getDate(kendo.date.dayOfWeek(ab,Z,1));
},_createSlots:function(){var Y=[];
Y.push(this._weeks(this.start,this.end));
Y.push(this._days(this.start,this.end));
return Y;
},_layout:function(){var Z=[];
var Y=this.options;
Z.push(this._slotHeaders(this._slots[0],kendo.template(Y.weekHeaderTemplate)));
Z.push(this._slotHeaders(this._slots[1],kendo.template(Y.dayHeaderTemplate)));
return Z;
}});
kendo.ui.GanttMonthView=v.extend({name:"month",options:{weekHeaderTemplate:V,monthHeaderTemplate:E,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(Y){this.start=kendo.date.firstDayOfMonth(Y.start);
this.end=kendo.date.addDays(kendo.date.getDate(kendo.date.lastDayOfMonth(Y.end)),1);
},_createSlots:function(){var Y=[];
Y.push(this._months(this.start,this.end));
Y.push(this._weeks(this.start,this.end));
return Y;
},_layout:function(){var Z=[];
var Y=this.options;
Z.push(this._slotHeaders(this._slots[0],kendo.template(Y.monthHeaderTemplate)));
Z.push(this._slotHeaders(this._slots[1],kendo.template(Y.weekHeaderTemplate)));
return Z;
}});
kendo.ui.GanttYearView=v.extend({name:"year",options:{yearHeaderTemplate:X,monthHeaderTemplate:E,resizeTooltipFormat:"dddd, MMM d, yyyy"},range:function(Y){this.start=kendo.date.firstDayOfMonth(new Date(Y.start.setMonth(0)));
this.end=kendo.date.firstDayOfMonth(new Date(Y.end.setMonth(12)));
},_createSlots:function(){var Z=[];
var Y=this._months(this.start,this.end);
l(Y).each(function(aa,ab){ab.span=1;
});
Z.push(this._years(this.start,this.end));
Z.push(Y);
return Z;
},_layout:function(){var Z=[];
var Y=this.options;
Z.push(this._slotHeaders(this._slots[0],kendo.template(Y.yearHeaderTemplate)));
Z.push(this._slotHeaders(this._slots[1],kendo.template(Y.monthHeaderTemplate)));
return Z;
}});
var S={wrapper:"k-timeline k-grid k-widget",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",gridContentWrap:"k-grid-content",tasksWrapper:"k-gantt-tables",dependenciesWrapper:"k-gantt-dependencies",task:"k-task",line:"k-line",taskResizeHandle:"k-resize-handle",taskResizeHandleWest:"k-resize-w",taskDragHandle:"k-task-draghandle",taskComplete:"k-task-complete",taskDelete:"k-task-delete",taskWrapActive:"k-task-wrap-active",taskWrap:"k-task-wrap",taskDot:"k-task-dot",taskDotStart:"k-task-start",taskDotEnd:"k-task-end",hovered:"k-state-hover",selected:"k-state-selected",origin:"k-origin"};
var u=kendo.ui.GanttTimeline=W.extend({init:function(Y,Z){W.fn.init.call(this,Y,Z);
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}y=kendo.support.isRtl(Y);
this._wrapper();
this._domTrees();
this._views();
this._selectable();
this._draggable();
this._resizable();
this._percentResizeDraggable();
this._createDependencyDraggable();
this._attachEvents();
this._tooltip();
},options:{name:"GanttTimeline",messages:{views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"}},snap:true,selectable:true,editable:true},destroy:function(){W.fn.destroy.call(this);
clearTimeout(this._tooltipTimeout);
if(this._currentTimeUpdateTimer){clearInterval(this._currentTimeUpdateTimer);
}this._unbindView(this._selectedView);
if(this._moveDraggable){this._moveDraggable.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}if(this._percentDraggable){this._percentDraggable.destroy();
}if(this._dependencyDraggable){this._dependencyDraggable.destroy();
}if(this.touch){this.touch.destroy();
}this._headerTree=null;
this._taskTree=null;
this._dependencyTree=null;
this.wrapper.off(I);
kendo.destroy(this.wrapper);
},_wrapper:function(){var aa=u.styles;
var ab=this;
var Z=this.options;
var Y=function(){var af=typeof Z.rowHeight===P?Z.rowHeight:Z.rowHeight+"px";
var ag=l(kendo.format(O,af));
var ad;
var ac;
var ae=ab.wrapper.find(s+aa.tasksWrapper);
ae.append(ag);
ad=ag.find("tr").outerHeight();
ac=ag.find("td").height();
ag.remove();
return{row:ad,cell:ac};
};
this.wrapper=this.element.addClass(aa.wrapper).append("<div class='"+aa.gridHeader+"'><div class='"+aa.gridHeaderWrap+"'></div></div>").append("<div class='"+aa.gridContentWrap+"'><div class='"+aa.tasksWrapper+"'></div><div class='"+aa.dependenciesWrapper+"'></div></div>");
if(Z.rowHeight){this._calculatedSize=Y();
}},_domTrees:function(){var Y=u.styles;
var Z=kendo.dom.Tree;
var aa=this.wrapper;
this._headerTree=new Z(aa.find(s+Y.gridHeaderWrap)[0]);
this._taskTree=new Z(aa.find(s+Y.tasksWrapper)[0]);
this._dependencyTree=new Z(aa.find(s+Y.dependenciesWrapper)[0]);
},_views:function(){var af=this.options.views;
var ae;
var aa;
var ac;
var Y;
var ad;
this.views={};
for(var Z=0,ab=af.length;
Z<ab;
Z++){ae=af[Z];
aa=x(ae);
if(aa&&ae.selectable===false){continue;
}ac=aa?typeof ae.type!=="string"?ae.title:ae.type:ae;
Y=r[ac];
if(Y){if(aa){ae.type=Y.type;
}Y.title=this.options.messages.views[ac];
}ae=t({title:ac},Y,aa?ae:{});
if(ac){this.views[ac]=ae;
if(!ad||ae.selected){ad=ac;
}}}if(ad){this._selectedViewName=ad;
}},view:function(Y){if(Y){this._selectView(Y);
this.trigger("navigate",{view:Y,action:"changeView"});
}return this._selectedView;
},_selectView:function(Y){if(Y&&this.views[Y]){if(this._selectedView){this._unbindView(this._selectedView);
}this._selectedView=this._initializeView(Y);
this._selectedViewName=Y;
}},_viewByIndex:function(Y){var Z;
var aa=this.views;
for(Z in aa){if(!Y){return Z;
}Y--;
}},_initializeView:function(Y){var aa=this.views[Y];
if(aa){var Z=aa.type;
if(typeof Z==="string"){Z=kendo.getter(aa.type)(window);
}if(Z){aa=new Z(this.wrapper,T(t(true,{headerTree:this._headerTree,taskTree:this._taskTree,dependencyTree:this._dependencyTree,calculatedSize:this._calculatedSize},aa,this.options)));
}else{throw new Error("There is no such view");
}}return aa;
},_unbindView:function(Y){if(Y){Y.destroy();
}},_range:function(ac){var ab={field:"start",dir:"asc"};
var Z={field:"end",dir:"desc"};
if(!ac||!ac.length){return{start:new Date(),end:new Date()};
}var aa=new L(ac).sort(ab).toArray()[0].start||new Date();
var Y=new L(ac).sort(Z).toArray()[0].end||new Date();
return{start:new Date(aa),end:new Date(Y)};
},_render:function(Z){var aa=this.view();
var Y=this._range(Z);
this._tasks=Z;
aa.range(Y);
aa.renderLayout();
aa.render(Z);
},_renderDependencies:function(Y){this.view()._renderDependencies(Y);
},_taskByUid:function(ac){var ab=this._tasks;
var Z=ab.length;
var aa;
for(var Y=0;
Y<Z;
Y++){aa=ab[Y];
if(aa.uid===ac){return aa;
}}},_draggable:function(){var af=this;
var aa;
var ae;
var Z;
var ac;
var ab=this.options.snap;
var ad=u.styles;
var Y=function(){af.view()._removeDragHint();
if(aa){aa.css("opacity",1);
}aa=null;
ae=null;
af.dragInProgress=false;
};
if(!this.options.editable){return;
}this._moveDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:s+ad.task,holdToDrag:kendo.support.mobileOS,ignore:s+ad.taskResizeHandle});
this._moveDraggable.bind("dragstart",function(ag){var ah=af.view();
aa=ag.currentTarget.parent();
ae=af._taskByUid(ag.currentTarget.attr("data-uid"));
if(af.trigger("moveStart",{task:ae})){ag.preventDefault();
return;
}Z=ae.start;
ac=ah._timeByPosition(ag.x.location,ab)-Z;
ah._createDragHint(aa);
aa.css("opacity",0.5);
clearTimeout(af._tooltipTimeout);
af.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ah){if(!af.dragInProgress){return;
}var aj=af.view();
var ag=new Date(aj._timeByPosition(ah.x.location,ab)-ac);
var ai=ag;
if(!af.trigger("move",{task:ae,start:ag})){Z=ag;
if(y){ai=new Date(Z.getTime()+ae.duration());
}aj._updateDragHint(ai);
}},15)).bind("dragend",function(){af.trigger("moveEnd",{task:ae,start:Z});
Y();
}).bind("dragcancel",function(){Y();
}).userEvents.bind("select",function(){m();
});
},_resizable:function(){var ag=this;
var ab;
var af;
var aa;
var Z;
var ac;
var ad=this.options.snap;
var ae=u.styles;
var Y=function(){ag.view()._removeResizeHint();
ab=null;
af=null;
ag.dragInProgress=false;
};
if(!this.options.editable){return;
}this._resizeDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:s+ae.taskResizeHandle,holdToDrag:false});
this._resizeDraggable.bind("dragstart",function(ah){ac=ah.currentTarget.hasClass(ae.taskResizeHandleWest);
if(y){ac=!ac;
}ab=ah.currentTarget.closest(s+ae.task);
af=ag._taskByUid(ab.attr("data-uid"));
if(ag.trigger("resizeStart",{task:af})){ah.preventDefault();
return;
}aa=af.start;
Z=af.end;
ag.view()._createResizeHint(af);
clearTimeout(ag._tooltipTimeout);
ag.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ai){if(!ag.dragInProgress){return;
}var aj=ag.view();
var ah=aj._timeByPosition(ai.x.location,ad,!ac);
if(ac){if(ah<Z){aa=ah;
}else{aa=Z;
}}else{if(ah>aa){Z=ah;
}else{Z=aa;
}}if(!ag.trigger("resize",{task:af,start:aa,end:Z})){aj._updateResizeHint(aa,Z,ac);
}},15)).bind("dragend",function(){ag.trigger("resizeEnd",{task:af,resizeStart:ac,start:aa,end:Z});
Y();
}).bind("dragcancel",function(){Y();
}).userEvents.bind("select",function(){m();
});
},_percentResizeDraggable:function(){var ah=this;
var ae;
var af;
var ag;
var ai;
var ac;
var ab;
var Z;
var ak;
var aj;
var ad=u.styles;
var aa;
var Y=function(){ah.view()._removePercentCompleteTooltip();
af=null;
ae=null;
ah.dragInProgress=false;
};
var al=function(am){af.find(s+ad.taskComplete).width(am).end().siblings(s+ad.taskDragHandle).css(y?"right":"left",am);
};
if(!this.options.editable){return;
}this._percentDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:s+ad.taskDragHandle,holdToDrag:false});
this._percentDraggable.bind("dragstart",function(am){if(ah.trigger("percentResizeStart")){am.preventDefault();
return;
}af=am.currentTarget.siblings(s+ad.task);
ae=ah._taskByUid(af.attr("data-uid"));
Z=ae.percentComplete;
ag=af.offset();
ai=this.element.offset();
ac=af.find(s+ad.taskComplete).width();
ab=af.outerWidth();
clearTimeout(ah._tooltipTimeout);
ah.dragInProgress=true;
}).bind("drag",kendo.throttle(function(an){if(!ah.dragInProgress){return;
}aa=y?-an.x.initialDelta:an.x.initialDelta;
var am=Math.max(0,Math.min(ab,ac+aa));
Z=Math.round(am/ab*100);
al(am);
ak=ag.top-ai.top;
aj=ag.left+am-ai.left;
if(y){aj+=ab-2*am;
}ah.view()._updatePercentCompleteTooltip(ak,aj,Z);
},15)).bind("dragend",function(){ah.trigger("percentResizeEnd",{task:ae,percentComplete:Z/100});
Y();
}).bind("dragcancel",function(){al(ac);
Y();
}).userEvents.bind("select",function(){m();
});
},_createDependencyDraggable:function(){var af=this;
var ab;
var Z=l();
var aa=l();
var ac;
var ad;
var ah=n.msie&&n.version<9;
var ae=u.styles;
var Y=function(){ab.css("display","").removeClass(ae.hovered);
ab.parent().removeClass(ae.origin);
ab=null;
ag(false);
aa=l();
Z=l();
af.view()._removeDependencyDragHint();
af.dragInProgress=false;
};
var ag=function(ai){if(!aa.hasClass(ae.origin)){aa.find(s+ae.taskDot).css("display",ai?"block":"");
Z.toggleClass(ae.hovered,ai);
}};
if(!this.options.editable){return;
}if(ah&&document.namespaces){document.namespaces.add("kvml","urn:schemas-microsoft-com:vml","#default#VML");
}this._dependencyDraggable=new kendo.ui.Draggable(this.wrapper,{distance:0,filter:s+ae.taskDot,holdToDrag:false});
this._dependencyDraggable.bind("dragstart",function(ai){if(af.trigger("dependencyDragStart")){ai.preventDefault();
return;
}ab=ai.currentTarget.css("display","block").addClass(ae.hovered);
ab.parent().addClass(ae.origin);
var aj=ab.offset();
var ak=af.wrapper.find(s+ae.tasksWrapper).offset();
ac=Math.round(aj.left-ak.left+ab.outerHeight()/2);
ad=Math.round(aj.top-ak.top+ab.outerWidth()/2);
clearTimeout(af._tooltipTimeout);
af.dragInProgress=true;
}).bind("drag",kendo.throttle(function(ak){if(!af.dragInProgress){return;
}af.view()._removeDependencyDragHint();
var am=l(kendo.elementUnderCursor(ak));
var al=af.wrapper.find(s+ae.tasksWrapper).offset();
var ai=ak.x.location-al.left;
var aj=ak.y.location-al.top;
af.view()._updateDependencyDragHint({x:ac,y:ad},{x:ai,y:aj},ah);
ag(false);
Z=am.hasClass(ae.taskDot)?am:l();
aa=am.closest(s+ae.taskWrap);
ag(true);
},15)).bind("dragend",function(){if(Z.length){var ai=ab.hasClass(ae.taskDotStart);
var al=Z.hasClass(ae.taskDotStart);
var am=ai?al?3:2:al?1:0;
var aj=af._taskByUid(ab.siblings(s+ae.task).attr("data-uid"));
var ak=af._taskByUid(Z.siblings(s+ae.task).attr("data-uid"));
if(aj!==ak){af.trigger("dependencyDragEnd",{type:am,predecessor:aj,successor:ak});
}}Y();
}).bind("dragcancel",function(){Y();
}).userEvents.bind("select",function(){m();
});
},_selectable:function(){var Z=this;
var Y=u.styles;
if(this.options.selectable){this.wrapper.on(o+I,s+Y.task,function(aa){aa.stopPropagation();
if(!aa.ctrlKey){Z.trigger("select",{uid:l(this).attr("data-uid")});
}else{Z.trigger("clear");
}}).on(o+I,s+Y.taskWrap,function(aa){aa.stopPropagation();
l(this).css("z-index","0");
var ab=l(document.elementFromPoint(aa.clientX,aa.clientY));
if(ab.hasClass(Y.line)){ab.click();
}l(this).css("z-index","");
}).on(o+I,s+Y.tasksWrapper,function(){if(Z.selectDependency().length>0){Z.clearSelection();
}else{Z.trigger("clear");
}}).on(o+I,s+Y.line,function(aa){aa.stopPropagation();
Z.selectDependency(this);
});
}},select:function(aa){var Y=this.wrapper.find(aa);
var Z=u.styles;
if(Y.length){this.clearSelection();
Y.addClass(Z.selected);
if(kendo.support.mobileOS){Y.parent().addClass(Z.taskWrapActive);
}return;
}return this.wrapper.find(s+Z.task+s+Z.selected);
},selectDependency:function(ab){var Y=this.wrapper.find(ab);
var aa;
var Z=u.styles;
if(Y.length){this.clearSelection();
this.trigger("clear");
aa=l(Y).attr("data-uid");
this.wrapper.find(s+Z.line+"[data-uid='"+aa+"']").addClass(Z.selected);
return;
}return this.wrapper.find(s+Z.line+s+Z.selected);
},clearSelection:function(){var Y=u.styles;
this.wrapper.find(s+Y.selected).removeClass(Y.selected);
if(kendo.support.mobileOS){this.wrapper.find(s+Y.taskWrapActive).removeClass(Y.taskWrapActive);
}},_attachEvents:function(){var Z=this;
var Y=u.styles;
if(this.options.editable){this._tabindex();
this.wrapper.on(o+I,s+Y.taskDelete,function(aa){Z.trigger("removeTask",{uid:l(this).closest(s+Y.task).attr("data-uid")});
aa.stopPropagation();
aa.preventDefault();
}).on(C+I,function(aa){var ab;
if(aa.keyCode===D.DELETE){ab=Z.selectDependency();
if(ab.length){Z.trigger("removeDependency",{uid:ab.attr("data-uid")});
Z.clearSelection();
}}});
if(!kendo.support.mobileOS){this.wrapper.on(q+I,s+Y.task,function(aa){Z.trigger("editTask",{uid:l(this).attr("data-uid")});
aa.stopPropagation();
aa.preventDefault();
});
}else{this.touch=this.wrapper.kendoTouch({filter:s+Y.task,doubletap:function(aa){Z.trigger("editTask",{uid:l(aa.touch.currentTarget).attr("data-uid")});
}}).data("kendoTouch");
}}},_tooltip:function(){var ab=this;
var ac=this.options.tooltip;
var aa=u.styles;
var Y;
var Z=function(ad){Y=ad.clientX;
};
if(ac&&ac.visible===false){return;
}if(!kendo.support.mobileOS){this.wrapper.on(F+I,s+aa.task,function(){var ad=this;
var ae=ab._taskByUid(l(this).attr("data-uid"));
if(ab.dragInProgress){return;
}ab._tooltipTimeout=setTimeout(function(){ab.view()._createTaskTooltip(ae,ad,Y);
},800);
l(this).on(H,Z);
}).on(G+I,s+aa.task,function(){clearTimeout(ab._tooltipTimeout);
ab.view()._removeTaskTooltip();
l(this).off(H,Z);
});
}else{this.wrapper.on(o+I,s+aa.taskDelete,function(ad){ad.stopPropagation();
ab.view()._removeTaskTooltip();
}).on(G+I,s+aa.task,function(ad){var ae=l(ad.relatedTarget).parents(s+aa.taskWrap,s+aa.task);
if(ae.length===0){ab.view()._removeTaskTooltip();
}});
this.touch.bind("tap",function(ae){var af=ae.touch.target;
var ag=ab._taskByUid(l(af).attr("data-uid"));
var ad=ae.touch.x.client;
if(ab.view()._taskTooltip){ab.view()._removeTaskTooltip();
}ab.view()._createTaskTooltip(ag,af,ad);
}).bind("doubletap",function(){ab.view()._removeTaskTooltip();
});
}}});
t(true,u,{styles:S});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
