(function(a){$telerik.findAutoComplete=$find;
$telerik.toAutoComplete=function(n){return n;
};
Type.registerNamespace("Telerik.Web.UI");
var c=Telerik.Web.UI,b=Sys.Serialization.JavaScriptSerializer,g={0:"contains",1:"startswith"},j=1,e=".",i=2,m="racToken",h="racFocused",k="racSelected",l="racShowAll",d=46,f=113;
a.registerEnum(c,"RadAutoCompleteInputType",{Token:0,Text:1});
a.registerEnum(c,"RadAutoCompleteFilter",{Contains:0,StartsWith:1});
a.registerEnum(c,"RadAutoCompleteDropDownPosition",{Automatic:0,Static:1});
a.registerEnum(c,"RadAutoCompleteBinding",{Callback:0,WebService:1,OData:2,ClientDataSource:3});
c.AutoCompleteBoxAttributeCollection=function(){this._data={};
this._keys=[];
};
c.AutoCompleteBoxAttributeCollection.prototype={getAttribute:function(n){return this._data[n];
},setAttribute:function(n,o){this._add(n,o);
},_add:function(n,o){if(Array.indexOf(this._keys,n)<0){Array.add(this._keys,n);
}this._data[n]=o;
},removeAttribute:function(n){Array.remove(this._keys,n);
delete this._data[n];
},_load:function(n){for(var o in n){this._add(o,n[o]);
}},get_count:function(){return this._keys.length;
}};
c.AutoCompleteBoxAttributeCollection.registerClass("Telerik.Web.UI.AutoCompleteBoxAttributeCollection");
c.RadAutoCompleteBox=function(n){c.RadAutoCompleteBox.initializeBase(this,[n]);
this._entryData=null;
this._dropDownItemData=null;
this._children=null;
this._inputElement=null;
this._originalText="";
this._log=new c.ChangeLog();
this._attributes=new c.AutoCompleteBoxAttributeCollection(this);
this._persistChanges=true;
this._postBackReference=null;
this._postBackOnRemove=false;
this._postBackOnAdd=false;
this._postBackOnChange=false;
this._animationContainer=null;
this._enabled=true;
this._dropDown=null;
this._entries=[];
this._uniqueId=null;
this._requestTimer=null;
this._requestInProgress=false;
this._selectedToken=null;
this._flatBinder=null;
this._bindingMode=null;
this._webServiceSettings=null;
this._webServiceLoader=null;
this._clientDropDownTemplate=null;
this._emptyMessage=null;
this._tokensSettings=[];
this._textSettings=[];
this._removeTokenTitle="";
this._requestDelay=250;
this._loadingIcon=null;
this._showAllResultsText="";
this._clientDataSource=null;
this._clientDataSourceID="";
this._dataTextField="";
this._dataValueField="";
this._odataClientSettings=null;
this._highlightFirstMatch=true;
this._shouldFocus=false;
this._expandAnimation=new c.AnimationSettings({});
this._collapseAnimation=new c.AnimationSettings({});
this._enableScreenBoundaryDetection=true;
this._enableDirectionDetection=false;
this._ariaSettings=null;
};
c.RadAutoCompleteBox.prototype={initialize:function(){var q=this,n=a(this._element),o=a(this.get_inputElement());
c.RadAutoCompleteBox.callBaseMethod(this,"initialize");
this._log.initialize();
if(this._isInTokenMode()){n.on("click",".racRemoveTokenLink",function(r){q._onRemoveLinkClick(r);
});
n.on("click","."+m,function(r){q._onTokenClick(r);
});
if(this.get_tokensSettings().allowTokenEditing){n.on("dblclick",".racToken",function(r){q._onTokenDblClick(r);
r.stopPropagation();
});
n.on("keydown",".racEditTokenInput",function(r){q._onEditInputKeyDown(r);
});
n.on("blur",".racEditTokenInput",function(r){q._onEditInputBlur(r);
});
}}n.on("click",function(r){q._onInputCellClick(r);
});
o.attr({autocomplete:"off",size:20}).on({keydown:function(r){q._onKeyDown(r);
},keypress:function(r){q._onKeyPress(r);
},keyup:function(r){q._onKeyUp(r);
},paste:function(r){q._onPaste(r);
},blur:function(r){q._onBlur(r);
},focusin:function(r){q._onFocus(r);
}});
if(this.get_showLoadingIcon()){this._createLoadingIcon();
}this._initializeDropDown();
this._initializeInputWidth(true);
this._createChildControls();
this._cdInitDelegate=a.proxy(this._initializeClientDataSource,this);
Sys.Application.add_load(this._cdInitDelegate);
var p=this.get_text();
if(!this._isInTokenMode()){this._originalText=this.get_text();
}this.get_element().value=p;
this._initializeValidatorChangeEvent();
if(this.get_isUsingODataSource()){this._initializeODataSourceBinder();
}this._bindingMode=this._determineBindingMode();
this._toggleEmptyMessage();
this._updateInputSize(true);
if(this._enableClientFiltering){if(this._bindingMode!=c.RadAutoCompleteBinding.Callback){a(this._dropDown.get_itemsContainer()).empty();
this._requestItems("",true);
}this._dropDown.hideItems();
}if(!this._enabled){this.disable();
}if(this._shouldFocus){o.focus();
}if(this.get_enableAriaSupport()){this._applyAriaSupport();
}this._raiseControlEvent(this,"load",{});
},dispose:function(){c.RadAutoCompleteBox.callBaseMethod(this,"dispose");
this._dropDown.dispose();
a(this._element).add(this.get_inputElement()).off();
},_initializeValidatorChangeEvent:function(n){var q=this._inputElement,p="if(!event) return; var t = event.srcElement || event.target; if (!t._shouldTriggerChange) return; ",o=q.onchange;
if(typeof(o)=="function"){o=o.toString();
o=o.substring(o.indexOf("{")+1,o.lastIndexOf("}"));
q.onchange=new Function("event",p+" "+o);
}},enable:function(){this.set_enabled(true);
},disable:function(){this.set_enabled(false);
},clear:function(){this._dropDown.close();
},createEntry:function(q,r,n){var p=new c.AutoCompleteBoxEntry(),o={text:q,value:r,attributes:n};
p._initialize(o,this);
return p;
},query:function(o){var q=this,p=(this.get_maxResultCount()==-1),n=q._dropDown;
o=o||this.get_searchString();
q._cachedSearchString=o;
clearTimeout(this._requestTimer);
if(!o||o.length<this.get_minFilterLength()){this.clear();
}else{if(this.get_enableClientFiltering()){n.filterItems(o,p);
n.open(q._getDropDownPositionInfo());
}else{this._requestTimer=setTimeout(function(){q._requestItems(o,p);
},this._requestDelay);
}}},saveClientState:function(){var n=(this._log._logEntries!==null)?this._log.serialize():"[]";
return'{"enabled":'+this._enabled+',"logEntries":'+n+"}";
},updateClientState:function(){if(this._shouldUpdateClientState){this.set_clientState(this.saveClientState());
}},_applyAriaSupport:function(){this._applyInputElementAttributes();
this._applyDropDownElementAttributes();
this._applyTokenListAttributes();
if(this._ariaSettings){var o=b.deserialize(this._ariaSettings);
var n=new c.WaiAriaDecorator(this.get_inputElement(),o);
n.setAttributes();
}},_applyInputElementAttributes:function(){var r=this,n=a(r.get_element()),o=n.find(".racLabel"),q=r.get_id()+"_label",p=r.get_inputElement();
a(p).attr({role:"textbox","aria-haspopup":true,"aria-expanded":false,"aria-readonly":false,"aria-disabled":!r.get_enabled(),"aria-busy":false,"aria-owns":r.get_id()+"_listbox "+r.get_id()+"_tokens"});
if(o.length>0){a(p).attr("aria-labelledby",q);
o.attr("id",q);
}else{if(r.get_element().title){a(p).attr("aria-label",r.get_element().title);
}}p.setAttribute("aria-autocomplete","listbox");
},_applyDropDownElementAttributes:function(){var o=this,n=a(o.get_dropDownElement());
n.attr({role:"listbox","aria-live":"polite",id:o.get_id()+"_listbox"});
},_applyTokenListAttributes:function(){var o=this,n=a(o.get_element()).find(".racTokenList");
n.attr({role:"list","aria-hidden":"false","aria-readonly":"false",id:o.get_id()+"_tokens"});
},_applyTokenAriaAttributes:function(){var p=this,o=p.get_inputElement(),n=a(p._selectedToken);
if(p._selectedToken){n.attr({role:"option","aria-label":n.text(),"aria-readonly":!p.get_allowTokenEditing(),id:p.get_id()+"_focusedToken"});
a(o).attr({role:"listbox","aria-activedescendant":p.get_id()+"_focusedToken"});
}else{a(o).attr("role","textbox");
a(o).attr("aria-activedescendant",a(o).attr("id"));
a(o).attr("aria-expanded",false);
}},_addEntry:function(n){this.get_entries()._add(n);
if(this._postBackOnAdd){this._postback({command:"Add",text:n.get_text(),value:n.get_value(),attributes:n.get_attributes()._data});
}else{this._logChanges();
}},_addTextToken:function(n){var o=n._renderTextToken();
this._insertToken(n,o,".racTextToken");
},_addToken:function(n){var o=n._renderToken();
this._insertToken(n,o,".racToken");
},_insertToken:function(q,r,p){var n=a(this.get_inputElement()),o;
a(r).insertBefore(n);
o=n.parent().find(p).last();
o.data("entry",q);
q.set_token(o[0]);
n.val("");
},_addEntryFromItem:function(o){if(!this._isInTokenMode()&&this.get_allowCustomEntry()){this._appendEntryText(o.get_text(),!this._isInSingleSelectionMode());
return;
}var n=this._createEntryFromDropDownItem(o);
this._appendEntryText(o.get_text(),!this._isInSingleSelectionMode());
this._addEntry(n);
},_appendEntryText:function(p,n){var s=this.get_text(),t,q=this.get_inputElement(),o=this.get_delimiter().charAt(0)+" ",r="";
t=this._getDelimiterIndex(s);
if(t!=-1&&!this._isInTokenMode()&&this.get_allowCustomEntry()){if(!this._getIsDoubleSymbolDelimiter()){r=s.substring(0,t)+o;
}else{r=s.substring(0,t+1)+" ";
}}r+=p;
if(n){r+=o;
}q.value=r;
this._updateInputSize();
},_clearTokenSelection:function(){a(this._selectedToken).removeClass(h);
this._selectedToken=null;
},_createChildControls:function(){var n=this,p=this._entryData,o=new c.AutoCompleteBoxEntryCollection(n);
this._children=o;
this._childControlsCreated=true;
if(this.get_enableClientFiltering()&&this._dropDownItemData){this._populateDropDown(this._dropDownItemData,true);
}if(!this._entryData){return;
}a.each(p,function(q){var r=new c.AutoCompleteBoxEntry();
r._initialize(p[q],n);
o._add(r);
});
this._originalText=this.get_text();
this._logChanges();
},_createLoadingIcon:function(){var n=document.createElement("span");
n.className="racLoadingIcon";
n.style.display="none";
a(this.get_inputElement()).after(n);
this._loadingIcon=n;
},_createEntryFromDropDownItem:function(n){return this.createEntry(n.get_text(),n.get_value(),n.get_attributes()._data);
},_createEntriesFromText:function(v){var p,t,n=this.get_delimiter(),s;
if(!this._getIsDoubleSymbolDelimiter()){p=this.get_text().split(n);
}else{t=this._getDoubleCharRegExp(n);
p=this.get_text().split(t);
}s=p.length;
this.get_entries().clear();
if(this._isInSingleSelectionMode()){if(v){this._addEntry(this.createEntry(v));
}}else{for(var r=0;
r<s;
r++){var q=p[r].trim();
if(q){this._addEntry(this.createEntry(q));
if(this._getIsDoubleSymbolDelimiter()){var u=v.indexOf(q),o=v.substr(u+q.length,1);
v=v.substr(v.indexOf(o));
}}}}},_determineBindingMode:function(){if(this._clientDataSourceID){return c.RadAutoCompleteBinding.ClientDataSource;
}else{if(this.get_odataClientSettings()){return c.RadAutoCompleteBinding.OData;
}else{if(this.get_webServiceSettings()){return c.RadAutoCompleteBinding.WebService;
}else{return c.RadAutoCompleteBinding.Callback;
}}}},_requestItems:function(p,q){var n=c.RadAutoCompleteBinding,o={searchString:p,showAllResults:q};
switch(this.get_bindingMode()){case n.WebService:this._doLoadOnDemandFromWebService(o);
break;
case n.OData:this._doLoadOnDemandUsingOData(o);
break;
case n.Callback:this._doLoadOnDemand(o);
break;
case n.ClientDataSource:this._doLoadOnDemandFromClientDataSource(o);
break;
}},_loadDropDownItems:function(n,o,p){this._raiseControlEvent(this,"requested",{data:n,text:this.get_searchString()});
this._dropDown._clientTemplate=this._clientDropDownTemplate;
this._populateDropDown(n,false,p,o);
},_doLoadOnDemandUsingOData:function(o){var v=this,q=o.searchString,t=o.showAllResults,u=this.get_odataClientSettings().DataTextField,r=t?-1:this.get_maxResultCount(),p={ShowAllResults:o.showAllResults};
v._onRequestStart();
var s={events:{requesting:function(w){var x=w.get_options();
if(!v.get_enableClientFiltering()){w.set_filterExpressions({field:u,operator:g[v.get_filter()],value:q});
}if(r>0){x.data.take=r;
}x.context=p;
},success:function(w,x){if(v._requestInProgress){v._onODataResponse(w,x,arguments[2]);
v._onRequestEnd();
}},fail:function(w){if(v._requestInProgress){v._onErrorReceived("Request failed","");
v._onRequestEnd();
}}}};
var n=this._raiseCancellableControlEvent(this,"requesting",{text:this.get_searchString()});
if(n){return;
}this._flatBinder.fetch(s);
},_onODataResponse:function(r,o,n){var p=(o==r.length),q=(n&&!n.ShowAllResults)?!p:false;
this._loadDropDownItems(r,null,q);
},_doLoadOnDemand:function(r){var s=r.searchString,n={Text:s,ShowAllResults:r.showAllResults},t=Function.createDelegate(this,this._onCallbackResponse),u=Function.createDelegate(this,this._onCallbackError),p=new c.CallbackSettings({id:this._uniqueId,arguments:b.serialize(n),onCallbackSuccess:t,context:{ShowAllResults:r.showAllResults},onCallbackError:u,isAsync:true});
this._onRequestStart();
var q=this._raiseCancellableControlEvent(this,"requesting",{text:s});
if(q){return;
}var o=new c.CallbackLoader(p);
o.invokeCallbackMethod();
},_onCallbackResponse:function(r,o){if(!this._requestInProgress){return;
}var s=r.split("_$$_"),p=a.parseJSON(s[0]),n=a(this.get_dropDownElement()).find("ul"),q=(o&&!o.ShowAllResults)?(s[2]!="True"):false;
n.html(s[1]);
this._raiseControlEvent(this,"requested",{data:p,text:this.get_searchString()});
this._populateDropDown(p,true,q);
this._onRequestEnd();
},_onCallbackError:function(n){if(!this._requestInProgress){return;
}this._onErrorReceived(n,this.get_searchString());
this._onRequestEnd();
},_doLoadOnDemandFromClientDataSource:function(q){this._onRequestStart();
var o=this._raiseCancellableControlEvent(this,"requesting",{text:q.searchString});
if(o){return;
}var p=this._clientDataSource,n=this;
if(p.get_data().length===0){p.fetch(function(){n._processClientDataSourceData(q);
});
}else{n._processClientDataSourceData(q);
}},_loadItemsFromData:function(n,s){var p=n,q=this.get_maxResultCount(),r,o={dataTextField:this._dataTextField,dataValueField:this._dataValueField};
if(s){r=false;
}else{if(q<p.length){p=p.slice(0,q);
r=true;
}else{r=false;
}}this._loadDropDownItems(p,o,r);
this._onRequestEnd();
},_processClientDataSourceData:function(r){if(!this._requestInProgress){return;
}var p=this._clientDataSource,o=this;
var q,n=Telerik.Web.UI.ClientDataSource.FilterOperator;
if(this.get_filter()==Telerik.Web.UI.RadAutoCompleteFilter.Contains){q=n.Contains;
}else{q=n.StartsWith;
}p.get_filterExpressions().clear();
p.get_filterExpressions().add([{fieldName:this._dataTextField,value:r.searchString,operator:q}]);
p.fetch(function(){var s=p.view();
o._loadItemsFromData(s,r.showAllResults);
});
},_doLoadOnDemandFromWebService:function(o){var q=o.searchString,t=o.showAllResults,u={Text:q,MaxResultCount:t?-1:this.get_maxResultCount(),IsCaseSensitive:this.get_isCaseSensitive()},p={ShowAllResults:o.showAllResults},r={context:u},v=this.get_webServiceSettings(),s=v;
this._onRequestStart();
var n=this._raiseCancellableControlEvent(this,"requesting",r);
if(n){return;
}this._webServiceLoader=new c.WebServiceLoader(v);
if(s.get_isWcf()){r.context=this._webServiceLoader._serializeDictionaryAsKeyValuePairs(r.context);
}this._webServiceLoader.add_loadingSuccess(Function.createDelegate(this,this._onWebServiceResponse));
this._webServiceLoader.add_loadingError(Function.createDelegate(this,this._onWebServiceError));
this._webServiceLoader.loadData(r,p);
},_onWebServiceResponse:function(t,o){if(!this._requestInProgress){return;
}var p=o.get_data().Items,q=this.get_maxResultCount(),u=o.get_context().ShowAllResults,n=o.get_data().EndOfItems,r=(o&&!u)?!n:false,s;
if(q!=-1&&q<p.length){if(u){r=false;
}else{p=p.slice(0,q);
r=true;
}}s=p;
this._loadDropDownItems(s,null,r);
this._onRequestEnd();
},_onWebServiceError:function(p,o){if(!this._requestInProgress){return;
}var n=o.get_message(),q=o.get_context();
this._onErrorReceived(n,q);
this._onRequestEnd();
},_onErrorReceived:function(o,q){var p=(o.indexOf("DataSource not set")!=-1),n={errorMessage:o};
if(this._raiseCancellableControlEvent(this,"requestFailed",n)){return;
}if(p){alert("The control DataSource(or DataSourceID) is not set.");
}else{alert(o);
}},_onRequestStart:function(){if(this.get_showLoadingIcon()){a(this._loadingIcon).show();
if(this.get_enableAriaSupport()){a(this.get_inputElement()).attr("aria-busy",true);
}}this._requestInProgress=true;
},_onRequestEnd:function(){if(this.get_showLoadingIcon()){a(this._loadingIcon).hide();
if(this.get_enableAriaSupport()){a(this.get_inputElement()).attr("aria-busy",false);
}}this._requestInProgress=false;
},_ensureChildControls:function(){if(!this._childControlsCreated){this._createChildControls();
this._childControlsCreated=true;
}},_focusInput:function(n){var o=this;
o.get_inputElement().focus();
},_getEntriesTexts:function(){var q=[],n=this.get_entries(),o=n.get_count();
if(this._isInSingleSelectionMode()){if(o>0){return n.getEntry(0).get_text();
}else{return"";
}}for(var p=0;
p<o;
p++){q[q.length]=n.getEntry(p).get_text();
if(this._getIsDoubleSymbolDelimiter()&&!this._isInTokenMode()){q[q.length]=this.get_delimiter().charAt(0);
}else{q[q.length]=this.get_delimiter();
}q[q.length]=" ";
}return q.join("");
},_initializeDropDown:function(){var s=this,p=a(this._element).find(".racSlide").get(0),n=a(p).children(".RadAutoCompleteBoxPopup"),q=a(this._element).find(".racLabel").outerWidth();
if(q){q+=1;
}var o={enableClientFiltering:this.get_enableClientFiltering(),filter:this.get_filter(),maxResultCount:this.get_maxResultCount(),isCaseSensitive:this.get_isCaseSensitive(),showAllResultsText:this._showAllResultsText,highlightFirstMatch:this._highlightFirstMatch,width:this.get_dropDownWidth()||(a(this._element).width()-q),height:this.get_dropDownHeight(),anchor:this._element,expandAnimation:this.get_expandAnimation(),collapseAnimation:this.get_collapseAnimation(),enableScreenBoundaryDetection:this.get_enableScreenBoundaryDetection(),enableDirectionDetection:this.get_enableDirectionDetection()};
this._dropDown=new c.RadAutoCompleteBox.DropDown(p,o);
if($telerik.isIE7){var r=n.outerWidth(true),t=n.css("width");
if(t.indexOf("%")==-1){t=parseInt(t,10);
if(t!==0){n.width(t-(r-t));
}}}this._dropDown.on({itemDataBound:s._onDropDownItemDataBound,dropDownMouseUp:s._onDropDownMouseUp,dropDownItemClicked:s._onDropDownItemClicked,dropDownOpening:s._onDropDownOpening,dropDownOpened:s._onDropDownOpened,dropDownClosing:s._onDropDownClosing,dropDownClosed:s._onDropDownClosed,ShowAllClick:s._onShowAllClick,ShowAllFocus:s._onShowAllFocus},this);
},_initializeInputWidth:function(r){var n=a(this._element),q=this.get_inputElement(),p=n.find(".racTokenList"),o=n.find(".racLabel"),s=o.get(0);
if(s){var t=o.outerWidth()+j,u=p.outerWidth()-p.width(),v=n.width();
p.width(v-(t+u));
}if(!this._isInTokenMode()&&this.get_allowCustomEntry()){q.style.width="100%";
this._updateText(r);
}},_initializeODataSourceBinder:function(){var o=this.get_odataClientSettings().ODataSourceID,n=$find(o);
if(!n){var p=String.format("DataSource with id {0} was not found on the page",o);
alert(p);
}else{this._flatBinder=new c.RadODataDataSource.Binder.Flat(n,this);
this._flatBinder.initialize();
}},_initializeClientDataSource:function(){if(this._clientDataSourceID){this._clientDataSource=$find(this._clientDataSourceID);
}Sys.Application.remove_load(this._cdInitDelegate);
},_isInTokenMode:function(){return this.get_inputType()==c.RadAutoCompleteInputType.Token;
},_isInSingleSelectionMode:function(){return(!this._isInTokenMode()&&this.get_textSettings().selectionMode===0);
},_logChanges:function(){this._logEntries();
this.updateClientState();
this.get_element().value=this.get_text();
},_logEntries:function(){var o=this.get_entries(),n=o.get_count();
this._log.initialize();
for(var p=0;
p<n;
p++){this._log.logInsert(o.getEntry(p));
}},_populateDropDown:function(n,q,r,o){var p=this._dropDown,s=n.length;
if(n.length){p.populate(n,q,o);
if(r&&s>=this.get_maxResultCount()){p._addShowAllButton();
}else{p._removeShowAllButton();
}if(!this.get_enableClientFiltering()){p.open(this._getDropDownPositionInfo());
if(this._highlightFirstMatch){p.highlightNext();
}}}else{this.clear();
}},_getDropDownPositionInfo:function(){var n={automaticPosition:(this.get_dropDownPosition()==c.RadAutoCompleteDropDownPosition.Automatic),simpleTextMode:(!this._isInTokenMode()&&this.get_allowCustomEntry()),delimiter:this.get_delimiter()};
return n;
},_raiseControlEvent:function(o,p,n){a.raiseControlEvent(o,p,n);
},_raiseCancellableControlEvent:function(o,p,n){return a.raiseCancellableControlEvent(o,p,n);
},_removeEntry:function(n){var o=n.get_index();
this.get_entries()._remove(n);
if(this._postBackOnRemove){this._postback({command:"Remove",index:o});
}},_removeTextToken:function(n){this._removeToken(n);
},_removeToken:function(n){var o=n.get_token();
a(o).remove();
},_shouldApplyEmptyMessage:function(){return(this.get_entries().get_count()===0&&this.get_emptyMessage());
},_toggleEmptyMessage:function(o){var n=a(this.get_inputElement());
if(this._shouldApplyEmptyMessage()){n.val(this.get_emptyMessage());
if(n.is(":not(.racEmptyMessage)")){n.addClass("racEmptyMessage");
}}else{if(n.is(".racEmptyMessage")){n.get(0).className="racInput";
}}this._updateInputSize(o);
},_updateInputSize:function(r){var u=this,o=this._element,n=a(o),q=this.get_inputElement(),t=q.value,s=0;
if(r){if(t.length>0){q.size=t.length;
}else{if(t.length===0){q.size=i;
}}}else{var v=o.offsetHeight,p=0;
if(!this._isMaxWidthRemoved&&!this.get_showLoadingIcon()){a(q).css("maxWidth","none");
this._isMaxWidthRemoved=true;
}if(this._isInTokenMode()){q.style.width=u._dropDown._getTextWidth(t)+10+"px";
}else{if(this.get_allowCustomEntry()&&this.get_element().style.width.indexOf("%")!=-1){q.style.width="100%";
}else{n.find(".racTextToken").each(function(x,w){p+=a(w).outerWidth(true);
});
s=n.outerWidth(true)-p-a(this._loadingIcon).outerWidth(true);
if(s>0&&this.get_allowCustomEntry()){a(q).width(s);
}else{q.style.width=u._dropDown._getTextWidth(t)+10+"px";
}}}if(v!==o.offsetHeight){this._dropDown.position(this._getDropDownPositionInfo());
}}},_updateText:function(o){var n=this.get_inputElement(),p=this._getEntriesTexts();
n.value=p;
this._updateInputSize(o);
},_getIsDelimiter:function(n){var p=false,o=this.get_delimiter();
if(this._getIsDoubleSymbolDelimiter()){p=(n===o.charCodeAt(0)||n===o.charCodeAt(1));
}else{p=n===o.charCodeAt(0);
}return p;
},_getDelimiterIndex:function(q){var n=this.get_delimiter();
if(this._getIsDoubleSymbolDelimiter()){var o=q.lastIndexOf(n.charAt(0)),p=q.lastIndexOf(n.charAt(1));
return Math.max(o,p);
}return q.lastIndexOf(n.charAt(0));
},_getIsDoubleSymbolDelimiter:function(){return this.get_delimiter().length>1;
},_getDoubleCharRegExp:function(n){return new RegExp("["+n.charAt(0)+"|"+n.charAt(1)+"]");
},_onFocus:function(n){var o=this.get_inputElement();
if(a(o).is(".racEmptyMessage")){a(o).removeClass("racEmptyMessage");
o.value="";
}if(!this._isInTokenMode()){this._putCursorAtEnd(o);
}this._originalText=this.get_text();
},_putCursorAtEnd:function(o){var n=a(o);
if(o.setSelectionRange){var p=n.val().length;
o.setSelectionRange(p,p);
}else{n.val(n.val());
}},_onBlur:function(p){var s=this.get_text(),o=this._dropDown,n=this._dropDown.select(),r=this.get_inputElement();
if(!o._shouldBlurAutoComplete&&!n){return;
}if(!o._shouldBlurAutoComplete&&n&&n.get_text()!=s){return;
}this._onRequestEnd();
if(this._requestTimer){clearTimeout(this._requestTimer);
}o.close();
this._clearTokenSelection();
if(n){this._addEntryFromItem(n);
s=this.get_text();
}if(!this.get_allowCustomEntry()){r.value="";
s=this.get_text();
}if(s==this._originalText&&n){if(!o._isScroll){this._toggleEmptyMessage();
return;
}}this.get_element().value=s;
r._shouldTriggerChange=true;
a(r).trigger("change");
r._shouldTriggerChange=undefined;
if(this._isInTokenMode()){if(this.get_allowCustomEntry()&&this.get_searchString()&&!n){var q=this.createEntry(this.get_searchString());
this._addEntry(q);
}}else{if(this.get_allowCustomEntry()){this._createEntriesFromText(s);
this._updateText();
}if(s!==this._originalText){this._onTextChanged(s);
if(this._postBackOnChange){this._logChanges();
this._postback({command:"Change",text:s});
}}}this._originalText=s;
this._logChanges();
this._toggleEmptyMessage();
},_onInputCellClick:function(n){if(!this._enabled){return;
}if(this.get_inputElement().value==this.get_emptyMessage()){this.get_inputElement().value="";
}if(n.target.className!="racEditTokenInput"){this._focusInput();
}},_onKeyDown:function(u){var F=this,t=this._dropDown,q,x,y=this.get_inputElement(),D=y.value,E=D.length,G=this._isInTokenMode()?m:"racTextToken",o=a(this.get_element()).find("."+G).last(),r=function(I,H){I._appendEntryText(q.get_text(),false);
q.ensureVisible(H);
I._dropDown.position(I._getDropDownPositionInfo());
};
if(u.keyCode!==Sys.UI.Key.backspace&&u.keyCode!==Sys.UI.Key.left&&u.keyCode!==Sys.UI.Key.right&&u.keyCode!==f&&u.keyCode!==d&&this._selectedToken){this._clearTokenSelection();
}setTimeout(function(){F._updateInputSize();
},10);
switch(u.keyCode){case Sys.UI.Key.left:case Sys.UI.Key.right:if(E===0){if(this._selectedToken){var C=(u.keyCode===Sys.UI.Key.left)?a(F._selectedToken).prev():a(this._selectedToken).next();
if(F.get_enableAriaSupport()){a(F._selectedToken).removeAttr("id");
}F._clearTokenSelection();
if(C&&C.hasClass(G)){C.addClass(h);
F._selectedToken=C.get(0);
}}else{if(F._isInTokenMode()||!F.get_allowCustomEntry()){o.addClass(h);
F._selectedToken=o.get(0);
}}if(F.get_enableAriaSupport()){F._applyTokenAriaAttributes();
}}break;
case Sys.UI.Key.up:if(F.get_enableAriaSupport()){a(y).attr("aria-activedescendant",a(y).attr("id"));
}u.preventDefault();
t.highlightPrev();
q=t.get_activeItem();
if(q){r(this,false);
}break;
case Sys.UI.Key.down:if(F.get_enableAriaSupport()){a(y).attr("aria-activedescendant",a(y).attr("id"));
}if(!t.isVisible()&&E>0){F.query();
if(!F._highlightFirstMatch){return;
}}u.preventDefault();
t.highlightNext();
q=t.get_activeItem();
if(q){r(this,true);
}break;
case Sys.UI.Key.esc:if(t.isVisible()){this._appendEntryText(this._cachedSearchString,false);
t.close();
}else{y.value="";
}break;
case Sys.UI.Key.enter:var A=t.select(),w,n=a(t.get_itemsContainer()),p=n.siblings(e+l),z=p.hasClass(h);
if(F.get_enableAriaSupport()){if(!z){a(y).attr("role","textbox");
}a(y).attr("aria-expanded",z);
a(y).attr("aria-activedescendant",a(y).attr("id"));
}u.preventDefault();
if(z){F._onShowAllClick();
return;
}if(A){this._addEntryFromItem(A);
}else{var B=this.get_searchString();
if(B.length===0){return;
}if(this.get_allowCustomEntry()&&!this._isInSingleSelectionMode()){if(this._isInTokenMode()){w=this.createEntry(B);
this._addEntry(w);
}else{var v=false,s=this.get_delimiter();
D=this.get_text();
if(this._getIsDoubleSymbolDelimiter()){v=this._endsWith(D,s.charAt(0))||this._endsWith(D,s.charAt(1));
if(!v){y.value+=s.charAt(0)+" ";
}}else{y.value+=s;
}}}if(this.get_allowCustomEntry()&&!this._isInTokenMode()){this._createEntriesFromText(D);
this._toggleEmptyMessage();
this._updateText();
}}this._updateInputSize();
this.clear();
break;
case Sys.UI.Key.backspace:if(E===0){if(this._selectedToken){x=a(this._selectedToken).data()["entry"];
this._removeEntry(x);
this._selectedToken=null;
}else{if(this._isInTokenMode()||!this.get_allowCustomEntry()){o.addClass(h);
this._selectedToken=o.get(0);
}}if(F.get_enableAriaSupport()){if(F._selectedToken){F._applyTokenAriaAttributes();
}else{a(y).attr("aria-activedescendant",a(y).attr("id"));
a(y).attr("aria-expanded",false);
}}}break;
case d:if(this._selectedToken){x=a(this._selectedToken).data()["entry"];
this._removeEntry(x);
this._selectedToken=null;
if(F.get_enableAriaSupport()){a(y).attr("aria-activedescendant",a(y).attr("id"));
a(y).attr("aria-expanded",false);
}}break;
case f:if(F._isInTokenMode()&&F.get_allowCustomEntry()&&F.get_allowTokenEditing()){F._switchToEditMode(F._selectedToken);
}break;
}},_onKeyPress:function(o){var n=o.keyCode?o.keyCode:o.charCode,q=this._getIsDelimiter(n),p;
if(q&&!this._isInSingleSelectionMode()){if(!this._isInTokenMode()&&this.get_allowCustomEntry()){return;
}o.preventDefault();
var r=this.get_searchString();
if(!r||r==" "||r.length===0||!this.get_allowCustomEntry()){return;
}p=this.createEntry(r);
this._addEntry(p);
this.clear();
}},_endsWith:function(n,o){return n.indexOf(o,n.length-o.length)!==-1;
},_onKeyUp:function(p){var n=p.keyCode,u=Sys.UI.Key,s=n===u.backspace,t=n!=u.up&&n!=u.down&&n!=u.enter&&n!=u.tab&&n!=u.esc&&!s,q=false,o=this.get_delimiter(),w=this.get_text(),r;
if(o.length>1){q=this._endsWith(w,o.charAt(0))||this._endsWith(w,o.charAt(1));
}else{q=this._endsWith(w,o);
}if(t||s){if(!q){this.query();
}else{var v=this.get_searchString(n);
if(!v&&v.length===0||!this.get_allowCustomEntry()){return;
}if(v!==""){r=this.createEntry(v);
this._addEntry(r);
this.clear();
}}}},_onPaste:function(n){var o=this;
setTimeout(function(){o._updateInputSize();
o.query();
},1);
},_onRemoveLinkClick:function(n){if(!this._enabled){return;
}var o=a(n.target).closest(".racToken").data()["entry"];
this._removeEntry(o);
this._logChanges();
},_onEditInputKeyDown:function(n){if(!this._enabled){return;
}var o=a(n.target.parentElement).data()["entry"],p=a(n.target).get(0),q=a(n.target.parentElement.firstChild).get(0);
switch(n.keyCode){case Sys.UI.Key.enter:n.preventDefault();
if(p.value!=o.get_text()){o.set_text(p.value);
q.nodeValue=p.value;
}else{q.nodeValue=o.get_text();
}this._removeTokenEditInput(p);
this._logChanges();
this.get_inputElement().focus();
return false;
break;
case Sys.UI.Key.esc:q.nodeValue=o.get_text();
this._removeTokenEditInput(p);
this.get_inputElement().focus();
break;
default:return false;
}},_onEditInputBlur:function(n){if(!this._enabled||this._preventTokenBlur){return;
}var o=a(n.target.parentElement).data()["entry"],p=a(this.get_element()).find(".racEditTokenInput").get(0),q=a(n.target.parentElement.firstChild).get(0);
q.nodeValue=o.get_text();
this._removeTokenEditInput(p);
},_onTokenClick:function(o){if(!this._enabled){return;
}var n=a(o.currentTarget);
if(n.hasClass(m)){this._selectedToken=o.currentTarget;
n.addClass(h);
}},_onTokenDblClick:function(n){this._switchToEditMode(n.currentTarget);
},_switchToEditMode:function(u){if(!this._enabled){return;
}var q=a(this.get_element()).find(".racEditTokenInput.radPreventDecorate");
if(q.get(0)!==undefined){var t=q.parent(),o=a(t).data()["entry"],w;
w=a(t).contents().filter(function(){return this.nodeType==3;
});
w.nodeValue=o.get_text();
this._removeTokenEditInput(q);
}var p=document.createElement("input"),v=a(u.firstChild).get(0).nodeValue,n=a(p),s=this.get_renderMode()==c.RenderMode.Lite,r=a(u).width();
if(s){r-=a(u.firstElementChild).outerWidth(true);
}n.attr("type","text").val(v).width(r).addClass("racEditTokenInput radPreventDecorate");
if(this.get_enableAriaSupport()){n.attr("role","option");
n.attr("id",this.get_id()+"_selectedToken");
a(this.get_inputElement()).attr("aria-activedescendant",this.get_id()+"_selectedToken");
}a(u).addClass(k);
a(u.firstChild).get(0).nodeValue="";
a(u).find(".racRemoveTokenLink").before(p);
n.focus();
this._selectInputText(p,v.length);
},_removeTokenEditInput:function(n){a(n.parentElement).removeClass(k);
this._preventTokenBlur=true;
a(n).remove();
this._preventTokenBlur=false;
},_selectInputText:function(o,q){var p=0,n=q;
if(o.createTextRange){var r=o.createTextRange();
r.moveStart("character",p);
r.moveEnd("character",n);
r.select();
}else{o.setSelectionRange(p,n);
}},_onDropDownItemDataBound:function(n){this._raiseControlEvent(this,"dropDownItemDataBound",n);
},_onDropDownOpening:function(n){var o=this._raiseCancellableControlEvent(this,"dropDownOpening",n);
n.set_cancel(o);
},_onDropDownOpened:function(p){var q=this,n=a(q._dropDown.get_itemsContainer()),o=n.siblings(e+l);
if(q.get_enableAriaSupport()){a(q.get_inputElement()).attr("role","listbox");
a(q.get_inputElement()).attr("aria-expanded",true);
n.find("li").attr("role","option");
if(q._dropDown._hasShowAllButton){o.attr({role:"option","aria-label":q._showAllResultsText,id:q.get_id()+"_showAll"});
}}this._raiseControlEvent(this,"dropDownOpened",p);
},_onDropDownClosing:function(n){var o=this._raiseCancellableControlEvent(this,"dropDownClosing",n);
n.set_cancel(o);
},_onDropDownClosed:function(o){var n=a(this.get_inputElement());
if(this.get_enableAriaSupport()){n.attr({role:"textbox","aria-activedescendant":n.attr("id"),"aria-expanded":false});
}this._raiseControlEvent(this,"dropDownClosed",o);
},_onDropDownMouseUp:function(n){this._focusInput();
},_onDropDownItemClicked:function(n){var o=n.get_item(),p=this;
if(o){setTimeout(function(){p._addEntryFromItem(o);
p._updateInputSize();
},10);
}},_onShowAllClick:function(n){var o=this.get_searchString();
if(this.get_enableClientFiltering()){this._dropDown.filterItems(o,true);
this._dropDown.open(this._getDropDownPositionInfo());
}else{this._requestItems(o,true);
}},_onShowAllFocus:function(o){var q=this,n=a(q.get_inputElement()),p=q.get_id()+"_showAll";
if(q.get_enableAriaSupport()){n.attr({"aria-activedescendant":p});
}this._appendEntryText(this._cachedSearchString,false);
},_onEntryAdding:function(n){var o=a.extendEventArgs(new Sys.CancelEventArgs(),{entry:n});
return this._raiseCancellableControlEvent(this,"entryAdding",o);
},_onEntryAdded:function(n){this._raiseControlEvent(this,"entryAdded",a.extendEventArgs({},{entry:n}));
},_onEntryRemoving:function(n){var o=a.extendEventArgs(new Sys.CancelEventArgs(),{entry:n});
return this._raiseCancellableControlEvent(this,"entryRemoving",o);
},_onEntryRemoved:function(n){this._raiseControlEvent(this,"entryRemoved",a.extendEventArgs({},{entry:n}));
},_onTextChanged:function(n){this._raiseControlEvent(this,"textChanged",a.extendEventArgs({},{text:n}));
},_postback:function(n){if(!this._postBackReference){return;
}var p=this._serializePostbackCommand(n),o=this._postBackReference.replace("arguments",p);
eval(o);
},_serializePostbackCommand:function(n){var o=b.serialize(n);
return encodeURIComponent(o.replace(/'/g,"&squote"));
},get_requestDelay:function(){return this._requestDelay;
},set_requestDelay:function(n){this._requestDelay=n;
},get_attributes:function(){return this._attributes;
},set_attributes:function(n){this._attributes._load(n);
},_getChildren:function(){this._ensureChildControls();
return this._children;
},get_entries:function(){return this._getChildren();
},set_enabled:function(p){var n=a(this.get_inputElement()),o=a(this._element).find(".racTokenList");
this._enabled=p;
if(!p){n.attr("disabled","disabled");
}else{n.removeAttr("disabled");
}o.toggleClass("racDisabled",!p);
if(this.get_enableAriaSupport()){n.attr("aria-disabled",!p);
}this.updateClientState();
},get_enabled:function(){return this._enabled;
},get_inputElement:function(){if(!this._inputElement){this._inputElement=a(this.get_element()).find(".racInput").get(0);
}return this._inputElement;
},get_entryData:function(){return this._entryData;
},get_dropDownItemData:function(){return this._dropDownItemData;
},get_text:function(){var n=this.get_inputElement().value;
if(!this._isInTokenMode()&&this.get_allowCustomEntry()){return n;
}else{return this._getEntriesTexts()+n;
}},get_searchString:function(){var o,r=this.get_text(),n=this.get_delimiter(),q=this._getDoubleCharRegExp(n),s=[];
if(!this._isInSingleSelectionMode()){if(!this._getIsDoubleSymbolDelimiter()){o=this.get_text().split(n);
}else{if(!this.get_allowCustomEntry()){o=this.get_inputElement().value;
}else{o=this.get_text().split(q);
}}}else{o=this.get_text().split(q);
}for(var p=0;
p<o.length;
p++){if(o[p]!==null){s.push(o[p]);
}}if(!this._isInSingleSelectionMode()){if(s[s.length-1]!==undefined){return s[s.length-1].trimStart();
}else{return o;
}}return r;
},get_bindingMode:function(){return this._bindingMode;
},get_dropDownElement:function(){return this._dropDown._element;
},set_entryData:function(n){this._entryData=n;
},set_dropDownItemData:function(n){this._dropDownItemData=n;
},get_emptyMessage:function(){return this._emptyMessage;
},set_emptyMessage:function(n){if(this._emptyMessage!==n){this._emptyMessage=n;
}},get_webServiceSettings:function(){return this._webServiceSettings;
},get_flatModel:function(){var n=this.get_odataClientSettings();
return c.RadODataDataSource.Binder.Flat.Model(n);
},set_webServiceSettings:function(o){var n=b.deserialize(o);
this._webServiceSettings=new c.WebServiceSettings(n);
},get_isUsingODataSource:function(){return this._odataClientSettings!==null;
},get_tokensSettings:function(){return this._tokensSettings;
},set_tokensSettings:function(n){this._tokensSettings=Sys.Serialization.JavaScriptSerializer.deserialize(n);
},get_allowTokenEditing:function(){if(!this._tokensSettings.allowTokenEditing){this._tokensSettings.allowTokenEditing=false;
}return this._tokensSettings.allowTokenEditing;
},set_allowTokenEditing:function(n){this._tokensSettings.allowTokenEditing=n;
},get_textSettings:function(){return this._textSettings;
},set_textSettings:function(n){this._textSettings=Sys.Serialization.JavaScriptSerializer.deserialize(n);
},get_expandAnimation:function(){return this._expandAnimation;
},set_expandAnimation:function(o){var n=b.deserialize(o);
this._expandAnimation=new c.AnimationSettings(n);
if(this._dropDown&&this._dropDown._dropDown){this._dropDown._dropDown.set_expandAnimation(this._expandAnimation);
}},get_collapseAnimation:function(){return this._collapseAnimation;
},set_collapseAnimation:function(o){var n=b.deserialize(o);
this._collapseAnimation=new c.AnimationSettings(n);
if(this._dropDown&&this._dropDown._dropDown){this._dropDown._dropDown.set_collapseAnimation(this._collapseAnimation);
}},get_enableScreenBoundaryDetection:function(){return this._enableScreenBoundaryDetection;
},set_enableScreenBoundaryDetection:function(n){this._enableScreenBoundaryDetection=n;
if(this._dropDown&&this._dropDown._dropDown){this._dropDown._dropDown.set_enableScreenBoundaryDetection(n);
}},get_enableDirectionDetection:function(){return this._enableDirectionDetection;
},set_enableDirectionDetection:function(n){this._enableDirectionDetection=n;
if(this._dropDown&&this._dropDown._dropDown){this._dropDown._dropDown.set_enableDirectionDetection(n);
}},repaint:function(){this._initializeInputWidth(true);
}};
a.registerControlProperties(c.RadAutoCompleteBox,{filter:0,inputType:0,dropDownPosition:0,allowCustomEntry:false,delimiter:";",odataClientSettings:null,enableClientFiltering:false,minFilterLength:1,maxResultCount:-1,showLoadingIcon:true,isCaseSensitive:false,dropDownWidth:"",dropDownHeight:"",enableAriaSupport:false});
a.registerControlEvents(c.RadAutoCompleteBox,["load","dropDownItemDataBound","dropDownOpening","dropDownOpened","dropDownClosing","dropDownClosed","entryAdding","entryAdded","entryRemoving","entryRemoved","textChanged","requesting","requested","requestFailed"]);
c.RadAutoCompleteBox.registerClass("Telerik.Web.UI.RadAutoCompleteBox",c.RadWebControl);
})($telerik.$);
(function(b,a){var c=b.RadAutoCompleteBox,d=".",h="racShowAll",g="RadAutoCompleteBoxPopup",f="racList",e="racItem";
c.DropDown=function(j,i){a.observable(this);
this._element=j;
this._popup=null;
this._items=[];
this._activeElement=null;
this._shouldBlurAutoComplete=true;
this._isScroll=false;
this._clientTemplate=null;
this._enableClientFiltering=i.enableClientFiltering;
this._filter=i.filter;
this._maxResultCount=i.maxResultCount;
this._matchesCount=0;
this._isCaseSensitive=i.isCaseSensitive;
this._showAllResultsText=i.showAllResultsText;
this._highlightFirstMatch=i.highlightFirstMatch;
this._width=i.width;
this._height=i.height;
this._parent=i.anchor;
this._expandAnimation=i.expandAnimation;
this._collapseAnimation=i.collapseAnimation;
this._enableScreenBoundaryDetection=i.enableScreenBoundaryDetection;
this._enableDirectionDetection=i.enableDirectionDetection;
this._dropDown=null;
this._hasShowAllButton=false;
this.init();
};
c.DropDown.prototype={get_itemsContainer:function(){var j=this.get_popup(),i=a(j).children(d+f).get(0);
return i;
},get_popup:function(){if(!this._popup){this._popup=a(this._element).find(d+g).get(0);
}return this._popup;
},get_activeItem:function(){var i=this._activeElement;
return i?i._item:null;
},getItem:function(i){return this._items[i];
},get_items:function(){return this._items;
},get_clientTemplate:function(){return this._clientTemplate;
},set_clientTemplate:function(i){this._clientTemplate=i;
},init:function(){var i=this;
this._initializeDropDown();
a(this.get_popup()).on({mousedown:function(j){i._shouldBlurAutoComplete=false;
},mouseup:function(j){i._shouldBlurAutoComplete=true;
i._onDropDownMouseUp(j);
},click:function(j){i._onShowAllClick(j);
}},d+h);
a(this.get_itemsContainer()).on({click:function(j){i._onDropDownClick(j);
i.close();
},mousedown:function(j){i._shouldBlurAutoComplete=false;
},mouseup:function(j){i._shouldBlurAutoComplete=true;
i._onDropDownMouseUp(j);
},scroll:function(j){if($telerik.isIE){i._isScroll=true;
setTimeout(function(){i._shouldBlurAutoComplete=true;
},0);
i._onDropDownMouseUp(j);
}},mouseover:function(j){i._onDropDownHover(j);
},mouseout:function(j){i._onDropDownOut(j);
}});
},_initializeDropDown:function(){this._dropDown=new b.DropDown(this._element,{direction:2,expandAnimation:this._expandAnimation,collapseAnimation:this._collapseAnimation,enableScreenBoundaryDetection:this._enableScreenBoundaryDetection,anchor:this._parent,width:this._width||"auto",height:this._height,enableDirectionDetection:this._enableDirectionDetection});
this._dropDown.on({opening:this._onDropDownOpening,opened:this._onDropDownOpened,closing:this._onDropDownClosing,closed:this._onDropDownClosed,reflowing:this._onDropDownReflowing,reflowed:this._onDropDownReflowed,collapseAnimationEnded:this._onCollapseAnimationEnded},this);
this._dropDown.initialize();
this._dropDown.updateSize();
},dispose:function(){this.disposeObservable();
this._positionInfo=null;
if(this._dropDown){this._dropDown.dispose();
this._dropDown=null;
}a(document).add(this.get_itemsContainer()).off();
this.clear();
a(this._element).remove();
this._element=null;
},populate:function(j,l,k){var m=this,i=a(this.get_itemsContainer()).find(d+e);
if(!l){this.clear();
}a.each(j,function(p,n){var q=new c.DropDownItem(n,k);
m.trigger("itemDataBound",a.extendEventArgs({},{item:q,dataItem:n}));
if(m._clientTemplate){q._renderedClientTemplate=b.TemplateRenderer.renderTemplate(n,m,q);
}else{if(l){var o=i.get(p);
q._setElement(o);
o._item=q;
}}m._items.push(q);
});
if(!l){this.render();
}},clear:function(){this._activeElement=null;
if(this._enableClientFiltering){this.hideItems();
return;
}var k=this.get_items();
for(var j=0;
j<k.length;
j++){k[j].dispose();
}this._items=[];
this._removeShowAllButton();
a(this.get_itemsContainer()).empty();
},open:function(j){var i=this._dropDown;
this._positionInfo=j;
if(i.isVisible()){i.resolveScreenBoundaries();
i.position();
}else{i.show();
}this.position(j);
},position:function(k){var i=a(this._element),j=this._getDropDownHorizontalOffset(k);
i.css({left:j+"px"});
},select:function(){var j=this.get_activeItem(),i=a.extendEventArgs(new Sys.CancelEventArgs(),{item:j});
this.trigger("itemSelecting",i);
if(i.get_cancel()){return;
}this.trigger("itemSelected",a.extendEventArgs({},{item:j}));
return j;
},close:function(){this._toggleShowAllFocus(false);
this._dropDown.hide();
},filterItems:function(k,l){var j=true;
var i=function(n,q){var s=this,p=s._maxResultCount,o=s._isCaseSensitive?n.get_text():n.get_text().toLowerCase(),r=o.indexOf(q),m=s._filter===0?r!==-1:r===0;
if(l){s._removeShowAllButton();
}else{s._addShowAllButton();
}if(m){s._matchesCount+=1;
}if(!l&&s._matchesCount>p){m=false;
}if(m===true){a(n._element).show();
if(s._highlightFirstMatch&&j){s.updateActiveItem(s.get_activeItem(),n);
j=false;
}}else{if(m===false){a(n._element).hide();
if(s._activeElement===n._element){s.toggleHighlight(n,false);
}}}};
this._matchesCount=0;
if(!this._isCaseSensitive){k=k.toLowerCase();
}this.process(0,k,i);
},hideItems:function(){var i=function(j){a(j._element).hide();
};
this.process(0,"",i);
},process:function(l,k,i){var m=this,j=this._items;
clearTimeout(this._filterTimer);
this._filterTimer=setTimeout(function(){var n=l,p=j.length,q=new Date().getTime(),o;
while(n<p&&(new Date().getTime()-q)<50){o=j[n];
i.apply(m,[o,k]);
n++;
}if(n<p){m.process(n,k,i);
}},10);
},highlightNext:function(){this.updateActiveItem(this.get_activeItem(),this._getNextItem(1));
},highlightPrev:function(){this.updateActiveItem(this.get_activeItem(),this._getNextItem(-1));
},render:function(){var i=a(this.get_itemsContainer());
a.each(this._items,function(j,k){i.append(k.render());
});
},updateActiveItem:function(j,i){var k=(!i)&&this._hasShowAllButton;
if(k){this.trigger("ShowAllFocus");
}this._toggleShowAllFocus(k);
this.toggleHighlight(j,false);
this.toggleHighlight(i,true);
},toggleHighlight:function(i,j){if(i){i.set_highlight(j);
this._activeElement=j?i.get_element():null;
}},isVisible:function(){return this._dropDown.isVisible();
},_onDropDownOpening:function(j){var i=new Sys.CancelEventArgs();
this.trigger("dropDownOpening",i);
j.set_cancel(i.get_cancel());
},_onDropDownOpened:function(){var i=new Sys.EventArgs();
this._adjustChildListElementHeight();
this.trigger("dropDownOpened",i);
},_onDropDownClosing:function(j){var i=new Sys.CancelEventArgs();
this.trigger("dropDownClosing",i);
j.set_cancel(i.get_cancel());
},_onDropDownClosed:function(){var i=new Sys.EventArgs();
this.toggleHighlight(this.get_activeItem(),false);
this.trigger("dropDownClosed",i);
},_onDropDownReflowing:function(){a(this.get_itemsContainer()).height("");
},_onDropDownReflowed:function(){this.position(this._positionInfo);
this._adjustChildListElementHeight();
},_onCollapseAnimationEnded:function(){this.clear();
a(this.get_itemsContainer()).height("");
},_addShowAllButton:function(){var i=a(this.get_itemsContainer());
if(i.siblings(d+h).length===0){i.after("<div class='"+h+"'><span>"+this._showAllResultsText+"</span></div>");
}this._hasShowAllButton=true;
this._adjustChildListElementHeight();
},_removeShowAllButton:function(){var i=a(this.get_itemsContainer()),j=i.siblings(d+h);
if(j.length>0){j.remove();
}this._hasShowAllButton=false;
this._adjustChildListElementHeight();
},_toggleShowAllFocus:function(k){var i=a(this.get_itemsContainer()),j=i.siblings(d+h);
j.toggleClass("racFocused",k);
},_adjustChildListElementHeight:function(){var j=a(this.get_popup());
if(j[0].style.height===""){return;
}var l=j.height(),k=j.find(d+h),i=a(this.get_itemsContainer()),m=k.outerHeight(true),n;
if(l>0){n=l-m;
i.css("height",n);
}},_onDropDownHover:function(i){var j=this._extractItemFromDomElement(i.target);
this.updateActiveItem(this.get_activeItem(),j);
},_onDropDownOut:function(i){this.toggleHighlight(this.get_activeItem(),false);
},_onDropDownClick:function(j){var k=this._extractItemFromDomElement(j.target);
this.updateActiveItem(this.get_activeItem(),k);
this.select();
var i=a.extendEventArgs(new Sys.EventArgs(),{item:k});
this.trigger("dropDownItemClicked",i);
},_onDropDownMouseUp:function(i){this.trigger("dropDownMouseUp",null);
},_onShowAllClick:function(i){i.preventDefault();
this.trigger("ShowAllClick",i);
},_extractItemFromDomElement:function(i){while(i.nodeType!==9){if(i._item&&a(i).is(d+e)){return i._item;
}i=i.parentNode;
}return null;
},_getDropDownHorizontalOffset:function(s){var j=a(this._parent),i=a(this._element),q=j.offset().left,k=s&&s.automaticPosition,o=k?this._getInputLastDelimiterOffset(s):j.offset().left,r=q+j.width(),m=i.find(d+g).outerWidth(true)||i.width(),t=o+m-r,n=j.find(".racLabel").outerWidth();
var p=this._dropDown._getHiddenElementOffsetParent(this._element);
var l=$telerik.getComputedStyle(document.body,"position",null);
q+=n;
if(!k&&n){o+=n;
}if(t>0){o-=t;
}if(o<q+10){o=q;
}if(p!==document.body||l==="relative"||l==="absolute"){o-=a(p).offset().left;
}return o;
},_getInputLastDelimiterOffset:function(n){var m=this._parent,i=a(m).find(".racInput"),l=i.offset().left;
if(n&&n.simpleTextMode){var k=i.val(),j=7;
k=k.substring(0,k.lastIndexOf(n.delimiter));
l+=this._getTextWidth(k)+j;
}return l;
},_getTextWidth:function(j){var i=a(this._parent).find(".racInput")[0],k=this._createTextSizingDiv(i),l;
document.body.appendChild(k);
k.style.width="0";
k.innerHTML=$telerik.htmlEncode(j);
k.style.width="auto";
l=k.offsetWidth;
setTimeout(function(){document.body.removeChild(k);
},0);
return l;
},_createTextSizingDiv:function(n){var o=document.createElement("div"),j=["font-size","font-family","font-weight","font-variant","font-style","text-transform"],k=["fontSize","fontFamily","fontWeight","fontVariant","fontStyle","textTransform"];
o.style.position="absolute";
o.style.display="block";
o.style.visibility="hidden";
if($telerik.getComputedStyle(n,j[0],null)===null){j=k;
}for(var l=0,m=j.length;
l<m;
l++){o.style[k[l]]=$telerik.getComputedStyle(n,j[l],null);
}return o;
},_getNextItem:function(l){var k=a(this.get_itemsContainer()).children("li:visible"),i=a(this._activeElement),j;
if(i.length===0||!i.is(":visible")){j=(l==1)?k.first(":visible"):k.last(":visible");
}else{j=(l==1)?i.nextAll(":visible").first():i.prevAll(":visible").first();
}if(j.length!==0){return j[0]._item;
}return null;
}};
b.RadAutoCompleteBox.DropDown.registerClass("Telerik.Web.UI.RadAutoCompleteBox.DropDown");
})(Telerik.Web.UI,$telerik.$);
(function(b,a){b.RadAutoCompleteBox.DropDownItem=function(c,d){this._text="";
this._value="";
this._template=null;
this._element=null;
this._attributes=null;
this._load(c,d);
};
b.RadAutoCompleteBox.DropDownItem.prototype={_load:function(c,d){if(d){if(typeof(c[d.dataTextField])!="undefined"){this._text=c[d.dataTextField];
}if(typeof(c[d.dataValueField])!="undefined"&&c.Value!==""){this._value=c[d.dataValueField];
}}else{this._text=c.text||c.Text;
this._value=c.value||c.Value;
}if(c.Attributes){this.get_attributes()._load(c.Attributes);
}},_renderBegingTag:function(c){c[c.length]="<li class='racItem";
if(this._renderedClientTemplate){c[c.length]=" racTemplate";
}c[c.length]="'>";
},_renderBody:function(c){if(this._renderedClientTemplate){c[c.length]=this._renderedClientTemplate;
}else{c[c.length]=this.get_text();
}},_renderEndTag:function(c){c[c.length]="</li>";
},_setElement:function(c){this._element=c;
},dispose:function(){this._element._item=null;
this._element=null;
},render:function(){if(!this._element){var c=[];
this._renderBegingTag(c);
this._renderBody(c);
this._renderEndTag(c);
this._element=a(c.join("")).get(0);
}this._element._item=this;
return this._element;
},get_text:function(){return this._text;
},get_value:function(){return this._value;
},get_attributes:function(){if(!this._attributes){this._attributes=new b.AutoCompleteBoxAttributeCollection(this);
}return this._attributes;
},set_highlight:function(c){a(this._element).toggleClass("racItemHovered",c);
},get_element:function(){return this._element;
},ensureVisible:function(c){if(!this._getIsVisible()){this.scrollIntoView(c);
}},_getIsVisible:function(){var d=this.get_element(),e=this._getScrollableElement(),f=d.offsetTop,c=f+d.offsetHeight;
return f>=e.scrollTop&&(c-e.scrollTop)<=e.offsetHeight;
},_getScrollableElement:function(){return this.get_element().parentNode;
},scrollIntoView:function(c){var d=this.get_element(),f=d.offsetTop,e=this._getScrollableElement();
if(c){f+=d.offsetHeight-e.offsetHeight;
}e.scrollTop=f;
},get_clientTemplate:function(){return null;
}};
b.RadAutoCompleteBox.DropDownItem.registerClass("Telerik.Web.UI.RadAutoCompleteBox.DropDownItem");
})(Telerik.Web.UI,$telerik.$);
(function(b,a){Type.registerNamespace("Telerik.Web.UI");
b.AutoCompleteBoxEntryCollection=function(c){this._array=[];
this._owner=c;
};
b.AutoCompleteBoxEntryCollection.prototype={add:function(c){var d=this._owner;
this._add(c);
d._logChanges();
if(!d._isInTokenMode()&&d.get_allowCustomEntry()){d._updateText();
}},clear:function(){var c=this._owner;
this._array=[];
c._logChanges();
a(c.get_element()).find(".racToken, .racTextToken").remove();
if(!c._isInTokenMode()){c._updateText();
}c._toggleEmptyMessage();
},insert:function(d,c){Array.insert(this._array,d,c);
c.set_parent(this._owner);
},remove:function(c){var d=this._owner;
this._remove(c);
d._logChanges();
if(!d._isInTokenMode()&&d.get_allowCustomEntry()){d._updateText();
}d._toggleEmptyMessage();
},get_count:function(){return this._array.length;
},getEntry:function(c){return this._array[c];
},indexOf:function(c){for(var d=0,e=this._array.length;
d<e;
d++){if(this._array[d]===c){return d;
}}return -1;
},forEach:function(e){for(var d=0,c=this.get_count();
d<c;
d++){e(this._array[d]);
}},toArray:function(){return this._array.slice(0);
},_add:function(c){var f=this._owner,d=this._array.length,e=f._isInTokenMode();
if(e&&f._onEntryAdding(c)){f.get_inputElement().value="";
return;
}if(f._isInSingleSelectionMode()){this._array=[];
a(f.get_element()).find(".racTextToken").remove();
d=0;
}this.insert(d,c);
if(e){f._addToken(c);
f._onEntryAdded(c);
}else{if(!f.get_allowCustomEntry()){f._addTextToken(c);
}}},_remove:function(c){var e=this._owner,d=e._isInTokenMode();
if(d&&e._onEntryRemoving(c)){return;
}Array.remove(this._array,c);
c.set_parent(null);
c._control=null;
if(d){e._removeToken(c);
e._onEntryRemoved(c);
}else{if(!e.get_allowCustomEntry()){e._removeTextToken(c);
}}}};
b.AutoCompleteBoxEntryCollection.registerClass("Telerik.Web.UI.AutoCompleteBoxEntryCollection");
})(Telerik.Web.UI,$telerik.$);
(function(b,a){Type.registerNamespace("Telerik.Web.UI");
b.AutoCompleteBoxEntry=function(){b.AutoCompleteBoxEntry.initializeBase(this);
this._parent=null;
this._itemData={};
this._text="";
this._value="";
this._tokenElement=null;
this._attributes=null;
};
b.AutoCompleteBoxEntry.prototype={_initialize:function(c,d){this._loadItemData(c);
this._parent=d;
},_loadItemData:function(c){if(typeof(c.text)!="undefined"){this.set_text(c.text);
}if(typeof(c.value)!="undefined"&&c.value!==""){this.set_value(c.value);
}if(c.attributes){this.get_attributes()._load(c.attributes);
}},_renderToken:function(){var c=[];
c[c.length]="<span class='racToken'>";
c[c.length]=$telerik.htmlEncode(this.get_text());
c[c.length]="<a class='racRemoveTokenLink' title='"+this._parent._removeTokenTitle+"' ></a>";
c[c.length]="</span>";
return c.join("");
},_renderTextToken:function(){var c=[],d=this._parent;
c[c.length]="<span class='racTextToken'>";
c[c.length]=$telerik.htmlEncode(this.get_text());
if(!d._isInSingleSelectionMode()){c[c.length]=d.get_delimiter().charAt(0);
}c[c.length]=" </span>";
return c.join("");
},get_attributes:function(){if(!this._attributes){this._attributes=new b.AutoCompleteBoxAttributeCollection(this);
}return this._attributes;
},_getData:function(){var c={text:this.get_text(),value:this.get_value()};
if(this.get_attributes().get_count()>0){c.attributes=this.get_attributes()._data;
}return c;
},_getHierarchicalIndex:function(){return this.get_index();
},get_index:function(){if(!this.get_parent()){return -1;
}return this.get_parent()._getChildren().indexOf(this);
},_setSelected:function(d){var c=this.get_token();
if(c){a(c).toggleClass("racFocused",d);
}}};
a.registerControlProperties(b.AutoCompleteBoxEntry,{token:null,parent:null,text:"",value:""});
b.AutoCompleteBoxEntry.registerClass("Telerik.Web.UI.AutoCompleteBoxEntry");
})(Telerik.Web.UI,$telerik.$);
