(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.core",["jquery"],l);
}(function(){var k={id:"core",name:"Core",category:"framework",description:"The core of the Kendo framework."};
(function(l,aZ,aV){var ag=aZ.kendo=aZ.kendo||{cultures:{}},N=l.extend,E=l.each,Z=l.isArray,aD=l.proxy,ao=l.noop,ak=Math,aP,ad=aZ.JSON||{},aO={},aA=/%/,P=/\{(\d+)(:[^\}]+)?\}/g,t=/(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+(?:\.?)\d*)px\s*(\d+)?/i,ar=/^(\+|-?)\d+(\.?)\d*$/,Q="function",aN="string",aq="number",at="object",ap="null",s="boolean",aW="undefined",W={},aJ={},aM=[].slice;
ag.version="2016.1.218".replace(/^\s+|\s+$/g,"");
function u(){}u.extend=function(a6){var a3=function(){},a5,a8=this,a7=a6&&a6.init?a6.init:function(){a8.apply(this,arguments);
},a4;
a3.prototype=a8.prototype;
a4=a7.fn=a7.prototype=new a3();
for(a5 in a6){if(a6[a5]!=null&&a6[a5].constructor===Object){a4[a5]=N(true,{},a3.prototype[a5],a6[a5]);
}else{a4[a5]=a6[a5];
}}a4.constructor=a7;
a7.extend=a8.extend;
return a7;
};
u.prototype._initOptions=function(a3){this.options=B({},this.options,a3);
};
var ab=ag.isFunction=function(a3){return typeof a3==="function";
};
var aC=function(){this._defaultPrevented=true;
};
var aa=function(){return this._defaultPrevented===true;
};
var au=u.extend({init:function(){this._events={};
},bind:function(a3,a7,bb){var bd=this,a9,a4=typeof a3===aN?[a3]:a3,ba,bc,a6,a8=typeof a7===Q,a5;
if(a7===aV){for(a9 in a3){bd.bind(a9,a3[a9]);
}return bd;
}for(a9=0,ba=a4.length;
a9<ba;
a9++){a3=a4[a9];
a6=a8?a7:a7[a3];
if(a6){if(bb){bc=a6;
a6=function(){bd.unbind(a3,a6);
bc.apply(bd,arguments);
};
a6.original=bc;
}a5=bd._events[a3]=bd._events[a3]||[];
a5.push(a6);
}}return bd;
},one:function(a3,a4){return this.bind(a3,a4,true);
},first:function(a3,a7){var bb=this,a9,a4=typeof a3===aN?[a3]:a3,ba,a6,a8=typeof a7===Q,a5;
for(a9=0,ba=a4.length;
a9<ba;
a9++){a3=a4[a9];
a6=a8?a7:a7[a3];
if(a6){a5=bb._events[a3]=bb._events[a3]||[];
a5.unshift(a6);
}}return bb;
},trigger:function(a4,a3){var a8=this,a5=a8._events[a4],a6,a7;
if(a5){a3=a3||{};
a3.sender=a8;
a3._defaultPrevented=false;
a3.preventDefault=aC;
a3.isDefaultPrevented=aa;
a5=a5.slice();
for(a6=0,a7=a5.length;
a6<a7;
a6++){a5[a6].call(a8,a3);
}return a3._defaultPrevented===true;
}return false;
},unbind:function(a3,a5){var a7=this,a4=a7._events[a3],a6;
if(a3===aV){a7._events={};
}else{if(a4){if(a5){for(a6=a4.length-1;
a6>=0;
a6--){if(a4[a6]===a5||a4[a6].original===a5){a4.splice(a6,1);
}}}else{a7._events[a3]=[];
}}}return a7;
}});
function v(a4,a6){if(a6){return"'"+a4.split("'").join("\\'").split('\\"').join('\\\\\\"').replace(/\n/g,"\\n").replace(/\r/g,"\\r").replace(/\t/g,"\\t")+"'";
}else{var a3=a4.charAt(0),a5=a4.substring(1);
if(a3==="="){return"+("+a5+")+";
}else{if(a3===":"){return"+$kendoHtmlEncode("+a5+")+";
}else{return";"+a4+";$kendoOutput+=";
}}}}var r=/^\w+/,G=/\$\{([^}]*)\}/g,H=/\\\}/g,y=/__CURLY__/g,I=/\\#/g,aK=/__SHARP__/g,a2=["","0","00","000","0000"];
aP={paramName:"data",useWithBlock:true,render:function(a7,a3){var a5,a6,a4="";
for(a5=0,a6=a3.length;
a5<a6;
a5++){a4+=a7(a3[a5]);
}return a4;
},compile:function(bc,a8){var bb=N({},this,a8),a9=bb.paramName,a3=a9.match(r)[0],bd=bb.useWithBlock,a6="var $kendoOutput, $kendoHtmlEncode = kendo.htmlEncode;",a5,ba,a7;
if(ab(bc)){return bc;
}a6+=bd?"with("+a9+"){":"";
a6+="$kendoOutput=";
ba=bc.replace(H,"__CURLY__").replace(G,"#=$kendoHtmlEncode($1)#").replace(y,"}").replace(I,"__SHARP__").split("#");
for(a7=0;
a7<ba.length;
a7++){a6+=v(ba[a7],a7%2===0);
}a6+=bd?";}":";";
a6+="return $kendoOutput;";
a6=a6.replace(aK,"#");
try{a5=new Function(a3,a6);
a5._slotCount=Math.floor(ba.length/2);
return a5;
}catch(a4){throw new Error(ag.format("Invalid template:'{0}' Generated code:'{1}'",bc,a6));
}}};
function aw(a5,a3,a4){a5=a5+"";
a3=a3||2;
a4=a3-a5.length;
if(a4){return a2[a3].substring(0,a4)+a5;
}return a5;
}(function(){var a3=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a4,a5,a6={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},a8,ba={}.toString;
if(typeof Date.prototype.toJSON!==Q){Date.prototype.toJSON=function(){var bb=this;
return isFinite(bb.valueOf())?aw(bb.getUTCFullYear(),4)+"-"+aw(bb.getUTCMonth()+1)+"-"+aw(bb.getUTCDate())+"T"+aw(bb.getUTCHours())+":"+aw(bb.getUTCMinutes())+":"+aw(bb.getUTCSeconds())+"Z":null;
};
String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf();
};
}function a7(bb){a3.lastIndex=0;
return a3.test(bb)?'"'+bb.replace(a3,function(bc){var bd=a6[bc];
return typeof bd===aN?bd:"\\u"+("0000"+bc.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+bb+'"';
}function a9(be,bb){var bc,bd,bj,bf,bg=a4,bh,bk=bb[be],bi;
if(bk&&typeof bk===at&&typeof bk.toJSON===Q){bk=bk.toJSON(be);
}if(typeof a8===Q){bk=a8.call(bb,be,bk);
}bi=typeof bk;
if(bi===aN){return a7(bk);
}else{if(bi===aq){return isFinite(bk)?String(bk):ap;
}else{if(bi===s||bi===ap){return String(bk);
}else{if(bi===at){if(!bk){return ap;
}a4+=a5;
bh=[];
if(ba.apply(bk)==="[object Array]"){bf=bk.length;
for(bc=0;
bc<bf;
bc++){bh[bc]=a9(bc,bk)||ap;
}bj=bh.length===0?"[]":a4?"[\n"+a4+bh.join(",\n"+a4)+"\n"+bg+"]":"["+bh.join(",")+"]";
a4=bg;
return bj;
}if(a8&&typeof a8===at){bf=a8.length;
for(bc=0;
bc<bf;
bc++){if(typeof a8[bc]===aN){bd=a8[bc];
bj=a9(bd,bk);
if(bj){bh.push(a7(bd)+(a4?": ":":")+bj);
}}}}else{for(bd in bk){if(Object.hasOwnProperty.call(bk,bd)){bj=a9(bd,bk);
if(bj){bh.push(a7(bd)+(a4?": ":":")+bj);
}}}}bj=bh.length===0?"{}":a4?"{\n"+a4+bh.join(",\n"+a4)+"\n"+bg+"}":"{"+bh.join(",")+"}";
a4=bg;
return bj;
}}}}}if(typeof ad.stringify!==Q){ad.stringify=function(be,bc,bd){var bb;
a4="";
a5="";
if(typeof bd===aq){for(bb=0;
bb<bd;
bb+=1){a5+=" ";
}}else{if(typeof bd===aN){a5=bd;
}}a8=bc;
if(bc&&typeof bc!==Q&&(typeof bc!==at||typeof bc.length!==aq)){throw new Error("JSON.stringify");
}return a9("",{"":be});
};
}}());
(function(){var a5=/dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|HH|H|hh|h|mm|m|fff|ff|f|tt|ss|s|zzz|zz|z|"[^"]*"|'[^']*'/g,bj=/^(n|c|p|e)(\d*)$/i,bd=/(\\.)|(['][^']*[']?)|(["][^"]*["]?)/g,a4=/\,/g,a6="",bg=".",a3=",",bi="#",bl="0",bf="??",a7="en-US",be={}.toString;
ag.cultures["en-US"]={name:a7,numberFormat:{pattern:["-n"],decimals:2,",":",",".":".",groupSize:[3],percent:{pattern:["-n %","n %"],decimals:2,",":",",".":".",groupSize:[3],symbol:"%"},currency:{name:"US Dollar",abbr:"USD",pattern:["($n)","$n"],decimals:2,",":",",".":".",groupSize:[3],symbol:"$"}},calendars:{standard:{days:{names:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],namesAbbr:["Sun","Mon","Tue","Wed","Thu","Fri","Sat"],namesShort:["Su","Mo","Tu","We","Th","Fr","Sa"]},months:{names:["January","February","March","April","May","June","July","August","September","October","November","December"],namesAbbr:["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]},AM:["AM","am","AM"],PM:["PM","pm","PM"],patterns:{d:"M/d/yyyy",D:"dddd, MMMM dd, yyyy",F:"dddd, MMMM dd, yyyy h:mm:ss tt",g:"M/d/yyyy h:mm tt",G:"M/d/yyyy h:mm:ss tt",m:"MMMM dd",M:"MMMM dd",s:"yyyy'-'MM'-'ddTHH':'mm':'ss",t:"h:mm tt",T:"h:mm:ss tt",u:"yyyy'-'MM'-'dd HH':'mm':'ss'Z'",y:"MMMM, yyyy",Y:"MMMM, yyyy"},"/":"/",":":":",firstDay:0,twoDigitYearMax:2029}}};
function a8(bm){if(bm){if(bm.numberFormat){return bm;
}if(typeof bm===aN){var bn=ag.cultures;
return bn[bm]||bn[bm.split("-")[0]]||null;
}return null;
}return null;
}function bb(bm){if(bm){bm=a8(bm);
}return bm||ag.cultures.current;
}ag.culture=function(bn){var bo=ag.cultures,bm;
if(bn!==aV){bm=a8(bn)||bo[a7];
bm.calendar=bm.calendars.standard;
bo.current=bm;
}else{return bo.current;
}};
ag.findCulture=a8;
ag.getCulture=bb;
ag.culture(a7);
function a9(bo,bq,bn){bn=bb(bn);
var bm=bn.calendars.standard,bp=bm.days,br=bm.months;
bq=bm.patterns[bq]||bq;
return bq.replace(a5,function(bs){var bt;
var bu;
var bv;
if(bs==="d"){bu=bo.getDate();
}else{if(bs==="dd"){bu=aw(bo.getDate());
}else{if(bs==="ddd"){bu=bp.namesAbbr[bo.getDay()];
}else{if(bs==="dddd"){bu=bp.names[bo.getDay()];
}else{if(bs==="M"){bu=bo.getMonth()+1;
}else{if(bs==="MM"){bu=aw(bo.getMonth()+1);
}else{if(bs==="MMM"){bu=br.namesAbbr[bo.getMonth()];
}else{if(bs==="MMMM"){bu=br.names[bo.getMonth()];
}else{if(bs==="yy"){bu=aw(bo.getFullYear()%100);
}else{if(bs==="yyyy"){bu=aw(bo.getFullYear(),4);
}else{if(bs==="h"){bu=bo.getHours()%12||12;
}else{if(bs==="hh"){bu=aw(bo.getHours()%12||12);
}else{if(bs==="H"){bu=bo.getHours();
}else{if(bs==="HH"){bu=aw(bo.getHours());
}else{if(bs==="m"){bu=bo.getMinutes();
}else{if(bs==="mm"){bu=aw(bo.getMinutes());
}else{if(bs==="s"){bu=bo.getSeconds();
}else{if(bs==="ss"){bu=aw(bo.getSeconds());
}else{if(bs==="f"){bu=ak.floor(bo.getMilliseconds()/100);
}else{if(bs==="ff"){bu=bo.getMilliseconds();
if(bu>99){bu=ak.floor(bu/10);
}bu=aw(bu);
}else{if(bs==="fff"){bu=aw(bo.getMilliseconds(),3);
}else{if(bs==="tt"){bu=bo.getHours()<12?bm.AM[0]:bm.PM[0];
}else{if(bs==="zzz"){bt=bo.getTimezoneOffset();
bv=bt<0;
bu=ak.abs(bt/60).toString().split(".")[0];
bt=ak.abs(bt)-bu*60;
bu=(bv?"+":"-")+aw(bu);
bu+=":"+aw(bt);
}else{if(bs==="zz"||bs==="z"){bu=bo.getTimezoneOffset()/60;
bv=bu<0;
bu=ak.abs(bu).toString().split(".")[0];
bu=(bv?"+":"-")+(bs==="zz"?aw(bu):bu);
}}}}}}}}}}}}}}}}}}}}}}}}return bu!==aV?bu:bs.slice(1,bs.length-1);
});
}function ba(bJ,bt,bn){bn=bb(bn);
var bK=bn.numberFormat,bq=bK[bg],bN=bK.decimals,bL=bK.pattern[0],bH=[],bS,bE,bF,bp,bu,bI=bJ<0,bC,bv,bD,bw,bO=a6,bT=a6,bB,bG,bm,bx,by,br,bP,bU,bA,bz,bM,bo,bR,bQ=-1,bs;
if(bJ===aV){return a6;
}if(!isFinite(bJ)){return bJ;
}if(!bt){return bn.name.length?bJ.toLocaleString():bJ.toString();
}bu=bj.exec(bt);
if(bu){bt=bu[1].toLowerCase();
bE=bt==="c";
bF=bt==="p";
if(bE||bF){bK=bE?bK.currency:bK.percent;
bq=bK[bg];
bN=bK.decimals;
bS=bK.symbol;
bL=bK.pattern[bI?0:1];
}bp=bu[2];
if(bp){bN=+bp;
}if(bt==="e"){return bp?bJ.toExponential(bN):bJ.toExponential();
}if(bF){bJ*=100;
}bJ=bh(bJ,bN);
bI=bJ<0;
bJ=bJ.split(bg);
bC=bJ[0];
bv=bJ[1];
if(bI){bC=bC.substring(1);
}bT=bc(bC,0,bC.length,bK);
if(bv){bT+=bq+bv;
}if(bt==="n"&&!bI){return bT;
}bJ=a6;
for(bB=0,bG=bL.length;
bB<bG;
bB++){bm=bL.charAt(bB);
if(bm==="n"){bJ+=bT;
}else{if(bm==="$"||bm==="%"){bJ+=bS;
}else{bJ+=bm;
}}}return bJ;
}if(bI){bJ=-bJ;
}if(bt.indexOf("'")>-1||bt.indexOf('"')>-1||bt.indexOf("\\")>-1){bt=bt.replace(bd,function(bW){var bX=bW.charAt(0).replace("\\",""),bV=bW.slice(1).replace(bX,"");
bH.push(bV);
return bf;
});
}bt=bt.split(";");
if(bI&&bt[1]){bt=bt[1];
by=true;
}else{if(bJ===0){bt=bt[2]||bt[0];
if(bt.indexOf(bi)==-1&&bt.indexOf(bl)==-1){return bt;
}}else{bt=bt[0];
}}bM=bt.indexOf("%");
bo=bt.indexOf("$");
bF=bM!=-1;
bE=bo!=-1;
if(bF){bJ*=100;
}if(bE&&bt[bo-1]==="\\"){bt=bt.split("\\").join("");
bE=false;
}if(bE||bF){bK=bE?bK.currency:bK.percent;
bq=bK[bg];
bN=bK.decimals;
bS=bK.symbol;
}bx=bt.indexOf(a3)>-1;
if(bx){bt=bt.replace(a4,a6);
}br=bt.indexOf(bg);
bG=bt.length;
if(br!=-1){bv=bJ.toString().split("e");
if(bv[1]){bv=bh(bJ,Math.abs(bv[1]));
}else{bv=bv[0];
}bv=bv.split(bg)[1]||a6;
bU=bt.lastIndexOf(bl)-br;
bP=bt.lastIndexOf(bi)-br;
bA=bU>-1;
bz=bP>-1;
bB=bv.length;
if(!bA&&!bz){bt=bt.substring(0,br)+bt.substring(br+1);
bG=bt.length;
br=-1;
bB=0;
}if(bA&&bU>bP){bB=bU;
}else{if(bP>bU){if(bz&&bB>bP){bB=bP;
}else{if(bA&&bB<bU){bB=bU;
}}}}if(bB>-1){bJ=bh(bJ,bB);
}}else{bJ=bh(bJ);
}bP=bt.indexOf(bi);
bR=bU=bt.indexOf(bl);
if(bP==-1&&bU!=-1){bQ=bU;
}else{if(bP!=-1&&bU==-1){bQ=bP;
}else{bQ=bP>bU?bU:bP;
}}bP=bt.lastIndexOf(bi);
bU=bt.lastIndexOf(bl);
if(bP==-1&&bU!=-1){bs=bU;
}else{if(bP!=-1&&bU==-1){bs=bP;
}else{bs=bP>bU?bP:bU;
}}if(bQ==bG){bs=bQ;
}if(bQ!=-1){bT=bJ.toString().split(bg);
bC=bT[0];
bv=bT[1]||a6;
bD=bC.length;
bw=bv.length;
if(bI&&bJ*-1>=0){bI=false;
}bJ=bt.substring(0,bQ);
if(bI&&!by){bJ+="-";
}for(bB=bQ;
bB<bG;
bB++){bm=bt.charAt(bB);
if(br==-1){if(bs-bB<bD){bJ+=bC;
break;
}}else{if(bU!=-1&&bU<bB){bO=a6;
}if(br-bB<=bD&&br-bB>-1){bJ+=bC;
bB=br;
}if(br===bB){bJ+=(bv?bq:a6)+bv;
bB+=bs-br+1;
continue;
}}if(bm===bl){bJ+=bm;
bO=bm;
}else{if(bm===bi){bJ+=bO;
}}}if(bx){bJ=bc(bJ,bQ,bs,bK);
}if(bs>=bQ){bJ+=bt.substring(bs+1);
}if(bE||bF){bT=a6;
for(bB=0,bG=bJ.length;
bB<bG;
bB++){bm=bJ.charAt(bB);
bT+=bm==="$"||bm==="%"?bS:bm;
}bJ=bT;
}bG=bH.length;
if(bG){for(bB=0;
bB<bG;
bB++){bJ=bJ.replace(bf,bH[bB]);
}}}return bJ;
}var bc=function(bu,bx,bn,bv){var bm=bu.indexOf(bv[bg]);
var bp=bv.groupSize.slice();
var bo=bp.shift();
var br,bs;
var bq,bw,by;
var bt;
bn=bm!==-1?bm:bn+1;
br=bu.substring(bx,bn);
bs=br.length;
if(bs>=bo){bq=bs;
bw=[];
while(bq>-1){by=br.substring(bq-bo,bq);
if(by){bw.push(by);
}bq-=bo;
bt=bp.shift();
bo=bt!==aV?bt:bo;
if(bo===0){bw.push(br.substring(0,bq));
break;
}}br=bw.reverse().join(bv[a3]);
bu=bu.substring(0,bx)+br+bu.substring(bn);
}return bu;
};
var bh=function(bn,bm){bm=bm||0;
bn=bn.toString().split("e");
bn=Math.round(+(bn[0]+"e"+(bn[1]?+bn[1]+bm:bm)));
bn=bn.toString().split("e");
bn=+(bn[0]+"e"+(bn[1]?+bn[1]-bm:-bm));
return bn.toFixed(bm);
};
var bk=function(bo,bn,bm){if(bn){if(be.call(bo)==="[object Date]"){return a9(bo,bn,bm);
}else{if(typeof bo===aq){return ba(bo,bn,bm);
}}}return bo!==aV?bo:"";
};
ag.format=function(bm){var bn=arguments;
return bm.replace(P,function(bp,bo,bq){var br=bn[parseInt(bo,10)+1];
return bk(br,bq?bq.substring(1):"");
});
};
ag._extractFormat=function(bm){if(bm.slice(0,3)==="{0:"){bm=bm.slice(3,bm.length-1);
}return bm;
};
ag._activeElement=function(){try{return document.activeElement;
}catch(bm){return document.documentElement.activeElement;
}};
ag._round=bh;
ag.toString=bk;
}());
(function(){var bc=/\u00A0/g,a6=/[eE][\-+]?[0-9]+/,bj=/[+|\-]\d{1,2}/,a8=/[+|\-]\d{1,2}:?\d{2}/,a4=/^\/Date\((.*?)\)\/$/,bf=/[+-]\d*/,a7=["G","g","d","F","D","y","m","T","t"],bd={2:/^\d{1,2}/,3:/^\d{1,3}/,4:/^\d{4}/},be={}.toString;
function bg(bm,bl,bk){return !(bm>=bl&&bm<=bk);
}function a5(bk){return bk.charAt(0);
}function bb(bk){return l.map(bk,a5);
}function a3(bk,bl){if(!bl&&bk.getHours()===23){bk.setHours(bk.getHours()+2);
}}function a9(bl){var bm=0,bn=bl.length,bk=[];
for(;
bm<bn;
bm++){bk[bm]=(bl[bm]+"").toLowerCase();
}return bk;
}function ba(bk){var bl={},bm;
for(bm in bk){bl[bm]=a9(bk[bm]);
}return bl;
}function bh(bP,bt,bp){if(!bP){return null;
}var bC=function(bT){var bS=0;
while(bt[bz]===bT){bS++;
bz++;
}if(bS>0){bz-=1;
}return bS;
},bv=function(bU){var bT=bd[bU]||new RegExp("^\\d{1,"+bU+"}"),bS=bP.substr(bQ,bU).match(bT);
if(bS){bS=bS[0];
bQ+=bS.length;
return parseInt(bS,10);
}return null;
},bu=function(bZ,bU){var bS=0,bT=bZ.length,bX,bY,bW=0,bV=0,b0;
for(;
bS<bT;
bS++){bX=bZ[bS];
bY=bX.length;
b0=bP.substr(bQ,bY);
if(bU){b0=b0.toLowerCase();
}if(b0==bX&&bY>bW){bW=bY;
bV=bS;
}}if(bW){bQ+=bW;
return bV+1;
}return null;
},bn=function(){var bS=false;
if(bP.charAt(bQ)===bt[bz]){bQ++;
bS=true;
}return bS;
},bl=bp.calendars.standard,bR=null,bI=null,br=null,bx=null,bG=null,bM=null,bF=null,bz=0,bQ=0,bB=false,bq=new Date(),bN=bl.twoDigitYearMax||2029,bs=bq.getFullYear(),bm,bo,bA,bJ,bL,bO,bE,bk,bK,by,bH,bw,bD;
if(!bt){bt="d";
}bJ=bl.patterns[bt];
if(bJ){bt=bJ;
}bt=bt.split("");
bA=bt.length;
for(;
bz<bA;
bz++){bm=bt[bz];
if(bB){if(bm==="'"){bB=false;
}else{bn();
}}else{if(bm==="d"){bo=bC("d");
if(!bl._lowerDays){bl._lowerDays=ba(bl.days);
}if(br!==null&&bo>2){continue;
}br=bo<3?bv(2):bu(bl._lowerDays[bo==3?"namesAbbr":"names"],true);
if(br===null||bg(br,1,31)){return null;
}}else{if(bm==="M"){bo=bC("M");
if(!bl._lowerMonths){bl._lowerMonths=ba(bl.months);
}bI=bo<3?bv(2):bu(bl._lowerMonths[bo==3?"namesAbbr":"names"],true);
if(bI===null||bg(bI,1,12)){return null;
}bI-=1;
}else{if(bm==="y"){bo=bC("y");
bR=bv(bo);
if(bR===null){return null;
}if(bo==2){if(typeof bN==="string"){bN=bs+parseInt(bN,10);
}bR=bs-bs%100+bR;
if(bR>bN){bR-=100;
}}}else{if(bm==="h"){bC("h");
bx=bv(2);
if(bx==12){bx=0;
}if(bx===null||bg(bx,0,11)){return null;
}}else{if(bm==="H"){bC("H");
bx=bv(2);
if(bx===null||bg(bx,0,23)){return null;
}}else{if(bm==="m"){bC("m");
bG=bv(2);
if(bG===null||bg(bG,0,59)){return null;
}}else{if(bm==="s"){bC("s");
bM=bv(2);
if(bM===null||bg(bM,0,59)){return null;
}}else{if(bm==="f"){bo=bC("f");
bD=bP.substr(bQ,bo).match(bd[3]);
bF=bv(bo);
if(bF!==null){bF=parseFloat("0."+bD[0],10);
bF=ag._round(bF,3);
bF*=1000;
}if(bF===null||bg(bF,0,999)){return null;
}}else{if(bm==="t"){bo=bC("t");
bk=bl.AM;
bK=bl.PM;
if(bo===1){bk=bb(bk);
bK=bb(bK);
}bL=bu(bK);
if(!bL&&!bu(bk)){return null;
}}else{if(bm==="z"){bO=true;
bo=bC("z");
if(bP.substr(bQ,1)==="Z"){bn();
continue;
}bE=bP.substr(bQ,6).match(bo>2?a8:bj);
if(!bE){return null;
}bE=bE[0].split(":");
by=bE[0];
bH=bE[1];
if(!bH&&by.length>3){bQ=by.length-2;
bH=by.substring(bQ);
by=by.substring(0,bQ);
}by=parseInt(by,10);
if(bg(by,-12,13)){return null;
}if(bo>2){bH=parseInt(bH,10);
if(isNaN(bH)||bg(bH,0,59)){return null;
}}}else{if(bm==="'"){bB=true;
bn();
}else{if(!bn()){return null;
}}}}}}}}}}}}}}bw=bx!==null||bG!==null||bM||null;
if(bR===null&&bI===null&&br===null&&bw){bR=bs;
bI=bq.getMonth();
br=bq.getDate();
}else{if(bR===null){bR=bs;
}if(br===null){br=1;
}}if(bL&&bx<12){bx+=12;
}if(bO){if(by){bx+=-by;
}if(bH){bG+=-bH;
}bP=new Date(Date.UTC(bR,bI,br,bx,bG,bM,bF));
}else{bP=new Date(bR,bI,br,bx,bG,bM,bF);
a3(bP,bx);
}if(bR<100){bP.setFullYear(bR);
}if(bP.getDate()!==br&&bO===aV){return null;
}return bP;
}function bi(bk){var bl=bk.substr(0,1)==="-"?-1:1;
bk=bk.substring(1);
bk=parseInt(bk.substr(0,2),10)*60+parseInt(bk.substring(2),10);
return bl*bk;
}ag.parseDate=function(br,bm,bk){if(be.call(br)==="[object Date]"){return br;
}var bn=0;
var bl=null;
var bo,bp;
var bq;
if(br&&br.indexOf("/D")===0){bl=a4.exec(br);
if(bl){bl=bl[1];
bq=bf.exec(bl.substring(1));
bl=new Date(parseInt(bl,10));
if(bq){bq=bi(bq[0]);
bl=ag.timezone.apply(bl,0);
bl=ag.timezone.convert(bl,0,-1*bq);
}return bl;
}}bk=ag.getCulture(bk);
if(!bm){bm=[];
bp=bk.calendar.patterns;
bo=a7.length;
for(;
bn<bo;
bn++){bm[bn]=bp[a7[bn]];
}bn=0;
bm=["yyyy/MM/dd HH:mm:ss","yyyy/MM/dd HH:mm","yyyy/MM/dd","ddd MMM dd yyyy HH:mm:ss","yyyy-MM-ddTHH:mm:ss.fffffffzzz","yyyy-MM-ddTHH:mm:ss.fffzzz","yyyy-MM-ddTHH:mm:sszzz","yyyy-MM-ddTHH:mm:ss.fffffff","yyyy-MM-ddTHH:mm:ss.fff","yyyy-MM-ddTHH:mmzzz","yyyy-MM-ddTHH:mmzz","yyyy-MM-ddTHH:mm:ss","yyyy-MM-ddTHH:mm","yyyy-MM-dd HH:mm:ss","yyyy-MM-dd HH:mm","yyyy-MM-dd","HH:mm:ss","HH:mm"].concat(bm);
}bm=Z(bm)?bm:[bm];
bo=bm.length;
for(;
bn<bo;
bn++){bl=bh(br,bm[bn],bk);
if(bl){return bl;
}}return bl;
};
ag.parseInt=function(bm,bk){var bl=ag.parseFloat(bm,bk);
if(bl){bl=bl|0;
}return bl;
};
ag.parseFloat=function(bu,bk,bm){if(!bu&&bu!==0){return null;
}if(typeof bu===aq){return bu;
}bu=bu.toString();
bk=ag.getCulture(bk);
var bp=bk.numberFormat,br=bp.percent,bl=bp.currency,bt=bl.symbol,bs=br.symbol,bo=bu.indexOf("-"),bq,bn;
if(a6.test(bu)){bu=parseFloat(bu.replace(bp["."],"."));
if(isNaN(bu)){bu=null;
}return bu;
}if(bo>0){return null;
}else{bo=bo>-1;
}if(bu.indexOf(bt)>-1||bm&&bm.toLowerCase().indexOf("c")>-1){bp=bl;
bq=bp.pattern[0].replace("$",bt).split("n");
if(bu.indexOf(bq[0])>-1&&bu.indexOf(bq[1])>-1){bu=bu.replace(bq[0],"").replace(bq[1],"");
bo=true;
}}else{if(bu.indexOf(bs)>-1){bn=true;
bp=br;
bt=bs;
}}bu=bu.replace("-","").replace(bt,"").replace(bc," ").split(bp[","].replace(bc," ")).join("").replace(bp["."],".");
bu=parseFloat(bu);
if(isNaN(bu)){bu=null;
}else{if(bo){bu*=-1;
}}if(bu&&bn){bu/=100;
}return bu;
};
}());
function V(a4){var a6=a4.css(ag.support.transitions.css+"box-shadow")||a4.css("box-shadow"),a5=a6?a6.match(t)||[0,0,0,0,0]:[0,0,0,0,0],a3=ak.max(+a5[3],+(a5[4]||0));
return{left:-a5[1]+a3,right:+a5[1]+a3,bottom:+a5[2]+a3};
}function a0(a5,a3){var a4=aO.browser,a8,a7=a5.css("direction")=="rtl";
if(!a5.parent().hasClass("k-animation-container")){var bb=V(a5),bc=a5[0].style.width,a6=a5[0].style.height,ba=aA.test(bc),a9=aA.test(a6);
if(a4.opera){bb.left=bb.right=bb.bottom=5;
}a8=ba||a9;
if(!ba&&(!a3||a3&&bc)){bc=a5.outerWidth();
}if(!a9&&(!a3||a3&&a6)){a6=a5.outerHeight();
}a5.wrap(l("<div/>").addClass("k-animation-container").css({width:bc,height:a6,marginLeft:bb.left*(a7?1:-1),paddingLeft:bb.left,paddingRight:bb.right,paddingBottom:bb.bottom}));
if(a8){a5.css({width:"100%",height:"100%",boxSizing:"border-box",mozBoxSizing:"border-box",webkitBoxSizing:"border-box"});
}}else{var bd=a5.parent(".k-animation-container"),be=bd[0].style;
if(bd.is(":hidden")){bd.show();
}a8=aA.test(be.width)||aA.test(be.height);
if(!a8){bd.css({width:a5.outerWidth(),height:a5.outerHeight(),boxSizing:"content-box",mozBoxSizing:"content-box",webkitBoxSizing:"content-box"});
}}if(a4.msie&&ak.floor(a4.version)<=7){a5.css({zoom:1});
a5.children(".k-menu").width(a5.width());
}return a5.parent();
}function B(a3){var a4=1,a5=arguments.length;
for(a4=1;
a4<a5;
a4++){C(a3,arguments[a4]);
}return a3;
}function C(a4,bd){var a8=ag.data.ObservableArray,a7=ag.data.LazyObservableArray,a3=ag.data.DataSource,a6=ag.data.HierarchicalDataSource,a9,bc,bb,ba,a5;
for(a9 in bd){bc=bd[a9];
bb=typeof bc;
if(bb===at&&bc!==null){ba=bc.constructor;
}else{ba=null;
}if(ba&&ba!==Array&&ba!==a8&&ba!==a7&&ba!==a3&&ba!==a6){if(bc instanceof Date){a4[a9]=new Date(bc.getTime());
}else{if(ab(bc.clone)){a4[a9]=bc.clone();
}else{a5=a4[a9];
if(typeof a5===at){a4[a9]=a5||{};
}else{a4[a9]={};
}C(a4[a9],bc);
}}}else{if(bb!==aW){a4[a9]=bc;
}}}return a4;
}function aR(a3,a6,a4){for(var a5 in a6){if(a6.hasOwnProperty(a5)&&a6[a5].test(a3)){return a5;
}}return a4!==aV?a4:a3;
}function aU(a3){return a3.replace(/([a-z][A-Z])/g,function(a4){return a4.charAt(0)+"-"+a4.charAt(1).toLowerCase();
});
}function aS(a3){return a3.replace(/\-(\w)/g,function(a5,a4){return a4.toUpperCase();
});
}function S(a4,a5){var a6={},a3;
if(document.defaultView&&document.defaultView.getComputedStyle){a3=document.defaultView.getComputedStyle(a4,"");
if(a5){l.each(a5,function(a7,a8){a6[a8]=a3.getPropertyValue(a8);
});
}}else{a3=a4.currentStyle;
if(a5){l.each(a5,function(a7,a8){a6[a8]=a3[aS(a8)];
});
}}if(!ag.size(a6)){a6=a3;
}return a6;
}function ac(a3){if(a3&&a3.className&&typeof a3.className==="string"&&a3.className.indexOf("k-auto-scrollable")>-1){return true;
}var a4=S(a3,["overflow"]).overflow;
return a4=="auto"||a4=="scroll";
}function aI(a4,a7){var a8=aO.browser.webkit;
var a6=aO.browser.mozilla;
var a3=a4 instanceof l?a4[0]:a4;
var a5;
if(!a4){return;
}a5=aO.isRtl(a4);
if(a7!==aV){if(a5&&a8){a3.scrollLeft=a3.scrollWidth-a3.clientWidth-a7;
}else{if(a5&&a6){a3.scrollLeft=-a7;
}else{a3.scrollLeft=a7;
}}}else{if(a5&&a8){return a3.scrollWidth-a3.clientWidth-a3.scrollLeft;
}else{return Math.abs(a3.scrollLeft);
}}}(function(){aO._scrollbar=aV;
aO.scrollbar=function(bc){if(!isNaN(aO._scrollbar)&&!bc){return aO._scrollbar;
}else{var bb=document.createElement("div"),bd;
bb.style.cssText="overflow:scroll;overflow-x:hidden;zoom:1;clear:both;display:block";
bb.innerHTML="&nbsp;";
document.body.appendChild(bb);
aO._scrollbar=bd=bb.offsetWidth-bb.scrollWidth;
document.body.removeChild(bb);
return bd;
}};
aO.isRtl=function(bb){return l(bb).closest(".k-rtl").length>0;
};
var a8=document.createElement("table");
try{a8.innerHTML="<tr><td></td></tr>";
aO.tbodyInnerHtml=true;
}catch(a4){aO.tbodyInnerHtml=false;
}aO.touch="ontouchstart" in aZ;
aO.msPointers=aZ.MSPointerEvent;
aO.pointers=aZ.PointerEvent;
var ba=aO.transitions=false,a9=aO.transforms=false,a5="HTMLElement" in aZ?HTMLElement.prototype:[];
aO.hasHW3D="WebKitCSSMatrix" in aZ&&"m11" in new aZ.WebKitCSSMatrix()||"MozPerspective" in document.documentElement.style||"msPerspective" in document.documentElement.style;
E(["Moz","webkit","O","ms"],function(){var bd=this.toString(),bb=typeof a8.style[bd+"Transition"]===aN;
if(bb||typeof a8.style[bd+"Transform"]===aN){var bc=bd.toLowerCase();
a9={css:bc!="ms"?"-"+bc+"-":"",prefix:bd,event:bc==="o"||bc==="webkit"?bc:""};
if(bb){ba=a9;
ba.event=ba.event?ba.event+"TransitionEnd":"transitionend";
}return false;
}});
a8=null;
aO.transforms=a9;
aO.transitions=ba;
aO.devicePixelRatio=aZ.devicePixelRatio===aV?1:aZ.devicePixelRatio;
try{aO.screenWidth=aZ.outerWidth||aZ.screen?aZ.screen.availWidth:aZ.innerWidth;
aO.screenHeight=aZ.outerHeight||aZ.screen?aZ.screen.availHeight:aZ.innerHeight;
}catch(a4){aO.screenWidth=aZ.screen.availWidth;
aO.screenHeight=aZ.screen.availHeight;
}aO.detectOS=function(bk){var bi=false,bg,bf=[],bh=!/mobile safari/i.test(bk),bc={wp:/(Windows Phone(?: OS)?)\s(\d+)\.(\d+(\.\d+)?)/,fire:/(Silk)\/(\d+)\.(\d+(\.\d+)?)/,android:/(Android|Android.*(?:Opera|Firefox).*?\/)\s*(\d+)\.(\d+(\.\d+)?)/,iphone:/(iPhone|iPod).*OS\s+(\d+)[\._]([\d\._]+)/,ipad:/(iPad).*OS\s+(\d+)[\._]([\d_]+)/,meego:/(MeeGo).+NokiaBrowser\/(\d+)\.([\d\._]+)/,webos:/(webOS)\/(\d+)\.(\d+(\.\d+)?)/,blackberry:/(BlackBerry|BB10).*?Version\/(\d+)\.(\d+(\.\d+)?)/,playbook:/(PlayBook).*?Tablet\s*OS\s*(\d+)\.(\d+(\.\d+)?)/,windows:/(MSIE)\s+(\d+)\.(\d+(\.\d+)?)/,tizen:/(tizen).*?Version\/(\d+)\.(\d+(\.\d+)?)/i,sailfish:/(sailfish).*rv:(\d+)\.(\d+(\.\d+)?).*firefox/i,ffos:/(Mobile).*rv:(\d+)\.(\d+(\.\d+)?).*Firefox/},bj={ios:/^i(phone|pad|pod)$/i,android:/^android|fire$/i,blackberry:/^blackberry|playbook/i,windows:/windows/,wp:/wp/,flat:/sailfish|ffos|tizen/i,meego:/meego/},be={tablet:/playbook|ipad|fire/i},bd={omini:/Opera\sMini/i,omobile:/Opera\sMobi/i,firefox:/Firefox|Fennec/i,mobilesafari:/version\/.*safari/i,ie:/MSIE|Windows\sPhone/i,chrome:/chrome|crios/i,webkit:/webkit/i};
for(var bb in bc){if(bc.hasOwnProperty(bb)){bf=bk.match(bc[bb]);
if(bf){if(bb=="windows"&&"plugins" in navigator){return false;
}bi={};
bi.device=bb;
bi.tablet=aR(bb,be,false);
bi.browser=aR(bk,bd,"default");
bi.name=aR(bb,bj);
bi[bi.name]=true;
bi.majorVersion=bf[2];
bi.minorVersion=bf[3].replace("_",".");
bg=bi.minorVersion.replace(".","").substr(0,2);
bi.flatVersion=bi.majorVersion+bg+new Array(3-(bg.length<3?bg.length:2)).join("0");
bi.cordova=typeof aZ.PhoneGap!==aW||typeof aZ.cordova!==aW;
bi.appMode=aZ.navigator.standalone||/file|local|wmapp/.test(aZ.location.protocol)||bi.cordova;
if(bi.android&&(aO.devicePixelRatio<1.5&&bi.flatVersion<400||bh)&&(aO.screenWidth>800||aO.screenHeight>800)){bi.tablet=bb;
}break;
}}}return bi;
};
var a7=aO.mobileOS=aO.detectOS(navigator.userAgent);
aO.wpDevicePixelRatio=a7.wp?screen.width/320:0;
aO.kineticScrollNeeded=a7&&(aO.touch||aO.msPointers||aO.pointers);
aO.hasNativeScrolling=false;
if(a7.ios||a7.android&&a7.majorVersion>2||a7.wp){aO.hasNativeScrolling=a7;
}aO.delayedClick=function(){if(aO.touch){if(a7.ios){return true;
}if(a7.android){if(!aO.browser.chrome){return true;
}if(aO.browser.version<32){return false;
}return !(l("meta[name=viewport]").attr("content")||"").match(/user-scalable=no/i);
}}return false;
};
aO.mouseAndTouchPresent=aO.touch&&!(aO.mobileOS.ios||aO.mobileOS.android);
aO.detectBrowser=function(bf){var bc=false,be=[],bd={edge:/(edge)[ \/]([\w.]+)/i,webkit:/(chrome)[ \/]([\w.]+)/i,safari:/(webkit)[ \/]([\w.]+)/i,opera:/(opera)(?:.*version|)[ \/]([\w.]+)/i,msie:/(msie\s|trident.*? rv:)([\w.]+)/i,mozilla:/(mozilla)(?:.*? rv:([\w.]+)|)/i};
for(var bb in bd){if(bd.hasOwnProperty(bb)){be=bf.match(bd[bb]);
if(be){bc={};
bc[bb]=true;
bc[be[1].toLowerCase().split(" ")[0].split("/")[0]]=true;
bc.version=parseInt(document.documentMode||be[2],10);
break;
}}}return bc;
};
aO.browser=aO.detectBrowser(navigator.userAgent);
aO.detectClipboardAccess=function(){var bb={copy:document.queryCommandSupported?document.queryCommandSupported("copy"):false,cut:document.queryCommandSupported?document.queryCommandSupported("cut"):false,paste:document.queryCommandSupported?document.queryCommandSupported("paste"):false};
if(aO.browser.chrome&&aO.browser.version>=43){bb.copy=true;
bb.cut=true;
}return bb;
};
aO.clipboard=aO.detectClipboardAccess();
aO.zoomLevel=function(){try{var bb=aO.browser;
var be=0;
var bc=document.documentElement;
if(bb.msie&&bb.version==11&&bc.scrollHeight>bc.clientHeight&&!aO.touch){be=aO.scrollbar();
}return aO.touch?bc.clientWidth/aZ.innerWidth:bb.msie&&bb.version>=10?((top||aZ).document.documentElement.offsetWidth+be)/(top||aZ).innerWidth:1;
}catch(bd){return 1;
}};
aO.cssBorderSpacing=typeof document.documentElement.style.borderSpacing!="undefined"&&!(aO.browser.msie&&aO.browser.version<8);
(function(bb){var bc="",bd=l(document.documentElement),be=parseInt(bb.version,10);
if(bb.msie){bc="ie";
}else{if(bb.mozilla){bc="ff";
}else{if(bb.safari){bc="safari";
}else{if(bb.webkit){bc="webkit";
}else{if(bb.opera){bc="opera";
}else{if(bb.edge){bc="edge";
}}}}}}if(bc){bc="k-"+bc+" k-"+bc+be;
}if(aO.mobileOS){bc+=" k-mobile";
}bd.addClass(bc);
}(aO.browser));
aO.eventCapture=document.documentElement.addEventListener;
var a6=document.createElement("input");
aO.placeholder="placeholder" in a6;
aO.propertyChangeEvent="onpropertychange" in a6;
aO.input=function(){var bf=["number","date","time","month","week","datetime","datetime-local"];
var bc=bf.length;
var bg="test";
var bd={};
var bb=0;
var be;
for(;
bb<bc;
bb++){be=bf[bb];
a6.setAttribute("type",be);
a6.value=bg;
bd[be.replace("-","")]=a6.type!=="text"&&a6.value!==bg;
}return bd;
}();
a6.style.cssText="float:left;";
aO.cssFloat=!!a6.style.cssFloat;
a6=null;
aO.stableSort=function(){var bd=513;
var bc=[{index:0,field:"b"}];
for(var bb=1;
bb<bd;
bb++){bc.push({index:bb,field:"a"});
}bc.sort(function(be,bf){return be.field>bf.field?1:be.field<bf.field?-1:0;
});
return bc[0].index===1;
}();
aO.matchesSelector=a5.webkitMatchesSelector||a5.mozMatchesSelector||a5.msMatchesSelector||a5.oMatchesSelector||a5.matchesSelector||a5.matches||function(bd){var bc=document.querySelectorAll?(this.parentNode||document).querySelectorAll(bd)||[]:l(bd),bb=bc.length;
while(bb--){if(bc[bb]==this){return true;
}}return false;
};
aO.pushState=aZ.history&&aZ.history.pushState;
var a3=document.documentMode;
aO.hashChange="onhashchange" in aZ&&!(aO.browser.msie&&(!a3||a3<=8));
aO.customElements="registerElement" in aZ.document;
}());
function aL(a4){var a5=0,a3;
for(a3 in a4){if(a4.hasOwnProperty(a3)&&a3!="toJSON"){a5++;
}}return a5;
}function U(a3,a6,a4){if(!a6){a6="offset";
}var a5=a3[a6]();
if(aO.browser.msie&&(aO.pointers||aO.msPointers)&&!a4){a5.top-=aZ.pageYOffset-document.documentElement.scrollTop;
a5.left-=aZ.pageXOffset-document.documentElement.scrollLeft;
}return a5;
}var D={left:{reverse:"right"},right:{reverse:"left"},down:{reverse:"up"},up:{reverse:"down"},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out"},out:{reverse:"in"}};
function ax(a4){var a3={};
E(typeof a4==="string"?a4.split(" "):a4,function(a5){a3[a5]=this;
});
return a3;
}function R(a3){return new ag.effects.Element(a3);
}var F={};
l.extend(F,{enabled:true,Element:function(a3){this.element=l(a3);
},promise:function(a3,a4){if(!a3.is(":visible")){a3.css({display:a3.data("olddisplay")||"block"}).css("display");
}if(a4.hide){a3.data("olddisplay",a3.css("display")).hide();
}if(a4.init){a4.init();
}if(a4.completeCallback){a4.completeCallback(a3);
}a3.dequeue();
},disable:function(){this.enabled=false;
this.promise=this.promiseShim;
},enable:function(){this.enabled=true;
this.promise=this.animatedPromise;
}});
F.promiseShim=F.promise;
function aB(a5,a4,a6,a3){if(typeof a5===aN){if(ab(a4)){a3=a4;
a4=400;
a6=false;
}if(ab(a6)){a3=a6;
a6=false;
}if(typeof a4===s){a6=a4;
a4=400;
}a5={effects:a5,duration:a4,reverse:a6,complete:a3};
}return N({effects:{},duration:400,reverse:false,init:ao,teardown:ao,hide:false},a5,{completeCallback:a5.complete,complete:ao});
}function n(a5,a9,a4,ba,a3){var a6=0,a8=a5.length,a7;
for(;
a6<a8;
a6++){a7=l(a5[a6]);
a7.queue(function(){F.promise(a7,aB(a9,a4,ba,a3));
});
}return a5;
}function aT(a5,a4,a6,a3){if(a4){a4=a4.split(" ");
E(a4,function(a7,a8){a5.toggleClass(a8,a3);
});
}return a5;
}if(!("kendoAnimate" in l.fn)){N(l.fn,{kendoStop:function(a3,a4){return this.stop(a3,a4);
},kendoAnimate:function(a5,a4,a6,a3){return n(this,a5,a4,a6,a3);
},kendoAddClass:function(a3,a4){return ag.toggleClass(this,a3,a4,true);
},kendoRemoveClass:function(a3,a4){return ag.toggleClass(this,a3,a4,false);
},kendoToggleClass:function(a3,a4,a5){return ag.toggleClass(this,a3,a4,a5);
}});
}var m=/&/g,aj=/</g,aF=/"/g,q=/'/g,X=/>/g;
function Y(a3){return(""+a3).replace(m,"&amp;").replace(aj,"&lt;").replace(X,"&gt;").replace(aF,"&quot;").replace(q,"&#39;");
}var L=function(a3){return a3.target;
};
if(aO.touch){L=function(a3){var a4="originalEvent" in a3?a3.originalEvent.changedTouches:"changedTouches" in a3?a3.changedTouches:null;
return a4?document.elementFromPoint(a4[0].clientX,a4[0].clientY):a3.target;
};
E(["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","tap"],function(a3,a4){l.fn[a4]=function(a5){return this.bind(a4,a5);
};
});
}if(aO.touch){if(!aO.mobileOS){aO.mousedown="mousedown touchstart";
aO.mouseup="mouseup touchend";
aO.mousemove="mousemove touchmove";
aO.mousecancel="mouseleave touchcancel";
aO.click="click";
aO.resize="resize";
}else{aO.mousedown="touchstart";
aO.mouseup="touchend";
aO.mousemove="touchmove";
aO.mousecancel="touchcancel";
aO.click="touchend";
aO.resize="orientationchange";
}}else{if(aO.pointers){aO.mousemove="pointermove";
aO.mousedown="pointerdown";
aO.mouseup="pointerup";
aO.mousecancel="pointercancel";
aO.click="pointerup";
aO.resize="orientationchange resize";
}else{if(aO.msPointers){aO.mousemove="MSPointerMove";
aO.mousedown="MSPointerDown";
aO.mouseup="MSPointerUp";
aO.mousecancel="MSPointerCancel";
aO.click="MSPointerUp";
aO.resize="orientationchange resize";
}else{aO.mousemove="mousemove";
aO.mousedown="mousedown";
aO.mouseup="mouseup";
aO.mousecancel="mouseleave";
aO.click="click";
aO.resize="resize";
}}}var a1=function(a8,a9){var ba=a9||"d",a5,a4,a6,a7,a3=1;
for(a4=0,a6=a8.length;
a4<a6;
a4++){a7=a8[a4];
if(a7!==""){a5=a7.indexOf("[");
if(a5!==0){if(a5==-1){a7="."+a7;
}else{a3++;
a7="."+a7.substring(0,a5)+" || {})"+a7.substring(a5);
}}a3++;
ba+=a7+(a4<a6-1?" || {})":")");
}}return new Array(a3).join("(")+ba;
},ai=/^([a-z]+:)?\/\//i;
N(ag,{widgets:[],_widgetRegisteredCallbacks:[],ui:ag.ui||{},fx:ag.fx||R,effects:ag.effects||F,mobile:ag.mobile||{},data:ag.data||{},dataviz:ag.dataviz||{},drawing:ag.drawing||{},spreadsheet:{messages:{}},keys:{INSERT:45,DELETE:46,BACKSPACE:8,TAB:9,ENTER:13,ESC:27,LEFT:37,UP:38,RIGHT:39,DOWN:40,END:35,HOME:36,SPACEBAR:32,PAGEUP:33,PAGEDOWN:34,F2:113,F10:121,F12:123,NUMPAD_PLUS:107,NUMPAD_MINUS:109,NUMPAD_DOT:110},support:ag.support||aO,animate:ag.animate||n,ns:"",attr:function(a3){return"data-"+ag.ns+a3;
},getShadows:V,wrap:a0,deepExtend:B,getComputedStyles:S,webComponents:ag.webComponents||[],isScrollable:ac,scrollLeft:aI,size:aL,toCamelCase:aS,toHyphens:aU,getOffset:ag.getOffset||U,parseEffects:ag.parseEffects||ax,toggleClass:ag.toggleClass||aT,directions:ag.directions||D,Observable:au,Class:u,Template:aP,template:aD(aP.compile,aP),render:aD(aP.render,aP),stringify:aD(ad.stringify,ad),eventTarget:L,htmlEncode:Y,isLocalUrl:function(a3){return a3&&!ai.test(a3);
},expr:function(a3,a5,a4){a3=a3||"";
if(typeof a5==aN){a4=a5;
a5=false;
}a4=a4||"d";
if(a3&&a3.charAt(0)!=="["){a3="."+a3;
}if(a5){a3=a3.replace(/"([^.]*)\.([^"]*)"/g,'"$1_$DOT$_$2"');
a3=a3.replace(/'([^.]*)\.([^']*)'/g,"'$1_$DOT$_$2'");
a3=a1(a3.split("."),a4);
a3=a3.replace(/_\$DOT\$_/g,".");
}else{a3=a4+a3;
}return a3;
},getter:function(a3,a5){var a4=a3+a5;
return W[a4]=W[a4]||new Function("d","return "+ag.expr(a3,a5));
},setter:function(a3){return aJ[a3]=aJ[a3]||new Function("d,value",ag.expr(a3)+"=value");
},accessor:function(a3){return{get:ag.getter(a3),set:ag.setter(a3)};
},guid:function(){var a4="",a3,a5;
for(a3=0;
a3<32;
a3++){a5=ak.random()*16|0;
if(a3==8||a3==12||a3==16||a3==20){a4+="-";
}a4+=(a3==12?4:a3==16?a5&3|8:a5).toString(16);
}return a4;
},roleSelector:function(a3){return a3.replace(/(\S+)/g,"["+ag.attr("role")+"=$1],").slice(0,-1);
},directiveSelector:function(a3){var a5=a3.split(" ");
if(a5){for(var a4=0;
a4<a5.length;
a4++){if(a5[a4]!="view"){a5[a4]=a5[a4].replace(/(\w*)(view|bar|strip|over)$/,"$1-$2");
}}}return a5.join(" ").replace(/(\S+)/g,"kendo-mobile-$1,").slice(0,-1);
},triggeredByInput:function(a3){return/^(label|input|textarea|select)$/i.test(a3.target.tagName);
},onWidgetRegistered:function(a3){for(var a4=0,a5=ag.widgets.length;
a4<a5;
a4++){a3(ag.widgets[a4]);
}ag._widgetRegisteredCallbacks.push(a3);
},logToConsole:function(a4){var a3=aZ.console;
if(!ag.suppressLog&&typeof a3!="undefined"&&a3.log){a3.log(a4);
}}});
var aY=au.extend({init:function(a4,a5){var a6=this;
a6.element=ag.jQuery(a4).handler(a6);
a6.angular("init",a5);
au.fn.init.call(a6);
var a3=a5?a5.dataSource:null;
if(a3){a5=N({},a5,{dataSource:{}});
}a5=a6.options=N(true,{},a6.options,a5);
if(a3){a5.dataSource=a3;
}if(!a6.element.attr(ag.attr("role"))){a6.element.attr(ag.attr("role"),(a5.name||"").toLowerCase());
}a6.element.data("kendo"+a5.prefix+a5.name,a6);
a6.bind(a6.events,a5);
},events:[],options:{prefix:""},_hasBindingTarget:function(){return !!this.element[0].kendoBindingTarget;
},_tabindex:function(a6){a6=a6||this.wrapper;
var a3=this.element,a5="tabindex",a4=a6.attr(a5)||a3.attr(a5);
a3.removeAttr(a5);
a6.attr(a5,!isNaN(a4)?a4:0);
},setOptions:function(a3){this._setEvents(a3);
l.extend(this.options,a3);
},_setEvents:function(a6){var a7=this,a4=0,a5=a7.events.length,a3;
for(;
a4<a5;
a4++){a3=a7.events[a4];
if(a7.options[a3]&&a6[a3]){a7.unbind(a3,a7.options[a3]);
}}a7.bind(a7.events,a6);
},resize:function(a4){var a5=this.getSize(),a3=this._size;
if(a4||(a5.width>0||a5.height>0)&&(!a3||a5.width!==a3.width||a5.height!==a3.height)){this._size=a5;
this._resize(a5,a4);
this.trigger("resize",a5);
}},getSize:function(){return ag.dimensions(this.element);
},size:function(a3){if(!a3){return this.getSize();
}else{this.setSize(a3);
}},setSize:l.noop,_resize:l.noop,destroy:function(){var a3=this;
a3.element.removeData("kendo"+a3.options.prefix+a3.options.name);
a3.element.removeData("handler");
a3.unbind();
},_destroy:function(){this.destroy();
},angular:function(){},_muteAngularRebind:function(a3){this._muteRebind=true;
a3.call(this);
this._muteRebind=false;
}});
var A=aY.extend({dataItems:function(){return this.dataSource.flatView();
},_angularItems:function(a3){var a4=this;
a4.angular(a3,function(){return{elements:a4.items(),data:l.map(a4.dataItems(),function(a5){return{dataItem:a5};
})};
});
}});
ag.dimensions=function(a5,a3){var a4=a5[0];
if(a3){a5.css(a3);
}return{width:a4.offsetWidth,height:a4.offsetHeight};
};
ag.notify=ao;
var aQ=/template$/i,af=/^\s*(?:\{(?:.|\r\n|\n)*\}|\[(?:.|\r\n|\n)*\])\s*$/,ae=/^\{(\d+)(:[^\}]+)?\}|^\[[A-Za-z_]*\]$/,z=/([A-Z])/g;
function ay(a3,a4){var a5;
if(a4.indexOf("data")===0){a4=a4.substring(4);
a4=a4.charAt(0).toLowerCase()+a4.substring(1);
}a4=a4.replace(z,"-$1");
a5=a3.getAttribute("data-"+ag.ns+a4);
if(a5===null){a5=aV;
}else{if(a5==="null"){a5=null;
}else{if(a5==="true"){a5=true;
}else{if(a5==="false"){a5=false;
}else{if(ar.test(a5)){a5=parseFloat(a5);
}else{if(af.test(a5)&&!ae.test(a5)){a5=new Function("return ("+a5+")")();
}}}}}}return a5;
}function az(a3,a5){var a6={},a4,a7;
for(a4 in a5){a7=ay(a3,a4);
if(a7!==aV){if(aQ.test(a4)){a7=ag.template(l("#"+a7).html());
}a6[a4]=a7;
}}return a6;
}ag.initWidget=function(a5,bb,be){var bc,ba,bg,a7,a9,bd,bf,a4,a6,bi;
if(!be){be=ag.ui.roles;
}else{if(be.roles){be=be.roles;
}}a5=a5.nodeType?a5:a5[0];
bd=a5.getAttribute("data-"+ag.ns+"role");
if(!bd){return;
}a6=bd.indexOf(".")===-1;
if(a6){bg=be[bd];
}else{bg=ag.getter(bd)(aZ);
}var a3=l(a5).data(),bh=bg?"kendo"+bg.fn.options.prefix+bg.fn.options.name:"";
if(a6){bi=new RegExp("^kendo.*"+bd+"$","i");
}else{bi=new RegExp("^"+bh+"$","i");
}for(var a8 in a3){if(a8.match(bi)){if(a8===bh){bc=a3[a8];
}else{return a3[a8];
}}}if(!bg){return;
}a4=ay(a5,"dataSource");
bb=l.extend({},az(a5,bg.fn.options),bb);
if(a4){if(typeof a4===aN){bb.dataSource=ag.getter(a4)(aZ);
}else{bb.dataSource=a4;
}}for(a7=0,a9=bg.fn.events.length;
a7<a9;
a7++){ba=bg.fn.events[a7];
bf=ay(a5,ba);
if(bf!==aV){bb[ba]=ag.getter(bf)(aZ);
}}if(!bc){bc=new bg(a5,bb);
}else{if(!l.isEmptyObject(bb)){bc.setOptions(bb);
}}return bc;
};
ag.rolesFromNamespaces=function(a5){var a6=[],a3,a4;
if(!a5[0]){a5=[ag.ui,ag.dataviz.ui];
}for(a3=0,a4=a5.length;
a3<a4;
a3++){a6[a3]=a5[a3].roles;
}return N.apply(null,[{}].concat(a6.reverse()));
};
ag.init=function(a3){var a4=ag.rolesFromNamespaces(aM.call(arguments,1));
l(a3).find("[data-"+ag.ns+"role]").addBack().each(function(){ag.initWidget(this,{},a4);
});
};
ag.destroy=function(a3){l(a3).find("[data-"+ag.ns+"role]").addBack().each(function(){var a4=l(this).data();
for(var a5 in a4){if(a5.indexOf("kendo")===0&&typeof a4[a5].destroy===Q){a4[a5].destroy();
}}});
};
function x(a3,a4){return l.contains(a3,a4)?-1:1;
}function aG(){var a3=l(this);
return l.inArray(a3.attr("data-"+ag.ns+"role"),["slider","rangeslider"])>-1||a3.is(":visible");
}ag.resize=function(a3,a4){var a5=l(a3).find("[data-"+ag.ns+"role]").addBack().filter(aG);
if(!a5.length){return;
}var a6=l.makeArray(a5);
a6.sort(x);
l.each(a6,function(){var a7=ag.widgetInstance(l(this));
if(a7){a7.resize(a4);
}});
};
ag.parseOptions=az;
N(ag.ui,{Widget:aY,DataBoundWidget:A,roles:{},progress:function(a4,ba){var a8=a4.find(".k-loading-mask"),a9=ag.support,a3=a9.browser,a6,a7,bb,a5;
if(ba){if(!a8.length){a6=a9.isRtl(a4);
a7=a6?"right":"left";
a5=a4.scrollLeft();
bb=a3.webkit?!a6?0:a4[0].scrollWidth-a4.width()-2*a5:0;
a8=l("<div class='k-loading-mask'><span class='k-loading-text'>Loading...</span><div class='k-loading-image'/><div class='k-loading-color'/></div>").width("100%").height("100%").css("top",a4.scrollTop()).css(a7,Math.abs(a5)+bb).prependTo(a4);
}}else{if(a8){a8.remove();
}}},plugin:function(a9,a8,a7){var a6=a9.fn.options.name,a3;
a8=a8||ag.ui;
a7=a7||"";
a8[a6]=a9;
a8.roles[a6.toLowerCase()]=a9;
a3="getKendo"+a7+a6;
a6="kendo"+a7+a6;
var ba={name:a6,widget:a9,prefix:a7||""};
ag.widgets.push(ba);
for(var a4=0,a5=ag._widgetRegisteredCallbacks.length;
a4<a5;
a4++){ag._widgetRegisteredCallbacks[a4](ba);
}l.fn[a6]=function(bc){var bd=this,bb;
if(typeof bc===aN){bb=aM.call(arguments,1);
this.each(function(){var bg=l.data(this,a6),be,bf;
if(!bg){throw new Error(ag.format("Cannot call method '{0}' of {1} before it is initialized",bc,a6));
}be=bg[bc];
if(typeof be!==Q){throw new Error(ag.format("Cannot find method '{0}' of {1}",bc,a6));
}bf=be.apply(bg,bb);
if(bf!==aV){bd=bf;
return false;
}});
}else{this.each(function(){return new a9(this,bc);
});
}return bd;
};
l.fn[a6].widget=a9;
l.fn[a3]=function(){return this.data(a6);
};
}});
var w={bind:function(){return this;
},nullObject:true,options:{}};
var al=aY.extend({init:function(a3,a4){aY.fn.init.call(this,a3,a4);
this.element.autoApplyNS();
this.wrapper=this.element;
this.element.addClass("km-widget");
},destroy:function(){aY.fn.destroy.call(this);
this.element.kendoDestroy();
},options:{prefix:"Mobile"},events:[],view:function(){var a3=this.element.closest(ag.roleSelector("view splitview modalview drawer"));
return ag.widgetInstance(a3,ag.mobile.ui)||w;
},viewHasNativeScrolling:function(){var a3=this.view();
return a3&&a3.options.useNativeScrolling;
},container:function(){var a3=this.element.closest(ag.roleSelector("view layout modalview drawer splitview"));
return ag.widgetInstance(a3.eq(0),ag.mobile.ui)||w;
}});
N(ag.mobile,{init:function(a3){ag.init(a3,ag.mobile.ui,ag.ui,ag.dataviz.ui);
},appLevelNativeScrolling:function(){return ag.mobile.application&&ag.mobile.application.options&&ag.mobile.application.options.useNativeScrolling;
},roles:{},ui:{Widget:al,DataBoundWidget:A.extend(al.prototype),roles:{},plugin:function(a3){ag.ui.plugin(a3,ag.mobile.ui,"Mobile");
}}});
B(ag.dataviz,{init:function(a3){ag.init(a3,ag.dataviz.ui);
},ui:{roles:{},themes:{},views:[],plugin:function(a3){ag.ui.plugin(a3,ag.dataviz.ui);
}},roles:{}});
ag.touchScroller=function(a3,a4){if(!a4){a4={};
}a4.useNative=true;
return l(a3).map(function(a6,a5){a5=l(a5);
if(aO.kineticScrollNeeded&&ag.mobile.ui.Scroller&&!a5.data("kendoMobileScroller")){a5.kendoMobileScroller(a4);
return a5.data("kendoMobileScroller");
}else{return false;
}})[0];
};
ag.preventDefault=function(a3){a3.preventDefault();
};
ag.widgetInstance=function(a3,a8){var a7=a3.data(ag.ns+"role"),ba=[],a4,a6;
if(a7){if(a7==="content"){a7="scroller";
}if(a8){if(a8[0]){for(a4=0,a6=a8.length;
a4<a6;
a4++){ba.push(a8[a4].roles[a7]);
}}else{ba.push(a8.roles[a7]);
}}else{ba=[ag.ui.roles[a7],ag.dataviz.ui.roles[a7],ag.mobile.ui.roles[a7]];
}if(a7.indexOf(".")>=0){ba=[ag.getter(a7)(aZ)];
}for(a4=0,a6=ba.length;
a4<a6;
a4++){var a9=ba[a4];
if(a9){var a5=a3.data("kendo"+a9.fn.options.prefix+a9.fn.options.name);
if(a5){return a5;
}}}}};
ag.onResize=function(a3){var a4=a3;
if(aO.mobileOS.android){a4=function(){setTimeout(a3,600);
};
}l(aZ).on(aO.resize,a4);
return a4;
};
ag.unbindResize=function(a3){l(aZ).off(aO.resize,a3);
};
ag.attrValue=function(a3,a4){return a3.data(ag.ns+a4);
};
ag.days={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
function O(a3,a4){var a5=a3.nodeName.toLowerCase();
return(/input|select|textarea|button|object/.test(a5)?!a3.disabled:"a"===a5?a3.href||a4:a4)&&aX(a3);
}function aX(a3){return l.expr.filters.visible(a3)&&!l(a3).parents().addBack().filter(function(){return l.css(this,"visibility")==="hidden";
}).length;
}l.extend(l.expr[":"],{kendoFocusable:function(a3){var a4=l.attr(a3,"tabindex");
return O(a3,!isNaN(a4)&&a4>-1);
}});
var am=["mousedown","mousemove","mouseenter","mouseleave","mouseover","mouseout","mouseup","click"];
var M="label, input, [data-rel=external]";
var an={setupMouseMute:function(){var a5=0,a6=am.length,a3=document.documentElement;
if(an.mouseTrap||!aO.eventCapture){return;
}an.mouseTrap=true;
an.bustClick=false;
an.captureMouse=false;
var a4=function(a7){if(an.captureMouse){if(a7.type==="click"){if(an.bustClick&&!l(a7.target).is(M)){a7.preventDefault();
a7.stopPropagation();
}}else{a7.stopPropagation();
}}};
for(;
a5<a6;
a5++){a3.addEventListener(am[a5],a4,true);
}},muteMouse:function(a3){an.captureMouse=true;
if(a3.data.bustClick){an.bustClick=true;
}clearTimeout(an.mouseTrapTimeoutID);
},unMuteMouse:function(){clearTimeout(an.mouseTrapTimeoutID);
an.mouseTrapTimeoutID=setTimeout(function(){an.captureMouse=false;
an.bustClick=false;
},400);
}};
var J={down:"touchstart mousedown",move:"mousemove touchmove",up:"mouseup touchend touchcancel",cancel:"mouseleave touchcancel"};
if(aO.touch&&(aO.mobileOS.ios||aO.mobileOS.android)){J={down:"touchstart",move:"touchmove",up:"touchend touchcancel",cancel:"touchcancel"};
}else{if(aO.pointers){J={down:"pointerdown",move:"pointermove",up:"pointerup",cancel:"pointercancel pointerleave"};
}else{if(aO.msPointers){J={down:"MSPointerDown",move:"MSPointerMove",up:"MSPointerUp",cancel:"MSPointerCancel MSPointerLeave"};
}}}if(aO.msPointers&&!("onmspointerenter" in aZ)){l.each({MSPointerEnter:"MSPointerOver",MSPointerLeave:"MSPointerOut"},function(a4,a3){l.event.special[a4]={delegateType:a3,bindType:a3,handle:function(a5){var a8,a9=this,a7=a5.relatedTarget,a6=a5.handleObj;
if(!a7||a7!==a9&&!l.contains(a9,a7)){a5.type=a6.origType;
a8=a6.handler.apply(this,arguments);
a5.type=a3;
}return a8;
}};
});
}var T=function(a3){return J[a3]||a3;
},K=/([^ ]+)/g;
ag.applyEventMap=function(a3,a4){a3=a3.replace(K,T);
if(a4){a3=a3.replace(K,"$1."+a4);
}return a3;
};
var av=l.fn.on;
function ah(a4,a3){return new ah.fn.init(a4,a3);
}N(true,ah,l);
ah.fn=ah.prototype=new l();
ah.fn.constructor=ah;
ah.fn.init=function(a4,a3){if(a3&&a3 instanceof l&&!(a3 instanceof ah)){a3=ah(a3);
}return l.fn.init.call(this,a4,a3,aH);
};
ah.fn.init.prototype=ah.fn;
var aH=ah(document);
N(ah.fn,{handler:function(a3){this.data("handler",a3);
return this;
},autoApplyNS:function(a3){this.data("kendoNS",a3||ag.guid());
return this;
},on:function(){var ba=this,a8=ba.data("kendoNS");
if(arguments.length===1){return av.call(ba,arguments[0]);
}var a6=ba,a3=aM.call(arguments);
if(typeof a3[a3.length-1]===aW){a3.pop();
}var a5=a3[a3.length-1],a7=ag.applyEventMap(a3[0],a8);
if(aO.mouseAndTouchPresent&&a7.search(/mouse|click/)>-1&&this[0]!==document.documentElement){an.setupMouseMute();
var a9=a3.length===2?null:a3[1],a4=a7.indexOf("click")>-1&&a7.indexOf("touchend")>-1;
av.call(this,{touchstart:an.muteMouse,touchend:an.unMuteMouse},a9,{bustClick:a4});
}if(typeof a5===aN){a6=ba.data("handler");
a5=a6[a5];
a3[a3.length-1]=function(bb){a5.call(a6,bb);
};
}a3[0]=a7;
av.apply(ba,a3);
return ba;
},kendoDestroy:function(a3){a3=a3||this.data("kendoNS");
if(a3){this.off("."+a3);
}return this;
}});
ag.jQuery=ah;
ag.eventMap=J;
ag.timezone=function(){var a9={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};
var a6={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function bc(bn,bk){var bg;
var bl;
var bj;
var bh=bk[3];
var bi=bk[4];
var bm=bk[5];
var bf=bk[8];
if(!bf){bk[8]=bf={};
}if(bf[bn]){return bf[bn];
}if(!isNaN(bi)){bg=new Date(Date.UTC(bn,a9[bh],bi,bm[0],bm[1],bm[2],0));
}else{if(bi.indexOf("last")===0){bg=new Date(Date.UTC(bn,a9[bh]+1,1,bm[0]-24,bm[1],bm[2],0));
bl=a6[bi.substr(4,3)];
bj=bg.getUTCDay();
bg.setUTCDate(bg.getUTCDate()+bl-bj-(bl>bj?7:0));
}else{if(bi.indexOf(">=")>=0){bg=new Date(Date.UTC(bn,a9[bh],bi.substr(5),bm[0],bm[1],bm[2],0));
bl=a6[bi.substr(0,3)];
bj=bg.getUTCDay();
bg.setUTCDate(bg.getUTCDate()+bl-bj+(bl<bj?7:0));
}}}return bf[bn]=bg;
}function a7(bj,bh,bl){bh=bh[bl];
if(!bh){var bi=bl.split(":");
var bf=0;
if(bi.length>1){bf=bi[0]*60+Number(bi[1]);
}return[-1000000,"max","-","Jan",1,[0,0,0],bf,"-"];
}var bk=new Date(bj).getUTCFullYear();
bh=g.grep(bh,function(bn){var bm=bn[0];
var bo=bn[1];
return bm<=bk&&(bo>=bk||bm==bk&&bo=="only"||bo=="max");
});
bh.push(bj);
bh.sort(function(bm,bn){if(typeof bm!="number"){bm=Number(bc(bk,bm));
}if(typeof bn!="number"){bn=Number(bc(bk,bn));
}return bm-bn;
});
var bg=bh[g.inArray(bj,bh)-1]||bh[bh.length-1];
return isNaN(bg)?bg:null;
}function a8(bi,bl,bg){var bk=bl[bg];
if(typeof bk==="string"){bk=bl[bk];
}if(!bk){throw new Error('Timezone "'+bg+'" is either incorrect, or kendo.timezones.min.js is not included.');
}for(var bf=bk.length-1;
bf>=0;
bf--){var bh=bk[bf][3];
if(bh&&bi>bh){break;
}}var bj=bk[bf+1];
if(!bj){throw new Error('Timezone "'+bg+'" not found on '+bi+".");
}return bj;
}function be(bh,bj,bf,bg){if(typeof bh!=aq){bh=Date.UTC(bh.getFullYear(),bh.getMonth(),bh.getDate(),bh.getHours(),bh.getMinutes(),bh.getSeconds(),bh.getMilliseconds());
}var bi=a8(bh,bj,bg);
return{zone:bi,rule:a7(bh,bf,bi[1])};
}function ba(bi,bh){if(bh=="Etc/UTC"||bh=="Etc/GMT"){return 0;
}var bf=be(bi,this.zones,this.rules,bh);
var bj=bf.zone;
var bg=bf.rule;
return ag.parseFloat(bg?bj[0]-bg[6]:bj[0]);
}function a3(bj,bi){var bg=be(bj,this.zones,this.rules,bi);
var bk=bg.zone;
var bh=bg.rule;
var bf=bk[2];
if(bf.indexOf("/")>=0){return bf.split("/")[bh&&+bh[6]?1:0];
}else{if(bf.indexOf("%s")>=0){return bf.replace("%s",!bh||bh[7]=="-"?"":bh[7]);
}}return bf;
}function a5(bf,bh,bj){if(typeof bh==aN){bh=this.offset(bf,bh);
}if(typeof bj==aN){bj=this.offset(bf,bj);
}var bg=bf.getTimezoneOffset();
bf=new Date(bf.getTime()+(bh-bj)*60000);
var bi=bf.getTimezoneOffset();
return new Date(bf.getTime()+(bi-bg)*60000);
}function a4(bf,bg){return this.convert(bf,bf.getTimezoneOffset(),bg);
}function bb(bf,bg){return this.convert(bf,bg,bf.getTimezoneOffset());
}function bd(bf){return this.apply(new Date(bf),"Etc/UTC");
}return{zones:{},rules:{},offset:ba,convert:a5,apply:a4,remove:bb,abbr:a3,toLocalDate:bd};
}();
ag.date=function(){var be=60000,bd=86400000;
function a4(bl,bm){if(bm===0&&bl.getHours()===23){bl.setHours(bl.getHours()+2);
return true;
}return false;
}function bf(bl,bm,bn){var bo=bl.getHours();
bn=bn||1;
bm=(bm-bl.getDay()+7*bn)%7;
bl.setDate(bl.getDate()+bm);
a4(bl,bo);
}function a5(bl,bm,bn){bl=new Date(bl);
bf(bl,bm,bn);
return bl;
}function a6(bl){return new Date(bl.getFullYear(),bl.getMonth(),1);
}function bc(bl){var bn=new Date(bl.getFullYear(),bl.getMonth()+1,0),bm=a6(bl),bo=Math.abs(bn.getTimezoneOffset()-bm.getTimezoneOffset());
if(bo){bn.setHours(bm.getHours()+bo/60);
}return bn;
}function a7(bl){bl=new Date(bl.getFullYear(),bl.getMonth(),bl.getDate(),0,0,0);
a4(bl,0);
return bl;
}function bk(bl){return Date.UTC(bl.getFullYear(),bl.getMonth(),bl.getDate(),bl.getHours(),bl.getMinutes(),bl.getSeconds(),bl.getMilliseconds());
}function a8(bl){return bl.getTime()-a7(bl);
}function ba(bq,bm,bl){var bo=a8(bm),bn=a8(bl),bp;
if(!bq||bo==bn){return true;
}if(bm>=bl){bl+=bd;
}bp=a8(bq);
if(bo>bp){bp+=bd;
}if(bn<bo){bn+=bd;
}return bp>=bo&&bp<=bn;
}function a9(bq,bm,bl){var bo=bm.getTime(),bn=bl.getTime(),bp;
if(bo>=bn){bn+=bd;
}bp=bq.getTime();
return bp>=bo&&bp<=bn;
}function a3(bl,bn){var bm=bl.getHours();
bl=new Date(bl);
bh(bl,bn*bd);
a4(bl,bm);
return bl;
}function bh(bl,bo,bn){var bp=bl.getTimezoneOffset();
var bm;
bl.setTime(bl.getTime()+bo);
if(!bn){bm=bl.getTimezoneOffset()-bp;
bl.setTime(bl.getTime()+bm*be);
}}function bg(bl,bm){bl=new Date(ag.date.getDate(bl).getTime()+ag.date.getMilliseconds(bm));
a4(bl,bm.getHours());
return bl;
}function bi(){return a7(new Date());
}function bb(bl){return a7(bl).getTime()==bi().getTime();
}function bj(bl){var bm=new Date(1980,1,1,0,0,0);
if(bl){bm.setHours(bl.getHours(),bl.getMinutes(),bl.getSeconds(),bl.getMilliseconds());
}return bm;
}return{adjustDST:a4,dayOfWeek:a5,setDayOfWeek:bf,getDate:a7,isInDateRange:a9,isInTimeRange:ba,isToday:bb,nextDay:function(bl){return a3(bl,1);
},previousDay:function(bl){return a3(bl,-1);
},toUtcTime:bk,MS_PER_DAY:bd,MS_PER_HOUR:60*be,MS_PER_MINUTE:be,setTime:bh,setHours:bg,addDays:a3,today:bi,toInvariantTime:bj,firstDayOfMonth:a6,lastDayOfMonth:bc,getMilliseconds:a8};
}();
ag.stripWhitespace=function(a4){if(document.createNodeIterator){var a6=document.createNodeIterator(a4,NodeFilter.SHOW_TEXT,function(a7){return a7.parentNode==a4?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT;
},false);
while(a6.nextNode()){if(a6.referenceNode&&!a6.referenceNode.textContent.trim()){a6.referenceNode.parentNode.removeChild(a6.referenceNode);
}}}else{for(var a5=0;
a5<a4.childNodes.length;
a5++){var a3=a4.childNodes[a5];
if(a3.nodeType==3&&!/\S/.test(a3.nodeValue)){a4.removeChild(a3);
a5--;
}if(a3.nodeType==1){ag.stripWhitespace(a3);
}}}};
var o=aZ.requestAnimationFrame||aZ.webkitRequestAnimationFrame||aZ.mozRequestAnimationFrame||aZ.oRequestAnimationFrame||aZ.msRequestAnimationFrame||function(a3){setTimeout(a3,1000/60);
};
ag.animationFrame=function(a3){o.call(aZ,a3);
};
var p=[];
ag.queueAnimation=function(a3){p[p.length]=a3;
if(p.length===1){ag.runNextAnimation();
}};
ag.runNextAnimation=function(){ag.animationFrame(function(){if(p[0]){p.shift()();
if(p[0]){ag.runNextAnimation();
}}});
};
ag.parseQueryStringParams=function(a8){var a7=a8.split("?")[1]||"",a6={},a5=a7.split(/&|=/),a4=a5.length,a3=0;
for(;
a3<a4;
a3+=2){if(a5[a3]!==""){a6[decodeURIComponent(a5[a3])]=decodeURIComponent(a5[a3+1]);
}}return a6;
};
ag.elementUnderCursor=function(a3){if(typeof a3.x.client!="undefined"){return document.elementFromPoint(a3.x.client,a3.y.client);
}};
ag.wheelDeltaY=function(a6){var a5=a6.originalEvent,a4=a5.wheelDeltaY,a3;
if(a5.wheelDelta){if(a4===aV||a4){a3=a5.wheelDelta;
}}else{if(a5.detail&&a5.axis===a5.VERTICAL_AXIS){a3=-a5.detail*10;
}}return a3;
};
ag.throttle=function(a4,a3){var a7;
var a5=0;
if(!a3||a3<=0){return a4;
}var a6=function(){var bb=this;
var a9=+new Date()-a5;
var a8=arguments;
function ba(){a4.apply(bb,a8);
a5=+new Date();
}if(!a5){return ba();
}if(a7){clearTimeout(a7);
}if(a9>a3){ba();
}else{a7=setTimeout(ba,a3-a9);
}};
a6.cancel=function(){clearTimeout(a7);
};
return a6;
};
ag.caret=function(a4,bb,a5){var a8;
var a6=bb!==aV;
if(a5===aV){a5=bb;
}if(a4[0]){a4=a4[0];
}if(a6&&a4.disabled){return;
}try{if(a4.selectionStart!==aV){if(a6){a4.focus();
a4.setSelectionRange(bb,a5);
}else{bb=[a4.selectionStart,a4.selectionEnd];
}}else{if(document.selection){if(l(a4).is(":visible")){a4.focus();
}a8=a4.createTextRange();
if(a6){a8.collapse(true);
a8.moveStart("character",bb);
a8.moveEnd("character",a5-bb);
a8.select();
}else{var a7=a8.duplicate(),ba,a9;
a8.moveToBookmark(document.selection.createRange().getBookmark());
a7.setEndPoint("EndToStart",a8);
ba=a7.text.length;
a9=ba+a8.text.length;
bb=[ba,a9];
}}}}catch(a3){bb=[];
}return bb;
};
ag.compileMobileDirective=function(a4,a5){var a3=aZ.angular;
a4.attr("data-"+ag.ns+"role",a4[0].tagName.toLowerCase().replace("kendo-mobile-","").replace("-",""));
a3.element(a4).injector().invoke(["$compile",function(a6){a6(a4)(a5);
if(!/^\$(digest|apply)$/.test(a5.$$phase)){a5.$digest();
}}]);
return ag.widgetInstance(a4,ag.mobile.ui);
};
ag.antiForgeryTokens=function(){var a5={},a4=l("meta[name=csrf-token],meta[name=_csrf]").attr("content"),a3=l("meta[name=csrf-param],meta[name=_csrf_header]").attr("content");
l("input[name^='__RequestVerificationToken']").each(function(){a5[this.name]=this.value;
});
if(a3!==aV&&a4!==aV){a5[a3]=a4;
}return a5;
};
ag.cycleForm=function(a5){var a3=a5.find("input, .k-widget").first();
var a6=a5.find("button, .k-button").last();
function a4(a7){var a8=ag.widgetInstance(a7);
if(a8&&a8.focus){a8.focus();
}else{a7.focus();
}}a6.on("keydown",function(a7){if(a7.keyCode==ag.keys.TAB&&!a7.shiftKey){a7.preventDefault();
a4(a3);
}});
a3.on("keydown",function(a7){if(a7.keyCode==ag.keys.TAB&&a7.shiftKey){a7.preventDefault();
a4(a6);
}});
};
(function(){function a5(a9,ba,bf,be){var bb=l("<form>").attr({action:bf,method:"POST",target:be});
var a8=ag.antiForgeryTokens();
a8.fileName=ba;
var bd=a9.split(";base64,");
a8.contentType=bd[0].replace("data:","");
a8.base64=bd[1];
for(var bc in a8){if(a8.hasOwnProperty(bc)){l("<input>").attr({value:a8[bc],name:bc,type:"hidden"}).appendTo(bb);
}}bb.appendTo("body").submit().remove();
}var a4=document.createElement("a");
var a3="download" in a4&&!ag.support.browser.edge;
function a6(bc,bd){var ba=bc;
if(typeof bc=="string"){var bf=bc.split(";base64,");
var bb=bf[0];
var a9=atob(bf[1]);
var a8=new Uint8Array(a9.length);
for(var be=0;
be<a9.length;
be++){a8[be]=a9.charCodeAt(be);
}ba=new Blob([a8.buffer],{type:bb});
}navigator.msSaveBlob(ba,bd);
}function a7(a8,ba){if(aZ.Blob&&a8 instanceof Blob){a8=URL.createObjectURL(a8);
}a4.download=ba;
a4.href=a8;
var a9=document.createEvent("MouseEvents");
a9.initMouseEvent("click",true,false,aZ,0,0,0,0,0,false,false,false,false,0,null);
a4.dispatchEvent(a9);
}ag.saveAs=function(a8){var a9=a5;
if(!a8.forceProxy){if(a3){a9=a7;
}else{if(navigator.msSaveBlob){a9=a6;
}}}a9(a8.dataURI,a8.fileName,a8.proxyURL,a8.proxyTarget);
};
}());
ag.proxyModelSetters=function aE(a3){var a4={};
Object.keys(a3||{}).forEach(function(a5){Object.defineProperty(a4,a5,{get:function(){return a3[a5];
},set:function(a6){a3[a5]=a6;
a3.dirty=true;
}});
});
return a4;
};
}($telerik.$,window));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
