(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.dom",["kendo.core"],l);
}(function(){var k={id:"dom",name:"Virtual DOM",category:"framework",depends:["core"],advanced:true};
(function(r){function s(){this.node=null;
}s.prototype={remove:function(){this.node.parentNode.removeChild(this.node);
this.attr={};
},attr:{},text:function(){return"";
}};
function u(){}u.prototype={nodeName:"#null",attr:{style:{}},children:[],remove:function(){}};
var t=new u();
function m(A,y,z){this.nodeName=A;
this.attr=y||{};
this.children=z||[];
}m.prototype=new s();
m.prototype.appendTo=function(B){var A=document.createElement(this.nodeName);
var y=this.children;
for(var z=0;
z<y.length;
z++){y[z].render(A,t);
}B.appendChild(A);
return A;
};
m.prototype.render=function(F,y){var E;
if(y.nodeName!==this.nodeName){y.remove();
E=this.appendTo(F);
}else{E=y.node;
var C;
var B=this.children;
var D=B.length;
var z=y.children;
var A=z.length;
if(Math.abs(A-D)>2){this.render({appendChild:function(G){F.replaceChild(G,y.node);
}},t);
return;
}for(C=0;
C<D;
C++){B[C].render(E,z[C]||t);
}for(C=D;
C<A;
C++){z[C].remove();
}}this.node=E;
this.syncAttributes(y.attr);
this.removeAttributes(y.attr);
};
m.prototype.syncAttributes=function(z){var y=this.attr;
for(var B in y){var C=y[B];
var A=z[B];
if(B==="style"){this.setStyle(C,A);
}else{if(C!==A){this.setAttribute(B,C,A);
}}}};
m.prototype.setStyle=function(B,y){var A=this.node;
var z;
if(y){for(z in B){if(B[z]!==y[z]){A.style[z]=B[z];
}}}else{for(z in B){A.style[z]=B[z];
}}};
m.prototype.removeStyle=function(y){var B=this.attr.style||{};
var A=this.node;
for(var z in y){if(B[z]===j){A.style[z]="";
}}};
m.prototype.removeAttributes=function(z){var y=this.attr;
for(var A in z){if(A==="style"){this.removeStyle(z.style);
}else{if(y[A]===j){this.removeAttribute(A);
}}}};
m.prototype.removeAttribute=function(y){var z=this.node;
if(y==="style"){z.style.cssText="";
}else{if(y==="className"){z.className="";
}else{z.removeAttribute(y);
}}};
m.prototype.setAttribute=function(y,A){var z=this.node;
if(z[y]!==j){z[y]=A;
}else{z.setAttribute(y,A);
}};
m.prototype.text=function(){var z="";
for(var y=0;
y<this.children.length;
++y){z+=this.children[y].text();
}return z;
};
function w(y){this.nodeValue=y;
}w.prototype=new s();
w.prototype.nodeName="#text";
w.prototype.render=function(A,y){var z;
if(y.nodeName!==this.nodeName){y.remove();
z=document.createTextNode(this.nodeValue);
A.appendChild(z);
}else{z=y.node;
if(this.nodeValue!==y.nodeValue){z.nodeValue=this.nodeValue;
}}this.node=z;
};
w.prototype.text=function(){return this.nodeValue;
};
function p(y){this.html=y;
}p.prototype={nodeName:"#html",attr:{},remove:function(){for(var y=0;
y<this.nodes.length;
y++){this.nodes[y].parentNode.removeChild(this.nodes[y]);
}},render:function(B,y){if(y.nodeName!==this.nodeName||y.html!==this.html){y.remove();
var A=B.lastChild;
q(B,this.html);
this.nodes=[];
for(var z=A?A.nextSibling:B.firstChild;
z;
z=z.nextSibling){this.nodes.push(z);
}}else{this.nodes=y.nodes.slice(0);
}}};
var o=document.createElement("div");
function q(z,y){o.innerHTML=y;
while(o.firstChild){z.appendChild(o.firstChild);
}}function n(y){return new p(y);
}function l(A,y,z){return new m(A,y,z);
}function v(y){return new w(y);
}function x(y){this.root=y;
this.children=[];
}x.prototype={html:n,element:l,text:v,render:function(z){var y=this.children;
var A;
var B;
for(A=0,B=z.length;
A<B;
A++){z[A].render(this.root,y[A]||t);
}for(A=B;
A<y.length;
A++){y[A].remove();
}this.children=z;
}};
r.dom={html:n,text:v,element:l,Tree:x,Node:s};
}(window.kendo));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
