(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.fx",["kendo.core"],l);
}(function(){var k={id:"fx",name:"Effects",category:"framework",description:"Required for animation effects in all Kendo UI widgets.",depends:["core"]};
(function(l,ay){var P=window.kendo,J=P.effects,E=l.each,H=l.extend,ab=l.proxy,aj=P.support,s=aj.browser,aq=aj.transforms,au=aj.transitions,ag={scale:0,scalex:0,scaley:0,scale3d:0},aw={translate:0,translatex:0,translatey:0,translate3d:0},K=typeof document.documentElement.style.zoom!=="undefined"&&!aq,R=/matrix3?d?\s*\(.*,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?,\s*([\d\.\-]+)\w*?/i,z=/^(-?[\d\.\-]+)?[\w\s]*,?\s*(-?[\d\.\-]+)?[\w\s]*/i,ax=/translatex?$/i,U=/(zoom|fade|expand)(\w+)/,ah=/(zoom|fade|expand)/,az=/[xy]$/i,ap=["perspective","rotate","rotatex","rotatey","rotatez","rotate3d","scale","scalex","scaley","scalez","scale3d","skew","skewx","skewy","translate","translatex","translatey","translatez","translate3d","matrix","matrix3d"],an=["rotate","scale","scalex","scaley","skew","skewx","skewy","translate","translatex","translatey","matrix"],ao={rotate:"deg",scale:"",skew:"px",translate:"px"},A=aq.css,af=Math.round,r="",ac="px",S="none",p="auto",aA="width",L="height",M="hidden",V="origin",m="abortId",W="overflow",av="translate",aa="position",w="completeCallback",at=A+"transition",al=A+"transform",q=A+"backface-visibility",Z=A+"perspective",C="1500px",am="perspective("+C+")",D={left:{reverse:"right",property:"left",transition:"translatex",vertical:false,modifier:-1},right:{reverse:"left",property:"left",transition:"translatex",vertical:false,modifier:1},down:{reverse:"up",property:"top",transition:"translatey",vertical:true,modifier:1},up:{reverse:"down",property:"top",transition:"translatey",vertical:true,modifier:-1},top:{reverse:"bottom"},bottom:{reverse:"top"},"in":{reverse:"out",modifier:-1},out:{reverse:"in",modifier:1},vertical:{reverse:"vertical"},horizontal:{reverse:"horizontal"}};
P.directions=D;
H(l.fn,{kendoStop:function(aB,aC){if(au){return J.stopQueue(this,aB||false,aC||false);
}else{return this.stop(aB,aC);
}}});
if(aq&&!au){E(an,function(aB,aC){l.fn[aC]=function(aF){if(typeof aF=="undefined"){return o(this,aC);
}else{var aD=l(this)[0],aE=aC+"("+aF+ao[aC.replace(az,"")]+")";
if(aD.style.cssText.indexOf(al)==-1){l(this).css(al,aE);
}else{aD.style.cssText=aD.style.cssText.replace(new RegExp(aC+"\\(.*?\\)","i"),aE);
}}return this;
};
l.fx.step[aC]=function(aD){l(aD.elem)[aC](aD.now);
};
});
var B=l.fx.prototype.cur;
l.fx.prototype.cur=function(){if(an.indexOf(this.prop)!=-1){return parseFloat(l(this.elem)[this.prop]());
}return B.apply(this,arguments);
};
}P.toggleClass=function(aD,aC,aE,aB){if(aC){aC=aC.split(" ");
if(au){aE=H({exclusive:"all",duration:400,ease:"ease-out"},aE);
aD.css(at,aE.exclusive+" "+aE.duration+"ms "+aE.ease);
setTimeout(function(){aD.css(at,"").css(L);
},aE.duration);
}E(aC,function(aF,aG){aD.toggleClass(aG,aB);
});
}return aD;
};
P.parseEffects=function(aC,aD){var aB={};
if(typeof aC==="string"){E(aC.split(" "),function(aH,aK){var aI=!ah.test(aK),aJ=aK.replace(U,function(aN,aL,aM){return aL+":"+aM.toLowerCase();
}),aF=aJ.split(":"),aE=aF[1],aG={};
if(aF.length>1){aG.direction=aD&&aI?D[aE].reverse:aE;
}aB[aF[0]]=aG;
});
}else{E(aC,function(aF){var aE=this.direction;
if(aE&&aD&&!ah.test(aF)){this.direction=D[aE].reverse;
}aB[aF]=this;
});
}return aB;
};
function Y(aB){return parseInt(aB,10);
}function X(aB,aC){return Y(aB.css(aC));
}function Q(aC){var aB=[];
for(var aD in aC){aB.push(aD);
}return aB;
}function ai(aC){for(var aB in aC){if(ap.indexOf(aB)!=-1&&an.indexOf(aB)==-1){delete aC[aB];
}}return aC;
}function T(aC,aG){var aH=[],aB={},aF,aE,aI,aD;
for(aE in aG){aF=aE.toLowerCase();
aD=aq&&ap.indexOf(aF)!=-1;
if(!aj.hasHW3D&&aD&&an.indexOf(aF)==-1){delete aG[aE];
}else{aI=aG[aE];
if(aD){aH.push(aE+"("+aI+")");
}else{aB[aE]=aI;
}}}if(aH.length){aB[al]=aH.join(" ");
}return aB;
}if(au){H(J,{transition:function(aD,aG,aF){var aB,aC=0,aE=aD.data("keys")||[],aJ;
aF=H({duration:200,ease:"ease-out",complete:null,exclusive:"all"},aF);
var aI=false;
var aH=function(){if(!aI){aI=true;
if(aJ){clearTimeout(aJ);
aJ=null;
}aD.removeData(m).dequeue().css(at,"").css(at);
aF.complete.call(aD);
}};
aF.duration=l.fx?l.fx.speeds[aF.duration]||aF.duration:aF.duration;
aB=T(aD,aG);
l.merge(aE,Q(aB));
aD.data("keys",l.unique(aE)).height();
aD.css(at,aF.exclusive+" "+aF.duration+"ms "+aF.ease).css(at);
aD.css(aB).css(al);
if(au.event){aD.one(au.event,aH);
if(aF.duration!==0){aC=500;
}}aJ=setTimeout(aH,aF.duration+aC);
aD.data(m,aJ);
aD.data(w,aH);
},stopQueue:function(aE,aB,aF){var aD,aH=aE.data("keys"),aG=!aF&&aH,aC=aE.data(w);
if(aG){aD=P.getComputedStyles(aE[0],aH);
}if(aC){aC();
}if(aG){aE.css(aD);
}return aE.removeData("keys").stop(aB);
}});
}function o(aC,aE){if(aq){var aF=aC.css(al);
if(aF==S){return aE=="scale"?1:0;
}var aD=aF.match(new RegExp(aE+"\\s*\\(([\\d\\w\\.]+)")),aB=0;
if(aD){aB=Y(aD[1]);
}else{aD=aF.match(R)||[0,0,0,0,0];
aE=aE.toLowerCase();
if(ax.test(aE)){aB=parseFloat(aD[3]/aD[2]);
}else{if(aE=="translatey"){aB=parseFloat(aD[4]/aD[2]);
}else{if(aE=="scale"){aB=parseFloat(aD[2]);
}else{if(aE=="rotate"){aB=parseFloat(Math.atan2(aD[2],aD[1]));
}}}}}return aB;
}else{return parseFloat(aC.css(aE));
}}var G=P.Class.extend({init:function(aB,aC){var aD=this;
aD.element=aB;
aD.effects=[];
aD.options=aC;
aD.restore=[];
},run:function(aG){var aP=this,aE,aJ,aK,aL=aG.length,aH=aP.element,aM=aP.options,aD=l.Deferred(),aN={},aI={},aO,aB,aC;
aP.effects=aG;
aD.then(l.proxy(aP,"complete"));
aH.data("animating",true);
for(aJ=0;
aJ<aL;
aJ++){aE=aG[aJ];
aE.setReverse(aM.reverse);
aE.setOptions(aM);
aP.addRestoreProperties(aE.restore);
aE.prepare(aN,aI);
aB=aE.children();
for(aK=0,aC=aB.length;
aK<aC;
aK++){aB[aK].duration(aM.duration).run();
}}for(var aF in aM.effects){H(aI,aM.effects[aF].properties);
}if(!aH.is(":visible")){H(aN,{display:aH.data("olddisplay")||"block"});
}if(aq&&!aM.reset){aO=aH.data("targetTransform");
if(aO){aN=H(aO,aN);
}}aN=T(aH,aN);
if(aq&&!au){aN=ai(aN);
}aH.css(aN).css(al);
for(aJ=0;
aJ<aL;
aJ++){aG[aJ].setup();
}if(aM.init){aM.init();
}aH.data("targetTransform",aI);
J.animate(aH,aI,H({},aM,{complete:aD.resolve}));
return aD.promise();
},stop:function(){l(this.element).kendoStop(true,true);
},addRestoreProperties:function(aE){var aB=this.element,aF,aC=0,aD=aE.length;
for(;
aC<aD;
aC++){aF=aE[aC];
this.restore.push(aF);
if(!aB.data(aF)){aB.data(aF,aB.css(aF));
}}},restoreCallback:function(){var aB=this.element;
for(var aC=0,aD=this.restore.length;
aC<aD;
aC++){var aE=this.restore[aC];
aB.css(aE,aB.data(aE));
}},complete:function(){var aG=this,aD=0,aC=aG.element,aF=aG.options,aB=aG.effects,aE=aB.length;
aC.removeData("animating").dequeue();
if(aF.hide){aC.data("olddisplay",aC.css("display")).hide();
}this.restoreCallback();
if(K&&!aq){setTimeout(l.proxy(this,"restoreCallback"),0);
}for(;
aD<aE;
aD++){aB[aD].teardown();
}if(aF.completeCallback){aF.completeCallback(aC);
}}});
J.promise=function(aG,aH){var aE=[],aC,aF=new G(aG,aH),aI=P.parseEffects(aH.effects),aB;
aH.effects=aI;
for(var aD in aI){aC=J[t(aD)];
if(aC){aB=new aC(aG,aI[aD].direction);
aE.push(aB);
}}if(aE[0]){aF.run(aE);
}else{if(!aG.is(":visible")){aG.css({display:aG.data("olddisplay")||"block"}).css("display");
}if(aH.init){aH.init();
}aG.dequeue();
aF.complete();
}};
H(J,{animate:function(aB,aD,aC){var aE=aC.transition!==false;
delete aC.transition;
if(au&&"transition" in J&&aE){J.transition(aB,aD,aC);
}else{if(aq){aB.animate(ai(aD),{queue:false,show:false,hide:false,duration:aC.duration,complete:aC.complete});
}else{aB.each(function(){var aF=l(this),aG={};
E(ap,function(aK,aQ){var aN,aH=aD?aD[aQ]+" ":null;
if(aH){var aP=aD;
if(aQ in ag&&aD[aQ]!==ay){aN=aH.match(z);
if(aq){H(aP,{scale:+aN[0]});
}}else{if(aQ in aw&&aD[aQ]!==ay){var aO=aF.css(aa),aL=aO=="absolute"||aO=="fixed";
if(!aF.data(av)){if(aL){aF.data(av,{top:X(aF,"top")||0,left:X(aF,"left")||0,bottom:X(aF,"bottom"),right:X(aF,"right")});
}else{aF.data(av,{top:X(aF,"marginTop")||0,left:X(aF,"marginLeft")||0});
}}var aM=aF.data(av);
aN=aH.match(z);
if(aN){var aI=aQ==av+"y"?+null:+aN[1],aJ=aQ==av+"y"?+aN[1]:+aN[2];
if(aL){if(!isNaN(aM.right)){if(!isNaN(aI)){H(aP,{right:aM.right-aI});
}}else{if(!isNaN(aI)){H(aP,{left:aM.left+aI});
}}if(!isNaN(aM.bottom)){if(!isNaN(aJ)){H(aP,{bottom:aM.bottom-aJ});
}}else{if(!isNaN(aJ)){H(aP,{top:aM.top+aJ});
}}}else{if(!isNaN(aI)){H(aP,{marginLeft:aM.left+aI});
}if(!isNaN(aJ)){H(aP,{marginTop:aM.top+aJ});
}}}}}if(!aq&&aQ!="scale"&&aQ in aP){delete aP[aQ];
}if(aP){H(aG,aP);
}}});
if(s.msie){delete aG.scale;
}aF.animate(aG,{queue:false,show:false,hide:false,duration:aC.duration,complete:aC.complete});
});
}}}});
J.animatedPromise=J.promise;
var F=P.Class.extend({init:function(aC,aB){var aD=this;
aD.element=aC;
aD._direction=aB;
aD.options={};
aD._additionalEffects=[];
if(!aD.restore){aD.restore=[];
}},reverse:function(){this._reverse=true;
return this.run();
},play:function(){this._reverse=false;
return this.run();
},add:function(aB){this._additionalEffects.push(aB);
return this;
},direction:function(aB){this._direction=aB;
return this;
},duration:function(aB){this._duration=aB;
return this;
},compositeRun:function(){var aD=this,aC=new G(aD.element,{reverse:aD._reverse,duration:aD._duration}),aB=aD._additionalEffects.concat([aD]);
return aC.run(aB);
},run:function(){if(this._additionalEffects&&this._additionalEffects[0]){return this.compositeRun();
}var aL=this,aE=aL.element,aG=0,aI=aL.restore,aH=aI.length,aM,aD=l.Deferred(),aJ={},aF={},aK,aB=aL.children(),aC=aB.length;
aD.then(l.proxy(aL,"_complete"));
aE.data("animating",true);
for(aG=0;
aG<aH;
aG++){aM=aI[aG];
if(!aE.data(aM)){aE.data(aM,aE.css(aM));
}}for(aG=0;
aG<aC;
aG++){aB[aG].duration(aL._duration).run();
}aL.prepare(aJ,aF);
if(!aE.is(":visible")){H(aJ,{display:aE.data("olddisplay")||"block"});
}if(aq){aK=aE.data("targetTransform");
if(aK){aJ=H(aK,aJ);
}}aJ=T(aE,aJ);
if(aq&&!au){aJ=ai(aJ);
}aE.css(aJ).css(al);
aL.setup();
aE.data("targetTransform",aF);
J.animate(aE,aF,{duration:aL._duration,complete:aD.resolve});
return aD.promise();
},stop:function(){var aD=0,aB=this.children(),aC=aB.length;
for(aD=0;
aD<aC;
aD++){aB[aD].stop();
}l(this.element).kendoStop(true,true);
return this;
},restoreCallback:function(){var aB=this.element;
for(var aC=0,aD=this.restore.length;
aC<aD;
aC++){var aE=this.restore[aC];
aB.css(aE,aB.data(aE));
}},_complete:function(){var aC=this,aB=aC.element;
aB.removeData("animating").dequeue();
aC.restoreCallback();
if(aC.shouldHide()){aB.data("olddisplay",aB.css("display")).hide();
}if(K&&!aq){setTimeout(l.proxy(aC,"restoreCallback"),0);
}aC.teardown();
},setOptions:function(aB){H(true,this.options,aB);
},children:function(){return[];
},shouldHide:l.noop,setup:l.noop,prepare:l.noop,teardown:l.noop,directions:[],setReverse:function(aB){this._reverse=aB;
return this;
}});
function t(aB){return aB.charAt(0).toUpperCase()+aB.substring(1);
}function x(aE,aB){var aD=F.extend(aB),aC=aD.prototype.directions;
J[t(aE)]=aD;
J.Element.prototype[aE]=function(aF,aG,aH,aI){return new aD(this.element,aF,aG,aH,aI);
};
E(aC,function(aF,aG){J.Element.prototype[aE+t(aG)]=function(aH,aI,aJ){return new aD(this.element,aG,aH,aI,aJ);
};
});
}var I=["left","right","up","down"],O=["in","out"];
x("slideIn",{directions:I,divisor:function(aB){this.options.divisor=aB;
return this;
},prepare:function(aG,aD){var aI=this,aJ,aC=aI.element,aB=D[aI._direction],aF=-aB.modifier*(aB.vertical?aC.outerHeight():aC.outerWidth()),aH=aF/(aI.options&&aI.options.divisor||1)+ac,aE="0px";
if(aI._reverse){aJ=aG;
aG=aD;
aD=aJ;
}if(aq){aG[aB.transition]=aH;
aD[aB.transition]=aE;
}else{aG[aB.property]=aH;
aD[aB.property]=aE;
}}});
x("tile",{directions:I,init:function(aC,aB,aD){F.prototype.init.call(this,aC,aB);
this.options={previous:aD};
},previousDivisor:function(aB){this.options.previousDivisor=aB;
return this;
},children:function(){var aG=this,aF=aG._reverse,aE=aG.options.previous,aD=aG.options.previousDivisor||1,aC=aG._direction;
var aB=[P.fx(aG.element).slideIn(aC).setReverse(aF)];
if(aE){aB.push(P.fx(aE).slideIn(D[aC].reverse).divisor(aD).setReverse(!aF));
}return aB;
}});
function y(aD,aE,aC,aB){x(aD,{directions:O,startValue:function(aF){this._startValue=aF;
return this;
},endValue:function(aF){this._endValue=aF;
return this;
},shouldHide:function(){return this._shouldHide;
},prepare:function(aI,aF){var aM=this,aL,aG,aH=this._direction==="out",aJ=aM.element.data(aE),aK=!(isNaN(aJ)||aJ==aC);
if(aK){aL=aJ;
}else{if(typeof this._startValue!=="undefined"){aL=this._startValue;
}else{aL=aH?aC:aB;
}}if(typeof this._endValue!=="undefined"){aG=this._endValue;
}else{aG=aH?aB:aC;
}if(this._reverse){aI[aE]=aG;
aF[aE]=aL;
}else{aI[aE]=aL;
aF[aE]=aG;
}aM._shouldHide=aF[aE]===aB;
}});
}y("fade","opacity",1,0);
y("zoom","scale",1,0.01);
x("slideMargin",{prepare:function(aI,aC){var aJ=this,aB=aJ.element,aF=aJ.options,aG=aB.data(V),aE=aF.offset,aD,aH=aJ._reverse;
if(!aH&&aG===null){aB.data(V,parseFloat(aB.css("margin-"+aF.axis)));
}aD=aB.data(V)||0;
aC["margin-"+aF.axis]=!aH?aD+aE:aD;
}});
x("slideTo",{prepare:function(aG,aC){var aH=this,aB=aH.element,aE=aH.options,aD=aE.offset.split(","),aF=aH._reverse;
if(aq){aC.translatex=!aF?aD[0]:0;
aC.translatey=!aF?aD[1]:0;
}else{aC.left=!aF?aD[0]:0;
aC.top=!aF?aD[1]:0;
}aB.css("left");
}});
x("expand",{directions:["horizontal","vertical"],restore:[W],prepare:function(aK,aC){var aL=this,aB=aL.element,aF=aL.options,aI=aL._reverse,aG=aL._direction==="vertical"?L:aA,aJ=aB[0].style[aG],aE=aB.data(aG),aD=parseFloat(aE||aJ),aH=af(aB.css(aG,p)[aG]());
aK.overflow=M;
aD=aF&&aF.reset?aH||aD:aD||aH;
aC[aG]=(aI?0:aD)+ac;
aK[aG]=(aI?aD:0)+ac;
if(aE===ay){aB.data(aG,aJ);
}},shouldHide:function(){return this._reverse;
},teardown:function(){var aE=this,aB=aE.element,aD=aE._direction==="vertical"?L:aA,aC=aB.data(aD);
if(aC==p||aC===r){setTimeout(function(){aB.css(aD,p).css(aD);
},0);
}}});
var ak={position:"absolute",marginLeft:0,marginTop:0,scale:1};
x("transfer",{init:function(aB,aC){this.element=aB;
this.options={target:aC};
this.restore=[];
},setup:function(){this.element.appendTo(document.body);
},prepare:function(aH,aD){var aI=this,aC=aI.element,aF=J.box(aC),aE=J.box(aI.options.target),aB=o(aC,"scale"),aG=J.fillScale(aE,aF),aJ=J.transformOrigin(aE,aF);
H(aH,ak);
aD.scale=1;
aC.css(al,"scale(1)").css(al);
aC.css(al,"scale("+aB+")");
aH.top=aF.top;
aH.left=aF.left;
aH.transformOrigin=aJ.x+ac+" "+aJ.y+ac;
if(aI._reverse){aH.scale=aG;
}else{aD.scale=aG;
}}});
var v={top:"rect(auto auto $size auto)",bottom:"rect($size auto auto auto)",left:"rect(auto $size auto auto)",right:"rect(auto auto auto $size)"};
var ae={top:{start:"rotatex(0deg)",end:"rotatex(180deg)"},bottom:{start:"rotatex(-180deg)",end:"rotatex(0deg)"},left:{start:"rotatey(0deg)",end:"rotatey(-180deg)"},right:{start:"rotatey(180deg)",end:"rotatey(0deg)"}};
function u(aB,aC){var aE=P.directions[aC].vertical,aD=aB[aE?L:aA]()/2+"px";
return v[aC].replace("$size",aD);
}x("turningPage",{directions:I,init:function(aD,aC,aB){F.prototype.init.call(this,aD,aC);
this._container=aB;
},prepare:function(aF,aC){var aG=this,aD=aG._reverse,aB=aD?D[aG._direction].reverse:aG._direction,aE=ae[aB];
aF.zIndex=1;
if(aG._clipInHalf){aF.clip=u(aG._container,P.directions[aB].reverse);
}aF[q]=M;
aC[al]=am+(aD?aE.start:aE.end);
aF[al]=am+(aD?aE.end:aE.start);
},setup:function(){this._container.append(this.element);
},face:function(aB){this._face=aB;
return this;
},shouldHide:function(){var aD=this,aC=aD._reverse,aB=aD._face;
return aC&&!aB||!aC&&aB;
},clipInHalf:function(aB){this._clipInHalf=aB;
return this;
},temporary:function(){this.element.addClass("temp-page");
return this;
}});
x("staticPage",{directions:I,init:function(aD,aC,aB){F.prototype.init.call(this,aD,aC);
this._container=aB;
},restore:["clip"],prepare:function(aD,aC){var aE=this,aB=aE._reverse?D[aE._direction].reverse:aE._direction;
aD.clip=u(aE._container,aB);
aD.opacity=0.999;
aC.opacity=1;
},shouldHide:function(){var aD=this,aC=aD._reverse,aB=aD._face;
return aC&&!aB||!aC&&aB;
},face:function(aB){this._face=aB;
return this;
}});
x("pageturn",{directions:["horizontal","vertical"],init:function(aD,aC,aE,aB){F.prototype.init.call(this,aD,aC);
this.options={};
this.options.face=aE;
this.options.back=aB;
},children:function(){var aJ=this,aF=aJ.options,aC=aJ._direction==="horizontal"?"left":"top",aH=P.directions[aC].reverse,aG=aJ._reverse,aI,aE=aF.face.clone(true).removeAttr("id"),aB=aF.back.clone(true).removeAttr("id"),aD=aJ.element;
if(aG){aI=aC;
aC=aH;
aH=aI;
}return[P.fx(aF.face).staticPage(aC,aD).face(true).setReverse(aG),P.fx(aF.back).staticPage(aH,aD).setReverse(aG),P.fx(aE).turningPage(aC,aD).face(true).clipInHalf(true).temporary().setReverse(aG),P.fx(aB).turningPage(aH,aD).clipInHalf(true).temporary().setReverse(aG)];
},prepare:function(aC,aB){aC[Z]=C;
aC.transformStyle="preserve-3d";
aC.opacity=0.999;
aB.opacity=1;
},teardown:function(){this.element.find(".temp-page").remove();
}});
x("flip",{directions:["horizontal","vertical"],init:function(aD,aC,aE,aB){F.prototype.init.call(this,aD,aC);
this.options={};
this.options.face=aE;
this.options.back=aB;
},children:function(){var aH=this,aD=aH.options,aB=aH._direction==="horizontal"?"left":"top",aF=P.directions[aB].reverse,aE=aH._reverse,aG,aC=aH.element;
if(aE){aG=aB;
aB=aF;
aF=aG;
}return[P.fx(aD.face).turningPage(aB,aC).face(true).setReverse(aE),P.fx(aD.back).turningPage(aF,aC).setReverse(aE)];
},prepare:function(aB){aB[Z]=C;
aB.transformStyle="preserve-3d";
}});
var ad=!aj.mobileOS.android;
var N=".km-touch-scrollbar, .km-actionsheet-wrapper";
x("replace",{_before:l.noop,_after:l.noop,init:function(aB,aC,aD){F.prototype.init.call(this,aB);
this._previous=l(aC);
this._transitionClass=aD;
},duration:function(){throw new Error("The replace effect does not support duration setting; the effect duration may be customized through the transition class rule");
},beforeTransition:function(aB){this._before=aB;
return this;
},afterTransition:function(aB){this._after=aB;
return this;
},_both:function(){return l().add(this._element).add(this._previous);
},_containerClass:function(){var aC=this._direction,aB="k-fx k-fx-start k-fx-"+this._transitionClass;
if(aC){aB+=" k-fx-"+aC;
}if(this._reverse){aB+=" k-fx-reverse";
}return aB;
},complete:function(aC){if(!this.deferred||aC&&l(aC.target).is(N)){return;
}var aB=this.container;
aB.removeClass("k-fx-end").removeClass(this._containerClass()).off(au.event,this.completeProxy);
this._previous.hide().removeClass("k-fx-current");
this.element.removeClass("k-fx-next");
if(ad){aB.css(W,"");
}if(!this.isAbsolute){this._both().css(aa,"");
}this.deferred.resolve();
delete this.deferred;
},run:function(){if(this._additionalEffects&&this._additionalEffects[0]){return this.compositeRun();
}var aI=this,aE=aI.element,aH=aI._previous,aC=aE.parents().filter(aH.parents()).first(),aB=aI._both(),aD=l.Deferred(),aG=aE.css(aa),aF;
if(!aC.length){aC=aE.parent();
}this.container=aC;
this.deferred=aD;
this.isAbsolute=aG=="absolute";
if(!this.isAbsolute){aB.css(aa,"absolute");
}if(ad){aF=aC.css(W);
aC.css(W,"hidden");
}if(!au){this.complete();
}else{aE.addClass("k-fx-hidden");
aC.addClass(this._containerClass());
this.completeProxy=l.proxy(this,"complete");
aC.on(au.event,this.completeProxy);
P.animationFrame(function(){aE.removeClass("k-fx-hidden").addClass("k-fx-next");
aH.css("display","").addClass("k-fx-current");
aI._before(aH,aE);
P.animationFrame(function(){aC.removeClass("k-fx-start").addClass("k-fx-end");
aI._after(aH,aE);
});
});
}return aD.promise();
},stop:function(){this.complete();
}});
var n=P.Class.extend({init:function(){var aB=this;
aB._tickProxy=ab(aB._tick,aB);
aB._started=false;
},tick:l.noop,done:l.noop,onEnd:l.noop,onCancel:l.noop,start:function(){if(!this.enabled()){return;
}if(!this.done()){this._started=true;
P.animationFrame(this._tickProxy);
}else{this.onEnd();
}},enabled:function(){return true;
},cancel:function(){this._started=false;
this.onCancel();
},_tick:function(){var aB=this;
if(!aB._started){return;
}aB.tick();
if(!aB.done()){P.animationFrame(aB._tickProxy);
}else{aB._started=false;
aB.onEnd();
}}});
var ar=n.extend({init:function(aB){var aC=this;
H(aC,aB);
n.fn.init.call(aC);
},done:function(){return this.timePassed()>=this.duration;
},timePassed:function(){return Math.min(this.duration,new Date()-this.startDate);
},moveTo:function(aC){var aD=this,aB=aD.movable;
aD.initial=aB[aD.axis];
aD.delta=aC.location-aD.initial;
aD.duration=typeof aC.duration=="number"?aC.duration:300;
aD.tick=aD._easeProxy(aC.ease);
aD.startDate=new Date();
aD.start();
},_easeProxy:function(aB){var aC=this;
return function(){aC.movable.moveAxis(aC.axis,aB(aC.timePassed(),aC.initial,aC.delta,aC.duration));
};
}});
H(ar,{easeOutExpo:function(aE,aB,aC,aD){return aE==aD?aB+aC:aC*(-Math.pow(2,-10*aE/aD)+1)+aB;
},easeOutBack:function(aF,aB,aC,aD,aE){aE=1.70158;
return aC*((aF=aF/aD-1)*aF*((aE+1)*aF+aE)+1)+aB;
}});
J.Animation=n;
J.Transition=ar;
J.createEffect=x;
J.box=function(aB){aB=l(aB);
var aC=aB.offset();
aC.width=aB.outerWidth();
aC.height=aB.outerHeight();
return aC;
};
J.transformOrigin=function(aB,aC){var aD=(aB.left-aC.left)*aC.width/(aC.width-aB.width),aE=(aB.top-aC.top)*aC.height/(aC.height-aB.height);
return{x:isNaN(aD)?0:aD,y:isNaN(aE)?0:aE};
};
J.fillScale=function(aB,aC){return Math.min(aB.width/aC.width,aB.height/aC.height);
};
J.fitScale=function(aB,aC){return Math.max(aB.width/aC.width,aB.height/aC.height);
};
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
