(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.gantt",["kendo.data","kendo.popup","kendo.window","kendo.resizable","kendo.gantt.list","kendo.gantt.timeline","kendo.grid","kendo.pdf"],l);
}(function(){var k={id:"gantt",name:"Gantt",category:"web",description:"The Gantt component.",depends:["data","popup","resizable","window","gantt.list","gantt.timeline","grid"]};
(function(l,ap){var R=window.kendo;
var ai="matchMedia" in window;
var p=R.support.browser;
var U=R.support.mobileOS;
var W=R.Observable;
var ar=R.ui.Widget;
var u=R.data.DataSource;
var Y=R.data.ObservableObject;
var X=R.data.ObservableArray;
var ac=R.data.Query;
var O=l.isArray;
var N=l.inArray;
var P=R.isFunction;
var ab=l.proxy;
var E=l.extend;
var Q=l.isPlainObject;
var T=l.map;
var S=R.keys;
var y=3;
var V=".kendoGantt";
var Z="p0";
var aj="tabIndex";
var r="click";
var at="width";
var ah="string";
var A={down:{origin:"bottom left",position:"top left"},up:{origin:"top left",position:"bottom left"}};
var o="aria-activedescendant";
var m="gantt_active_cell";
var n="action-option-focused";
var B=".";
var ak="Are you sure you want to delete this task?";
var z="Are you sure you want to delete this dependency?";
var an=R.template('<button class="#=styles.buttonToggle#"><span class="#=styles.iconToggle#">&nbps;</span></button>');
var q='<button class="#=styles.button# #=className#" #if (action) {#data-action="#=action#"#}#><span class="#=iconClass#"></span><span>#=text#</span></button>';
var s='<a class="#=className#" #=attr# href="\\#">#=text#</a>';
var aq=R.template('<li class="#=styles.currentView# #=styles.viewButtonDefault#"><a href="\\#" class="#=styles.link#">&nbps;</a></li>');
var M=R.template('<ul class="#=styles.viewsWrapper#">#for(var view in views){#<li class="#=styles.viewButtonDefault# #=styles.viewButton#-#= view.toLowerCase() #" data-#=ns#name="#=view#"><a href="\\#" class="#=styles.link#">#=views[view].title#</a></li>#}#</ul>');
var al=R.template('<div class="#=styles.popupWrapper#"><ul class="#=styles.popupList#" role="listbox">#for(var i = 0, l = actions.length; i < l; i++){#<li class="#=styles.item#" data-action="#=actions[i].data#" role="option">#=actions[i].text#</span>#}#</ul></div>');
var w=function(av,aw){var au={name:aw.field};
var ax=aw.model.fields[aw.field].validation;
if(ax&&Q(ax)&&ax.message){au[R.attr("dateCompare-msg")]=ax.message;
}l('<input type="text" required '+R.attr("type")+'="date" '+R.attr("role")+'="datetimepicker" '+R.attr("bind")+'="value:'+aw.field+'" '+R.attr("validate")+"='true' />").attr(au).appendTo(av);
l("<span "+R.attr("for")+'="'+aw.field+'" class="k-invalid-msg"/>').hide().appendTo(av);
};
var ae=function(au,av){l('<a href="#" class="'+av.styles.button+'">'+av.messages.assignButton+"</a>").click(av.click).appendTo(au);
};
var K={wrapper:"k-widget k-gantt",rowHeight:"k-gantt-rowheight",listWrapper:"k-gantt-layout k-gantt-treelist",list:"k-gantt-treelist",timelineWrapper:"k-gantt-layout k-gantt-timeline",timeline:"k-gantt-timeline",splitBarWrapper:"k-splitbar k-state-default k-splitbar-horizontal k-splitbar-draggable-horizontal k-gantt-layout",splitBar:"k-splitbar",splitBarHover:"k-splitbar-horizontal-hover",popupWrapper:"k-list-container",popupList:"k-list k-reset",resizeHandle:"k-resize-handle",icon:"k-icon",item:"k-item",line:"k-line",buttonDelete:"k-gantt-delete",buttonCancel:"k-gantt-cancel",buttonSave:"k-gantt-update",buttonToggle:"k-gantt-toggle",primary:"k-primary",hovered:"k-state-hover",selected:"k-state-selected",focused:"k-state-focused",gridHeader:"k-grid-header",gridHeaderWrap:"k-grid-header-wrap",gridContent:"k-grid-content",popup:{form:"k-popup-edit-form",editForm:"k-gantt-edit-form",formContainer:"k-edit-form-container",resourcesFormContainer:"k-resources-form-container",message:"k-popup-message",buttonsContainer:"k-edit-buttons k-state-default",button:"k-button",editField:"k-edit-field",editLabel:"k-edit-label",resourcesField:"k-gantt-resources"},toolbar:{headerWrapper:"k-floatwrap k-header k-gantt-toolbar",footerWrapper:"k-floatwrap k-header k-gantt-toolbar",toolbar:"k-gantt-toolbar",expanded:"k-state-expanded",views:"k-gantt-views",viewsWrapper:"k-reset k-header k-gantt-views",actions:"k-gantt-actions",button:"k-button k-button-icontext",buttonToggle:"k-button k-button-icon k-gantt-toggle",iconPlus:"k-icon k-i-plus",iconPdf:"k-icon k-i-pdf",iconToggle:"k-icon k-i-gantt-toggle",viewButtonDefault:"k-state-default",viewButton:"k-view",currentView:"k-current-view",link:"k-link",pdfButton:"k-gantt-pdf",appendButton:"k-gantt-create"}};
function ag(au){return"["+R.attr("uid")+(au?"='"+au+"']":"]");
}function ao(au){delete au.name;
delete au.prefix;
delete au.remove;
delete au.edit;
delete au.add;
delete au.navigate;
return au;
}function v(ay){if(ay.filter("[name=end], [name=start]").length){var ax=ay.attr("name");
var aA=R.widgetInstance(ay,R.ui);
var av={};
var au=ay;
var aw;
var az;
while(au!==window&&!aw){au=au.parent();
aw=au.data("kendoEditable");
}az=aw?aw.options.model:null;
if(!az){return true;
}av.start=az.start;
av.end=az.end;
av[ax]=aA?aA.value():R.parseDate(ay.value());
return av.start<=av.end;
}return true;
}function F(ay,au){var az=ay.parents("["+R.attr("role")+'="gantt"]');
var ax=[];
var aw=af(az);
ay.attr(aj,0);
if(au){aw.each(function(aA,aB){ax[aA]=l(aB).scrollTop();
});
}try{ay[0].setActive();
}catch(av){ay[0].focus();
}if(au){aw.each(function(aA,aB){l(aB).scrollTop(ax[aA]);
});
}}function af(au){return l(au).parentsUntil("body").filter(function(ax,aw){var av=R.getComputedStyles(aw,["overflow"]);
return av.overflow!="visible";
}).add(window);
}var x;
var am=W.extend({init:function(au,av){W.fn.init.call(this);
this.element=au;
this.options=E(true,{},this.options,av);
this._popup();
},options:{direction:"down",navigatable:false},_current:function(aw){var av=G.styles;
var au=this.list.find(B+av.focused);
var ax=au[aw]();
if(ax.length){au.removeClass(av.focused).removeAttr("id");
ax.addClass(av.focused).attr("id",n);
this.list.find("ul").removeAttr(o).attr(o,n);
}},_popup:function(){var az=this;
var aw=G.styles;
var ax="li"+B+aw.item;
var av=B+aw.toolbar.appendButton;
var au=this.options.messages.actions;
var ay=this.options.navigatable;
this.list=l(al({styles:aw,actions:[{data:"add",text:au.addChild},{data:"insert-before",text:au.insertBefore},{data:"insert-after",text:au.insertAfter}]}));
this.element.append(this.list);
this.popup=new R.ui.Popup(this.list,E({anchor:this.element.find(av),open:function(){az._adjustListWidth();
},animation:this.options.animation},A[this.options.direction]));
this.element.on(r+V,av,function(aB){var aC=l(this);
var aA=aC.attr(R.attr("action"));
aB.preventDefault();
if(aA){az.trigger("command",{type:aA});
}else{az.popup.open();
if(ay){az.list.find("li:first").addClass(aw.focused).attr("id",n).end().find("ul").attr({TABINDEX:0,"aria-activedescendant":n}).focus();
}}});
this.list.find(ax).hover(function(){l(this).addClass(aw.hovered);
},function(){l(this).removeClass(aw.hovered);
}).end().on(r+V,ax,function(){az.trigger("command",{type:l(this).attr(R.attr("action"))});
az.popup.close();
});
if(ay){this.popup.bind("close",function(){az.list.find(ax).removeClass(aw.focused).end().find("ul").attr(aj,0);
az.element.parents("["+R.attr("role")+'="gantt"]').find(B+aw.gridContent+" > table:first").focus();
});
this.list.find("ul").on("keydown"+V,function(aA){var aB=aA.keyCode;
switch(aB){case S.UP:aA.preventDefault();
az._current("prev");
break;
case S.DOWN:aA.preventDefault();
az._current("next");
break;
case S.ENTER:az.list.find(B+aw.focused).click();
break;
case S.ESC:aA.preventDefault();
az.popup.close();
break;
}});
}},_adjustListWidth:function(){var ax=this.list;
var aw=G.styles;
var az=ax[0].style.width;
var aA=this.element.find(B+aw.toolbar.appendButton);
var ay=ax.outerWidth();
var au;
var av;
if(!ax.data(at)&&az){return;
}au=window.getComputedStyle?window.getComputedStyle(aA[0],null):0;
av=au?parseFloat(au.width):aA.outerWidth();
if(au&&(p.mozilla||p.msie)){av+=parseFloat(au.paddingLeft)+parseFloat(au.paddingRight)+parseFloat(au.borderLeftWidth)+parseFloat(au.borderRightWidth);
}if(ax.css("box-sizing")!=="border-box"){az=av-(ax.outerWidth()-ax.width());
}else{az=av;
}if(ay>az){az=ay;
}ax.css({fontFamily:aA.css("font-family"),width:az}).data(at,az);
},destroy:function(){clearTimeout(this._focusTimeout);
this.popup.destroy();
this.element.off(V);
this.list.off(V);
this.unbind();
}});
var t=function(av,au){return function(ay){ay=O(ay)?{data:ay}:ay;
var ax=ay||{};
var aw=ax.data;
ax.data=aw;
if(!(ax instanceof av)&&ax instanceof u){throw new Error("Incorrect DataSource type. Only "+au+" instances are supported");
}return ax instanceof av?ax:new av(ax);
};
};
var I=R.data.Model.define({id:"id",fields:{id:{type:"number"},predecessorId:{type:"number"},successorId:{type:"number"},type:{type:"number"}}});
var J=u.extend({init:function(au){u.fn.init.call(this,E(true,{},{schema:{modelBase:I,model:I}},au));
},successors:function(au){return this._dependencies("predecessorId",au);
},predecessors:function(au){return this._dependencies("successorId",au);
},dependencies:function(au){var av=this.predecessors(au);
var aw=this.successors(au);
av.push.apply(av,aw);
return av;
},_dependencies:function(av,ax){var au=this.view();
var aw={field:av,operator:"eq",value:ax};
au=new ac(au).filter(aw).toArray();
return au;
}});
J.create=t(J,"GanttDependencyDataSource");
var L=R.data.Model.define({duration:function(){var au=this.end;
var av=this.start;
return au-av;
},isMilestone:function(){return this.duration()===0;
},_offset:function(ax){var au=["start","end"];
var aw;
for(var av=0;
av<au.length;
av++){aw=new Date(this.get(au[av]).getTime()+ax);
this.set(au[av],aw);
}},id:"id",fields:{id:{type:"number"},parentId:{type:"number",defaultValue:null,validation:{required:true}},orderId:{type:"number",validation:{required:true}},title:{type:"string",defaultValue:"New task"},start:{type:"date",validation:{required:true}},end:{type:"date",validation:{required:true,dateCompare:v,message:"End date should be after or equal to the start date"}},percentComplete:{type:"number",validation:{required:true,min:0,max:1,step:0.01}},summary:{type:"boolean"},expanded:{type:"boolean",defaultValue:true}}});
var H=u.extend({init:function(au){u.fn.init.call(this,E(true,{},{schema:{modelBase:L,model:L}},au));
},remove:function(aw){var av=aw.get("parentId");
var au=this.taskAllChildren(aw);
this._removeItems(au);
aw=u.fn.remove.call(this,aw);
this._childRemoved(av,aw.get("orderId"));
return aw;
},add:function(au){if(!au){return;
}au=this._toGanttTask(au);
return this.insert(this.taskSiblings(au).length,au);
},insert:function(au,av){if(!av){return;
}av=this._toGanttTask(av);
av.set("orderId",au);
av=u.fn.insert.call(this,au,av);
this._reorderSiblings(av,this.taskSiblings(av).length-1);
this._resolveSummaryFields(this.taskParent(av));
return av;
},taskChildren:function(ax){var au=this.view();
var av={field:"parentId",operator:"eq",value:null};
var aw=this._sort&&this._sort.length?this._sort:{field:"orderId",dir:"asc"};
var ay;
if(!!ax){ay=ax.get("id");
if(ay===ap||ay===null||ay===""){return[];
}av.value=ay;
}au=new ac(au).filter(av).sort(aw).toArray();
return au;
},taskAllChildren:function(aw){var av=[];
var ax=this;
var au=function(ay){var az=ax.taskChildren(ay);
av.push.apply(av,az);
T(az,au);
};
if(!!aw){au(aw);
}else{av=this.view();
}return av;
},taskSiblings:function(av){if(!av){return null;
}var au=this.taskParent(av);
return this.taskChildren(au);
},taskParent:function(au){if(!au||au.get("parentId")===null){return null;
}return this.get(au.parentId);
},taskLevel:function(aw){var au=0;
var av=this.taskParent(aw);
while(av!==null){au+=1;
av=this.taskParent(av);
}return au;
},taskTree:function(az){var aw=[];
var av;
var aA=this.taskChildren(az);
for(var ax=0,ay=aA.length;
ax<ay;
ax++){av=aA[ax];
aw.push(av);
if(av.get("expanded")){var au=this.taskTree(av);
aw.push.apply(aw,au);
}}return aw;
},update:function(ay,az){var aA=this;
var ax;
var aw=function(aF,aE){var aB=aA.taskAllChildren(aF);
for(var aC=0,aD=aB.length;
aC<aD;
aC++){aB[aC]._offset(aE);
}};
var av=function(aB){var aC=aB.field;
var aD=aB.sender;
switch(aC){case"start":aA._resolveSummaryStart(aA.taskParent(aD));
aw(aD,aD.get(aC).getTime()-ax.getTime());
break;
case"end":aA._resolveSummaryEnd(aA.taskParent(aD));
break;
case"percentComplete":aA._resolveSummaryPercentComplete(aA.taskParent(aD));
break;
case"orderId":aA._reorderSiblings(aD,ax);
break;
}};
if(az.parentId!==ap){ax=ay.get("parentId");
if(ax!==az.parentId){ay.set("parentId",az.parentId);
aA._childRemoved(ax,ay.get("orderId"));
ay.set("orderId",aA.taskSiblings(ay).length-1);
aA._resolveSummaryFields(aA.taskParent(ay));
}delete az.parentId;
}ay.bind("change",av);
for(var au in az){ax=ay.get(au);
ay.set(au,az[au]);
}ay.unbind("change",av);
},_resolveSummaryFields:function(au){if(!au){return;
}this._updateSummary(au);
if(!this.taskChildren(au).length){return;
}this._resolveSummaryStart(au);
this._resolveSummaryEnd(au);
this._resolveSummaryPercentComplete(au);
},_resolveSummaryStart:function(av){var aw=this;
var au=function(aC){var ax=aw.taskChildren(aC);
var aB=ax[0].start.getTime();
var ay;
for(var az=1,aA=ax.length;
az<aA;
az++){ay=ax[az].start.getTime();
if(ay<aB){aB=ay;
}}return new Date(aB);
};
this._updateSummaryRecursive(av,"start",au);
},_resolveSummaryEnd:function(av){var aw=this;
var au=function(aC){var ax=aw.taskChildren(aC);
var aB=ax[0].end.getTime();
var ay;
for(var az=1,aA=ax.length;
az<aA;
az++){ay=ax[az].end.getTime();
if(ay>aB){aB=ay;
}}return new Date(aB);
};
this._updateSummaryRecursive(av,"end",au);
},_resolveSummaryPercentComplete:function(av){var aw=this;
var au=function(ay){var ax=aw.taskChildren(ay);
var az=new ac(ax).aggregate([{field:"percentComplete",aggregate:"average"}]);
return az.percentComplete.average;
};
this._updateSummaryRecursive(av,"percentComplete",au);
},_updateSummaryRecursive:function(ax,av,au){if(!ax){return;
}var ay=au(ax);
ax.set(av,ay);
var aw=this.taskParent(ax);
if(aw){this._updateSummaryRecursive(aw,av,au);
}},_childRemoved:function(az,aw){var ay=az===null?null:this.get(az);
var au=this.taskChildren(ay);
for(var av=aw,ax=au.length;
av<ax;
av++){au[av].set("orderId",av);
}this._resolveSummaryFields(ay);
},_reorderSiblings:function(aC,ay){var az=aC.get("orderId");
var au=az>ay;
var aB=au?ay:az;
var av=au?az:ay;
var ax=au?aB:aB+1;
var aA=this.taskSiblings(aC);
av=Math.min(av,aA.length-1);
for(var aw=aB;
aw<=av;
aw++){if(aA[aw]===aC){continue;
}aA[aw].set("orderId",ax);
ax+=1;
}},_updateSummary:function(av){if(av!==null){var au=this.taskChildren(av).length;
av.set("summary",au>0);
}},_toGanttTask:function(au){if(!(au instanceof L)){var av=au;
au=this._createNewModel();
au.accept(av);
}return au;
}});
H.create=t(H,"GanttDataSource");
E(true,R.data,{GanttDataSource:H,GanttTask:L,GanttDependencyDataSource:J,GanttDependency:I});
var D={desktop:{dateRange:w,resources:ae}};
var C=R.Observable.extend({init:function(au,av){R.Observable.fn.init.call(this);
this.element=au;
this.options=E(true,{},this.options,av);
this.createButton=this.options.createButton;
},fields:function(av,ay){var aB=this;
var az=this.options;
var ax=az.messages.editor;
var aA=az.resources;
var aw;
var au=function(aC){aC.preventDefault();
aA.editor(aB.container.find(B+G.styles.popup.resourcesField),ay);
};
if(az.editable.template){aw=l.map(ay.fields,function(aD,aC){return{field:aC};
});
}else{aw=[{field:"title",title:ax.title},{field:"start",title:ax.start,editor:av.dateRange},{field:"end",title:ax.end,editor:av.dateRange},{field:"percentComplete",title:ax.percentComplete,format:Z}];
if(ay.get(aA.field)){aw.push({field:aA.field,title:ax.resources,messages:ax,editor:av.resources,click:au,styles:G.styles.popup});
}}return aw;
},_buildEditTemplate:function(aA,aw,au){var aD=this.options.resources;
var aF=this.options.editable.template;
var aE=E({},R.Template,this.options.templateSettings);
var aB=aE.paramName;
var aC=G.styles.popup;
var ax="";
if(aF){if(typeof aF===ah){aF=window.unescape(aF);
}ax+=R.template(aF,aE)(aA);
}else{for(var ay=0,az=aw.length;
ay<az;
ay++){var av=aw[ay];
ax+='<div class="'+aC.editLabel+'"><label for="'+av.field+'">'+(av.title||av.field||"")+"</label></div>";
if(av.field===aD.field){ax+='<div class="'+aC.resourcesField+'" style="display:none"></div>';
}if(!aA.editable||aA.editable(av.field)){au.push(av);
ax+="<div "+R.attr("container-for")+'="'+av.field+'" class="'+aC.editField+'"></div>';
}else{var aG="#:";
if(av.field){av=R.expr(av.field,aB);
aG+=av+"==null?'':"+av;
}else{aG+="''";
}aG+="#";
aG=R.template(aG,aE);
ax+='<div class="'+aC.editField+'">'+aG(aA)+"</div>";
}}}return ax;
}});
var aa=C.extend({destroy:function(){this.close();
this.unbind();
},editTask:function(au){this.editable=this._createPopupEditor(au);
},close:function(){var av=this;
var au=function(){if(av.editable){av.editable.destroy();
av.editable=null;
av.container=null;
}if(av.popup){av.popup.destroy();
av.popup=null;
}};
if(this.editable&&this.container.is(":visible")){this.container.data("kendoWindow").bind("deactivate",au).close();
}else{au();
}},showDialog:function(ay){var au=ay.buttons;
var aA=G.styles.popup;
var av=R.format('<div class="{0}"><div class="{1}"><p class="{2}">{3}</p><div class="{4}">',aA.form,aA.formContainer,aA.message,ay.text,aA.buttonsContainer);
for(var aw=0,ax=au.length;
aw<ax;
aw++){av+=this.createButton(au[aw]);
}av+="</div></div></div>";
var aB=this.element;
if(this.popup){this.popup.destroy();
}var az=this.popup=l(av).appendTo(aB).eq(0).on("click",B+aA.button,function(aD){aD.preventDefault();
az.close();
var aC=l(aD.currentTarget).index();
au[aC].click();
}).kendoWindow({modal:true,resizable:false,draggable:false,title:ay.title,visible:false,close:function(){this.destroy();
aB.focus();
}}).getKendoWindow();
az.center().open();
},_createPopupEditor:function(aD){var aE=this;
var aB={};
var aA=this.options.messages;
var ay=G.styles;
var aC=ay.popup;
var az=R.format('<div {0}="{1}" class="{2} {3}"><div class="{4}">',R.attr("uid"),aD.uid,aC.form,aC.editForm,aC.formContainer);
var ax=this.fields(D.desktop,aD);
var av=[];
az+=this._buildEditTemplate(aD,ax,av);
az+='<div class="'+aC.buttonsContainer+'">';
az+=this.createButton({name:"update",text:aA.save,className:G.styles.primary});
az+=this.createButton({name:"cancel",text:aA.cancel});
az+=this.createButton({name:"delete",text:aA.destroy});
az+="</div></div></div>";
var au=this.container=l(az).appendTo(this.element).eq(0).kendoWindow(E({modal:true,resizable:false,draggable:true,title:aA.editor.editorTitle,visible:false,close:function(aF){if(aF.userTriggered){if(aE.trigger("cancel",{container:au,model:aD})){aF.preventDefault();
}}}},aB));
var aw=au.kendoEditable({fields:av,model:aD,clearContainer:false,validateOnBlur:true,target:aE.options.target}).data("kendoEditable");
R.cycleForm(au);
if(!this.trigger("edit",{container:au,model:aD})){au.data("kendoWindow").center().open();
au.on(r+V,B+ay.buttonCancel,function(aF){aF.preventDefault();
aF.stopPropagation();
aE.trigger("cancel",{container:au,model:aD});
});
au.on(r+V,B+ay.buttonSave,function(aF){aF.preventDefault();
aF.stopPropagation();
var aH=aE.fields(D.desktop,aD);
var aK={};
var aG;
for(var aI=0,aJ=aH.length;
aI<aJ;
aI++){aG=aH[aI].field;
aK[aG]=aD.get(aG);
}aE.trigger("save",{container:au,model:aD,updateInfo:aK});
});
au.on(r+V,B+ay.buttonDelete,function(aF){aF.preventDefault();
aF.stopPropagation();
aE.trigger("remove",{container:au,model:aD});
});
}else{aE.trigger("cancel",{container:au,model:aD});
}return aw;
}});
var ad=ar.extend({init:function(au,av){ar.fn.init.call(this,au,av);
this.wrapper=this.element;
this.model=this.options.model;
this.resourcesField=this.options.resourcesField;
this.createButton=this.options.createButton;
this._initContainer();
this._attachHandlers();
},events:["save"],open:function(){this.window.center().open();
this.grid.resize(true);
},close:function(){this.window.bind("deactivate",ab(this.destroy,this)).close();
},destroy:function(){this._dettachHandlers();
this.grid.destroy();
this.grid=null;
this.window.destroy();
this.window=null;
ar.fn.destroy.call(this);
R.destroy(this.wrapper);
this.element=this.wrapper=null;
},_attachHandlers:function(){var av=G.styles;
var aw=this.grid;
var au=this._cancelProxy=ab(this._cancel,this);
this.container.on(r+V,B+av.buttonCancel,this._cancelProxy);
this._saveProxy=ab(this._save,this);
this.container.on(r+V,B+av.buttonSave,this._saveProxy);
this.window.bind("close",function(ax){if(ax.userTriggered){au(ax);
}});
aw.wrapper.on(r+V,"input[type='checkbox']",function(){var ax=l(this);
var az=l(ax).closest("tr");
var ay=aw.dataSource.getByUid(az.attr(R.attr("uid")));
var aA=l(ax).is(":checked")?1:"";
ay.set("value",aA);
});
},_dettachHandlers:function(){this._cancelProxy=null;
this._saveProxy=null;
this.container.off(V);
this.grid.wrapper.off();
},_cancel:function(au){au.preventDefault();
this.close();
},_save:function(au){au.preventDefault();
this._updateModel();
if(!this.wrapper.is(B+G.styles.popup.resourcesField)){this.trigger("save",{container:this.wrapper,model:this.model});
}this.close();
},_initContainer:function(){var av=G.styles.popup;
var au=R.format('<div class="{0} {1}"><div class="{2} {3}"/></div>"',av.form,av.editForm,av.formContainer,av.resourcesFormContainer);
au=l(au);
this.container=au.find(B+av.resourcesFormContainer);
this.window=au.kendoWindow({modal:true,resizable:false,draggable:true,visible:false,title:this.options.messages.resourcesEditorTitle}).data("kendoWindow");
this._resourceGrid();
this._createButtons();
},_resourceGrid:function(){var aw=this;
var av=this.options.messages;
var au=l('<div id="resources-grid"/>').appendTo(this.container);
this.grid=new R.ui.Grid(au,{columns:[{field:"name",title:av.resourcesHeader,template:"<label><input type='checkbox' value='#=name#'# if (value > 0 && value !== null) {#checked='checked'# } #/>#=name#</labe>"},{field:"value",title:av.unitsHeader,template:function(ax){var az=ax.format;
var ay=ax.value!==null?ax.value:"";
return az?R.toString(ay,az):ay;
}}],height:280,sortable:true,editable:true,filterable:true,dataSource:{data:aw.options.data,schema:{model:{id:"id",fields:{id:{from:"id"},name:{from:"name",type:"string",editable:false},value:{from:"value",type:"number",defaultValue:""},format:{from:"format",type:"string"}}}}},save:function(ax){var ay=!!ax.values.value;
ax.container.parent().find("input[type='checkbox']").prop("checked",ay);
}});
},_createButtons:function(){var au=this.options.buttons;
var av='<div class="'+G.styles.popup.buttonsContainer+'">';
for(var aw=0,ax=au.length;
aw<ax;
aw++){av+=this.createButton(au[aw]);
}av+="</div>";
this.container.append(av);
},_updateModel:function(){var ax=[];
var ay;
var au=this.grid.dataSource.data();
for(var av=0,aw=au.length;
av<aw;
av++){ay=au[av].get("value");
if(ay!==null&&ay>0){ax.push(au[av]);
}}this.model[this.resourcesField]=ax;
}});
var G=ar.extend({init:function(au,aw,av){if(O(aw)){aw={dataSource:aw};
}x={append:{text:"Add Task",action:"add",className:G.styles.toolbar.appendButton,iconClass:G.styles.toolbar.iconPlus},pdf:{text:"Export to PDF",className:G.styles.toolbar.pdfButton,iconClass:G.styles.toolbar.iconPdf}};
ar.fn.init.call(this,au,aw);
if(av){this._events=av;
}this._wrapper();
this._resources();
if(!this.options.views||!this.options.views.length){this.options.views=["day","week","month"];
}this._timeline();
this._toolbar();
this._footer();
this._adjustDimensions();
this._preventRefresh=true;
this.view(this.timeline._selectedViewName);
this._preventRefresh=false;
this._dataSource();
this._assignments();
this._dropDowns();
this._list();
this._dependencies();
this._resizable();
this._scrollable();
this._dataBind();
this._attachEvents();
this._createEditor();
R.notify(this);
},events:["dataBinding","dataBound","add","edit","remove","cancel","save","change","navigate","moveStart","move","moveEnd","resizeStart","resize","resizeEnd","columnResize"],options:{name:"Gantt",autoBind:true,navigatable:false,selectable:true,editable:true,resizable:false,columnResizeHandleWidth:y,columns:[],views:[],dataSource:{},dependencies:{},resources:{},assignments:{},taskTemplate:null,messages:{save:"Save",cancel:"Cancel",destroy:"Delete",deleteTaskConfirmation:ak,deleteDependencyConfirmation:z,deleteTaskWindowTitle:"Delete task",deleteDependencyWindowTitle:"Delete dependency",views:{day:"Day",week:"Week",month:"Month",year:"Year",start:"Start",end:"End"},actions:{append:"Add Task",addChild:"Add Child",insertBefore:"Add Above",insertAfter:"Add Below",pdf:"Export to PDF"},editor:{editorTitle:"Task",resourcesEditorTitle:"Resources",title:"Title",start:"Start",end:"End",percentComplete:"Complete",resources:"Resources",assignButton:"Assign",resourcesHeader:"Resources",unitsHeader:"Units"}},showWorkHours:true,showWorkDays:true,toolbar:null,workDayStart:new Date(1980,1,1,8,0,0),workDayEnd:new Date(1980,1,1,17,0,0),workWeekStart:1,workWeekEnd:5,hourSpan:1,snap:true,height:600,listWidth:"30%",rowHeight:null},select:function(av){var au=this.list;
if(!av){return au.select();
}au.select(av);
return;
},clearSelection:function(){this.list.clearSelection();
},destroy:function(){ar.fn.destroy.call(this);
if(this.dataSource){this.dataSource.unbind("change",this._refreshHandler);
this.dataSource.unbind("progress",this._progressHandler);
this.dataSource.unbind("error",this._errorHandler);
}if(this.dependencies){this.dependencies.unbind("change",this._dependencyRefreshHandler);
this.dependencies.unbind("error",this._dependencyErrorHandler);
}if(this.timeline){this.timeline.unbind();
this.timeline.destroy();
}if(this.list){this.list.unbind();
this.list.destroy();
}if(this.footerDropDown){this.footerDropDown.destroy();
}if(this.headerDropDown){this.headerDropDown.destroy();
}if(this._editor){this._editor.destroy();
}if(this._resizeDraggable){this._resizeDraggable.destroy();
}this.toolbar.off(V);
if(ai){this._mediaQuery.removeListener(this._mediaQueryHandler);
this._mediaQuery=null;
}l(window).off("resize"+V,this._resizeHandler);
l(this.wrapper).off(V);
this.toolbar=null;
this.footer=null;
},setOptions:function(aw){var av=R.deepExtend({},this.options,aw);
var au=this._events;
if(!aw.views){var ax=this.view().name;
av.views=l.map(this.options.views,function(aA){var ay=Q(aA);
var az=ay?typeof aA.type!=="string"?aA.title:aA.type:aA;
if(ax===az){if(ay){aA.selected=true;
}else{aA={type:az,selected:true};
}}else{if(ay){aA.selected=false;
}}return aA;
});
}if(!aw.dataSource){av.dataSource=this.dataSource;
}if(!aw.dependencies){av.dependencies=this.dependencies;
}if(!aw.resources){av.resources=this.resources;
}if(!aw.assignments){av.assignments=this.assignments;
}this.destroy();
this.element.empty();
this.options=null;
this.init(this.element,av,au);
ar.fn._setEvents.call(this,av);
},_attachEvents:function(){this._resizeHandler=ab(this.resize,this,false);
l(window).on("resize"+V,this._resizeHandler);
},_wrapper:function(){var au=G.styles;
var ax=[au.icon,au.resizeHandle].join(" ");
var aw=this.options;
var av=aw.height;
var ay=aw.width;
this.wrapper=this.element.addClass(au.wrapper).append("<div class='"+au.listWrapper+"'><div></div></div>").append("<div class='"+au.splitBarWrapper+"'><div class='"+ax+"'></div></div>").append("<div class='"+au.timelineWrapper+"'><div></div></div>");
this.wrapper.find(B+au.list).width(aw.listWidth);
if(av){this.wrapper.height(av);
}if(ay){this.wrapper.width(ay);
}if(aw.rowHeight){this.wrapper.addClass(au.rowHeight);
}},_toolbar:function(){var aB=this;
var ax=G.styles;
var aI=B+ax.toolbar.views+" > li";
var aA=B+ax.toolbar.pdfButton;
var aE=B+ax.buttonToggle;
var aw=B+ax.gridContent;
var aG=l(B+ax.list);
var aC=l(B+ax.timeline);
var az=ax.hovered;
var au=this.options.toolbar;
var av=l("<div class='"+ax.toolbar.actions+"'>");
var aF;
var aH;
var aD;
var ay=function(aJ){if(aJ.matches){aG.css({display:"none","max-width":0});
}else{aG.css({display:"inline-block",width:"30%","max-width":"none"});
aC.css("display","inline-block");
aB.refresh();
aC.find(aw).scrollTop(aB.scrollTop);
}aB._resize();
};
if(!P(au)){au=typeof au===ah?au:this._actions(au);
au=ab(R.template(au),this);
}aD=l(an({styles:ax.toolbar}));
aH=l(M({ns:R.ns,views:this.timeline.views,styles:ax.toolbar}));
av.append(au({}));
aF=l("<div class='"+ax.toolbar.headerWrapper+"'>").append(aD).append(aH).append(av);
if(aH.find("li").length>1){aH.prepend(aq({styles:ax.toolbar}));
}this.wrapper.prepend(aF);
this.toolbar=aF;
if(ai){this._mediaQueryHandler=ab(ay,this);
this._mediaQuery=window.matchMedia("(max-width: 480px)");
this._mediaQuery.addListener(this._mediaQueryHandler);
}aF.on(r+V,aI,function(aK){aK.preventDefault();
var aL=aB.list;
var aM=l(this).attr(R.attr("name"));
var aJ=aH.find(B+ax.toolbar.currentView);
if(aJ.is(":visible")){aJ.parent().toggleClass(ax.toolbar.expanded);
}if(aL.editable&&aL.editable.trigger("validate")){return;
}if(!aB.trigger("navigate",{view:aM})){aB.view(aM);
}}).on(r+V,aA,function(aJ){aJ.preventDefault();
aB.saveAsPDF();
}).on(r+V,aE,function(aJ){aJ.preventDefault();
if(aG.is(":visible")){aG.css({display:"none",width:"0"});
aC.css({display:"inline-block",width:"100%"});
aB.refresh();
aC.find(aw).scrollTop(aB.scrollTop);
}else{aC.css({display:"none",width:0});
aG.css({display:"inline-block",width:"100%","max-width":"none"}).find(aw).scrollTop(aB.scrollTop);
}aB._resize();
});
this.wrapper.find(B+ax.toolbar.toolbar+" li").hover(function(){l(this).addClass(az);
},function(){l(this).removeClass(az);
});
},_actions:function(){var ay=this.options;
var au=ay.toolbar;
var av="";
if(!O(au)){if(ay.editable){au=["append"];
}else{return av;
}}for(var aw=0,ax=au.length;
aw<ax;
aw++){av+=this._createButton(au[aw]);
}return av;
},_footer:function(){if(!this.options.editable){return;
}var ax=G.styles.toolbar;
var ay=this.options.messages.actions;
var av=l(R.template(q)(E(true,{styles:ax},x.append,{text:ay.append})));
var au=l("<div class='"+ax.actions+"'>").append(av);
var aw=l("<div class='"+ax.footerWrapper+"'>").append(au);
this.wrapper.append(aw);
this.footer=aw;
},_createButton:function(av){var az=av.template||q;
var ax=this.options.messages.actions;
var aw=typeof av===ah?av:av.name||av.text;
var au=x[aw]?x[aw].className:"k-gantt-"+(aw||"").replace(/\s/g,"");
var ay={iconClass:"",action:"",text:aw,className:au,styles:G.styles.toolbar};
if(!aw&&!(Q(av)&&av.template)){throw new Error("Custom commands should have name specified");
}ay=E(true,ay,x[aw],{text:ax[aw]});
if(Q(av)){if(av.className&&N(ay.className,av.className.split(" "))<0){av.className+=" "+ay.className;
}ay=E(true,ay,av);
}return R.template(az)(ay);
},_adjustDimensions:function(){var au=this.element;
var aw=G.styles;
var ax=B+aw.list;
var aA=B+aw.timeline;
var ay=B+aw.splitBar;
var aB=this.toolbar.outerHeight();
var av=this.footer?this.footer.outerHeight():0;
var aC=au.height();
var aD=au.width();
var az=au.find(ay).outerWidth();
var aE=au.find(ax).outerWidth();
au.children([ax,aA,ay].join(",")).height(aC-(aB+av)).end().children(aA).width(aD-(az+aE));
if(aD<aE+az){au.find(ax).width(aD-az);
}},_scrollTo:function(aA){var aB=this.timeline.view();
var ax=this.list;
var av=R.attr("uid");
var aw=typeof aA==="string"?aA:aA.closest("tr"+ag()).attr(av);
var au;
var az;
var ay=function(){if(az.length!==0){au();
}};
if(aB.content.is(":visible")){az=aB.content.find(ag(aw));
au=function(){aB._scrollTo(az);
};
}else{az=ax.content.find(ag(aw));
au=function(){az.get(0).scrollIntoView();
};
}ay();
},_dropDowns:function(){var ax=this;
var av=B+G.styles.toolbar.actions;
var au=this.options.messages.actions;
var ay=this.timeline;
var aw=function(aA){var aI=aA.type;
var aD;
var az=ax.dataSource;
var aH=az._createNewModel();
var aF=ax.dataItem(ax.select());
var aE=az.taskParent(aF);
var aC=ay.view()._timeSlots()[0];
var aG=aI==="add"?aF:aE;
var aB=ax.list.editable;
if(aB&&aB.trigger("validate")){return;
}aH.set("title","New task");
if(aG){aH.set("parentId",aG.get("id"));
aH.set("start",aG.get("start"));
aH.set("end",aG.get("end"));
}else{aH.set("start",aC.start);
aH.set("end",aC.end);
}if(aI!=="add"){aD=aF.get("orderId");
aD=aI==="insert-before"?aD:aD+1;
}ax._createTask(aH,aD);
};
if(!this.options.editable){return;
}this.footerDropDown=new am(this.footer.children(av).eq(0),{messages:{actions:au},direction:"up",animation:{open:{effects:"slideIn:up"}},navigatable:ax.options.navigatable});
this.headerDropDown=new am(this.toolbar.children(av).eq(0),{messages:{actions:au},navigatable:ax.options.navigatable});
this.footerDropDown.bind("command",aw);
this.headerDropDown.bind("command",aw);
},_list:function(){var aD=this;
var aA=aD.options.navigatable;
var ax=G.styles;
var az=this.wrapper.find(B+ax.list);
var aw=az.find("> div");
var aE=this.wrapper.find(B+ax.toolbar.actions+" > button");
var aB={columns:this.options.columns||[],dataSource:this.dataSource,selectable:this.options.selectable,editable:this.options.editable,resizable:this.options.resizable,columnResizeHandleWidth:this.options.columnResizeHandleWidth,listWidth:az.outerWidth(),resourcesField:this.resources.field,rowHeight:this.options.rowHeight};
var av=aB.columns;
var au;
var aC=function(){if(aA){aD._current(aD._cachedCurrent);
F(aD.list.content.find("table"),true);
}delete aD._cachedCurrent;
};
for(var ay=0;
ay<av.length;
ay++){au=av[ay];
if(au.field===this.resources.field&&typeof au.editor!=="function"){au.editor=ab(this._createResourceEditor,this);
}}this.list=new R.ui.GanttList(aw,aB);
this.list.bind("render",function(){aD._navigatable();
},true).bind("edit",function(aF){aD._cachedCurrent=aF.cell;
if(aD.trigger("edit",{task:aF.model,container:aF.cell})){aF.preventDefault();
}}).bind("cancel",function(aF){if(aD.trigger("cancel",{task:aF.model,container:aF.cell})){aF.preventDefault();
}aC();
}).bind("update",function(aF){aD._updateTask(aF.task,aF.updateInfo);
aC();
}).bind("change",function(){aD.trigger("change");
var aF=aD.list.select();
if(aF.length){aE.removeAttr("data-action","add");
aD.timeline.select("[data-uid='"+aF.attr("data-uid")+"']");
}else{aE.attr("data-action","add");
aD.timeline.clearSelection();
}}).bind("columnResize",function(aF){aD.trigger("columnResize",{column:aF.column,oldWidth:aF.oldWidth,newWidth:aF.newWidth});
});
},_timeline:function(){var ay=this;
var aw=G.styles;
var ax=ao(E(true,{resourcesField:this.resources.field},this.options));
var av=this.wrapper.find(B+aw.timeline+" > div");
var au=B+aw.toolbar.currentView+" > "+B+aw.toolbar.link;
this.timeline=new R.ui.GanttTimeline(av,ax);
this.timeline.bind("navigate",function(az){var aB=az.view.replace(/\./g,"\\.").toLowerCase();
var aA=ay.toolbar.find(B+aw.toolbar.views+" > li").removeClass(aw.selected).end().find(B+aw.toolbar.viewButton+"-"+aB).addClass(aw.selected).find(B+aw.toolbar.link).text();
ay.toolbar.find(au).text(aA);
ay.refresh();
}).bind("moveStart",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){az.preventDefault();
return;
}if(ay.trigger("moveStart",{task:az.task})){az.preventDefault();
}}).bind("move",function(az){var aC=az.task;
var aB=az.start;
var aA=new Date(aB.getTime()+aC.duration());
if(ay.trigger("move",{task:aC,start:aB,end:aA})){az.preventDefault();
}}).bind("moveEnd",function(az){var aC=az.task;
var aB=az.start;
var aA=new Date(aB.getTime()+aC.duration());
if(!ay.trigger("moveEnd",{task:aC,start:aB,end:aA})){ay._updateTask(ay.dataSource.getByUid(aC.uid),{start:aB,end:aA});
}}).bind("resizeStart",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){az.preventDefault();
return;
}if(ay.trigger("resizeStart",{task:az.task})){az.preventDefault();
}}).bind("resize",function(az){if(ay.trigger("resize",{task:az.task,start:az.start,end:az.end})){az.preventDefault();
}}).bind("resizeEnd",function(az){var aA=az.task;
var aB={};
if(az.resizeStart){aB.start=az.start;
}else{aB.end=az.end;
}if(!ay.trigger("resizeEnd",{task:aA,start:az.start,end:az.end})){ay._updateTask(ay.dataSource.getByUid(aA.uid),aB);
}}).bind("percentResizeStart",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){az.preventDefault();
}}).bind("percentResizeEnd",function(az){ay._updateTask(ay.dataSource.getByUid(az.task.uid),{percentComplete:az.percentComplete});
}).bind("dependencyDragStart",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){az.preventDefault();
}}).bind("dependencyDragEnd",function(aA){var az=ay.dependencies._createNewModel({type:aA.type,predecessorId:aA.predecessor.id,successorId:aA.successor.id});
ay._createDependency(az);
}).bind("select",function(az){var aA=ay.list.editable;
if(aA){aA.trigger("validate");
}ay.select("[data-uid='"+az.uid+"']");
}).bind("editTask",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){return;
}ay.editTask(az.uid);
}).bind("clear",function(){ay.clearSelection();
}).bind("removeTask",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){return;
}ay.removeTask(ay.dataSource.getByUid(az.uid));
}).bind("removeDependency",function(az){var aA=ay.list.editable;
if(aA&&aA.trigger("validate")){return;
}ay.removeDependency(ay.dependencies.getByUid(az.uid));
});
},_dataSource:function(){var av=this.options;
var au=av.dataSource;
au=O(au)?{data:au}:au;
if(this.dataSource&&this._refreshHandler){this.dataSource.unbind("change",this._refreshHandler).unbind("progress",this._progressHandler).unbind("error",this._errorHandler);
}else{this._refreshHandler=ab(this.refresh,this);
this._progressHandler=ab(this._requestStart,this);
this._errorHandler=ab(this._error,this);
}this.dataSource=R.data.GanttDataSource.create(au).bind("change",this._refreshHandler).bind("progress",this._progressHandler).bind("error",this._errorHandler);
},_dependencies:function(){var av=this.options.dependencies||{};
var au=O(av)?{data:av}:av;
if(this.dependencies&&this._dependencyRefreshHandler){this.dependencies.unbind("change",this._dependencyRefreshHandler).unbind("error",this._dependencyErrorHandler);
}else{this._dependencyRefreshHandler=ab(this.refreshDependencies,this);
this._dependencyErrorHandler=ab(this._error,this);
}this.dependencies=R.data.GanttDependencyDataSource.create(au).bind("change",this._dependencyRefreshHandler).bind("error",this._dependencyErrorHandler);
},_resources:function(){var av=this.options.resources;
var au=av.dataSource||{};
this.resources={field:"resources",dataTextField:"name",dataColorField:"color",dataFormatField:"format"};
E(this.resources,av);
this.resources.dataSource=R.data.DataSource.create(au);
},_assignments:function(){var au=this.options.assignments;
var av=au.dataSource||{};
if(this.assignments){this.assignments.dataSource.unbind("change",this._assignmentsRefreshHandler);
}else{this._assignmentsRefreshHandler=ab(this.refresh,this);
}this.assignments={dataTaskIdField:"taskId",dataResourceIdField:"resourceId",dataValueField:"value"};
E(this.assignments,au);
this.assignments.dataSource=R.data.DataSource.create(av);
this.assignments.dataSource.bind("change",this._assignmentsRefreshHandler);
},_createEditor:function(){var av=this;
var au=this._editor=new aa(this.wrapper,E({},this.options,{target:this,resources:{field:this.resources.field,editor:ab(this._createResourceEditor,this)},createButton:ab(this._createPopupButton,this)}));
au.bind("cancel",function(aw){var ax=av.dataSource.getByUid(aw.model.uid);
if(av.trigger("cancel",{container:aw.container,task:ax})){aw.preventDefault();
return;
}av.cancelTask();
}).bind("edit",function(aw){var ax=av.dataSource.getByUid(aw.model.uid);
if(av.trigger("edit",{container:aw.container,task:ax})){aw.preventDefault();
}}).bind("save",function(aw){var ax=av.dataSource.getByUid(aw.model.uid);
av.saveTask(ax,aw.updateInfo);
}).bind("remove",function(aw){av.removeTask(aw.model.uid);
});
},_createResourceEditor:function(au,az){var aB=this;
var ay=az instanceof Y?az:az.model;
var aw=ay.get("id");
var ax=this.options.messages;
var aA=aB.resources.field;
var av=this._resourceEditor=new ad(au,{resourcesField:aA,data:this._wrapResourceData(aw),model:ay,messages:E({},ax.editor),buttons:[{name:"update",text:ax.save,className:G.styles.primary},{name:"cancel",text:ax.cancel}],createButton:ab(this._createPopupButton,this),save:function(aC){aB._updateAssignments(aC.model.get("id"),aC.model.get(aA));
}});
av.open();
},_createPopupButton:function(au){var av=au.name||au.text;
var aw={className:G.styles.popup.button+" k-gantt-"+(av||"").replace(/\s/g,""),text:av,attr:""};
if(!av&&!(Q(au)&&au.template)){throw new Error("Custom commands should have name specified");
}if(Q(au)){if(au.className){au.className+=" "+aw.className;
}aw=E(true,aw,au);
}return R.template(s)(aw);
},view:function(au){return this.timeline.view(au);
},dataItem:function(aw){if(!aw){return null;
}var av=this.list;
var au=av.content.find(aw);
return av._modelFromElement(au);
},setDataSource:function(au){this.options.dataSource=au;
this._dataSource();
this.list._setDataSource(this.dataSource);
if(this.options.autoBind){au.fetch();
}},setDependenciesDataSource:function(au){this.options.dependencies=au;
this._dependencies();
if(this.options.autoBind){au.fetch();
}},items:function(){return this.wrapper.children(".k-task");
},_updateAssignments:function(az,aF){var aw=this.assignments.dataSource;
var aG=this.assignments.dataTaskIdField;
var aE=this.assignments.dataResourceIdField;
var ax=false;
var av=new ac(aw.view()).filter({field:aG,operator:"eq",value:az}).toArray();
var au;
var aD;
var aH;
while(av.length){au=av[0];
for(var ay=0,aB=aF.length;
ay<aB;
ay++){aD=aF[ay];
if(au.get(aE)===aD.get("id")){aH=aF[ay].get("value");
this._updateAssignment(au,aH);
aF.splice(ay,1);
ax=true;
break;
}}if(!ax){this._removeAssignment(au);
}ax=false;
av.shift();
}for(var aA=0,aC=aF.length;
aA<aC;
aA++){aD=aF[aA];
this._createAssignment(aD,az);
}aw.sync();
},cancelTask:function(){var av=this._editor;
var au=av.container;
if(au){av.close();
}},editTask:function(aw){var au=typeof aw==="string"?this.dataSource.getByUid(aw):aw;
if(!au){return;
}var av=this.dataSource._createNewModel(au.toJSON());
av.uid=au.uid;
this.cancelTask();
this._editTask(av);
},_editTask:function(au){this._editor.editTask(au);
},saveTask:function(ax,ay){var aw=this._editor;
var au=aw.container;
var av=aw.editable;
if(au&&av&&av.end()){this._updateTask(ax,ay);
}},_updateTask:function(av,aw){var au=this.resources.field;
if(!this.trigger("save",{task:av,values:aw})){this._preventRefresh=true;
this.dataSource.update(av,aw);
if(aw[au]){this._updateAssignments(av.get("id"),aw[au]);
}this._syncDataSource();
}},_updateAssignment:function(au,aw){var av=this.assignments.dataValueField;
au.set(av,aw);
},removeTask:function(aw){var av=this;
var au=typeof aw==="string"?this.dataSource.getByUid(aw):aw;
if(!au){return;
}this._taskConfirm(function(ax){if(!ax){av._removeTask(au);
}},au);
},_createTask:function(aw,av){if(!this.trigger("add",{task:aw,dependency:null})){var au=this.dataSource;
this._preventRefresh=true;
if(av===ap){au.add(aw);
}else{au.insert(av,aw);
}this._scrollToUid=aw.uid;
this._syncDataSource();
}},_createDependency:function(au){if(!this.trigger("add",{task:null,dependency:au})){this._preventDependencyRefresh=true;
this.dependencies.add(au);
this._preventDependencyRefresh=false;
this.dependencies.sync();
}},_createAssignment:function(ay,ax){var av=this.assignments;
var aw=av.dataSource;
var aB=av.dataTaskIdField;
var az=av.dataResourceIdField;
var aA=av.dataValueField;
var au=aw._createNewModel();
au[aB]=ax;
au[az]=ay.get("id");
au[aA]=ay.get("value");
aw.add(au);
},removeDependency:function(aw){var av=this;
var au=typeof aw==="string"?this.dependencies.getByUid(aw):aw;
if(!au){return;
}this._dependencyConfirm(function(ax){if(!ax){av._removeDependency(au);
}},au);
},_removeTaskDependencies:function(ax,au){this._preventDependencyRefresh=true;
for(var av=0,aw=au.length;
av<aw;
av++){this.dependencies.remove(au[av]);
}this._preventDependencyRefresh=false;
this.dependencies.sync();
},_removeTaskAssignments:function(az){var av=this.assignments.dataSource;
var au=av.view();
var aw={field:this.assignments.dataTaskIdField,operator:"eq",value:az.get("id")};
au=new ac(au).filter(aw).toArray();
this._preventRefresh=true;
for(var ax=0,ay=au.length;
ax<ay;
ax++){av.remove(au[ax]);
}this._preventRefresh=false;
av.sync();
},_removeTask:function(av){var au=this.dependencies.dependencies(av.id);
if(!this.trigger("remove",{task:av,dependencies:au})){this._removeTaskDependencies(av,au);
this._removeTaskAssignments(av);
this._preventRefresh=true;
if(this.dataSource.remove(av)){this._syncDataSource();
}this._preventRefresh=false;
}},_removeDependency:function(au){if(!this.trigger("remove",{task:null,dependencies:[au]})){if(this.dependencies.remove(au)){this.dependencies.sync();
}}},_removeAssignment:function(au){this.assignments.dataSource.remove(au);
},_taskConfirm:function(au,aw){var av=this.options.messages;
this._confirm(au,{model:aw,text:av.deleteTaskConfirmation,title:av.deleteTaskWindowTitle});
},_dependencyConfirm:function(au,av){var aw=this.options.messages;
this._confirm(au,{model:av,text:aw.deleteDependencyConfirmation,title:aw.deleteDependencyWindowTitle});
},_confirm:function(av,ay){var aw=this.options.editable;
var ax;
var au;
if(aw===true||aw.confirmation!==false){ax=this.options.messages;
au=[{name:"delete",text:ax.destroy,className:G.styles.primary,click:function(){av();
}},{name:"cancel",text:ax.cancel,click:function(){av(true);
}}];
this.showDialog(E(true,{},ay,{buttons:au}));
}else{av();
}},showDialog:function(au){this._editor.showDialog(au);
},refresh:function(){if(this._preventRefresh||this.list.editable){return;
}this._progress(false);
var ax=this.dataSource;
var az=ax.taskTree();
var ay=this._scrollToUid;
var aw;
var av;
var au=-1;
if(this.current){av=this.current.closest("tr").attr(R.attr("uid"));
au=this.current.index();
}if(this.trigger("dataBinding")){return;
}if(this.resources.dataSource.data().length!==0){this._assignResources(az);
}if(this._editor){this._editor.close();
}this.clearSelection();
this.list._render(az);
this.timeline._render(az);
this.timeline._renderDependencies(this.dependencies.view());
if(ay){this._scrollTo(ay);
this.select(ag(ay));
}if((ay||av)&&au>=0){aw=this.list.content.find("tr"+ag(ay||av)+" > td:eq("+au+")");
this._current(aw);
}this._scrollToUid=null;
this.trigger("dataBound");
},refreshDependencies:function(){if(this._preventDependencyRefresh){return;
}if(this.trigger("dataBinding")){return;
}this.timeline._renderDependencies(this.dependencies.view());
this.trigger("dataBound");
},_assignResources:function(aB){var aA=this.resources;
var aw=this.assignments;
var ax=function(){var aD=aw.dataSource.view();
var aE={field:aw.dataTaskIdField};
aD=new ac(aD).group(aE).toArray();
return aD;
};
var av=ax();
var au=function(aG,aD){var aH=aG.get("id");
R.setter(aA.field)(aG,new X([]));
for(var aE=0,aF=av.length;
aE<aF;
aE++){if(av[aE].value===aH){aD(aG,av[aE].items);
}}};
var aC=function(aL,aF){for(var aG=0,aH=aF.length;
aG<aH;
aG++){var aE=aF[aG];
var aI=aA.dataSource.get(aE.get(aw.dataResourceIdField));
var aK=aE.get(aw.dataValueField);
var aJ=aE.get(aw.dataResourceIdField);
var aM=aI.get(aA.dataFormatField)||Z;
var aD=R.toString(aK,aM);
aL[aA.field].push(new Y({id:aJ,name:aI.get(aA.dataTextField),color:aI.get(aA.dataColorField),value:aK,formatedValue:aD}));
}};
for(var ay=0,az=aB.length;
ay<az;
ay++){au(aB[ay],aC);
}},_wrapResourceData:function(aw){var aC=this;
var aA=[];
var ay;
var az=this.resources.dataSource.view();
var au=this.assignments.dataSource.view();
var aB=new ac(au).filter({field:aC.assignments.dataTaskIdField,operator:"eq",value:aw}).toArray();
var aD=function(aE){var aF=null;
new ac(aB).filter({field:aC.assignments.dataResourceIdField,operator:"eq",value:aE}).select(function(aG){aF+=aG.get(aC.assignments.dataValueField);
});
return aF;
};
for(var av=0,ax=az.length;
av<ax;
av++){ay=az[av];
aA.push({id:ay.get("id"),name:ay.get(aC.resources.dataTextField),format:ay.get(aC.resources.dataFormatField)||Z,value:aD(ay.id)});
}return aA;
},_syncDataSource:function(){this._preventRefresh=false;
this._requestStart();
this.dataSource.sync();
},_requestStart:function(){this._progress(true);
},_error:function(){this._progress(false);
},_progress:function(au){R.ui.progress(this.element,au);
},_resizable:function(){var aw=this;
var aC=this.wrapper;
var av=G.styles;
var au=B+av.gridContent;
var aB=aC.find(B+av.list);
var az=aC.find(B+av.timeline);
var aA;
var ay;
var ax;
this._resizeDraggable=aC.find(B+av.splitBar).height(aB.height()).hover(function(){l(this).addClass(av.splitBarHover);
},function(){l(this).removeClass(av.splitBarHover);
}).end().kendoResizable({orientation:"horizontal",handle:B+av.splitBar,start:function(){aA=aB.width();
ay=az.width();
ax=az.find(au).scrollLeft();
},resize:function(aE){var aD=aE.x.initialDelta;
if(R.support.isRtl(aC)){aD*=-1;
}if(aA+aD<0||ay-aD<0){return;
}aB.width(aA+aD);
az.width(ay-aD);
az.find(au).scrollLeft(ax+aD);
aw.timeline.view()._renderCurrentTime();
}}).data("kendoResizable");
},_scrollable:function(){var ax=this;
var av=G.styles;
var au=B+av.gridContent;
var aw=B+av.gridHeaderWrap;
var az=this.timeline.element.find(aw);
var ay=this.timeline.element.find(au);
var aB=this.list.element.find(aw);
var aA=this.list.element.find(au);
if(U){aA.css("overflow-y","auto");
}ay.on("scroll",function(){ax.scrollTop=this.scrollTop;
az.scrollLeft(this.scrollLeft);
aA.scrollTop(this.scrollTop);
});
aA.on("scroll",function(){ax.scrollTop=this.scrollTop;
aB.scrollLeft(this.scrollLeft);
ay.scrollTop(this.scrollTop);
}).on("DOMMouseScroll"+V+" mousewheel"+V,function(aD){var aE=ay.scrollTop();
var aC=R.wheelDeltaY(aD);
if(aC){aD.preventDefault();
l(aD.currentTarget).one("wheel"+V,false);
ay.scrollTop(aE+-aC);
}});
},_navigatable:function(){var aI=this;
var aF=this.options.navigatable;
var ay=this.options.editable;
var aB=this.list.header.find("table");
var aw=this.list.content.find("table");
var aA=G.styles;
var aC=R.support.isRtl(this.wrapper);
var aJ=this.timeline.element.find(B+aA.gridContent);
var aH=aB.add(aw);
var au=ag();
var av;
var az={collapse:false,expand:true};
var aG=function(aL){var aM=aI.timeline.view()._timeSlots()[0].offsetWidth;
aJ.scrollLeft(aJ.scrollLeft()+(aL?-aM:aM));
};
var aE=function(aM){var aN=aI.current.parent("tr"+ag());
var aL=aI.current.index();
var aO=aN[aM]();
if(aI.select().length!==0){aI.clearSelection();
}if(aO.length!==0){aI._current(aO.children("td:eq("+aL+")"));
aI._scrollTo(aI.current);
}else{if(aI.current.is("td")&&aM=="prev"){F(aB);
}else{if(aI.current.is("th")&&aM=="next"){F(aw);
}}}};
var aD=function(aL){var aM=aI.current[aL]();
if(aM.length!==0){aI._current(aM);
av=aI.current.index();
}};
var aK=function(aM){var aL=aI.dataItem(aI.current);
if(aL.summary&&aL.expanded!==aM){aL.set("expanded",aM);
}};
var ax=function(){if(!aI.options.editable||aI.list.editable){return;
}var aL=aI.select();
var aM=R.attr("uid");
if(aL.length){aI.removeTask(aL.attr(aM));
}};
l(this.wrapper).on("mousedown"+V,"tr"+au+", div"+au+":not("+B+aA.line+")",function(aN){var aM=l(aN.currentTarget);
var aO=l(aN.target).is(":button,a,:input,a>.k-icon,textarea,span.k-icon,span.k-link,.k-input,.k-multiselect-wrap");
var aL;
if(aN.ctrlKey){return;
}if(aF){if(aM.is("tr")){aL=l(aN.target).closest("td");
}else{aL=aI.list.content.find("tr"+ag(aM.attr(R.attr("uid")))+" > td:first");
}aI._current(aL);
}if((aF||ay)&&!aO){aI._focusTimeout=setTimeout(function(){F(aI.list.content.find("table"),true);
},2);
}});
if(aF!==true){aw.on("keydown"+V,function(aL){if(aL.keyCode==S.DELETE){ax();
}});
return;
}aH.on("focus"+V,function(){var aN=this===aw.get(0)?"td":"th";
var aM=aI.select();
var aL=aI.current||l(aM.length?aM:this).find(aN+":eq("+(av||0)+")");
aI._current(aL);
}).on("blur"+V,function(){aI._current();
if(this==aB){l(this).attr(aj,-1);
}}).on("keydown"+V,function(aL){var aN=aL.keyCode;
var aM;
if(!aI.current){return;
}aM=aI.current.is("td");
switch(aN){case S.RIGHT:aL.preventDefault();
if(aL.altKey){aG();
}else{if(aL.ctrlKey){aK(aC?az.collapse:az.expand);
}else{aD(aC?"prev":"next");
}}break;
case S.LEFT:aL.preventDefault();
if(aL.altKey){aG(true);
}else{if(aL.ctrlKey){aK(aC?az.expand:az.collapse);
}else{aD(aC?"next":"prev");
}}break;
case S.UP:aL.preventDefault();
aE("prev");
break;
case S.DOWN:aL.preventDefault();
aE("next");
break;
case S.SPACEBAR:aL.preventDefault();
if(aM){aI.select(aI.current.closest("tr"));
}break;
case S.ENTER:aL.preventDefault();
if(aM){if(aI.options.editable){aI._cachedCurrent=aI.current;
aI.list._startEditHandler(aI.current);
l(this).one("keyup",function(aO){aO.stopPropagation();
});
}}else{aI.current.children("a.k-link").click();
}break;
case S.ESC:aL.stopPropagation();
break;
case S.DELETE:if(aM){ax();
}break;
default:if(aN>=49&&aN<=57){aI.view(aI.timeline._viewByIndex(aN-49));
}break;
}});
},_current:function(av){var aw=G.styles;
var au;
if(this.current&&this.current.length){this.current.removeClass(aw.focused).removeAttr("id");
}if(av&&av.length){this.current=av.addClass(aw.focused).attr("id",m);
au=l(R._activeElement());
if(au.is("table")&&this.wrapper.find(au).length>0){au.removeAttr(o).attr(o,m);
}}else{this.current=null;
}},_dataBind:function(){var av=this;
if(av.options.autoBind){this._preventRefresh=true;
this._preventDependencyRefresh=true;
var au=l.map([this.dataSource,this.dependencies,this.resources.dataSource,this.assignments.dataSource],function(aw){return aw.fetch();
});
l.when.apply(null,au).done(function(){av._preventRefresh=false;
av._preventDependencyRefresh=false;
av.refresh();
});
}},_resize:function(){this._adjustDimensions();
this.timeline.view()._adjustHeight();
this.timeline.view()._renderCurrentTime();
this.list._adjustHeight();
}});
if(R.PDFMixin){R.PDFMixin.extend(G.fn);
G.fn._drawPDF=function(){var av=G.styles;
var aw="."+av.list;
var ax=this.wrapper.find(aw).width();
var au=this.wrapper.clone();
au.find(aw).css("width",ax);
return this._drawPDFShadow({content:au},{avoidLinks:this.options.pdf.avoidLinks});
};
}R.ui.plugin(G);
E(true,G,{styles:K});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
