(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.list",["kendo.data","kendo.popup"],l);
}(function(){var k={id:"list",name:"List",category:"framework",depends:["data","popup"],hidden:true};
(function(l,R){var z=window.kendo,Q=z.ui,T=Q.Widget,A=z.keys,P=z.support,v=z.htmlEncode,m=z._activeElement,E=z.data.ObservableArray,w="id",q="change",t="k-state-focused",u="k-state-hover",C="k-loading",F="open",r="close",p="cascade",L="select",M="selected",K="requestStart",J="requestEnd",U="width",s=l.extend,G=l.proxy,x=l.isArray,o=P.browser,y=o.msie&&o.version<9,H=/"/g,n={ComboBox:"DropDownList",DropDownList:"ComboBox"};
var B=z.ui.DataBoundWidget.extend({init:function(V,Y){var Z=this,X=Z.ns,W;
T.fn.init.call(Z,V,Y);
V=Z.element;
Y=Z.options;
Z._isSelect=V.is(L);
if(Z._isSelect&&Z.element[0].length){if(!Y.dataSource){Y.dataTextField=Y.dataTextField||"text";
Y.dataValueField=Y.dataValueField||"value";
}}Z.ul=l('<ul unselectable="on" class="k-list k-reset"/>').attr({tabIndex:-1,"aria-hidden":true});
Z.list=l("<div class='k-list-container'/>").append(Z.ul).on("mousedown"+X,G(Z._listMousedown,Z));
W=V.attr(w);
if(W){Z.list.attr(w,W+"-list");
Z.ul.attr(w,W+"_listbox");
}Z._header();
Z._accessors();
Z._initValue();
},options:{valuePrimitive:false,headerTemplate:""},setOptions:function(V){T.fn.setOptions.call(this,V);
if(V&&V.enable!==R){V.enabled=V.enable;
}},focus:function(){this._focused.focus();
},readonly:function(V){this._editable({readonly:V===R?true:V,disable:false});
},enable:function(V){this._editable({readonly:false,disable:!(V=V===R?true:V)});
},_listOptions:function(X){var Y=this;
var V=Y.options;
var Z=V.virtual;
var W=G(Y._listBound,Y);
Z=typeof Z==="object"?Z:{};
X=l.extend({autoBind:false,selectable:true,dataSource:Y.dataSource,click:G(Y._click,Y),change:G(Y._listChange,Y),activate:G(Y._activateItem,Y),deactivate:G(Y._deactivateItem,Y),dataBinding:function(){Y.trigger("dataBinding");
Y._angularItems("cleanup");
},dataBound:W,listBound:W,height:V.height,dataValueField:V.dataValueField,dataTextField:V.dataTextField,groupTemplate:V.groupTemplate,fixedGroupTemplate:V.fixedGroupTemplate,template:V.template},X,Z);
if(!X.template){X.template="#:"+z.expr(X.dataTextField,"data")+"#";
}return X;
},_initList:function(){var W=this;
var V=W._listOptions({selectedItemChange:G(W._listChange,W)});
if(!W.options.virtual){W.listView=new z.ui.StaticList(W.ul,V);
}else{W.listView=new z.ui.VirtualList(W.ul,V);
}W._setListValue();
},_setListValue:function(V){V=V||this.options.value;
if(V!==R){this.listView.value(V).done(G(this._updateSelectionState,this));
}},_updateSelectionState:l.noop,_listMousedown:function(V){if(!this.filterInput||this.filterInput[0]!==V.target){V.preventDefault();
}},_isFilterEnabled:function(){var V=this.options.filter;
return V&&V!=="none";
},_filterSource:function(X,Y){var ab=this;
var Z=ab.options;
var V=ab.dataSource;
var W=s({},V.filter()||{});
var aa=I(W,Z.dataTextField);
if((X||aa)&&ab.trigger("filtering",{filter:X})){return;
}W={filters:W.filters||[],logic:"and"};
if(X){W.filters.push(X);
}if(ab._cascading){this.listView.setDSFilter(W);
}if(!Y){V.filter(W);
}else{V.read({filter:W});
}},_header:function(){var X=this;
var W=X.options.headerTemplate;
var V;
if(l.isFunction(W)){W=W({});
}if(W){X.list.prepend(W);
V=X.ul.prev();
X.header=V[0]?V:null;
if(X.header){X.angular("compile",function(){return{elements:X.header};
});
}}},_initValue:function(){var V=this,W=V.options.value;
if(W!==null){V.element.val(W);
}else{W=V._accessor();
V.options.value=W;
}V._old=W;
},_ignoreCase:function(){var X=this,W=X.dataSource.reader.model,V;
if(W&&W.fields){V=W.fields[X.options.dataTextField];
if(V&&V.type&&V.type!=="string"){X.options.ignoreCase=false;
}}},_focus:function(V){return this.listView.focus(V);
},current:function(V){return this._focus(V);
},items:function(){return this.ul[0].children;
},destroy:function(){var W=this;
var V=W.ns;
T.fn.destroy.call(W);
W._unbindDataSource();
W.listView.destroy();
W.list.off(V);
W.popup.destroy();
if(W._form){W._form.off("reset",W._resetHandler);
}},dataItem:function(V){var W=this;
if(V===R){return W.listView.selectedDataItems()[0];
}if(typeof V!=="number"){if(W.options.virtual){return W.dataSource.getByUid(l(V).data("uid"));
}V=l(W.items()).index(V);
}return W.dataSource.flatView()[V];
},_activateItem:function(){var V=this.listView.focus();
if(V){this._focused.add(this.filterInput).attr("aria-activedescendant",V.attr("id"));
}},_deactivateItem:function(){this._focused.add(this.filterInput).removeAttr("aria-activedescendant");
},_accessors:function(){var Z=this;
var V=Z.element;
var X=Z.options;
var W=z.getter;
var Y=V.attr(z.attr("text-field"));
var aa=V.attr(z.attr("value-field"));
if(!X.dataTextField&&Y){X.dataTextField=Y;
}if(!X.dataValueField&&aa){X.dataValueField=aa;
}Z._text=W(X.dataTextField);
Z._value=W(X.dataValueField);
},_aria:function(W){var Y=this,X=Y.options,V=Y._focused.add(Y.filterInput);
if(X.suggest!==R){V.attr("aria-autocomplete",X.suggest?"both":"list");
}W=W?W+" "+Y.ul[0].id:Y.ul[0].id;
V.attr("aria-owns",W);
Y.ul.attr("aria-live",!Y._isFilterEnabled()?"off":"polite");
},_blur:function(){var V=this;
V._change();
V.close();
},_change:function(){var X=this;
var V=X.selectedIndex;
var W=X.options.value;
var Z=X.value();
var Y;
if(X._isSelect&&!X.listView.bound()&&W){Z=W;
}if(Z!==S(X._old,typeof Z)){Y=true;
}else{if(V!==R&&V!==X._oldIndex){Y=true;
}}if(Y){X._old=Z;
X._oldIndex=V;
if(!X._typing){X.element.trigger(q);
}X.trigger(q);
}X.typing=false;
},_data:function(){return this.dataSource.view();
},_enable:function(){var X=this,W=X.options,V=X.element.is("[disabled]");
if(W.enable!==R){W.enabled=W.enable;
}if(!W.enabled||V){X.enable(false);
}else{X.readonly(X.element.is("[readonly]"));
}},_dataValue:function(V){var W=this._value(V);
if(W===R){W=this._text(V);
}return W;
},_offsetHeight:function(){var V=0;
var W=this.listView.content.prevAll(":visible");
W.each(function(){var X=l(this);
if(X.hasClass("k-list-filter")){V+=X.children().outerHeight();
}else{V+=X.outerHeight();
}});
return V;
},_height:function(W){var aa=this;
var X=aa.list;
var V=aa.options.height;
var ab=aa.popup.visible();
var Y;
var Z;
if(W){Z=X.add(X.parent(".k-animation-container")).show();
if(!X.is(":visible")){Z.hide();
return;
}V=aa.listView.content[0].scrollHeight>V?V:"auto";
Z.height(V);
if(V!=="auto"){Y=aa._offsetHeight();
if(Y){V-=Y;
}}aa.listView.content.height(V);
if(!ab){Z.hide();
}}return V;
},_adjustListWidth:function(){var X=this.list,Y=X[0].style.width,Z=this.wrapper,V,W;
if(!X.data(U)&&Y){return;
}V=window.getComputedStyle?window.getComputedStyle(Z[0],null):0;
W=parseFloat(V&&V.width)||Z.outerWidth();
if(V&&o.msie){W+=parseFloat(V.paddingLeft)+parseFloat(V.paddingRight)+parseFloat(V.borderLeftWidth)+parseFloat(V.borderRightWidth);
}if(X.css("box-sizing")!=="border-box"){Y=W-(X.outerWidth()-X.width());
}else{Y=W;
}X.css({fontFamily:Z.css("font-family"),width:Y}).data(U,Y);
return true;
},_openHandler:function(V){this._adjustListWidth();
if(this.trigger(F)){V.preventDefault();
}else{this._focused.attr("aria-expanded",true);
this.ul.attr("aria-hidden",false);
}},_closeHandler:function(V){if(this.trigger(r)){V.preventDefault();
}else{this._focused.attr("aria-expanded",false);
this.ul.attr("aria-hidden",true);
}},_focusItem:function(){var X=this.listView;
var V=X.focus();
var W=X.select();
W=W[W.length-1];
if(W===R&&this.options.highlightFirst&&!V){W=0;
}if(W!==R){X.focus(W);
}else{X.scrollToIndex(0);
}},_calculateGroupPadding:function(W){var X=this.ul.children(".k-first:first");
var V=this.listView.content.prev(".k-group-header");
var Y=0;
if(V[0]&&V[0].style.display!=="none"){if(W!=="auto"){Y=z.support.scrollbar();
}Y+=parseFloat(X.css("border-right-width"),10)+parseFloat(X.children(".k-group").css("padding-right"),10);
V.css("padding-right",Y);
}},_calculatePopupHeight:function(V){var W=this._height(this.dataSource.flatView().length||V);
this._calculateGroupPadding(W);
},_resizePopup:function(V){if(this.options.virtual){return;
}if(!this.popup.element.is(":visible")){this.popup.one("open",function(W){return G(function(){this._calculatePopupHeight(W);
},this);
}.call(this,V));
}else{this._calculatePopupHeight(V);
}},_popup:function(){var V=this;
V.popup=new Q.Popup(V.list,s({},V.options.popup,{anchor:V.wrapper,open:G(V._openHandler,V),close:G(V._closeHandler,V),animation:V.options.animation,isRtl:P.isRtl(V.wrapper)}));
},_makeUnselectable:function(){if(y){this.list.find("*").not(".k-textbox").attr("unselectable","on");
}},_toggleHover:function(V){l(V.currentTarget).toggleClass(u,V.type==="mouseenter");
},_toggle:function(V,W){var X=this;
var Y=P.mobileOS&&(P.touch||P.MSPointers||P.pointers);
V=V!==R?V:!X.popup.visible();
if(!W&&!Y&&X._focused[0]!==m()){X._prevent=true;
X._focused.focus();
X._prevent=false;
}X[V?F:r]();
},_triggerCascade:function(){var V=this;
if(!V._cascadeTriggered||V._old!==V.value()||V._oldIndex!==V.selectedIndex){V._cascadeTriggered=true;
V.trigger(p,{userTriggered:V._userTriggered});
}},_triggerChange:function(){if(this._valueBeforeCascade!==this.value()){this.trigger(q);
}},_unbindDataSource:function(){var V=this;
V.dataSource.unbind(K,V._requestStartHandler).unbind(J,V._requestEndHandler).unbind("error",V._errorHandler);
}});
function S(W,V){if(W!==R&&W!==""&&W!==null){if(V==="boolean"){W=Boolean(W);
}else{if(V==="number"){W=Number(W);
}else{if(V==="string"){W=W.toString();
}}}}return W;
}s(B,{inArray:function(X,Y){var V,W,Z=Y.children;
if(!X||X.parentNode!==Y){return -1;
}for(V=0,W=Z.length;
V<W;
V++){if(X===Z[V]){return V;
}}return -1;
},unifyType:S});
z.ui.List=B;
Q.Select=B.extend({init:function(V,W){B.fn.init.call(this,V,W);
this._initial=this.element.val();
},setDataSource:function(V){var X=this;
var W;
X.options.dataSource=V;
X._dataSource();
if(X.listView.bound()){X._initialIndex=null;
}X.listView.setDataSource(X.dataSource);
if(X.options.autoBind){X.dataSource.fetch();
}W=X._parentWidget();
if(W){X._cascadeSelect(W);
}},close:function(){this.popup.close();
},select:function(V){var W=this;
if(V===R){return W.selectedIndex;
}else{W._select(V);
W._old=W._accessor();
W._oldIndex=W.selectedIndex;
}},search:function(aa){aa=typeof aa==="string"?aa:this.text();
var Z=this;
var X=aa.length;
var Y=Z.options;
var W=Y.ignoreCase;
var V=Y.dataTextField;
clearTimeout(Z._typingTimeout);
if(!X||X>=Y.minLength){Z._state="filter";
if(!Z._isFilterEnabled()){Z._filter(aa);
}else{Z._open=true;
Z._filterSource({value:W?aa.toLowerCase():aa,field:V,operator:Y.filter,ignoreCase:W});
}}},_accessor:function(W,V){return this[this._isSelect?"_accessorSelect":"_accessorInput"](W,V);
},_accessorInput:function(W){var V=this.element[0];
if(W===R){return V.value;
}else{if(W===null){W="";
}V.value=W;
}},_accessorSelect:function(Z,W){var V=this.element[0];
var Y=V.selectedIndex;
var X;
if(Z===R){if(Y>-1){X=V.options[Y];
}if(X){Z=X.value;
}return Z||"";
}else{if(Y>-1){V.options[Y].removeAttribute(M);
V.options[Y].selected=false;
}if(W===R){W=-1;
}if(Z!==null&&Z!==""&&W==-1){this._custom(Z);
}else{if(Z){V.value=Z;
}else{V.selectedIndex=W;
}if(V.selectedIndex>-1){X=V.options[V.selectedIndex];
}if(X){X.setAttribute(M,M);
}}}},_custom:function(Y){var X=this;
var W=X.element;
var V=X._customOption;
if(!V){V=l("<option/>");
X._customOption=V;
W.append(V);
}V.text(Y);
V[0].setAttribute(M,M);
V[0].selected=true;
},_hideBusy:function(){var V=this;
clearTimeout(V._busy);
V._arrow.removeClass(C);
V._focused.attr("aria-busy",false);
V._busy=null;
},_showBusy:function(){var V=this;
V._request=true;
if(V._busy){return;
}V._busy=setTimeout(function(){if(V._arrow){V._focused.attr("aria-busy",true);
V._arrow.addClass(C);
}},100);
},_requestEnd:function(){this._request=false;
this._hideBusy();
},_dataSource:function(){var Z=this,W=Z.element,Y=Z.options,V=Y.dataSource||{},X;
V=l.isArray(V)?{data:V}:V;
if(Z._isSelect){X=W[0].selectedIndex;
if(X>-1){Y.index=X;
}V.select=W;
V.fields=[{field:Y.dataTextField},{field:Y.dataValueField}];
}if(Z.dataSource){Z._unbindDataSource();
}else{Z._requestStartHandler=G(Z._showBusy,Z);
Z._requestEndHandler=G(Z._requestEnd,Z);
Z._errorHandler=G(Z._hideBusy,Z);
}Z.dataSource=z.data.DataSource.create(V).bind(K,Z._requestStartHandler).bind(J,Z._requestEndHandler).bind("error",Z._errorHandler);
},_firstItem:function(){this.listView.focusFirst();
},_lastItem:function(){this.listView.focusLast();
},_nextItem:function(){this.listView.focusNext();
},_prevItem:function(){this.listView.focusPrev();
},_move:function(Z){var ac=this;
var aa=Z.keyCode;
var Y=aa===A.DOWN;
var X;
var ab;
var W;
if(aa===A.UP||Y){if(Z.altKey){ac.toggle(Y);
}else{if(!ac.listView.bound()){if(!ac._fetch){ac.dataSource.one(q,function(){ac._fetch=false;
ac._move(Z);
});
ac._fetch=true;
ac._filterSource();
}Z.preventDefault();
return true;
}W=ac._focus();
if(!ac._fetch&&(!W||W.hasClass("k-state-selected"))){if(Y){ac._nextItem();
if(!ac._focus()){ac._lastItem();
}}else{ac._prevItem();
if(!ac._focus()){ac._firstItem();
}}}if(ac.trigger(L,{item:ac._focus()})){ac._focus(W);
return;
}ac._select(ac._focus(),true);
if(!ac.popup.visible()){ac._blur();
}}Z.preventDefault();
ab=true;
}else{if(aa===A.ENTER||aa===A.TAB){if(ac.popup.visible()){Z.preventDefault();
}W=ac._focus();
X=ac.dataItem();
if(!ac.popup.visible()&&(!X||ac.text()!==ac._text(X))){W=null;
}var V=ac.filterInput&&ac.filterInput[0]===m();
if(W){if(ac.trigger(L,{item:W})){return;
}ac._select(W);
}else{if(ac.input){ac._accessor(ac.input.val());
ac.listView.value(ac.input.val());
}}if(ac._focusElement){ac._focusElement(ac.wrapper);
}if(V&&aa===A.TAB){ac.wrapper.focusout();
}else{ac._blur();
}ac.close();
ab=true;
}else{if(aa===A.ESC){if(ac.popup.visible()){Z.preventDefault();
}ac.close();
ab=true;
}}}return ab;
},_fetchData:function(){var W=this;
var V=!!W.dataSource.view().length;
if(W._request||W.options.cascadeFrom){return;
}if(!W.listView.bound()&&!W._fetch&&!V){W._fetch=true;
W.dataSource.fetch().done(function(){W._fetch=false;
});
}},_options:function(V,ad,ag){var af=this,Z=af.element,ab=V.length,ae="",ac,W,X,Y,aa=0;
if(ad){ae=ad;
}for(;
aa<ab;
aa++){ac="<option";
W=V[aa];
X=af._text(W);
Y=af._value(W);
if(Y!==R){Y+="";
if(Y.indexOf('"')!==-1){Y=Y.replace(H,"&quot;");
}ac+=' value="'+Y+'"';
}ac+=">";
if(X!==R){ac+=v(X);
}ac+="</option>";
ae+=ac;
}Z.html(ae);
if(ag!==R){Z[0].value=ag;
if(Z[0].value&&!ag){Z[0].selectedIndex=-1;
}}},_reset:function(){var Y=this,V=Y.element,X=V.attr("form"),W=X?l("#"+X):V.closest("form");
if(W[0]){Y._resetHandler=function(){setTimeout(function(){Y.value(Y._initial);
});
};
Y._form=W.on("reset",Y._resetHandler);
}},_parentWidget:function(){var V=this.options.name;
var X=l("#"+this.options.cascadeFrom);
var W=X.data("kendo"+V);
if(!W){W=X.data("kendo"+n[V]);
}return W;
},_cascade:function(){var Z=this;
var X=Z.options;
var V=X.cascadeFrom;
var W;
var Y;
if(V){Y=Z._parentWidget();
if(!Y){return;
}Y.bind("set",function(){Z.one("set",function(aa){Z._selectedValue=aa.value;
});
});
X.autoBind=false;
W=G(function(aa){var ab=this.value();
this._userTriggered=aa.userTriggered;
if(this.listView.bound()){this._clearSelection(Y,true);
}this._cascadeSelect(Y,ab);
},Z);
Y.first(p,W);
Y._focused.bind("focus",function(){Y.unbind(p,W);
Y.first(q,W);
});
Y._focused.bind("focusout",function(){Y.unbind(q,W);
Y.first(p,W);
});
if(Y.listView.bound()){Z._cascadeSelect(Y);
}else{if(!Y.value()){Z.enable(false);
}}}},_cascadeChange:function(V){var W=this;
var X=W._accessor()||W._selectedValue;
W._selectedValue=null;
if(W._userTriggered){W._clearSelection(V,true);
}else{if(X){if(X!==W.listView.value()[0]){W.value(X);
}if(!W.dataSource.view()[0]||W.selectedIndex===-1){W._clearSelection(V,true);
}}else{if(W.dataSource.flatView().length){W.select(W.options.index);
}}}W.enable();
W._triggerCascade();
W._triggerChange();
W._userTriggered=false;
},_cascadeSelect:function(aa,ac){var ab=this;
var V=aa.dataItem();
var Y=V?aa._value(V):null;
var ad=ab.options.cascadeFromField||aa.options.dataValueField;
var W,X;
ab._valueBeforeCascade=ac!==R?ac:ab.value();
if(Y||Y===0){W=ab.dataSource.filter()||{};
I(W,ad);
X=(W.filters||[]).slice(0);
X.push({field:ad,operator:"eq",value:Y});
var Z=function(){ab.unbind("dataBound",Z);
ab._cascadeChange(aa);
};
ab.first("dataBound",Z);
ab._cascading=true;
ab._filterSource({field:ad,operator:"eq",value:Y});
ab._cascading=false;
}else{ab.enable(false);
ab._clearSelection(aa);
ab._triggerCascade();
ab._triggerChange();
ab._userTriggered=false;
}}});
var N=".StaticList";
var O=z.ui.DataBoundWidget.extend({init:function(V,W){T.fn.init.call(this,V,W);
this.element.attr("role","listbox").on("click"+N,"li",G(this._click,this)).on("mouseenter"+N,"li",function(){l(this).addClass(u);
}).on("mouseleave"+N,"li",function(){l(this).removeClass(u);
});
this.content=this.element.wrap("<div class='k-list-scroller' unselectable='on'></div>").parent();
this.header=this.content.before('<div class="k-group-header" style="display:none"></div>').prev();
this.bound(false);
this._optionID=z.guid();
this._selectedIndices=[];
this._view=[];
this._dataItems=[];
this._values=[];
var X=this.options.value;
if(X){this._values=l.isArray(X)?X.slice(0):[X];
}this._getter();
this._templates();
this.setDataSource(this.options.dataSource);
this._onScroll=G(function(){var Y=this;
clearTimeout(Y._scrollId);
Y._scrollId=setTimeout(function(){Y._renderHeader();
},50);
},this);
},options:{name:"StaticList",dataValueField:null,valuePrimitive:false,selectable:true,template:null,groupTemplate:null,fixedGroupTemplate:null},events:["click",q,"activate","deactivate","dataBinding","dataBound","selectedItemChange"],setDataSource:function(W){var X=this;
var V=W||{};
var Y;
V=l.isArray(V)?{data:V}:V;
V=z.data.DataSource.create(V);
if(X.dataSource){X.dataSource.unbind(q,X._refreshHandler);
Y=X.value();
X.value([]);
X.bound(false);
X.value(Y);
}else{X._refreshHandler=G(X.refresh,X);
}X.setDSFilter(V.filter());
X.dataSource=V.bind(q,X._refreshHandler);
X._fixedHeader();
},skip:function(){return this.dataSource.skip();
},setOptions:function(V){T.fn.setOptions.call(this,V);
this._getter();
this._templates();
this._render();
},destroy:function(){this.element.off(N);
if(this._refreshHandler){this.dataSource.unbind(q,this._refreshHandler);
}clearTimeout(this._scrollId);
T.fn.destroy.call(this);
},scrollToIndex:function(V){var W=this.element[0].children[V];
if(W){this.scroll(W);
}},scroll:function(Z){if(!Z){return;
}if(Z[0]){Z=Z[0];
}var W=this.content[0],ab=Z.offsetTop,aa=Z.offsetHeight,Y=W.scrollTop,X=W.clientHeight,V=ab+aa;
if(Y>ab){Y=ab;
}else{if(V>Y+X){Y=V-X;
}}W.scrollTop=Y;
},selectedDataItems:function(V){if(V===R){return this._dataItems.slice();
}this._dataItems=V;
this._values=this._getValues(V);
},_getValues:function(V){var W=this._valueGetter;
return l.map(V,function(X){return W(X);
});
},focusNext:function(){var V=this.focus();
if(!V){V=0;
}else{V=V.next();
}this.focus(V);
},focusPrev:function(){var V=this.focus();
if(!V){V=this.element[0].children.length-1;
}else{V=V.prev();
}this.focus(V);
},focusFirst:function(){this.focus(this.element[0].children[0]);
},focusLast:function(){this.focus(this.element[0].children[this.element[0].children.length-1]);
},focus:function(V){var Y=this;
var X=Y._optionID;
var W;
if(V===R){return Y._current;
}V=Y._get(V);
V=V[V.length-1];
V=l(this.element[0].children[V]);
if(Y._current){Y._current.removeClass(t).removeAttr("aria-selected").removeAttr(w);
Y.trigger("deactivate");
}W=!!V[0];
if(W){V.addClass(t);
Y.scroll(V);
V.attr("id",X);
}Y._current=W?V:null;
Y.trigger("activate");
},focusIndex:function(){return this.focus()?this.focus().index():R;
},skipUpdate:function(V){this._skipUpdate=V;
},select:function(X){var ad=this;
var aa=ad.options.selectable;
var ac=aa!=="multiple"&&aa!==false;
var ab=ad._selectedIndices;
var V=[];
var Y=[];
var Z;
if(X===R){return ab.slice();
}X=ad._get(X);
if(X.length===1&&X[0]===-1){X=[];
}var W=ad.isFiltered();
if(W&&!ac&&ad._deselectFiltered(X)){return;
}if(ac&&!W&&l.inArray(X[X.length-1],ab)!==-1){if(ad._dataItems.length&&ad._view.length){ad._dataItems=[ad._view[ab[0]].item];
}return;
}Z=ad._deselect(X);
Y=Z.removed;
X=Z.indices;
if(X.length){if(ac){X=[X[X.length-1]];
}V=ad._select(X);
}if(V.length||Y.length){ad._valueComparer=null;
ad.trigger(q,{added:V,removed:Y});
}},removeAt:function(V){this._selectedIndices.splice(V,1);
this._values.splice(V,1);
this._valueComparer=null;
return{position:V,dataItem:this._dataItems.splice(V,1)[0]};
},setValue:function(V){V=l.isArray(V)||V instanceof E?V.slice(0):[V];
this._values=V;
this._valueComparer=null;
},value:function(Y){var X=this;
var V=X._valueDeferred;
var W;
if(Y===R){return X._values.slice();
}X.setValue(Y);
if(!V||V.state()==="resolved"){X._valueDeferred=V=l.Deferred();
}if(X.bound()){W=X._valueIndices(X._values);
if(X.options.selectable==="multiple"){X.select(-1);
}X.select(W);
V.resolve();
}X._skipUpdate=false;
return V;
},items:function(){return this.element.children(".k-item");
},_click:function(V){if(!V.isDefaultPrevented()){if(!this.trigger("click",{item:l(V.currentTarget)})){this.select(V.currentTarget);
}}},_valueExpr:function(aa,ab){var Z=this;
var X=0;
var V;
var W;
var Y=[];
if(!Z._valueComparer||Z._valueType!==aa){Z._valueType=aa;
for(;
X<ab.length;
X++){Y.push(S(ab[X],aa));
}V="for (var idx = 0; idx < "+Y.length+"; idx++) { if (current === values[idx]) {   return idx; }} return -1;";
W=new Function("current","values",V);
Z._valueComparer=function(ac){return W(ac,Y);
};
}return Z._valueComparer;
},_dataItemPosition:function(V,Y){var W=this._valueGetter(V);
var X=this._valueExpr(typeof W,Y);
return X(W);
},_getter:function(){this._valueGetter=z.getter(this.options.dataValueField);
},_deselect:function(Z){var ag=this;
var V=ag.element[0].children;
var ad=ag.options.selectable;
var af=ag._selectedIndices;
var W=ag._dataItems;
var ah=ag._values;
var ab=[];
var X=0;
var aa;
var Y,ae;
var ac=0;
Z=Z.slice();
if(ad===true||!Z.length){for(;
X<af.length;
X++){l(V[af[X]]).removeClass("k-state-selected");
ab.push({position:X,dataItem:W[X]});
}ag._values=[];
ag._dataItems=[];
ag._selectedIndices=[];
}else{if(ad==="multiple"){for(;
X<Z.length;
X++){Y=Z[X];
if(!l(V[Y]).hasClass("k-state-selected")){continue;
}for(aa=0;
aa<af.length;
aa++){ae=af[aa];
if(ae===Y){l(V[ae]).removeClass("k-state-selected");
ab.push({position:aa+ac,dataItem:W.splice(aa,1)[0]});
af.splice(aa,1);
Z.splice(X,1);
ah.splice(aa,1);
ac+=1;
X-=1;
aa-=1;
break;
}}}}}return{indices:Z,removed:ab};
},_deselectFiltered:function(Z){var V=this.element[0].children;
var W,Y,aa;
var ab=[];
var X=0;
for(;
X<Z.length;
X++){Y=Z[X];
W=this._view[Y].item;
aa=this._dataItemPosition(W,this._values);
if(aa>-1){ab.push(this.removeAt(aa));
l(V[Y]).removeClass("k-state-selected");
}}if(ab.length){this.trigger(q,{added:[],removed:ab});
return true;
}return false;
},_select:function(ab){var ac=this;
var W=ac.element[0].children;
var X=ac._view;
var Y,aa;
var V=[];
var Z=0;
if(ab[ab.length-1]!==-1){ac.focus(ab);
}for(;
Z<ab.length;
Z++){aa=ab[Z];
Y=X[aa];
if(aa===-1||!Y){continue;
}Y=Y.item;
ac._selectedIndices.push(aa);
ac._dataItems.push(Y);
ac._values.push(ac._valueGetter(Y));
l(W[aa]).addClass("k-state-selected").attr("aria-selected",true);
V.push({dataItem:Y});
}return V;
},_get:function(V){if(typeof V==="number"){V=[V];
}else{if(!x(V)){V=l(V).data("offset-index");
if(V===R){V=-1;
}V=[V];
}}return V;
},_template:function(){var X=this;
var V=X.options;
var W=V.template;
if(!W){W=z.template('<li tabindex="-1" role="option" unselectable="on" class="k-item">${'+z.expr(V.dataTextField,"data")+"}</li>",{useWithBlock:false});
}else{W=z.template(W);
W=function(Y){return'<li tabindex="-1" role="option" unselectable="on" class="k-item">'+W(Y)+"</li>";
};
}return W;
},_templates:function(){var W;
var X={template:this.options.template,groupTemplate:this.options.groupTemplate,fixedGroupTemplate:this.options.fixedGroupTemplate};
for(var V in X){W=X[V];
if(W&&typeof W!=="function"){X[V]=z.template(W);
}}this.templates=X;
},_normalizeIndices:function(W){var X=[];
var V=0;
for(;
V<W.length;
V++){if(W[V]!==R){X.push(W[V]);
}}return X;
},_valueIndices:function(Z,Y){var V=this._view;
var W=0;
var X;
Y=Y?Y.slice():[];
if(!Z.length){return[];
}for(;
W<V.length;
W++){X=this._dataItemPosition(V[W].item,Z);
if(X!==-1){Y[X]=W;
}}return this._normalizeIndices(Y);
},_firstVisibleItem:function(){var W=this.element[0];
var V=this.content[0];
var ab=V.scrollTop;
var Z=l(W.children[0]).height();
var aa=Math.floor(ab/Z)||0;
var Y=W.children[aa]||W.lastChild;
var X=Y.offsetTop<ab;
while(Y){if(X){if(Y.offsetTop+Z>ab||!Y.nextSibling){break;
}Y=Y.nextSibling;
}else{if(Y.offsetTop<=ab||!Y.previousSibling){break;
}Y=Y.previousSibling;
}}return this._view[l(Y).data("offset-index")];
},_fixedHeader:function(){if(this.isGrouped()&&this.templates.fixedGroupTemplate){this.header.show();
this.content.scroll(this._onScroll);
}else{this.header.hide();
this.content.off("scroll",this._onScroll);
}},_renderHeader:function(){var V=this.templates.fixedGroupTemplate;
if(!V){return;
}var W=this._firstVisibleItem();
if(W){this.header.html(V(W.group));
}},_renderItem:function(V){var X='<li tabindex="-1" role="option" unselectable="on" class="k-item';
var W=V.item;
var Y=V.index!==0;
var Z=V.selected;
if(Y&&V.newGroup){X+=" k-first";
}if(Z){X+=" k-state-selected";
}X+='"'+(Z?' aria-selected="true"':"")+' data-offset-index="'+V.index+'">';
X+=this.templates.template(W);
if(Y&&V.newGroup){X+='<div class="k-group">'+this.templates.groupTemplate(V.group)+"</div>";
}return X+"</li>";
},_render:function(){var Y="";
var Z=0;
var aa=0;
var V;
var W=[];
var af=this.dataSource.view();
var ae=this.value();
var X,ad,ac;
var ab=this.isGrouped();
if(ab){for(Z=0;
Z<af.length;
Z++){X=af[Z];
ad=true;
for(ac=0;
ac<X.items.length;
ac++){V={selected:this._selected(X.items[ac],ae),item:X.items[ac],group:X.value,newGroup:ad,index:aa};
W[aa]=V;
aa+=1;
Y+=this._renderItem(V);
ad=false;
}}}else{for(Z=0;
Z<af.length;
Z++){V={selected:this._selected(af[Z],ae),item:af[Z],index:Z};
W[Z]=V;
Y+=this._renderItem(V);
}}this._view=W;
this.element[0].innerHTML=Y;
if(ab&&W.length){this._renderHeader();
}},_selected:function(V,X){var W=!this.isFiltered()||this.options.selectable==="multiple";
return W&&this._dataItemPosition(V,X)!==-1;
},setDSFilter:function(V){this._lastDSFilter=s({},V);
},isFiltered:function(){if(!this._lastDSFilter){this.setDSFilter(this.dataSource.filter());
}return !z.data.Query.compareFilters(this.dataSource.filter(),this._lastDSFilter);
},refresh:function(W){var aa=this;
var V=W&&W.action;
var Z=aa.options.skipUpdateOnBind;
var X=V==="itemchange";
var Y;
aa.trigger("dataBinding");
aa._fixedHeader();
aa._render();
aa.bound(true);
if(X||V==="remove"){Y=D(aa._dataItems,W.items);
if(Y.changed.length){if(X){aa.trigger("selectedItemChange",{items:Y.changed});
}else{aa.value(aa._getValues(Y.unchanged));
}}}else{if(aa.isFiltered()||aa._skipUpdate){aa.focus(0);
if(aa._skipUpdate){aa._skipUpdate=false;
aa._selectedIndices=aa._valueIndices(aa._values,aa._selectedIndices);
}}else{if(!Z&&(!V||V==="add")){aa.value(aa._values);
}}}if(aa._valueDeferred){aa._valueDeferred.resolve();
}aa.trigger("dataBound");
},bound:function(V){if(V===R){return this._bound;
}this._bound=V;
},isGrouped:function(){return(this.dataSource.group()||[]).length;
}});
Q.plugin(O);
function D(ac,aa){var Z=aa.length;
var ad=ac.length;
var W;
var X;
var Y,ab;
var V=[];
var ae=[];
if(ad){for(Y=0;
Y<ad;
Y++){W=ac[Y];
X=false;
for(ab=0;
ab<Z;
ab++){if(W===aa[ab]){X=true;
V.push({index:Y,item:W});
break;
}}if(!X){ae.push(W);
}}}return{changed:V,unchanged:ae};
}function I(V,W){var X;
var Y=false;
if(V.filters){X=l.grep(V.filters,function(Z){Y=I(Z,W);
if(Z.filters){return Z.filters.length;
}else{return Z.field!=W;
}});
if(!Y&&V.filters.length!==X.length){Y=true;
}V.filters=X;
}return Y;
}}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
