(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.menu",["kendo.popup"],l);
}(function(){var k={id:"menu",name:"Menu",category:"web",description:"The Menu widget displays hierarchical data as a multi-level menu.",depends:["popup"]};
(function(l,ar){var L=window.kendo,aq=L.ui,n=L._activeElement,ao=L.support.touch&&L.support.mobileOS,W="mousedown",q="click",C=l.extend,ah=l.proxy,z=l.each,ak=L.template,N=L.keys,aw=aq.Widget,A=/^(ul|a|div)$/i,ab=".kendoMenu",J="img",ac="open",T="k-menu",Q="k-link",O="k-last",r="close",an="timer",D="k-first",I="k-image",aj="select",ax="zIndex",m="activate",u="deactivate",ae="touchstart"+ab+" MSPointerDown"+ab+" pointerdown"+ab,af=L.support.pointers,Z=L.support.msPointers,p=Z||af,X=af?"pointerover":Z?"MSPointerOver":"mouseenter",Y=af?"pointerout":Z?"MSPointerOut":"mouseleave",V=ao||p,y=l(document.documentElement),M="kendoPopup",v="k-state-default",H="k-state-hover",E="k-state-focused",x="k-state-disabled",U=".k-menu",G=".k-menu-group",ag=G+",.k-animation-container",o=":not(.k-list) > .k-item",w=".k-item.k-state-disabled",K=".k-item:not(.k-state-disabled)",R=".k-item:not(.k-state-disabled) > .k-link",B=":not(.k-item.k-separator)",aa=B+":eq(0)",P=B+":last",am="> div:not(.k-animation-container,.k-list-container)",ap={"2":1,touch:1},al={content:ak("<div class='k-content #= groupCssClass() #' tabindex='-1'>#= content(item) #</div>"),group:ak("<ul class='#= groupCssClass(group) #'#= groupAttributes(group) # role='menu' aria-hidden='true'>#= renderItems(data) #</ul>"),itemWrapper:ak("<#= tag(item) # class='#= textClass(item) #'#= textAttributes(item) #>#= image(item) ##= sprite(item) ##= text(item) ##= arrow(data) #</#= tag(item) #>"),item:ak("<li class='#= wrapperCssClass(group, item) #' role='menuitem' #=item.items ? \"aria-haspopup='true'\": \"\"##=item.enabled === false ? \"aria-disabled='true'\" : ''#>#= itemWrapper(data) ## if (item.items) { ##= subGroup({ items: item.items, menu: menu, group: { expanded: item.expanded } }) ## } else if (item.content || item.contentUrl) { ##= renderContent(data) ## } #</li>"),image:ak("<img class='k-image' alt='' src='#= imageUrl #' />"),arrow:ak("<span class='#= arrowClass(item, group) #'></span>"),sprite:ak("<span class='k-sprite #= spriteCssClass #'></span>"),empty:ak("")},ai={wrapperCssClass:function(ay,aA){var aB="k-item",az=aA.index;
if(aA.enabled===false){aB+=" k-state-disabled";
}else{aB+=" k-state-default";
}if(ay.firstLevel&&az===0){aB+=" k-first";
}if(az==ay.length-1){aB+=" k-last";
}if(aA.cssClass){aB+=" "+aA.cssClass;
}return aB;
},textClass:function(){return Q;
},textAttributes:function(ay){return ay.url?" href='"+ay.url+"'":"";
},arrowClass:function(az,ay){var aA="k-icon";
if(ay.horizontal){aA+=" k-i-arrow-s";
}else{aA+=" k-i-arrow-e";
}return aA;
},text:function(ay){return ay.encoded===false?ay.text:L.htmlEncode(ay.text);
},tag:function(ay){return ay.url?"a":"span";
},groupAttributes:function(ay){return ay.expanded!==true?" style='display:none'":"";
},groupCssClass:function(){return"k-group k-menu-group";
},content:function(ay){return ay.content?ay.content:"&nbsp;";
}};
function F(ay,az){ay=ay.split(" ")[!az+0]||ay;
return ay.replace("top","up").replace("bottom","down");
}function ad(ay,aC,aA){ay=ay.split(" ")[!aC+0]||ay;
var aB={origin:["bottom",aA?"right":"left"],position:["top",aA?"right":"left"]},az=/left|right/.test(ay);
if(az){aB.origin=["top",ay];
aB.position[1]=L.directions[ay].reverse;
}else{aB.origin[0]=ay;
aB.position[0]=L.directions[ay].reverse;
}aB.origin=aB.origin.join(" ");
aB.position=aB.position.join(" ");
return aB;
}function s(aA,ay){try{return l.contains(aA,ay);
}catch(az){return false;
}}function av(ay){ay=l(ay);
ay.addClass("k-item").children(J).addClass(I);
ay.children("a").addClass(Q).children(J).addClass(I);
ay.filter(":not([disabled])").addClass(v);
ay.filter(".k-separator:empty").append("&nbsp;");
ay.filter("li[disabled]").addClass(x).removeAttr("disabled").attr("aria-disabled",true);
if(!ay.filter("[role]").length){ay.attr("role","menuitem");
}if(!ay.children("."+Q).length){ay.contents().filter(function(){return !this.nodeName.match(A)&&!(this.nodeType==3&&!l.trim(this.nodeValue));
}).wrapAll("<span class='"+Q+"'/>");
}at(ay);
au(ay);
}function at(ay){ay=l(ay);
ay.find("> .k-link > [class*=k-i-arrow]:not(.k-sprite)").remove();
ay.filter(":has(.k-menu-group)").children(".k-link:not(:has([class*=k-i-arrow]:not(.k-sprite)))").each(function(){var az=l(this),aA=az.parent().parent();
az.append("<span class='k-icon "+(aA.hasClass(T+"-horizontal")?"k-i-arrow-s":"k-i-arrow-e")+"'/>");
});
}function au(ay){ay=l(ay);
ay.filter(".k-first:not(:first-child)").removeClass(D);
ay.filter(".k-last:not(:last-child)").removeClass(O);
ay.filter(":first-child").addClass(D);
ay.filter(":last-child").addClass(O);
}var S=aw.extend({init:function(ay,az){var aA=this;
aw.fn.init.call(aA,ay,az);
ay=aA.wrapper=aA.element;
az=aA.options;
aA._initData(az);
aA._updateClasses();
aA._animations(az);
aA.nextItemZIndex=100;
aA._tabindex();
aA._focusProxy=ah(aA._focusHandler,aA);
ay.on(ae,K,aA._focusProxy).on(q+ab,w,false).on(q+ab,K,ah(aA._click,aA)).on("keydown"+ab,ah(aA._keydown,aA)).on("focus"+ab,ah(aA._focus,aA)).on("focus"+ab,".k-content",ah(aA._focus,aA)).on(ae+" "+W+ab,".k-content",ah(aA._preventClose,aA)).on("blur"+ab,ah(aA._removeHoverItem,aA)).on("blur"+ab,"[tabindex]",ah(aA._checkActiveElement,aA)).on(X+ab,K,ah(aA._mouseenter,aA)).on(Y+ab,K,ah(aA._mouseleave,aA)).on(X+ab+" "+Y+ab+" "+W+ab+" "+q+ab,R,ah(aA._toggleHover,aA));
if(az.openOnClick){aA.clicked=false;
aA._documentClickHandler=ah(aA._documentClick,aA);
l(document).click(aA._documentClickHandler);
}ay.attr("role","menubar");
if(ay[0].id){aA._ariaId=L.format("{0}_mn_active",ay[0].id);
}L.notify(aA);
},events:[ac,r,m,u,aj],options:{name:"Menu",animation:{open:{duration:200},close:{duration:100}},orientation:"horizontal",direction:"default",openOnClick:false,closeOnClick:true,hoverDelay:100,popupCollision:ar},_initData:function(ay){var az=this;
if(ay.dataSource){az.angular("cleanup",function(){return{elements:az.element.children()};
});
az.element.empty();
az.append(ay.dataSource,az.element);
az.angular("compile",function(){return{elements:az.element.children()};
});
}},setOptions:function(az){var ay=this.options.animation;
this._animations(az);
az.animation=C(true,ay,az.animation);
if("dataSource" in az){this._initData(az);
}this._updateClasses();
aw.fn.setOptions.call(this,az);
},destroy:function(){var ay=this;
aw.fn.destroy.call(ay);
ay.element.off(ab);
if(ay._documentClickHandler){l(document).unbind("click",ay._documentClickHandler);
}L.destroy(ay.element);
},enable:function(ay,az){this._toggleDisabled(ay,az!==false);
return this;
},disable:function(ay){this._toggleDisabled(ay,false);
return this;
},append:function(az,aA){aA=this.element.find(aA);
var ay=this._insert(az,aA,aA.length?aA.find("> .k-menu-group, > .k-animation-container > .k-menu-group"):null);
z(ay.items,function(){ay.group.append(this);
at(this);
});
at(aA);
au(ay.group.find(".k-first, .k-last").add(ay.items));
return this;
},insertBefore:function(az,aA){aA=this.element.find(aA);
var ay=this._insert(az,aA,aA.parent());
z(ay.items,function(){aA.before(this);
at(this);
au(this);
});
au(aA);
return this;
},insertAfter:function(az,aA){aA=this.element.find(aA);
var ay=this._insert(az,aA,aA.parent());
z(ay.items,function(){aA.after(this);
at(this);
au(this);
});
au(aA);
return this;
},_insert:function(aA,aE,aC){var aF=this,aB,az;
if(!aE||!aE.length){aC=aF.element;
}var aD=l.isPlainObject(aA),ay={firstLevel:aC.hasClass(T),horizontal:aC.hasClass(T+"-horizontal"),expanded:true,length:aC.children().length};
if(aE&&!aC.length){aC=l(S.renderGroup({group:ay})).appendTo(aE);
}if(aD||l.isArray(aA)){aB=l(l.map(aD?[aA]:aA,function(aH,aG){if(typeof aH==="string"){return l(aH).get();
}else{return l(S.renderItem({group:ay,item:C(aH,{index:aG})})).get();
}}));
}else{if(typeof aA=="string"&&aA.charAt(0)!="<"){aB=aF.element.find(aA);
}else{aB=l(aA);
}az=aB.find("> ul").addClass("k-menu-group").attr("role","menu");
aB=aB.filter("li");
aB.add(az.find("> li")).each(function(){av(this);
});
}return{items:aB,group:aC};
},remove:function(az){az=this.element.find(az);
var aC=this,aB=az.parentsUntil(aC.element,o),aA=az.parent("ul:not(.k-menu)");
az.remove();
if(aA&&!aA.children(o).length){var ay=aA.parent(".k-animation-container");
if(ay.length){ay.remove();
}else{aA.remove();
}}if(aB.length){aB=aB.eq(0);
at(aB);
au(aB);
}return aC;
},open:function(az){var aD=this,aC=aD.options,aA=aC.orientation=="horizontal",ay=aC.direction,aB=L.support.isRtl(aD.wrapper);
az=aD.element.find(az);
if(/^(top|bottom|default)$/.test(ay)){if(aB){ay=aA?(ay+" left").replace("default","bottom"):"left";
}else{ay=aA?(ay+" right").replace("default","bottom"):"right";
}}az.siblings().find(">.k-popup:visible,>.k-animation-container>.k-popup:visible").each(function(){var aE=l(this).data("kendoPopup");
if(aE){aE.close();
}});
az.each(function(){var aE=l(this);
clearTimeout(aE.data(an));
aE.data(an,setTimeout(function(){var aM=aE.find(".k-menu-group:first:hidden"),aJ;
if(aM[0]&&aD._triggerEvent({item:aE[0],type:ac})===false){if(!aM.find(".k-menu-group")[0]&&aM.children(".k-item").length>1){var aN=l(window).height(),aL=function(){aM.css({maxHeight:aN-(aM.outerHeight()-aM.height())-L.getShadows(aM).bottom,overflow:"auto"});
};
if(L.support.browser.msie&&L.support.browser.version<=7){setTimeout(aL,0);
}else{aL();
}}else{aM.css({maxHeight:"",overflow:""});
}aE.data(ax,aE.css(ax));
aE.css(ax,aD.nextItemZIndex++);
aJ=aM.data(M);
var aK=aE.parent().hasClass(T),aI=aK&&aA,aF=ad(ay,aK,aB),aG=aC.animation.open.effects,aH=aG!==ar?aG:"slideIn:"+F(ay,aK);
if(!aJ){aJ=aM.kendoPopup({activate:function(){aD._triggerEvent({item:this.wrapper.parent(),type:m});
},deactivate:function(aO){aO.sender.element.removeData("targetTransform").css({opacity:""});
aD._triggerEvent({item:this.wrapper.parent(),type:u});
},origin:aF.origin,position:aF.position,collision:aC.popupCollision!==ar?aC.popupCollision:aI?"fit":"fit flip",anchor:aE,appendTo:aE,animation:{open:C(true,{effects:aH},aC.animation.open),close:aC.animation.close},close:function(aO){var aP=aO.sender.wrapper.parent();
if(!aD._triggerEvent({item:aP[0],type:r})){aP.css(ax,aP.data(ax));
aP.removeData(ax);
if(ao){aP.removeClass(H);
aD._removeHoverItem();
}}else{aO.preventDefault();
}}}).data(M);
}else{aJ=aM.data(M);
aJ.options.origin=aF.origin;
aJ.options.position=aF.position;
aJ.options.animation.open.effects=aH;
}aM.removeAttr("aria-hidden");
aJ.open();
}},aD.options.hoverDelay));
});
return aD;
},close:function(aA,ay){var aB=this,az=aB.element;
aA=az.find(aA);
if(!aA.length){aA=az.find(">.k-item");
}aA.each(function(){var aC=l(this);
if(!ay&&aB._isRootItem(aC)){aB.clicked=false;
}clearTimeout(aC.data(an));
aC.data(an,setTimeout(function(){var aD=aC.find(".k-menu-group:not(.k-list-container):not(.k-calendar-container):first:visible").data(M);
if(aD){aD.close();
aD.element.attr("aria-hidden",true);
}},aB.options.hoverDelay));
});
return aB;
},_toggleDisabled:function(az,ay){this.element.find(az).each(function(){l(this).toggleClass(v,ay).toggleClass(x,!ay).attr("aria-disabled",!ay);
});
},_toggleHover:function(ay){var aA=l(L.eventTarget(ay)||ay.target).closest(o),az=ay.type==X||W.indexOf(ay.type)!==-1;
if(!aA.parents("li."+x).length){aA.toggleClass(H,az||ay.type=="mousedown"||ay.type=="click");
}this._removeHoverItem();
},_preventClose:function(){if(!this.options.closeOnClick){this._closurePrevented=true;
}},_checkActiveElement:function(ay){var aB=this,az=l(ay?ay.currentTarget:this._hoverItem()),aA=aB._findRootParent(az)[0];
if(!this._closurePrevented){setTimeout(function(){if(!document.hasFocus()||!s(aA,L._activeElement())&&ay&&!s(aA,ay.currentTarget)){aB.close(aA);
}},0);
}this._closurePrevented=false;
},_removeHoverItem:function(){var ay=this._hoverItem();
if(ay&&ay.hasClass(E)){ay.removeClass(E);
this._oldHoverItem=null;
}},_updateClasses:function(){var ay=this.element,aA=".k-menu-init div ul",az;
ay.removeClass("k-menu-horizontal k-menu-vertical");
ay.addClass("k-widget k-reset k-header k-menu-init "+T).addClass(T+"-"+this.options.orientation);
ay.find("li > ul").filter(function(){return !L.support.matchesSelector.call(this,aA);
}).addClass("k-group k-menu-group").attr("role","menu").attr("aria-hidden",ay.is(":visible")).end().find("li > div").addClass("k-content").attr("tabindex","-1");
az=ay.find("> li,.k-menu-group > li");
ay.removeClass("k-menu-init");
az.each(function(){av(this);
});
},_mouseenter:function(ay){var aB=this,az=l(ay.currentTarget),aA=az.children(".k-animation-container").length||az.children(G).length;
if(ay.delegateTarget!=az.parents(U)[0]){return;
}if((!aB.options.openOnClick||aB.clicked)&&!ao&&!((af||Z)&&ay.originalEvent.pointerType in ap&&aB._isRootItem(az.closest(o)))){if(!s(ay.currentTarget,ay.relatedTarget)&&aA){aB.open(az);
}}if(aB.options.openOnClick&&aB.clicked||V){az.siblings().each(ah(function(aC,aD){aB.close(aD,true);
},aB));
}},_mouseleave:function(ay){var aB=this,az=l(ay.currentTarget),aA=az.children(".k-animation-container").length||az.children(G).length;
if(az.parentsUntil(".k-animation-container",".k-list-container,.k-calendar-container")[0]){ay.stopImmediatePropagation();
return;
}if(!aB.options.openOnClick&&!ao&&!((af||Z)&&ay.originalEvent.pointerType in ap)&&!s(ay.currentTarget,ay.relatedTarget||ay.target)&&aA&&!s(ay.currentTarget,L._activeElement())){aB.close(az);
}},_click:function(aA){var aP=this,aJ,aK=aP.options,aN=l(L.eventTarget(aA)),aI=aN[0]?aN[0].nodeName.toUpperCase():"",aC=aI=="INPUT"||aI=="SELECT"||aI=="BUTTON"||aI=="LABEL",aH=aN.closest("."+Q),aB=aN.closest(o),aD=aH.attr("href"),ay,az,aO=aN.attr("href"),aL=l("<a href='#' />").attr("href"),aE=!!aD&&aD!==aL,aF=aE&&!!aD.match(/^#/),aG=!!aO&&aO!==aL,aM=aK.openOnClick&&az&&aP._isRootItem(aB);
if(aN.closest(am,aB[0]).length){return;
}if(aB.hasClass(x)){aA.preventDefault();
return;
}if(!aA.handled&&aP._triggerEvent({item:aB[0],type:aj})&&!aC){aA.preventDefault();
}aA.handled=true;
ay=aB.children(ag);
az=ay.is(":visible");
if(aK.closeOnClick&&(!aE||aF)&&(!ay.length||aM)){aB.removeClass(H).css("height");
aP._oldHoverItem=aP._findRootParent(aB);
aP.close(aH.parentsUntil(aP.element,o));
aP.clicked=false;
if("MSPointerUp".indexOf(aA.type)!=-1){aA.preventDefault();
}return;
}if(aE&&aA.enterKey){aH[0].click();
}if((!aP._isRootItem(aB)||!aK.openOnClick)&&!L.support.touch&&!((af||Z)&&aP._isRootItem(aB.closest(o)))){return;
}if(!aE&&!aC&&!aG){aA.preventDefault();
}aP.clicked=true;
aJ=ay.is(":visible")?r:ac;
if(!aK.closeOnClick&&aJ==r){return;
}aP[aJ](aB);
},_documentClick:function(ay){if(s(this.element[0],ay.target)){return;
}this.clicked=false;
},_focus:function(az){var aC=this,aB=az.target,aA=aC._hoverItem(),ay=n();
if(aB!=aC.wrapper[0]&&!l(aB).is(":kendoFocusable")){az.stopPropagation();
l(aB).closest(".k-content").closest(".k-menu-group").closest(".k-item").addClass(E);
aC.wrapper.focus();
return;
}if(ay===az.currentTarget){if(aA.length){aC._moveHover([],aA);
}else{if(!aC._oldHoverItem){aC._moveHover([],aC.wrapper.children().first());
}}}},_keydown:function(az){var aF=this,aD=az.keyCode,aB=aF._oldHoverItem,aE,ay,aA,aC=L.support.isRtl(aF.wrapper);
if(az.target!=az.currentTarget&&aD!=N.ESC){return;
}if(!aB){aB=aF._oldHoverItem=aF._hoverItem();
}ay=aF._itemBelongsToVertival(aB);
aA=aF._itemHasChildren(aB);
if(aD==N.RIGHT){aE=aF[aC?"_itemLeft":"_itemRight"](aB,ay,aA);
}else{if(aD==N.LEFT){aE=aF[aC?"_itemRight":"_itemLeft"](aB,ay,aA);
}else{if(aD==N.DOWN){aE=aF._itemDown(aB,ay,aA);
}else{if(aD==N.UP){aE=aF._itemUp(aB,ay,aA);
}else{if(aD==N.ESC){aE=aF._itemEsc(aB,ay);
}else{if(aD==N.ENTER||aD==N.SPACEBAR){aE=aB.children(".k-link");
if(aE.length>0){aF._click({target:aE[0],preventDefault:function(){},enterKey:true});
aF._moveHover(aB,aF._findRootParent(aB));
}}else{if(aD==N.TAB){aE=aF._findRootParent(aB);
aF._moveHover(aB,aE);
aF._checkActiveElement();
return;
}}}}}}}if(aE&&aE[0]){az.preventDefault();
az.stopPropagation();
}},_hoverItem:function(){return this.wrapper.find(".k-item.k-state-hover,.k-item.k-state-focused").filter(":visible");
},_itemBelongsToVertival:function(ay){var az=this.wrapper.hasClass("k-menu-vertical");
if(!ay.length){return az;
}return ay.parent().hasClass("k-menu-group")||az;
},_itemHasChildren:function(ay){if(!ay.length){return false;
}return ay.children("ul.k-menu-group, div.k-animation-container").length>0;
},_moveHover:function(az,aA){var aB=this,ay=aB._ariaId;
if(az.length&&aA.length){az.removeClass(E);
}if(aA.length){if(aA[0].id){ay=aA[0].id;
}aA.addClass(E);
aB._oldHoverItem=aA;
if(ay){aB.element.removeAttr("aria-activedescendant");
l("#"+ay).removeAttr("id");
aA.attr("id",ay);
aB.element.attr("aria-activedescendant",ay);
}}},_findRootParent:function(ay){if(this._isRootItem(ay)){return ay;
}else{return ay.parentsUntil(U,"li.k-item").last();
}},_isRootItem:function(ay){return ay.parent().hasClass(T);
},_itemRight:function(aA,ay,az){var aD=this,aB,aC;
if(aA.hasClass(x)){return;
}if(!ay){aB=aA.nextAll(aa);
if(!aB.length){aB=aA.prevAll(P);
}}else{if(az){aD.open(aA);
aB=aA.find(".k-menu-group").children().first();
}else{if(aD.options.orientation=="horizontal"){aC=aD._findRootParent(aA);
aD.close(aC);
aB=aC.nextAll(aa);
}}}if(aB&&!aB.length){aB=aD.wrapper.children(".k-item").first();
}else{if(!aB){aB=[];
}}aD._moveHover(aA,aB);
return aB;
},_itemLeft:function(az,ay){var aB=this,aA;
if(!ay){aA=az.prevAll(aa);
if(!aA.length){aA=az.nextAll(P);
}}else{aA=az.parent().closest(".k-item");
aB.close(aA);
if(aB._isRootItem(aA)&&aB.options.orientation=="horizontal"){aA=aA.prevAll(aa);
}}if(!aA.length){aA=aB.wrapper.children(".k-item").last();
}aB._moveHover(az,aA);
return aA;
},_itemDown:function(aA,ay,az){var aC=this,aB;
if(!ay){if(!az||aA.hasClass(x)){return;
}else{aC.open(aA);
aB=aA.find(".k-menu-group").children().first();
}}else{aB=aA.nextAll(aa);
}if(!aB.length&&aA.length){aB=aA.parent().children().first();
}else{if(!aA.length){aB=aC.wrapper.children(".k-item").first();
}}aC._moveHover(aA,aB);
return aB;
},_itemUp:function(az,ay){var aB=this,aA;
if(!ay){return;
}else{aA=az.prevAll(aa);
}if(!aA.length&&az.length){aA=az.parent().children().last();
}else{if(!az.length){aA=aB.wrapper.children(".k-item").last();
}}aB._moveHover(az,aA);
return aA;
},_itemEsc:function(az,ay){var aB=this,aA;
if(!ay){return az;
}else{aA=az.parent().closest(".k-item");
aB.close(aA);
aB._moveHover(az,aA);
}return aA;
},_triggerEvent:function(ay){var az=this;
return az.trigger(ay.type,{type:ay.type,item:ay.item});
},_focusHandler:function(ay){var aA=this,az=l(L.eventTarget(ay)).closest(o);
setTimeout(function(){aA._moveHover([],az);
if(az.children(".k-content")[0]){az.parent().closest(".k-item").removeClass(E);
}},200);
},_animations:function(ay){if(ay&&"animation" in ay&&!ay.animation){ay.animation={open:{effects:{}},close:{hide:true,effects:{}}};
}}});
C(S,{renderItem:function(aA){aA=C({menu:{},group:{}},aA);
var ay=al.empty,az=aA.item;
return al.item(C(aA,{image:az.imageUrl?al.image:ay,sprite:az.spriteCssClass?al.sprite:ay,itemWrapper:al.itemWrapper,renderContent:S.renderContent,arrow:az.items||az.content?al.arrow:ay,subGroup:S.renderGroup},ai));
},renderGroup:function(ay){return al.group(C({renderItems:function(aE){var aA="",aB=0,aC=aE.items,aD=aC?aC.length:0,az=C({length:aD},aE.group);
for(;
aB<aD;
aB++){aA+=S.renderItem(C(aE,{group:az,item:C({index:aB},aC[aB])}));
}return aA;
}},ay,ai));
},renderContent:function(ay){return al.content(C(ay,ai));
}});
var t=S.extend({init:function(ay,az){var aA=this;
S.fn.init.call(aA,ay,az);
aA.target=l(aA.options.target);
aA._popup();
aA._wire();
},options:{name:"ContextMenu",filter:null,showOn:"contextmenu",orientation:"vertical",alignToAnchor:false,target:"body"},events:[ac,r,m,u,aj],setOptions:function(ay){var az=this;
S.fn.setOptions.call(az,ay);
az.target.off(az.showOn+ab,az._showProxy);
if(az.userEvents){az.userEvents.destroy();
}az.target=l(az.options.target);
if(ay.orientation&&az.popup.wrapper[0]){az.popup.element.unwrap();
}az._wire();
S.fn.setOptions.call(this,ay);
},destroy:function(){var ay=this;
ay.target.off(ay.options.showOn+ab);
y.off(L.support.mousedown+ab,ay._closeProxy);
if(ay.userEvents){ay.userEvents.destroy();
}S.fn.destroy.call(ay);
},open:function(az,aA){var ay=this;
az=l(az)[0];
if(s(ay.element[0],l(az)[0])){S.fn.open.call(ay,az);
}else{if(ay._triggerEvent({item:ay.element,type:ac})===false){if(ay.popup.visible()&&ay.options.filter){ay.popup.close(true);
ay.popup.element.kendoStop(true);
}if(aA!==ar){ay.popup.wrapper.hide();
ay.popup.open(az,aA);
}else{ay.popup.options.anchor=(az?az:ay.popup.anchor)||ay.target;
ay.popup.element.kendoStop(true);
ay.popup.open();
}y.off(ay.popup.downEvent,ay.popup._mousedownProxy);
y.on(L.support.mousedown+ab,ay._closeProxy);
}}return ay;
},close:function(){var ay=this;
if(s(ay.element[0],l(arguments[0])[0])){S.fn.close.call(ay,arguments[0]);
}else{if(ay.popup.visible()){if(ay._triggerEvent({item:ay.element,type:r})===false){ay.popup.close();
y.off(L.support.mousedown+ab,ay._closeProxy);
ay.unbind(aj,ay._closeTimeoutProxy);
}}}},_showHandler:function(ay){var az=ay,aA,aC=this,aB=aC.options;
if(ay.event){az=ay.event;
az.pageX=ay.x.location;
az.pageY=ay.y.location;
}if(s(aC.element[0],ay.relatedTarget||ay.target)){return;
}aC._eventOrigin=az;
az.preventDefault();
az.stopImmediatePropagation();
aC.element.find("."+E).removeClass(E);
if(aB.filter&&L.support.matchesSelector.call(az.currentTarget,aB.filter)||!aB.filter){if(aB.alignToAnchor){aC.popup.options.anchor=az.currentTarget;
aC.open(az.currentTarget);
}else{aC.popup.options.anchor=az.currentTarget;
if(aC._targetChild){aA=aC.target.offset();
aC.open(az.pageX-aA.left,az.pageY-aA.top);
}else{aC.open(az.pageX,az.pageY);
}}}},_closeHandler:function(aA){var aE=this,aD=l(aA.relatedTarget||aA.target),aC=aD.closest(aE.target.selector)[0]==aE.target[0],ay=aD.closest(K).children(ag),az=s(aE.element[0],aD[0]);
aE._eventOrigin=aA;
var aB=aA.which!==3;
if(aE.popup.visible()&&(aB&&aC||!aC)&&(aE.options.closeOnClick&&!ay[0]&&az||!az)){if(az){this.unbind(aj,this._closeTimeoutProxy);
aE.bind(aj,aE._closeTimeoutProxy);
}else{aE.close();
}}},_wire:function(){var aA=this,ay=aA.options,az=aA.target;
aA._showProxy=ah(aA._showHandler,aA);
aA._closeProxy=ah(aA._closeHandler,aA);
aA._closeTimeoutProxy=ah(aA.close,aA);
if(az[0]){if(L.support.mobileOS&&ay.showOn=="contextmenu"){aA.userEvents=new L.UserEvents(az,{filter:ay.filter,allowSelection:false});
az.on(ay.showOn+ab,false);
aA.userEvents.bind("hold",aA._showProxy);
}else{if(ay.filter){az.on(ay.showOn+ab,ay.filter,aA._showProxy);
}else{az.on(ay.showOn+ab,aA._showProxy);
}}}},_triggerEvent:function(az){var aB=this,ay=l(aB.popup.options.anchor)[0],aA=aB._eventOrigin;
aB._eventOrigin=ar;
return aB.trigger(az.type,C({type:az.type,item:az.item||this.element[0],target:ay},aA?{event:aA}:{}));
},_popup:function(){var ay=this;
ay._triggerProxy=ah(ay._triggerEvent,ay);
ay.popup=ay.element.addClass("k-context-menu").kendoPopup({anchor:ay.target||"body",copyAnchorStyles:ay.options.copyAnchorStyles,collision:ay.options.popupCollision||"fit",animation:ay.options.animation,activate:ay._triggerProxy,deactivate:ay._triggerProxy}).data("kendoPopup");
ay._targetChild=s(ay.target[0],ay.popup.element[0]);
}});
aq.plugin(S);
aq.plugin(t);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
