(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.numerictextbox",["kendo.core","kendo.userevents"],l);
}(function(){var k={id:"numerictextbox",name:"NumericTextBox",category:"web",description:"The NumericTextBox widget can format and display numeric, percentage or currency textbox.",depends:["core","userevents"]};
(function(l,U){var D=window.kendo,q=D.caret,E=D.keys,T=D.ui,V=T.Widget,m=D._activeElement,v=D._extractFormat,J=D.parseFloat,K=D.support.placeholder,y=D.getCulture,O=D._round,r="change",t="disabled",N="readonly",B="k-input",Q="spin",G=".kendoNumericTextBox",S="touchend",F="mouseleave"+G,A="mouseenter"+G+" "+F,s="k-state-default",x="k-state-focused",z="k-state-hover",w="focus",L=".",P="k-state-selected",R="k-state-disabled",n="aria-disabled",o="aria-readonly",C=/^(-)?(\d*)$/,H=null,M=l.proxy,u=l.extend;
var I=V.extend({init:function(X,ab){var ad=this,Y=ab&&ab.step!==U,aa,Z,ac,ae,W;
V.fn.init.call(ad,X,ab);
ab=ad.options;
X=ad.element.on("focusout"+G,M(ad._focusout,ad)).attr("role","spinbutton");
ab.placeholder=ab.placeholder||X.attr("placeholder");
ad._initialOptions=u({},ab);
ad._reset();
ad._wrapper();
ad._arrows();
ad._input();
if(!D.support.mobileOS){ad._text.on(w+G,M(ad._click,ad));
}else{ad._text.on(S+G+" "+w+G,function(){ad._toggleText(false);
X.focus();
});
}aa=ad.min(X.attr("min"));
Z=ad.max(X.attr("max"));
ac=ad._parse(X.attr("step"));
if(ab.min===H&&aa!==H){ab.min=aa;
}if(ab.max===H&&Z!==H){ab.max=Z;
}if(!Y&&ac!==H){ab.step=ac;
}X.attr("aria-valuemin",ab.min).attr("aria-valuemax",ab.max);
ab.format=v(ab.format);
ae=ab.value;
ad.value(ae!==H?ae:X.val());
W=X.is("[disabled]")||l(ad.element).parents("fieldset").is(":disabled");
if(W){ad.enable(false);
}else{ad.readonly(X.is("[readonly]"));
}D.notify(ad);
},options:{name:"NumericTextBox",decimals:H,min:H,max:H,value:H,step:1,culture:"",format:"n",spinners:true,placeholder:"",upArrowText:"Increase value",downArrowText:"Decrease value"},events:[r,Q],_editable:function(Y){var ab=this,X=ab.element,W=Y.disable,Z=Y.readonly,aa=ab._text.add(X),ac=ab._inputWrapper.off(A);
ab._toggleText(true);
ab._upArrowEventHandler.unbind("press");
ab._downArrowEventHandler.unbind("press");
X.off("keydown"+G).off("keypress"+G).off("paste"+G);
if(!Z&&!W){ac.addClass(s).removeClass(R).on(A,ab._toggleHover);
aa.removeAttr(t).removeAttr(N).attr(n,false).attr(o,false);
ab._upArrowEventHandler.bind("press",function(ad){ad.preventDefault();
ab._spin(1);
ab._upArrow.addClass(P);
});
ab._downArrowEventHandler.bind("press",function(ad){ad.preventDefault();
ab._spin(-1);
ab._downArrow.addClass(P);
});
ab.element.on("keydown"+G,M(ab._keydown,ab)).on("keypress"+G,M(ab._keypress,ab)).on("paste"+G,M(ab._paste,ab));
}else{ac.addClass(W?R:s).removeClass(W?s:R);
aa.attr(t,W).attr(N,Z).attr(n,W).attr(o,Z);
}},readonly:function(W){this._editable({readonly:W===U?true:W,disable:false});
},enable:function(W){this._editable({readonly:false,disable:!(W=W===U?true:W)});
},destroy:function(){var W=this;
W.element.add(W._text).add(W._upArrow).add(W._downArrow).add(W._inputWrapper).off(G);
W._upArrowEventHandler.destroy();
W._downArrowEventHandler.destroy();
if(W._form){W._form.off("reset",W._resetHandler);
}V.fn.destroy.call(W);
},min:function(W){return this._option("min",W);
},max:function(W){return this._option("max",W);
},step:function(W){return this._option("step",W);
},value:function(Y){var X=this,W;
if(Y===U){return X._value;
}Y=X._parse(Y);
W=X._adjust(Y);
if(Y!==W){return;
}X._update(Y);
X._old=X._value;
},focus:function(){this._focusin();
},_adjust:function(aa){var Z=this,Y=Z.options,X=Y.min,W=Y.max;
if(aa===H){return aa;
}if(X!==H&&aa<X){aa=X;
}else{if(W!==H&&aa>W){aa=W;
}}return aa;
},_arrows:function(){var ab=this,X,W=function(){clearTimeout(ab._spinning);
X.removeClass(P);
},Z=ab.options,aa=Z.spinners,Y=ab.element;
X=Y.siblings(".k-icon");
if(!X[0]){X=l(p("n",Z.upArrowText)+p("s",Z.downArrowText)).insertAfter(Y);
X.wrapAll('<span class="k-select"/>');
}if(!aa){X.parent().toggle(aa);
ab._inputWrapper.addClass("k-expand-padding");
}ab._upArrow=X.eq(0);
ab._upArrowEventHandler=new D.UserEvents(ab._upArrow,{release:W});
ab._downArrow=X.eq(1);
ab._downArrowEventHandler=new D.UserEvents(ab._downArrow,{release:W});
},_blur:function(){var W=this;
W._toggleText(true);
W._change(W.element.val());
},_click:function(W){var X=this;
clearTimeout(X._focusing);
X._focusing=setTimeout(function(){var ae=W.target,ad=q(ae)[0],ag=ae.value.substring(0,ad),aa=X._format(X.options.format),ab=aa[","],af,ac,Z,Y=0;
if(ab){ac=new RegExp("\\"+ab,"g");
Z=new RegExp("([\\d\\"+ab+"]+)(\\"+aa[L]+")?(\\d+)?");
}if(Z){af=Z.exec(ag);
}if(af){Y=af[0].replace(ac,"").length;
if(ag.indexOf("(")!=-1&&X._value<0){Y++;
}}X._focusin();
q(X.element[0],Y);
});
},_change:function(X){var W=this;
W._update(X);
X=W._value;
if(W._old!=X){W._old=X;
if(!W._typing){W.element.trigger(r);
}W.trigger(r);
}W._typing=false;
},_culture:function(W){return W||y(this.options.culture);
},_focusin:function(){var W=this;
W._inputWrapper.addClass(x);
W._toggleText(false);
W.element[0].focus();
},_focusout:function(){var W=this;
clearTimeout(W._focusing);
W._inputWrapper.removeClass(x).removeClass(z);
W._blur();
},_format:function(X,W){var Y=this._culture(W).numberFormat;
X=X.toLowerCase();
if(X.indexOf("c")>-1){Y=Y.currency;
}else{if(X.indexOf("p")>-1){Y=Y.percent;
}}return Y;
},_input:function(){var ab=this,X="k-formatted-value",Z=ab.element.addClass(B).show()[0],W=Z.accessKey,ac=ab.wrapper,aa;
aa=ac.find(L+X);
if(!aa[0]){aa=l('<input type="text"/>').insertBefore(Z).addClass(X);
}try{Z.setAttribute("type","text");
}catch(Y){Z.type="text";
}aa[0].tabIndex=Z.tabIndex;
aa[0].style.cssText=Z.style.cssText;
aa[0].title=Z.title;
aa.prop("placeholder",ab.options.placeholder);
if(W){aa.attr("accesskey",W);
Z.accessKey="";
}ab._text=aa.addClass(Z.className);
},_keydown:function(W){var Y=this,X=W.keyCode;
Y._key=X;
if(X==E.DOWN){Y._step(-1);
}else{if(X==E.UP){Y._step(1);
}else{if(X==E.ENTER){Y._change(Y.element.val());
}else{Y._typing=true;
}}}},_keypress:function(X){if(X.which===0||X.metaKey||X.ctrlKey||X.keyCode===E.BACKSPACE||X.keyCode===E.ENTER){return;
}var ag=this;
var ab=ag.options.min;
var Y=ag.element;
var ad=q(Y);
var af=ad[0];
var ae=ad[1];
var W=String.fromCharCode(X.which);
var ac=ag._format(ag.options.format);
var Z=ag._key===E.NUMPAD_DOT;
var ah=Y.val();
var aa;
if(Z){W=ac[L];
}ah=ah.substring(0,af)+W+ah.substring(ae);
aa=ag._numericRegex(ac).test(ah);
if(aa&&Z){Y.val(ah);
q(Y,af+W.length);
X.preventDefault();
}else{if(ab!==null&&ab>=0&&ah.charAt(0)==="-"||!aa){X.preventDefault();
}}ag._key=0;
},_numericRegex:function(W){var Z=this;
var Y=W[L];
var X=Z.options.decimals;
if(Y===L){Y="\\"+Y;
}if(X===H){X=W.decimals;
}if(X===0){return C;
}if(Z._separator!==Y){Z._separator=Y;
Z._floatRegExp=new RegExp("^(-)?(((\\d+("+Y+"\\d*)?)|("+Y+"\\d*)))?$");
}return Z._floatRegExp;
},_paste:function(W){var Y=this,X=W.target,Z=X.value;
setTimeout(function(){if(Y._parse(X.value)===H){Y._update(Z);
}});
},_option:function(W,Z){var Y=this,X=Y.options;
if(Z===U){return X[W];
}Z=Y._parse(Z);
if(!Z&&W==="step"){return;
}X[W]=Z;
Y.element.attr("aria-value"+W,Z).attr(W,Z);
},_spin:function(W,Y){var X=this;
Y=Y||500;
clearTimeout(X._spinning);
X._spinning=setTimeout(function(){X._spin(W,50);
},Y);
X._step(W);
},_step:function(X){var Y=this,W=Y.element,Z=Y._parse(W.val())||0;
if(m()!=W[0]){Y._focusin();
}Z+=Y.options.step*X;
Y._update(Y._adjust(Z));
Y._typing=false;
Y.trigger(Q);
},_toggleHover:function(W){l(W.currentTarget).toggleClass(z,W.type==="mouseenter");
},_toggleText:function(X){var W=this;
W._text.toggle(X);
W.element.toggle(!X);
},_parse:function(X,W){return J(X,this._culture(W),this.options.format);
},_update:function(ad){var ac=this,ab=ac.options,Y=ab.format,X=ab.decimals,W=ac._culture(),aa=ac._format(Y,W),Z;
if(X===H){X=aa.decimals;
}ad=ac._parse(ad,W);
Z=ad!==H;
if(Z){ad=parseFloat(O(ad,X));
}ac._value=ad=ac._adjust(ad);
ac._placeholder(D.toString(ad,Y,W));
if(Z){ad=ad.toString();
if(ad.indexOf("e")!==-1){ad=O(+ad,X);
}ad=ad.replace(L,aa[L]);
}else{ad="";
}ac.element.val(ad).attr("aria-valuenow",ad);
},_placeholder:function(W){this._text.val(W);
if(!K&&!W){this._text.val(this.options.placeholder);
}},_wrapper:function(){var Y=this,X=Y.element,W=X[0],Z;
Z=X.parents(".k-numerictextbox");
if(!Z.is("span.k-numerictextbox")){Z=X.hide().wrap('<span class="k-numeric-wrap k-state-default" />').parent();
Z=Z.wrap("<span/>").parent();
}Z[0].style.cssText=W.style.cssText;
W.style.width="";
Y.wrapper=Z.addClass("k-widget k-numerictextbox").addClass(W.className).css("display","");
Y._inputWrapper=l(Z[0].firstChild);
},_reset:function(){var Z=this,W=Z.element,Y=W.attr("form"),X=Y?l("#"+Y):W.closest("form");
if(X[0]){Z._resetHandler=function(){setTimeout(function(){Z.value(W[0].value);
Z.max(Z._initialOptions.max);
Z.min(Z._initialOptions.min);
});
};
Z._form=X.on("reset",Z._resetHandler);
}}});
function p(W,X){return'<span unselectable="on" class="k-link"><span unselectable="on" class="k-icon k-i-arrow-'+W+'" title="'+X+'">'+X+"</span></span>";
}T.plugin(I);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
