(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("pdf/core",["kendo.core","util/main"],l);
}(function(){(function(aw,W,at){var H=aw.kendo;
var A=!!aw.Uint8Array;
var T="\n";
var ar=0;
var l=function(){var az="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
return{decode:function(aL){var aI=aL.replace(/[^A-Za-z0-9\+\/\=]/g,""),aH=0,aJ=aI.length,aK=[];
while(aH<aJ){var aD=az.indexOf(aI.charAt(aH++));
var aE=az.indexOf(aI.charAt(aH++));
var aF=az.indexOf(aI.charAt(aH++));
var aG=az.indexOf(aI.charAt(aH++));
var aA=aD<<2|aE>>>4;
var aB=(aE&15)<<4|aF>>>2;
var aC=(aF&3)<<6|aG;
aK.push(aA);
if(aF!=64){aK.push(aB);
}if(aG!=64){aK.push(aC);
}}return aK;
},encode:function(aA){var aI=0,aJ=aA.length;
var aK="";
while(aI<aJ){var aB=aA[aI++];
var aC=aA[aI++];
var aD=aA[aI++];
var aE=aB>>>2;
var aF=(aB&3)<<4|aC>>>4;
var aG=(aC&15)<<2|aD>>>6;
var aH=aD&63;
if(aI-aJ==2){aG=aH=64;
}else{if(aI-aJ==1){aH=64;
}}aK+=az.charAt(aE)+az.charAt(aF)+az.charAt(aG)+az.charAt(aH);
}return aK;
}};
}();
var V={a0:[2383.94,3370.39],a1:[1683.78,2383.94],a2:[1190.55,1683.78],a3:[841.89,1190.55],a4:[595.28,841.89],a5:[419.53,595.28],a6:[297.64,419.53],a7:[209.76,297.64],a8:[147.4,209.76],a9:[104.88,147.4],a10:[73.7,104.88],b0:[2834.65,4008.19],b1:[2004.09,2834.65],b2:[1417.32,2004.09],b3:[1000.63,1417.32],b4:[708.66,1000.63],b5:[498.9,708.66],b6:[354.33,498.9],b7:[249.45,354.33],b8:[175.75,249.45],b9:[124.72,175.75],b10:[87.87000000000001,124.72],c0:[2599.37,3676.54],c1:[1836.85,2599.37],c2:[1298.27,1836.85],c3:[918.43,1298.27],c4:[649.13,918.43],c5:[459.21,649.13],c6:[323.15,459.21],c7:[229.61,323.15],c8:[161.57,229.61],c9:[113.39,161.57],c10:[79.37000000000001,113.39],executive:[521.86,756],folio:[612,936],legal:[612,1008],letter:[612,792],tabloid:[792,1224]};
function P(){var az=0,aB=m();
function aA(){for(var aC=0;
aC<arguments.length;
++aC){var aE=arguments[aC];
if(aE===at){throw new Error("Cannot output undefined to PDF");
}else{if(aE instanceof ao){aE.beforeRender(aA);
aE.render(aA);
}else{if(E(aE)){ap(aE,aA);
}else{if(F(aE)){aq(aE,aA);
}else{if(typeof aE=="number"){if(isNaN(aE)){throw new Error("Cannot output NaN to PDF");
}var aD=aE.toFixed(7);
if(aD.indexOf(".")>=0){aD=aD.replace(/\.?0+$/,"");
}if(aD=="-0"){aD="0";
}aB.writeString(aD);
}else{if(/string|boolean/.test(typeof aE)){aB.writeString(aE+"");
}else{if(typeof aE.get=="function"){aB.write(aE.get());
}else{if(typeof aE=="object"){if(!aE){aB.writeString("null");
}else{aA(new Z(aE));
}}}}}}}}}}}aA.writeData=function(aC){aB.write(aC);
};
aA.withIndent=function(aC){++az;
aC(aA);
--az;
};
aA.indent=function(){aA(T,U("",az*2,"  "));
aA.apply(null,arguments);
};
aA.offset=function(){return aB.offset();
};
aA.toString=function(){throw new Error("FIX CALLER");
};
aA.get=function(){return aB.get();
};
aA.stream=function(){return aB;
};
return aA;
}function ax(aC,aA){var az=aC.beforeRender;
var aB=aC.render;
aC.beforeRender=function(){};
aC.render=function(aD){aD(aA," 0 R");
};
aC.renderFull=function(aD){aC._offset=aD.offset();
aD(aA," 0 obj ");
az.call(aC,aD);
aB.call(aC,aD);
aD(" endobj");
};
}function z(az){if(typeof az!="function"){var aB=az;
az=function(aE,aD){return aE in aB?aB[aE]:aD;
};
}var aC=az("paperSize",V.a4);
if(!aC){return{};
}if(typeof aC=="string"){aC=V[aC.toLowerCase()];
if(aC==null){throw new Error("Unknown paper size");
}}aC[0]=au(aC[0]);
aC[1]=au(aC[1]);
if(az("landscape",false)){aC=[Math.max(aC[0],aC[1]),Math.min(aC[0],aC[1])];
}var aA=az("margin");
if(aA){if(typeof aA=="string"||typeof aA=="number"){aA=au(aA,0);
aA={left:aA,top:aA,right:aA,bottom:aA};
}else{aA={left:au(aA.left,0),top:au(aA.top,0),right:au(aA.right,0),bottom:au(aA.bottom,0)};
}if(az("addMargin")){aC[0]+=aA.left+aA.right;
aC[1]+=aA.top+aA.bottom;
}}return{paperSize:aC,margin:aA};
}function aa(aD){var aG=this;
var aE=P();
var aB=0;
var aC=[];
function aA(aI,aH){return aD&&aD[aI]!=null?aD[aI]:aH;
}aG.getOption=aA;
aG.attach=function(aH){if(aC.indexOf(aH)<0){ax(aH,++aB);
aC.push(aH);
}return aH;
};
aG.pages=[];
aG.FONTS={};
aG.IMAGES={};
aG.GRAD_COL_FUNCTIONS={};
aG.GRAD_OPC_FUNCTIONS={};
aG.GRAD_COL={};
aG.GRAD_OPC={};
var az=aG.attach(new Y());
var aF=aG.attach(new ah());
az.setPages(aF);
aG.addPage=function(aL){var aN=z(function(aR,aQ){return aL&&aL[aR]!=null?aL[aR]:aQ;
});
var aO=aN.paperSize;
var aK=aN.margin;
var aJ=aO[0];
var aI=aO[1];
if(aK){aJ-=aK.left+aK.right;
aI-=aK.top+aK.bottom;
}var aH=new ak(P(),null,true);
var aP={Contents:aG.attach(aH),Parent:aF,MediaBox:[0,0,aO[0],aO[1]]};
var aM=new ag(aG,aP);
aM._content=aH;
aF.addPage(aG.attach(aM));
aM.transform(1,0,0,-1,0,aO[1]);
if(aK){aM.translate(aK.left,aK.top);
aM.rect(0,0,aJ,aI);
aM.clip();
}aG.pages.push(aM);
return aM;
};
aG.render=function(){var aH;
aE("%PDF-1.4",T,"%базон",T,T);
for(aH=0;
aH<aC.length;
++aH){aC[aH].renderFull(aE);
aE(T,T);
}var aI=aE.offset();
aE("xref",T,0," ",aC.length+1,T);
aE("0000000000 65535 f ",T);
for(aH=0;
aH<aC.length;
++aH){aE(ay(aC[aH]._offset,10)," 00000 n ",T);
}aE(T);
aE("trailer",T);
aE(new Z({Size:aC.length+1,Root:az,Info:new Z({Producer:new al(aA("producer","Kendo UI PDF Generator v."+H.version)),Title:new al(aA("title","")),Author:new al(aA("author","")),Subject:new al(aA("subject","")),Keywords:new al(aA("keywords","")),Creator:new al(aA("creator","Kendo UI PDF Generator v."+H.version)),CreationDate:aA("date",new Date())})}),T,T);
aE("startxref",T,aI,T);
aE("%%EOF",T);
return aE.stream().offset(0);
};
}var v={"Times-Roman":true,"Times-Bold":true,"Times-Italic":true,"Times-BoldItalic":true,Helvetica:true,"Helvetica-Bold":true,"Helvetica-Oblique":true,"Helvetica-BoldOblique":true,Courier:true,"Courier-Bold":true,"Courier-Oblique":true,"Courier-BoldOblique":true,Symbol:true,ZapfDingbats:true};
function I(aC,az){function aA(){if(aw.console){if(aw.console.error){aw.console.error("Cannot load URL: %s",aC);
}else{aw.console.log("Cannot load URL: %s",aC);
}}az(null);
}var aB=new XMLHttpRequest();
aB.open("GET",aC,true);
if(A){aB.responseType="arraybuffer";
}aB.onload=function(){if(aB.status==200||aB.status==304){if(A){az(new Uint8Array(aB.response));
}else{az(new VBArray(aB.responseBody).toArray());
}}else{aA();
}};
aB.onerror=aA;
aB.send(null);
}function J(aB,az){var aA=v[aB];
if(aA){az(aA);
}else{I(aB,function(aC){if(aC==null){throw new Error("Cannot load font from "+aB);
}else{var aD=new H.pdf.TTFFont(aC);
v[aB]=aD;
az(aD);
}});
}}var C={};
function L(aG,aE){var aF=C[aG],aD,aC;
if(aF){aE(aF);
}else{aF=new Image();
if(!/^data:/i.test(aG)){aF.crossOrigin="Anonymous";
}if(A&&!/^data:/i.test(aG)){var aH=new XMLHttpRequest();
aH.onload=function(){aC=aH.response;
aD=URL.createObjectURL(aC);
az(aD);
};
aH.onerror=aA;
aH.open("GET",aG,true);
aH.responseType="blob";
aH.send();
}else{az(aG);
}}function az(aI){aF.src=aI;
if(aF.complete&&!H.support.browser.msie){aB();
}else{aF.onload=aB;
aF.onerror=aA;
}}function aA(){aE(C[aG]="TAINTED");
}function aB(){if(aC&&/^image\/jpe?g$/i.test(aC.type)){var aS=new FileReader();
aS.onload=function(){aF=new ad(aF.width,aF.height,m(new Uint8Array(this.result)));
URL.revokeObjectURL(aD);
aE(C[aG]=aF);
};
aS.readAsArrayBuffer(aC);
return;
}var aK=document.createElement("canvas");
aK.width=aF.width;
aK.height=aF.height;
var aL=aK.getContext("2d");
aL.drawImage(aF,0,0);
var aQ;
try{aQ=aL.getImageData(0,0,aF.width,aF.height);
}catch(aN){return aA();
}finally{if(aD){URL.revokeObjectURL(aD);
}}var aO=false,aT=m(),aJ=m();
var aR=aQ.data;
var aP=0;
while(aP<aR.length){aT.writeByte(aR[aP++]);
aT.writeByte(aR[aP++]);
aT.writeByte(aR[aP++]);
var aI=aR[aP++];
if(aI<255){aO=true;
}aJ.writeByte(aI);
}if(aO){aF=new ai(aF.width,aF.height,aT,aJ);
}else{var aM=aK.toDataURL("image/jpeg");
aM=aM.substr(aM.indexOf(";base64,")+8);
var aU=m();
aU.writeBase64(aM);
aU.offset(0);
aF=new ad(aF.width,aF.height,aU);
}aE(C[aG]=aF);
}}function Q(az){return function(aD,aA){var aC=aD.length,aB=aC;
if(aC===0){return aA();
}while(aB-->0){az(aD[aB],function(){if(--aC===0){aA();
}});
}};
}var K=Q(J);
var M=Q(L);
aa.prototype={loadFonts:K,loadImages:M,getFont:function(aA){var az=this.FONTS[aA];
if(!az){az=v[aA];
if(!az){throw new Error("Font "+aA+" has not been loaded");
}if(az===true){az=this.attach(new aj(aA));
}else{az=this.attach(new ab(this,az));
}this.FONTS[aA]=az;
}return az;
},getImage:function(aA){var az=this.IMAGES[aA];
if(!az){az=C[aA];
if(!az){throw new Error("Image "+aA+" has not been loaded");
}if(az==="TAINTED"){return null;
}az=this.IMAGES[aA]=this.attach(az.asStream(this));
}return az;
},getOpacityGS:function(aD,aA){var aC=W(aD).toFixed(3);
aD=W(aC);
aC+=aA?"S":"F";
var az=this._opacityGSCache||(this._opacityGSCache={});
var aB=az[aC];
if(!aB){var aE={Type:k("ExtGState")};
if(aA){aE.CA=aD;
}else{aE.ca=aD;
}aB=this.attach(new Z(aE));
aB._resourceName=k("GS"+ ++ar);
az[aC]=aB;
}return aB;
},dict:function(az){return new Z(az);
},name:function(az){return k(az);
},stream:function(aA,az){return new ak(az,aA);
}};
function U(aB,aA,az){while(aB.length<aA){aB=az+aB;
}return aB;
}function ay(aA,az){return U(aA+"",az,"0");
}function B(aA,az){return Object.prototype.hasOwnProperty.call(aA,az);
}var E=Array.isArray||function(az){return az instanceof Array;
};
function F(az){return az instanceof Date;
}function ap(az,aA){aA("[");
if(az.length>0){aA.withIndent(function(){for(var aB=0;
aB<az.length;
++aB){if(aB>0&&aB%8===0){aA.indent(az[aB]);
}else{aA(" ",az[aB]);
}}});
}aA(" ]");
}function aq(az,aA){aA("(D:",ay(az.getUTCFullYear(),4),ay(az.getUTCMonth()+1,2),ay(az.getUTCDate(),2),ay(az.getUTCHours(),2),ay(az.getUTCMinutes(),2),ay(az.getUTCSeconds(),2),"Z)");
}function R(az){return az*(72/25.4);
}function s(az){return R(az*10);
}function D(az){return az*72;
}function au(aC,az){if(typeof aC=="number"){return aC;
}if(typeof aC=="string"){var aA;
aA=/^\s*([0-9.]+)\s*(mm|cm|in|pt)\s*$/.exec(aC);
if(aA){var aB=W(aA[1]);
if(!isNaN(aB)){if(aA[2]=="pt"){return aB;
}return{mm:R,cm:s,"in":D}[aA[2]](aB);
}}}if(az!=null){return az;
}throw new Error("Can't parse unit: "+aC);
}function ao(){}ao.prototype.beforeRender=function(){};
function t(aA,aC,az){if(!az){az=ao;
}aA.prototype=new az();
for(var aB in aC){if(B(aC,aB)){aA.prototype[aB]=aC[aB];
}}return aA;
}var al=t(function al(az){this.value=az;
},{render:function(aB){var aC="",az=this.escape();
for(var aA=0;
aA<az.length;
++aA){aC+=String.fromCharCode(az.charCodeAt(aA)&255);
}aB("(",aC,")");
},escape:function(){return this.value.replace(/([\(\)\\])/g,"\\$1");
},toString:function(){return this.value;
}});
var ac=t(function ac(az){this.value=az;
},{render:function(aA){aA("<");
for(var az=0;
az<this.value.length;
++az){aA(ay(this.value.charCodeAt(az).toString(16),4));
}aA(">");
}},al);
var ae=t(function ae(az){this.name=az;
},{render:function(az){az("/"+this.escape());
},escape:function(){return this.name.replace(/[^\x21-\x7E]/g,function(az){return"#"+ay(az.charCodeAt(0).toString(16),2);
});
},toString:function(){return this.name;
}});
var af={};
ae.get=k;
function k(az){if(B(af,az)){return af[az];
}return af[az]=new ae(az);
}var Z=t(function Z(az){this.props=az;
},{render:function(aA){var aB=this.props,az=true;
aA("<<");
aA.withIndent(function(){for(var aC in aB){if(B(aB,aC)&&!/^_/.test(aC)){az=false;
aA.indent(k(aC)," ",aB[aC]);
}}});
if(!az){aA.indent();
}aA(">>");
}});
var ak=t(function ak(aA,aB,az){if(typeof aA=="string"){var aC=m();
aC.write(aA);
aA=aC;
}this.data=aA;
this.props=aB||{};
this.compress=az;
},{render:function(aA){var az=this.data.get(),aB=this.props;
if(this.compress&&aw.pako&&typeof aw.pako.deflate=="function"){if(!aB.Filter){aB.Filter=[];
}else{if(!(aB.Filter instanceof Array)){aB.Filter=[aB.Filter];
}}aB.Filter.unshift(k("FlateDecode"));
az=aw.pako.deflate(az);
}aB.Length=az.length;
aA(new Z(aB)," stream",T);
aA.writeData(az);
aA(T,"endstream");
}});
var Y=t(function Y(az){az=this.props=az||{};
az.Type=k("Catalog");
},{setPages:function(az){this.props.Pages=az;
}},Z);
var ah=t(function ah(){this.props={Type:k("Pages"),Kids:[],Count:0};
},{addPage:function(az){this.props.Kids.push(az);
this.props.Count++;
}},Z);
function ad(aB,aA,az){this.asStream=function(){var aC=new ak(az,{Type:k("XObject"),Subtype:k("Image"),Width:aB,Height:aA,BitsPerComponent:8,ColorSpace:k("DeviceRGB"),Filter:k("DCTDecode")});
aC._resourceName=k("I"+ ++ar);
return aC;
};
}function ai(aC,aA,aB,az){this.asStream=function(aE){var aD=new ak(az,{Type:k("XObject"),Subtype:k("Image"),Width:aC,Height:aA,BitsPerComponent:8,ColorSpace:k("DeviceGray")},true);
var aF=new ak(aB,{Type:k("XObject"),Subtype:k("Image"),Width:aC,Height:aA,BitsPerComponent:8,ColorSpace:k("DeviceRGB"),SMask:aE.attach(aD)},true);
aF._resourceName=k("I"+ ++ar);
return aF;
};
}var aj=t(function aj(az){this.props={Type:k("Font"),Subtype:k("Type1"),BaseFont:k(az)};
this._resourceName=k("F"+ ++ar);
},{encodeText:function(az){return new al(az+"");
}},Z);
var ab=t(function ab(aB,az,aC){aC=this.props=aC||{};
aC.Type=k("Font");
aC.Subtype=k("Type0");
aC.Encoding=k("Identity-H");
this._pdf=aB;
this._font=az;
this._sub=az.makeSubset();
this._resourceName=k("F"+ ++ar);
var aA=az.head;
this.name=az.psName;
var aD=this.scale=az.scale;
this.bbox=[aA.xMin*aD,aA.yMin*aD,aA.xMax*aD,aA.yMax*aD];
this.italicAngle=az.post.italicAngle;
this.ascent=az.ascent*aD;
this.descent=az.descent*aD;
this.lineGap=az.lineGap*aD;
this.capHeight=az.os2.capHeight||this.ascent;
this.xHeight=az.os2.xHeight||0;
this.stemV=0;
this.familyClass=(az.os2.familyClass||0)>>8;
this.isSerif=this.familyClass>=1&&this.familyClass<=7;
this.isScript=this.familyClass==10;
this.flags=(az.post.isFixedPitch?1:0)|(this.isSerif?1<<1:0)|(this.isScript?1<<3:0)|(this.italicAngle!==0?1<<6:0)|1<<5;
},{encodeText:function(az){return new ac(this._sub.encodeText(az+""));
},getTextWidth:function(aA,aD){var aE=0,az=this._font.cmap.codeMap;
for(var aC=0;
aC<aD.length;
++aC){var aB=az[aD.charCodeAt(aC)];
aE+=this._font.widthOfGlyph(aB||0);
}return aE*aA/1000;
},beforeRender:function(){var aJ=this;
var aK=aJ._sub;
var aB=aK.render();
var aG=new ak(m(aB),{Length1:aB.length},true);
var aD=aJ._pdf.attach(new Z({Type:k("FontDescriptor"),FontName:k(aJ._sub.psName),FontBBox:aJ.bbox,Flags:aJ.flags,StemV:aJ.stemV,ItalicAngle:aJ.italicAngle,Ascent:aJ.ascent,Descent:aJ.descent,CapHeight:aJ.capHeight,XHeight:aJ.xHeight,FontFile2:aJ._pdf.attach(aG)}));
var aA=aK.ncid2ogid;
var aF=aK.firstChar;
var aH=aK.lastChar;
var az=[];
(function aI(aP,aN){if(aP<=aH){var aO=aA[aP];
if(aO==null){aI(aP+1);
}else{if(!aN){az.push(aP,aN=[]);
}aN.push(aJ._font.widthOfGlyph(aO));
aI(aP+1,aN);
}}}(aF));
var aC=new Z({Type:k("Font"),Subtype:k("CIDFontType2"),BaseFont:k(aJ._sub.psName),CIDSystemInfo:new Z({Registry:new al("Adobe"),Ordering:new al("Identity"),Supplement:0}),FontDescriptor:aD,FirstChar:aF,LastChar:aH,DW:Math.round(aJ._font.widthOfGlyph(0)),W:az,CIDToGIDMap:aJ._pdf.attach(aJ._makeCidToGidMap())});
var aE=aJ.props;
aE.BaseFont=k(aJ._sub.psName);
aE.DescendantFonts=[aJ._pdf.attach(aC)];
var aL=new am(aF,aH,aK.subset);
var aM=new ak(P(),null,true);
aM.data(aL);
aE.ToUnicode=aJ._pdf.attach(aM);
},_makeCidToGidMap:function(){return new ak(m(this._sub.cidToGidMap()),null,true);
}},Z);
var am=t(function an(az,aA,aB){this.firstChar=az;
this.lastChar=aA;
this.map=aB;
},{render:function(az){az.indent("/CIDInit /ProcSet findresource begin");
az.indent("12 dict begin");
az.indent("begincmap");
az.indent("/CIDSystemInfo <<");
az.indent("  /Registry (Adobe)");
az.indent("  /Ordering (UCS)");
az.indent("  /Supplement 0");
az.indent(">> def");
az.indent("/CMapName /Adobe-Identity-UCS def");
az.indent("/CMapType 2 def");
az.indent("1 begincodespacerange");
az.indent("  <0000><ffff>");
az.indent("endcodespacerange");
var aA=this;
az.indent(aA.lastChar-aA.firstChar+1," beginbfchar");
az.withIndent(function(){for(var aB=aA.firstChar;
aB<=aA.lastChar;
++aB){var aE=aA.map[aB];
var aD=H.util.ucs2encode([aE]);
az.indent("<",ay(aB.toString(16),4),">","<");
for(var aC=0;
aC<aD.length;
++aC){az(ay(aD.charCodeAt(aC).toString(16),4));
}az(">");
}});
az.indent("endbfchar");
az.indent("endcmap");
az.indent("CMapName currentdict /CMap defineresource pop");
az.indent("end");
az.indent("end");
}});
function O(az){return az.map(function(aA){return E(aA)?O(aA):typeof aA=="number"?(Math.round(aA*1000)/1000).toFixed(3):aA;
}).join(" ");
}function o(aF,aG,aC,az,aH,aD,aA){var aE=O([aG,aC,az,aH,aD,aA]);
var aB=aF.GRAD_COL_FUNCTIONS[aE];
if(!aB){aB=aF.GRAD_COL_FUNCTIONS[aE]=aF.attach(new Z({FunctionType:2,Domain:[0,1],Range:[0,1,0,1,0,1],N:1,C0:[aG,aC,az],C1:[aH,aD,aA]}));
}return aB;
}function r(aD,az,aA){var aC=O([az,aA]);
var aB=aD.GRAD_OPC_FUNCTIONS[aC];
if(!aB){aB=aD.GRAD_OPC_FUNCTIONS[aC]=aD.attach(new Z({FunctionType:2,Domain:[0,1],Range:[0,1],N:1,C0:[az],C1:[aA]}));
}return aB;
}function N(aI,aL){var aE=false;
var aH=[];
var aA=[];
var aG=[];
var aD=[];
var aF,aJ,aB,aK,aC;
for(aF=1;
aF<aL.length;
++aF){aJ=aL[aF-1];
aB=aL[aF];
aK=aJ.color;
aC=aB.color;
aA.push(o(aI,aK.r,aK.g,aK.b,aC.r,aC.g,aC.b));
if(aK.a<1||aC.a<1){aE=true;
}aG.push(aB.offset);
aD.push(0,1);
}if(aE){for(aF=1;
aF<aL.length;
++aF){aJ=aL[aF-1];
aB=aL[aF];
aK=aJ.color;
aC=aB.color;
aH.push(r(aI,aK.a,aC.a));
}}aG.pop();
return{hasAlpha:aE,colors:az(aA),opacities:aE?az(aH):null};
function az(aM){if(aM.length==1){return aM[0];
}return{FunctionType:3,Functions:aM,Domain:[0,1],Bounds:aG,Encode:aD};
}}function n(aF,aE,aH,aB,aC,aA){var aG,aD;
if(!aA){var az=[aE].concat(aB);
aH.forEach(function(aI){az.push(aI.offset,aI.color.r,aI.color.g,aI.color.b);
});
aD=O(az);
aG=aF.GRAD_COL[aD];
}if(!aG){aG=new Z({Type:k("Shading"),ShadingType:aE?3:2,ColorSpace:k("DeviceRGB"),Coords:aB,Domain:[0,1],Function:aC,Extend:[true,true]});
aF.attach(aG);
aG._resourceName="S"+ ++ar;
if(aD){aF.GRAD_COL[aD]=aG;
}}return aG;
}function q(aG,aE,aH,aB,aC,aA){var aF,aD;
if(!aA){var az=[aE].concat(aB);
aH.forEach(function(aI){az.push(aI.offset,aI.color.a);
});
aD=O(az);
aF=aG.GRAD_OPC[aD];
}if(!aF){aF=new Z({Type:k("ExtGState"),AIS:false,CA:1,ca:1,SMask:{Type:k("Mask"),S:k("Luminosity"),G:aG.attach(new ak("/a0 gs /s0 sh",{Type:k("XObject"),Subtype:k("Form"),FormType:1,BBox:aA?[aA.left,aA.top+aA.height,aA.left+aA.width,aA.top]:[0,1,1,0],Group:{Type:k("Group"),S:k("Transparency"),CS:k("DeviceGray"),I:true},Resources:{ExtGState:{a0:{CA:1,ca:1}},Shading:{s0:{ColorSpace:k("DeviceGray"),Coords:aB,Domain:[0,1],ShadingType:aE?3:2,Function:aC,Extend:[true,true]}}}}))}});
aG.attach(aF);
aF._resourceName="O"+ ++ar;
if(aD){aG.GRAD_OPC[aD]=aF;
}}return aF;
}function p(aF,aC,az){var aD=aC.type=="radial";
var aB=N(aF,aC.stops);
var aA=aD?[aC.start.x,aC.start.y,aC.start.r,aC.end.x,aC.end.y,aC.end.r]:[aC.start.x,aC.start.y,aC.end.x,aC.end.y];
var aG=n(aF,aD,aC.stops,aA,aB.colors,aC.userSpace&&az);
var aE=aB.hasAlpha?q(aF,aD,aC.stops,aA,aB.opacities,aC.userSpace&&az):null;
return{hasAlpha:aB.hasAlpha,shading:aG,opacity:aE};
}var ag=t(function ag(az,aA){this._pdf=az;
this._rcount=0;
this._textMode=false;
this._fontResources={};
this._gsResources={};
this._xResources={};
this._patResources={};
this._shResources={};
this._opacity=1;
this._matrix=[1,0,0,1,0,0];
this._annotations=[];
this._font=null;
this._fontSize=null;
this._contextStack=[];
aA=this.props=aA||{};
aA.Type=k("Page");
aA.ProcSet=[k("PDF"),k("Text"),k("ImageB"),k("ImageC"),k("ImageI")];
aA.Resources=new Z({Font:new Z(this._fontResources),ExtGState:new Z(this._gsResources),XObject:new Z(this._xResources),Pattern:new Z(this._patResources),Shading:new Z(this._shResources)});
aA.Annots=this._annotations;
},{_out:function(){this._content.data.apply(null,arguments);
},transform:function(az,aA,aB,aC,aD,aE){if(!G(arguments)){this._matrix=S(arguments,this._matrix);
this._out(az," ",aA," ",aB," ",aC," ",aD," ",aE," cm");
this._out(T);
}},translate:function(az,aA){this.transform(1,0,0,1,az,aA);
},scale:function(az,aA){this.transform(az,0,0,aA,0,0);
},rotate:function(az){var aA=Math.cos(az),aB=Math.sin(az);
this.transform(aA,aB,-aB,aA,0,0);
},beginText:function(){this._textMode=true;
this._out("BT",T);
},endText:function(){this._textMode=false;
this._out("ET",T);
},_requireTextMode:function(){if(!this._textMode){throw new Error("Text mode required; call page.beginText() first");
}},_requireFont:function(){if(!this._font){throw new Error("No font selected; call page.setFont() first");
}},setFont:function(az,aA){this._requireTextMode();
if(az==null){az=this._font;
}else{if(!(az instanceof ab)){az=this._pdf.getFont(az);
}}if(aA==null){aA=this._fontSize;
}this._fontResources[az._resourceName]=az;
this._font=az;
this._fontSize=aA;
this._out(az._resourceName," ",aA," Tf",T);
},setTextLeading:function(az){this._requireTextMode();
this._out(az," TL",T);
},setTextRenderingMode:function(az){this._requireTextMode();
this._out(az," Tr",T);
},showText:function(aC,aA){this._requireFont();
if(aC.length>1&&aA&&this._font instanceof ab){var az=this._font.getTextWidth(this._fontSize,aC);
var aB=aA/az*100;
this._out(aB," Tz ");
}this._out(this._font.encodeText(aC)," Tj",T);
},showTextNL:function(az){this._requireFont();
this._out(this._font.encodeText(az)," '",T);
},addLink:function(aC,az){var aA=this._toPage({x:az.left,y:az.bottom});
var aB=this._toPage({x:az.right,y:az.top});
this._annotations.push(new Z({Type:k("Annot"),Subtype:k("Link"),Rect:[aA.x,aA.y,aB.x,aB.y],Border:[0,0,0],A:new Z({Type:k("Action"),S:k("URI"),URI:new al(aC)})}));
},setStrokeColor:function(aB,aA,az){this._out(aB," ",aA," ",az," RG",T);
},setOpacity:function(az){this.setFillOpacity(az);
this.setStrokeOpacity(az);
this._opacity*=az;
},setStrokeOpacity:function(aA){if(aA<1){var az=this._pdf.getOpacityGS(this._opacity*aA,true);
this._gsResources[az._resourceName]=az;
this._out(az._resourceName," gs",T);
}},setFillColor:function(aB,aA,az){this._out(aB," ",aA," ",az," rg",T);
},setFillOpacity:function(aA){if(aA<1){var az=this._pdf.getOpacityGS(this._opacity*aA,false);
this._gsResources[az._resourceName]=az;
this._out(az._resourceName," gs",T);
}},gradient:function(aB,az){this.save();
this.rect(az.left,az.top,az.width,az.height);
this.clip();
if(!aB.userSpace){this.transform(az.width,0,0,az.height,az.left,az.top);
}var aA=p(this._pdf,aB,az);
var aD=aA.shading._resourceName,aC;
this._shResources[aD]=aA.shading;
if(aA.hasAlpha){aC=aA.opacity._resourceName;
this._gsResources[aC]=aA.opacity;
this._out("/"+aC+" gs ");
}this._out("/"+aD+" sh",T);
this.restore();
},setDashPattern:function(az,aA){this._out(az," ",aA," d",T);
},setLineWidth:function(az){this._out(az," w",T);
},setLineCap:function(az){this._out(az," J",T);
},setLineJoin:function(az){this._out(az," j",T);
},setMitterLimit:function(az){this._out(az," M",T);
},save:function(){this._contextStack.push(this._context());
this._out("q",T);
},restore:function(){this._out("Q",T);
this._context(this._contextStack.pop());
},moveTo:function(az,aA){this._out(az," ",aA," m",T);
},lineTo:function(az,aA){this._out(az," ",aA," l",T);
},bezier:function(az,aC,aA,aD,aB,aE){this._out(az," ",aC," ",aA," ",aD," ",aB," ",aE," c",T);
},bezier1:function(az,aB,aA,aC){this._out(az," ",aB," ",aA," ",aC," y",T);
},bezier2:function(az,aB,aA,aC){this._out(az," ",aB," ",aA," ",aC," v",T);
},close:function(){this._out("h",T);
},rect:function(aB,aC,aA,az){this._out(aB," ",aC," ",aA," ",az," re",T);
},ellipse:function(aE,aF,aC,aD){function az(aG){return aE+aG;
}function aA(aG){return aF+aG;
}var aB=0.5522847498307936;
this.moveTo(az(0),aA(aD));
this.bezier(az(aC*aB),aA(aD),az(aC),aA(aD*aB),az(aC),aA(0));
this.bezier(az(aC),aA(-aD*aB),az(aC*aB),aA(-aD),az(0),aA(-aD));
this.bezier(az(-aC*aB),aA(-aD),az(-aC),aA(-aD*aB),az(-aC),aA(0));
this.bezier(az(-aC),aA(aD*aB),az(-aC*aB),aA(aD),az(0),aA(aD));
},circle:function(aA,aB,az){this.ellipse(aA,aB,az,az);
},stroke:function(){this._out("S",T);
},nop:function(){this._out("n",T);
},clip:function(){this._out("W n",T);
},clipStroke:function(){this._out("W S",T);
},closeStroke:function(){this._out("s",T);
},fill:function(){this._out("f",T);
},fillStroke:function(){this._out("B",T);
},drawImage:function(aA){var az=this._pdf.getImage(aA);
if(az){this._xResources[az._resourceName]=az;
this._out(az._resourceName," Do",T);
}},comment:function(aA){var az=this;
aA.split(/\r?\n/g).forEach(function(aB){az._out("% ",aB,T);
});
},_context:function(az){if(az!=null){this._opacity=az.opacity;
this._matrix=az.matrix;
}else{return{opacity:this._opacity,matrix:this._matrix};
}},_toPage:function(aG){var aF=this._matrix;
var az=aF[0],aA=aF[1],aB=aF[2],aC=aF[3],aD=aF[4],aE=aF[5];
return{x:az*aG.x+aB*aG.y+aD,y:aA*aG.x+aC*aG.y+aE};
}},Z);
function m(az){var aE=0,aD=0;
if(az==null){az=A?new Uint8Array(256):[];
}else{aD=az.length;
}var aA=A?function(a0){if(a0>=az.length){var a1=new Uint8Array(Math.max(a0+256,az.length*2));
a1.set(az,0);
az=a1;
}}:function(){};
var aC=A?function(){return new Uint8Array(az.buffer,0,aD);
}:function(){return az;
};
var aR=A?function(a0){if(typeof a0=="string"){return aZ(a0);
}var a1=a0.length;
aA(aE+a1);
az.set(a0,aE);
aE+=a1;
if(aE>aD){aD=aE;
}}:function(a0){if(typeof a0=="string"){return aZ(a0);
}for(var a1=0;
a1<a0.length;
++a1){aS(a0[a1]);
}};
var aO=A?function(a1,a0){if(az.buffer.slice){return new Uint8Array(az.buffer.slice(a1,a1+a0));
}else{var a2=new Uint8Array(a0);
a2.set(new Uint8Array(az.buffer,a1,a0));
return a2;
}}:function(a1,a0){return az.slice(a1,a1+a0);
};
function aB(){return aE>=aD;
}function aG(){return aE<aD?az[aE++]:0;
}function aS(a0){aA(aE);
az[aE++]=a0&255;
if(aE>aD){aD=aE;
}}function aL(){return aG()<<8|aG();
}function aX(a0){aS(a0>>8);
aS(a0);
}function aM(){var a0=aL();
return a0>=32768?a0-65536:a0;
}function aY(a0){aX(a0<0?a0+65536:a0);
}function aJ(){return aL()*65536+aL();
}function aV(a0){aX(a0>>>16&65535);
aX(a0&65535);
}function aK(){var a0=aJ();
return a0>=2147483648?a0-4294967296:a0;
}function aW(a0){aV(a0<0?a0+4294967296:a0);
}function aH(){return aJ()/65536;
}function aT(a0){aV(Math.round(a0*65536));
}function aI(){return aK()/65536;
}function aU(a0){aW(Math.round(a0*65536));
}function aF(a0){return aQ(a0,aG);
}function aN(a0){return String.fromCharCode.apply(String,aF(a0));
}function aZ(a1){for(var a0=0;
a0<a1.length;
++a0){aS(a1.charCodeAt(a0));
}}function aQ(a1,a2){for(var a3=new Array(a1),a0=0;
a0<a1;
++a0){a3[a0]=a2();
}return a3;
}var aP={eof:aB,readByte:aG,writeByte:aS,readShort:aL,writeShort:aX,readLong:aJ,writeLong:aV,readFixed:aH,writeFixed:aT,readShort_:aM,writeShort_:aY,readLong_:aK,writeLong_:aW,readFixed_:aI,writeFixed_:aU,read:aF,write:aR,readString:aN,writeString:aZ,times:aQ,get:aC,slice:aO,offset:function(a0){if(a0!=null){aE=a0;
return aP;
}return aE;
},skip:function(a0){aE+=a0;
},toString:function(){throw new Error("FIX CALLER.  BinaryStream is no longer convertible to string!");
},length:function(){return aD;
},saveExcursion:function(a0){var a1=aE;
try{return a0();
}finally{aE=a1;
}},writeBase64:function(a0){if(aw.atob){aZ(aw.atob(a0));
}else{aR(l.decode(a0));
}},base64:function(){return l.encode(aC());
}};
return aP;
}function av(az){return az.replace(/^\s*(['"])(.*)\1\s*$/,"$2");
}function X(az){var aC=/^\s*((normal|italic)\s+)?((normal|small-caps)\s+)?((normal|bold|\d+)\s+)?(([0-9.]+)(px|pt))(\/(([0-9.]+)(px|pt)|normal))?\s+(.*?)\s*$/i;
var aB=aC.exec(az);
if(!aB){return{fontSize:12,fontFamily:"sans-serif"};
}var aA=aB[8]?parseInt(aB[8],10):12;
return{italic:aB[2]&&aB[2].toLowerCase()=="italic",variant:aB[4],bold:aB[6]&&/bold|700/i.test(aB[6]),fontSize:aA,lineHeight:aB[12]?aB[12]=="normal"?aA:parseInt(aB[12],10):null,fontFamily:aB[14].split(/\s*,\s*/g).map(av)};
}function y(aD){function aB(aF){if(aD.bold){aF+="|bold";
}if(aD.italic){aF+="|italic";
}return aF.toLowerCase();
}var az=aD.fontFamily;
var aC,aE;
if(az instanceof Array){for(var aA=0;
aA<az.length;
++aA){aC=aB(az[aA]);
aE=w[aC];
if(aE){break;
}}}else{aE=w[az.toLowerCase()];
}while(typeof aE=="function"){aE=aE();
}if(!aE){aE="Times-Roman";
}return aE;
}var w={serif:"Times-Roman","serif|bold":"Times-Bold","serif|italic":"Times-Italic","serif|bold|italic":"Times-BoldItalic","sans-serif":"Helvetica","sans-serif|bold":"Helvetica-Bold","sans-serif|italic":"Helvetica-Oblique","sans-serif|bold|italic":"Helvetica-BoldOblique",monospace:"Courier","monospace|bold":"Courier-Bold","monospace|italic":"Courier-Oblique","monospace|bold|italic":"Courier-BoldOblique",zapfdingbats:"ZapfDingbats","zapfdingbats|bold":"ZapfDingbats","zapfdingbats|italic":"ZapfDingbats","zapfdingbats|bold|italic":"ZapfDingbats"};
function x(az,aA){az=az.toLowerCase();
w[az]=function(){return w[aA];
};
w[az+"|bold"]=function(){return w[aA+"|bold"];
};
w[az+"|italic"]=function(){return w[aA+"|italic"];
};
w[az+"|bold|italic"]=function(){return w[aA+"|bold|italic"];
};
}x("Times New Roman","serif");
x("Courier New","monospace");
x("Arial","sans-serif");
x("Helvetica","sans-serif");
x("Verdana","sans-serif");
x("Tahoma","sans-serif");
x("Georgia","sans-serif");
x("Monaco","monospace");
x("Andale Mono","monospace");
function u(aA,aB){if(arguments.length==1){for(var az in aA){if(B(aA,az)){u(az,aA[az]);
}}}else{aA=aA.toLowerCase();
w[aA]=aB;
switch(aA){case"dejavu sans":w["sans-serif"]=aB;
break;
case"dejavu sans|bold":w["sans-serif|bold"]=aB;
break;
case"dejavu sans|italic":w["sans-serif|italic"]=aB;
break;
case"dejavu sans|bold|italic":w["sans-serif|bold|italic"]=aB;
break;
case"dejavu serif":w.serif=aB;
break;
case"dejavu serif|bold":w["serif|bold"]=aB;
break;
case"dejavu serif|italic":w["serif|italic"]=aB;
break;
case"dejavu serif|bold|italic":w["serif|bold|italic"]=aB;
break;
case"dejavu mono":w.monospace=aB;
break;
case"dejavu mono|bold":w["monospace|bold"]=aB;
break;
case"dejavu mono|italic":w["monospace|italic"]=aB;
break;
case"dejavu mono|bold|italic":w["monospace|bold|italic"]=aB;
break;
}}}H.pdf={Document:aa,BinaryStream:m,defineFont:u,parseFontDef:X,getFontURL:y,loadFonts:K,loadImages:M,getPaperOptions:z,TEXT_RENDERING_MODE:{fill:0,stroke:1,fillAndStroke:2,invisible:3,fillAndClip:4,strokeAndClip:5,fillStrokeClip:6,clip:7}};
function S(az,aC){var aA=az[0],aD=az[1],aF=az[2],aH=az[3],aJ=az[4],aL=az[5];
var aB=aC[0],aE=aC[1],aG=aC[2],aI=aC[3],aK=aC[4],aM=aC[5];
return[aA*aB+aD*aG,aA*aE+aD*aI,aF*aB+aH*aG,aF*aE+aH*aI,aJ*aB+aL*aG+aK,aJ*aE+aL*aI+aM];
}function G(az){return az[0]===1&&az[1]===0&&az[2]===0&&az[3]===1&&az[4]===0&&az[5]===0;
}}(window,parseFloat));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("pdf/ttf",["pdf/core","util/main"],l);
}(function(){(function(E){function p(G,F){return Object.prototype.hasOwnProperty.call(G,F);
}function A(F){return Object.keys(F).sort(function(G,H){return G-H;
}).map(parseFloat);
}var y=E.kendo.pdf;
var k=y.BinaryStream;
function n(F){this.raw=F;
this.scalerType=F.readLong();
this.tableCount=F.readShort();
this.searchRange=F.readShort();
this.entrySelector=F.readShort();
this.rangeShift=F.readShort();
var I=this.tables={};
for(var H=0;
H<this.tableCount;
++H){var G={tag:F.readString(4),checksum:F.readLong(),offset:F.readLong(),length:F.readLong()};
I[G.tag]=G;
}}n.prototype={readTable:function(H,F){var G=this.tables[H];
if(!G){throw new Error("Table "+H+" not found in directory");
}return this[H]=G.table=new F(this,G);
},render:function(S){var Q=Object.keys(S).length;
var J=Math.pow(2,Math.floor(Math.log(Q)/Math.LN2));
var N=J*16;
var H=Math.floor(Math.log(J)/Math.LN2);
var M=Q*16-N;
var L=k();
L.writeLong(this.scalerType);
L.writeShort(Q);
L.writeShort(N);
L.writeShort(H);
L.writeShort(M);
var G=Q*16;
var K=L.offset()+G;
var I=null;
var R=k();
for(var T in S){if(p(S,T)){var P=S[T];
L.writeString(T);
L.writeLong(this.checksum(P));
L.writeLong(K);
L.writeLong(P.length);
R.write(P);
if(T=="head"){I=K;
}K+=P.length;
while(K%4){R.writeByte(0);
K++;
}}}L.write(R.get());
var O=this.checksum(L.get());
var F=2981146554-O;
L.offset(I+8);
L.writeLong(F);
return L.get();
},checksum:function(F){F=k(F);
var G=0;
while(!F.eof()){G+=F.readLong();
}return G&4294967295;
}};
function m(H){function F(J,I){this.definition=I;
this.length=I.length;
this.offset=I.offset;
this.file=J;
this.rawData=J.raw;
this.parse(J.raw);
}F.prototype.raw=function(){return this.rawData.slice(this.offset,this.length);
};
for(var G in H){if(p(H,G)){F[G]=F.prototype[G]=H[G];
}}return F;
}var q=m({parse:function(F){F.offset(this.offset);
this.version=F.readLong();
this.revision=F.readLong();
this.checkSumAdjustment=F.readLong();
this.magicNumber=F.readLong();
this.flags=F.readShort();
this.unitsPerEm=F.readShort();
this.created=F.read(8);
this.modified=F.read(8);
this.xMin=F.readShort_();
this.yMin=F.readShort_();
this.xMax=F.readShort_();
this.yMax=F.readShort_();
this.macStyle=F.readShort();
this.lowestRecPPEM=F.readShort();
this.fontDirectionHint=F.readShort_();
this.indexToLocFormat=F.readShort_();
this.glyphDataFormat=F.readShort_();
},render:function(F){var G=k();
G.writeLong(this.version);
G.writeLong(this.revision);
G.writeLong(0);
G.writeLong(this.magicNumber);
G.writeShort(this.flags);
G.writeShort(this.unitsPerEm);
G.write(this.created);
G.write(this.modified);
G.writeShort_(this.xMin);
G.writeShort_(this.yMin);
G.writeShort_(this.xMax);
G.writeShort_(this.yMax);
G.writeShort(this.macStyle);
G.writeShort(this.lowestRecPPEM);
G.writeShort_(this.fontDirectionHint);
G.writeShort_(F);
G.writeShort_(this.glyphDataFormat);
return G.get();
}});
var t=m({parse:function(F){F.offset(this.offset);
var G=this.file.head.indexToLocFormat;
if(G===0){this.offsets=F.times(this.length/2,function(){return 2*F.readShort();
});
}else{this.offsets=F.times(this.length/4,F.readLong);
}},offsetOf:function(F){return this.offsets[F];
},lengthOf:function(F){return this.offsets[F+1]-this.offsets[F];
},render:function(H){var I=k();
var G=H[H.length-1]>65535;
for(var F=0;
F<H.length;
++F){if(G){I.writeLong(H[F]);
}else{I.writeShort(H[F]/2);
}}return{format:G?1:0,table:I.get()};
}});
var r=m({parse:function(F){F.offset(this.offset);
this.version=F.readLong();
this.ascent=F.readShort_();
this.descent=F.readShort_();
this.lineGap=F.readShort_();
this.advanceWidthMax=F.readShort();
this.minLeftSideBearing=F.readShort_();
this.minRightSideBearing=F.readShort_();
this.xMaxExtent=F.readShort_();
this.caretSlopeRise=F.readShort_();
this.caretSlopeRun=F.readShort_();
this.caretOffset=F.readShort_();
F.skip(4*2);
this.metricDataFormat=F.readShort_();
this.numOfLongHorMetrics=F.readShort();
},render:function(F){var G=k();
G.writeLong(this.version);
G.writeShort_(this.ascent);
G.writeShort_(this.descent);
G.writeShort_(this.lineGap);
G.writeShort(this.advanceWidthMax);
G.writeShort_(this.minLeftSideBearing);
G.writeShort_(this.minRightSideBearing);
G.writeShort_(this.xMaxExtent);
G.writeShort_(this.caretSlopeRise);
G.writeShort_(this.caretSlopeRun);
G.writeShort_(this.caretOffset);
G.write([0,0,0,0,0,0,0,0]);
G.writeShort_(this.metricDataFormat);
G.writeShort(F.length);
return G.get();
}});
var u=m({parse:function(F){F.offset(this.offset);
this.version=F.readLong();
this.numGlyphs=F.readShort();
this.maxPoints=F.readShort();
this.maxContours=F.readShort();
this.maxComponentPoints=F.readShort();
this.maxComponentContours=F.readShort();
this.maxZones=F.readShort();
this.maxTwilightPoints=F.readShort();
this.maxStorage=F.readShort();
this.maxFunctionDefs=F.readShort();
this.maxInstructionDefs=F.readShort();
this.maxStackElements=F.readShort();
this.maxSizeOfInstructions=F.readShort();
this.maxComponentElements=F.readShort();
this.maxComponentDepth=F.readShort();
},render:function(F){var G=k();
G.writeLong(this.version);
G.writeShort(F.length);
G.writeShort(this.maxPoints);
G.writeShort(this.maxContours);
G.writeShort(this.maxComponentPoints);
G.writeShort(this.maxComponentContours);
G.writeShort(this.maxZones);
G.writeShort(this.maxTwilightPoints);
G.writeShort(this.maxStorage);
G.writeShort(this.maxFunctionDefs);
G.writeShort(this.maxInstructionDefs);
G.writeShort(this.maxStackElements);
G.writeShort(this.maxSizeOfInstructions);
G.writeShort(this.maxComponentElements);
G.writeShort(this.maxComponentDepth);
return G.get();
}});
var s=m({parse:function(F){F.offset(this.offset);
var G=this.file,H=G.hhea;
this.metrics=F.times(H.numOfLongHorMetrics,function(){return{advance:F.readShort(),lsb:F.readShort_()};
});
var I=G.maxp.numGlyphs-G.hhea.numOfLongHorMetrics;
this.leftSideBearings=F.times(I,F.readShort_);
},forGlyph:function(F){var G=this.metrics;
var H=G.length;
if(F<H){return G[F];
}return{advance:G[H-1].advance,lsb:this.leftSideBearings[F-H]};
},render:function(F){var I=k();
for(var G=0;
G<F.length;
++G){var H=this.forGlyph(F[G]);
I.writeShort(H.advance);
I.writeShort_(H.lsb);
}return I.get();
}});
var o=function(){function I(M){this.raw=M;
}I.prototype={compound:false,render:function(){return this.raw.get();
}};
var F=1;
var J=8;
var H=32;
var L=64;
var K=128;
function G(M){this.raw=M;
var O=this.glyphIds=[];
var P=this.idOffsets=[];
while(true){var N=M.readShort();
P.push(M.offset());
O.push(M.readShort());
if(!(N&H)){break;
}M.skip(N&F?4:2);
if(N&K){M.skip(8);
}else{if(N&L){M.skip(4);
}else{if(N&J){M.skip(2);
}}}}}G.prototype={compound:true,render:function(O){var P=k(this.raw.get());
for(var M=0;
M<this.glyphIds.length;
++M){var N=this.glyphIds[M];
P.offset(this.idOffsets[M]);
P.writeShort(O[N]);
}return P.get();
}};
return m({parse:function(){this.cache={};
},glyphFor:function(P){var M=this.cache;
if(p(M,P)){return M[P];
}var R=this.file.loca;
var Q=R.lengthOf(P);
if(Q===0){return M[P]=null;
}var N=this.rawData;
var T=this.offset+R.offsetOf(P);
var U=k(N.slice(T,Q));
var S=U.readShort_();
var W=U.readShort_();
var Y=U.readShort_();
var V=U.readShort_();
var X=U.readShort_();
var O=M[P]=S==-1?new G(U):new I(U);
O.numberOfContours=S;
O.xMin=W;
O.yMin=Y;
O.xMax=V;
O.yMax=X;
return O;
},render:function(N,S,R){var T=k(),Q=[];
for(var O=0;
O<S.length;
++O){var P=S[O];
var M=N[P];
Q.push(T.offset());
if(M){T.write(M.render(R));
}}Q.push(T.offset());
return{table:T.get(),offsets:Q};
}});
}();
var v=function(){function F(H,G){this.text=H;
this.length=H.length;
this.platformID=G.platformID;
this.platformSpecificID=G.platformSpecificID;
this.languageID=G.languageID;
this.nameID=G.nameID;
}return m({parse:function(H){H.offset(this.offset);
H.readShort();
var G=H.readShort();
var L=this.offset+H.readShort();
var J=H.times(G,function(){return{platformID:H.readShort(),platformSpecificID:H.readShort(),languageID:H.readShort(),nameID:H.readShort(),length:H.readShort(),offset:H.readShort()+L};
});
var M=this.strings={};
for(var I=0;
I<J.length;
++I){var K=J[I];
H.offset(K.offset);
var N=H.readString(K.length);
if(!M[K.nameID]){M[K.nameID]=[];
}M[K.nameID].push(new F(N,K));
}this.postscriptEntry=M[6][0];
this.postscriptName=this.postscriptEntry.text.replace(/[^\x20-\x7F]/g,"");
},render:function(K){var N=this.strings;
var M=0;
for(var G in N){if(p(N,G)){M+=N[G].length;
}}var J=k();
var O=k();
J.writeShort(0);
J.writeShort(M);
J.writeShort(6+12*M);
for(G in N){if(p(N,G)){var I=G==6?[new F(K,this.postscriptEntry)]:N[G];
for(var H=0;
H<I.length;
++H){var L=I[H];
J.writeShort(L.platformID);
J.writeShort(L.platformSpecificID);
J.writeShort(L.languageID);
J.writeShort(L.nameID);
J.writeShort(L.length);
J.writeShort(O.offset());
O.writeString(L.text);
}}}J.write(O.get());
return J.get();
}});
}();
var z=function(){var F=".notdef .null nonmarkingreturn space exclam quotedbl numbersign dollar percent ampersand quotesingle parenleft parenright asterisk plus comma hyphen period slash zero one two three four five six seven eight nine colon semicolon less equal greater question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z bracketleft backslash bracketright asciicircum underscore grave a b c d e f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright asciitilde Adieresis Aring Ccedilla Eacute Ntilde Odieresis Udieresis aacute agrave acircumflex adieresis atilde aring ccedilla eacute egrave ecircumflex edieresis iacute igrave icircumflex idieresis ntilde oacute ograve ocircumflex odieresis otilde uacute ugrave ucircumflex udieresis dagger degree cent sterling section bullet paragraph germandbls registered copyright trademark acute dieresis notequal AE Oslash infinity plusminus lessequal greaterequal yen mu partialdiff summation product pi integral ordfeminine ordmasculine Omega ae oslash questiondown exclamdown logicalnot radical florin approxequal Delta guillemotleft guillemotright ellipsis nonbreakingspace Agrave Atilde Otilde OE oe endash emdash quotedblleft quotedblright quoteleft quoteright divide lozenge ydieresis Ydieresis fraction currency guilsinglleft guilsinglright fi fl daggerdbl periodcentered quotesinglbase quotedblbase perthousand Acircumflex Ecircumflex Aacute Edieresis Egrave Iacute Icircumflex Idieresis Igrave Oacute Ocircumflex apple Ograve Uacute Ucircumflex Ugrave dotlessi circumflex tilde macron breve dotaccent ring cedilla hungarumlaut ogonek caron Lslash lslash Scaron scaron Zcaron zcaron brokenbar Eth eth Yacute yacute Thorn thorn minus multiply onesuperior twosuperior threesuperior onehalf onequarter threequarters franc Gbreve gbreve Idotaccent Scedilla scedilla Cacute cacute Ccaron ccaron dcroat".split(/\s+/g);
return m({parse:function(G){G.offset(this.offset);
this.format=G.readLong();
this.italicAngle=G.readFixed_();
this.underlinePosition=G.readShort_();
this.underlineThickness=G.readShort_();
this.isFixedPitch=G.readLong();
this.minMemType42=G.readLong();
this.maxMemType42=G.readLong();
this.minMemType1=G.readLong();
this.maxMemType1=G.readLong();
var I;
switch(this.format){case 65536:case 196608:break;
case 131072:I=G.readShort();
this.glyphNameIndex=G.times(I,G.readShort);
this.names=[];
var H=this.offset+this.length;
while(G.offset()<H){this.names.push(G.readString(G.readByte()));
}break;
case 151552:I=G.readShort();
this.offsets=G.read(I);
break;
case 262144:this.map=G.times(this.file.maxp.numGlyphs,G.readShort);
break;
}},glyphFor:function(G){switch(this.format){case 65536:return F[G]||".notdef";
case 131072:var H=this.glyphNameIndex[G];
if(H<F.length){return F[H];
}return this.names[H-F.length]||".notdef";
case 151552:case 196608:return".notdef";
case 262144:return this.map[G]||65535;
}},render:function(K){if(this.format==196608){return this.raw();
}var L=k(this.rawData.slice(this.offset,32));
L.writeLong(131072);
L.offset(32);
var J=[];
var N=[];
for(var G=0;
G<K.length;
++G){var H=K[G];
var M=this.glyphFor(H);
var I=F.indexOf(M);
if(I>=0){J.push(I);
}else{J.push(F.length+N.length);
N.push(M);
}}L.writeShort(K.length);
for(G=0;
G<J.length;
++G){L.writeShort(J[G]);
}for(G=0;
G<N.length;
++G){L.writeByte(N[G].length);
L.writeString(N[G]);
}return L.get();
}});
}();
var l=function(){function F(I,J,H){var K=this;
K.platformID=I.readShort();
K.platformSpecificID=I.readShort();
K.offset=J+I.readLong();
I.saveExcursion(function(){var L;
I.offset(K.offset);
K.format=I.readShort();
switch(K.format){case 0:K.length=I.readShort();
K.language=I.readShort();
for(var T=0;
T<256;
++T){H[T]=I.readByte();
}break;
case 4:K.length=I.readShort();
K.language=I.readShort();
var Z=I.readShort()/2;
I.skip(6);
var P=I.times(Z,I.readShort);
I.skip(2);
var ab=I.times(Z,I.readShort);
var U=I.times(Z,I.readShort_);
var V=I.times(Z,I.readShort);
var M=(K.length+K.offset-I.offset())/2;
var S=I.times(M,I.readShort);
for(T=0;
T<Z;
++T){var aa=ab[T],N=P[T];
for(L=aa;
L<=N;
++L){var R;
if(V[T]===0){R=L+U[T];
}else{var W=V[T]/2-(Z-T)+(L-aa);
R=S[W]||0;
if(R!==0){R+=U[T];
}}H[L]=R&65535;
}}break;
case 6:K.length=I.readShort();
K.language=I.readShort();
L=I.readShort();
var X=I.readShort();
while(X-->0){H[L++]=I.readShort();
}break;
case 12:I.readShort();
K.length=I.readLong();
K.language=I.readLong();
var Y=I.readLong();
while(Y-->0){L=I.readLong();
var O=I.readLong();
var Q=I.readLong();
while(L<=O){H[L++]=Q++;
}}break;
default:if(E.console){E.console.error("Unhandled CMAP format: "+K.format);
}}});
}function G(U,W){var I=A(U);
var ae=[];
var N=[];
var T=null;
var L=null;
function V(ag){return W[U[ag]];
}for(var R=0;
R<I.length;
++R){var H=I[R];
var P=V(H);
var J=P-H;
if(T==null||J!==L){if(T){N.push(T);
}ae.push(H);
L=J;
}T=H;
}if(T){N.push(T);
}N.push(65535);
ae.push(65535);
var ab=ae.length;
var ac=ab*2;
var aa=2*Math.pow(2,Math.floor(Math.log(ab)/Math.LN2));
var O=Math.log(aa/2)/Math.LN2;
var Z=ac-aa;
var K=[];
var Y=[];
var Q=[];
for(R=0;
R<ab;
++R){var ad=ae[R];
var M=N[R];
if(ad==65535){K.push(0);
Y.push(0);
break;
}var af=V(ad);
if(ad-af>=32768){K.push(0);
Y.push(2*(Q.length+ab-R));
for(var S=ad;
S<=M;
++S){Q.push(V(S));
}}else{K.push(af-ad);
Y.push(0);
}}var X=k();
X.writeShort(3);
X.writeShort(1);
X.writeLong(12);
X.writeShort(4);
X.writeShort(16+ab*8+Q.length*2);
X.writeShort(0);
X.writeShort(ac);
X.writeShort(aa);
X.writeShort(O);
X.writeShort(Z);
N.forEach(X.writeShort);
X.writeShort(0);
ae.forEach(X.writeShort);
K.forEach(X.writeShort_);
Y.forEach(X.writeShort);
Q.forEach(X.writeShort);
return X.get();
}return m({parse:function(H){var J=this;
var I=J.offset;
H.offset(I);
J.codeMap={};
J.version=H.readShort();
var K=H.readShort();
J.tables=H.times(K,function(){return new F(H,I,J.codeMap);
});
},render:function(H,I){var J=k();
J.writeShort(0);
J.writeShort(1);
J.write(G(H,I));
return J.get();
}});
}();
var x=m({parse:function(F){F.offset(this.offset);
this.version=F.readShort();
this.averageCharWidth=F.readShort_();
this.weightClass=F.readShort();
this.widthClass=F.readShort();
this.type=F.readShort();
this.ySubscriptXSize=F.readShort_();
this.ySubscriptYSize=F.readShort_();
this.ySubscriptXOffset=F.readShort_();
this.ySubscriptYOffset=F.readShort_();
this.ySuperscriptXSize=F.readShort_();
this.ySuperscriptYSize=F.readShort_();
this.ySuperscriptXOffset=F.readShort_();
this.ySuperscriptYOffset=F.readShort_();
this.yStrikeoutSize=F.readShort_();
this.yStrikeoutPosition=F.readShort_();
this.familyClass=F.readShort_();
this.panose=F.times(10,F.readByte);
this.charRange=F.times(4,F.readLong);
this.vendorID=F.readString(4);
this.selection=F.readShort();
this.firstCharIndex=F.readShort();
this.lastCharIndex=F.readShort();
if(this.version>0){this.ascent=F.readShort_();
this.descent=F.readShort_();
this.lineGap=F.readShort_();
this.winAscent=F.readShort();
this.winDescent=F.readShort();
this.codePageRange=F.times(2,F.readLong);
if(this.version>1){this.xHeight=F.readShort();
this.capHeight=F.readShort();
this.defaultChar=F.readShort();
this.breakChar=F.readShort();
this.maxContext=F.readShort();
}}},render:function(){return this.raw();
}});
var C=100000;
function w(){var H="",G=C+"";
for(var F=0;
F<G.length;
++F){H+=String.fromCharCode(G.charCodeAt(F)-48+65);
}++C;
return H;
}function B(F){this.font=F;
this.subset={};
this.unicodes={};
this.ogid2ngid={0:0};
this.ngid2ogid={0:0};
this.ncid2ogid={};
this.next=this.firstChar=1;
this.nextGid=1;
this.psName=w()+"+"+this.font.psName;
}B.prototype={use:function(F){var J=this;
if(typeof F=="string"){return kendo.util.ucs2decode(F).reduce(function(L,K){return L+String.fromCharCode(J.use(K));
},"");
}var G=J.unicodes[F];
if(!G){G=J.next++;
J.subset[G]=F;
J.unicodes[F]=G;
var I=J.font.cmap.codeMap[F];
if(I){J.ncid2ogid[G]=I;
if(J.ogid2ngid[I]==null){var H=J.nextGid++;
J.ogid2ngid[I]=H;
J.ngid2ogid[H]=I;
}}}return G;
},encodeText:function(F){return this.use(F);
},glyphIds:function(){return A(this.ogid2ngid);
},glyphsFor:function(G,J){if(!J){J={};
}for(var H=0;
H<G.length;
++H){var I=G[H];
if(!J[I]){var F=J[I]=this.font.glyf.glyphFor(I);
if(F&&F.compound){this.glyphsFor(F.glyphIds,J);
}}}return J;
},render:function(){var H=this.glyphsFor(this.glyphIds());
for(var L in H){if(p(H,L)){L=parseInt(L,10);
if(this.ogid2ngid[L]==null){var J=this.nextGid++;
this.ogid2ngid[L]=J;
this.ngid2ogid[J]=L;
}}}var K=A(this.ngid2ogid);
var M=K.map(function(O){return this.ngid2ogid[O];
},this);
var F=this.font;
var G=F.glyf.render(H,M,this.ogid2ngid);
var I=F.loca.render(G.offsets);
this.lastChar=this.next-1;
var N={cmap:l.render(this.ncid2ogid,this.ogid2ngid),glyf:G.table,loca:I.table,hmtx:F.hmtx.render(M),hhea:F.hhea.render(M),maxp:F.maxp.render(M),post:F.post.render(M),name:F.name.render(this.psName),head:F.head.render(I.format),"OS/2":F.os2.render()};
return this.font.directory.render(N);
},cidToGidMap:function(){var J=k(),G=0;
for(var F=this.firstChar;
F<this.next;
++F){while(G<F){J.writeShort(0);
G++;
}var I=this.ncid2ogid[F];
if(I){var H=this.ogid2ngid[I];
J.writeShort(H);
}else{J.writeShort(0);
}G++;
}return J.get();
}};
function D(K,H){var L=this;
var F=L.contents=k(K);
if(F.readString(4)=="ttcf"){if(!H){throw new Error("Must specify a name for TTC files");
}F.readLong();
var I=F.readLong();
for(var G=0;
G<I;
++G){var J=F.readLong();
F.saveExcursion(function(){F.offset(J);
L.parse();
});
if(L.psName==H){return;
}}throw new Error("Font "+H+" not found in collection");
}else{F.offset(0);
L.parse();
}}D.prototype={parse:function(){var F=this.directory=new n(this.contents);
this.head=F.readTable("head",q);
this.loca=F.readTable("loca",t);
this.hhea=F.readTable("hhea",r);
this.maxp=F.readTable("maxp",u);
this.hmtx=F.readTable("hmtx",s);
this.glyf=F.readTable("glyf",o);
this.name=F.readTable("name",v);
this.post=F.readTable("post",z);
this.cmap=F.readTable("cmap",l);
this.os2=F.readTable("OS/2",x);
this.psName=this.name.postscriptName;
this.ascent=this.os2.ascent||this.hhea.ascent;
this.descent=this.os2.descent||this.hhea.descent;
this.lineGap=this.os2.lineGap||this.hhea.lineGap;
this.scale=1000/this.head.unitsPerEm;
},widthOfGlyph:function(F){return this.hmtx.forGlyph(F).advance*this.scale;
},makeSubset:function(){return new B(this);
}};
y.TTFFont=D;
}(window));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("pdf/drawing",["kendo.core","kendo.color","kendo.drawing","pdf/core"],l);
}(function(){(function(A,k){var t=A.drawing;
var z=A.geometry;
var O=A.pdf.TEXT_RENDERING_MODE;
var m={dash:[4],dashDot:[4,2,1,2],dot:[1,2],longDash:[8,2],longDashDot:[8,2,1,2],longDashDotDot:[8,2,1,2,1,2],solid:[]};
var B={butt:0,round:1,square:2};
var C={miter:0,round:1,bevel:2};
function I(W,R){var U=[],X=[],Z=W.options;
function V(ac,aa,ab){if(!ab){ab=Z;
}if(ab.pdf&&ab.pdf[ac]!=null){return ab.pdf[ac];
}return aa;
}var Y=V("multiPage");
W.traverse(function(aa){n({Image:function(ab){if(X.indexOf(ab.src())<0){X.push(ab.src());
}},Text:function(ab){var ac=A.pdf.parseFontDef(ab.options.font);
var ad=A.pdf.getFontURL(ac);
if(U.indexOf(ad)<0){U.push(ad);
}}},aa);
});
function T(){if(--S>0){return;
}var ab=new A.pdf.Document({producer:V("producer"),title:V("title"),author:V("author"),subject:V("subject"),keywords:V("keywords"),creator:V("creator"),date:V("date")});
function aa(ae){var af=ae.options;
var ak=G(ae);
var ad=ak.bbox;
ae=ak.root;
var ai=V("paperSize",V("paperSize","auto"),af),ac=false;
if(ai=="auto"){if(ad){var aj=ad.getSize();
ai=[aj.width,aj.height];
ac=true;
var ag=ad.getOrigin();
ak=new t.Group();
ak.transform(new z.Matrix(1,0,0,1,-ag.x,-ag.y));
ak.append(ae);
ae=ak;
}else{ai="A4";
}}var ah;
ah=ab.addPage({paperSize:ai,margin:V("margin",V("margin"),af),addMargin:ac,landscape:V("landscape",V("landscape",false),af)});
q(ae,ah,ab);
}if(Y){W.children.forEach(aa);
}else{aa(W);
}R(ab.render(),ab);
}var S=2;
A.pdf.loadFonts(U,T);
A.pdf.loadImages(X,T);
}function Q(S,R){I(S,function(T){R("data:application/pdf;base64,"+T.base64());
});
}function P(S,R){I(S,function(T){R(new Blob([T.get()],{type:"application/pdf"}));
});
}function J(T,S,U,R){if(window.Blob&&!A.support.browser.safari){P(T,function(V){A.saveAs({dataURI:V,fileName:S});
if(R){R(V);
}});
}else{Q(T,function(V){A.saveAs({dataURI:V,fileName:S,proxyURL:U});
if(R){R(V);
}});
}}function n(T,R){var S=T[R.nodeType];
if(S){return S.call.apply(S,arguments);
}return R;
}function q(R,U,V){if(R.options._pdfDebug){U.comment("BEGIN: "+R.options._pdfDebug);
}var W=R.transform();
var T=R.opacity();
U.save();
if(T!=null&&T<1){U.setOpacity(T);
}M(R,U,V);
L(R,U,V);
if(W){var S=W.matrix();
U.transform(S.a,S.b,S.c,S.d,S.e,S.f);
}K(R,U,V);
n({Path:v,MultiPath:u,Circle:p,Arc:o,Text:x,Image:s,Group:r,Rect:w},R,U,V);
U.restore();
if(R.options._pdfDebug){U.comment("END: "+R.options._pdfDebug);
}}function M(T,X){var Y=T.stroke&&T.stroke();
if(!Y){return;
}var R=Y.color;
if(R){R=H(R);
if(R==null){return;
}X.setStrokeColor(R.r,R.g,R.b);
if(R.a!=1){X.setStrokeOpacity(R.a);
}}var Z=Y.width;
if(Z!=null){if(Z===0){return;
}X.setLineWidth(Z);
}var S=Y.dashType;
if(S){X.setDashPattern(m[S],0);
}var U=Y.lineCap;
if(U){X.setLineCap(B[U]);
}var V=Y.lineJoin;
if(V){X.setLineJoin(C[V]);
}var W=Y.opacity;
if(W!=null){X.setStrokeOpacity(W);
}}function L(S,V){var T=S.fill&&S.fill();
if(!T){return;
}if(T instanceof t.Gradient){return;
}var R=T.color;
if(R){R=H(R);
if(R==null){return;
}V.setFillColor(R.r,R.g,R.b);
if(R.a!=1){V.setFillOpacity(R.a);
}}var U=T.opacity;
if(U!=null){V.setFillOpacity(U);
}}function K(S,T,U){var R=S.clip();
if(R){l(R,T,U);
T.clip();
}}function N(R){return R&&(R instanceof t.Gradient||R.color&&!/^(none|transparent)$/i.test(R.color)&&(R.width==null||R.width>0)&&(R.opacity==null||R.opacity>0));
}function F(S,X,Y,ab){var U=S.fill();
if(U instanceof t.Gradient){if(ab){X.clipStroke();
}else{X.clip();
}var W=U instanceof t.RadialGradient;
var aa,T;
if(W){aa={x:U.center().x,y:U.center().y,r:0};
T={x:U.center().x,y:U.center().y,r:U.radius()};
}else{aa={x:U.start().x,y:U.start().y};
T={x:U.end().x,y:U.end().y};
}var V={type:W?"radial":"linear",start:aa,end:T,userSpace:U.userSpace(),stops:U.stops.elements().map(function(af){var ae=af.offset();
if(/%$/.test(ae)){ae=parseFloat(ae)/100;
}else{ae=parseFloat(ae);
}var ad=H(af.color());
ad.a*=af.opacity();
return{offset:ae,color:ad};
})};
var R=S.rawBBox();
var ac=R.topLeft(),Z=R.getSize();
R={left:ac.x,top:ac.y,width:Z.width,height:Z.height};
X.gradient(V,R);
return true;
}}function E(R,S,T){if(N(R.fill())&&N(R.stroke())){if(!F(R,S,T,true)){S.fillStroke();
}}else{if(N(R.fill())){if(!F(R,S,T,false)){S.fill();
}}else{if(N(R.stroke())){S.stroke();
}else{S.nop();
}}}}function D(V,U){var W=V.segments;
if(W.length==4&&V.options.closed){var R=[];
for(var S=0;
S<W.length;
++S){if(W[S].controlIn()){return false;
}R[S]=W[S].anchor();
}var T=R[0].y==R[1].y&&R[1].x==R[2].x&&R[2].y==R[3].y&&R[3].x==R[0].x||R[0].x==R[1].x&&R[1].y==R[2].y&&R[2].x==R[3].x&&R[3].y==R[0].y;
if(T){U.rect(R[0].x,R[0].y,R[2].x-R[0].x,R[2].y-R[0].y);
return true;
}}}function l(T,V,W){var aa=T.segments;
if(aa.length===0){return;
}if(!D(T,V,W)){for(var X,U=0;
U<aa.length;
++U){var Z=aa[U];
var R=Z.anchor();
if(!X){V.moveTo(R.x,R.y);
}else{var Y=X.controlOut();
var S=Z.controlIn();
if(Y&&S){V.bezier(Y.x,Y.y,S.x,S.y,R.x,R.y);
}else{V.lineTo(R.x,R.y);
}}X=Z;
}if(T.options.closed){V.close();
}}}function v(R,S,T){l(R,S,T);
E(R,S,T);
}function u(R,T,V){var U=R.paths;
for(var S=0;
S<U.length;
++S){l(U[S],T,V);
}E(R,T,V);
}function p(R,T,U){var S=R.geometry();
T.circle(S.center.x,S.center.y,S.radius);
E(R,T,U);
}function o(R,T,U){var V=R.geometry().curvePoints();
T.moveTo(V[0].x,V[0].y);
for(var S=1;
S<V.length;
){T.bezier(V[S].x,V[S++].y,V[S].x,V[S++].y,V[S].x,V[S++].y);
}E(R,T,U);
}function x(R,T){var V=A.pdf.parseFontDef(R.options.font);
var U=R._position;
var S;
if(R.fill()&&R.stroke()){S=O.fillAndStroke;
}else{if(R.fill()){S=O.fill;
}else{if(R.stroke()){S=O.stroke;
}}}T.transform(1,0,0,-1,U.x,U.y+V.fontSize);
T.beginText();
T.setFont(A.pdf.getFontURL(V),V.fontSize);
T.setTextRenderingMode(S);
T.showText(R.content(),R._pdfRect?R._pdfRect.width():null);
T.endText();
}function r(S,U,V){if(S._pdfLink){U.addLink(S._pdfLink.url,S._pdfLink);
}var R=S.children;
for(var T=0;
T<R.length;
++T){q(R[T],U,V);
}}function s(R,S){var W=R.src();
if(!W){return;
}var T=R.rect();
var V=T.getOrigin();
var U=T.getSize();
S.transform(U.width,0,0,-U.height,V.x,V.y+U.height);
S.drawImage(W);
}function w(R,T,U){var S=R.geometry();
T.rect(S.origin.x,S.origin.y,S.size.width,S.size.height);
E(R,T,U);
}function y(S,U){var R=k.Deferred();
for(var T in U){S.options.set("pdf."+T,U[T]);
}t.pdf.toDataURL(S,R.resolve);
return R.promise();
}function H(S){var R=A.parseColor(S,true);
return R?R.toRGB():null;
}function G(Z){var T=false;
var W=z.Matrix.unit();
var U=null;
var S;
do{S=false;
Z=X(Z);
}while(Z&&S);
return{root:Z,bbox:U};
function R(ac){S=true;
return ac;
}function aa(ac){return ac.visible()&&ac.opacity()>0&&(N(ac.fill())||N(ac.stroke()));
}function Y(ac){var ad=[];
for(var af=0;
af<ac.length;
++af){var ae=X(ac[af]);
if(ae!=null){ad.push(ae);
}}return ad;
}function ab(ag,ad){var ae=T;
var af=W;
if(ag.transform()){W=W.multiplyCopy(ag.transform().matrix());
}var ac=ag.clip();
if(ac){ac=ac.bbox();
if(ac){ac=ac.bbox(W);
T=T?z.Rect.intersect(T,ac):ac;
}}try{return ad();
}finally{T=ae;
W=af;
}}function V(ad){if(T==null){return false;
}var ac=ad.rawBBox().bbox(W);
if(T&&ac){ac=z.Rect.intersect(ac,T);
}return ac;
}function X(ac){return ab(ac,function(){if(!(ac instanceof t.Group||ac instanceof t.MultiPath)){var ad=V(ac);
if(!ad){return R(null);
}U=U?z.Rect.union(U,ad):ad;
}return n({Path:function(ae){if(ae.segments.length===0||!aa(ae)){return R(null);
}return ae;
},MultiPath:function(af){if(!aa(af)){return R(null);
}var ae=new t.MultiPath(af.options);
ae.paths=Y(af.paths);
if(ae.paths.length===0){return R(null);
}return ae;
},Circle:function(ae){if(!aa(ae)){return R(null);
}return ae;
},Arc:function(ae){if(!aa(ae)){return R(null);
}return ae;
},Text:function(ae){if(!/\S/.test(ae.content())||!aa(ae)){return R(null);
}return ae;
},Image:function(ae){if(!(ae.visible()&&ae.opacity()>0)){return R(null);
}return ae;
},Group:function(af){var ae=new t.Group(af.options);
ae.children=Y(af.children);
ae._pdfLink=af._pdfLink;
if(af!==Z&&ae.children.length===0&&!af._pdfLink){return R(null);
}return ae;
},Rect:function(ae){if(!aa(ae)){return R(null);
}return ae;
}},ac);
});
}}A.deepExtend(t,{exportPDF:y,pdf:{toDataURL:Q,toBlob:P,saveAs:J,toStream:I}});
}(window.kendo,window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.pdf",["kendo.core","pdf/core","pdf/ttf","pdf/drawing","kendo.drawing"],l);
}(function(){var k={id:"pdf",name:"PDF export",description:"PDF Generation framework",mixin:true,category:"framework",depends:["core","drawing"]};
(function(m,l){m.PDFMixin={extend:function(n){n.events.push("pdfExport");
n.options.pdf=this.options;
n.saveAsPDF=this.saveAsPDF;
n._drawPDF=this._drawPDF;
n._drawPDFShadow=this._drawPDFShadow;
},options:{fileName:"Export.pdf",proxyURL:"",paperSize:"auto",allPages:false,landscape:false,margin:null,title:null,author:null,subject:null,keywords:null,creator:"Kendo UI PDF Generator v."+m.version,date:null},saveAsPDF:function(){var p=new l.Deferred();
var q=p.promise();
var n={promise:q};
if(this.trigger("pdfExport",n)){return;
}var o=this.options.pdf;
o.multiPage=o.allPages;
this._drawPDF(p).then(function(r){return m.drawing.exportPDF(r,o);
}).done(function(r){m.saveAs({dataURI:r,fileName:o.fileName,proxyURL:o.proxyURL,forceProxy:o.forceProxy,proxyTarget:o.proxyTarget});
p.resolve();
}).fail(function(r){p.reject(r);
});
return q;
},_drawPDF:function(n){var o=new l.Deferred();
m.drawing.drawDOM(this.wrapper).done(function(q){var p={page:q,pageNumber:1,progress:1,totalPages:1};
n.notify(p);
o.resolve(p.page);
}).fail(function(p){o.reject(p);
});
return o;
},_drawPDFShadow:function(p,o){p=p||{};
var r=this.wrapper;
var q=l("<div class='k-pdf-export-shadow'>");
if(p.width){q.css({width:p.width,overflow:"visible"});
}r.before(q);
q.append(p.content||r.clone(true,true));
var n=l.Deferred();
setTimeout(function(){var s=m.drawing.drawDOM(q,o);
s.always(function(){q.remove();
}).then(function(){n.resolve.apply(n,arguments);
}).fail(function(){n.reject.apply(n,arguments);
}).progress(function(){n.progress.apply(n,arguments);
});
},15);
return n.promise();
}};
}(kendo,window.kendo.jQuery));
return kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
