(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.resizable",["kendo.core","kendo.draganddrop"],l);
}(function(){var k={id:"resizable",name:"Resizable",category:"framework",depends:["core","draganddrop"],advanced:true};
(function(l,w){var p=window.kendo,v=p.ui,y=v.Widget,q=l.proxy,o=p.isFunction,m=l.extend,n="horizontal",x="vertical",u="start",s="resize",t="resizeend";
var r=y.extend({init:function(z,A){var B=this;
y.fn.init.call(B,z,A);
B.orientation=B.options.orientation.toLowerCase()!=x?n:x;
B._positionMouse=B.orientation==n?"x":"y";
B._position=B.orientation==n?"left":"top";
B._sizingDom=B.orientation==n?"outerWidth":"outerHeight";
B.draggable=new v.Draggable(z,{distance:1,filter:A.handle,drag:q(B._resize,B),dragcancel:q(B._cancel,B),dragstart:q(B._start,B),dragend:q(B._stop,B)});
B.userEvents=B.draggable.userEvents;
},events:[s,t,u],options:{name:"Resizable",orientation:n},resize:function(){},_max:function(z){var C=this,A=C.hint?C.hint[C._sizingDom]():0,B=C.options.max;
return o(B)?B(z):B!==w?C._initialElementPosition+B-A:B;
},_min:function(z){var B=this,A=B.options.min;
return o(A)?A(z):A!==w?B._initialElementPosition+A:A;
},_start:function(z){var C=this,B=C.options.hint,A=l(z.currentTarget);
C._initialElementPosition=A.position()[C._position];
C._initialMousePosition=z[C._positionMouse].startLocation;
if(B){C.hint=o(B)?l(B(A)):B;
C.hint.css({position:"absolute"}).css(C._position,C._initialElementPosition).appendTo(C.element);
}C.trigger(u,z);
C._maxPosition=C._max(z);
C._minPosition=C._min(z);
l(document.body).css("cursor",A.css("cursor"));
},_resize:function(A){var E=this,B=E._maxPosition,C=E._minPosition,z=E._initialElementPosition+(A[E._positionMouse].location-E._initialMousePosition),D;
D=C!==w?Math.max(C,z):z;
E.position=D=B!==w?Math.min(B,D):D;
if(E.hint){E.hint.toggleClass(E.options.invalidClass||"",D==B||D==C).css(E._position,D);
}E.resizing=true;
E.trigger(s,m(A,{position:D}));
},_stop:function(z){var A=this;
if(A.hint){A.hint.remove();
}A.resizing=false;
A.trigger(t,m(z,{position:A.position}));
l(document.body).css("cursor","");
},_cancel:function(z){var A=this;
if(A.hint){A.position=w;
A.hint.css(A._position,A._initialElementPosition);
A._stop(z);
}},destroy:function(){var z=this;
y.fn.destroy.call(z);
if(z.draggable){z.draggable.destroy();
}},press:function(A){if(!A){return;
}var z=A.position(),B=this;
B.userEvents.press(z.left,z.top,A[0]);
B.targetPosition=z;
B.target=A;
},move:function(A){var D=this,B=D._position,C=D.targetPosition,z=D.position;
if(z===w){z=C[B];
}C[B]=z+A;
D.userEvents.move(C.left,C.top);
},end:function(){this.userEvents.end();
this.target=this.position=w;
}});
p.ui.plugin(r);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
