(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.timepicker",["kendo.popup"],l);
}(function(){var k={id:"timepicker",name:"TimePicker",category:"web",description:"The TimePicker widget allows the end user to select a value from a list of predefined values or to type a new value.",depends:["popup"]};
(function(l,ag){var K=window.kendo,L=K.keys,T=K.parseDate,m=K._activeElement,C=K._extractFormat,ab=K.support,t=ab.browser,af=K.ui,ah=af.Widget,S="open",w="close",u="change",R=".kendoTimePicker",v="click"+R,y="k-state-default",z="disabled",W="readonly",M="li",Z="<span/>",D="k-state-focused",F="k-state-hover",G="mouseenter"+R+" mouseleave"+R,N="mousedown"+R,P=60000,O=86400000,X="k-state-selected",aa="k-state-disabled",s="aria-selected",p="aria-expanded",q="aria-hidden",o="aria-disabled",r="aria-readonly",n="aria-activedescendant",H="id",I=l.isArray,B=l.extend,V=l.proxy,x=Date,ae=new x();
ae=new x(ae.getFullYear(),ae.getMonth(),ae.getDate(),0,0,0);
var ad=function(aj){var ak=this,ai=aj.id;
ak.options=aj;
ak._dates=[];
ak.ul=l('<ul tabindex="-1" role="listbox" aria-hidden="true" unselectable="on" class="k-list k-reset"/>').css({overflow:ab.kineticScrollNeeded?"":"auto"}).on(v,M,V(ak._click,ak)).on("mouseenter"+R,M,function(){l(this).addClass(F);
}).on("mouseleave"+R,M,function(){l(this).removeClass(F);
});
ak.list=l("<div class='k-list-container k-list-scroller' unselectable='on'/>").append(ak.ul).on(N,U);
if(ai){ak._timeViewID=ai+"_timeview";
ak._optionID=ai+"_option_selected";
ak.ul.attr(H,ak._timeViewID);
}ak._popup();
ak._heightHandler=V(ak._height,ak);
ak.template=K.template('<li tabindex="-1" role="option" class="k-item" unselectable="on">#=data#</li>',{useWithBlock:false});
};
ad.prototype={current:function(aj){var ak=this,ai=ak.options.active;
if(aj!==ag){if(ak._current){ak._current.removeClass(X).removeAttr(s).removeAttr(H);
}if(aj){aj=l(aj).addClass(X).attr(H,ak._optionID).attr(s,true);
ak.scroll(aj[0]);
}ak._current=aj;
if(ai){ai(aj);
}}else{return ak._current;
}},close:function(){this.popup.close();
},destroy:function(){var ai=this;
ai.ul.off(R);
ai.list.off(R);
ai.popup.destroy();
},open:function(){var ai=this;
if(!ai.ul[0].firstChild){ai.bind();
}ai.popup.open();
if(ai._current){ai.scroll(ai._current[0]);
}},dataBind:function(aj){var aq=this,ao=aq.options,ak=ao.format,ar=K.toString,ap=aq.template,an=aj.length,am=0,ai,al="";
for(;
am<an;
am++){ai=aj[am];
if(J(ai,ao.min,ao.max)){al+=ap(ar(ai,ak,ao.culture));
}}aq._html(al);
},refresh:function(){var aA=this,aw=aA.options,ai=aw.format,av=A(),al=av<0,ap=aw.min,ao=aw.max,at=E(ap),ar=E(ao),aq=aw.interval*P,aB=K.toString,az=aA.template,ax=new x(+ap),ay=ax.getDate(),au,am,ak=0,an,aj="";
if(al){an=(O+av*P)/aq;
}else{an=O/aq;
}if(at!=ar){if(at>ar){ar+=O;
}an=(ar-at)/aq+1;
}am=parseInt(an,10);
for(;
ak<an;
ak++){if(ak){Y(ax,aq,al);
}if(ar&&am==ak){au=E(ax);
if(ay<ax.getDate()){au+=O;
}if(au>ar){ax=new x(+ao);
}}aA._dates.push(E(ax));
aj+=az(aB(ax,ai,aw.culture));
}aA._html(aj);
},bind:function(){var aj=this,ai=aj.options.dates;
if(ai&&ai[0]){aj.dataBind(ai);
}else{aj.refresh();
}},_html:function(ai){var aj=this;
aj.ul[0].innerHTML=ai;
aj.popup.unbind(S,aj._heightHandler);
aj.popup.one(S,aj._heightHandler);
aj.current(null);
aj.select(aj._value);
},scroll:function(am){if(!am){return;
}var aj=this.list[0],ao=am.offsetTop,an=am.offsetHeight,al=aj.scrollTop,ak=aj.clientHeight,ai=ao+an;
if(al>ao){al=ao;
}else{if(ai>al+ak){al=ai-ak;
}}aj.scrollTop=al;
},select:function(aj){var am=this,ak=am.options,ai=am._current,al;
if(aj instanceof Date){aj=K.toString(aj,ak.format,ak.culture);
}if(typeof aj==="string"){if(!ai||ai.text()!==aj){aj=l.grep(am.ul[0].childNodes,function(an){return(an.textContent||an.innerText)==aj;
});
aj=aj[0]?aj:null;
}else{aj=ai;
}}al=am._distinctSelection(aj);
am.current(al);
},_distinctSelection:function(aj){var al=this,ai,ak;
if(aj&&aj.length>1){ai=E(al._value);
ak=l.inArray(ai,al._dates);
aj=al.ul.children()[ak];
}return aj;
},setOptions:function(aj){var ai=this.options;
aj.min=T(aj.min);
aj.max=T(aj.max);
this.options=B(ai,aj,{active:ai.active,change:ai.change,close:ai.close,open:ai.open});
this.bind();
},toggle:function(){var ai=this;
if(ai.popup.visible()){ai.close();
}else{ai.open();
}},value:function(aj){var ai=this;
ai._value=aj;
if(ai.ul[0].firstChild){ai.select(aj);
}},_click:function(ak){var am=this,al=l(ak.currentTarget),ai=al.text(),aj=am.options.dates;
if(aj&&aj.length>0){ai=aj[al.index()];
}if(!ak.isDefaultPrevented()){am.select(al);
am.options.change(ai,true);
am.close();
}},_height:function(){var al=this;
var aj=al.list;
var ak=aj.parent(".k-animation-container");
var ai=al.options.height;
if(al.ul[0].children.length){aj.add(ak).show().height(al.ul[0].scrollHeight>ai?ai:"auto").hide();
}},_parse:function(al){var ak=this,aj=ak.options,ai=ak._value||ae;
if(al instanceof x){return al;
}al=T(al,aj.parseFormats,aj.culture);
if(al){al=new x(ai.getFullYear(),ai.getMonth(),ai.getDate(),al.getHours(),al.getMinutes(),al.getSeconds(),al.getMilliseconds());
}return al;
},_adjustListWidth:function(){var ak=this.list,al=ak[0].style.width,am=this.options.anchor,ai,aj;
if(!ak.data("width")&&al){return;
}ai=window.getComputedStyle?window.getComputedStyle(am[0],null):0;
aj=ai?parseFloat(ai.width):am.outerWidth();
if(ai&&(t.mozilla||t.msie)){aj+=parseFloat(ai.paddingLeft)+parseFloat(ai.paddingRight)+parseFloat(ai.borderLeftWidth)+parseFloat(ai.borderRightWidth);
}al=aj-(ak.outerWidth()-ak.width());
ak.css({fontFamily:am.css("font-family"),width:al}).data("width",al);
},_popup:function(){var al=this,aj=al.list,ak=al.options,ai=ak.anchor;
al.popup=new af.Popup(aj,B(ak.popup,{anchor:ai,open:ak.open,close:ak.close,animation:ak.animation,isRtl:ab.isRtl(ak.anchor)}));
},move:function(ak){var am=this,al=ak.keyCode,an=am.ul[0],ai=am._current,aj=al===L.DOWN;
if(al===L.UP||aj){if(ak.altKey){am.toggle(aj);
return;
}else{if(aj){ai=ai?ai[0].nextSibling:an.firstChild;
}else{ai=ai?ai[0].previousSibling:an.lastChild;
}}if(ai){am.select(ai);
}am.options.change(am._current.text());
ak.preventDefault();
}else{if(al===L.ENTER||al===L.TAB||al===L.ESC){ak.preventDefault();
if(ai){am.options.change(ai.text(),true);
}am.close();
}}}};
function Y(ai,am,aj){var ak=ai.getTimezoneOffset(),al;
ai.setTime(ai.getTime()+am);
if(!aj){al=ai.getTimezoneOffset()-ak;
ai.setTime(ai.getTime()+al*P);
}}function A(){var ak=new x(),ai=new x(ak.getFullYear(),ak.getMonth(),ak.getDate(),0,0,0),aj=new x(ak.getFullYear(),ak.getMonth(),ak.getDate(),12,0,0);
return -1*(ai.getTimezoneOffset()-aj.getTimezoneOffset());
}function E(ai){return ai.getHours()*60*P+ai.getMinutes()*P+ai.getSeconds()*1000+ai.getMilliseconds();
}function J(an,aj,ai){var al=E(aj),ak=E(ai),am;
if(!an||al==ak){return true;
}am=E(an);
if(al>am){am+=O;
}if(ak<al){ak+=O;
}return am>=al&&am<=ak;
}ad.getMilliseconds=E;
K.TimeView=ad;
var ac=ah.extend({init:function(ak,al){var am=this,ao,an,ai;
ah.fn.init.call(am,ak,al);
ak=am.element;
al=am.options;
al.min=T(ak.attr("min"))||T(al.min);
al.max=T(ak.attr("max"))||T(al.max);
Q(al);
am._initialOptions=B({},al);
am._wrapper();
am.timeView=an=new ad(B({},al,{id:ak.attr(H),anchor:am.wrapper,format:al.format,change:function(aq,ap){if(ap){am._change(aq);
}else{ak.val(aq);
}},open:function(ap){am.timeView._adjustListWidth();
if(am.trigger(S)){ap.preventDefault();
}else{ak.attr(p,true);
ao.attr(q,false);
}},close:function(ap){if(am.trigger(w)){ap.preventDefault();
}else{ak.attr(p,false);
ao.attr(q,true);
}},active:function(ap){ak.removeAttr(n);
if(ap){ak.attr(n,an._optionID);
}}}));
ao=an.ul;
am._icon();
am._reset();
try{ak[0].setAttribute("type","text");
}catch(aj){ak[0].type="text";
}ak.addClass("k-input").attr({role:"combobox","aria-expanded":false,"aria-owns":an._timeViewID});
ai=ak.is("[disabled]")||l(am.element).parents("fieldset").is(":disabled");
if(ai){am.enable(false);
}else{am.readonly(ak.is("[readonly]"));
}am._old=am._update(al.value||am.element.val());
am._oldText=ak.val();
K.notify(am);
},options:{name:"TimePicker",min:ae,max:ae,format:"",dates:[],parseFormats:[],value:null,interval:30,height:200,animation:{}},events:[S,w,u],setOptions:function(ai){var aj=this;
var ak=aj._value;
ah.fn.setOptions.call(aj,ai);
ai=aj.options;
Q(ai);
aj.timeView.setOptions(ai);
if(ak){aj.element.val(K.toString(ak,ai.format,ai.culture));
}},dataBind:function(ai){if(I(ai)){this.timeView.dataBind(ai);
}},_editable:function(al){var an=this,aj=al.disable,am=al.readonly,ai=an._arrow.off(R),ak=an.element.off(R),ao=an._inputWrapper.off(R);
if(!am&&!aj){ao.addClass(y).removeClass(aa).on(G,an._toggleHover);
ak.removeAttr(z).removeAttr(W).attr(o,false).attr(r,false).on("keydown"+R,V(an._keydown,an)).on("focusout"+R,V(an._blur,an)).on("focus"+R,function(){an._inputWrapper.addClass(D);
});
ai.on(v,V(an._click,an)).on(N,U);
}else{ao.addClass(aj?aa:y).removeClass(aj?y:aa);
ak.attr(z,aj).attr(W,am).attr(o,aj).attr(r,am);
}},readonly:function(ai){this._editable({readonly:ai===ag?true:ai,disable:false});
},enable:function(ai){this._editable({readonly:false,disable:!(ai=ai===ag?true:ai)});
},destroy:function(){var ai=this;
ah.fn.destroy.call(ai);
ai.timeView.destroy();
ai.element.off(R);
ai._arrow.off(R);
ai._inputWrapper.off(R);
if(ai._form){ai._form.off("reset",ai._resetHandler);
}},close:function(){this.timeView.close();
},open:function(){this.timeView.open();
},min:function(ai){return this._option("min",ai);
},max:function(ai){return this._option("max",ai);
},value:function(aj){var ai=this;
if(aj===ag){return ai._value;
}ai._old=ai._update(aj);
if(ai._old===null){ai.element.val("");
}ai._oldText=ai.element.val();
},_blur:function(){var ai=this,aj=ai.element.val();
ai.close();
if(aj!==ai._oldText){ai._change(aj);
}ai._inputWrapper.removeClass(D);
},_click:function(){var aj=this,ai=aj.element;
aj.timeView.toggle();
if(!ab.touch&&ai[0]!==m()){ai.focus();
}},_change:function(aj){var ai=this;
aj=ai._update(aj);
if(+ai._old!=+aj){ai._old=aj;
ai._oldText=ai.element.val();
if(!ai._typing){ai.element.trigger(u);
}ai.trigger(u);
}ai._typing=false;
},_icon:function(){var ak=this,aj=ak.element,ai;
ai=aj.next("span.k-select");
if(!ai[0]){ai=l('<span unselectable="on" class="k-select"><span unselectable="on" class="k-icon k-i-clock">select</span></span>').insertAfter(aj);
}ak._arrow=ai.attr({role:"button","aria-controls":ak.timeView._timeViewID});
},_keydown:function(ai){var ak=this,aj=ai.keyCode,al=ak.timeView,am=ak.element.val();
if(al.popup.visible()||ai.altKey){al.move(ai);
}else{if(aj===L.ENTER&&am!==ak._oldText){ak._change(am);
}else{ak._typing=true;
}}},_option:function(ai,al){var ak=this,aj=ak.options;
if(al===ag){return aj[ai];
}al=ak.timeView._parse(al);
if(!al){return;
}al=new x(+al);
aj[ai]=al;
ak.timeView.options[ai]=al;
ak.timeView.bind();
},_toggleHover:function(ai){l(ai.currentTarget).toggleClass(F,ai.type==="mouseenter");
},_update:function(am){var ak=this,aj=ak.options,al=ak.timeView,ai=al._parse(am);
if(!J(ai,aj.min,aj.max)){ai=null;
}ak._value=ai;
ak.element.val(ai?K.toString(ai,aj.format,aj.culture):am);
al.value(ai);
return ai;
},_wrapper:function(){var aj=this,ai=aj.element,ak;
ak=ai.parents(".k-timepicker");
if(!ak[0]){ak=ai.wrap(Z).parent().addClass("k-picker-wrap k-state-default");
ak=ak.wrap(Z).parent();
}ak[0].style.cssText=ai[0].style.cssText;
aj.wrapper=ak.addClass("k-widget k-timepicker k-header").addClass(ai[0].className);
ai.css({width:"100%",height:ai[0].style.height});
aj._inputWrapper=l(ak[0].firstChild);
},_reset:function(){var al=this,ai=al.element,ak=ai.attr("form"),aj=ak?l("#"+ak):ai.closest("form");
if(aj[0]){al._resetHandler=function(){al.value(ai[0].defaultValue);
al.max(al._initialOptions.max);
al.min(al._initialOptions.min);
};
al._form=aj.on("reset",al._resetHandler);
}}});
function Q(ai){var aj=ai.parseFormats;
ai.format=C(ai.format||K.getCulture(ai.culture).calendars.standard.patterns.t);
aj=I(aj)?aj:[aj];
aj.splice(0,0,ai.format);
ai.parseFormats=aj;
}function U(ai){ai.preventDefault();
}af.plugin(ac);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
