(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.tooltip",["kendo.core","kendo.popup"],l);
}(function(){var k={id:"tooltip",name:"Tooltip",category:"web",description:"The Tooltip widget displays a popup hint for a given html element.",depends:["core","popup"]};
(function(l,P){var B=window.kendo,Q=B.ui.Widget,D=B.ui.Popup,x=B.isFunction,z=l.isPlainObject,u=l.extend,F=l.proxy,s=l(document),y=B.isLocalUrl,m="_tt_active",p="aria-describedby",M="show",v="hide",t="error",n="contentLoad",G="requestStart",A="k-content-frame",N='<div role="tooltip" class="k-widget k-tooltip#if (!autoHide) {# k-tooltip-closable#}#">#if (!autoHide) {# <div class="k-tooltip-button"><a href="\\#" class="k-icon k-i-close">close</a></div> #}#<div class="k-tooltip-content"></div>#if (callout){ #<div class="k-callout k-callout-#=dir#"></div>#}#</div>',w=B.template("<iframe frameborder='0' class='"+A+"' src='#= content.url #'>This page requires frames in order to show content</iframe>"),C=".kendoTooltip",E={bottom:{origin:"bottom center",position:"top center"},top:{origin:"top center",position:"bottom center"},left:{origin:"center left",position:"center right",collision:"fit flip"},right:{origin:"center right",position:"center left",collision:"fit flip"},center:{position:"center center",origin:"center center"}},J={top:"bottom",bottom:"top",left:"right",right:"left",center:"center"},r={bottom:"n",top:"s",left:"e",right:"w",center:"n"},q={horizontal:{offset:"top",size:"outerHeight"},vertical:{offset:"left",size:"outerWidth"}},o=function(R){return R.target.data(B.ns+"title");
};
function H(R){while(R.length){I(R);
R=R.parent();
}}function I(R){var S=R.data(B.ns+"title");
if(S){R.attr("title",S);
R.removeData(B.ns+"title");
}}function K(R){var S=R.attr("title");
if(S){R.data(B.ns+"title",S);
R.attr("title","");
}}function L(R){while(R.length&&!R.is("body")){K(R);
R=R.parent();
}}var O=Q.extend({init:function(S,T){var U=this,R;
Q.fn.init.call(U,S,T);
R=U.options.position.match(/left|right/)?"horizontal":"vertical";
U.dimensions=q[R];
U._documentKeyDownHandler=F(U._documentKeyDown,U);
U.element.on(U.options.showOn+C,U.options.filter,F(U._showOn,U)).on("mouseenter"+C,U.options.filter,F(U._mouseenter,U));
if(this.options.autoHide){U.element.on("mouseleave"+C,U.options.filter,F(U._mouseleave,U));
}},options:{name:"Tooltip",filter:"",content:o,showAfter:100,callout:true,position:"bottom",showOn:"mouseenter",autoHide:true,width:null,height:null,animation:{open:{effects:"fade:in",duration:0},close:{effects:"fade:out",duration:40,hide:true}}},events:[M,v,n,t,G],_mouseenter:function(R){L(l(R.currentTarget));
},_showOn:function(S){var T=this;
var R=l(S.currentTarget);
if(T.options.showOn&&T.options.showOn.match(/click|focus/)){T._show(R);
}else{clearTimeout(T.timeout);
T.timeout=setTimeout(function(){T._show(R);
},T.options.showAfter);
}},_appendContent:function(V){var W=this,R=W.options.content,S=W.content,U=W.options.iframe,T;
if(z(R)&&R.url){if(!("iframe" in W.options)){U=!y(R.url);
}W.trigger(G,{options:R,target:V});
if(!U){S.empty();
B.ui.progress(S,true);
W._ajaxRequest(R);
}else{S.hide();
T=S.find("."+A)[0];
if(T){T.src=R.url||T.src;
}else{S.html(w({content:R}));
}S.find("."+A).off("load"+C).on("load"+C,function(){W.trigger(n);
S.show();
});
}}else{if(R&&x(R)){R=R({sender:this,target:V});
S.html(R||"");
}else{S.html(R);
}}W.angular("compile",function(){return{elements:S};
});
},_ajaxRequest:function(R){var S=this;
g.ajax(u({type:"GET",dataType:"html",cache:false,error:function(U,T){B.ui.progress(S.content,false);
S.trigger(t,{status:T,xhr:U});
},success:F(function(T){B.ui.progress(S.content,false);
S.content.html(T);
S.trigger(n);
},S)},R));
},_documentKeyDown:function(R){if(R.keyCode===B.keys.ESC){this.hide();
}},refresh:function(){var S=this,R=S.popup;
if(R&&R.options.anchor){S._appendContent(R.options.anchor);
}},hide:function(){if(this.popup){this.popup.close();
}},show:function(R){R=R||this.element;
L(R);
this._show(R);
},_show:function(S){var T=this,R=T.target();
if(!T.popup){T._initPopup();
}if(R&&R[0]!=S[0]){T.popup.close();
T.popup.element.kendoStop(true,true);
}if(!R||R[0]!=S[0]){T._appendContent(S);
T.popup.options.anchor=S;
}T.popup.one("deactivate",function(){H(S);
S.removeAttr(p);
this.element.removeAttr("id").attr("aria-hidden",true);
s.off("keydown"+C,T._documentKeyDownHandler);
});
T.popup.open();
},_initPopup:function(){var S=this,R=S.options,T=l(B.template(N)({callout:R.callout&&R.position!=="center",dir:r[R.position],autoHide:R.autoHide}));
S.popup=new D(T,u({activate:function(){var U=this.options.anchor,V=U[0].id||S.element[0].id;
if(V){U.attr(p,V+m);
this.element.attr("id",V+m);
}if(R.callout){S._positionCallout();
}this.element.removeAttr("aria-hidden");
s.on("keydown"+C,S._documentKeyDownHandler);
S.trigger(M);
},close:function(){S.trigger(v);
},copyAnchorStyles:false,animation:R.animation},E[R.position]));
T.css({width:R.width,height:R.height});
S.content=T.find(".k-tooltip-content");
S.arrow=T.find(".k-callout");
if(R.autoHide){T.on("mouseleave"+C,F(S._mouseleave,S));
}else{T.on("click"+C,".k-tooltip-button",F(S._closeButtonClick,S));
}},_closeButtonClick:function(R){R.preventDefault();
this.hide();
},_mouseleave:function(R){if(this.popup){var S=l(R.currentTarget),T=S.offset(),U=R.pageX,V=R.pageY;
T.right=T.left+S.outerWidth();
T.bottom=T.top+S.outerHeight();
if(U>T.left&&U<T.right&&V>T.top&&V<T.bottom){return;
}this.popup.close();
}else{H(l(R.currentTarget));
}clearTimeout(this.timeout);
},_positionCallout:function(){var ab=this,aa=ab.options.position,V=ab.dimensions,X=V.offset,Z=ab.popup,R=Z.options.anchor,S=l(R).offset(),T=parseInt(ab.arrow.css("border-top-width"),10),W=l(Z.element).offset(),U=r[Z.flipped?J[aa]:aa],Y=S[X]-W[X]+l(R)[V.size]()/2-T;
ab.arrow.removeClass("k-callout-n k-callout-s k-callout-w k-callout-e").addClass("k-callout-"+U).css(X,Y);
},target:function(){if(this.popup){return this.popup.options.anchor;
}return null;
},destroy:function(){var R=this.popup;
if(R){R.element.off(C);
R.destroy();
}clearTimeout(this.timeout);
this.element.off(C);
s.off("keydown"+C,this._documentKeyDownHandler);
Q.fn.destroy.call(this);
}});
B.ui.plugin(O);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
