(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.touch",["kendo.core","kendo.userevents"],l);
}(function(){var k={id:"touch",name:"Touch",category:"mobile",description:"The kendo Touch widget provides a cross-platform compatible API for handling user-initiated touch events, multi-touch gestures and event sequences (drag, swipe, etc.). ",depends:["core","userevents"]};
(function(l,r){var n=window.kendo,s=n.ui.Widget,p=l.proxy,m=Math.abs,o=20;
var q=s.extend({init:function(t,w){var x=this;
s.fn.init.call(x,t,w);
w=x.options;
t=x.element;
x.wrapper=t;
function u(y){return function(z){x._triggerTouch(y,z);
};
}function v(y){return function(z){x.trigger(y,{touches:z.touches,distance:z.distance,center:z.center,event:z.event});
};
}x.events=new n.UserEvents(t,{filter:w.filter,surface:w.surface,minHold:w.minHold,multiTouch:w.multiTouch,allowSelection:true,fastTap:w.fastTap,press:u("touchstart"),hold:u("hold"),tap:p(x,"_tap"),gesturestart:v("gesturestart"),gesturechange:v("gesturechange"),gestureend:v("gestureend")});
if(w.enableSwipe){x.events.bind("start",p(x,"_swipestart"));
x.events.bind("move",p(x,"_swipemove"));
}else{x.events.bind("start",p(x,"_dragstart"));
x.events.bind("move",u("drag"));
x.events.bind("end",u("dragend"));
}n.notify(x);
},events:["touchstart","dragstart","drag","dragend","tap","doubletap","hold","swipe","gesturestart","gesturechange","gestureend"],options:{name:"Touch",surface:null,global:false,fastTap:false,multiTouch:false,enableSwipe:false,minXDelta:30,maxYDelta:20,maxDuration:1000,minHold:800,doubleTapTimeout:800},cancel:function(){this.events.cancel();
},_triggerTouch:function(u,t){if(this.trigger(u,{touch:t.touch,event:t.event})){t.preventDefault();
}},_tap:function(t){var v=this,u=v.lastTap,w=t.touch;
if(u&&w.endTime-u.endTime<v.options.doubleTapTimeout&&n.touchDelta(w,u).distance<o){v._triggerTouch("doubletap",t);
v.lastTap=null;
}else{v._triggerTouch("tap",t);
v.lastTap=w;
}},_dragstart:function(t){this._triggerTouch("dragstart",t);
},_swipestart:function(t){if(m(t.x.velocity)*2>=m(t.y.velocity)){t.sender.capture();
}},_swipemove:function(v){var x=this,w=x.options,y=v.touch,u=v.event.timeStamp-y.startTime,t=y.x.initialDelta>0?"right":"left";
if(m(y.x.initialDelta)>=w.minXDelta&&m(y.y.initialDelta)<w.maxYDelta&&u<w.maxDuration){x.trigger("swipe",{direction:t,touch:v.touch});
y.cancel();
}}});
n.ui.plugin(q);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
