(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("kendo.userevents",["kendo.core"],l);
}(function(){var k={id:"userevents",name:"User Events",category:"framework",depends:["core"],hidden:true};
(function(l,Q){var B=window.kendo,K=B.support,q=window.document,n=B.Class,E=B.Observable,D=l.now,t=l.extend,F=K.mobileOS,A=F&&F.android,o=800,p=K.browser.msie?5:0,G="press",z="hold",I="select",J="start",C="move",s="end",m="cancel",L="tap",H="release",w="gesturestart",u="gesturechange",v="gestureend",x="gesturetap";
var M={api:0,touch:0,mouse:9,pointer:9};
var r=!K.touch||K.mouseAndTouchPresent;
function P(V,W){var X=V.x.location,Z=V.y.location,Y=W.x.location,aa=W.y.location,T=X-Y,U=Z-aa;
return{center:{x:(X+Y)/2,y:(Z+aa)/2},distance:Math.sqrt(T*T+U*U)};
}function y(V){var aa=[],Y=V.originalEvent,U=V.currentTarget,W=0,X,T,Z;
if(V.api){aa.push({id:2,event:V,target:V.target,currentTarget:V.target,location:V,type:"api"});
}else{if(V.type.match(/touch/)){T=Y?Y.changedTouches:[];
for(X=T.length;
W<X;
W++){Z=T[W];
aa.push({location:Z,event:V,target:Z.target,currentTarget:U,id:Z.identifier,type:"touch"});
}}else{if(K.pointers||K.msPointers){aa.push({location:Y,event:V,target:V.target,currentTarget:U,id:Y.pointerId,type:"pointer"});
}else{aa.push({id:1,event:V,target:V.target,currentTarget:U,location:V,type:"mouse"});
}}}return aa;
}var O=n.extend({init:function(T,U){var V=this;
V.axis=T;
V._updateLocationData(U);
V.startLocation=V.location;
V.velocity=V.delta=0;
V.timeStamp=D();
},move:function(T){var V=this,U=T["page"+V.axis],X=D(),W=X-V.timeStamp||1;
if(!U&&A){return;
}V.delta=U-V.location;
V._updateLocationData(T);
V.initialDelta=U-V.startLocation;
V.velocity=V.delta/W;
V.timeStamp=X;
},_updateLocationData:function(U){var V=this,T=V.axis;
V.location=U["page"+T];
V.client=U["client"+T];
V.screen=U["screen"+T];
}});
var N=n.extend({init:function(V,T,U){t(this,{x:new O("X",U.location),y:new O("Y",U.location),type:U.type,useClickAsTap:V.useClickAsTap,threshold:V.threshold||M[U.type],userEvents:V,target:T,currentTarget:U.currentTarget,initialTouch:U.target,id:U.id,pressEvent:U,_moved:false,_finished:false});
},press:function(){this._holdTimeout=setTimeout(l.proxy(this,"_hold"),this.userEvents.minHold);
this._trigger(G,this.pressEvent);
},_hold:function(){this._trigger(z,this.pressEvent);
},move:function(U){var T=this;
if(T._finished){return;
}T.x.move(U.location);
T.y.move(U.location);
if(!T._moved){if(T._withinIgnoreThreshold()){return;
}if(!R.current||R.current===T.userEvents){T._start(U);
}else{return T.dispose();
}}if(!T._finished){T._trigger(C,U);
}},end:function(T){this.endTime=D();
if(this._finished){return;
}this._finished=true;
this._trigger(H,T);
if(this._moved){this._trigger(s,T);
}else{if(!this.useClickAsTap){this._trigger(L,T);
}}clearTimeout(this._holdTimeout);
this.dispose();
},dispose:function(){var U=this.userEvents,T=U.touches;
this._finished=true;
this.pressEvent=null;
clearTimeout(this._holdTimeout);
T.splice(l.inArray(this,T),1);
},skip:function(){this.dispose();
},cancel:function(){this.dispose();
},isMoved:function(){return this._moved;
},_start:function(T){clearTimeout(this._holdTimeout);
this.startTime=D();
this._moved=true;
this._trigger(J,T);
},_trigger:function(V,X){var W=this,U=X.event,T={touch:W,x:W.x,y:W.y,target:W.target,event:U};
if(W.userEvents.notify(V,T)){U.preventDefault();
}},_withinIgnoreThreshold:function(){var T=this.x.initialDelta,U=this.y.initialDelta;
return Math.sqrt(T*T+U*U)<=this.threshold;
}});
function S(T){var U=B.eventMap.up.split(" "),V=0,W=U.length;
for(;
V<W;
V++){T(U[V]);
}}var R=E.extend({init:function(T,W){var Z=this,U,V=B.guid();
W=W||{};
U=Z.filter=W.filter;
Z.threshold=W.threshold||p;
Z.minHold=W.minHold||o;
Z.touches=[];
Z._maxTouches=W.multiTouch?2:1;
Z.allowSelection=W.allowSelection;
Z.captureUpIfMoved=W.captureUpIfMoved;
Z.useClickAsTap=!W.fastTap&&!K.delayedClick();
Z.eventNS=V;
T=l(T).handler(Z);
E.fn.init.call(Z);
t(Z,{element:T,surface:W.global&&r?l(q.documentElement):l(W.surface||T),stopPropagation:W.stopPropagation,pressed:false});
Z.surface.handler(Z).on(B.applyEventMap("move",V),"_move").on(B.applyEventMap("up cancel",V),"_end");
T.on(B.applyEventMap("down",V),U,"_start");
if(Z.useClickAsTap){T.on(B.applyEventMap("click",V),U,"_click");
}if(K.pointers||K.msPointers){if(K.browser.version<11){T.css("-ms-touch-action","pinch-zoom double-tap-zoom");
}else{T.css("touch-action","pan-y");
}}if(W.preventDragEvent){T.on(B.applyEventMap("dragstart",V),B.preventDefault);
}T.on(B.applyEventMap("mousedown",V),U,{root:T},"_select");
if(Z.captureUpIfMoved&&K.eventCapture){var Y=Z.surface[0],X=l.proxy(Z.preventIfMoving,Z);
S(function(aa){Y.addEventListener(aa,X,true);
});
}Z.bind([G,z,L,J,C,s,H,m,w,u,v,x,I],W);
},preventIfMoving:function(T){if(this._isMoved()){T.preventDefault();
}},destroy:function(){var U=this;
if(U._destroyed){return;
}U._destroyed=true;
if(U.captureUpIfMoved&&K.eventCapture){var T=U.surface[0];
S(function(V){T.removeEventListener(V,U.preventIfMoving);
});
}U.element.kendoDestroy(U.eventNS);
U.surface.kendoDestroy(U.eventNS);
U.element.removeData("handler");
U.surface.removeData("handler");
U._disposeAll();
U.unbind();
delete U.surface;
delete U.element;
delete U.currentTarget;
},capture:function(){R.current=this;
},cancel:function(){this._disposeAll();
this.trigger(m);
},notify:function(U,T){var V=this,W=V.touches;
if(this._isMultiTouch()){switch(U){case C:U=u;
break;
case s:U=v;
break;
case L:U=x;
break;
}t(T,{touches:W},P(W[0],W[1]));
}return this.trigger(U,t(T,{type:U}));
},press:function(U,V,T){this._apiCall("_start",U,V,T);
},move:function(T,U){this._apiCall("_move",T,U);
},end:function(T,U){this._apiCall("_end",T,U);
},_isMultiTouch:function(){return this.touches.length>1;
},_maxTouchesReached:function(){return this.touches.length>=this._maxTouches;
},_disposeAll:function(){var T=this.touches;
while(T.length>0){T.pop().dispose();
}},_isMoved:function(){return l.grep(this.touches,function(T){return T.isMoved();
}).length;
},_select:function(T){if(!this.allowSelection||this.trigger(I,{event:T})){T.preventDefault();
}},_start:function(T){var Y=this,V=0,U=Y.filter,X,aa=y(T),W=aa.length,Z,ab=T.which;
if(ab&&ab>1||Y._maxTouchesReached()){return;
}R.current=null;
Y.currentTarget=T.currentTarget;
if(Y.stopPropagation){T.stopPropagation();
}for(;
V<W;
V++){if(Y._maxTouchesReached()){break;
}Z=aa[V];
if(U){X=l(Z.currentTarget);
}else{X=Y.element;
}if(!X.length){continue;
}Z=new N(Y,X,Z);
Y.touches.push(Z);
Z.press();
if(Y._isMultiTouch()){Y.notify("gesturestart",{});
}}},_move:function(T){this._eachTouch("move",T);
},_end:function(T){this._eachTouch("end",T);
},_click:function(U){var T={touch:{initialTouch:U.target,target:l(U.currentTarget),endTime:D(),x:{location:U.pageX,client:U.clientX},y:{location:U.pageY,client:U.clientY}},x:U.pageX,y:U.pageY,target:l(U.currentTarget),event:U,type:"tap"};
if(this.trigger("tap",T)){U.preventDefault();
}},_eachTouch:function(Y,V){var Z=this,U={},ab=y(V),T=Z.touches,W,aa,ac,X;
for(W=0;
W<T.length;
W++){aa=T[W];
U[aa.id]=aa;
}for(W=0;
W<ab.length;
W++){ac=ab[W];
X=U[ac.id];
if(X){X[Y](ac);
}}},_apiCall:function(U,V,W,T){this[U]({api:true,pageX:V,pageY:W,clientX:V,clientY:W,target:l(T||this.element)[0],stopPropagation:l.noop,preventDefault:l.noop});
}});
R.defaultThreshold=function(T){p=T;
};
R.minHold=function(T){o=T;
};
B.getTouches=y;
B.touchDelta=P;
B.UserEvents=R;
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
