namespace HouseOfSynergy.PowerTools.Library.Attributes
{
	public class ByteSignedFieldAttribute:
		HouseOfSynergy.PowerTools.Library.Attributes.Int16FieldAttribute
	{
		public new sbyte Minimum { get; private set; }

		public new sbyte Maximum { get; private set; }

		public ByteSignedFieldAttribute
		(
			System.Type Type,
			int Ordinal,
			string Name,
			string Description,
			string Label,
			string Tooltip,
			bool Required,
			bool ReadOnly,
			bool AutoGenerated,
			sbyte Minimum,
			sbyte Maximum
		)
			: base(Type, Ordinal, Name, Description, Label, Tooltip, Required, ReadOnly, AutoGenerated, Minimum, Maximum)
		{
			this.Minimum = Minimum;
			this.Maximum = Maximum;
		}
	}
}