namespace HouseOfSynergy.PowerTools.Library.Attributes
{
	public class Int32FieldAttribute:
		HouseOfSynergy.PowerTools.Library.Attributes.Int64FieldAttribute
	{
		public new int Minimum { get; private set; }

		public new int Maximum { get; private set; }

		public Int32FieldAttribute
		(
			System.Type Type,
			int Ordinal,
			string Name,
			string Description,
			string Label,
			string Tooltip,
			bool Required,
			bool ReadOnly,
			bool AutoGenerated,
			int Minimum,
			int Maximum
		)
			: base(Type, Ordinal, Name, Description, Label, Tooltip, Required, ReadOnly, AutoGenerated, Minimum, Maximum)
		{
			this.Minimum = Minimum;
			this.Maximum = Maximum;
		}
	}
}