(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.themes",["kendo.dataviz.core"],l);
}(function(){var k={id:"dataviz.themes",name:"Themes",description:"Built-in themes for the DataViz widgets",category:"dataviz",depends:["dataviz.core"],hidden:true};
(function(l){var u=window.kendo,B=u.dataviz.ui,q=u.deepExtend;
var m=1.5,n=0.4,o="#000",w="Arial,Helvetica,sans-serif",x="11px "+w,y="12px "+w,z="16px "+w,C="#fff";
var p={title:{font:z},legend:{labels:{font:y}},seriesDefaults:{visible:true,labels:{font:x},donut:{margin:1},line:{width:2},vericalLine:{width:2},scatterLine:{width:1},area:{opacity:0.4,markers:{visible:false,size:6},highlight:{markers:{border:{color:"#fff",opacity:1,width:1}}},line:{opacity:1,width:0}},verticalArea:{opacity:0.4,markers:{visible:false,size:6},line:{opacity:1,width:0}},radarLine:{width:2,markers:{visible:false}},radarArea:{opacity:0.5,markers:{visible:false,size:6},line:{opacity:1,width:0}},candlestick:{line:{width:1,color:o},border:{width:1,_brightness:0.8},gap:1,spacing:0.3,downColor:C,highlight:{line:{width:2},border:{width:2,opacity:1}}},ohlc:{line:{width:1},gap:1,spacing:0.3,highlight:{line:{width:3,opacity:1}}},bubble:{opacity:0.6,border:{width:0},labels:{background:"transparent"}},bar:{gap:m,spacing:n},column:{gap:m,spacing:n},rangeColumn:{gap:m,spacing:n},rangeBar:{gap:m,spacing:n},waterfall:{gap:0.5,spacing:n,line:{width:1,color:o}},horizontalWaterfall:{gap:0.5,spacing:n,line:{width:1,color:o}},bullet:{gap:m,spacing:n,target:{color:"#ff0000"}},verticalBullet:{gap:m,spacing:n,target:{color:"#ff0000"}},boxPlot:{outliersField:"",meanField:"",whiskers:{width:1,color:o},mean:{width:1,color:o},median:{width:1,color:o},border:{width:1,_brightness:0.8},gap:1,spacing:0.3,downColor:C,highlight:{whiskers:{width:2},border:{width:2,opacity:1}}},funnel:{labels:{color:"",background:""}},notes:{icon:{border:{width:1}},label:{padding:3,font:y},line:{length:10,width:1},visible:true}},categoryAxis:{majorGridLines:{visible:true}},axisDefaults:{labels:{font:y},title:{font:z,margin:5},crosshair:{tooltip:{font:y}},notes:{icon:{size:7,border:{width:1}},label:{padding:3,font:y},line:{length:10,width:1},visible:true}},tooltip:{font:y},navigator:{pane:{height:90,margin:{top:10}}}};
var t={scale:{labels:{font:y}}};
var r={shapeDefaults:{hover:{opacity:0.2},stroke:{width:0}},editable:{resize:{handles:{width:7,height:7}}},selectable:{stroke:{width:1,dashType:"dot"}},connectionDefaults:{stroke:{width:2},selection:{handles:{width:8,height:8}},editable:{tools:["edit","delete"]}}};
var A=B.themes,v=B.registerTheme=function(G,E){var F={};
F.chart=q({},p,E.chart);
F.gauge=q({},t,E.gauge);
F.diagram=q({},r,E.diagram);
F.treeMap=q({},E.treeMap);
var D=F.chart.seriesDefaults;
D.verticalLine=q({},D.line);
D.verticalArea=q({},D.area);
D.polarArea=q({},D.radarArea);
D.polarLine=q({},D.radarLine);
A[G]=F;
};
v("black",{chart:{title:{color:C},legend:{labels:{color:C},inactiveItems:{labels:{color:"#919191"},markers:{color:"#919191"}}},seriesDefaults:{labels:{color:C},errorBars:{color:C},notes:{icon:{background:"#3b3b3b",border:{color:"#8e8e8e"}},label:{color:C},line:{color:"#8e8e8e"}},pie:{overlay:{gradient:"sharpBevel"}},donut:{overlay:{gradient:"sharpGlass"}},line:{markers:{background:"#3d3d3d"}},scatter:{markers:{background:"#3d3d3d"}},scatterLine:{markers:{background:"#3d3d3d"}},waterfall:{line:{color:"#8e8e8e"}},horizontalWaterfall:{line:{color:"#8e8e8e"}},candlestick:{downColor:"#555",line:{color:C},border:{_brightness:1.5,opacity:1},highlight:{border:{color:C,opacity:0.2}}},ohlc:{line:{color:C}}},chartArea:{background:"#3d3d3d"},seriesColors:["#0081da","#3aafff","#99c900","#ffeb3d","#b20753","#ff4195"],axisDefaults:{line:{color:"#8e8e8e"},labels:{color:C},majorGridLines:{color:"#545454"},minorGridLines:{color:"#454545"},title:{color:C},crosshair:{color:"#8e8e8e"},notes:{icon:{background:"#3b3b3b",border:{color:"#8e8e8e"}},label:{color:C},line:{color:"#8e8e8e"}}}},gauge:{pointer:{color:"#0070e4"},scale:{rangePlaceholderColor:"#1d1d1d",labels:{color:C},minorTicks:{color:C},majorTicks:{color:C},line:{color:C}}},diagram:{shapeDefaults:{fill:{color:"#0066cc"},connectorDefaults:{fill:{color:C},stroke:{color:"#384049"},hover:{fill:{color:"#3d3d3d"},stroke:{color:"#efefef"}}},content:{color:C}},editable:{resize:{handles:{fill:{color:"#3d3d3d"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:C}}}},rotate:{thumb:{stroke:{color:C},fill:{color:C}}}},selectable:{stroke:{color:C}},connectionDefaults:{stroke:{color:C},content:{color:C},selection:{handles:{fill:{color:"#3d3d3d"},stroke:{color:"#efefef"}}}}},treeMap:{colors:[["#0081da","#314b5c"],["#3aafff","#3c5464"],["#99c900","#4f5931"],["#ffeb3d","#64603d"],["#b20753","#543241"],["#ff4195","#643e4f"]]}});
v("blueopal",{chart:{title:{color:"#293135"},legend:{labels:{color:"#293135"},inactiveItems:{labels:{color:"#27A5BA"},markers:{color:"#27A5BA"}}},seriesDefaults:{labels:{color:o,background:C,opacity:0.5},errorBars:{color:"#293135"},candlestick:{downColor:"#c4d0d5",line:{color:"#9aabb2"}},waterfall:{line:{color:"#9aabb2"}},horizontalWaterfall:{line:{color:"#9aabb2"}},notes:{icon:{background:"transparent",border:{color:"#9aabb2"}},label:{color:"#293135"},line:{color:"#9aabb2"}}},seriesColors:["#0069a5","#0098ee","#7bd2f6","#ffb800","#ff8517","#e34a00"],axisDefaults:{line:{color:"#9aabb2"},labels:{color:"#293135"},majorGridLines:{color:"#c4d0d5"},minorGridLines:{color:"#edf1f2"},title:{color:"#293135"},crosshair:{color:"#9aabb2"},notes:{icon:{background:"transparent",border:{color:"#9aabb2"}},label:{color:"#293135"},line:{color:"#9aabb2"}}}},gauge:{pointer:{color:"#005c83"},scale:{rangePlaceholderColor:"#daecf4",labels:{color:"#293135"},minorTicks:{color:"#293135"},majorTicks:{color:"#293135"},line:{color:"#293135"}}},diagram:{shapeDefaults:{fill:{color:"#7ec6e3"},connectorDefaults:{fill:{color:"#003f59"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#003f59"}}},content:{color:"#293135"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#003f59"},hover:{fill:{color:"#003f59"},stroke:{color:"#003f59"}}}},rotate:{thumb:{stroke:{color:"#003f59"},fill:{color:"#003f59"}}}},selectable:{stroke:{color:"#003f59"}},connectionDefaults:{stroke:{color:"#003f59"},content:{color:"#293135"},selection:{handles:{fill:{color:"#3d3d3d"},stroke:{color:"#efefef"}}}}},treeMap:{colors:[["#0069a5","#bad7e7"],["#0098ee","#b9e0f5"],["#7bd2f6","#ceeaf6"],["#ffb800","#e6e3c4"],["#ff8517","#e4d8c8"],["#e34a00","#ddccc2"]]}});
v("highcontrast",{chart:{title:{color:"#ffffff"},legend:{labels:{color:"#ffffff"},inactiveItems:{labels:{color:"#66465B"},markers:{color:"#66465B"}}},seriesDefaults:{labels:{color:"#ffffff"},errorBars:{color:"#ffffff"},notes:{icon:{background:"transparent",border:{color:"#ffffff"}},label:{color:"#ffffff"},line:{color:"#ffffff"}},pie:{overlay:{gradient:"sharpGlass"}},donut:{overlay:{gradient:"sharpGlass"}},line:{markers:{background:"#2c232b"}},scatter:{markers:{background:"#2c232b"}},scatterLine:{markers:{background:"#2c232b"}},area:{opacity:0.5},waterfall:{line:{color:"#ffffff"}},horizontalWaterfall:{line:{color:"#ffffff"}},candlestick:{downColor:"#664e62",line:{color:"#ffffff"},border:{_brightness:1.5,opacity:1},highlight:{border:{color:"#ffffff",opacity:1}}},ohlc:{line:{color:"#ffffff"}}},chartArea:{background:"#2c232b"},seriesColors:["#a7008f","#ffb800","#3aafff","#99c900","#b20753","#ff4195"],axisDefaults:{line:{color:"#ffffff"},labels:{color:"#ffffff"},majorGridLines:{color:"#664e62"},minorGridLines:{color:"#4f394b"},title:{color:"#ffffff"},crosshair:{color:"#ffffff"},notes:{icon:{background:"transparent",border:{color:"#ffffff"}},label:{color:"#ffffff"},line:{color:"#ffffff"}}}},gauge:{pointer:{color:"#a7008f"},scale:{rangePlaceholderColor:"#2c232b",labels:{color:"#ffffff"},minorTicks:{color:"#2c232b"},majorTicks:{color:"#664e62"},line:{color:"#ffffff"}}},diagram:{shapeDefaults:{fill:{color:"#a7018f"},connectorDefaults:{fill:{color:C},stroke:{color:"#2c232b"},hover:{fill:{color:"#2c232b"},stroke:{color:C}}},content:{color:C}},editable:{resize:{handles:{fill:{color:"#2c232b"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:C}}}},rotate:{thumb:{stroke:{color:C},fill:{color:C}}}},selectable:{stroke:{color:C}},connectionDefaults:{stroke:{color:C},content:{color:C},selection:{handles:{fill:{color:"#2c232b"},stroke:{color:C}}}}},treeMap:{colors:[["#a7008f","#451c3f"],["#ffb800","#564122"],["#3aafff","#2f3f55"],["#99c900","#424422"],["#b20753","#471d33"],["#ff4195","#562940"]]}});
v("default",{chart:{title:{color:"#8e8e8e"},legend:{labels:{color:"#232323"},inactiveItems:{labels:{color:"#919191"},markers:{color:"#919191"}}},seriesDefaults:{labels:{color:o,background:C,opacity:0.5},errorBars:{color:"#232323"},candlestick:{downColor:"#dedede",line:{color:"#8d8d8d"}},waterfall:{line:{color:"#8e8e8e"}},horizontalWaterfall:{line:{color:"#8e8e8e"}},notes:{icon:{background:"transparent",border:{color:"#8e8e8e"}},label:{color:"#232323"},line:{color:"#8e8e8e"}}},seriesColors:["#ff6800","#a0a700","#ff8d00","#678900","#ffb53c","#396000"],axisDefaults:{line:{color:"#8e8e8e"},labels:{color:"#232323"},minorGridLines:{color:"#f0f0f0"},majorGridLines:{color:"#dfdfdf"},title:{color:"#232323"},crosshair:{color:"#8e8e8e"},notes:{icon:{background:"transparent",border:{color:"#8e8e8e"}},label:{color:"#232323"},line:{color:"#8e8e8e"}}}},gauge:{pointer:{color:"#ea7001"},scale:{rangePlaceholderColor:"#dedede",labels:{color:"#2e2e2e"},minorTicks:{color:"#2e2e2e"},majorTicks:{color:"#2e2e2e"},line:{color:"#2e2e2e"}}},diagram:{shapeDefaults:{fill:{color:"#e15613"},connectorDefaults:{fill:{color:"#282828"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#282828"}}},content:{color:"#2e2e2e"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#282828"},hover:{fill:{color:"#282828"},stroke:{color:"#282828"}}}},rotate:{thumb:{stroke:{color:"#282828"},fill:{color:"#282828"}}}},selectable:{stroke:{color:"#a7018f"}},connectionDefaults:{stroke:{color:"#282828"},content:{color:"#2e2e2e"},selection:{handles:{fill:{color:C},stroke:{color:"#282828"}}}}},treeMap:{colors:[["#ff6800","#edcfba"],["#a0a700","#dadcba"],["#ff8d00","#edd7ba"],["#678900","#cfd6ba"],["#ffb53c","#eddfc6"],["#396000","#c6ceba"]]}});
v("silver",{chart:{title:{color:"#4e5968"},legend:{labels:{color:"#4e5968"},inactiveItems:{labels:{color:"#B1BCC8"},markers:{color:"#B1BCC8"}}},seriesDefaults:{labels:{color:"#293135",background:"#eaeaec",opacity:0.5},errorBars:{color:"#4e5968"},notes:{icon:{background:"transparent",border:{color:"#4e5968"}},label:{color:"#4e5968"},line:{color:"#4e5968"}},line:{markers:{background:"#eaeaec"}},scatter:{markers:{background:"#eaeaec"}},scatterLine:{markers:{background:"#eaeaec"}},pie:{connectors:{color:"#A6B1C0"}},donut:{connectors:{color:"#A6B1C0"}},waterfall:{line:{color:"#a6b1c0"}},horizontalWaterfall:{line:{color:"#a6b1c0"}},candlestick:{downColor:"#a6afbe"}},chartArea:{background:"#eaeaec"},seriesColors:["#007bc3","#76b800","#ffae00","#ef4c00","#a419b7","#430B62"],axisDefaults:{line:{color:"#a6b1c0"},labels:{color:"#4e5968"},majorGridLines:{color:"#dcdcdf"},minorGridLines:{color:"#eeeeef"},title:{color:"#4e5968"},crosshair:{color:"#a6b1c0"},notes:{icon:{background:"transparent",border:{color:"#4e5968"}},label:{color:"#4e5968"},line:{color:"#4e5968"}}}},gauge:{pointer:{color:"#0879c0"},scale:{rangePlaceholderColor:"#f3f3f4",labels:{color:"#515967"},minorTicks:{color:"#515967"},majorTicks:{color:"#515967"},line:{color:"#515967"}}},diagram:{shapeDefaults:{fill:{color:"#1c82c2"},connectorDefaults:{fill:{color:"#515967"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#282828"}}},content:{color:"#515967"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#515967"},hover:{fill:{color:"#515967"},stroke:{color:"#515967"}}}},rotate:{thumb:{stroke:{color:"#515967"},fill:{color:"#515967"}}}},selectable:{stroke:{color:"#515967"}},connectionDefaults:{stroke:{color:"#515967"},content:{color:"#515967"},selection:{handles:{fill:{color:C},stroke:{color:"#515967"}}}}},treeMap:{colors:[["#007bc3","#c2dbea"],["#76b800","#dae7c3"],["#ffae00","#f5e5c3"],["#ef4c00","#f2d2c3"],["#a419b7","#e3c7e8"],["#430b62","#d0c5d7"]]}});
v("metro",{chart:{title:{color:"#777777"},legend:{labels:{color:"#777777"},inactiveItems:{labels:{color:"#CBCBCB"},markers:{color:"#CBCBCB"}}},seriesDefaults:{labels:{color:o},errorBars:{color:"#777777"},notes:{icon:{background:"transparent",border:{color:"#777777"}},label:{color:"#777777"},line:{color:"#777777"}},candlestick:{downColor:"#c7c7c7",line:{color:"#787878"}},waterfall:{line:{color:"#c7c7c7"}},horizontalWaterfall:{line:{color:"#c7c7c7"}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:["#8ebc00","#309b46","#25a0da","#ff6900","#e61e26","#d8e404","#16aba9","#7e51a1","#313131","#ed1691"],axisDefaults:{line:{color:"#c7c7c7"},labels:{color:"#777777"},minorGridLines:{color:"#c7c7c7"},majorGridLines:{color:"#c7c7c7"},title:{color:"#777777"},crosshair:{color:"#c7c7c7"},notes:{icon:{background:"transparent",border:{color:"#777777"}},label:{color:"#777777"},line:{color:"#777777"}}}},gauge:{pointer:{color:"#8ebc00"},scale:{rangePlaceholderColor:"#e6e6e6",labels:{color:"#777"},minorTicks:{color:"#777"},majorTicks:{color:"#777"},line:{color:"#777"}}},diagram:{shapeDefaults:{fill:{color:"#8ebc00"},connectorDefaults:{fill:{color:o},stroke:{color:C},hover:{fill:{color:C},stroke:{color:o}}},content:{color:"#777"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#787878"},hover:{fill:{color:"#787878"},stroke:{color:"#787878"}}}},rotate:{thumb:{stroke:{color:"#787878"},fill:{color:"#787878"}}}},selectable:{stroke:{color:"#515967"}},connectionDefaults:{stroke:{color:"#787878"},content:{color:"#777"},selection:{handles:{fill:{color:C},stroke:{color:"#787878"}}}}},treeMap:{colors:[["#8ebc00","#e8f2cc"],["#309b46","#d6ebda"],["#25a0da","#d3ecf8"],["#ff6900","#ffe1cc"],["#e61e26","#fad2d4"],["#d8e404","#f7facd"],["#16aba9","#d0eeee"],["#7e51a1","#e5dcec"],["#313131","#d6d6d6"],["#ed1691","#fbd0e9"]]}});
v("metroblack",{chart:{title:{color:"#ffffff"},legend:{labels:{color:"#ffffff"},inactiveItems:{labels:{color:"#797979"},markers:{color:"#797979"}}},seriesDefaults:{border:{_brightness:1},labels:{color:"#ffffff"},errorBars:{color:"#ffffff"},notes:{icon:{background:"transparent",border:{color:"#cecece"}},label:{color:"#ffffff"},line:{color:"#cecece"}},line:{markers:{background:"#0e0e0e"}},bubble:{opacity:0.6},scatter:{markers:{background:"#0e0e0e"}},scatterLine:{markers:{background:"#0e0e0e"}},candlestick:{downColor:"#828282",line:{color:"#ffffff"}},waterfall:{line:{color:"#cecece"}},horizontalWaterfall:{line:{color:"#cecece"}},overlay:{gradient:"none"}},chartArea:{background:"#0e0e0e"},seriesColors:["#00aba9","#309b46","#8ebc00","#ff6900","#e61e26","#d8e404","#25a0da","#7e51a1","#313131","#ed1691"],axisDefaults:{line:{color:"#cecece"},labels:{color:"#ffffff"},minorGridLines:{color:"#2d2d2d"},majorGridLines:{color:"#333333"},title:{color:"#ffffff"},crosshair:{color:"#cecece"},notes:{icon:{background:"transparent",border:{color:"#cecece"}},label:{color:"#ffffff"},line:{color:"#cecece"}}}},gauge:{pointer:{color:"#00aba9"},scale:{rangePlaceholderColor:"#2d2d2d",labels:{color:"#ffffff"},minorTicks:{color:"#333333"},majorTicks:{color:"#cecece"},line:{color:"#cecece"}}},diagram:{shapeDefaults:{fill:{color:"#00aba9"},connectorDefaults:{fill:{color:C},stroke:{color:"#0e0e0e"},hover:{fill:{color:"#0e0e0e"},stroke:{color:C}}},content:{color:C}},editable:{resize:{handles:{fill:{color:"#0e0e0e"},stroke:{color:"#787878"},hover:{fill:{color:"#787878"},stroke:{color:"#787878"}}}},rotate:{thumb:{stroke:{color:C},fill:{color:C}}}},selectable:{stroke:{color:"#787878"}},connectionDefaults:{stroke:{color:C},content:{color:C},selection:{handles:{fill:{color:"#0e0e0e"},stroke:{color:C}}}}},treeMap:{colors:[["#00aba9","#0b2d2d"],["#309b46","#152a19"],["#8ebc00","#28310b"],["#ff6900","#3e200b"],["#e61e26","#391113"],["#d8e404","#36390c"],["#25a0da","#132b37"],["#7e51a1","#241b2b"],["#313131","#151515"],["#ed1691","#3b1028"]]}});
v("moonlight",{chart:{title:{color:"#ffffff"},legend:{labels:{color:"#ffffff"},inactiveItems:{labels:{color:"#A1A7AB"},markers:{color:"#A1A7AB"}}},seriesDefaults:{labels:{color:"#ffffff"},errorBars:{color:"#ffffff"},notes:{icon:{background:"transparent",border:{color:"#8c909e"}},label:{color:"#ffffff"},line:{color:"#8c909e"}},pie:{overlay:{gradient:"sharpBevel"}},donut:{overlay:{gradient:"sharpGlass"}},line:{markers:{background:"#212a33"}},bubble:{opacity:0.6},scatter:{markers:{background:"#212a33"}},scatterLine:{markers:{background:"#212a33"}},area:{opacity:0.3},candlestick:{downColor:"#757d87",line:{color:"#ea9d06"},border:{_brightness:1.5,opacity:1},highlight:{border:{color:C,opacity:0.2}}},waterfall:{line:{color:"#8c909e"}},horizontalWaterfall:{line:{color:"#8c909e"}},ohlc:{line:{color:"#ea9d06"}}},chartArea:{background:"#212a33"},seriesColors:["#ffca08","#ff710f","#ed2e24","#ff9f03","#e13c02","#a00201"],axisDefaults:{line:{color:"#8c909e"},minorTicks:{color:"#8c909e"},majorTicks:{color:"#8c909e"},labels:{color:"#ffffff"},majorGridLines:{color:"#3e424d"},minorGridLines:{color:"#2f3640"},title:{color:"#ffffff"},crosshair:{color:"#8c909e"},notes:{icon:{background:"transparent",border:{color:"#8c909e"}},label:{color:"#ffffff"},line:{color:"#8c909e"}}}},gauge:{pointer:{color:"#f4af03"},scale:{rangePlaceholderColor:"#2f3640",labels:{color:C},minorTicks:{color:"#8c909e"},majorTicks:{color:"#8c909e"},line:{color:"#8c909e"}}},diagram:{shapeDefaults:{fill:{color:"#f3ae03"},connectorDefaults:{fill:{color:C},stroke:{color:"#414550"},hover:{fill:{color:"#414550"},stroke:{color:C}}},content:{color:C}},editable:{resize:{handles:{fill:{color:"#414550"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:C}}}},rotate:{thumb:{stroke:{color:C},fill:{color:C}}}},selectable:{stroke:{color:C}},connectionDefaults:{stroke:{color:C},content:{color:C},selection:{handles:{fill:{color:"#414550"},stroke:{color:C}}}}},treeMap:{colors:[["#ffca08","#4e4b2b"],["#ff710f","#4e392d"],["#ed2e24","#4b2c31"],["#ff9f03","#4e422a"],["#e13c02","#482e2a"],["#a00201","#3b232a"]]}});
v("uniform",{chart:{title:{color:"#686868"},legend:{labels:{color:"#686868"},inactiveItems:{labels:{color:"#B6B6B6"},markers:{color:"#B6B6B6"}}},seriesDefaults:{labels:{color:"#686868"},errorBars:{color:"#686868"},notes:{icon:{background:"transparent",border:{color:"#9e9e9e"}},label:{color:"#686868"},line:{color:"#9e9e9e"}},pie:{overlay:{gradient:"sharpBevel"}},donut:{overlay:{gradient:"sharpGlass"}},line:{markers:{background:"#ffffff"}},bubble:{opacity:0.6},scatter:{markers:{background:"#ffffff"}},scatterLine:{markers:{background:"#ffffff"}},area:{opacity:0.3},candlestick:{downColor:"#cccccc",line:{color:"#cccccc"},border:{_brightness:1.5,opacity:1},highlight:{border:{color:"#cccccc",opacity:0.2}}},waterfall:{line:{color:"#9e9e9e"}},horizontalWaterfall:{line:{color:"#9e9e9e"}},ohlc:{line:{color:"#cccccc"}}},chartArea:{background:"#ffffff"},seriesColors:["#527aa3","#6f91b3","#8ca7c2","#a8bdd1","#c5d3e0","#e2e9f0"],axisDefaults:{line:{color:"#9e9e9e"},minorTicks:{color:"#aaaaaa"},majorTicks:{color:"#888888"},labels:{color:"#686868"},majorGridLines:{color:"#dadada"},minorGridLines:{color:"#e7e7e7"},title:{color:"#686868"},crosshair:{color:"#9e9e9e"},notes:{icon:{background:"transparent",border:{color:"#9e9e9e"}},label:{color:"#686868"},line:{color:"#9e9e9e"}}}},gauge:{pointer:{color:"#527aa3"},scale:{rangePlaceholderColor:"#e7e7e7",labels:{color:"#686868"},minorTicks:{color:"#aaaaaa"},majorTicks:{color:"#888888"},line:{color:"#9e9e9e"}}},diagram:{shapeDefaults:{fill:{color:"#d1d1d1"},connectorDefaults:{fill:{color:"#686868"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#686868"}}},content:{color:"#686868"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#686868"},hover:{fill:{color:"#686868"},stroke:{color:"#686868"}}}},rotate:{thumb:{stroke:{color:"#686868"},fill:{color:"#686868"}}}},selectable:{stroke:{color:"#686868"}},connectionDefaults:{stroke:{color:"#686868"},content:{color:"#686868"},selection:{handles:{fill:{color:C},stroke:{color:"#686868"}}}}},treeMap:{colors:[["#527aa3","#d0d8e1"],["#6f91b3","#d6dde4"],["#8ca7c2","#dce1e7"],["#a8bdd1","#e2e6ea"],["#c5d3e0","#e7eaed"],["#e2e9f0","#edeff0"]]}});
v("bootstrap",{chart:{title:{color:"#333333"},legend:{labels:{color:"#333333"},inactiveItems:{labels:{color:"#999999"},markers:{color:"#9A9A9A"}}},seriesDefaults:{labels:{color:"#333333"},overlay:{gradient:"none"},errorBars:{color:"#343434"},notes:{icon:{background:"#000000",border:{color:"#000000"}},label:{color:"#333333"},line:{color:"#000000"}},pie:{overlay:{gradient:"none"}},donut:{overlay:{gradient:"none"}},line:{markers:{background:"#ffffff"}},bubble:{opacity:0.6},scatter:{markers:{background:"#ffffff"}},scatterLine:{markers:{background:"#ffffff"}},area:{opacity:0.8},candlestick:{downColor:"#d0d0d0",line:{color:"#333333"},border:{_brightness:1.5,opacity:1},highlight:{border:{color:"#b8b8b8",opacity:0.2}}},waterfall:{line:{color:"#cccccc"}},horizontalWaterfall:{line:{color:"#cccccc"}},ohlc:{line:{color:"#333333"}}},chartArea:{background:"#ffffff"},seriesColors:["#428bca","#5bc0de","#5cb85c","#f2b661","#e67d4a","#da3b36"],axisDefaults:{line:{color:"#cccccc"},minorTicks:{color:"#ebebeb"},majorTicks:{color:"#cccccc"},labels:{color:"#333333"},majorGridLines:{color:"#cccccc"},minorGridLines:{color:"#ebebeb"},title:{color:"#333333"},crosshair:{color:"#000000"},notes:{icon:{background:"#000000",border:{color:"#000000"}},label:{color:"#ffffff"},line:{color:"#000000"}}}},gauge:{pointer:{color:"#428bca"},scale:{rangePlaceholderColor:"#cccccc",labels:{color:"#333333"},minorTicks:{color:"#ebebeb"},majorTicks:{color:"#cccccc"},line:{color:"#cccccc"}}},diagram:{shapeDefaults:{fill:{color:"#428bca"},connectorDefaults:{fill:{color:"#333333"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#333333"}}},content:{color:"#333333"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#333333"},hover:{fill:{color:"#333333"},stroke:{color:"#333333"}}}},rotate:{thumb:{stroke:{color:"#333333"},fill:{color:"#333333"}}}},selectable:{stroke:{color:"#333333"}},connectionDefaults:{stroke:{color:"#c4c4c4"},content:{color:"#333333"},selection:{handles:{fill:{color:C},stroke:{color:"#333333"}},stroke:{color:"#333333"}}}},treeMap:{colors:[["#428bca","#d1e0ec"],["#5bc0de","#d6eaf0"],["#5cb85c","#d6e9d6"],["#5cb85c","#f4e8d7"],["#e67d4a","#f2ddd3"],["#da3b36","#f0d0cf"]]}});
v("flat",{chart:{title:{color:"#4c5356"},legend:{labels:{color:"#4c5356"},inactiveItems:{labels:{color:"#CBCBCB"},markers:{color:"#CBCBCB"}}},seriesDefaults:{labels:{color:"#4c5356"},errorBars:{color:"#4c5356"},notes:{icon:{background:"transparent",border:{color:"#cdcdcd"}},label:{color:"#4c5356"},line:{color:"#cdcdcd"}},candlestick:{downColor:"#c7c7c7",line:{color:"#787878"}},area:{opacity:0.9},waterfall:{line:{color:"#cdcdcd"}},horizontalWaterfall:{line:{color:"#cdcdcd"}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:["#10c4b2","#ff7663","#ffb74f","#a2df53","#1c9ec4","#ff63a5","#1cc47b"],axisDefaults:{line:{color:"#cdcdcd"},labels:{color:"#4c5356"},minorGridLines:{color:"#cdcdcd"},majorGridLines:{color:"#cdcdcd"},title:{color:"#4c5356"},crosshair:{color:"#cdcdcd"},notes:{icon:{background:"transparent",border:{color:"#cdcdcd"}},label:{color:"#4c5356"},line:{color:"#cdcdcd"}}}},gauge:{pointer:{color:"#10c4b2"},scale:{rangePlaceholderColor:"#cdcdcd",labels:{color:"#4c5356"},minorTicks:{color:"#4c5356"},majorTicks:{color:"#4c5356"},line:{color:"#4c5356"}}},diagram:{shapeDefaults:{fill:{color:"#10c4b2"},connectorDefaults:{fill:{color:"#363940"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#363940"}}},content:{color:"#4c5356"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#363940"},hover:{fill:{color:"#363940"},stroke:{color:"#363940"}}}},rotate:{thumb:{stroke:{color:"#363940"},fill:{color:"#363940"}}}},selectable:{stroke:{color:"#363940"}},connectionDefaults:{stroke:{color:"#cdcdcd"},content:{color:"#4c5356"},selection:{handles:{fill:{color:C},stroke:{color:"#363940"}},stroke:{color:"#363940"}}}},treeMap:{colors:[["#10c4b2","#cff3f0"],["#ff7663","#ffe4e0"],["#ffb74f","#fff1dc"],["#a2df53","#ecf9dd"],["#1c9ec4","#d2ecf3"],["#ff63a5","#ffe0ed"],["#1cc47b","#d2f3e5"]]}});
v("material",{chart:{title:{color:"#444444"},legend:{labels:{color:"#444444"},inactiveItems:{labels:{color:"#CBCBCB"},markers:{color:"#CBCBCB"}}},seriesDefaults:{labels:{color:"#444444"},errorBars:{color:"#444444"},notes:{icon:{background:"transparent",border:{color:"#e5e5e5"}},label:{color:"#444444"},line:{color:"#e5e5e5"}},candlestick:{downColor:"#c7c7c7",line:{color:"#787878"}},area:{opacity:0.9},waterfall:{line:{color:"#e5e5e5"}},horizontalWaterfall:{line:{color:"#e5e5e5"}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:["#3f51b5","#03a9f4","#4caf50","#f9ce1d","#ff9800","#ff5722"],axisDefaults:{line:{color:"#e5e5e5"},labels:{color:"#444444"},minorGridLines:{color:"#e5e5e5"},majorGridLines:{color:"#e5e5e5"},title:{color:"#444444"},crosshair:{color:"#7f7f7f"},notes:{icon:{background:"transparent",border:{color:"#e5e5e5"}},label:{color:"#444444"},line:{color:"#e5e5e5"}}}},gauge:{pointer:{color:"#3f51b5"},scale:{rangePlaceholderColor:"#e5e5e5",labels:{color:"#444444"},minorTicks:{color:"#444444"},majorTicks:{color:"#444444"},line:{color:"#444444"}}},diagram:{shapeDefaults:{fill:{color:"#3f51b5"},connectorDefaults:{fill:{color:"#7f7f7f"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#7f7f7f"}}},content:{color:"#444444"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#444444"},hover:{fill:{color:"#444444"},stroke:{color:"#444444"}}}},rotate:{thumb:{stroke:{color:"#444444"},fill:{color:"#444444"}}}},selectable:{stroke:{color:"#444444"}},connectionDefaults:{stroke:{color:"#7f7f7f"},content:{color:"#444444"},selection:{handles:{fill:{color:C},stroke:{color:"#444444"}},stroke:{color:"#444444"}}}},treeMap:{colors:[["#3f51b5","#cff3f0"],["#03a9f4","#e5f6fe"],["#4caf50","#edf7ed"],["#f9ce1d","#fefae8"],["#ff9800","#fff4e5"],["#ff5722","#ffeee8"]]}});
v("materialblack",{chart:{title:{color:"#fff"},legend:{labels:{color:"#fff"},inactiveItems:{labels:{color:"#CBCBCB"},markers:{color:"#CBCBCB"}}},seriesDefaults:{labels:{color:"#fff"},errorBars:{color:"#fff"},notes:{icon:{background:"transparent",border:{color:"#e5e5e5"}},label:{color:"#fff"},line:{color:"#e5e5e5"}},candlestick:{downColor:"#c7c7c7",line:{color:"#787878"}},area:{opacity:0.9},waterfall:{line:{color:"#4d4d4d"}},horizontalWaterfall:{line:{color:"#4d4d4d"}},overlay:{gradient:"none"},border:{_brightness:1}},chartArea:{background:"#1c1c1c"},seriesColors:["#3f51b5","#03a9f4","#4caf50","#f9ce1d","#ff9800","#ff5722"],axisDefaults:{line:{color:"#4d4d4d"},labels:{color:"#fff"},minorGridLines:{color:"#4d4d4d"},majorGridLines:{color:"#4d4d4d"},title:{color:"#fff"},crosshair:{color:"#7f7f7f"},notes:{icon:{background:"transparent",border:{color:"#4d4d4d"}},label:{color:"#fff"},line:{color:"#4d4d4d"}}}},gauge:{pointer:{color:"#3f51b5"},scale:{rangePlaceholderColor:"#4d4d4d",labels:{color:"#fff"},minorTicks:{color:"#fff"},majorTicks:{color:"#fff"},line:{color:"#fff"}}},diagram:{shapeDefaults:{fill:{color:"#3f51b5"},connectorDefaults:{fill:{color:"#7f7f7f"},stroke:{color:C},hover:{fill:{color:C},stroke:{color:"#7f7f7f"}}},content:{color:"#fff"}},editable:{resize:{handles:{fill:{color:C},stroke:{color:"#fff"},hover:{fill:{color:"#fff"},stroke:{color:"#fff"}}}},rotate:{thumb:{stroke:{color:"#fff"},fill:{color:"#fff"}}}},selectable:{stroke:{color:"#fff"}},connectionDefaults:{stroke:{color:"#7f7f7f"},content:{color:"#fff"},selection:{handles:{fill:{color:C},stroke:{color:"#fff"}},stroke:{color:"#fff"}}}},treeMap:{colors:[["#3f51b5","#cff3f0"],["#03a9f4","#e5f6fe"],["#4caf50","#edf7ed"],["#f9ce1d","#fefae8"],["#ff9800","#fff4e5"],["#ff5722","#ffeee8"]]}});
(function(){var M="#333333";
var G="#7f7f7f";
var H="#bdbdbd";
var D="#c8c8c8";
var E="#dddddd";
var K=["#008fd3","#99d101","#f39b02","#f05662","#c03c53","#acacac"];
var L=["#cbe8f5","#eaf5cb","#fceacc","#fbdcdf","#f2d7dc","#eeeeee"];
var J=K[0];
var F=C;
function I(){return{icon:{background:"#007cc0",border:{color:"#007cc0"}},label:{color:"#ffffff"},line:{color:D}};
}v("fiori",{chart:{title:{color:M},legend:{labels:{color:M},inactiveItems:{labels:{color:G},markers:{color:G}}},seriesDefaults:{labels:{color:M},errorBars:{color:M},notes:I(),candlestick:{downColor:D,line:{color:H}},area:{opacity:0.8},waterfall:{line:{color:D}},horizontalWaterfall:{line:{color:D}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:K,axisDefaults:{line:{color:D},labels:{color:M},minorGridLines:{color:E},majorGridLines:{color:D},title:{color:M},crosshair:{color:G},notes:I()}},gauge:{pointer:{color:J},scale:{rangePlaceholderColor:D,labels:{color:M},minorTicks:{color:M},majorTicks:{color:M},line:{color:M}}},diagram:{shapeDefaults:{fill:{color:J},connectorDefaults:{fill:{color:M},stroke:{color:F},hover:{fill:{color:F},stroke:{color:M}}},content:{color:M}},editable:{resize:{handles:{fill:{color:F},stroke:{color:H},hover:{fill:{color:H},stroke:{color:H}}}},rotate:{thumb:{stroke:{color:H},fill:{color:H}}}},selectable:{stroke:{color:H}},connectionDefaults:{stroke:{color:H},content:{color:H},selection:{handles:{fill:{color:F},stroke:{color:H}},stroke:{color:H}}}},treeMap:{colors:s(K,L)}});
}());
(function(){var M="#4e4e4e";
var G="#7f7f7f";
var H="#bdbdbd";
var D="#c8c8c8";
var E="#e5e5e5";
var K=["#0072c6","#5db2ff","#008a17","#82ba00","#ff8f32","#ac193d"];
var L=["#cbe2f3","#deeffe","#cbe7d0","#e5f0cb","#fee8d5","#eed0d7"];
var J=K[0];
var F=C;
function I(){return{icon:{background:"#00b0ff",border:{color:"#00b0ff"}},label:{color:"#ffffff"},line:{color:D}};
}v("office365",{chart:{title:{color:M},legend:{labels:{color:M},inactiveItems:{labels:{color:G},markers:{color:G}}},seriesDefaults:{labels:{color:M},errorBars:{color:M},notes:I(),candlestick:{downColor:D,line:{color:H}},area:{opacity:0.8},waterfall:{line:{color:D}},horizontalWaterfall:{line:{color:D}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:K,axisDefaults:{line:{color:D},labels:{color:M},minorGridLines:{color:E},majorGridLines:{color:D},title:{color:M},crosshair:{color:G},notes:I()}},gauge:{pointer:{color:J},scale:{rangePlaceholderColor:D,labels:{color:M},minorTicks:{color:M},majorTicks:{color:M},line:{color:M}}},diagram:{shapeDefaults:{fill:{color:J},connectorDefaults:{fill:{color:M},stroke:{color:F},hover:{fill:{color:F},stroke:{color:M}}},content:{color:M}},editable:{resize:{handles:{fill:{color:F},stroke:{color:H},hover:{fill:{color:H},stroke:{color:H}}}},rotate:{thumb:{stroke:{color:H},fill:{color:H}}}},selectable:{stroke:{color:H}},connectionDefaults:{stroke:{color:H},content:{color:H},selection:{handles:{fill:{color:F},stroke:{color:H}},stroke:{color:H}}}},treeMap:{colors:s(K,L)}});
}());
(function(){var M="#32364c";
var G="#7f7f7f";
var H="#bdbdbd";
var D="#dfe0e1";
var E="#dfe0e1";
var K=["#ff4350","#ff9ea5","#00acc1","#80deea","#ffbf46","#ffd78c"];
var L=["#ffd9dc","#ffeced","#cceef3","#e6f8fb","#fff2da","#fff7e8"];
var J=K[0];
var F=C;
function I(){return{icon:{background:"#007cc0",border:{color:"#007cc0"}},label:{color:"#ffffff"},line:{color:D}};
}v("nova",{chart:{title:{color:M},legend:{labels:{color:M},inactiveItems:{labels:{color:G},markers:{color:G}}},seriesDefaults:{labels:{color:M},errorBars:{color:M},notes:I(),candlestick:{downColor:D,line:{color:H}},area:{opacity:0.8},waterfall:{line:{color:D}},horizontalWaterfall:{line:{color:D}},overlay:{gradient:"none"},border:{_brightness:1}},seriesColors:K,axisDefaults:{line:{color:D},labels:{color:M},minorGridLines:{color:E},majorGridLines:{color:D},title:{color:M},crosshair:{color:M},notes:I()}},gauge:{pointer:{color:J},scale:{rangePlaceholderColor:D,labels:{color:M},minorTicks:{color:M},majorTicks:{color:M},line:{color:M}}},diagram:{shapeDefaults:{fill:{color:J},connectorDefaults:{fill:{color:M},stroke:{color:F},hover:{fill:{color:F},stroke:{color:M}}},content:{color:M}},editable:{resize:{handles:{fill:{color:F},stroke:{color:H},hover:{fill:{color:H},stroke:{color:H}}}},rotate:{thumb:{stroke:{color:H},fill:{color:H}}}},selectable:{stroke:{color:H}},connectionDefaults:{stroke:{color:H},content:{color:H},selection:{handles:{fill:{color:F},stroke:{color:H}},stroke:{color:H}}}},treeMap:{colors:s(K,L)}});
}());
function s(D,E){return l.map(D,function(G,F){return[[G,E[F]]];
});
}}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
