Type.registerNamespace("Telerik.Web");
(function(){$telerik.toRating=function(e){return e;
};
$telerik.findRating=$find;
var a=Telerik.Web.UI;
var c=function(f,e){a[f]=function(){var g=Array.prototype.slice.call(arguments);
a[f].initializeBase(this,g);
};
a[f].registerClass("Telerik.Web.UI."+f,e);
};
a.RatingPrecision=function(){};
a.RatingPrecision.prototype={Item:0,Half:1,Exact:2};
a.RatingPrecision.registerEnum("Telerik.Web.UI.RatingPrecision");
a.RatingSelectionMode=function(){};
a.RatingSelectionMode.prototype={Single:0,Continuous:1};
a.RatingSelectionMode.registerEnum("Telerik.Web.UI.RatingSelectionMode");
a.RatingRatingEventArgs=function(e){a.RatingRatingEventArgs.initializeBase(this);
this._newValue=e;
};
a.RatingRatingEventArgs.prototype={get_newValue:function(){return this._newValue;
}};
a.RatingRatingEventArgs.registerClass("Telerik.Web.UI.RatingRatingEventArgs",Sys.CancelEventArgs);
c("RadRatingRatingEventArgs",Telerik.Web.UI.RatingRatingEventArgs);
a.RatingRatedEventArgs=function(e){a.RatingRatedEventArgs.initializeBase(this);
this._oldValue=e;
};
a.RatingRatedEventArgs.prototype={get_oldValue:function(){return this._oldValue;
}};
a.RatingRatedEventArgs.registerClass("Telerik.Web.UI.RatingRatedEventArgs",Sys.EventArgs);
c("RadRatingRatedEventArgs",Telerik.Web.UI.RatingRatedEventArgs);
a.RadRating=function(e){a.RadRating.initializeBase(this,[e]);
this._itemCount=5;
this._value=0;
this._doubleValue="0";
this._selectionMode=a.RatingSelectionMode.Continuous;
this._precision=a.RatingPrecision.Item;
this._orientation=a.Orientation.Horizontal;
this._isDirectionReversed=false;
this._enableToolTips=true;
this._autoPostBack=false;
this._readOnly=false;
this._enabled=true;
this._uniqueID=null;
this._preInitializeComplete=false;
this._ulWrapper=null;
this._items=[];
this._itemData=[];
this._definedItems=false;
this._itemWidth="";
this._itemHeight="";
this._documentMouseMoveDelegate=null;
this._selectedItemCssClass="rrtSelected";
this._hoveredItemCssClass="rrtOver";
this._clearSelectedStateOnHover=false;
};
a.RadRating.prototype={initialize:function(){if(!this._preInitializeComplete){a.RadRating._preInitialize(this.get_id(),this._orientation);
}a.RadRating.callBaseMethod(this,"initialize");
$telerik.$(".tm",this.get_element()).remove().contents().insertBefore(this.get_element());
var f=this._ulWrapper=$telerik.getFirstChildByTagName(this.get_element(),"ul",0);
this._decorateListWrapper();
this._createItemData();
this._enableRatingControl(!this._readOnly&&this._enabled);
$addHandler(f,"click",this._cancelEvent);
this._synchronizeUIWithValue(this._value,true);
this.get_element().value=this._doubleValue;
var e=this;
setTimeout(function(){e._requestItemsHoverImages();
},0);
this.raiseEvent("load");
if(!this.canRepaint()){this.add_parentShown(this.get_element());
}},dispose:function(){this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
$clearHandlers(this._ulWrapper);
this._ulWrapper=null;
this._items=null;
this._itemData=[];
a.RadRating.callBaseMethod(this,"dispose");
},repaint:function(){a.RadRating._preInitialize(this.get_id(),this._orientation);
var e=this._value;
this._clearSelection(e);
this._synchronizeUIWithValue(e);
},_decorateListWrapper:function(){if($telerik.isMobileSafari){$telerik.$(this._ulWrapper).addClass("_Telerik_MobileSafari");
}},_getMainEventHandlers:function(){return $telerik.isTouchDevice?{mouseup:this._mouseUpTouchDevice}:{mouseover:this._mouseOver,mouseup:this._mouseUp,mouseout:this._mouseOut};
},_createItemData:function(){var k=this._isDirectionReversed,j,r;
var n=this._items=$telerik.getChildrenByTagName(this._ulWrapper,"li");
if(k){var s=[];
for(j=(n.length-1);
j>=0;
j--){s[s.length]=n[j];
}n=this._items=s;
}var p=0;
var o=0;
var l=this._itemData;
var f=this._definedItems=(l&&l.length>0);
for(j=0,r=n.length;
j<r;
j++){var e;
if(!f){e={value:(j+1)};
}else{e=l[j];
var w={};
var t={};
if(!e.imageUrl){e.imageUrl="";
}else{w.url="url("+e.imageUrl+")";
}if(!e.selectedImageUrl){e.selectedImageUrl=e.imageUrl;
}if(e.selectedImageUrl){t.url="url("+e.selectedImageUrl+")";
}if(e.imageUrl||e.selectedImageUrl){p++;
}var g=e.hoveredImageUrl;
var h=e.hoveredSelectedImageUrl;
if(g||h){e.hoveredImageUrl=g?g:h;
e.hoveredSelectedImageUrl=h?h:g;
o++;
}else{e.hoveredImageUrl=e.selectedImageUrl;
e.hoveredSelectedImageUrl=e.selectedImageUrl;
}if(e.hoveredImageUrl){w.hoveredUrl="url("+e.hoveredImageUrl+")";
}if(e.hoveredSelectedImageUrl){t.hoveredUrl="url("+e.hoveredSelectedImageUrl+")";
}e.item=(k?t:w);
e.itemSpan=(k?w:t);
}e.index=j;
e.itemElement=n[j];
l[j]=e;
}if(f&&o==0&&p>0){this._clearSelectedStateOnHover=true;
}var q=this._itemWidth;
var v=(""!=q);
q=parseInt(q,10)+"px";
var m=this._itemHeight;
var u=(""!=m);
m=parseInt(m,10)+"px";
if(a.Orientation.Horizontal==this._orientation){if(v){n.itemSpanWidth=k?q:"0px";
n.itemSpanSelectedWidth=k?"0px":q;
if(u){n.itemPartsStaticSize=m;
}}}else{if(u){n.itemSpanHeight=k?m:"0px";
n.itemSpanSelectedHeight=k?"0px":m;
if(v){n.itemPartsStaticSize=q;
}}}},_requestItemsHoverImages:function(){var j=this._itemData;
for(var h=0,k=j.length;
h<k;
h++){var e=j[h];
var g=e.hoveredImageUrl;
if(g!=e.selectedImageUrl){this._requestImage(g);
var f=e.hoveredSelectedImageUrl;
if(f!=g){this._requestImage(f);
}}}},_requestImage:function(e){var f=document.createElement("img");
f.setAttribute("src",e);
f.setAttribute("alt","");
f.setAttribute("class","rrtHiddenImages");
this.get_element().appendChild(f);
},_getItem:function(e){for(var f=0;
f<3&&e!==this._ulWrapper;
f++,e=e.parentNode){if("li"==e.tagName.toLowerCase()){return e;
}}return null;
},_getItemA:function(f){var e=f.getElementsByTagName("a");
if(e&&e.length>0){return e[0];
}return null;
},_getItemSpan:function(e){var f=e.getElementsByTagName("span");
if(f&&f.length>0){return f[0];
}return null;
},_getItemData:function(g){var h=this._itemData;
for(var f=0,j=h.length;
f<j;
f++){var e=h[f];
if(e.itemElement===g){return e;
}}},_getItemValue:function(f,e){var g=this._getItemData(f).value;
if(a.RatingPrecision.Item!=this._precision){g-=1;
g+=this._getFraction(f,e);
}if(!isNaN(g)){return g;
}return 0;
},_getItemByValue:function(j){j=Math.ceil(j);
var g=this._itemData;
for(var f=0,h=g.length;
f<h;
f++){var e=g[f];
if(e.value===j){return e.itemElement;
}}},_getItemIndexByValue:function(j){j=Math.ceil(j);
var g=this._itemData;
for(var f=0,h=g.length;
f<h;
f++){var e=g[f];
if(e.value===j){return e.index;
}}},_getItemIndex:function(f){var e=this._getItemData(f).index;
if(!isNaN(e)){return e;
}return -1;
},_getFraction:function(g,e){if(!g){return;
}var f=0;
var m=(a.Orientation.Horizontal==this._orientation?"width":"height");
var h=$telerik.getSize(this._getItemA(g))[m];
var i=this._overPartItem;
var j=this._overPartItemComplement;
if(e&&i&&j){var l=$telerik.getSize(i)[m];
var k=$telerik.getSize(j)[m];
f=Math.max(l,k);
if(0==f&&Sys.UI.DomElement.containsCssClass(g,this._hoveredItemCssClass)){return 1;
}}else{f=$telerik.getSize(this._getItemSpan(g))[m];
if(this._isDirectionReversed){f=h-f;
}}return this._calculateFraction(f,h);
},_calculateFraction:function(e,f){return d(e/f);
},_markContinuousHovered:function(e){if(this._selectionMode!=a.RatingSelectionMode.Continuous){return;
}var h=this._items;
for(var f=0,j=h.length;
f<j;
f++){var g=h[f];
if(e===g){break;
}this._markItemHovered(g);
}},_markItemHovered:function(h){Sys.UI.DomElement.addCssClass(h,this._hoveredItemCssClass);
var g=this._getItemData(h);
var j=g.itemSpan;
if(j&&j.hoveredUrl){var i=this._getItemSpan(h);
i.style.backgroundImage=j.hoveredUrl;
}var f=g.item;
if(f&&f.hoveredUrl){var e=this._getItemA(h);
e.style.backgroundImage=f.hoveredUrl;
}},_clearOverState:function(e){var h=(a.RatingSelectionMode.Continuous==this._selectionMode);
var k=this._items;
var f=e?this._getItemIndex(e):null;
for(var g=(k.length-1);
g>=0;
g--){var j=k[g];
if(h&&f!=null&&(f>this._getItemIndex(j))){return;
}this._clearItemOverState(j);
}},_clearItemOverState:function(h){Sys.UI.DomElement.removeCssClass(h,this._hoveredItemCssClass);
var g=this._getItemData(h);
var j=g.itemSpan;
if(j&&j.url){var i=this._getItemSpan(h);
i.style.backgroundImage=j.url;
}var f=g.item;
if(f&&f.url){var e=this._getItemA(h);
e.style.backgroundImage=f.url;
}},_markContinuousSelected:function(e){var h=this._items;
var k=h.itemSpanSelectedWidth;
var j=h.itemSpanSelectedHeight;
this._markItemSelected(e,k,j);
if(a.RatingSelectionMode.Continuous!=this._selectionMode){return;
}for(var f=0,l=h.length;
f<l;
f++){var g=h[f];
if(e===g){break;
}this._markItemSelected(g,k,j);
}},_markItemSelected:function(e,g,f){Sys.UI.DomElement.addCssClass(e,this._selectedItemCssClass);
this._setItemSize(e,g,f);
},_clearSelection:function(o){var f=(a.RatingSelectionMode.Continuous==this._selectionMode);
var j=this._items;
var l=j.itemSpanWidth;
var k=j.itemSpanHeight;
var n=this._getItemIndexByValue(o);
var m=this._getItemIndexByValue(this._value);
for(var e=m;
e>=0;
e--){var g=j[e];
if(m==e){this._clearPart(g);
}var h=this._getItemIndex(g);
if(n!=null&&((f&&n>h)||(n==h))){return;
}this._clearItemSelectedState(g,l,k);
}},_clearItemSelectedState:function(e,g,f){Sys.UI.DomElement.removeCssClass(e,this._selectedItemCssClass);
this._setItemSize(e,g,f);
},_setItemSize:function(e,g,f){var h=this._getItemSpan(e);
if(g){h.style.width=g;
}if(f){h.style.height=f;
}},_clearPart:function(e,f){var h=this._getItemSpan(e);
if(!h){return;
}var g=f?(f.toString()+"px"):"";
h.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=g;
},_updateHoveredItem:function(i){this._mouseOut(i,true);
var k=this._hoveredItem;
var q=this._overPartItem;
var r=this._overPartItemComplement;
if(!k||!q||!r){return;
}var o=$telerik.getDocumentRelativeCursorPosition(i)[this._locationProperty];
var w=o-this._ulLocation;
w=Math.min(this._maxMousePosition,Math.max(0,w));
w%=this._itemOuterSize;
w-=this._positionOffset;
this._clearItemOverState(k);
var p=this._getOverPartsSize(w,k);
var v=p.partSize;
var t=p.partComplementSize;
var x=this._sizeProperty;
var g=parseInt(q.style[x],10);
if(isNaN(g)||g<1){q.style[x]="1px";
}var f=parseInt(r.style[x],10);
if(isNaN(g)||f<1){r.style[x]="1px";
}var j=(a.Orientation.Horizontal==this._orientation);
if(this._isDirectionReversed){var n=this._marginProperty;
var m=this._itemSize;
var y=this._spanSize;
var u=m-v-(j?0:y);
q.style[n]=u.toString()+"px";
var s=m-t-(j?0:(y+u+v));
r.style[n]=s.toString()+"px";
}else{if(!j){q.style.marginTop=(-t).toString()+"px";
}}q.style[x]=v.toString()+"px";
r.style[x]=t.toString()+"px";
this._updateHoveredItemPartsImages(k);
if(this._enableToolTips){var h=this._getItemData(k);
if(!h.tooltip){var l=this._getItemA(k);
l.title=this._getItemValue(k,true);
}}},_updateHoveredItemPartsImages:function(h){var f=this._isDirectionReversed?"right bottom":"left top";
var g=this._getItemData(h);
var k=g.itemSpan;
var j=this._overPartItem.style;
if(k&&k.hoveredUrl){j.backgroundImage=k.hoveredUrl;
j.backgroundPosition=f;
}else{if(j.backgroundPosition){this._clearBackgroundPosition(j);
}}var e=g.item;
var i=this._overPartItemComplement.style;
if(e&&e.hoveredUrl){i.backgroundImage=e.hoveredUrl;
i.backgroundPosition=f;
}else{if(i.backgroundPosition){this._clearBackgroundPosition(i);
}}},_clearBackgroundPosition:function(e){if(e.removeAttribute){e.removeAttribute("backgroundPosition");
}else{e.removeProperty("backgroundPosition");
}},_getOverPartsSize:function(n,j){var h=this.get_renderMode()==a.RenderMode.Lite;
var i=this._isDirectionReversed;
var k=this._itemSize;
var f=this._itemHalfSize;
var o=this._precision;
var g=(a.RatingPrecision.Half==o);
var m=0;
var l=0;
if(((a.RatingPrecision.Exact==o)&&(n<0||n>=k))||(g&&((!i&&n>f)||(i&&n<=f)))){if((!i&&n>=0)||(i&&n<k)){this._markItemHovered(j);
}}else{var q=this._spanSize;
if(i){if(h){var e=k-q;
if(n>e){if(g){l=f;
}else{l=k-n;
}}else{if(g){m=f;
}else{l=q;
m=k-n;
}}}else{if(n>q){l=g?f:(k-n);
if(g&&(q>f)){m=f;
l=(k-q);
}}else{m=g?f:(k-n);
l=k-q;
}}}else{if((n>q)||(g&&(q<f))){m=q;
l=g?f:n;
}else{m=g?f:n;
}}}var p={partSize:((m<0)?0:m),partComplementSize:((l<0)?0:l)};
return p;
},_createPartElements:function(j){var f=this._overPartItem;
var g=this._overPartItemComplement;
if(j){if(!f){f=document.createElement("span");
f.className="rrtPart";
g=document.createElement("span");
g.className="rrtPartComplement";
var h=this._items.itemPartsStaticSize;
if(h){var i=(a.Orientation.Horizontal==this._orientation)?"height":"width";
f.style[i]=h;
g.style[i]=h;
var e="-"+h;
f.style.marginTop=e;
g.style.marginTop=e;
}this._overPartItem=f;
this._overPartItemComplement=g;
}}else{if(f&&g){f.parentNode.removeChild(f);
this._overPartItem=null;
g.parentNode.removeChild(g);
this._overPartItemComplement=null;
}}},_storeStartCoords:function(j){if(j){var f=(a.Orientation.Horizontal==this._orientation);
var g=this._items[0];
var e=this._getItemA(g);
var k=this._ulWrapper;
var h=this._locationProperty=f?"left":"top";
var i=this._sizeProperty=f?"width":"height";
this._marginProperty=f?"marginLeft":"marginTop";
this._ulLocation=$telerik.getLocation(k)[f?"x":"y"]+($telerik.getMarginBox(k)[h]+$telerik.getBorderBox(k)[h]+$telerik.getPaddingBox(k)[h]);
this._itemOuterSize=$telerik.getOuterSize(g)[i];
this._itemSize=$telerik.getSize(e)[i];
this._itemHalfSize=parseFloat(this._itemSize/2,10);
this._positionOffset=$telerik.getMarginBox(e)[h]+$telerik.getBorderBox(e)[h];
this._maxMousePosition=(this._itemOuterSize*this._itemCount)-1;
}else{this._locationProperty=null;
this._sizeProperty=null;
this._marginProperty=null;
this._ulLocation=null;
this._itemOuterSize=null;
this._itemSize=null;
this._itemHalfSize=null;
this._positionOffset=null;
this._maxMousePosition=null;
}},_attachDocumentHandlers:function(e){if(true==e){this._documentMouseMoveDelegate=Function.createDelegate(this,this._updateHoveredItem);
$telerik.addExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
}else{if(this._documentMouseMoveDelegate){$telerik.removeExternalHandler(document,"mousemove",this._documentMouseMoveDelegate);
this._documentMouseMoveDelegate=null;
}}},_attachDisabledHandlers:function(e){var f=$telerik.$(this.get_element()).find("a");
if(e){f.on("focus",b);
}else{f.off("focus",b);
}},_getFractionSize:function(m,u){var p=this._overPartItem;
var q=this._overPartItemComplement;
if(!(p&&q)&&typeof(u)=="undefined"){return 0;
}var k=this.get_renderMode()==a.RenderMode.Lite;
var l=this._isDirectionReversed&&!k;
var j=(a.Orientation.Horizontal==this._orientation);
var t=(j?"width":"height");
var n=this._items;
var o=$telerik.getSize(this._getItemA(m?m:n[0]))[t];
var g=0;
if(p&&q){var s=$telerik.getSize(p)[t];
var r=$telerik.getSize(q)[t];
g=(s>r)?s:r;
if(0==g&&Sys.UI.DomElement.containsCssClass(m,this._hoveredItemCssClass)){g=o;
}if(l){g=o-g;
}}else{if(u!=null){var f=u-Math.floor(u);
if(f>0){if(l){f=1-f;
}g=Math.round(o*f);
}else{g=(-1);
}}}var i=(l&&g==o)||(!l&&g==0);
var h=(l&&g==0)||(!l&&g==o);
var e=j?(""!=this._itemWidth):(""!=this._itemHeight);
if((!e&&h)||i){g=(-1);
if(i){this._clearItemSelectedState(m,n.itemSpanWidth,n.itemSpanHeight);
}}g=(g<0)?"":g.toString()+"px";
return g;
},_mouseOver:function(f){var g=this._getItem(f.target||f.srcElement);
if(!g){this._hoveredItem=null;
return;
}var i=this._hoveredItem;
if(i&&i===g){return;
}this._clearOverState(g);
if(this._clearSelectedStateOnHover){this._clearSelection();
}this._markContinuousHovered(g);
if(a.RatingPrecision.Item!=this._precision){this._mouseOverPrecise(g,f);
}else{this._markItemHovered(g);
}if(this._enableToolTips){var h=this._getItemA(g);
var j=this._getItemData(g).tooltip;
h.title=j?j:this._getItemValue(g);
}},_mouseOverPrecise:function(h,f){this._createPartElements(true);
this._hoveredItem=h;
var j=(a.Orientation.Horizontal==this._orientation);
var n=(j?"width":"height");
var i=this._getItemSpan(h);
if(i){this._spanSize=$telerik.getSize(i)[n];
}var l=this._overPartItem;
var m=this._overPartItemComplement;
var k=this._isDirectionReversed;
l.style[n]="0px";
m.style[n]="0px";
if(!j&&!k){m.style.marginTop=(-this._spanSize).toString()+"px";
}var g=this._getItemA(h);
g.appendChild(k?l:m);
g.appendChild(k?m:l);
if(!this._itemOuterSize){this._storeStartCoords(true);
}if(!this._documentMouseMoveDelegate){this._attachDocumentHandlers(true);
}this._updateHoveredItem(f);
},_mouseUp:function(f){var n=this._getItem(f.target||f.srcElement);
if(!n){return;
}var h=(a.RatingPrecision.Item!=this._precision);
var k=this._overPartItem;
var l=this._overPartItemComplement;
if(h&&(!k||!this._overPartItemComplement)){return;
}var j=this._value;
var i=this._getItemValue(n,true);
var m=new a.RatingRatingEventArgs(i);
this.raiseEvent("rating",m);
if(m.get_cancel()){return;
}if(j!=i){this._clearSelection(i);
this._markContinuousSelected(n);
if(h){var p=this._getItemSpan(n);
var q=this._getFractionSize(n,i);
var g=(a.Orientation.Horizontal==this._orientation);
var o=g?"width":"height";
k.style[o]="1px";
l.style[o]="1px";
p.style[o]=q;
this._spanSize=$telerik.getSize(p)[o];
if(!g&&!this._isDirectionReversed){q=(q!="")?("-"+q):"";
l.style.marginTop=q;
}this._updateHoveredItem(f);
}}this._setValue(i);
this.raiseEvent("rated",new a.RatingRatedEventArgs(j));
if(this._autoPostBack){this._raiseServerEvent();
}},_mouseUpTouchDevice:function(h){var q=this._getItem(h.target||h.srcElement);
if(!q){return;
}var r=this._getItemA(q);
var j=this._precision!=a.RatingPrecision.Item;
var m={left:h.rawEvent.pageX,top:h.rawEvent.pageY};
var k=$telerik.getLocation(q);
k={left:k.x,top:k.y};
var f=a.Orientation.Horizontal==this._orientation?"left":"top";
var t=a.Orientation.Horizontal==this._orientation?"width":"height";
var l=$telerik.getSize(q)[t]-2*($telerik.getMarginBox(r)[f]+$telerik.getBorderBox(r)[f]);
var i=0,s=0;
if(j){s=m[f]-k[f];
var g=this._isDirectionReversed?l-s:s;
i=this._calculateFraction(g,l);
s=this._calculateFractionSize(l,s);
}var o=this._value;
var n=this._calculateItemValue(q,i);
var p=new a.RatingRatingEventArgs(n);
this.raiseEvent("rating",p);
if(p.get_cancel()){return;
}if(o!=n){this._clearSelection(n);
this._markContinuousSelected(q);
if(j){var u=this._getItemSpan(q);
u.style[t]=s+"px";
this._spanSize=s;
}}this._setValue(n);
this.raiseEvent("rated",new a.RatingRatedEventArgs(o));
if(this._autoPostBack){this._raiseServerEvent();
}},_calculateItemValue:function(f,e){var g=this._getItemData(f).value;
var h=g-1;
switch(this._precision){case a.RatingPrecision.Item:return g;
case a.RatingPrecision.Half:return e>0.5?g:g-0.5;
case a.RatingPrecision.Exact:return h+e;
default:throw"impossible";
}},_calculateFractionSize:function(f,g){var e=parseInt(f/2,10);
var h=this._isDirectionReversed?[e,0]:[f,e];
switch(this._precision){case a.RatingPrecision.Item:return 0;
case a.RatingPrecision.Half:return g>e?h[0]:h[1];
case a.RatingPrecision.Exact:return g;
default:throw"impossible";
}},_mouseOut:function(f,h){var g=$telerik.isMouseOverElementEx(this._ulWrapper,f);
if(g){if(!h&&a.RatingPrecision.Item!=this._precision){this._hoveredItem=null;
}return $telerik.cancelRawEvent(f);
}this._attachDocumentHandlers(false);
this._createPartElements(false);
this._storeStartCoords(false);
this._spanSize=null;
this._hoveredItem=null;
this._clearOverState();
if(this._clearSelectedStateOnHover){this._synchronizeUIWithValue(this._value);
}},_cancelEvent:function(f){if(!f){return false;
}if(f.preventDefault){f.preventDefault();
}f.returnValue=false;
return false;
},_raiseServerEvent:function(){setTimeout(Function.createDelegate(this,function(){__doPostBack(this._uniqueID);
}),0);
},add_load:function(e){this.get_events().addHandler("load",e);
},remove_load:function(e){this.get_events().removeHandler("load",e);
},add_rating:function(e){this.get_events().addHandler("rating",e);
},remove_rating:function(e){this.get_events().removeHandler("rating",e);
},add_rated:function(e){this.get_events().addHandler("rated",e);
},remove_rated:function(e){this.get_events().removeHandler("rated",e);
},get_itemCount:function(){return this._itemCount;
},get_value:function(){return this._value;
},set_value:function(h){var f=this._value;
var e=this.get_isInitialized();
if(e){h=this._fixValuePrecision(h);
var g=new a.RatingRatingEventArgs(h);
this.raiseEvent("rating",g);
if(g.get_cancel()){return;
}if(h!=f){this._clearSelection(h);
this._synchronizeUIWithValue(h);
}}this._setValue(h);
if(this._enableToolTips&&this._ulWrapper&&(this._readOnly||!this._enabled)){this._setAllItemTooltips(h);
}if(e){this.raiseEvent("rated",new a.RatingRatedEventArgs(f));
if(this._autoPostBack){this._raiseServerEvent();
}}},_setValue:function(e){this._value=e;
this._doubleValue=e.toString();
this.get_element().value=this._doubleValue;
this.updateClientState();
},_setAllItemTooltips:function(e){$telerik.$(this._ulWrapper).find("a").each(function(){this.title=e;
});
},_synchronizeUIWithValue:function(i,h){var e=this._getItemByValue(i);
if(e){if(!h){this._markContinuousSelected(e);
}if(i!=parseInt(i,10)){var f=this._getItemSpan(e);
var g=this._getFractionSize(e,i);
f.style[a.Orientation.Horizontal==this._orientation?"width":"height"]=g;
}}},_fixValuePrecision:function(f){if(!this._definedItems){var e=this._items;
if(f<0){f=0;
}else{if(f>e.length){f=e.length;
}}}return d(f);
},get_selectionMode:function(){return this._selectionMode;
},set_selectionMode:function(e){this._selectionMode=e;
},get_precision:function(){return this._precision;
},set_precision:function(e){this._precision=e;
},get_orientation:function(){return this._orientation;
},set_orientation:function(e){this._orientation=e;
},get_isDirectionReversed:function(){return this._isDirectionReversed;
},set_isDirectionReversed:function(e){this._isDirectionReversed=e;
},get_enableToolTips:function(){return this._enableToolTips;
},set_enableToolTips:function(e){this._enableToolTips=e;
},get_readOnly:function(){return this._readOnly;
},set_readOnly:function(e){if(this.get_isInitialized()&&e!=this._readOnly){this._enableRatingControl(!e);
}this._readOnly=e;
this.updateClientState();
},get_enabled:function(){return this._enabled;
},set_enabled:function(e){if(this.get_isInitialized()&&e!=this._enabled){this._enableRatingControl(e);
}this._enabled=e;
},get_itemData:function(){return this._itemData;
},set_itemData:function(e){this._itemData=e;
},_enableRatingControl:function(h){var i=this._ulWrapper;
var g=$telerik.$(i).find("a");
$clearHandlers(i);
this._attachDocumentHandlers(false);
this._attachDisabledHandlers(!h);
if(h){var f=this._getMainEventHandlers();
$addHandlers(i,f,this);
g.removeAttr("tabIndex");
}else{this._clearOverState();
g.attr("tabIndex","-1");
if(this._enableToolTips){var e=this.get_value();
this._setAllItemTooltips(e);
}}$addHandler(i,"click",this._cancelEvent);
},saveClientState:function(){var h=["readOnly"];
var j={value:this._doubleValue};
for(var e=0,f=h.length;
e<f;
e++){var g=h[e];
j[g]=this["get_"+g]();
}return Sys.Serialization.JavaScriptSerializer.serialize(j);
}};
a.RadRating._preInitialize=function(i,p){var h=$get(i);
if(!h||($telerik.getInvisibleParent(h)!=null)){return;
}var m=h.getElementsByTagName("li");
if(m&&m.length>0){var k=m[0];
var l=a.RadRating._getElementBox(k);
var q=a.RadRating._getElementBox($telerik.getChildrenByTagName(h,"ul")[0]);
var e=$telerik.getChildrenByTagName(k,"a")[0];
var o=$telerik.getOuterSize(e);
o.width+=l.horizontal;
o.height+=l.vertical;
var n=m.length;
var j=(0==p);
var g=q.horizontal+(j?(n*o.width):o.width);
var f=q.vertical+(j?o.height:(n*o.height));
if(parseInt(h.style.width,10)!=g||parseInt(h.style.height,10)!=f){$telerik.setContentSize(h,{width:g,height:f});
}}};
a.RadRating._getElementBox=function(g){var f={horizontal:0,vertical:0};
if(g){var e=$telerik.getBorderBox(g);
var i=$telerik.getPaddingBox(g);
var h=$telerik.getMarginBox(g);
f.horizontal=e.horizontal+i.horizontal+h.horizontal;
f.vertical=e.vertical+i.vertical+h.vertical;
}return f;
};
a.RadRating.registerClass("Telerik.Web.UI.RadRating",a.RadWebControl);
function d(e){return Math.round(e*10)/10;
}function b(f){f.target.blur();
}})();
