(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.gauge",["kendo.dataviz.core","kendo.drawing","kendo.dataviz.themes"],l);
}(function(){var k={id:"dataviz.gauge",name:"Gauge",category:"dataviz",description:"Radial and Linear gauges.",depends:["dataviz.core","dataviz.themes"]};
(function(l,az){var ah=Math,ab=window.kendo,aA=ab.util,aB=ab.ui.Widget,G=ab.deepExtend,F=ab.dataviz,u=F.autoMajorUnit,C=F.ChartElement,al=F.NumericAxis,v=F.Axis,A=F.Box2D,D=ab.Class,N=aA.defined,aa=aA.isNumber,Z=F.interpolateValue,U=F.getSpacing,ax=F.round,R=F.geometry,P=F.drawing,ao=R.Point,V=P.Group,an=P.Path,aw=R.Rect,ay=P.Text;
var p=150,ad=250,q="arrow",r="arrowPointer",w="barPointer",z="#000",B=0.05,E=F.COORD_PRECISION,ai=Number.MAX_VALUE,aj=-Number.MAX_VALUE,H=200,I=0.5,M=200,L=60,K=60,J=5,O=ah.PI/180,S=180,W="inside",ac="linear",ak="needle",am="outside",aq="radialPointer",aC="x",aD="y";
var ap=D.extend({init:function(aE,X){var Y=this;
var aF=aE.options;
C.fn.init.call(Y,X);
X=Y.options;
X.fill=X.color;
Y.scale=aE;
if(N(X.value)){X.value=ah.min(ah.max(X.value,aF.min),aF.max);
}else{X.value=aF.min;
}},options:{color:z},value:function(X){var aF=this;
var Y=aF.options;
var aG=Y.value;
var aE=aF.scale.options;
if(arguments.length===0){return aG;
}Y._oldValue=Y._oldValue!==az?Y.value:aE.min;
Y.value=ah.min(ah.max(X,aE.min),aE.max);
if(aF.elements){aF.repaint();
}}});
var at=ap.extend({options:{shape:ak,cap:{size:B},arrow:{width:16,height:14},animation:{type:aq,duration:p}},setRadius:function(X){var Y=this;
if(X){Y.elements.clear();
Y.render(Y.parent,Y.center,X);
}},setAngle:function(X){this.elements.transform(R.transform().rotate(X,this.center));
},repaint:function(){var aG=this;
var aF=aG.scale;
var aE=aG.options;
var Y=aF.slotAngle(aE._oldValue);
var X=aF.slotAngle(aE.value);
if(aE.animation.transitions===false){aG.setAngle(X);
}else{new au(aG.elements,G(aE.animation,{oldAngle:Y,newAngle:X})).play();
}},render:function(){var aG=this;
var aF=aG.scale;
var X=aF.arc.center;
var aE=aG.options;
var Y=new V();
if(aE.animation!==false){G(aE.animation,{startAngle:0,center:X,reverse:aF.options.reverse});
}if(aE.shape===ak){Y.append(aG._renderNeedle(),aG._renderCap());
}else{Y.append(aG._renderArrow());
}aG.elements=Y;
aG.setAngle(O);
return Y;
},reflow:function(X){var aG=this;
var aE=aG.center=X.center;
var aF=aG.radius=X.getRadiusX();
var Y=aG.capSize=Math.round(aF*aG.options.cap.size);
aG.bbox=aw.fromPoints(new ao(aE.x-Y,aE.y-Y),new ao(aE.x+Y,aE.y+Y));
},_renderNeedle:function(){var aH=this;
var aG=aH.options;
var Y=aH.scale.options.minorTicks.size;
var X=aH.center;
var aE=aG.color;
var aF=new an({fill:{color:aE},stroke:{color:aE,width:I}});
aF.moveTo(X.x+aH.radius-Y,X.y).lineTo(X.x,X.y-aH.capSize/2).lineTo(X.x,X.y+aH.capSize/2).close();
return aF;
},_renderCap:function(){var aG=this;
var aF=aG.options;
var Y=aF.cap.color||aF.color;
var aE=new R.Circle(aG.center,aG.capSize);
var X=new P.Circle(aE,{fill:{color:Y},stroke:{color:Y}});
return X;
}});
var av=al.extend({init:function(X){var Y=this;
Y.options=G({},Y.options,X);
Y.options.majorUnit=Y.options.majorUnit||u(Y.options.min,Y.options.max);
Y.options.minorUnit=Y.options.minorUnit||Y.options.majorUnit/10;
v.fn.init.call(Y,Y.options);
},options:{min:0,max:100,majorTicks:{size:15,align:W,color:z,width:I,visible:true},minorTicks:{size:10,align:W,color:z,width:I,visible:true},startAngle:-30,endAngle:210,labels:{position:W,padding:2}},render:function(Y,aE){var aF=this;
var X=aF.renderArc(Y,aE);
aF.bbox=X.bbox();
aF.labelElements=aF.renderLabels();
aF.ticks=aF.renderTicks();
aF.ranges=aF.renderRanges();
},reflow:function(X){var aF=this;
var Y=X.center();
var aE=ah.min(X.height(),X.width())/2;
if(aF.bbox!==az){aF.bbox=aF.arc.bbox();
aF.radius(aF.arc.getRadiusX());
aF.repositionRanges();
aF.renderLabels();
}else{return aF.render(Y,aE);
}},slotAngle:function(aJ){var aF=this.options;
var aI=aF.startAngle;
var aH=aF.reverse;
var X=aF.endAngle-aI;
var aE=aF.min;
var Y=aF.max;
var aG;
if(aH){aG=aF.endAngle-(aJ-aE)/(Y-aE)*X;
}else{aG=(aJ-aE)/(Y-aE)*X+aI;
}return aG+S;
},renderLabels:function(){var a2=this;
var aV=a2.options;
var aU=aV.majorTicks.size;
var Y=a2.arc.clone();
var aY=Y.getRadiusX();
var a3=a2.tickAngles(Y,aV.majorUnit);
var aO=a2.labels;
var aE=aO.length;
var aQ=aV.labels;
var aW=aQ.padding;
var aZ=aY*0.05;
var a1=aV.rangeSize=aV.rangeSize||aY*0.1;
var a0=aV.ranges||[];
var aI,aH,aM;
var X,aL,aT,aJ,aF,aG,aK;
var aP=new V();
var aS,aN,aX,aR;
if(a2.options.rangeDistance!==az){aZ=a2.options.rangeDistance;
}else{a2.options.rangeDistance=aZ;
}if(aQ.position===W){aY-=aU;
if(a0.length&&a2.labelElements===az){aY-=a1+aZ;
}Y.setRadiusX(aY).setRadiusY(aY);
}for(aJ=0;
aJ<aE;
aJ++){aL=aO[aJ];
aI=aL.box.width()/2;
aH=aL.box.height()/2;
X=a3[aJ];
aM=(X-S)*O;
aK=aQ.position===W;
aT=Y.pointAt(X);
aF=aT.x+ah.cos(aM)*(aI+aW)*(aK?1:-1);
aG=aT.y+ah.sin(aM)*(aH+aW)*(aK?1:-1);
aL.reflow(new F.Box2D(aF-aI,aG-aH,aF+aI,aG+aH));
aN=new ao(aL.box.x1,aL.box.y1);
if(a2.labelElements===az){aS=m(aL,aV.labels);
aP.append(aS);
}else{aS=a2.labelElements.children[aJ];
aX=aS.bbox().origin;
aR=aS.transform()||R.transform();
aR.translate(aN.x-aX.x,aN.y-aX.y);
aS.transform(aR);
}a2.bbox=aw.union(a2.bbox,aS.bbox());
}return aP;
},repositionRanges:function(){var aI=this;
var aG=aI.ranges.children;
var aH=aI.options.rangeSize;
var aE=aI.options.rangeDistance;
var aF,Y;
if(aG.length>0){aF=aI.getRangeRadius();
if(aI.options.labels.position===W){aF+=aH+aE;
}Y=aF+aH/2;
for(var X=0;
X<aG.length;
X++){aG[X]._geometry.setRadiusX(Y).setRadiusY(Y);
}aI.bbox=aw.union(aI.bbox,aI.ranges.bbox());
}},renderRanges:function(){var aO=this;
var X=aO.arc;
var aJ=new V();
var Y,aP;
var aM=aO.rangeSegments();
var aN=aM.length;
var aK=aO.options.reverse;
var aI=aO.options.rangeSize;
var aF=aO.options.rangeDistance;
var aL,aH,aG,aE;
if(aN){aH=aO.getRangeRadius();
aO.radius(aO.radius()-aI-aF);
for(aE=0;
aE<aN;
aE++){aL=aM[aE];
Y=aO.slotAngle(aL[aK?"to":"from"]);
aP=aO.slotAngle(aL[!aK?"to":"from"]);
if(aP-Y!==0){aG=new R.Arc(X.center,{radiusX:aH+aI/2,radiusY:aH+aI/2,startAngle:Y,endAngle:aP});
aJ.append(new P.Arc(aG,{stroke:{width:aI,color:aL.color,opacity:aL.opacity}}));
}}}return aJ;
},rangeSegments:function(){var aE=this;
var aJ=aE.options;
var aL=aJ.ranges||[];
var X=aL.length;
var aK;
var aP;
var Y=aJ.rangePlaceholderColor;
var aO=[];
var aN;
var aI=aJ.min;
var aH=aJ.max;
var aF,aG;
function aM(aR,aT,aQ,aS){return{from:aR,to:aT,color:aQ,opacity:aS};
}if(X){aO.push(aM(aI,aH,Y));
for(aF=0;
aF<X;
aF++){aK=T(aL[aF],aI,aH);
aP=aO.length;
for(aG=0;
aG<aP;
aG++){aN=aO[aG];
if(aN.from<=aK.from&&aK.from<=aN.to){aO.push(aM(aK.from,aK.to,aK.color,aK.opacity));
if(aN.from<=aK.to&&aK.to<=aN.to){aO.push(aM(aK.to,aN.to,Y,aK.opacity));
}aN.to=aK.from;
break;
}}}}return aO;
},getRangeRadius:function(){var aI=this;
var aE=aI.options;
var Y=aE.majorTicks.size;
var aH=aE.rangeSize;
var aG=aE.rangeDistance;
var X=aI.arc;
var aF;
if(aE.labels.position===am){aF=X.getRadiusX()-Y-aG-aH;
}else{aF=X.getRadiusX()-aH;
}return aF;
},renderArc:function(Y,aF){var aG=this;
var aE=aG.options;
var X=aG.arc=new R.Arc(Y,{radiusX:aF,radiusY:aF,startAngle:aE.startAngle+S,endAngle:aE.endAngle+S});
return X;
},renderTicks:function(){var aK=this;
var Y=aK.arc;
var aI=aK.options;
var aF=aI.labels.position;
var X=new V();
var aG=aI.majorTicks.size;
var aH=aI.minorTicks.size;
var aL=Y.clone();
var aJ=aL.getRadiusX();
function aE(aM,aQ,aV,aS){var aT=new V(),aN=aM.center,aP=aM.getRadiusX(),aO,aU,aR,aW=aS.visible;
if(aW){for(aO=0;
aO<aQ.length;
aO++){aU=aM.pointAt(aQ[aO]);
aR=new ao(aN.x+aP-aS.size,aN.y).rotate(aQ[aO],aN);
aT.append(new an({stroke:{color:aS.color,width:aS.width}}).moveTo(aU).lineTo(aR));
}}return aT;
}aK.majorTickAngles=aK.tickAngles(Y,aI.majorUnit);
aK.majorTicks=aE(aL,aK.majorTickAngles,aI.majorUnit,aI.majorTicks);
X.append(aK.majorTicks);
aK._tickDifference=aG-aH;
if(aF===am){aL.setRadiusX(aJ-aG+aH).setRadiusY(aJ-aG+aH);
}aK.minorTickAngles=aK.normalizeTickAngles(aK.tickAngles(Y,aI.minorUnit));
aK.minorTicks=aE(aL,aK.minorTickAngles,aI.minorUnit,aI.minorTicks,aI.majorUnit);
X.append(aK.minorTicks);
return X;
},normalizeTickAngles:function(X){var aG=this;
var aE=aG.options;
var aF=aE.majorUnit/aE.minorUnit;
for(var Y=X.length-1;
Y>=0;
Y--){if(Y%aF===0){X.splice(Y,1);
}}return X;
},tickAngles:function(aJ,aM){var aK=this;
var aE=aK.options;
var aI=aE.reverse;
var aH=aE.max-aE.min;
var X=aJ.endAngle-aJ.startAngle;
var aF=aJ.startAngle;
var aN=aH/aM;
var aL=X/aN;
var aG=[];
var Y;
if(aI){aF+=X;
aL=-aL;
}for(Y=0;
Y<aN;
Y++){aG.push(ax(aF,E));
aF+=aL;
}if(ax(aF)<=aJ.endAngle){aG.push(aF);
}return aG;
},radius:function(X){var Y=this;
if(X){Y.arc.setRadiusX(X).setRadiusY(X);
Y.repositionTicks(Y.majorTicks.children,Y.majorTickAngles);
Y.repositionTicks(Y.minorTicks.children,Y.minorTickAngles,true);
}else{return Y.arc.getRadiusX();
}},repositionTicks:function(aL,aJ,aE){var aI=this;
var X=aE?aI._tickDifference||0:0;
var aK=aI.arc;
var aG=aK.getRadiusX();
if(aE&&aI.options.labels.position===am&&X!==0){aK=aI.arc.clone();
aK.setRadiusX(aG-X).setRadiusY(aG-X);
}for(var Y=0;
Y<aL.length;
Y++){var aF=aK.pointAt(aJ[Y]);
var aH=aL[Y].segments;
var aM=aF.x-aH[0].anchor().x;
var aN=aF.y-aH[0].anchor().y;
aL[Y].transform(new R.Transformation().translate(aM,aN));
}}});
var Q=aB.extend({init:function(X,aK){var Y=this;
var aF;
var aI;
var aH;
var aJ=F.ui.themes||{};
var aG;
ab.destroy(X);
l(X).empty();
aB.fn.init.call(Y,X);
Y.wrapper=Y.element;
Y._originalOptions=G({},aK);
aF=G({},Y.options,aK);
aH=aF.theme;
aG=aJ[aH]||aJ[aH.toLowerCase()];
aI=aH&&aG?aG.gauge:{};
Y.options=G({},aI,aF);
if(l.isArray(aF.pointer)){for(var aE=0;
aE<aF.pointer.length;
aE++){Y.options.pointer[aE]=G({},aI.pointer,aF.pointer[aE]);
}}Y.element.addClass("k-gauge");
Y.surface=Y._createSurface();
Y.redraw();
},options:{plotArea:{},theme:"default",renderAs:"",pointer:{},scale:{},gaugeArea:{}},destroy:function(){this.surface.destroy();
aB.fn.destroy.call(this);
},value:function(aE){var Y=this;
var X=Y.pointers[0];
if(arguments.length===0){return X.value();
}X.value(aE);
Y._setValueOptions(aE);
},_draw:function(){var X=this.surface;
X.clear();
X.draw(this._visuals);
},exportVisual:function(){return this._visuals;
},allValues:function(aG){var aF=this;
var aE=aF.pointers;
var X=[];
var Y;
if(arguments.length===0){for(Y=0;
Y<aE.length;
Y++){X.push(aE[Y].value());
}return X;
}if(l.isArray(aG)){for(Y=0;
Y<aG.length;
Y++){if(aa(aG[Y])){aE[Y].value(aG[Y]);
}}}aF._setValueOptions(aG);
},_setValueOptions:function(aE){var Y=[].concat(this.options.pointer);
aE=[].concat(aE);
for(var X=0;
X<aE.length;
X++){Y[X].value=aE[X];
}},_resize:function(){var aE=this;
var Y=aE.options.transitions;
var X;
aE.options.transitions=false;
for(X=0;
X<aE.pointers.length;
X++){aE.pointers[X].options.animation.transitions=false;
}aE.redraw();
aE.options.transitions=Y;
for(X=0;
X<aE.pointers.length;
X++){aE.pointers[X].options.animation.transitions=Y;
}},redraw:function(){var aE=this;
var Y=G(aE._getSize(),aE.options.gaugeArea);
var aF=new aw([0,0],[Y.width,Y.height]);
var X;
aE.surface.clear();
aE.gaugeArea=aE._createGaugeArea();
aE.surface.element.css({width:Y.width,height:Y.height});
aE._createModel();
X=o(aF.bbox(),aE._gaugeAreaMargin);
aE.reflow(X);
},_createGaugeArea:function(){var aH=this;
var aF=aH.options.gaugeArea;
var aG=aH.surface.size();
var Y=aF.border||{};
var X=new aw([0,0],[aG.width,aG.height]);
aH._gaugeAreaMargin=aF.margin||J;
if(Y.width>0){X=o(X,Y.width);
}var aE=an.fromRect(X,{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType,lineJoin:"round",lineCap:"round"},fill:{color:aF.background}});
return aE;
},_createSurface:function(){var aE=this;
var X=aE.options;
var Y=aE._getSize();
Y=X.gaugeArea?G(Y,X.gaugeArea):Y;
var aF=l("<div></div>").appendTo(aE.element).css({width:Y.width,height:Y.height});
return new P.Surface.create(aF,{type:X.renderAs});
},getSize:function(){return this._getSize();
},_getSize:function(){var aE=this;
var X=aE.element;
var aF=X.width();
var Y=X.height();
if(!aF){aF=M;
}if(!Y){Y=H;
}return{width:aF,height:Y};
}});
var ar=Q.extend({init:function(X,Y){var aE=this;
Q.fn.init.call(aE,X,Y);
ab.notify(aE,F.ui);
},options:{name:"RadialGauge",transitions:true,gaugeArea:{background:""}},reflow:function(X){var aF=this;
var aE=aF.pointers;
aF.scale.reflow(X);
aF._initialPlotArea=aF.scale.bbox;
for(var Y=0;
Y<aE.length;
Y++){aE[Y].reflow(aF.scale.arc);
aF._initialPlotArea=aw.union(aF._initialPlotArea,aE[Y].bbox);
}aF.fitScale(X);
aF.alignScale(X);
aF._buildVisual(aF.gaugeArea,aE,aF.scale);
aF._draw();
},_buildVisual:function(Y,aF,aG){var aH=new V();
var X;
aH.append(Y);
aH.append(aG.ticks);
aH.append(aG.ranges);
for(var aE=0;
aE<aF.length;
aE++){X=aF[aE];
X.render();
aH.append(X.elements);
X.value(X.options.value);
}aH.append(aG.labelElements);
this._visuals=aH;
},fitScale:function(Y){var aQ=this;
var aN=aQ.scale;
var X=aN.arc;
var aM=aQ._initialPlotArea;
var aP=ah.abs(aQ.getDiff(aM,Y));
var aJ=ax(aP,E);
var aF=ax(-aP,E);
var aK,aI,aG,aH,aL;
var aO=0;
var aE=0;
while(aE++<100){aO=aL===aG?aO+1:0;
if(aO>5){break;
}if(aJ!=aH){aK=aQ.getPlotBox(aJ,Y,X);
if(0<=aK&&aK<=2){break;
}}if(aF!=aH){aG=aQ.getPlotBox(aF,Y,X);
if(0<=aG&&aG<=2){break;
}}if(aK>0&&aG>0){aH=aJ*2;
}else{if(aK<0&&aG<0){aH=aF*2;
}else{aH=ax((aJ+aF)/2||1,E);
}}aI=aQ.getPlotBox(aH,Y,X);
if(0<=aI&&aI<=2){break;
}aL=aG;
if(aI>0){aF=aH;
aG=aI;
}else{aJ=aH;
aK=aI;
}}},getPlotBox:function(aI,Y,X){var aJ=this;
var aH=aJ.scale;
var aF=aJ.pointers;
var aG=X.getRadiusX();
X=X.clone();
X.setRadiusX(aG+aI).setRadiusY(aG+aI);
aH.arc=X;
aH.reflow(Y);
aJ.plotBbox=aH.bbox;
for(var aE=0;
aE<aF.length;
aE++){aF[aE].reflow(X);
aJ.plotBbox=aw.union(aJ.plotBbox,aF[aE].bbox);
}return aJ.getDiff(aJ.plotBbox,Y);
},getDiff:function(Y,X){return ah.min(X.width()-Y.width(),X.height()-Y.height());
},alignScale:function(X){var aK=this;
var aH=aK.plotBbox.center();
var Y=X.center();
var aF=aH.x-Y.x;
var aG=aH.y-Y.y;
var aJ=aK.scale;
var aI=aK.pointers;
aJ.arc.center.x-=aF;
aJ.arc.center.y-=aG;
aJ.reflow(X);
for(var aE=0;
aE<aI.length;
aE++){aI[aE].reflow(aJ.arc);
aK.plotBbox=aw.union(aJ.bbox,aI[aE].bbox);
}},_createModel:function(){var aH=this;
var aE=aH.options;
var aF=aE.pointer;
var aG=aH.scale=new av(aE.scale);
var X;
aH.pointers=[];
aF=l.isArray(aF)?aF:[aF];
for(var Y=0;
Y<aF.length;
Y++){X=new at(aG,G({},aF[Y],{animation:{transitions:aE.transitions}}));
aH.pointers.push(X);
}}});
var ae=Q.extend({init:function(X,aE){var Y=this;
Q.fn.init.call(Y,X,aE);
ab.notify(Y,F.ui);
},options:{name:"LinearGauge",transitions:true,gaugeArea:{background:""},scale:{vertical:true}},reflow:function(X){var aI=this;
var aH=aI.pointers;
var aE=X.origin.x;
var aF=X.origin.y;
var Y=new F.Box2D(aE,aE,aE+X.width(),aF+X.height());
aI.scale.reflow(Y);
for(var aG=0;
aG<aH.length;
aG++){aH[aG].reflow();
}aI.bbox=aI._getBox(Y);
aI._alignElements();
aI._shrinkElements();
aI._buildVisual();
aI._draw();
},_buildVisual:function(){var aG=this;
var aH=new V();
var aF=aG.scale.render();
var aE=aG.pointers;
var X;
aH.append(aG.gaugeArea);
aH.append(aF);
for(var Y=0;
Y<aE.length;
Y++){X=aE[Y];
aH.append(X.render());
X.value(X.options.value);
}aG._visuals=aH;
},_createModel:function(){var aI=this;
var aF=aI.options;
var aG=aF.pointer;
var aH=aI.scale=new ag(aF.scale);
var X,Y;
aI.pointers=[];
aG=l.isArray(aG)?aG:[aG];
for(var aE=0;
aE<aG.length;
aE++){Y=G({},aG[aE],{animation:{transitions:aF.transitions}});
if(Y.shape===q){X=new s(aH,Y);
}else{X=new x(aH,Y);
}aI.pointers.push(X);
}},_getSize:function(){var Y=this;
var X=Y.element;
var aG=X.width();
var aE=X.height();
var aF=Y.options.scale.vertical;
if(!aG){aG=aF?L:M;
}if(!aE){aE=aF?H:K;
}return{width:aG,height:aE};
},_getBox:function(X){var aJ=this;
var aH=aJ.scale;
var aG=aJ.pointers;
var Y=X.center();
var aF=aG[0].box.clone().wrap(aH.box);
var aI;
for(var aE=0;
aE<aG.length;
aE++){aF.wrap(aG[aE].box.clone());
}if(aH.options.vertical){aI=aF.width()/2;
aF=new A(Y.x-aI,X.y1,Y.x+aI,X.y2);
}else{aI=aF.height()/2;
aF=new A(X.x1,Y.y-aI,X.x2,Y.y+aI);
}return aF;
},_alignElements:function(){var aJ=this;
var aH=aJ.scale;
var aG=aJ.pointers;
var aI=aH.box;
var X=aG[0].box.clone().wrap(aH.box);
var aF=aJ.bbox;
var Y,aE;
for(aE=0;
aE<aG.length;
aE++){X.wrap(aG[aE].box.clone());
}if(aH.options.vertical){Y=aF.center().x-X.center().x;
aH.reflow(new A(aI.x1+Y,aF.y1,aI.x2+Y,aF.y2));
}else{Y=aF.center().y-X.center().y;
aH.reflow(new A(aF.x1,aI.y1+Y,aF.x2,aI.y2+Y));
}for(aE=0;
aE<aG.length;
aE++){aG[aE].reflow(aJ.bbox);
}},_shrinkElements:function(){var aI=this;
var aG=aI.scale;
var aE=aI.pointers;
var aH=aG.box.clone();
var aF=aG.options.vertical?"y":"x";
var Y=aE[0].box;
var X;
for(X=0;
X<aE.length;
X++){Y.wrap(aE[X].box.clone());
}aH[aF+1]+=ah.max(aH[aF+1]-Y[aF+1],0);
aH[aF+2]-=ah.max(Y[aF+2]-aH[aF+2],0);
aG.reflow(aH);
for(X=0;
X<aE.length;
X++){aE[X].reflow(aI.bbox);
}}});
var ag=al.extend({init:function(X){var Y=this;
Y.options=G({},Y.options,X);
Y.options=G({},Y.options,{labels:{mirror:Y.options.mirror}});
Y.options.majorUnit=Y.options.majorUnit||u(Y.options.min,Y.options.max);
v.fn.init.call(Y,Y.options);
Y.options.minorUnit=Y.options.minorUnit||Y.options.majorUnit/10;
},options:{min:0,max:50,majorTicks:{size:15,align:W,color:z,width:I,visible:true},minorTicks:{size:10,align:W,color:z,width:I,visible:true},line:{width:I},labels:{position:W,padding:2},mirror:false,_alignLines:false},render:function(){var aH=this;
var X=aH.elements=new V();
var Y=aH.renderLabels();
var aF=aH.renderLine();
var aG=aH.renderTicks();
var aE=aH.renderRanges();
X.append(aF,Y,aG,aE);
return X;
},renderRanges:function(){var aP=this;
var aI=aP.options;
var aG=aI.min;
var aF=aI.max;
var aK=aI.ranges||[];
var aQ=aI.vertical;
var aH=aI.labels.mirror;
var Y=new V();
var X=aK.length;
var aL=aI.rangeSize||aI.minorTicks.size/2;
var aJ,aM,aN,aO,aE;
if(X){for(aE=0;
aE<X;
aE++){aJ=T(aK[aE],aG,aF);
aM=aP.getSlot(aJ.from,aJ.to);
aN=aQ?aP.lineBox():aM;
aO=aQ?aM:aP.lineBox();
if(aQ){aN.x1-=aL*(aH?-1:1);
}else{aO.y2+=aL*(aH?-1:1);
}Y.append(an.fromRect(new aw([aN.x1,aO.y1],[aN.x2-aN.x1,aO.y2-aO.y1]),{fill:{color:aJ.color,opacity:aJ.opacity},stroke:{}}));
}}return Y;
},renderLabels:function(){var aG=this;
var aF=aG.options;
var aE=aG.labels;
var X=new V();
for(var Y=0;
Y<aE.length;
Y++){X.append(m(aE[Y],aF.labels));
}return X;
},renderLine:function(){var aH=this;
var aG=aH.options;
var Y=aG.line;
var aE=aH.lineBox();
var aF;
var X=new V();
if(Y.width>0&&Y.visible){aF=new an({stroke:{color:Y.color,dashType:Y.dashType,width:Y.width}});
aF.moveTo(aE.x1,aE.y1).lineTo(aE.x2,aE.y2);
X.append(aF);
}return X;
},renderTicks:function(){var aH=this;
var aJ=new V();
var aF=aH.options;
var X=aH.lineBox();
var aE=aF.labels.mirror;
var Y=aF.majorTicks.visible?aF.majorUnit:0;
var aI={_alignLines:aF._alignLines,vertical:aF.vertical};
function aG(aN,aM){var aL,aK=aN.length;
if(aM.visible){for(aL=aM.skip;
aL<aK;
aL+=aM.step){if(aL%aM.skipUnit===0){continue;
}aI.tickX=aE?X.x2:X.x2-aM.size;
aI.tickY=aE?X.y1-aM.size:X.y1;
aI.position=aN[aL];
aJ.append(aH.renderAxisTick(aI,aM));
}}}aG(aH.getMajorTickPositions(),aF.majorTicks);
aG(aH.getMinorTickPositions(),G({},{skipUnit:Y/aF.minorUnit},aF.minorTicks));
return aJ;
},renderAxisTick:function(Y,aG){var aI=Y.tickX;
var aJ=Y.tickY;
var aE=Y.position;
var aF,X,aH;
if(Y.vertical){aF=new ao(aI,aE);
X=new ao(aI+aG.size,aE);
}else{aF=new ao(aE,aJ);
X=new ao(aE,aJ+aG.size);
}aH=new an({stroke:{color:aG.color,width:aG.width}}).moveTo(aF).lineTo(X);
return aH;
}});
var af=ap.extend({init:function(aE,X){var Y=this;
ap.fn.init.call(Y,aE,X);
Y.options=G({track:{visible:N(X.track)}},Y.options);
},options:{shape:w,track:{border:{width:1}},color:z,border:{width:1},opacity:1,margin:U(3),animation:{type:w},visible:true},reflow:function(){var aF=this;
var aE=aF.options;
var aJ=aF.scale;
var aK=aJ.lineBox();
var aN=aE.track.size||aE.size;
var aH=aE.size/2;
var Y=aJ.options.mirror;
var X=U(aE.margin);
var aO=aJ.options.vertical;
var aL=aO?X[Y?"left":"right"]:X[Y?"bottom":"top"];
var aG,aI,aM;
aL=Y?-aL:aL;
if(aO){aM=new A(aK.x1+aL,aK.y1,aK.x1+aL,aK.y2);
if(Y){aM.x1-=aN;
}else{aM.x2+=aN;
}if(aE.shape!==w){aI=new A(aK.x2+aL,aK.y1-aH,aK.x2+aL,aK.y2+aH);
aG=aI;
}}else{aM=new A(aK.x1,aK.y1-aL,aK.x2,aK.y1-aL);
if(Y){aM.y2+=aN;
}else{aM.y1-=aN;
}if(aE.shape!==w){aI=new A(aK.x1-aH,aK.y1-aL,aK.x2+aH,aK.y1-aL);
aG=aI;
}}aF.trackBox=aM;
aF.pointerRangeBox=aI;
aF.box=aG||aM.clone().pad(aE.border.width);
},getElementOptions:function(){var X=this.options;
return{fill:{color:X.color,opacity:X.opacity},stroke:N(X.border)?{color:X.border.width?X.border.color||X.color:"",width:X.border.width,dashType:X.border.dashType,opacity:X.opacity}:null};
},_margin:function(){var aF=this;
var aE=aF.options;
var aG=aF.scale;
var Y=aG.options.mirror;
var X=U(aE.margin);
var aI=aG.options.vertical;
var aH=aI?X[Y?"left":"right"]:X[Y?"bottom":"top"];
return aH;
}});
var s=af.extend({init:function(Y,X){af.fn.init.call(this,Y,X);
if(this.options.size===az){this.options.size=this.scale.options.majorTicks.size*0.6;
}},pointerShape:function(){var aK=this;
var Y=aK.options;
var aG=aK.scale;
var aJ=Y.size;
var aL=aG.options.vertical;
var X=aJ/2;
var aI=aG.options.mirror?-1:1;
var aF=aG.options.reverse;
var aE,aH;
if(aL){aE=aF?"y2":"y1";
aH=[new ao(0,0-X),new ao(0-aI*aJ,0),new ao(0,0+X)];
}else{aE=aF?"x1":"x2";
aH=[new ao(0-X,0),new ao(0,0+aI*aJ),new ao(0+X,0)];
}return aH;
},repaint:function(){var aF=this;
var aE=aF.scale;
var Y=aF.options;
var X=new t(aF.elements,G(Y.animation,{vertical:aE.options.vertical,mirror:aE.options.mirror,margin:aF._margin(Y.margin),from:aE.getSlot(Y._oldValue),to:aE.getSlot(Y.value)}));
if(Y.animation.transitions===false){X.options.duration=0;
}X.setup();
X.play();
},render:function(){var aI=this;
var aE=aI.options;
var Y=new V();
var aF=aI.scale;
var X=aI.getElementOptions();
var aG=aI.pointerShape(aE.value);
aE.animation.type=r;
Y=new an({stroke:X.stroke,fill:X.fill}).moveTo(aG[0]).lineTo(aG[1]).lineTo(aG[2]).close();
var aH=aF.getSlot(aE.value);
Y.transform(R.transform().translate(aH.x1,aH.y1));
aI.elements=Y;
return Y;
}});
var x=af.extend({init:function(Y,X){af.fn.init.call(this,Y,X);
if(this.options.size===az){this.options.size=this.scale.options.majorTicks.size*0.3;
}},pointerShape:function(aR){var aQ=this;
var aH=aQ.options;
var aM=aQ.scale;
var aS=aM.options.vertical;
var aG=aM.options.mirror;
var Y=aG==aS?-1:1;
var aN=aH.size*Y;
var aF=aM.getSlot(aM.options.min);
var aP=aM.getSlot(aR);
var X=aS?aD:aC;
var aO=aS?aC:aD;
var aE=aQ._margin()*Y;
var aI=new ao();
aI[X]=aF[X+"1"];
aI[aO]=aF[aO+"1"];
var aJ=new ao();
aJ[X]=aP[X+"1"];
aJ[aO]=aP[aO+"1"];
if(aS){aI.translate(aE,0);
aJ.translate(aE,0);
}else{aI.translate(0,aE);
aJ.translate(0,aE);
}var aK=aJ.clone();
var aL=aI.clone();
if(aS){aK.translate(aN,0);
aL.translate(aN,0);
}else{aK.translate(0,aN);
aL.translate(0,aN);
}return[aI,aJ,aK,aL];
},repaint:function(){var aI=this;
var aG=aI.scale;
var aE=aI.options;
var aH=aI.pointerShape(aE.value);
var aF=aI.elements.children[0];
var Y=aI.pointerShape(aE._oldValue);
aF.moveTo(aH[0]).lineTo(aH[1]).lineTo(aH[2]).lineTo(aH[3]).close();
var X=new y(aF,G(aE.animation,{reverse:aG.options.reverse,vertical:aG.options.vertical,oldPoints:[Y[1],Y[2]],newPoints:[aH[1],aH[2]]}));
if(aE.animation.transitions===false){X.options.duration=0;
}X.setup();
X.play();
},render:function(){var aF=this;
var Y=new V();
var X=aF.getElementOptions();
var aE=new an({stroke:X.stroke,fill:X.fill});
Y.append(aE);
aF.elements=Y;
return Y;
}});
var au=P.Animation.extend({init:function(X,Y){P.Animation.fn.init.call(this,X,Y);
Y=this.options;
Y.duration=ah.max(ah.abs(Y.newAngle-Y.oldAngle)/Y.duration*1000,1);
},options:{easing:ac,duration:p},step:function(aF){var Y=this;
var aE=Y.options;
var X=Z(aE.oldAngle,aE.newAngle,aF);
Y.element.transform(R.transform().rotate(X,aE.center));
}});
P.AnimationFactory.current.register(aq,au);
var t=P.Animation.extend({options:{easing:ac,duration:ad},setup:function(){var aG=this.options;
var aF=aG.margin;
var Y=aG.from;
var aH=aG.to;
var X=aG.vertical?"x1":"y1";
if(aG.mirror==aG.vertical){Y[X]-=aF;
aH[X]-=aF;
}else{Y[X]+=aF;
aH[X]+=aF;
}var aE=this.fromScale=new ao(Y.x1,Y.y1);
var aI=this.toScale=new ao(aH.x1,aH.y1);
if(aG.duration!==0){aG.duration=ah.max(aE.distanceTo(aI)/aG.duration*1000,1);
}},step:function(X){var Y=Z(this.fromScale.x,this.toScale.x,X);
var aE=Z(this.fromScale.y,this.toScale.y,X);
this.element.transform(R.transform().translate(Y,aE));
}});
P.AnimationFactory.current.register(r,t);
var y=P.Animation.extend({options:{easing:ac,speed:ad},setup:function(){var aG=this.options;
var aE=aG.newPoints;
var aF=aG.oldPoints;
var X=this.axis=aG.vertical?aD:aC;
var aH=this.to=aE[0][X];
var Y=this.from=aF[0][X];
if(aG.duration!==0){aG.duration=ah.max(ah.abs(aH-Y)/aG.speed*1000,1);
}this._set(Y);
},step:function(X){var Y=Z(this.from,this.to,X);
this._set(Y);
},_set:function(aE){var Y="set"+this.axis.toUpperCase();
var X=this.options.newPoints;
X[0][Y](aE);
X[1][Y](aE);
}});
P.AnimationFactory.current.register(w,y);
function m(aF,aH){var aG=aF.box;
var aL=aF.children[0].box;
var Y=aH.border||{};
var X=aH.background||"";
var aE=new V();
var aI,aJ,aM;
aM=an.fromRect(new aw([aG.x1,aG.y1],[aG.width(),aG.height()]),{stroke:{}});
var aK=new ay(aF.text,new ao(aL.x1,aL.y1),{font:aH.font,fill:{color:aH.color}});
aJ=n(aK.bbox().clone(),aH.padding);
aI=an.fromRect(aJ,{stroke:{color:Y.width?Y.color:"",width:Y.width,dashType:Y.dashType,lineJoin:"round",lineCap:"round"},fill:{color:X}});
aE.append(aM);
aE.append(aI);
aE.append(aK);
return aE;
}function T(aF,aE,Y){var X=N(aF.from)?aF.from:aj;
var aG=N(aF.to)?aF.to:ai;
aF.from=ah.max(ah.min(aG,X),aE);
aF.to=ah.min(ah.max(aG,X),Y);
return aF;
}function n(X,aG){var Y=X.getOrigin();
var aE=X.getSize();
var aF=U(aG);
X.setOrigin([Y.x-aF.left,Y.y-aF.top]);
X.setSize([aE.width+(aF.left+aF.right),aE.height+(aF.top+aF.bottom)]);
return X;
}function o(X,aE){var Y=U(aE);
Y.left=-Y.left;
Y.top=-Y.top;
Y.right=-Y.right;
Y.bottom=-Y.bottom;
return n(X,Y);
}F.ui.plugin(ar);
F.ui.plugin(ae);
F.ExportMixin.extend(Q.fn);
G(F,{Gauge:Q,RadialPointer:at,LinearPointer:af,ArrowLinearPointer:s,BarLinearPointer:x,LinearScale:ag,RadialScale:av,LinearGauge:ae,RadialGauge:ar});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
