(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/location",["kendo.drawing"],l);
}(function(){(function(k,F){var x=Math,l=x.abs,m=x.atan,n=x.atan2,p=x.cos,y=x.max,z=x.min,C=x.sin,E=x.tan,v=window.kendo,o=v.Class,q=v.dataviz,r=v.deepExtend,G=v.util,s=G.defined,t=G.deg,A=G.rad,B=G.round,D=G.sqr,H=G.valueOrDefault;
var w=o.extend({init:function(I,J){if(arguments.length===1){this.lat=I[0];
this.lng=I[1];
}else{this.lat=I;
this.lng=J;
}},DISTANCE_ITERATIONS:100,DISTANCE_CONVERGENCE:1e-12,DISTANCE_PRECISION:2,FORMAT:"{0:N6},{1:N6}",toArray:function(){return[this.lat,this.lng];
},equals:function(I){return I&&I.lat===this.lat&&I.lng===this.lng;
},clone:function(){return new w(this.lat,this.lng);
},round:function(I){this.lng=B(this.lng,I);
this.lat=B(this.lat,I);
return this;
},wrap:function(){this.lng=this.lng%180;
this.lat=this.lat%90;
return this;
},distanceTo:function(J,I){return this.greatCircleTo(J,I).distance;
},destination:function(K,I,J){I=A(I);
J=J||q.map.datums.WGS84;
var M=A(this.lat);
var N=A(this.lng);
var L=K/v.dataviz.map.datums.WGS84.a;
var O=x.asin(C(M)*p(L)+p(M)*C(L)*p(I));
var P=N+n(C(I)*C(L)*p(M),p(L)-C(M)*C(O));
return new w(t(O),t(P));
},greatCircleTo:function(Z,X){Z=w.create(Z);
X=X||q.map.datums.WGS84;
if(!Z||this.clone().round(8).equals(Z.clone().round(8))){return{distance:0,azimuthFrom:0,azimuthTo:0};
}var I=X.a;
var N=X.b;
var aa=X.f;
var ac=A(Z.lng-this.lng);
var al=m((1-aa)*E(A(this.lat)));
var aj=C(al);
var V=p(al);
var an=m((1-aa)*E(A(Z.lat)));
var ak=C(an);
var W=p(an);
var ad=ac;
var ae;
var ab=this.DISTANCE_ITERATIONS;
var Q=false;
var ah;
var T;
var ai;
var S;
var U;
var R;
var af;
while(!Q&&ab-->0){ah=C(ad);
T=p(ad);
ai=x.sqrt(D(W*ah)+D(V*ak-aj*W*T));
U=aj*ak+V*W*T;
af=n(ai,U);
var ag=V*W*ah/ai;
S=1-D(ag);
R=0;
if(S!==0){R=U-2*aj*ak/S;
}ae=ad;
var P=aa/16*S*(4+aa*(4-3*S));
ad=ac+(1-P)*aa*ag*(af+P*ai*(R+P*U*(-1+2*D(R))));
Q=l(ad-ae)<=this.DISTANCE_CONVERGENCE;
}var am=S*(D(I)-D(N))/D(N);
var J=1+am/16384*(4096+am*(-768+am*(320-175*am)));
var O=am/1024*(256+am*(-128+am*(74-47*am)));
var Y=O*ai*(R+O/4*(U*(-1+2*D(R))-O/6*R*(-3+4*D(ai))*(-3+4*D(R))));
var K=n(W*ah,V*ak-aj*W*T);
var M=n(V*ah,-aj*W+V*ak*T);
return{distance:B(N*J*(af-Y),this.DISTANCE_PRECISION),azimuthFrom:t(K),azimuthTo:t(M)};
}});
w.fn.toString=function(){return v.format(this.FORMAT,this.lat,this.lng);
};
w.fromLngLat=function(I){return new w(I[1],I[0]);
};
w.fromLatLng=function(I){return new w(I[0],I[1]);
};
w.create=function(I,J){if(s(I)){if(I instanceof w){return I.clone();
}else{if(arguments.length===1&&I.length===2){return w.fromLatLng(I);
}else{return new w(I,J);
}}}};
var u=o.extend({init:function(I,J){I=w.create(I);
J=w.create(J);
if(I.lng+180>J.lng+180&&I.lat+90<J.lat+90){this.se=I;
this.nw=J;
}else{this.se=J;
this.nw=I;
}},contains:function(K){var L=this.nw,M=this.se,J=H(K.lng,K[1]),I=H(K.lat,K[0]);
return K&&J+180>=L.lng+180&&J+180<=M.lng+180&&I+90>=M.lat+90&&I+90<=L.lat+90;
},center:function(){var K=this.nw;
var L=this.se;
var J=K.lng+(L.lng-K.lng)/2;
var I=K.lat+(L.lat-K.lat)/2;
return new w(I,J);
},containsAny:function(J){var K=false;
for(var I=0;
I<J.length;
I++){K=K||this.contains(J[I]);
}return K;
},include:function(K){var L=this.nw,M=this.se,J=H(K.lng,K[1]),I=H(K.lat,K[0]);
L.lng=z(L.lng,J);
L.lat=y(L.lat,I);
M.lng=y(M.lng,J);
M.lat=z(M.lat,I);
},includeAll:function(J){for(var I=0;
I<J.length;
I++){this.include(J[I]);
}},edges:function(){var I=this.nw,J=this.se;
return{nw:this.nw,ne:new w(I.lat,J.lng),se:this.se,sw:new w(J.lat,I.lng)};
},toArray:function(){var I=this.nw,J=this.se;
return[I,new w(I.lat,J.lng),J,new w(J.lat,I.lng)];
},overlaps:function(I){return this.containsAny(I.toArray())||I.containsAny(this.toArray());
}});
u.World=new u([90,-180],[-90,180]);
u.create=function(I,J){if(I instanceof u){return I;
}else{if(I&&J){return new u(I,J);
}else{if(I&&I.length===4&&!J){return new u([I[0],I[1]],[I[2],I[3]]);
}}}};
r(q,{map:{Extent:u,Location:w}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/attribution",["kendo.drawing"],l);
}(function(){(function(){var m=window.kendo,p=m.ui.Widget,n=m.template,o=m.util.valueOrDefault,l=m.util.defined;
var k=p.extend({init:function(q,r){p.fn.init.call(this,q,r);
this._initOptions(r);
this.items=[];
this.element.addClass("k-widget k-attribution");
},options:{name:"Attribution",separator:"&nbsp;|&nbsp;",itemTemplate:"#= text #"},filter:function(q,r){this._extent=q;
this._zoom=r;
this._render();
},add:function(q){if(l(q)){if(typeof q==="string"){q={text:q};
}this.items.push(q);
this._render();
}},remove:function(t){var s=[];
for(var q=0;
q<this.items.length;
q++){var r=this.items[q];
if(r.text!==t){s.push(r);
}}this.items=s;
this._render();
},clear:function(){this.items=[];
this.element.empty();
},_render:function(){var t=[];
var s=n(this.options.itemTemplate);
for(var q=0;
q<this.items.length;
q++){var r=this.items[q];
var u=this._itemText(r);
if(u!==""){t.push(s({text:u}));
}}if(t.length>0){this.element.empty().append(t.join(this.options.separator)).show();
}else{this.element.hide();
}},_itemText:function(s){var t="";
var r=this._inZoomLevel(s.minZoom,s.maxZoom);
var q=this._inArea(s.extent);
if(r&&q){t+=s.text;
}return t;
},_inZoomLevel:function(r,q){var s=true;
r=o(r,-Number.MAX_VALUE);
q=o(q,Number.MAX_VALUE);
s=this._zoom>r&&this._zoom<q;
return s;
},_inArea:function(q){var r=true;
if(q){r=q.contains(this._extent);
}return r;
}});
m.dataviz.ui.plugin(k);
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/navigator",["kendo.core"],l);
}(function(){(function(k){var n=window.kendo;
var s=n.ui.Widget;
var o=n.keys;
var r=k.proxy;
var q=".kendoNavigator";
function l(t){return n.format('<button class="k-button k-navigator-{0}"><span class="k-icon k-i-arrow-{0}"/></button>',t);
}var m=l("n")+l("e")+l("s")+l("w");
var p=s.extend({init:function(t,u){s.fn.init.call(this,t,u);
this._initOptions(u);
this.element.addClass("k-widget k-header k-shadow k-navigator").append(m).on("click"+q,".k-button",r(this,"_click"));
var v=this.element.parent().closest("["+n.attr("role")+"]");
this._keyroot=v.length>0?v:this.element;
this._tabindex(this._keyroot);
this._keydown=r(this._keydown,this);
this._keyroot.on("keydown",this._keydown);
},options:{name:"Navigator",panStep:1},events:["pan"],dispose:function(){this._keyroot.off("keydown",this._keydown);
},_pan:function(u,v){var t=this.options.panStep;
this.trigger("pan",{x:u*t,y:v*t});
},_click:function(u){var v=0;
var w=0;
var t=k(u.currentTarget);
if(t.is(".k-navigator-n")){w=1;
}else{if(t.is(".k-navigator-s")){w=-1;
}else{if(t.is(".k-navigator-e")){v=1;
}else{if(t.is(".k-navigator-w")){v=-1;
}}}}this._pan(v,w);
u.preventDefault();
},_keydown:function(t){switch(t.which){case o.UP:this._pan(0,1);
t.preventDefault();
break;
case o.DOWN:this._pan(0,-1);
t.preventDefault();
break;
case o.RIGHT:this._pan(1,0);
t.preventDefault();
break;
case o.LEFT:this._pan(-1,0);
t.preventDefault();
break;
}}});
n.dataviz.ui.plugin(p);
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/zoom",["kendo.core"],l);
}(function(){(function(k){var p=window.kendo;
var v=p.ui.Widget;
var q=p.keys;
var u=k.proxy;
function l(x,y){return p.format('<button class="k-button k-zoom-{0}" title="zoom-{0}">{1}</button>',x,y);
}var s=".kendoZoomControl";
var m=l("in","+")+l("out","-");
var t=187;
var r=189;
var o=61;
var n=173;
var w=v.extend({init:function(x,y){v.fn.init.call(this,x,y);
this._initOptions(y);
this.element.addClass("k-widget k-zoom-control k-button-wrap k-buttons-horizontal").append(m).on("click"+s,".k-button",u(this,"_click"));
var z=this.element.parent().closest("["+p.attr("role")+"]");
this._keyroot=z.length>0?z:this.element;
this._tabindex(this._keyroot);
this._keydown=u(this._keydown,this);
this._keyroot.on("keydown",this._keydown);
},options:{name:"ZoomControl",zoomStep:1},events:["change"],_change:function(x){var y=this.options.zoomStep;
this.trigger("change",{delta:x*y});
},_click:function(z){var x=k(z.currentTarget);
var y=1;
if(x.is(".k-zoom-out")){y=-1;
}this._change(y);
z.preventDefault();
},_keydown:function(x){switch(x.which){case q.NUMPAD_PLUS:case t:case o:this._change(1);
break;
case q.NUMPAD_MINUS:case r:case n:this._change(-1);
break;
}}});
p.dataviz.ui.plugin(w);
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/crs",["dataviz/map/location","kendo.drawing"],l);
}(function(){(function(k,N){var C=Math,l=C.atan,v=C.exp,I=C.pow,K=C.sin,A=C.log,M=C.tan,x=window.kendo,m=x.Class,n=x.dataviz,o=x.deepExtend,w=x.geometry,H=w.Point,B=n.map,z=B.Location,O=x.util,J=O.rad,p=O.deg,y=O.limitValue;
var E=C.PI,F=E/2,G=E/4,q=E/180;
var P={a:6378137,b:6356752.314245179,f:0.003352810664747481,e:0.08181919084262149};
var D=m.extend({init:function(Q){this._initOptions(Q);
},MAX_LNG:180,MAX_LAT:85.0840590501,INVERSE_ITERATIONS:15,INVERSE_CONVERGENCE:1e-12,options:{centralMeridian:0,datum:P},forward:function(V,Q){var X=this,W=X.options,R=W.datum,Y=R.a,U=W.centralMeridian,S=y(V.lat,-X.MAX_LAT,X.MAX_LAT),T=Q?y(V.lng,-X.MAX_LNG,X.MAX_LNG):V.lng,Z=J(T-U)*Y,aa=X._projectLat(S);
return new H(Z,aa);
},_projectLat:function(T){var R=this.options.datum,S=R.e,V=R.a,X=J(T),W=M(G+X/2),Q=S*K(X),U=I((1-Q)/(1+Q),S/2);
return V*A(W*U);
},inverse:function(W,Q){var X=this,V=X.options,R=V.datum,Y=R.a,U=V.centralMeridian,T=W.x/(q*Y)+U,S=y(X._inverseY(W.y),-X.MAX_LAT,X.MAX_LAT);
if(Q){T=y(T,-X.MAX_LNG,X.MAX_LNG);
}return new z(S,T);
},_inverseY:function(ab){var Y=this,R=Y.options.datum,Z=R.a,T=R.e,U=T/2,aa=v(-ab/Z),X=F-2*l(aa),V;
for(V=0;
V<=Y.INVERSE_ITERATIONS;
V++){var Q=T*K(X),W=I((1-Q)/(1+Q),U),S=F-2*l(aa*W)-X;
X+=S;
if(C.abs(S)<=Y.INVERSE_CONVERGENCE){break;
}}return p(X);
}});
var L=D.extend({MAX_LAT:85.0511287798,_projectLat:function(Q){var R=this.options.datum.a,T=J(Q),S=M(G+T/2);
return R*A(S);
},_inverseY:function(S){var Q=this.options.datum.a,R=v(-S/Q);
return p(F-2*l(R));
}});
var u=m.extend({forward:function(Q){return new H(Q.lng,Q.lat);
},inverse:function(Q){return new z(Q.y,Q.x);
}});
var s=m.extend({init:function(){var R=this,S=R._proj=new L();
var Q=this.c=2*E*S.options.datum.a;
this._tm=w.transform().translate(0.5,0.5).scale(1/Q,-1/Q);
this._itm=w.transform().scale(Q,-Q).translate(-0.5,-0.5);
},toPoint:function(R,T,Q){var S=this._proj.forward(R,Q);
return S.transform(this._tm).scale(T||1);
},toLocation:function(R,S,Q){R=R.clone().scale(1/(S||1)).transform(this._itm);
return this._proj.inverse(R,Q);
}});
var r=m.extend({init:function(){this._proj=new D();
},toPoint:function(Q){return this._proj.forward(Q);
},toLocation:function(Q){return this._proj.inverse(Q);
}});
var t=m.extend({init:function(){this._proj=new u();
},toPoint:function(Q){return this._proj.forward(Q);
},toLocation:function(Q){return this._proj.inverse(Q);
}});
o(n,{map:{crs:{EPSG3395:r,EPSG3857:s,EPSG4326:t},datums:{WGS84:P},projections:{Equirectangular:u,Mercator:D,SphericalMercator:L}}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/base",["kendo.core","dataviz/map/location"],l);
}(function(){(function(k,t){var s=k.proxy,q=window.kendo,l=q.Class,m=q.dataviz,n=q.deepExtend,p=m.map.Extent,u=q.util,o=u.defined;
var r=l.extend({init:function(v,w){this._initOptions(w);
this.map=v;
this.element=k("<div class='k-layer'></div>").css({zIndex:this.options.zIndex,opacity:this.options.opacity}).appendTo(v.scrollElement);
this._beforeReset=s(this._beforeReset,this);
this._reset=s(this._reset,this);
this._resize=s(this._resize,this);
this._panEnd=s(this._panEnd,this);
this._activate();
this._updateAttribution();
},destroy:function(){this._deactivate();
},show:function(){this.reset();
this._activate();
this._applyExtent(true);
},hide:function(){this._deactivate();
this._setVisibility(false);
},reset:function(){this._beforeReset();
this._reset();
},_reset:function(){this._applyExtent();
},_beforeReset:k.noop,_resize:k.noop,_panEnd:function(){this._applyExtent();
},_applyExtent:function(){var z=this.options;
var A=this.map.zoom();
var y=!o(z.minZoom)||A>=z.minZoom;
var x=!o(z.maxZoom)||A<=z.maxZoom;
var v=p.create(z.extent);
var w=!v||v.overlaps(this.map.extent());
this._setVisibility(y&&x&&w);
},_setVisibility:function(v){this.element.css("display",v?"":"none");
},_activate:function(){var v=this.map;
v.bind("beforeReset",this._beforeReset);
v.bind("reset",this._reset);
v.bind("resize",this._resize);
v.bind("panEnd",this._panEnd);
},_deactivate:function(){var v=this.map;
v.unbind("beforeReset",this._beforeReset);
v.unbind("reset",this._reset);
v.unbind("resize",this._resize);
v.unbind("panEnd",this._panEnd);
},_updateAttribution:function(){var v=this.map.attribution;
if(v){v.add(this.options.attribution);
}}});
n(m,{map:{layers:{Layer:r}}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/shape",["dataviz/map/layers/base","dataviz/map/location"],l);
}(function(){(function(k,B){var z=k.proxy,u=window.kendo,l=u.Class,n=u.data.DataSource,o=u.dataviz,p=u.deepExtend,v=u.util.last,q=u.util.defined,r=u.geometry,m=u.drawing,t=m.Group,y=o.map,x=y.Location,w=y.layers.Layer;
var A=w.extend({init:function(C,D){w.fn.init.call(this,C,D);
this.surface=m.Surface.create(this.element,{width:C.scrollElement.width(),height:C.scrollElement.height()});
this._initRoot();
this.movable=new u.ui.Movable(this.surface.element);
this._markers=[];
this._click=this._handler("shapeClick");
this.surface.bind("click",this._click);
this._mouseenter=this._handler("shapeMouseEnter");
this.surface.bind("mouseenter",this._mouseenter);
this._mouseleave=this._handler("shapeMouseLeave");
this.surface.bind("mouseleave",this._mouseleave);
this._initDataSource();
},options:{autoBind:true},destroy:function(){w.fn.destroy.call(this);
this.surface.destroy();
this.dataSource.unbind("change",this._dataChange);
},setDataSource:function(C){if(this.dataSource){this.dataSource.unbind("change",this._dataChange);
}this.dataSource=u.data.DataSource.create(C);
this.dataSource.bind("change",this._dataChange);
if(this.options.autoBind){this.dataSource.fetch();
}},_reset:function(){w.fn._reset.call(this);
this._translateSurface();
if(this._data){this._load(this._data);
}},_initRoot:function(){this._root=new t();
this.surface.draw(this._root);
},_beforeReset:function(){this.surface.clear();
this._initRoot();
},_resize:function(){this.surface.size(this.map.size());
},_initDataSource:function(){var C=this.options.dataSource;
this._dataChange=z(this._dataChange,this);
this.dataSource=n.create(C).bind("change",this._dataChange);
if(C&&this.options.autoBind){this.dataSource.fetch();
}},_dataChange:function(C){this._data=C.sender.view();
this._load(this._data);
},_load:function(D){this._clearMarkers();
if(!this._loader){this._loader=new s(this.map,this.options.style,this);
}var C=new t();
for(var E=0;
E<D.length;
E++){var F=this._loader.parse(D[E]);
if(F){C.append(F);
}}this._root.clear();
this._root.append(C);
},shapeCreated:function(E){var D=false;
if(E instanceof m.Circle){D=q(this._createMarker(E));
}if(!D){var C={layer:this,shape:E};
D=this.map.trigger("shapeCreated",C);
}return D;
},_createMarker:function(D){var C=this.map.markers.bind({location:D.location},D.dataItem);
if(C){this._markers.push(C);
}return C;
},_clearMarkers:function(){for(var C=0;
C<this._markers.length;
C++){this.map.markers.remove(this._markers[C]);
}this._markers=[];
},_panEnd:function(C){w.fn._panEnd.call(this,C);
this._translateSurface();
},_translateSurface:function(){var C=this.map;
var D=C.locationToView(C.extent().nw);
if(this.surface.translate){this.surface.translate(D);
this.movable.moveTo({x:D.x,y:D.y});
}},_handler:function(C){var D=this;
return function(F){if(F.element){var E={layer:D,shape:F.element,originalEvent:F.originalEvent};
D.map.trigger(C,E);
}};
}});
var s=l.extend({init:function(D,C,E){this.observer=E;
this.locator=D;
this.style=C;
},parse:function(C){var D=new t();
if(C.type==="Feature"){this._loadGeometryTo(D,C.geometry,C);
}else{this._loadGeometryTo(D,C,C);
}if(D.children.length<2){D=D.children[0];
}return D;
},_shapeCreated:function(D){var C=false;
if(this.observer&&this.observer.shapeCreated){C=this.observer.shapeCreated(D);
}return C;
},_loadGeometryTo:function(C,F,E){var D=F.coordinates;
var G;
var H;
switch(F.type){case"LineString":H=this._loadPolygon(C,[D],E);
this._setLineFill(H);
break;
case"MultiLineString":for(G=0;
G<D.length;
G++){H=this._loadPolygon(C,[D[G]],E);
this._setLineFill(H);
}break;
case"Polygon":this._loadPolygon(C,D,E);
break;
case"MultiPolygon":for(G=0;
G<D.length;
G++){this._loadPolygon(C,D[G],E);
}break;
case"Point":this._loadPoint(C,D,E);
break;
case"MultiPoint":for(G=0;
G<D.length;
G++){this._loadPoint(C,D[G],E);
}break;
}},_setLineFill:function(C){var D=C.segments;
if(D.length<4||!D[0].anchor().equals(v(D).anchor())){C.options.fill=null;
}},_loadShape:function(C,D){if(!this._shapeCreated(D)){C.append(D);
}return D;
},_loadPolygon:function(C,E,D){var F=this._buildPolygon(E);
F.dataItem=D;
return this._loadShape(C,F);
},_buildPolygon:function(G){var H=G.length>1?m.MultiPath:m.Path;
var E=new H(this.style);
for(var C=0;
C<G.length;
C++){for(var D=0;
D<G[C].length;
D++){var F=this.locator.locationToView(x.fromLngLat(G[C][D]));
if(D===0){E.moveTo(F.x,F.y);
}else{E.lineTo(F.x,F.y);
}}}return E;
},_loadPoint:function(D,E,F){var G=x.fromLngLat(E);
var H=this.locator.locationToView(G);
var C=new r.Circle(H,10);
var I=new m.Circle(C,this.style);
I.dataItem=F;
I.location=G;
return this._loadShape(D,I);
}});
p(u.data,{schemas:{geojson:{type:"json",data:function(C){if(C.type==="FeatureCollection"){return C.features;
}if(C.type==="GeometryCollection"){return C.geometries;
}return C;
}}},transports:{geojson:{read:{dataType:"json"}}}});
p(o,{map:{layers:{shape:A,ShapeLayer:A},GeoJSONLoader:s}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/bubble",["dataviz/map/layers/shape"],l);
}(function(){(function(k,y){var s=window.kendo,r=s.getter,n=s.dataviz,o=s.deepExtend,z=s.util,p=z.defined,q=s.geometry,m=s.drawing,u=n.map,t=u.Location,v=u.layers.ShapeLayer;
var l=v.extend({options:{autoBind:true,locationField:"location",valueField:"value",minSize:0,maxSize:100,scale:"sqrt",symbol:"circle"},_load:function(B){this.surface.clear();
if(B.length===0){return;
}var G=this.options;
var D=r(G.valueField);
B=B.slice(0);
B.sort(function(M,N){return D(N)-D(M);
});
var I=this._scaleType();
var H;
for(var E=0;
E<B.length;
E++){var C=B[E];
var F=r(G.locationField)(C);
var L=r(G.valueField)(C);
if(p(F)&&p(L)){if(!H){H=new I([0,L],[G.minSize,G.maxSize]);
}F=t.create(F);
var A=this.map.locationToView(F);
var J=H.map(L);
var K=this._createSymbol({center:A,size:J,style:G.style,dataItem:C,location:F});
K.dataItem=C;
K.location=F;
K.value=L;
this._drawSymbol(K);
}}},_scaleType:function(){var A=this.options.scale;
if(s.isFunction(A)){return A;
}return n.map.scales[A];
},_createSymbol:function(A){var B=this.options.symbol;
if(!s.isFunction(B)){B=n.map.symbols[B];
}return B(A);
},_drawSymbol:function(C){var A={layer:this,shape:C};
var B=this.map.trigger("shapeCreated",A);
if(!B){this.surface.draw(C);
}}});
var w=s.Class.extend({init:function(A,D){this._domain=A;
this._range=D;
var B=Math.sqrt(A[1])-Math.sqrt(A[0]);
var C=D[1]-D[0];
this._ratio=C/B;
},map:function(B){var A=(Math.sqrt(B)-Math.sqrt(this._domain[0]))*this._ratio;
return this._range[0]+A;
}});
var x={circle:function(A){var B=new q.Circle(A.center,A.size/2);
return new m.Circle(B,A.style);
},square:function(A){var D=new m.Path(A.style);
var C=A.size/2;
var B=A.center;
D.moveTo(B.x-C,B.y-C).lineTo(B.x+C,B.y-C).lineTo(B.x+C,B.y+C).lineTo(B.x-C,B.y+C).close();
return D;
}};
o(n,{map:{layers:{bubble:l,BubbleLayer:l},scales:{sqrt:w},symbols:x}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/tile",["dataviz/map/layers/base","dataviz/map/location"],l);
}(function(){(function(k,D){var t=Math,v=k.proxy,q=window.kendo,l=q.Class,z=q.template,m=q.dataviz,n=q.deepExtend,o=q.geometry,u=o.Point,r=m.map.layers.Layer,E=q.util,x=E.round,w=E.renderSize,s=E.limitValue;
var A=r.extend({init:function(F,G){r.fn.init.call(this,F,G);
if(typeof this.options.subdomains==="string"){this.options.subdomains=this.options.subdomains.split("");
}var H=this._viewType();
this._view=new H(this.element,this.options);
},destroy:function(){r.fn.destroy.call(this);
this._view.destroy();
this._view=null;
},_beforeReset:function(){var F=this.map;
var G=F.locationToLayer(F.extent().nw).round();
this._view.viewOrigin(G);
},_reset:function(){r.fn._reset.call(this);
this._updateView();
this._view.reset();
},_viewType:function(){return C;
},_activate:function(){r.fn._activate.call(this);
if(!q.support.mobileOS){if(!this._pan){this._pan=q.throttle(v(this._render,this),100);
}this.map.bind("pan",this._pan);
}},_deactivate:function(){r.fn._deactivate.call(this);
if(this._pan){this.map.unbind("pan",this._pan);
}},_updateView:function(){var I=this._view,H=this.map,F=H.extent(),G={nw:H.locationToLayer(F.nw).round(),se:H.locationToLayer(F.se).round()};
I.center(H.locationToLayer(H.center()));
I.extent(G);
I.zoom(H.zoom());
},_resize:function(){this._render();
},_panEnd:function(F){r.fn._panEnd.call(this,F);
this._render();
},_render:function(){this._updateView();
this._view.render();
}});
var C=l.extend({init:function(F,G){this.element=F;
this._initOptions(G);
this.pool=new B();
},options:{tileSize:256,subdomains:["a","b","c"],urlTemplate:""},center:function(F){this._center=F;
},extent:function(F){this._extent=F;
},viewOrigin:function(F){this._viewOrigin=F;
},zoom:function(F){this._zoom=F;
},pointToTileIndex:function(F){return new u(t.floor(F.x/this.options.tileSize),t.floor(F.y/this.options.tileSize));
},tileCount:function(){var I=this.size(),F=this.pointToTileIndex(this._extent.nw),G=this._extent.nw,H=this.indexToPoint(F).translate(-G.x,-G.y);
return{x:t.ceil((t.abs(H.x)+I.width)/this.options.tileSize),y:t.ceil((t.abs(H.y)+I.height)/this.options.tileSize)};
},size:function(){var G=this._extent.nw,H=this._extent.se,F=H.clone().translate(-G.x,-G.y);
return{width:F.x,height:F.y};
},indexToPoint:function(F){var G=F.x,H=F.y;
return new u(G*this.options.tileSize,H*this.options.tileSize);
},subdomainText:function(){var F=this.options.subdomains;
return F[this.subdomainIndex++%F.length];
},destroy:function(){this.element.empty();
this.pool.empty();
},reset:function(){this.pool.reset();
this.subdomainIndex=0;
this.render();
},render:function(){var G=this.tileCount(),F=this.pointToTileIndex(this._extent.nw),H,I,J;
for(I=0;
I<G.x;
I++){for(J=0;
J<G.y;
J++){H=this.createTile({x:F.x+I,y:F.y+J});
if(!H.visible){H.show();
}}}},createTile:function(F){var G=this.tileOptions(F);
var H=this.pool.get(this._center,G);
if(H.element.parent().length===0){this.element.append(H.element);
}return H;
},tileOptions:function(F){var G=this.wrapIndex(F),J=this.indexToPoint(F),I=this._viewOrigin,H=J.clone().translate(-I.x,-I.y);
return{index:G,currentIndex:F,point:J,offset:y(H),zoom:this._zoom,size:this.options.tileSize,subdomain:this.subdomainText(),urlTemplate:this.options.urlTemplate,errorUrlTemplate:this.options.errorUrlTemplate};
},wrapIndex:function(G){var F=t.pow(2,this._zoom);
return{x:this.wrapValue(G.x,F),y:s(G.y,0,F-1)};
},wrapValue:function(H,F){var G=t.abs(H)%F;
if(H>=0){H=G;
}else{H=F-(G===0?F:G);
}return H;
}});
var p=l.extend({init:function(F,G){this.id=F;
this.visible=true;
this._initOptions(G);
this.createElement();
this.show();
},options:{urlTemplate:"",errorUrlTemplate:""},createElement:function(){this.element=k("<img style='position: absolute; display: block;' />").css({width:this.options.size,height:this.options.size}).error(v(function(F){if(this.errorUrl()){F.target.setAttribute("src",this.errorUrl());
}else{F.target.removeAttribute("src");
}},this));
},show:function(){var F=this.element[0];
F.style.top=w(this.options.offset.y);
F.style.left=w(this.options.offset.x);
var G=this.url();
if(G){F.setAttribute("src",G);
}F.style.visibility="visible";
this.visible=true;
},hide:function(){this.element[0].style.visibility="hidden";
this.visible=false;
},url:function(){var F=z(this.options.urlTemplate);
return F(this.urlOptions());
},errorUrl:function(){var F=z(this.options.errorUrlTemplate);
return F(this.urlOptions());
},urlOptions:function(){var F=this.options;
return{zoom:F.zoom,subdomain:F.subdomain,z:F.zoom,x:F.index.x,y:F.index.y,s:F.subdomain,quadkey:F.quadkey,q:F.quadkey,culture:F.culture,c:F.culture};
},destroy:function(){if(this.element){this.element.remove();
this.element=null;
}}});
var B=l.extend({init:function(){this._items=[];
},options:{maxSize:100},get:function(F,G){if(this._items.length>=this.options.maxSize){this._remove(F);
}return this._create(G);
},empty:function(){var G=this._items;
for(var F=0;
F<G.length;
F++){G[F].destroy();
}this._items=[];
},reset:function(){var G=this._items;
for(var F=0;
F<G.length;
F++){G[F].hide();
}},_create:function(I){var H=this._items;
var J;
var G=E.hashKey(I.point.toString()+I.offset.toString()+I.zoom+I.urlTemplate);
for(var F=0;
F<H.length;
F++){if(H[F].id===G){J=H[F];
}}if(J){J.show();
}else{J=new p(G,I);
this._items.push(J);
}return J;
},_remove:function(F){var J=this._items;
var K=-1;
var I=-1;
for(var H=0;
H<J.length;
H++){var G=J[H].options.point.distanceTo(F);
if(G>K){I=H;
K=G;
}}if(I!==-1){J[I].destroy();
J.splice(I,1);
}}});
function y(F){return new u(x(F.x),x(F.y));
}n(m,{map:{layers:{tile:A,TileLayer:A,ImageTile:p,TilePool:B,TileView:C}}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/bing",["dataviz/map/layers/tile"],l);
}(function(){(function(k,v){var r=window.kendo,n=r.dataviz,o=r.deepExtend,p=r.util.defined,q=n.map.Extent,s=n.map.Location,t=n.map.layers.TileLayer,u=n.map.layers.TileView;
var l=t.extend({init:function(w,x){t.fn.init.call(this,w,x);
this._onMetadata=k.proxy(this._onMetadata,this);
this._fetchMetadata();
},options:{baseUrl:"//dev.virtualearth.net/REST/v1/Imagery/Metadata/",imagerySet:"road"},_fetchMetadata:function(){var w=this.options;
if(!w.key){throw new Error("Bing tile layer: API key is required");
}k.ajax({url:w.baseUrl+w.imagerySet,data:{output:"json",include:"ImageryProviders",key:w.key,uriScheme:this._scheme(window.location.protocol)},type:"get",dataType:"jsonp",jsonp:"jsonp",success:this._onMetadata});
},_scheme:function(w){return w.replace(":","")==="https"?"https":"http";
},_onMetadata:function(w){if(w&&w.resourceSets.length){var y=this.resource=w.resourceSets[0].resources[0];
o(this._view.options,{urlTemplate:y.imageUrl.replace("{subdomain}","#= subdomain #").replace("{quadkey}","#= quadkey #").replace("{culture}","#= culture #"),subdomains:y.imageUrlSubdomains});
var x=this.options;
if(!p(x.minZoom)){x.minZoom=y.zoomMin;
}if(!p(x.maxZoom)){x.maxZoom=y.zoomMax;
}this._addAttribution();
if(this.element.css("display")!=="none"){this._reset();
}}},_viewType:function(){return m;
},_addAttribution:function(){var x=this.map.attribution;
if(x){var B=this.resource.imageryProviders;
if(B){for(var z=0;
z<B.length;
z++){var A=B[z];
for(var C=0;
C<A.coverageAreas.length;
C++){var w=A.coverageAreas[C];
x.add({text:A.attribution,minZoom:w.zoomMin,maxZoom:w.zoomMax,extent:new q(new s(w.bbox[2],w.bbox[1]),new s(w.bbox[0],w.bbox[3]))});
}}}}},imagerySet:function(w){if(w){this.options.imagerySet=w;
this.map.attribution.clear();
this._fetchMetadata();
}else{return this.options.imagerySet;
}}});
var m=u.extend({options:{culture:"en-US"},tileOptions:function(w){var x=u.fn.tileOptions.call(this,w);
x.culture=this.options.culture;
x.quadkey=this.tileQuadKey(this.wrapIndex(w));
return x;
},tileQuadKey:function(y){var A="",w,z,x;
for(x=this._zoom;
x>0;
x--){w=0;
z=1<<x-1;
if((y.x&z)!==0){w++;
}if((y.y&z)!==0){w+=2;
}A+=w;
}return A;
}});
o(n,{map:{layers:{bing:l,BingLayer:l,BingView:m}}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/layers/marker",["dataviz/map/layers/base","dataviz/map/location","kendo.data","kendo.tooltip"],l);
}(function(){(function(k,A){var p=document,x=Math,q=k.inArray,y=k.proxy,r=window.kendo,l=r.Class,m=r.data.DataSource,z=r.ui.Tooltip,n=r.dataviz,o=r.deepExtend,u=n.map,t=u.Location,s=u.layers.Layer;
var w=s.extend({init:function(B,C){s.fn.init.call(this,B,C);
this._markerClick=y(this._markerClick,this);
this.element.on("click",".k-marker",this._markerClick);
this.items=[];
this._initDataSource();
},destroy:function(){s.fn.destroy.call(this);
this.element.off("click",".k-marker",this._markerClick);
this.dataSource.unbind("change",this._dataChange);
this.clear();
},options:{zIndex:1000,autoBind:true,dataSource:{},locationField:"location",titleField:"title"},add:function(B){if(k.isArray(B)){for(var C=0;
C<B.length;
C++){this._addOne(B[C]);
}}else{return this._addOne(B);
}},remove:function(C){C.destroy();
var B=q(C,this.items);
if(B>-1){this.items.splice(B,1);
}},clear:function(){for(var B=0;
B<this.items.length;
B++){this.items[B].destroy();
}this.items=[];
},update:function(D){var C=D.location();
if(C){D.showAt(this.map.locationToView(C));
var B={marker:D,layer:this};
this.map.trigger("markerActivate",B);
}},_reset:function(){s.fn._reset.call(this);
var C=this.items;
for(var B=0;
B<C.length;
B++){this.update(C[B]);
}},bind:function(F,D){var E=u.Marker.create(F,this.options);
E.dataItem=D;
var B={marker:E,layer:this};
var C=this.map.trigger("markerCreated",B);
if(!C){this.add(E);
return E;
}},setDataSource:function(B){if(this.dataSource){this.dataSource.unbind("change",this._dataChange);
}this.dataSource=r.data.DataSource.create(B);
this.dataSource.bind("change",this._dataChange);
if(this.options.autoBind){this.dataSource.fetch();
}},_addOne:function(B){var C=v.create(B,this.options);
C.addTo(this);
return C;
},_initDataSource:function(){var B=this.options.dataSource;
this._dataChange=y(this._dataChange,this);
this.dataSource=m.create(B).bind("change",this._dataChange);
if(B&&this.options.autoBind){this.dataSource.fetch();
}},_dataChange:function(B){this._load(B.sender.view());
},_load:function(B){this._data=B;
this.clear();
var D=r.getter(this.options.locationField);
var E=r.getter(this.options.titleField);
for(var F=0;
F<B.length;
F++){var C=B[F];
this.bind({location:D(C),title:E(C)},C);
}},_markerClick:function(C){var B={marker:k(C.target).data("kendoMarker"),layer:this};
this.map.trigger("markerClick",B);
}});
var v=l.extend({init:function(B){this.options=B||{};
},addTo:function(B){this.layer=B.markers||B;
this.layer.items.push(this);
this.layer.update(this);
},location:function(B){if(B){this.options.location=t.create(B).toArray();
if(this.layer){this.layer.update(this);
}return this;
}else{return t.create(this.options.location);
}},showAt:function(B){this.render();
this.element.css({left:x.round(B.x),top:x.round(B.y)});
if(this.tooltip&&this.tooltip.popup){this.tooltip.popup._position();
}},hide:function(){if(this.element){this.element.remove();
this.element=null;
}if(this.tooltip){this.tooltip.destroy();
this.tooltip=null;
}},destroy:function(){this.layer=null;
this.hide();
},render:function(){if(!this.element){var C=this.options;
var B=this.layer;
this.element=k(p.createElement("span")).addClass("k-marker k-marker-"+r.toHyphens(C.shape||"pin")).attr("title",C.title).attr(C.attributes||{}).data("kendoMarker",this).css("zIndex",C.zIndex);
if(B){B.element.append(this.element);
}this.renderTooltip();
}},renderTooltip:function(){var C=this;
var F=C.options.title;
var D=C.options.tooltip||{};
if(D&&z){var E=D.template;
if(E){var B=r.template(E);
D.content=function(G){G.location=C.location();
G.marker=C;
return B(G);
};
}if(F||D.content||D.contentUrl){this.tooltip=new z(this.element,D);
this.tooltip.marker=this;
}}}});
v.create=function(B,C){if(B instanceof v){return B;
}return new v(o({},C,B));
};
o(n,{map:{layers:{marker:w,MarkerLayer:w},Marker:v}});
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("dataviz/map/main",["dataviz/map/crs","dataviz/map/location"],l);
}(function(){(function(k,I){var p=document,A=Math,B=A.min,E=A.pow,F=k.proxy,v=window.kendo,M=v.ui.Widget,n=v.deepExtend,m=v.dataviz,H=m.ui,u=v.geometry,D=u.Point,y=m.map,r=y.Extent,x=y.Location,q=y.crs.EPSG3857,J=v.util,o=J.defined,w=J.limitValue,G=J.renderPos,K=J.valueOrDefault;
var l="k-",s=0.9,t=0.9300000000000001,C="DOMMouseScroll mousewheel",L=5;
var z=M.extend({init:function(N,O){v.destroy(N);
M.fn.init.call(this,N);
this._initOptions(O);
this.bind(this.events,O);
this.crs=new q();
this.element.addClass(l+this.options.name.toLowerCase()).css("position","relative").empty().append(p.createElement("div"));
this._viewOrigin=this._getOrigin();
this._initScroller();
this._initMarkers();
this._initControls();
this._initLayers();
this._reset();
this._mousewheel=F(this._mousewheel,this);
this.element.bind("click",F(this._click,this));
this.element.bind(C,this._mousewheel);
},options:{name:"Map",controls:{attribution:true,navigator:{panStep:100},zoom:true},layers:[],layerDefaults:{shape:{style:{fill:{color:"#fff"},stroke:{color:"#aaa",width:0.5}}},bubble:{style:{fill:{color:"#fff",opacity:0.5},stroke:{color:"#aaa",width:0.5}}},marker:{shape:"pinTarget",tooltip:{position:"top"}}},center:[0,0],zoom:3,minSize:256,minZoom:1,maxZoom:19,markers:[],markerDefaults:{shape:"pinTarget",tooltip:{position:"top"}},wraparound:true},events:["beforeReset","click","reset","pan","panEnd","markerActivate","markerClick","markerCreated","shapeClick","shapeCreated","shapeMouseEnter","shapeMouseLeave","zoomStart","zoomEnd"],destroy:function(){this.scroller.destroy();
if(this.navigator){this.navigator.destroy();
}if(this.attribution){this.attribution.destroy();
}if(this.zoomControl){this.zoomControl.destroy();
}this.markers.destroy();
for(var N=0;
N<this.layers.length;
N++){this.layers[N].destroy();
}M.fn.destroy.call(this);
},zoom:function(N){var O=this.options;
if(o(N)){N=A.round(w(N,O.minZoom,O.maxZoom));
if(O.zoom!==N){O.zoom=N;
this._reset();
}return this;
}else{return O.zoom;
}},center:function(N){if(N){this.options.center=x.create(N).toArray();
this._reset();
return this;
}else{return x.create(this.options.center);
}},extent:function(N){if(N){this._setExtent(N);
return this;
}else{return this._getExtent();
}},setOptions:function(N){M.fn.setOptions.call(this,N);
this._reset();
},locationToLayer:function(O,P){var N=!this.options.wraparound;
O=x.create(O);
return this.crs.toPoint(O,this._layerSize(P),N);
},layerToLocation:function(O,P){var N=!this.options.wraparound;
O=D.create(O);
return this.crs.toLocation(O,this._layerSize(P),N);
},locationToView:function(N){N=x.create(N);
var O=this.locationToLayer(this._viewOrigin);
var P=this.locationToLayer(N);
return P.translateWith(O.scale(-1));
},viewToLocation:function(O,P){var N=this.locationToLayer(this._getOrigin(),P);
O=D.create(O);
O=O.clone().translateWith(N);
return this.layerToLocation(O,P);
},eventOffset:function(N){var P=this.element.offset();
var O=N.originalEvent||N;
var Q=K(O.pageX,O.clientX)-P.left;
var R=K(O.pageY,O.clientY)-P.top;
return new u.Point(Q,R);
},eventToView:function(O){var N=this.eventOffset(O);
return this.locationToView(this.viewToLocation(N));
},eventToLayer:function(N){return this.locationToLayer(this.eventToLocation(N));
},eventToLocation:function(O){var N=this.eventOffset(O);
return this.viewToLocation(N);
},viewSize:function(){var N=this.element;
var O=this._layerSize();
var P=N.width();
if(!this.options.wraparound){P=B(O,P);
}return{width:P,height:B(O,N.height())};
},exportVisual:function(){this._reset();
return false;
},_setOrigin:function(N,Q){var O=this.viewSize(),P;
N=this._origin=x.create(N);
P=this.locationToLayer(N,Q);
P.x+=O.width/2;
P.y+=O.height/2;
this.options.center=this.layerToLocation(P,Q).toArray();
return this;
},_getOrigin:function(N){var O=this.viewSize(),P;
if(N||!this._origin){P=this.locationToLayer(this.center());
P.x-=O.width/2;
P.y-=O.height/2;
this._origin=this.layerToLocation(P);
}return this._origin;
},_setExtent:function(N){N=r.create(N);
this.center(N.center());
var T=this.element.width();
var O=this.element.height();
for(var U=this.options.maxZoom;
U>=this.options.minZoom;
U--){var R=this.locationToLayer(N.nw,U);
var S=this.locationToLayer(N.se,U);
var Q=A.abs(S.x-R.x);
var P=A.abs(S.y-R.y);
if(Q<=T&&P<=O){break;
}}this.zoom(U);
},_getExtent:function(){var O=this._getOrigin();
var N=this.locationToLayer(O);
var Q=this.viewSize();
N.x+=Q.width;
N.y+=Q.height;
var P=this.layerToLocation(N);
return new r(O,P);
},_zoomAround:function(O,N){this._setOrigin(this.layerToLocation(O,N),N);
this.zoom(N);
},_initControls:function(){var N=this.options.controls;
if(H.Attribution&&N.attribution){this._createAttribution(N.attribution);
}if(!v.support.mobileOS){if(H.Navigator&&N.navigator){this._createNavigator(N.navigator);
}if(H.ZoomControl&&N.zoom){this._createZoomControl(N.zoom);
}}},_createControlElement:function(O,N){var P=O.position||N;
var Q="."+G(P).replace(" ",".");
var R=k(".k-map-controls"+Q,this.element);
if(R.length===0){R=k("<div>").addClass("k-map-controls "+G(P)).appendTo(this.element);
}return k("<div>").appendTo(R);
},_createAttribution:function(O){var N=this._createControlElement(O,"bottomRight");
this.attribution=new H.Attribution(N,O);
},_createNavigator:function(P){var N=this._createControlElement(P,"topLeft");
var O=this.navigator=new H.Navigator(N,P);
this._navigatorPan=F(this._navigatorPan,this);
O.bind("pan",this._navigatorPan);
this._navigatorCenter=F(this._navigatorCenter,this);
O.bind("center",this._navigatorCenter);
},_navigatorPan:function(O){var Q=this;
var R=Q.scroller;
var T=R.scrollLeft+O.x;
var U=R.scrollTop-O.y;
var N=this._virtualSize;
var P=this.element.height();
var S=this.element.width();
T=w(T,N.x.min,N.x.max-S);
U=w(U,N.y.min,N.y.max-P);
Q.scroller.one("scroll",function(V){Q._scrollEnd(V);
});
Q.scroller.scrollTo(-T,-U);
},_navigatorCenter:function(){this.center(this.options.center);
},_createZoomControl:function(O){var N=this._createControlElement(O,"topLeft");
var P=this.zoomControl=new H.ZoomControl(N,O);
this._zoomControlChange=F(this._zoomControlChange,this);
P.bind("change",this._zoomControlChange);
},_zoomControlChange:function(N){if(!this.trigger("zoomStart",{originalEvent:N})){this.zoom(this.zoom()+N.delta);
this.trigger("zoomEnd",{originalEvent:N});
}},_initScroller:function(){var N=v.support.mobileOS?t:s;
var P=this.options.zoomable!==false;
var O=this.scroller=new v.mobile.ui.Scroller(this.element.children(0),{friction:N,velocityMultiplier:L,zoom:P,mousewheelScrolling:false});
O.bind("scroll",F(this._scroll,this));
O.bind("scrollEnd",F(this._scrollEnd,this));
O.userEvents.bind("gesturestart",F(this._scaleStart,this));
O.userEvents.bind("gestureend",F(this._scale,this));
this.scrollElement=O.scrollElement;
},_initLayers:function(){var O=this.options.layers,R=this.layers=[];
for(var P=0;
P<O.length;
P++){var S=O[P];
var T=S.type||"shape";
var N=this.options.layerDefaults[T];
var Q=m.map.layers[T];
R.push(new Q(this,n({},N,S)));
}},_initMarkers:function(){this.markers=new y.layers.MarkerLayer(this,this.options.markerDefaults);
this.markers.add(this.options.markers);
},_scroll:function(N){var Q=this.locationToLayer(this._viewOrigin).round();
var O=N.sender.movable;
var P=new u.Point(O.x,O.y).scale(-1).scale(1/O.scale);
Q.x+=P.x;
Q.y+=P.y;
this._scrollOffset=P;
this._setOrigin(this.layerToLocation(Q));
this.trigger("pan",{originalEvent:N,origin:this._getOrigin(),center:this.center()});
},_scrollEnd:function(N){if(!this._scrollOffset||!this._panComplete()){return;
}this._scrollOffset=null;
this._panEndTS=new Date();
this.trigger("panEnd",{originalEvent:N,origin:this._getOrigin(),center:this.center()});
},_panComplete:function(){return new Date()-(this._panEndTS||0)>50;
},_scaleStart:function(N){if(this.trigger("zoomStart",{originalEvent:N})){var O=N.touches[1];
if(O){O.cancel();
}}},_scale:function(P){var S=this.scroller.movable.scale;
var T=this._scaleToZoom(S);
var Q=new u.Point(P.center.x,P.center.y);
var N=this.viewToLocation(Q,T);
var O=this.locationToLayer(N,T);
var R=O.translate(-Q.x,-Q.y);
this._zoomAround(R,T);
this.trigger("zoomEnd",{originalEvent:P});
},_scaleToZoom:function(O){var N=this._layerSize()*O;
var P=N/this.options.minSize;
var Q=A.log(P)/A.log(2);
return A.round(Q);
},_reset:function(){if(this.attribution){this.attribution.filter(this.center(),this.zoom());
}this._viewOrigin=this._getOrigin(true);
this._resetScroller();
this.trigger("beforeReset");
this.trigger("reset");
},_resetScroller:function(){var P=this.scroller;
var S=P.dimensions.x;
var U=P.dimensions.y;
var O=this._layerSize();
var N=this.extent().nw;
var Q=this.locationToLayer(N).round();
P.movable.round=true;
P.reset();
P.userEvents.cancel();
var W=this.zoom();
P.dimensions.forcedMinScale=E(2,this.options.minZoom-W);
P.dimensions.maxScale=E(2,this.options.maxZoom-W);
var T={min:-Q.x,max:O-Q.x};
var V={min:-Q.y,max:O-Q.y};
if(this.options.wraparound){T.max=20*O;
T.min=-T.max;
}if(this.options.pannable===false){var R=this.viewSize();
T.min=V.min=0;
T.max=R.width;
V.max=R.height;
}S.makeVirtual();
U.makeVirtual();
S.virtualSize(T.min,T.max);
U.virtualSize(V.min,V.max);
this._virtualSize={x:T,y:V};
},_renderLayers:function(){var O=this.options.layers,R=this.layers=[],T=this.scrollWrap;
T.empty();
for(var P=0;
P<O.length;
P++){var S=O[P];
var U=S.type||"shape";
var N=this.options.layerDefaults[U];
var Q=m.map.layers[U];
R.push(new Q(this,n({},N,S)));
}},_layerSize:function(N){N=K(N,this.options.zoom);
return this.options.minSize*E(2,N);
},_click:function(O){if(!this._panComplete()){return;
}var N=this.eventOffset(O);
this.trigger("click",{originalEvent:O,location:this.viewToLocation(N)});
},_mousewheel:function(P){P.preventDefault();
var O=m.mwDelta(P)>0?-1:1;
var S=this.options;
var Q=this.zoom();
var V=w(Q+O,S.minZoom,S.maxZoom);
if(S.zoomable!==false&&V!==Q){if(!this.trigger("zoomStart",{originalEvent:P})){var N=this.eventOffset(P);
var R=this.viewToLocation(N);
var U=this.locationToLayer(R,V);
var T=U.translate(-N.x,-N.y);
this._zoomAround(T,V);
this.trigger("zoomEnd",{originalEvent:P});
}}}});
m.ui.plugin(z);
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.map",["kendo.data","kendo.userevents","kendo.tooltip","kendo.mobile.scroller","kendo.draganddrop","kendo.drawing","dataviz/map/location","dataviz/map/attribution","dataviz/map/navigator","dataviz/map/zoom","dataviz/map/crs","dataviz/map/layers/base","dataviz/map/layers/shape","dataviz/map/layers/bubble","dataviz/map/layers/tile","dataviz/map/layers/bing","dataviz/map/layers/marker","dataviz/map/main"],l);
}(function(){var k={id:"dataviz.map",name:"Map",category:"dataviz",description:"The Kendo DataViz Map displays spatial data",depends:["data","userevents","tooltip","dataviz.core","drawing","mobile.scroller"]};
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
