(function(b,a,e){var d=window.jQuery,c=window.$;
window.$=window.jQuery=a;
(function(g,f,j){var i=window.jQuery,h=window.$;
window.$=window.jQuery=f;
(function(l,k){k("util/main",["kendo.core"],l);
}(function(){(function(){var A=Math,x=window.kendo,p=x.deepExtend;
var s=A.PI/180,B=Number.MAX_VALUE,D=-Number.MAX_VALUE,W="undefined";
function q(Y){return typeof Y!==W;
}function P(aa,Z){var Y=G(Z);
return A.round(aa*Y)/Y;
}function G(Y){if(Y){return A.pow(10,Y);
}else{return 1;
}}function z(aa,Z,Y){return A.max(A.min(aa,Y),Z);
}function H(Y){return Y*s;
}function r(Y){return Y/s;
}function v(Y){return typeof Y==="number"&&!isNaN(Y);
}function X(Z,Y){return q(Z)?Z:Y;
}function T(Y){return Y*Y;
}function F(Z){var aa=[];
for(var Y in Z){aa.push(Y+Z[Y]);
}return aa.sort().join("");
}function t(aa){var Y=2166136261;
for(var Z=0;
Z<aa.length;
++Z){Y+=(Y<<1)+(Y<<4)+(Y<<7)+(Y<<8)+(Y<<24);
Y^=aa.charCodeAt(Z);
}return Y>>>0;
}function u(Y){return t(F(Y));
}var E=Date.now;
if(!E){E=function(){return new Date().getTime();
};
}function m(Y){var aa=Y.length,Z,ac=B,ab=D;
for(Z=0;
Z<aa;
Z++){ab=A.max(ab,Y[Z]);
ac=A.min(ac,Y[Z]);
}return{min:ac,max:ab};
}function o(Y){return m(Y).min;
}function n(Y){return m(Y).max;
}function S(Y){return Q(Y).min;
}function R(Y){return Q(Y).max;
}function Q(Y){var ac=B,ab=D;
for(var Z=0,aa=Y.length;
Z<aa;
Z++){var ad=Y[Z];
if(ad!==null&&isFinite(ad)){ac=A.min(ac,ad);
ab=A.max(ab,ad);
}}return{min:ac===B?j:ac,max:ab===D?j:ab};
}function y(Y){if(Y){return Y[Y.length-1];
}}function k(Y,Z){Y.push.apply(Y,Z);
return Y;
}function N(Y){return x.template(Y,{useWithBlock:false,paramName:"d"});
}function J(Y,Z){return q(Z)&&Z!==null?" "+Y+"='"+Z+"' ":"";
}function I(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){aa+=J(Y[Z][0],Y[Z][1]);
}return aa;
}function M(Y){var aa="";
for(var Z=0;
Z<Y.length;
Z++){var ab=Y[Z][1];
if(q(ab)){aa+=Y[Z][0]+":"+ab+";";
}}if(aa!==""){return aa;
}}function L(Y){if(typeof Y!=="string"){Y+="px";
}return Y;
}function K(aa){var ab=[];
if(aa){var Z=x.toHyphens(aa).split("-");
for(var Y=0;
Y<Z.length;
Y++){ab.push("k-pos-"+Z[Y]);
}}return ab.join(" ");
}function w(Y){return Y===""||Y===null||Y==="none"||Y==="transparent"||!q(Y);
}function l(Z){var Y={1:"i",10:"x",100:"c",2:"ii",20:"xx",200:"cc",3:"iii",30:"xxx",300:"ccc",4:"iv",40:"xl",400:"cd",5:"v",50:"l",500:"d",6:"vi",60:"lx",600:"dc",7:"vii",70:"lxx",700:"dcc",8:"viii",80:"lxxx",800:"dccc",9:"ix",90:"xc",900:"cm",1000:"m"};
var ab=[1000,900,800,700,600,500,400,300,200,100,90,80,70,60,50,40,30,20,10,9,8,7,6,5,4,3,2,1];
var aa="";
while(Z>0){if(Z<ab[0]){ab.shift();
}else{aa+=Y[ab[0]];
Z-=ab[0];
}}return aa;
}function O(ab){ab=ab.toLowerCase();
var Y={i:1,v:5,x:10,l:50,c:100,d:500,m:1000};
var ad=0,aa=0;
for(var Z=0;
Z<ab.length;
++Z){var ac=Y[ab.charAt(Z)];
if(!ac){return null;
}ad+=ac;
if(ac>aa){ad-=2*aa;
}aa=ac;
}return ad;
}function C(Z){var Y=Object.create(null);
return function(){var ab="";
for(var aa=arguments.length;
--aa>=0;
){ab+=":"+arguments[aa];
}if(ab in Y){return Y[ab];
}return Z.apply(this,arguments);
};
}function U(ac){var ab=[],Y=0,aa=ac.length,ad,Z;
while(Y<aa){ad=ac.charCodeAt(Y++);
if(ad>=55296&&ad<=56319&&Y<aa){Z=ac.charCodeAt(Y++);
if((Z&64512)==56320){ab.push(((ad&1023)<<10)+(Z&1023)+65536);
}else{ab.push(ad);
Y--;
}}else{ab.push(ad);
}}return ab;
}function V(Y){return Y.map(function(aa){var Z="";
if(aa>65535){aa-=65536;
Z+=String.fromCharCode(aa>>>10&1023|55296);
aa=56320|aa&1023;
}Z+=String.fromCharCode(aa);
return Z;
}).join("");
}p(x,{util:{MAX_NUM:B,MIN_NUM:D,append:k,arrayLimits:m,arrayMin:o,arrayMax:n,defined:q,deg:r,hashKey:t,hashObject:u,isNumber:v,isTransparent:w,last:y,limitValue:z,now:E,objectKey:F,round:P,rad:H,renderAttr:J,renderAllAttr:I,renderPos:K,renderSize:L,renderStyle:M,renderTemplate:N,sparseArrayLimits:Q,sparseArrayMin:S,sparseArrayMax:R,sqr:T,valueOrDefault:X,romanToArabic:O,arabicToRoman:l,memoize:C,ucs2encode:V,ucs2decode:U}});
x.drawing.util=x.util;
x.dataviz.util=x.util;
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/text-metrics",["kendo.core","util/main"],l);
}(function(){(function(k){var o=document,p=window.kendo,l=p.Class,u=p.util,n=u.defined;
var r=l.extend({init:function(w){this._size=w;
this._length=0;
this._map={};
},put:function(x,A){var y=this,z=y._map,w={key:x,value:A};
z[x]=w;
if(!y._head){y._head=y._tail=w;
}else{y._tail.newer=w;
w.older=y._tail;
y._tail=w;
}if(y._length>=y._size){z[y._head.key]=null;
y._head=y._head.newer;
y._head.older=null;
}else{y._length++;
}},get:function(x){var y=this,w=y._map[x];
if(w){if(w===y._head&&w!==y._tail){y._head=w.newer;
y._head.older=null;
}if(w!==y._tail){if(w.older){w.older.newer=w.newer;
w.newer.older=w.older;
}w.older=y._tail;
w.newer=null;
y._tail.newer=w;
y._tail=w;
}return w.value;
}}});
var m=k("<div style='position: absolute !important; top: -4000px !important; width: auto !important; height: auto !important;padding: 0 !important; margin: 0 !important; border: 0 !important;line-height: normal !important; visibility: hidden !important; white-space: nowrap!important;' />")[0];
function v(){return{width:0,height:0,baseline:0};
}var t=l.extend({init:function(w){this._cache=new r(1000);
this._initOptions(w);
},options:{baselineMarkerSize:1},measure:function(F,D,x){if(!F){return v();
}var E=u.objectKey(D),z=u.hashKey(F+E),y=this._cache.get(z);
if(y){return y;
}var C=v();
var B=x?x:m;
var w=this._baselineMarker().cloneNode(false);
for(var A in D){var G=D[A];
if(n(G)){B.style[A]=G;
}}k(B).text(F);
B.appendChild(w);
o.body.appendChild(B);
if((F+"").length){C.width=B.offsetWidth-this.options.baselineMarkerSize;
C.height=B.offsetHeight;
C.baseline=w.offsetTop+this.options.baselineMarkerSize;
}if(C.width>0&&C.height>0){this._cache.put(z,C);
}B.parentNode.removeChild(B);
return C;
},_baselineMarker:function(){return k("<div class='k-baseline-marker' style='display: inline-block; vertical-align: baseline;width: "+this.options.baselineMarkerSize+"px; height: "+this.options.baselineMarkerSize+"px;overflow: hidden;' />")[0];
}});
t.current=new t();
function s(y,x,w){return t.current.measure(y,x,w);
}function q(y,w){var z=[];
if(y.length>0&&document.fonts){try{z=y.map(function(A){return document.fonts.load(A);
});
}catch(x){p.logToConsole(x);
}Promise.all(z).then(w,w);
}else{w();
}}p.util.TextMetrics=t;
p.util.LRUCache=r;
p.util.loadFonts=q;
p.util.measureText=s;
}(window.kendo.jQuery));
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("util/base64",["util/main"],l);
}(function(){(function(){var o=window.kendo,k=o.deepExtend,n=String.fromCharCode;
var p="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
function l(y){var z="";
var q,r,s,t,u,v,w;
var x=0;
y=m(y);
while(x<y.length){q=y.charCodeAt(x++);
r=y.charCodeAt(x++);
s=y.charCodeAt(x++);
t=q>>2;
u=(q&3)<<4|r>>4;
v=(r&15)<<2|s>>6;
w=s&63;
if(isNaN(r)){v=w=64;
}else{if(isNaN(s)){w=64;
}}z=z+p.charAt(t)+p.charAt(u)+p.charAt(v)+p.charAt(w);
}return z;
}function m(s){var t="";
for(var r=0;
r<s.length;
r++){var q=s.charCodeAt(r);
if(q<128){t+=n(q);
}else{if(q<2048){t+=n(192|q>>>6);
t+=n(128|q&63);
}else{if(q<65536){t+=n(224|q>>>12);
t+=n(128|q>>>6&63);
t+=n(128|q&63);
}}}}return t;
}k(o.util,{encodeBase64:l,encodeUTF8:m});
}());
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("mixins/observers",["kendo.core"],l);
}(function(){(function(k){var o=Math,n=window.kendo,l=n.deepExtend,m=k.inArray;
var p={observers:function(){this._observers=this._observers||[];
return this._observers;
},addObserver:function(q){if(!this._observers){this._observers=[q];
}else{this._observers.push(q);
}return this;
},removeObserver:function(q){var s=this.observers();
var r=m(q,s);
if(r!=-1){s.splice(r,1);
}return this;
},trigger:function(s,q){var u=this._observers;
var t;
var r;
if(u&&!this._suspended){for(r=0;
r<u.length;
r++){t=u[r];
if(t[s]){t[s](q);
}}}return this;
},optionsChange:function(q){this.trigger("optionsChange",q);
},geometryChange:function(q){this.trigger("geometryChange",q);
},suspend:function(){this._suspended=(this._suspended||0)+1;
return this;
},resume:function(){this._suspended=o.max((this._suspended||0)-1,0);
return this;
},_observerField:function(q,r){if(this[q]){this[q].removeObserver(this);
}this[q]=r;
r.addObserver(this);
}};
l(n,{mixins:{ObserversMixin:p}});
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
(function(l,k){k("kendo.dataviz.treemap",["kendo.data","kendo.userevents","kendo.dataviz.themes"],l);
}(function(){var k={id:"dataviz.treeMap",name:"TreeMap",category:"dataviz",description:"The Kendo DataViz TreeMap",depends:["data","userevents","dataviz.themes"]};
(function(l,T){var E=Math,J=l.proxy,B=l.isArray,D=window.kendo,o=D.Class,V=D.ui.Widget,R=D.template,w=D.deepExtend,A=D.data.HierarchicalDataSource,z=D.getter,u=D.dataviz;
var I=".kendoTreeMap",n="change",t="dataBound",C="itemCreated",F=Number.MAX_VALUE,H="mouseover"+I,G="mouseleave"+I,U="undefined";
var S=V.extend({init:function(W,X){D.destroy(W);
l(W).empty();
V.fn.init.call(this,W,X);
this.wrapper=this.element;
this._initTheme(this.options);
this.element.addClass("k-widget k-treemap");
this._setLayout();
this._originalOptions=w({},this.options);
this._initDataSource();
this._attachEvents();
D.notify(this,u.ui);
},options:{name:"TreeMap",theme:"default",autoBind:true,textField:"text",valueField:"value",colorField:"color"},events:[t,C],_initTheme:function(W){var X=this,aa=u.ui.themes||{},Y=((W||{}).theme||"").toLowerCase(),Z=(aa[Y]||{}).treeMap;
X.options=w({},Z,W);
},_attachEvents:function(){this.element.on(H,J(this._mouseover,this)).on(G,J(this._mouseleave,this));
this._resizeHandler=J(this.resize,this,false);
D.onResize(this._resizeHandler);
},_setLayout:function(){if(this.options.type==="horizontal"){this._layout=new N(false);
this._view=new O(this,this.options);
}else{if(this.options.type==="vertical"){this._layout=new N(true);
this._view=new O(this,this.options);
}else{this._layout=new P();
this._view=new Q(this,this.options);
}}},_initDataSource:function(){var Y=this,X=Y.options,W=X.dataSource;
Y._dataChangeHandler=J(Y._onDataChange,Y);
Y.dataSource=A.create(W).bind(n,Y._dataChangeHandler);
if(W){if(Y.options.autoBind){Y.dataSource.fetch();
}}},setDataSource:function(W){var X=this;
X.dataSource.unbind(n,X._dataChangeHandler);
X.dataSource=W.bind(n,X._dataChangeHandler);
if(W){if(X.options.autoBind){X.dataSource.fetch();
}}},_onDataChange:function(W){var ab=W.node;
var aa=W.items;
var ac=this.options;
var Z,Y;
if(!ab){this._cleanItems();
this.element.empty();
Z=this._wrapItem(aa[0]);
this._layout.createRoot(Z,this.element.outerWidth(),this.element.outerHeight(),this.options.type==="vertical");
this._view.createRoot(Z);
this._root=Z;
this._colorIdx=0;
}else{if(aa.length){var ad=this._getByUid(ab.uid);
ad.children=[];
aa=new D.data.Query(aa)._sortForGrouping(ac.valueField,"desc");
for(Y=0;
Y<aa.length;
Y++){Z=aa[Y];
ad.children.push(this._wrapItem(Z));
}var X=this._view.htmlSize(ad);
this._layout.compute(ad.children,ad.coord,X);
this._setColors(ad.children);
this._view.render(ad);
}}for(Y=0;
Y<aa.length;
Y++){aa[Y].load();
}if(ab){this.trigger(t,{node:ab});
}},_cleanItems:function(){var W=this;
W.angular("cleanup",function(){return{elements:W.element.find(".k-leaf div,.k-treemap-title,.k-treemap-title-vertical")};
});
},_setColors:function(ac){var Z=this.options.colors;
var X=this._colorIdx;
var W=Z[X%Z.length];
var Y,ab;
if(B(W)){Y=r(W[0],W[1],ac.length);
}var ad=false;
for(var aa=0;
aa<ac.length;
aa++){ab=ac[aa];
if(!x(ab.color)){if(Y){ab.color=Y[aa];
}else{ab.color=W;
}}if(!ab.dataItem.hasChildren){ad=true;
}}if(ad){this._colorIdx++;
}},_contentSize:function(W){this.view.renderHeight(W);
},_wrapItem:function(W){var X={};
if(x(this.options.valueField)){X.value=y(this.options.valueField,W);
}if(x(this.options.colorField)){X.color=y(this.options.colorField,W);
}if(x(this.options.textField)){X.text=y(this.options.textField,W);
}X.level=W.level();
X.dataItem=W;
return X;
},_getByUid:function(Y){var X=[this._root];
var W;
while(X.length){W=X.pop();
if(W.dataItem.uid===Y){return W;
}if(W.children){X=X.concat(W.children);
}}},dataItem:function(X){var Y=l(X).attr(D.attr("uid")),W=this.dataSource;
return W&&W.getByUid(Y);
},findByUid:function(W){return this.element.find(".k-treemap-tile["+D.attr("uid")+"='"+W+"']");
},_mouseover:function(W){var X=l(W.target);
if(X.hasClass("k-leaf")){this._removeActiveState();
X.removeClass("k-state-hover").addClass("k-state-hover");
}},_removeActiveState:function(){this.element.find(".k-state-hover").removeClass("k-state-hover");
},_mouseleave:function(){this._removeActiveState();
},destroy:function(){V.fn.destroy.call(this);
this.element.off(I);
if(this.dataSource){this.dataSource.unbind(n,this._dataChangeHandler);
}this._root=null;
D.unbindResize(this._resizeHandler);
D.destroy(this.element);
},items:function(){return l();
},getSize:function(){return D.dimensions(this.element);
},_resize:function(){var X=this._root;
if(X){var W=this.element;
var Y=W.children();
X.coord.width=W.outerWidth();
X.coord.height=W.outerHeight();
Y.css({width:X.coord.width,height:X.coord.height});
this._resizeItems(X,Y);
}},_resizeItems:function(ab,Y){if(ab.children&&ab.children.length){var Z=Y.children(".k-treemap-wrap").children();
var W,X;
this._layout.compute(ab.children,ab.coord,{text:this._view.titleSize(ab,Y)});
for(var aa=0;
aa<ab.children.length;
aa++){W=ab.children[aa];
X=Z.filter("["+D.attr("uid")+"='"+W.dataItem.uid+"']");
this._view.setItemSize(W,X);
this._resizeItems(W,X);
}}},setOptions:function(X){var W=X.dataSource;
X.dataSource=T;
this._originalOptions=w(this._originalOptions,X);
this.options=w({},this._originalOptions);
this._setLayout();
this._initTheme(this.options);
V.fn._setEvents.call(this,X);
if(W){this.setDataSource(A.create(W));
}if(this.options.autoBind){this.dataSource.fetch();
}}});
var P=o.extend({createRoot:function(X,Y,W){X.coord={width:Y,height:W,top:0,left:0};
},leaf:function(W){return !W.children;
},layoutChildren:function(Z,W){var ac=W.width*W.height;
var ae=0,aa=[],Y;
for(Y=0;
Y<Z.length;
Y++){aa[Y]=parseFloat(Z[Y].value);
ae+=aa[Y];
}for(Y=0;
Y<aa.length;
Y++){Z[Y].area=ac*aa[Y]/ae;
}var ab=this.layoutHorizontal()?W.height:W.width;
var X=[Z[0]];
var ad=Z.slice(1);
this.squarify(ad,X,ab,W);
},squarify:function(Y,X,Z,W){this.computeDim(Y,X,Z,W);
},computeDim:function(ab,Z,ac,W){if(ab.length+Z.length==1){var X=ab.length==1?ab:Z;
this.layoutLast(X,ac,W);
return;
}if(ab.length>=2&&Z.length===0){Z=[ab[0]];
ab=ab.slice(1);
}if(ab.length===0){if(Z.length>0){this.layoutRow(Z,ac,W);
}return;
}var Y=ab[0];
if(this.worstAspectRatio(Z,ac)>=this.worstAspectRatio([Y].concat(Z),ac)){this.computeDim(ab.slice(1),Z.concat([Y]),ac,W);
}else{var aa=this.layoutRow(Z,ac,W);
this.computeDim(ab,[],aa.dim,aa);
}},layoutLast:function(X,Y,W){X[0].coord=W;
},layoutRow:function(X,Y,W){if(this.layoutHorizontal()){return this.layoutV(X,Y,W);
}else{return this.layoutH(X,Y,W);
}},orientation:"h",layoutVertical:function(){return this.orientation==="v";
},layoutHorizontal:function(){return this.orientation==="h";
},layoutChange:function(){this.orientation=this.layoutVertical()?"h":"v";
},worstAspectRatio:function(Z,ac){if(!Z||Z.length===0){return F;
}var X=0,aa=0,ab=F;
for(var Y=0;
Y<Z.length;
Y++){var W=Z[Y].area;
X+=W;
ab=ab<W?ab:W;
aa=aa>W?aa:W;
}return E.max(ac*ac*aa/(X*X),X*X/(ac*ac*ab));
},compute:function(W,Z,X){if(!(Z.width>=Z.height&&this.layoutHorizontal())){this.layoutChange();
}if(W&&W.length>0){var Y={width:Z.width,height:Z.height-X.text,top:0,left:0};
this.layoutChildren(W,Y);
}},layoutV:function(aa,ad,X){var ac=this._totalArea(aa),ab=0;
ad=M(ac/ad);
for(var Z=0;
Z<aa.length;
Z++){var Y=M(aa[Z].area/ad);
aa[Z].coord={height:Y,width:ad,top:X.top+ab,left:X.left};
ab+=Y;
}var W={height:X.height,width:X.width-ad,top:X.top,left:X.left+ad};
W.dim=E.min(W.width,W.height);
if(W.dim!=W.height){this.layoutChange();
}return W;
},layoutH:function(aa,ae,X){var ad=this._totalArea(aa);
var Y=M(ad/ae),ac=X.top,ab=0;
for(var Z=0;
Z<aa.length;
Z++){aa[Z].coord={height:Y,width:M(aa[Z].area/Y),top:ac,left:X.left+ab};
ab+=aa[Z].coord.width;
}var W={height:X.height-Y,width:X.width,top:X.top+Y,left:X.left};
W.dim=E.min(W.width,W.height);
if(W.dim!=W.width){this.layoutChange();
}return W;
},_totalArea:function(X){var Y=0;
for(var W=0;
W<X.length;
W++){Y+=X[W].area;
}return Y;
}});
var Q=o.extend({init:function(X,W){this.options=w({},this.options,W);
this.treeMap=X;
this.element=l(X.element);
this.offset=0;
},titleSize:function(X,W){var Y=W.children(".k-treemap-title");
return Y.height();
},htmlSize:function(X){var Y=this._getByUid(X.dataItem.uid);
var W={text:0};
if(X.children){this._clean(Y);
var Z=this._getText(X);
if(Z){var aa=this._createTitle(X);
Y.append(aa);
this._compile(aa,X.dataItem);
W.text=aa.height();
}Y.append(this._createWrap());
this.offset=(Y.outerWidth()-Y.innerWidth())/2;
}return W;
},_compile:function(X,W){this.treeMap.angular("compile",function(){return{elements:X,data:[{dataItem:W}]};
});
},_getByUid:function(W){return this.element.find(".k-treemap-tile["+D.attr("uid")+"='"+W+"']");
},render:function(aa){var ab=this._getByUid(aa.dataItem.uid);
var W=aa.children;
if(W){var ac=ab.find(".k-treemap-wrap");
for(var Y=0;
Y<W.length;
Y++){var Z=W[Y];
var X=this._createLeaf(Z);
ac.append(X);
this._compile(X.children(),Z.dataItem);
this.treeMap.trigger(C,{element:X});
}}},createRoot:function(X){var W=this._createLeaf(X);
this.element.append(W);
this._compile(W.children(),X.dataItem);
this.treeMap.trigger(C,{element:W});
},_clean:function(W){this.treeMap.angular("cleanup",function(){return{elements:W.children(":not(.k-treemap-wrap)")};
});
W.css("background-color","");
W.removeClass("k-leaf");
W.removeClass("k-inverse");
W.empty();
},_createLeaf:function(W){return this._createTile(W).css("background-color",W.color).addClass("k-leaf").toggleClass("k-inverse",this._tileColorBrightness(W)>180).append(l("<div></div>").html(this._getText(W)));
},_createTile:function(W){var X=l("<div class='k-treemap-tile'></div>");
this.setItemSize(W,X);
if(x(W.dataItem)&&x(W.dataItem.uid)){X.attr(D.attr("uid"),W.dataItem.uid);
}return X;
},_itemCoordinates:function(X){var W={width:X.coord.width,height:X.coord.height,left:X.coord.left,top:X.coord.top};
if(W.left&&this.offset){W.width+=this.offset*2;
}else{W.width+=this.offset;
}if(W.top){W.height+=this.offset*2;
}else{W.height+=this.offset;
}return W;
},setItemSize:function(Y,X){var W=this._itemCoordinates(Y);
X.css({width:W.width,height:W.height,left:W.left,top:W.top});
},_getText:function(W){var X=W.text;
if(this.options.template){X=this._renderTemplate(W);
}return X;
},_renderTemplate:function(W){var X=R(this.options.template);
return X({dataItem:W.dataItem,text:W.text});
},_createTitle:function(W){return l("<div class='k-treemap-title'></div>").append(l("<div></div>").html(this._getText(W)));
},_createWrap:function(){return l("<div class='k-treemap-wrap'></div>");
},_tileColorBrightness:function(W){return p(W.color);
}});
var N=o.extend({createRoot:function(X,Z,W,Y){X.coord={width:Z,height:W,top:0,left:0};
X.vertical=Y;
},init:function(W){this.vertical=W;
this.quotient=W?1:0;
},compute:function(W,aa,Y){if(W.length>0){var ab=aa.width;
var X=aa.height;
if(this.vertical){X-=Y.text;
}else{ab-=Y.text;
}var Z={width:ab,height:X,top:0,left:0};
this.layoutChildren(W,Z);
}},layoutChildren:function(Z,W){var ab=W.width*W.height;
var ac=0;
var aa=[];
var X;
for(X=0;
X<Z.length;
X++){var Y=Z[X];
aa[X]=parseFloat(Z[X].value);
ac+=aa[X];
Y.vertical=this.vertical;
}for(X=0;
X<aa.length;
X++){Z[X].area=ab*aa[X]/ac;
}this.sliceAndDice(Z,W);
},sliceAndDice:function(X,W){var Y=this._totalArea(X);
if(X[0].level%2===this.quotient){this.layoutHorizontal(X,W,Y);
}else{this.layoutVertical(X,W,Y);
}},layoutHorizontal:function(Z,W,ab){var aa=0;
for(var X=0;
X<Z.length;
X++){var Y=Z[X];
var ac=Y.area/(ab/W.width);
Y.coord={height:W.height,width:ac,top:W.top,left:W.left+aa};
aa+=ac;
}},layoutVertical:function(aa,W,ac){var ab=0;
for(var Y=0;
Y<aa.length;
Y++){var Z=aa[Y];
var X=Z.area/(ac/W.height);
Z.coord={height:X,width:W.width,top:W.top+ab,left:W.left};
ab+=X;
}},_totalArea:function(X){var Y=0;
for(var W=0;
W<X.length;
W++){Y+=X[W].area;
}return Y;
}});
var O=Q.extend({htmlSize:function(X){var Y=this._getByUid(X.dataItem.uid);
var W={text:0,offset:0};
if(X.children){this._clean(Y);
var Z=this._getText(X);
if(Z){var aa=this._createTitle(X);
Y.append(aa);
this._compile(aa,X.dataItem);
if(X.vertical){W.text=aa.height();
}else{W.text=aa.width();
}}Y.append(this._createWrap());
this.offset=(Y.outerWidth()-Y.innerWidth())/2;
}return W;
},titleSize:function(X,W){var Y;
if(X.vertical){Y=W.children(".k-treemap-title").height();
}else{Y=W.children(".k-treemap-title-vertical").width();
}return Y;
},_createTitle:function(W){var X;
if(W.vertical){X=l("<div class='k-treemap-title'></div>");
}else{X=l("<div class='k-treemap-title-vertical'></div>");
}return X.append(l("<div></div>").html(this._getText(W)));
}});
function y(W,Y){if(Y===null){return Y;
}var X=z(W,true);
return X(Y);
}function x(W){return typeof W!==U;
}function r(ac,aa,Z){var ad=K(ac);
var ab=K(aa);
var Y=p(ac)-p(aa)<0;
var W=[];
W.push(ac);
for(var X=0;
X<Z;
X++){var ae={r:q(ad.r,ab.r,X,Z,Y),g:q(ad.g,ab.g,X,Z,Y),b:q(ad.b,ab.b,X,Z,Y)};
W.push(m(ae));
}W.push(aa);
return W;
}function q(ad,ab,Y,aa,Z){var ae=E.min(E.abs(ad),E.abs(ab));
var ac=E.max(E.abs(ad),E.abs(ab));
var af=(ac-ae)/(aa+1);
var X=af*(Y+1);
var W;
if(Z){W=ae+X;
}else{W=ac-X;
}return W;
}function m(W){return"#"+v(W.r)+v(W.g)+v(W.b);
}function K(W){W=W.replace("#","");
var X=s(W);
return{r:L(X.r),g:L(X.g),b:L(X.b)};
}function v(W){var X=E.round(W).toString(16).toUpperCase();
if(X.length===1){X="0"+X;
}return X;
}function s(W){var X=W.length;
var Y={};
if(X===3){Y.r=W[0];
Y.g=W[1];
Y.b=W[2];
}else{Y.r=W.substring(0,2);
Y.g=W.substring(2,4);
Y.b=W.substring(4,6);
}return Y;
}function L(W){return parseInt(W.toString(16),16);
}function p(X){var W=0;
if(X){X=K(X);
W=E.sqrt(0.241*X.r*X.r+0.691*X.g*X.g+0.06800000000000001*X.b*X.b);
}return W;
}function M(X){var W=E.pow(10,4);
return E.round(X*W)/W;
}u.ui.plugin(S);
}(window.kendo.jQuery));
return window.kendo;
},typeof define=="function"&&define.amd?define:function(k,l,m){(m||l)();
}));
window.$=h;
window.jQuery=i;
})($telerik.$,$telerik.$);
window.$=c;
window.jQuery=d;
})($telerik.$,$telerik.$);
